### ISSUE TITLE
Crash browser when load large audio file

### ISSUE THREAD

**Issue by binal24** [katspaugh/wavesurfer.js#1001]
I'm trying to load a 1 hour podcast. When i am trying to play this file in Chrome browser, it crashes the page.
I have seen many users facing this issue. I have go through all issues, but can't find any proper solution.

So, please help me out with proper solution as soon as possible.

**Comment by mspae** [comment]
The browser crashes because it has to decode the whole file into memory to render the wave. This is a Lot of data for one hour of compressed audio.

You can fix this by predecoding the audio on the server and using the Media Element Backend.

**Comment by binal24** [comment]
Can you provide me some sample code for predecoding the audio on server?

**Comment by binal24** [comment]
I have more than 50 Mb size file.

**Comment by 1x-martin** [comment]
Here are some issues of people who had the same or similiar problems as you: https://github.com/katspaugh/wavesurfer.js/issues/839 https://github.com/katspaugh/wavesurfer.js/issues/488 https://github.com/katspaugh/wavesurfer.js/issues/316 https://github.com/katspaugh/wavesurfer.js/issues/493 https://github.com/katspaugh/wavesurfer.js/issues/2

**Comment by entonbiba** [comment]
@binal24 can you provide the podcast mp3 link?

**Comment by binal24** [comment]
I am suffering to create peaks. I have found this methods to create peaks array, node-pcm,ffmpeg,bbc/peaks.js,etc.
I am using bbc/peaks.js, but facing issues to create. 

So, anyone help me out to create peaks array using any other method?

**Comment by katspaugh** [comment]
@binal24 see the last section of the [FAQ](https://wavesurfer-js.org/faq/):

```
audiowaveform -i some-file.mp3 --pixels-per-second 10 -b 8 -o some-file.json
```

**Comment by binal24** [comment]
It doesn't works in windows system

**Comment by mspae** [comment]
Reference: https://github.com/bbc/audiowaveform/issues/23

@binal24 You could try https://github.com/jhurliman/node-pcm

I have also run into this issue (audiowaveform not running on windows) – I experimented a little but didn't come up with a definitite solution. You can find the code here: https://github.com/mspae/audiowavejs (Note that it's not functional or anything – but if you want to work on this problem yourself go ahead)

**Comment by binal24** [comment]
I have found solution instead of node-pcm, i am using "waveform-util". And its working fine for generating peak array.
https://www.npmjs.com/package/waveform-util

**Comment by 15838028035** [comment]
@mspae   have you slove it ? cloud you share your demo?

**Comment by 15838028035** [comment]
@binal24  have you test it ? memory up ?

**Comment by Liguo-Ma** [comment]
I can not load 1 hour wav file 
Also it is too slow to load waveform
How can I fix?

**Comment by marizuccara** [comment]
> I can not load 1 hour wav file
> Also it is too slow to load waveform
> How can I fix?

Hi you can use `MediaElementWebAudio` backend, which uses `MediaElementSourceNode` instead of `AudioBufferSourceNode`. In this way the data are not decoded in memory, because it uses as source the HTML5 audio tag instead of `AudioBuffer`. But with this backend you have to pass the peaks to draw the waveform.

**Comment by Liguo-Ma** [comment]
Hi Thanks very much for your reply.
Unfortunately I cannot understand.
I think you are saying I need json file for waveform
I tried to use bbc C++ json generator but I did not build github code.
Could you share exe file to gnerate jsonf file?
Thanks again

**Comment by marizuccara** [comment]
> Hi Thanks very much for your reply.
> Unfortunately I cannot understand.
> I think you are saying I need json file for waveform
> I tried to use bbc C++ json generator but I did not build github code.
> Could you share exe file to gnerate jsonf file?
> Thanks again

Hi, sorry but i don't use audiowaveform. You can try with ffmpeg.
Try google the necessary commands, for example:
https://stackoverflow.com/questions/41647492/get-waveform-data-from-audio-file-using-ffmpeg
