### ISSUE TITLE
"wavesurfer" is not defined

### ISSUE THREAD

**Issue by mthdvd** [katspaugh/wavesurfer.js#1003]
I get an Uncaught Reference Error: Wavesurfer is not defined when trying to render waveform in rails app. Gem is installed, div id is labeled.

Thank you for any help offered.

Apologies if this question reveals I'm the dumb kid in class.

**Comment by mspae** [comment]
Can you please provide us with the code you are using?

**Comment by mthdvd** [comment]
Thank you for the response.

**The code in my wavesurfer.js file in my Javascripts folder is:**

var wavesurfer = Object.create(WaveSurfer);

wavesurfer.init({
    container: document.querySelector('#waveform'),
    waveColor: 'violet',
    progressColor: 'purple'
});

wavesurfer.on('ready', function () {
    wavesurfer.play();
});

wavesurfer.load('file:///Users/mattdavid/Music/GarageBand/1_1_16%20-%204:21:16,%203.00%20PM.mp3');

**In my views file I have:**

<div id ="wavefrom"></div>

Thanks again.

**Comment by mthdvd** [comment]
forgot to mention -- application.js file contains:

//= require jquery
//= require jquery_ujs
//= require bootstrap
//= require turbolinks
//= require wavesurfer
//= require wavesurfer-plugins
//= require_tree .

**Comment by ToJen** [comment]
You could do this instead:

```
var wavesurfer = WaveSurfer.create({
    container: document.querySelector('#waveform'),
    waveColor: 'violet',
    progressColor: 'purple'
});
```

**Comment by entonbiba** [comment]
@mthdvd the rails gem of wavesurfer.js library is outdated. 

Try using the latest version with the code below in your app.
`https://cdnjs.cloudflare.com/ajax/libs/wavesurfer.js/1.3.2/wavesurfer.min.js`

````
var wavesurfer = WaveSurfer.create({
    container: '#waveform',
    waveColor: '#D2EDD4',
    progressColor: '#46B54D'
});

wavesurfer.on('ready', function () {
// code that runs after wavesurfer is ready
console.log('Success');
});

wavesurfer.load('https://ia800508.us.archive.org/15/items/LoveThemeFromTheGodfather/02LoveThemeFromTheGodfather.mp3');
````

**Comment by mthdvd** [comment]
Thank you for the suggestions. 

Code error went away, however, the "waveform" div is blank. The code under my layouts folder reads:
```

<!DOCTYPE html>
      
<head>

     <script src="https://cdnjs.cloudflare.com/ajax/libs/wavesurfer.js/1.3.2/wavesurfer.min.js">

         var wavesurfer = WaveSurfer.create({
        container: '#waveform',
        waveColor: 'violet',
       progressColor: 'purple'
      });

        wavesurfer.on('ready', function () {
      // code that runs after wavesurfer is ready
      console.log('Success');
      });

      wavesurfer.load('https://ia800508.us.archive.org/15/items/LoveThemeFromTheGodfather/02LoveThemeFromTheGodfather.mp3');

    
    </script>

</head>


<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="post_form">
        <%= render 'shared/post_form' %>
      </section>
    </aside>
  </div>

<div id = 'waveform'></div>

<% else %>

<div class="center jumbotron">

  <h1>Facebook 2 App</h1>

  <h2>
    Return of the Winklevossi.
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

</html>

<% end %>
```

**Comment by entonbiba** [comment]
@mthdvd it should be `<div id="waveform"></div>`.
