### ISSUE TITLE
Attaching a callback to region events

### ISSUE THREAD

**Issue by dimidd** [katspaugh/wavesurfer.js#1004]
Hi, I'm probably missing something very obvious, but how do you pass a custom callback to the regions plugin? E.g. I'd like to pass a function that will be called when `region-created` is fired. The docs for Regions, list the names of the events, but don't explain how to pass callbacks for them.
I've tried
```
        wavesurfer.enableDragSelection(
            {
              'region-created': function() {alert("created");}
            }
        );

 ```

Which had no effect.

**Comment by mspae** [comment]
You need to Listen to the Event: `wavesurfer.on('region-created', function(...`
