### ISSUE TITLE
How can I export the Wavesurfer-generated peaks? (rather than generate them server-side)

### ISSUE THREAD

**Issue by pmckelvy1** [katspaugh/wavesurfer.js#1010]
### Wavesurfer.js version(s):
1.3.2

### Browser version(s):
chrome 56

I have tried calling wavesurfer.exportImage() but it just tells me "this.drawer.getImage is not a function".
I have tried modifying the code / moving around some functions but I am getting similar undefined errors, and I feel like I shouldn't have to do much modifying to get this work.

Is there a way to easily grab the array of generated peaks so that I can export them to my server?  Am i initializing something incorrectly?

**note** i am having no problems loading audio, unloading it, playing it, etc...

**Comment by pmckelvy1** [comment]
also, using exportPCM works, but it gives me a long array full of null's and two 0's.

**Comment by thijstriemstra** [comment]
> I have tried calling wavesurfer.exportImage() but it just tells me "this.drawer.getImage is not a function".

It probably uses the default MultiCanvas backend and that doesn't implement getImage yet :(

`exportImage` will give you a bitmap normally, and I'm not sure how to export the points to the server.

**Comment by pmckelvy1** [comment]
@thijstriemstra do you know of a way to use something other than MultiCanvas that does implement getImage?

**Comment by pmckelvy1** [comment]
ended up using backend.getPeaks()

**Comment by batatop** [comment]
I had the same problem. You can solve it by firing the function inside the `wavesurfer.on('ready', function)` event.
