### ISSUE TITLE
Region - region.id

### ISSUE THREAD

**Issue by jj-quintin** [katspaugh/wavesurfer.js#1013]
Hello !

Thank you for this amazing app :-) 

I encounter a small problem with "wavesurfer.on('region-in', function (region)" I use to know which region is playing and so be able to display a series of corresponding information (subtitle, notes...) that I extract from an xml. Everything is perfect (id of the current region is correct) with a classic url (like http://somesite.com/somepage.html).

However, when calling the application with the url followed by parameters, like http://somesite.com/somepage.html?ID=5 (I need this to kwow the xml where I can find the url of the mp3, the regions, and so on, ), the very first region.id is always the number of the parameters (here "5") and the following region.id are something  like wavesurfer_s53sq0fl06o, wavesurfer_oerbr9apuv8, ...

The other infos are ok, for example : Start = 18 End = 23 Loop = false Drag = false Allow resize = false Color = hsla(200, 100%, 30%, 0.1), everything is perfect for that

thank you very much for your help

Wavesurfer.js version(s): 
https://cdnjs.cloudflare.com/ajax/libs/wavesurfer.js/1.3.0/wavesurfer.min.js
https://cdnjs.cloudflare.com/ajax/libs/wavesurfer.js/1.2.3/plugin/wavesurfer.regions.min.js

Browser version(s): Chrome (Version 56.0.2924.87)

Code needed to reproduce the issue: If needed, with pleasure :-)

**Comment by thijstriemstra** [comment]
@jj-quintin cant help you here but always try the latest wavesurfer (1.3.2) before reporting issues.

**Comment by mspae** [comment]
I won't know where the issue with the weird `5` region id is coming from but the `wafesurfer_xxx` type ids are intentionally created random ids by wavesurfer. They are created automatically if no custom ids are provided when adding a region.

**Comment by jj-quintin** [comment]
Thank you for those informations that helped me find the problem, which was on my side. Indeed, the id variables sent when creating the regions were undefined :-/ What surprised me is to have first id.region exactly the value of the parameter transmitted with the url of the application (I have to look on this weird stuff). Sorry for the inconvenience and thank you again for this great application
