### ISSUE TITLE
Ember.js Uncaught TypeError: Cannot set property 'fillStyle' of undefined

### ISSUE THREAD

**Issue by davidchalifoux** [katspaugh/wavesurfer.js#1014]
Hey, so I'm trying to use WaveSurfer within my Ember.js project with no prevail(I doubt Ember is causing these issues).

I imported the latest version of wavesurfer.js through Bower, and then used this exact code in one of my templates:
```
    <div id="waveform"></div>
    <script>
        var wavesurfer = WaveSurfer.create({
            container: '#waveform',
            waveColor: 'red',
            progressColor: 'purple'
        });
        wavesurfer.load('assets/sound4.mp3');
    </script>
```

Now when I try to see if it works, my console errors saying `Uncaught TypeError: Cannot set property 'fillStyle' of undefined`.

Here's what line in wavesurfer.js it's erroring at:

```
    setFillStyles: function (entry) {
        entry.waveCtx.fillStyle = this.params.waveColor; <--- HERE
        if (this.hasProgressCanvas) {
            entry.progressCtx.fillStyle = this.params.progressColor;
        }
    },
```

**Comment by thijstriemstra** [comment]
can you try to reproduce it without ember?

**Comment by davidchalifoux** [comment]
@thijstriemstra Actually I tested it out about 30min ago and got it to work. I wonder why it doesn't work within Ember?

**Comment by thijstriemstra** [comment]
I'm not familiar with ember.js but if you figure it out let us know here.

**Comment by davidchalifoux** [comment]
@thijstriemstra a user on StackOverflow sent me [this](https://github.com/katspaugh/wavesurfer.js/issues/950) discussion and I seem to be in the same boat somehow. I rolled back from 1.3.4 to 1.2.8 and it's working now. Any suggestions as to how I could get it to where I can be using the current versions?

**Comment by agamemnus** [comment]
@thijstriemstra I have the same problem, but I am not using Ember. Investigating...

**Comment by mspae** [comment]
Actually I think there was an issue a few months back somebody had while using ember. I think the cause was incorrect `for (entry in this.canvases)` (`this.canvases` being an array and not an object) https://github.com/katspaugh/wavesurfer.js/pull/961  and https://github.com/katspaugh/wavesurfer.js/issues/947 – Maybe this is related somehow.

**Comment by agamemnus** [comment]
Thank you. This was exactly the problem!

**Comment by davidchalifoux** [comment]
Hey, I just tried out the 2.0 beta and it's working great! Good work!
