### ISSUE TITLE
Wavesurfer doesn't reset mute state on next loaded source

### ISSUE THREAD

**Issue by tomasvilda** [katspaugh/wavesurfer.js#1040]
When I do

wavesurfer.load(file);
wavesurfer.play();

file is played with sound

wavesurfer.muteToggle();

now sound is muted

wavesurfer.load(nextfile);
wavesurfer.play();

file is played with sound (this is expected as I have loaded new file)

wavesurfer.muteToggle();

file is still played with sound (Wrong! as I see in source isMuted is not reset on load() method)

wavesurfer.muteToggle();

after second method call sound is muted.

**Comment by entonbiba** [comment]
@tomasvilda fixed in the pr
