### ISSUE TITLE
Cannot access mp3 files from FTP path

### ISSUE THREAD

**Issue by Agshealth-Raj** [katspaugh/wavesurfer.js#1042]
wavesurfer.load('ftp://xxxxxxxxx/0974420170202080243593.mp3');

its showing "No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://s.codepen.io' is therefore not allowed access.
"

Browser: Chrome 56.0.2924.87

**Comment by katspaugh** [comment]
It's not an issue with wavesurer.js, but a security policy in browsers.

**Comment by Agshealth-Raj** [comment]
is there any solution for that? also i dont know how to use loadBlob function?
Please help me...

**Comment by Agshealth-Raj** [comment]
i have configured mp3 files into my local host. 
"http://localhost/Web/1040520170203101234570.mp3" its showing same error.
