### ISSUE TITLE
How to get peaks with recommended Audiowaveform program?

### ISSUE THREAD

**Issue by ognjiscar** [katspaugh/wavesurfer.js#1047]
Hi. 
I understand  that loading prerendered image to load function requires an array of peaks, but cannot find out how to do it with recommended audiowaveform program. I get .png or .dat or whatever format, but don't know how to get peaks from these formats. Any advice?

Thanks for all the help.

**Comment by entonbiba** [comment]
@ognjiscar if you need to dynamicly generate the peaks data, you can use a server to generate it with php or even nodejs.

**Comment by ognjiscar** [comment]
I found the solution to my problem: In audiowaveform (bbc) program you get peaks data from 0-127. I normalized it (0-1 float ) and imported it into load function. Now it's working fine.

**Comment by BlazPerus** [comment]
@ognjiscar How did you normalize?

**Comment by ognjiscar** [comment]
Divide all numbers with maximum number in the table.

**Comment by gitdisrupt** [comment]
@ognjiscar i have been struggling with this ... id like to generate the peak data server side using PHP, but i am not having any luck :/ ... would you mind sharing how you achieved this? any help greatly appreciated
