### ISSUE TITLE
Invalid Software License Type

### ISSUE THREAD

**Issue by blakemurdock** [katspaugh/wavesurfer.js#1050]
#### Description
This software is under the Creative Commons Attribution 3.0 Unported license. However, it appears, upon further investigation into this license type, that this license is not intended for use with software. This license type is instead used for any type of “work,” as put in Creative Commons website, with the exception being computer software and hardware. 

Here is a link that states that the Creative Commons team recommends against using these license types for use with software:
https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software 

At the above link, the Creative Commons team gives some recommendations for software licenses. Some of the more popular choices are the GPL/LGPL license types. Here is a more comprehensive list: https://opensource.org/licenses 

The current license type prevents its use commercially without addressing source code distribution terms. If possible, I would like to place a high priority on this issue as it does hinder its use for all commercial software. Please let me know if there are any questions.

**Comment by tabascoeye** [comment]
I propose either Beerware License or the WTFPL

**Comment by thijstriemstra** [comment]
@katspaugh +1 for the MIT or BSD license

**Comment by katspaugh** [comment]
Let's go for BSD then.

**Comment by thijstriemstra** [comment]
other contributors all agree? any way we can ping all contributors at once? :)

**Comment by mspae** [comment]
:+1:

**Comment by entonbiba** [comment]
@katspaugh BSD 👍

**Comment by thijstriemstra** [comment]
@blakemurdock PRs welcome

**Comment by blakemurdock** [comment]
@thijstriemstra Alright. Sounds good. I'll get that in later today. Thanks guys.

**Comment by thijstriemstra** [comment]
Fixed with #1060.
