### ISSUE TITLE
Unable to get Audio From s3 Bucket

### ISSUE THREAD

**Issue by akradin** [katspaugh/wavesurfer.js#1051]
I am trying to get audio to be represented on my site via my AWS bucket. I think the reason I am having difficulty is probably related to the fact that I am a relatively new developer and I don't fully understand a lot of the issues that have already been opened.
That being said, I can create an ajax request to my bucket, but from there I am not sure what to do. I figured I could just reference my bucket directly using `wavesurfer.load` but this was unsuccessful. 
I do have the proper CORS configuration on my s3 bucket. Any help or redirection is much appreciated.
Chrome Version - 56.0.2924.87
Wavesurfer Version - 1.3.7

**Comment by akradin** [comment]
Nevermind, didn't realize `wavesurfer.load` kind of does its own ajax call using the link in s3.

**Comment by toweralaka** [comment]
Hello Akradin could you elaborate on how you fixed this, I have the same issue. Thank you!

**Comment by katspaugh** [comment]
Make sure to enable CORS. S3 has a preset for website hosting.
