### ISSUE TITLE
wavesurfer not rendering wav file from blobstorage in chrome

### ISSUE THREAD

**Issue by lararogu** [katspaugh/wavesurfer.js#1057]
I am trying to visualize a waveform from a .wav file stored in a blob container.I generate the SAS string and I get a uri that I pass to the wavesurfer.load( uri ) method. In firefox it works fine but in Chrome i get the exception unable to decode audio data.
uri=https://azureaccount.blob.core.windows.net/container/fileName.wav?sv=2016-05-31&sr............
wavesurfer.load(uri);
It happens the same if I store the file locally and I try to play it from my project folder. 
Any ideas?
Thanks

**Comment by thijstriemstra** [comment]
Can you load the blob directly using `loadBlob`: https://github.com/katspaugh/wavesurfer.js/blob/master/src/wavesurfer.js#L383

**Comment by lararogu** [comment]
I found out that the problem is that I have a 2KHz(sample rate) file and that Chrome is not able to decode it.It happens the same if I just try to play it using a html <audio> tag. In firefox it works fine. Any ideas on how to play a 2khz file in chrome,or how to resample it to make it work?

**Comment by thijstriemstra** [comment]
you can use ffmpeg to convert and resample it, see stackoverflow/google etc.

**Comment by CristianDeluxe** [comment]
I leave this in case it is useful for someone in the future, if the file is wav, when loading a blob with the latest version you must define the mime type, but I have found that if the mime type is audio/wav it does not play, but if we "force" it to audio/mpeg it does open:

```javascript
const mimeType = 'audio/wav'; // Your function to get the mime type

const blob = new window.Blob([new Uint8Array(buffer)], {
  // Try to force loading as mp3 if not supported
  type: MediaSource.isTypeSupported(mimeType)
    ? mimeType
    : 'audio/mpeg',
});

wavesurfer.loadBlob(blob).catch((error) => {
    console.error('Error loading audio', error);
});
```
