### ISSUE TITLE
Set bar spacing as well as width

### ISSUE THREAD

**Issue by iainhallam** [katspaugh/wavesurfer.js#1058]
Wavesurfer.js version(s): 1.3.2
Browser version(s): Firefox 52

I've got some good-looking waveforms being drawn as bars with the barWidth property, but I'd like to be able to set the space between the bars as well; would some kind of barSpace property be possible?

**Comment by thijstriemstra** [comment]
try and create a proposal in a pull request.

**Comment by iainhallam** [comment]
Looks like this could be added with some work in the drawBars function:

https://github.com/katspaugh/wavesurfer.js/blob/d2a1f38f1202187f42d4927977fe1af6c92d15a7/src/drawer.multicanvas.js#L229
