### ISSUE TITLE
Dragging Regions after initialisation to false

### ISSUE THREAD

**Issue by jawrainey** [katspaugh/wavesurfer.js#1062]
Hi all,

I would like to add regions that are by default not resizable or draggable. When a user requests to edit a region, then it will be made resizable/draggable programmatically. However, I could not make these regions resizable or draggable once they are initialised to false. Although there are ways around this (such as doing another pass after adding and setting these properties to false), this feels like the wrong approach.

I thought I would raise this issue before jumping into the codebase and proposing changes as **(1)** what I am trying to achieve may be expected behaviour, or **(2)** this is a known issue that I have not been able to find more details on or **(3)** I am using the API in an alternative way. 

I'm happy to contribute a PR after discussing this further if this is an issue 👍 

<hr>

### Source &amp; Browser versions

- **Wavesurfer.js:** 1.3.7
- **Wavesurfer.regions.js:** 1.3.7
- **Google Chrome:** Version 55.0.2883.95 (64-bit)
- **Firefox:** 52.0.2 (64-bit)

### Code needed to reproduce the issue:

- http://codepen.io/anon/pen/oZKdZd

### Use behaviour needed to reproduce the issue:

- Try dragging the first (green) region.

**Comment by entonbiba** [comment]
@jawrainey try this one

http://codepen.io/entonbiba/pen/mmOxmm 
```
wavesurfer.regions.list[2].drag = true;
wavesurfer.regions.list[2].resize = true;
```

**Comment by jawrainey** [comment]
@entonbiba, thanks for the response, though I think I did not describe the issue sufficiently! The issue is in relation to moving the first (green) region.

Changing these to true will only work because the object properties are not set (_drag_ & _resize_):

    wavesurfer.addRegion({id: 2, start: 28, end: 36, color: 'hsla(400, 100%, 30%, 0.1)'});

> @jawrainey try this one, it might be a bug with the .update() part of the plugin.

The update method works when the properties are not set when creating the object (as above):

    wavesurfer.regions.list[2].update({drag: false, resize: false});

The issue is that if these properties are not set, then I cannot update the region object to move the region. What's interesting is that the update method, or updating the properties manually as you have suggested does work, but does not have any affect!

http://codepen.io/anon/pen/oZKdZd

Note that the hover icon changes when trying to move the green region, and the properties are set the true

**Comment by entonbiba** [comment]
@jawrainey you should use `wavesurfer.region` instead of `wavesurfer.regions`

http://codepen.io/entonbiba/pen/zwZyOg
```
  wavesurfer.region.list[2].update({drag: false, resize: false});
  wavesurfer.region.list[1].update({drag: true, resize: true});  

```

**Comment by jawrainey** [comment]
Hi @entonbiba, the [documentation](https://wavesurfer-js.org/plugins/regions.html) suggestions using `wavesurfer.regions`, which works correctly in the codepen and when logging to the console. In your [example](http://codepen.io/entonbiba/pen/zwZyOg), although you set the second region to not be draggable/resizable, it can be dragged/resized.

Assuming we change these to `wavesurfer.regions`, then the first region can be moved and the second cannot, which illustrates that [update works](http://codepen.io/anon/pen/GmWaXb?editors=1010) correctly when no object properties are set for drag/resize when creating a region. However, the core problem I want to discuss and illustrate is that this update functionality does _not_ work if the drag/resize is set when creating a region:

    wavesurfer.addRegion({
      id: 1,
      start: 2, // time in seconds
      end: 5, // time in seconds
      color: 'hsla(100, 100%, 30%, 0.1)',
      drag: false,
      resize: false
    });

Updating the `drag/resize` options do not have any affect as I would expect, and this only occurs _because_ I have set defaults when creating the region as above:

    wavesurfer.regions.list[1].update({drag: true, resize: true});

**Comment by entonbiba** [comment]
@jawrainey yes the update method doesn't work because it doesn't do the following methods. I'll submit a pr to fix this.

http://codepen.io/entonbiba/pen/zwZyOg?editors=1010

```
this.bindInOut();
this.render();
```
