### ISSUE TITLE
Uncaught ReferenceError: wavesurfer is not defined ...

### ISSUE THREAD

**Issue by Agshealth-Raj** [katspaugh/wavesurfer.js#1063]
**Code Part :** 
```
 <div class="form-group_New">
            <div id="waveform"></div>
               <button class="btn btn-primary" onclick="wavesurfer.playPause()"> Play</button>
        </div>
```
**Scripts:**
```
var wavesurfer = WaveSurfer.create({
            container: '#waveform',
            waveColor: 'darkorange',
            progressColor: 'purple',
            splitChannels: true,
            height: 64
        });

        wavesurfer.load('https://wavesurfer-js.org/example/split-channels/stereo.mp3');
```

**Comment by Agshealth-Raj** [comment]
but i can see the wave form....

**Comment by mspae** [comment]
Please post a codepen so we can reproduce the error.

**Comment by entonbiba** [comment]
@Agshealth-Raj are you using the latest version of the library?

**Comment by RajPrime** [comment]
Its my mistake only. please close the issue..

**Comment by entonbiba** [comment]
@Agshealth-Raj put the wavesurfer.load code inside a wavesurfer ready event.

**Comment by romegab** [comment]
Hello. I have the same problem. Could somebody tell me exactly how to fix it?

**Comment by gbalamurugan** [comment]
I have same problem. 
I have tried with separe file and its working fine.. but same code is not working with in my application.. Please help.. Thanks in advance
