### ISSUE TITLE
Bad region dragging behaviour with cursor 

### ISSUE THREAD

**Issue by GianlucaCal** [katspaugh/wavesurfer.js#1064]
Hi, 

I noticed a problem in my project (which you can also see from here http://codepen.io/katspaugh/pen/obmOXV) when I drag or resize any region the cursor follow along. I fixed the resize behaviour by putting this code in the region plugin.

```
if (drag || resize) {
                   
                    if (resize==="end"){
                    my.wavesurfer.params.interact=false;
                    }

                    drag = false;
                    resize = false;
```
I could have putted `my.wavesurfer.params.interact=false;` right after the first `if` but then there would be no possibility to click inside the region. I noticed that there is no difference between drag or click event inside the region, could that be the problem??

Thanks

**Comment by entonbiba** [comment]
@GianlucaCal can you try with this sample and see if you experience the same issue.

http://codepen.io/entonbiba/pen/zwZyOg

**Comment by GianlucaCal** [comment]
not working either.

**Before dragging the region**

![1](https://cloud.githubusercontent.com/assets/24889920/25611508/a5397562-2f27-11e7-8850-b6e7e5a92d38.PNG)

**After dragging the regione the cursor follow**

![2](https://cloud.githubusercontent.com/assets/24889920/25611537/b99a0346-2f27-11e7-9967-142f55210f2f.PNG)

**Resizing the region the cursor follow the risize**

![3](https://cloud.githubusercontent.com/assets/24889920/25611555/c6b9e186-2f27-11e7-8eef-86867d06bec4.PNG)

**Comment by entonbiba** [comment]
@GianlucaCal yea I'll make it so when you drag it, it doesn't set the cursor on drag end.

**Comment by thijstriemstra** [comment]
#1295 seems to fix this, closing.
