### ISSUE TITLE
Tie to HTML5 Audio

### ISSUE THREAD

**Issue by scottgrobinson** [katspaugh/wavesurfer.js#1065]
Howdy!

Is it possible to 'tie' the waveform to a HTML5 audio widget? I've started playing around with it but I thought I'd ask first...

I'd like to use your waveform, but the controls available in the widget.

**Comment by entonbiba** [comment]
@scottgrobinson you can provide the waveform data in json format when loading the audio file in wavesurfer and use the `MediaElement` option. I think it's best to create your own custom controls to use with wavesurfer.

What audio widget is this?

**Comment by mspae** [comment]
If you use the media element backend and set the option `mediaControls` to true in the wavesurfer init parameters the controls should be rendered. They don't work perfectly with the waveform however.

**Comment by thijstriemstra** [comment]
Question answered, no feedback, closing.
