### ISSUE TITLE
Bind with node

### ISSUE THREAD

**Issue by jersobh** [katspaugh/wavesurfer.js#1066]
Hi there,

I'm trying without success to bind wavesurfer to an output node i've created, to change the gain. This is my code:

    window.wavesurfer = WaveSurfer.create({
      container: '#waveform',
      audioContext: this.audioCtx,
      backend: 'MediaElement',
      mediaType:'audio',
      normalize: true,
      height: 80,
      cursorColor: '#fff',
      waveColor: '#ff9800',
      progressColor: '#fff'
    });
  wavesurfer.on('ready', () => {

      this.playState.duration = parseInt(wavesurfer.getDuration());
      var musicGain = wavesurfer.backend.ac.createGain()
      musicGain.value = 1
      musicGain.connect(this.outputNode)

    });

But I'm getting:

Uncaught TypeError: Cannot read property 'createGain' of undefined

**Comment by entonbiba** [comment]
@jersobh 

try this,
```
var wavesurfer = WaveSurfer.create({
  container: '#waveform',
  normalize: true,
  height: 80,
  cursorColor: '#fff',
  waveColor: '#ff9800',
  progressColor: '#fff'
});

wavesurfer.on('ready', function () {
  this.playState.duration = parseInt(wavesurfer.getDuration());
  var musicGain = wavesurfer.backend.ac.createGain();
  musicGain.value = 1;
  musicGain.connect(this.outputNode);
});
```

**Comment by jersobh** [comment]
Nevermind. It's wavesurfer.backend.offlineAc.createGain()
