### ISSUE TITLE
Zooming in y-axis

### ISSUE THREAD

**Issue by lararogu** [katspaugh/wavesurfer.js#1068]
Right now I am doing it on the x-axis with the wavesurfer.zoom() method. I would like to do the same in both axis.

Is it possible to zoom in the waveform in the y-axis?.

thanks.

**Comment by entonbiba** [comment]
@lararogu what exactly will the y-axis zoom be useful for?

**Comment by lararogu** [comment]
I would like to see the waveform bigger,that it occupies most of the container.
Is it possible to define the size of the waveform before playing it?

**Comment by entonbiba** [comment]
@lararogu you can define the height of the waveform yes, but the width will remain responsive and up to the size of the device unless you specify the container as a set width.

`barHeight` parameter
http://codepen.io/entonbiba/pen/VpedWZ

**Comment by lararogu** [comment]
I am trying to use the barHeight parameter to change the wavefrom size.I downloaded the latest version of the source code but I am getting the following error when I create the waveform:

TypeError: Cannot read property 'extend' of undefined
    at Object.init (wavesurfer.js:46)
  init: function (params) {
        // Extract relevant parameters (or defaults)
        this.params = WaveSurfer.util.extend({}, this.defaultParams, params);

I have included the util.js file but seems like it doesnt find it,

Any ideas?

**Comment by entonbiba** [comment]
@lararogu you can do the following
```
  wavesurfer.params.barHeight=newnumbervalue;
  wavesurfer.empty();
  wavesurfer.drawBuffer();

```

**Comment by thijstriemstra** [comment]
No feedback, closing.
