### ISSUE TITLE
Waveform is only display after zooming

### ISSUE THREAD

**Issue by lararogu** [katspaugh/wavesurfer.js#1069]
I have a wav file played with wavesurfer. When I try to play it I can hear the file but the waveform is not displayed.
![image](https://cloud.githubusercontent.com/assets/15128912/25283054/bc6e17d8-26b2-11e7-9de2-c2d8946ab268.png)

It only appears after I change the zoom.
![image](https://cloud.githubusercontent.com/assets/15128912/25283077/d517aaec-26b2-11e7-9f43-848591fbb738.png)

Any ideas why is this happening?

**Comment by entonbiba** [comment]
@lararogu are you using the latest version?

**Comment by lararogu** [comment]
Yes,I have the latest version of the code. I dont understand because the file seems to be loaded fine because I hear it but the waveform is not displayed until I change the zoom.

**Comment by entonbiba** [comment]
@lararogu can you try the following sample I have created here,
http://codepen.io/entonbiba/pen/xgmqmv

**Comment by lararogu** [comment]
I fixed the problem.It was not a problem of the wavesurfer. I have the container for the waveform inside a modal that appears when I click a button and I was making it visible after I loaded the audio file,that is why it was not appearing immediately.
