### ISSUE TITLE
Seeking from ffmpeg pipe

### ISSUE THREAD

**Issue by jersobh** [katspaugh/wavesurfer.js#1070]
Hi there! 

I've created a seekable audio stream using a byte array with ffmpeg, but how can I use it on wavesurfer? 

Thanks in advance

**Comment by entonbiba** [comment]
@jersobh can you provide the code your using?

**Comment by jersobh** [comment]
My code doesn't have anything important, just this: 

  window.wavesurfer = WaveSurfer.create({
      container: '#waveform',
      audioContext: this.audioCtx,
      backend: 'MediaElement',
      mediaType:'audio',
      normalize: true,
      height: 80,
      cursorColor: '#fff',
      waveColor: '#ff9800',
      progressColor: '#fff'
    });



    wavesurfer.on('ready', () => {

      this.playState.duration = parseInt(wavesurfer.getDuration());
      // var musicGain = wavesurfer.backend.ac.createGain()
      // musicGain.value = 1
      // musicGain.connect(this.outputNode)

    });
    wavesurfer.on('seek', () => {
      //this.playState.currentTime = parseInt(wavesurfer.getCurrentTime());
    })
    wavesurfer.on('finish', () => {
      self.next();
    });


I just want to get the ffmpeg stream on http://localhost:8080 to use it with wavesurfer.. it's just a regular mp3 stream

**Comment by entonbiba** [comment]
@jersobh you can load the mp3 audio data with `wavesurfer.load(streamoutput)`, however it will only render whatever was outputted when it was loaded.

If you want to render a live stream audio, have a look at the microphone plugin. I'll look into creating a live audio stream plugin in the near future.

**Comment by jersobh** [comment]
But that would be like wavesurfer.load('http://localhost:8080')?

**Comment by jersobh** [comment]
I've been able to seek, but the wave doesn't show up :)

**Comment by jersobh** [comment]
Solved, the problem was on my stream :) Thank you bro
