### ISSUE TITLE
React js implementation

### ISSUE THREAD

**Issue by ricking06** [katspaugh/wavesurfer.js#1074]
Does this works with React js ?

**Comment by entonbiba** [comment]
@ricking06 haven't tried this library specifically, but you can try something like this following:

In your reactjs project folder where you have package.json install the library
`npm install wavesurfer.js`
then add it in the index.jsx with `import wavesurfer from 'wavesurfer.js'`

**Comment by mspae** [comment]
https://github.com/mspae/react-wavesurfer
