### ISSUE TITLE
How to create peaks from large files like more than 50 mb files?

### ISSUE THREAD

**Issue by RajPrime** [katspaugh/wavesurfer.js#1075]
Hi Creators,
i have to create peaks from large audio files. i read about this issue from your forum but i din't get any proper sample code. please help me. also i have an another doubt 
1. it is possible to show two channels using peaks?(i have channelA and ChannelB peaks data)
2. I am getting this error " XMLHttpRequest cannot load http://localhost/web/0668120170202121225743.mp3. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:50860' is therefore not allowed access. " while    wavesurfer.load('http://localhost/web/0668120170202121225743.mp3');

**Comment by entonbiba** [comment]
@RajPrime you can load the peaks data twice but you'll need to create the waveform twice. Do you want to load both peaks data on one waveform with channel A for top and channel B to bottom?

For the origin issue, you can download the cors plugin for google Chrome and enable it, this will fix it if your using Chrome. Or you can upload the files to a cdn or webhost and reference from there.

https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi?hl=en

**Comment by RajPrime** [comment]
yes, i want to display Channel A on top and Channel B in bottom.
"http://codepen.io/katspaugh/pen/ZQPaxB" please check this example. i need to display like that but using only peaks..

**Comment by entonbiba** [comment]
@RajPrime I will look into the splitChannels feature this weekend and see if I can add another option in there to display Channel A on top and B on bottom.

**Comment by RajPrime** [comment]
@entonbiba  Really great. thanks bro. also please do another help. i need to get peaks from audio file. please suggest any library files for that(i am using asp.net MVC with jquery)

**Comment by thijstriemstra** [comment]
Use the `audiowaveform` tool to generate peaks, see https://wavesurfer-js.org/faq/ for more info.
