### ISSUE TITLE
Issues In Xamarin Android Webview

### ISSUE THREAD

**Issue by codedammie** [katspaugh/wavesurfer.js#1079]
Greetings,
Have really enjoyed using wavesurfer.js for most of my projects but recently ran into hot waters when trying to load my web page in xamarin forms web view. After several modifications, it's now playing the songs but not loading the waveform.

**Comment by mspae** [comment]
Hello @codedammie Can you post your code somewhere?

**Comment by codedammie** [comment]
Thanks "mspae. Below are my codes:
The code for the page that's called in the webview is :
https://gist.github.com/codedammie/259e7bd9c25e9139279f6d462ce1d8e7

The code for the Xamarin Android webview is:
https://gist.github.com/codedammie/1f932aa7c8cd14975590eabf849e08ec

Thanks for the assist.

**Comment by entonbiba** [comment]
@codedammie try it with the latest version
