### ISSUE TITLE
Example for pre-rendered peaks doesn't actually show how to do it.

### ISSUE THREAD

**Issue by agamemnus** [katspaugh/wavesurfer.js#1082]
https://wavesurfer-js.org/example/audio-element/

It just says: `wavesurfer.load('example/media/demo.mp3');`. It doesn't show how one would add in the extra parameters.

**Comment by entonbiba** [comment]
@agamemnus those examples haven't been updated in a while. Sometime in the near future we will create more examples and link from the main page.
https://wavesurfer-js.org/examples/ 

For now you can check out this example I created for peak data.
http://codepen.io/entonbiba/pen/VPqvME

**Comment by agamemnus** [comment]
Thanks.

**Comment by agamemnus** [comment]
@entonbiba: I am also unsure how to save that peak data since the exportPCM doesn't work (https://github.com/katspaugh/wavesurfer.js/issues/1083). (I noticed you added a label -- thanks). I want to save the peaks with node.js as the audio files I am using are very big and I need the peaks to load much faster. Would appreciate any ideas.

**Comment by davidchalifoux** [comment]
+1 on the need for updated documentation.

**Comment by entonbiba** [comment]
@agamemnus you can use the following.
https://www.npmjs.com/package/audio-pcm-format

**Comment by agamemnus** [comment]
This is confusing.

What am I supposed to use https://www.npmjs.com/package/audio-pcm-format for?

In another thread/issue, someone mentioned https://github.com/bbc/audiowaveform to get the peaks. I don't know what audio-pcm-format is supposed to do or what exportPCM is supposed to do. If I am using audiowaveform, why do I need the others? I am very lost here.

**Comment by entonbiba** [comment]
@agamemnus that library is for nodejs didn't you ask for that? It will return the pcm json data from the serverside for faster rendering.

**Comment by agamemnus** [comment]
None of this really works how it should.
1) I do not know how to properly install the audiowaveform program.
2) I tried `audio-pcm-format`, but setting a sampleRate of 44100 gave me an out-of-memory error.
I tried a sampleRate of 50 and used the wavesurfer code, but the result had one or two big peaks that made the whole thing really small when normalized.

**Comment by agamemnus** [comment]
Okay. So I took the getPeaks code and I made it into a stream/chunk mechanism. I'm still improving on it and I'll post it later. Ideally, in the future, could just include wavesurfer.js and run getPeaks with a parameter...

**Comment by entonbiba** [comment]
@agamemnus what kind of ram/cpu are you running it on?

**Comment by thijstriemstra** [comment]
the `audio-element` shows how to do this now.

**Comment by purva15** [comment]
How can I create peaks from video mp4 file??

> @agamemnus those examples haven't been updated in a while. Sometime in the near future we will create more examples and link from the main page. https://wavesurfer-js.org/examples/
> 
> For now you can check out this example I created for peak data. http://codepen.io/entonbiba/pen/VPqvME

**Comment by jmcoder1** [comment]
> How can I create peaks from video mp4 file??
> 
> > @agamemnus those examples haven't been updated in a while. Sometime in the near future we will create more examples and link from the main page. https://wavesurfer-js.org/examples/
> > For now you can check out this example I created for peak data. http://codepen.io/entonbiba/pen/VPqvME

Did you get an answer  to this? I figured out how to get the audiobuffer, but not sure how to convert that to peak data.
