### ISSUE TITLE
wavesurfer.js selection point issue

### ISSUE THREAD

**Issue by wangzhaoming132** [katspaugh/wavesurfer.js#1085]
![Uploading QQ截图20170510215331.png…]()
On the choice of how to achieve, you can tell me how to achieve, thank you very much!

**Comment by wangzhaoming132** [comment]
![qq 20170510215331](https://cloud.githubusercontent.com/assets/19948422/25902461/293c17fc-35cc-11e7-8ab1-16cc9db6525e.jpg)

**Comment by wangzhaoming132** [comment]
![qq 20170510215331](https://cloud.githubusercontent.com/assets/19948422/25902492/412d2888-35cc-11e7-9416-8a2c1249fc4f.jpg)

**Comment by entonbiba** [comment]
@wangzhaoming132 are you using the latest version? Can you post some code on codepen?

**Comment by wangzhaoming132** [comment]
@entonbiba 
It's the latest version , The function I want to implement is the custom start position line.

 var wavesurfer = {};
	 
	 function wavesurferInit(data){
		 
		 var kwdEn = data.kwdEn;
		 wavesurfer = Object.create(WaveSurfer);
			
		 wavesurfer.init({
			  container: 'div.wave',
			  waveColor: 'violet',
			  progressColor: 'purple',
			  height: 128,
			  cursorColor: '#ff0000',
			  
			});
		 
		//语音路径
		var lenth = kwdEn.voicePath; 
	    wavesurfer.load('assets/avatars/000cebd0-158c-11e4-beec-5cf3fce34f00.wav');
	    
		wavesurfer.on('ready', function () {
			var lowpass = wavesurfer.backend.ac.createBiquadFilter();
			wavesurfer.backend.setFilter(lowpass);
		});
		
		//循环监听
		wavesurfer.on('ready', function () {
			  // Enable creating regions by dragging
			  wavesurfer.enableDragSelection({});
			  wavesurfer.play(18, 22);
			  // Add a couple of pre-defined regions
			  wavesurfer.addRegion({
			    start: 18, // time in seconds
			    end: 22, // time in seconds
			    drag: true,
			    
			    color: 'hsla(100, 100%, 30%, 0.1)'
			  });
		});
		
//		wavesurfer.on('region-update-end', function(region, event) {
//			  console.log("Region created - (backend startPos=" + wavesurfer.backend.startPosition+") and region start(region start = "+region.start+")");
//			  wavesurfer.backend.startPosition = region.start * wavesurfer.backend.startPosition;
//			  debugger
//			  wavesurfer.play(region.start , wavesurfer.backend.startPosition);//region.start * wavesurfer.backend.startPosition
//			  //event.stopPropagation();
//
//
//			});
		wavesurfer.on('region-click', function(region, event){
			 /* console.log("Region clicked:");
			  console.log("-- pos is " + wavesurfer.backend.startPosition);*/
			 // wavesurfer.seekTo(region.start);
			 // wavesurfer.backend.seekTo(region.start);
			  //wavesurfer.drawer.progress(region.start);
			  wavesurfer.backend.startPosition = region.start * wavesurfer.backend.startPosition;
			  wavesurfer.play(region.start , region.end);//region.start * wavesurfer.backend.startPosition
			  $('#starts').val(region.start);
			  $('#ends').val(region.end);
			  //event.stopPropagation();
			});
//		  wavesurfer.on('click', function(event){
//			  console.log("progress to ---");
//			});

			wavesurfer.on('region-dblclick', function(region, event){
			    region.remove();
			});

//			function removeAllRegions() {
//			  console.log("Clearing all regions - yay!");
//			  wavesurfer.clearRegions();
//			}

		
		//放大波形
		wavesurfer.on('ready', function () {
			var timeline = Object.create(WaveSurfer.Timeline);
			  timeline.init({
			    wavesurfer: wavesurfer,
			    container: '#waveform-timeline'
			  });
		});
		
		
		var slider = document.querySelector('#slider');
		
		slider.oninput = function () {
		  var zoomLevel = Number(slider.value);
		  wavesurfer.zoom(zoomLevel);
		}
		
		//时间显示
		var formatTime = function (time) {
		    return [
		        Math.floor((time % 3600) / 60), // minutes
		        ('00' + Math.floor(time % 60)).slice(-2) // seconds
		    ].join(':');
		};

		// Show current time
		wavesurfer.on('audioprocess', function () {
		    $('.waveform__counter').text( formatTime(wavesurfer.getCurrentTime()) );
		});

		// Show clip duration
		wavesurfer.on('ready', function () {
		    $('.waveform__duration').text( formatTime(wavesurfer.getDuration()) );
		});
		
		
		 // Drag'n'drop
	    var toggleActive = function (e, toggle) {
	        e.stopPropagation();
	        e.preventDefault();
	        toggle ? e.target.classList.add('wavesurfer-dragover') :
	            e.target.classList.remove('wavesurfer-dragover');
	    };
	 }

**Comment by thijstriemstra** [comment]
> The function I want to implement is the custom start position line.

I'm not sure what this means. Please re-open with a better description (if this is still an issue).

**Comment by wangzhaoming132** [comment]
> > 我想要实现的功能是自定义起始位置线。
> 
> 我不确定这意味着什么。请重新打开一个更好的描述（如果这仍然是一个问题）。



> > 我想要实现的功能是自定义起始位置线。
> 
> 我不确定这意味着什么。请重新打开一个更好的描述（如果这仍然是一个问题）。

This problem has already been solved. Thank you very much.
