### ISSUE TITLE
FireFox 53.0.2 Microphone plugin issue.

### ISSUE THREAD

**Issue by aaagepard** [katspaugh/wavesurfer.js#1089]
Wavesurfer.js microphone plugin doesnt works normally for me on example page - https://wavesurfer-js.org/plugins/microphone.html

After "Start the mic" click I see request to access the microphone and then no reaction on my voice, just horisontal line.

### Browser version(s):
FireFox 53.0.2 (32-bit)
Windows 7

![firefor videoaudio issue issue 147 collab-projectvideojs-record - google chrome](https://cloud.githubusercontent.com/assets/25985568/26024116/c91889c8-37d3-11e7-8579-1ea1be1f1133.jpg)

Works fine in Chrome.

**Comment by thijstriemstra** [comment]
can anyone reproduce this? @entonbiba?

**Comment by entonbiba** [comment]
@aaagepard @thijstriemstra I've updated the microphone sample, will test it on chrome since it's not working for me on chrome at the moment.
https://codepen.io/entonbiba/pen/ZKRgvZ

**Comment by aaagepard** [comment]
@entonbiba , new sample (https://codepen.io/entonbiba/pen/ZKRgvZ) works for me in Chrome 58.0.3029.110 (64-bit) Windows 7
But do not works in FireFox 53.0.2 (32-bit) Windows 7

**Comment by aaagepard** [comment]
Hello! Any news?

**Comment by aaagepard** [comment]
May be it will help.
I made some debug and got that in FF we cant got data from Channel when we are trying to redraw area.

if file wavesurfer.microphone.min.js::reloadBuffer I added this code 

```
/**
   * Redraw the waveform.
   */
  reloadBuffer: function(event) {

    console.log('reloadBuffer');
    console.log(event.inputBuffer.numberOfChannels);
    console.log(event.inputBuffer.getChannelData(0));

    if (!this.paused) {
      this.wavesurfer.empty();
      this.wavesurfer.loadDecodedBuffer(event.inputBuffer);
    }
  },
```

I got data in Chrome, 

![wavesurfer js - microphone plugin sample - google chrome](https://user-images.githubusercontent.com/25985568/27038772-9b1f1388-4f94-11e7-9d38-efd6fc394c56.jpg)


but empty arrays in FF

![wavesurfer js - microphone plugin sample - mozilla firefox](https://user-images.githubusercontent.com/25985568/27038722-78dbbaf6-4f94-11e7-87a8-b856063c9a54.jpg)

**Comment by thijstriemstra** [comment]
Can't reproduce it on firefox 53.0.3 on Ubuntu 16.04..

**Comment by aaagepard** [comment]
I tested on Windows 7.

**Comment by thijstriemstra** [comment]
Yea so it's an issue with that browser on that platform. Have you tried searching the firefox bugzilla for similar bug reports related to win/microphone?

**Comment by aaagepard** [comment]
seems there are no similar bug reports in bugzilla....

**Comment by thijstriemstra** [comment]
Can you reproduce it on other platforms? OSX? Eventually I would suggest opening a ticket in the firefox bugzilla..

**Comment by entonbiba** [comment]
@thijstriemstra  just tested on firefox 53.0.3 windows 10. 

@aaagepard
Go here and preview the mic code: https://www.entonbiba.com
Are you getting the following popup in firefox? Make sure your mic recording is turned on.
![image](https://user-images.githubusercontent.com/5193884/27057696-3b53f1f6-4f9b-11e7-9ad8-e0e2fefa679c.png)

![image](https://user-images.githubusercontent.com/5193884/27057727-5bab0700-4f9b-11e7-9306-d0e14d234559.png)


You should see the orange mic icon when you allow the mic on firefox.
![image](https://user-images.githubusercontent.com/5193884/27057750-7f7c4dc4-4f9b-11e7-802b-cd62ec977230.png)

**Comment by thijstriemstra** [comment]
@aaagepard is on windows 7 though..

**Comment by aaagepard** [comment]
@entonbiba yes, I got mic popup in FF.

![enton biba - codes - microphone plugin sample - mozilla firefox51616489489](https://user-images.githubusercontent.com/25985568/27080093-17882dde-5043-11e7-87bd-5bb7af63a02c.jpg)


Hm. I tested on other laptop with Windows 7 and FF 53.0.3 and it works FINE.  So it is very strange, why it dont work for my PC(but works in Chrome). will reinstall FF may be.

**Comment by thijstriemstra** [comment]
Good to hear.
