### ISSUE TITLE
move the website code to the master branch

### ISSUE THREAD

**Issue by agamemnus** [katspaugh/wavesurfer.js#1090]
https://wavesurfer-js.org/docs/events.html

"waveform-ready – Fires after the waveform is drawn when using the MediaElement backend. If your using the WebAudio backend you can use ready." ->
"waveform-ready – Fires after the waveform is drawn when using the MediaElement backend. If you're using the WebAudio backend, you can use ready."

**Comment by thijstriemstra** [comment]
can you create a pull request @agamemnus? Simply browse to the file in question on github and click the 'edit' button and save the changes.

**Comment by agamemnus** [comment]
K. Wasn't aware it was in the package.

**Comment by thijstriemstra** [comment]
checkout the `gh-pages` branch, or switch to it using the github web interface.

**Comment by thijstriemstra** [comment]
@katspaugh github now allows you to use `master` for github pages. Perhaps we should move the docs back to the master branch..

**Comment by katspaugh** [comment]
@thijstriemstra good idea!

**Comment by thijstriemstra** [comment]
> github now allows you to use master for github pages. Perhaps we should move the docs back to the master branch..

Perhaps something that can be done (or is already done) in v2.. @mspae?

**Comment by thijstriemstra** [comment]
Typo in docs looks fixed on the site. Should open a new ticket for moving docs into `master` branch.
