### ISSUE TITLE
Seeking broken when using 'MediaElement' backend. (2.0.0)

### ISSUE THREAD

**Issue by davidchalifoux** [katspaugh/wavesurfer.js#1093]
Hey, I recently checked wavesurfer to see if there was a new version that solved my bugs when using it with Ember.js. Luckily, the` 2.0.0` beta is working like a charm! However, since my project will most likely need to utilize pre-rendered waveforms, I decided to check out using `'Media Element'` as the backend.

Before changing the backend, I had a working waveform with a play-pause button. Now, after setting the backend(and yes adding the MediaElement files to my project) the seek ability seems to be broken.

If I wait for the waveform to load, and then play the audio file, it works as expected. However, if I try clicking a different point in the waveform, the audio file simply restarts from the beginning. Also, if I don't wait for the waveform to load to start the audio, trying to skip to another part once it's finished loading gives me the following error: `Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().`

I am not entirely sure this is a bug within wavesurfer or simply an error on my part, but some direction would be appreciated.

![image](http://dl.skuzzie.com/DP8ZV+)
Here's an example of the problem^

**Comment by entonbiba** [comment]
@davidchalifoux can you post the code on codepen?

**Comment by davidchalifoux** [comment]
@entonbiba hey, thanks for the reply. I just tested it out in a JSFiddle and got things to work. I have a suspicion that I accidentally included only `mediaelementplayer.js` instead of `mediaelement-and-player.js` I'm gonna go back and try it again within my project.

On a side note, do you have a suggestion for having only one sound be able to play at a time? If my project includes a feed of sounds should [this](http://stackoverflow.com/questions/20719550/play-one-html-audio-element-at-a-time) be fine or should I try a method that only uses one audio element? Thanks!

**Comment by BriceN** [comment]
@davidchalifoux I have this exact same problem, could you please explain how you resolve it ?

I don't get the "`mediaelementplayer.js` instead of `mediaelement-and-player.js`" part.

Thnaks !

**Comment by vatologic** [comment]
Same issue here. With WebAudio seeking works as expected - yet with the MediaElement as a backend every time I seek it plays from the beginning. The values of getDuration() and wavesurfer.progress are (weirdly enough) correct.
