### ISSUE TITLE
On minimap, the container parameter has no effect

### ISSUE THREAD

**Issue by puijob** [katspaugh/wavesurfer.js#1108]
On minimap, the container parameter has no effect, and the minimap is always created inside the main waveform container.

I've found a reference on this issue, but no answer:
https://github.com/katspaugh/wavesurfer.js/issues/954#issuecomment-276895818

**Comment by entonbiba** [comment]
@thijstriemstra shouldn't it be something like: 
`this.container = this.params.container || wavesurfer.drawer.params.container` ?
This way you can specify where you want the minimap to actually display and default with set it within the wavesurfer container?
