### ISSUE TITLE
toggleInteraction () --> should this be more specific?

### ISSUE THREAD

**Issue by agamemnus** [katspaugh/wavesurfer.js#1109]
I figure that maybe some plugins would like to use that state to determine if they should be running mouse events. But that needs specific code and it isn't implemented for e.g. the region plugin.

I was thinking that maybe there should be a separate command specifically to prevent the cursor from moving on click. That would help with the logic for my region plugin integration, since I don't want the cursor to move when I am editing regions.

**Comment by thijstriemstra** [comment]
PRs are welcome, please re-open with reference to PR nr.
