### ISSUE TITLE
Help Getting It To Work

### ISSUE THREAD

**Issue by laudmusic** [katspaugh/wavesurfer.js#1111]
Hello...

I'm new to this and trying to follow the turorials to get it to work and it doesn't render. Is there a step by step process that's available, more detailed than the pages you have?

Much appreciated. 

Thanks

Michael

**Comment by agamemnus** [comment]
I'd suggest that you try one of the codepen examples and slowly convert it to what you have. That way, you will find where you break it.

**Comment by entonbiba** [comment]
@laudmusic here are a few samples:

minimap
https://codepen.io/entonbiba/pen/ggeGyG

timeline
https://codepen.io/entonbiba/pen/xgmqmv

microphone
https://codepen.io/entonbiba/pen/ZKRgvZ
