### ISSUE TITLE
Stand Along Operation

### ISSUE THREAD

**Issue by laudmusic** [katspaugh/wavesurfer.js#1113]
Hello...

Looking to download all components and run on my local server (MAMP for testing at the moment). What do I need to download and amend in the code so it will not go outside my domain for dependencies? I want to work on this on my community in and do not have internet access during this time. 
Been trying to figure it out, but not working. 
Is there some dependence that also needs to be install on the root level of my server (i.e. ffmpeg)?

**Comment by entonbiba** [comment]
@laudmusic you can just download the files in the dist folder and reference those locally. 

https://github.com/katspaugh/wavesurfer.js/tree/master/dist
