### ISSUE TITLE
Re-declared unused argument in Spectrogram.resample

### ISSUE THREAD

**Issue by glebm** [katspaugh/wavesurfer.js#1134]
On [wavesurfer.spectrogram.js:300](https://github.com/katspaugh/wavesurfer.js/blob/d9f3394a808cb127c8ae07aed655a2ffc94c2397/plugin/wavesurfer.spectrogram.js#L300) the `columnsNumber` argument is re-declared:

```js
resample: function(oldMatrix, columnsNumber) {
    var columnsNumber = this.width;
```
I am not sure what the intent was here, but this prevents the code from compiling in TypeScript with the following error message:

```
ERROR - Redeclared variable: columnsNumber
```

**Comment by akreal** [comment]
I'm the original author of this function and I can't recall the details. This argument is not passed in function call now and I guess I used it during development and just forgot to remove it.

**Comment by glebm** [comment]
@akreal Thanks, sent #1135
