### ISSUE TITLE
Add wavesurfer-peakbuilder and gulp-wavesurfer-peakbuilder packages

### ISSUE THREAD

**Issue by benallfree** [katspaugh/wavesurfer.js#1139]
There is also a [wavesurfer-peakbuilder](https://github.com/benallfree/wavesurfer-peakbuilder) package for building peaks and a gulp package, [gulp-wavesurfer-peakbuilder](https://github.com/benallfree/gulp-wavesurfer-peakbuilder) to build JSON peak files.

This work with `audiowaveform` to convert its output into wavesurfer-compatible peaks.

**Comment by agamemnus** [comment]
I have had a lot of trouble getting audiowaveform to work on CentOS.

**Comment by benallfree** [comment]
@agamemnus The pcm package and a code sample would be a great addition to the waversurfer.js docs. I'm not clear if the sample rate and channel count needs to be known, or if it pcm can auto detect. 

My package auto-chunks based on how many peaks you want (default 300).

**Comment by thijstriemstra** [comment]
@benallfree add where? to the wiki? or include in the project?

**Comment by benallfree** [comment]
Sorry right. https://wavesurfer-js.org/projects/ says:

> If you like to include your project, drop us a line on GitHub.

That's what I was trying to do. 

I see now that `gh-pages` contains the site, so I'll just send a PR. We can close this ticket.
