### ISSUE TITLE
Web Audio Partial content (byte range requests) + preloaded peaks

### ISSUE THREAD

**Issue by matixmatix** [katspaugh/wavesurfer.js#1141]
I'm about to start implementing a music player with a waveform and I have these requirements:

- Passing pre-generated peaks for Web Audio (will be generated in the backend)
- Playing (seeking) should not need the whole file be downloaded, but rather issue Partial Content (206) requests to get only the range needed.

I read through the documentation and spend some time reading through issues, but some answers were several years old, so I'd like to know if Wavesurfer progressed to the point of having these two features. 

Thanks for making wavesurfer.js! 🙏

**Comment by agamemnus** [comment]
There are a few small bugs when loading with peaks but they are a mostly a nuisance... I have PRs for them in queue. My version is at https://github.com/agamemnus/wavesurfer.js/blob/master/dist/wavesurfer.js. In terms of peakgeneration, I'm currently working on refining my code, but just below you is another way: https://github.com/katspaugh/wavesurfer.js/issues/1139.

**Comment by matixmatix** [comment]
@agamemnus could you please explain these bugs (or link to PRs)?

Also, does preloading peaks and using Web Audio support partial content loading (when seeking/scrubbing)?

**Comment by agamemnus** [comment]
It seems to. Hard to explain the prs briefly. I'm actually still working on
some of them...

**Comment by matixmatix** [comment]
I successfully implemented this using `MediaElement` backend, using preloaded peaks using `audiowaveform` and some peaks post-processing and using CloudFront as a server.

**Comment by 15838028035** [comment]
is there a java server demo for generate peaks  @matixmatix

**Comment by 15838028035** [comment]
@matixmatix  cloud you share you successfully demo ?
