### ISSUE TITLE
Show time stamp when I hover mouse

### ISSUE THREAD

**Issue by sanjay-94** [katspaugh/wavesurfer.js#1143]
On my waveform, there is a cursor that shows the current progress of the audio. I want a second cursor to be shown when I hover over the waveform which shows the time stamp of the hovered position. Its exactly like the picture shown in this repository's markup image. The red cursor. How do I show a second cursor with the time stamp of the hovered position?

BTW this library is really cool! You are doing an amazing job!

**Comment by entonbiba** [comment]
@sanjaykumara1994 have a look at this sample, you can change it to make it display the time based on where the user hovers. 
https://codepen.io/entonbiba/pen/KaymLp

**Comment by sanjaykumara1994** [comment]
Hi @entonbiba ,
Thanks for the input. But I don't want the current audio time on the tooltip. I want the tooltip to show the hovered positions time. 
For example, suppose the audio is 4 mins long and the waveform cursor is at 13 seconds and progressing. Now i move my mouse pointer to the centre of the waveform. Then another waveform cursor should pop up with a tooltip showing the time at that point.

**Comment by Arkeyve** [comment]
You can use the `layerX` property of mouse events.

When mouse enters the waveform div, to get the time at the location cursor is present, compute `(event.layerX / wavesurfer.drawer.width) * wavesurfer.getDuration()`. You will get the time in seconds.

**Comment by tbogard** [comment]
I think I made it as part of the plugin cursor: https://github.com/katspaugh/wavesurfer.js/pull/1452
