### ISSUE TITLE
When providing preloaded peaks with MediaElement, the peaks are overwritten once the track loads entirely

### ISSUE THREAD

**Issue by matixmatix** [katspaugh/wavesurfer.js#1147]
I'm using wavesurfer.js 2.0.0-beta01, `MediaElement` as a backend, and providing preloaded peaks.

When the track starts playing, the provided peaks are shown OK. But after the whole track gets downloaded, peaks generated by wavesurfer.js are shown over preloaded peaks. 

I replicated the issue here: https://codepen.io/newjurgen/pen/KqvYxO (the track is around 20MBs, it can take a little while to load).

How can I prevent this behaviour? 

Thanks for making wavesurfer.js.

**Comment by matixmatix** [comment]
Seems it only happens with `MediaElement`. But I need this option because it enables partial content loading..

**Comment by matixmatix** [comment]
I solved the issue by adding a parameter when initializing: `forceDecode: false`. I thought this parameter defaults to  `false`? Looking at this code, it truly looks so: https://github.com/katspaugh/wavesurfer.js/blob/master/src/wavesurfer.js. But somehow the `forceDecode` gets the value `true`, even when leaving it out when initializing. Not sure how this happens, looks like a bug.

**Comment by thijstriemstra** [comment]
@entonbiba any idea?

**Comment by entonbiba** [comment]
@thijstriemstra it's actually set to true in version 2 by default, I don't see anywhere that it gets the parameter from the initialize. I'll create a pr with a proposed fix.

![image](https://user-images.githubusercontent.com/5193884/27801706-70600bde-5fed-11e7-8d04-52be02f7430e.png)

**Comment by mspae** [comment]
Fixed by the above PR once it's released.
