### ISSUE TITLE
Transparent background on canvas

### ISSUE THREAD

**Issue by arianestolfi** [katspaugh/wavesurfer.js#1149]
Hi!
can you tell please how to make a wavesurfer instance on a transparent canvas, 
as on the https://wavesurfer-js.org/ website?

thanks you a lot for developing this awesome tool!

A.

**Comment by entonbiba** [comment]
@arianestolfi by default it is transparent.

Here is an example.
https://codepen.io/entonbiba/pen/dRqYOP

**Comment by thijstriemstra** [comment]
No feedback, closing.
