### ISSUE TITLE
create a wavesurfer instance before the container exists?

### ISSUE THREAD

**Issue by piem** [katspaugh/wavesurfer.js#1156]
hi,

I'm using 2.0.0-beta01 from a react app.

This works well when calling `WaveSurfer.create` from `componentDidMount()`, which is called after `render()`.

``` ES6
import React from 'react';
import WaveSurfer from 'wavesurfer.js';

class WSComponent extends React.Component {
                                                                                                 
  render() {
    return (
      <div className="container">
        <div className="waveform">
        </div>
        <ChildComponent ws={this.ws} />
      </div>
    );
  }

  componentDidMount() {
    // create wavesurfer instance                                                                
    this.ws = WaveSurfer.create({                                                                
      container: '.waveform',
    });
  }

}

export default WSComponent;
```

But this prevents passing the wavesurfer instance to the children components. In the above case, `ChildComponent` will get `ws=null`.

Is there a way to (partially) create the instance before the container exists?

cheers, piem

**Comment by mspae** [comment]
The `container` parameter can also be an `HTMLElement`, you could try creating one with `document.createElement('div')`, passing that as container in `constructor` and then adding it in the render call.

Haven't tested this and it's not a very nice solution.

**Comment by mspae** [comment]
Also you could define `this.ws` in the constructor function of the component, pass it down to the children and simply assign it within the `componentDidMount` call. Since in JS all object variables are pass-by-reference not pass-by-value the reference the child component has will then be to the ws instance. You just need to make sure it checks before using any wavesurfer methods.

I'll close this for now. Please feel free to reopen if you have any difficulties.

**Comment by sorokinvj** [comment]
In case anyone needed WaveSurfer for React as badly as I am, I created this gist with the initialization of Waveform in the constructor.
Yes, it's not smooth, but working fine  https://gist.github.com/sorokinvj/6999dd1564156c3f6c078370314a3768

**Comment by sorokinvj** [comment]
@mspae Lots of people using React now, I would update the docs if I were you - this thing with impossibility of having instance of WaveSurfer in the render() could really depress decent people)

Thanks for WaveSurfer, indeed!
