### ISSUE TITLE
Importing the plugin directly in webpack doesn't work without an alias

### ISSUE THREAD

**Issue by raunofreiberg** [katspaugh/wavesurfer.js#1160]
Because the directory is called `wavesurfer.js` this causes some unwarranted action when trying to `import 'videojs-wavesurfer.js'` since it implies a JavaScript file. The fix is to add an alias to the `wavesurfer.js` directory under your webpack conf. Maybe consider changing the directory name by default so this doesn't cause issues in the first place.

**Comment by thijstriemstra** [comment]
The directory is called `wavesurfer.js` because it's the library name, something we can't change easily (and should be unnecessary, video.js for example also seems to work fine with their directory name). So many issues with webpack, blah.
