### ISSUE TITLE
loading wavesurfer from aws cloudfront url

### ISSUE THREAD

**Issue by tgeorge06** [katspaugh/wavesurfer.js#1161]
My issue is that my cloudfront url's are expiring before the audio is done playing.

My question is, after initial loading of the audio, what/why is it still trying to access the audio file from the cloudfront url?

**Comment by entonbiba** [comment]
@tgeorge06 may you provide an example of how you are using the library?

**Comment by tgeorge06** [comment]
`		this.wavesurfer = WaveSurfer.create({
			container: '#waveform',
			barWidth: 3,
			fillParent: true,
			normalize: true,
			scrollParent: true,
			backend: 'MediaElement',
			waveColor: '#cbf2ff',
			height: 100
		});
        
		this.wavesurfer.load(this.objSettings.strAudioURL);

		this.wavesurfer.on('ready', function () {
			objCallDetails.setDuration($('.length-time'));
            
			var timeline = Object.create(WaveSurfer.Timeline);
			timeline.init({
				wavesurfer: objCallDetails.wavesurfer,
				container: '.audio-wav-top'
			});

			if(objCallDetails.objSettings.blnRegionChart) objCallDetails.addRegions();
		});

		this.wavesurfer.on('loading', function (intPercent) {
			if(intPercent % 5 == 0)  $('.percent-loaded div').css('width', intPercent + '%');
			if(intPercent == 100)    $('.percent-loaded').fadeOut('slow');
		});`

**Comment by entonbiba** [comment]
@tgeorge06 you're using MediaElement which can load the metadata first and part of the audio as it plays. Try adding `preload: true;` which tells the browser that it should download the full audio.

Or

On amazon cloudfront create a behavior for audio files and change to TTL to 600 meaning 10 minutes.

**Comment by tgeorge06** [comment]
Thank you, i'll give the preload a try tomorrow and let you know.

**Comment by tgeorge06** [comment]
Well i've had the most success with the following

```
this.wavesurfer.load(this.objSettings.strAudioURL, null, 'auto');
```
I can see it actually loading the whole file now. The issue i am having now is when i skip forward (or it plays through overtime) it is still retrieving either metadata or waveform data from the cloudfront url.

**Comment by entonbiba** [comment]
@tgeorge06 webaudio needs to download the full audio first, how big is your audio file?

**Comment by tgeorge06** [comment]
@entonbiba 

around 60mb.

I've added `minPxPerSec = 3` and `pixelRatio = 1` to the options on longer audio files and just going to have to compress the .mp3's a little further and use WebAudio anyways.

I appreciate your help!
