### ISSUE TITLE
Double Audio / Play and Paused

### ISSUE THREAD

**Issue by Ethan0007** [katspaugh/wavesurfer.js#1166]
Hi,

I'm trying to implement wavesurfer in knockoutJS, I'm having issue when opening new dialog(with new audio) and clicking the play and paused button the audio from the previous dialog will still play and continue and now having double audio play in one player. How can i clear or dispose the previous audio? 

I implemented it through bindingHandlers.

#Thanks

**Comment by Ethan0007** [comment]
Hi,
This is solved the declaration of the var ws = Object.create(wavesurfer); its should be outside the init.

**Comment by mspae** [comment]
Please provide example code (preferably in a codepen or similiar) so we can better help. Thanks!

**Comment by Ethan0007** [comment]
Sir, @mspae this is already solved, it should be initialized outside on init function in binding handler.

**Comment by mspae** [comment]
:+1:
