### ISSUE TITLE
Determine size/time of viewed segment

### ISSUE THREAD

**Issue by Hokyjack** [katspaugh/wavesurfer.js#1170]
I would like to know if there is any way to determine the starting and ending time of currently viewed wave segment when using zoom/scrollbar.
I tried to compute the position of scrollbar but the the max value is not a full the total of canvas width. I am stuck.
Any idea how to implement this? 
![image](https://user-images.githubusercontent.com/8573741/28339650-19b4df0e-6c0d-11e7-8120-e7c81ff0fbef.png)

**Comment by thijstriemstra** [comment]
No feedback, closing.
