### ISSUE TITLE
load wave speed too slow

### ISSUE THREAD

**Issue by xiaoxiaodexueyin** [katspaugh/wavesurfer.js#1171]
hello,  
i load audio mp3/wav about 90M, it really need a lot of time to show the wave。but when i use <audio> tag，the speed is fast。perhaps the reason is wavesurfer download the audio?
do you have any good idea to resolve it? 

If there is a mistake, please forgive

**Comment by agamemnus** [comment]
You need to pre-generate the waves.

**Comment by xiaoxiaodexueyin** [comment]
i saw some other issues, they suggest pcm , wavesurfer-peakbuilder
but our project the audio is stored on another server......perhaps i have to download the audio first , then generate ....

**Comment by smohammedyasin** [comment]
i believe you need to generate peaks and store in database for each audio file. and on load you need to load peaks from servers

**Comment by markadrake** [comment]
Is there a tutorial or walkthrough of utilizing a package (could be software, could be node utility) to generate this waveform data?

**Comment by mspae** [comment]
you can use audiowaveform (https://github.com/bbc/audiowaveform) to generate peak data, for example like this:
```
audiowaveform -i some-file.mp3 --pixels-per-second 10 -b 8 -o some-file.json
```

**Comment by entonbiba** [comment]
@xiaoxiaodexueyin I'm working on a api service that will allow you to pull pregenerated waveforms, you can follow it here #1183

for now you'll have to do it on your own server.

**Comment by entonbiba** [comment]
once you have the peaks data you may load it like this
https://github.com/katspaugh/wavesurfer.js/issues/2058#issuecomment-761284236
