### ISSUE TITLE
What is the purpose of the following code?

### ISSUE THREAD

**Issue by agamemnus** [katspaugh/wavesurfer.js#1173]
https://github.com/katspaugh/wavesurfer.js/blob/master/src/wavesurfer.js#L705-L708:
````
// avoid draw wrong position while playing backward seeking
if (!paused) {
    this.backend.pause();
}
````

This code here pauses the backend (and then later plays it) when the user does a seek/when the code runs `seekTo`.

It runs the `audioprocess` event before the seek event is run. My code depends on the seek event being first (indicating a user-controlled move).

I would like to just put the play command after the seek event is fired (to preserve the functionality of an audioprocess running on a seekTo) and remove the pause command.

Would this break anything? The `avoid draw wrong position while playing backward seeking` comment doesn't make sense to me...

**Comment by agamemnus** [comment]
Also, since we are here, why does the seek click event run on a 0 timeout?:
````
// Click-to-seek
my.drawer.on('click', function (e, progress) {
    setTimeout(function () { my.seekTo(progress); }, 0);
});
````

**Comment by mspae** [comment]
The first snippet was originally introduced in #918 – it apparently fixes an issue with the MediaElement backend. (see the PR for a detailed description.

**Comment by mspae** [comment]
The second snippet was introduced in 8dcc397f62085237b48972e61f76e083f74587c6 – The commit message is "iOS" – no idea why it was added.

**Comment by mspae** [comment]
@agamemnus @thijstriemstra can we close this?

**Comment by agamemnus** [comment]
OK.

**Comment by agamemnus** [comment]
Second one: a fix for an iOS bug that might be fixed already? Might need testing.
