### ISSUE TITLE
Need to modify waveColor and progressColor after the player has initialized.

### ISSUE THREAD

**Issue by danielfaust** [katspaugh/wavesurfer.js#1178]
Is it possible to change the values of waveColor and progressColor after the player object has been created?

My problem is that the website background changes dynamically where under a certain condition it is bright and under another it is dark. This bright/dark change occurs with a button press. In that button handler I need to toggle the colors of the waveform from "rgba(0,0,0,0.3)" for the bright background and "rgba(255,255,255,0.3)" for the dark one.

Any ideas on how I can archive this?

**Comment by entonbiba** [comment]
@danielfaust can you link to the site?

**Comment by danielfaust** [comment]
@entonbiba Not currently, as it's under development in the intranet and the data it contains is personal.

Basically I track a bike ride and record audio at the same time.

When Google Maps is in ROAD `google.maps.MapTypeId.ROADMAP`, I need a dark waveform, when it is in `google.maps.MapTypeId.HYBRID` mode, I need a bright one.

Since the recordings are pretty long, rebuilding the entire wavesurfer.js object isn't that great. I need to switch the colors when I change the map type.

`google.maps.MapTypeId.ROADMAP`
![wavesurfer-road](https://user-images.githubusercontent.com/320098/28766461-f6e16566-75cf-11e7-9dfa-f032f673b630.png)

`google.maps.MapTypeId.HYBRID` Bad:
![wavesurfer-hybrid-bad](https://user-images.githubusercontent.com/320098/28766479-ff33a56c-75cf-11e7-862d-002dddac7a27.png)

`google.maps.MapTypeId.HYBRID` Good:
![wavesurfer-hybrid-good](https://user-images.githubusercontent.com/320098/28766490-074dfa90-75d0-11e7-8f28-eea4bb5ec544.png)

**Comment by SmileAppDev** [comment]
Would katspaugh answer to this question work? #864 
`wavesurfer.params.progressColor = 'red';
  wavesurfer.drawBuffer();`
Or would the drawBuffer cause too much to be redrawn?

**Comment by katspaugh** [comment]
Wow, that app looks cool. @danielfaust, out of curiosity, why do you record the audio while biking? A noise pollution research?

**Comment by danielfaust** [comment]
@SmileAppDev thanks, that works, but not on the minimap. I would need to change that too. Performance-wise `wavesurfer.drawBuffer();` is really good, but that may be because the non-minimap has a zoom factor of 20.

@katspaugh It's just for fun. I started with it because of the 5 ideas I had while riding the bike I only remembered about 2 of them. So I played with Tasker and Hi-Q MP3 Recorder and recorded one ride just to see if it's worth it. That then took me to create an FFT and think about the possiblilities of maybe analyzing my respiratory rate. So now I'm always recording it for the memos but also because I want to have that audio track in case I want to try the respiratory rate analysis thing. You can see the the breathing pretty good in the waveform, so possibly no FFT required there.

**Comment by thijstriemstra** [comment]
Use `wavesurfer.setProgressColor(color)` and `wavesurfer.setWaveColor(color)`.
