### ISSUE TITLE
 Error Cannot read property 'apply' of undefined during regionAdd() call

### ISSUE THREAD

**Issue by lukaszozimek** [katspaugh/wavesurfer.js#1184]
Hi, 
First of all thanks for this library 💯 

Currently I migrating my application form angular 1.6 to angular>4.0 I use our new 2.0.0-beta01 version. 

and getting error this error during call     this.surfer.addRegion(marker) :

`ERROR TypeError: Cannot read property 'apply' of undefined
    at vendor.bundle.js:92021
    at Array.forEach (<anonymous>)
    at t.value (vendor.bundle.js:92021)
    at e (vendor.bundle.js:91995)
    at e.value (vendor.bundle.js:91995)
    at t.addRegion (vendor.bundle.js:91995)
    at WaveSurferComponent.webpackJsonp.../../../../../src/app/components/common/wave-surfer/wave-surfer.component.ts.WaveSurferComponent.updateRegionObject (main.bundle.js:13166)
    at WaveSurferComponent.webpackJsonp.../../../../../src/app/components/common/wave-surfer/wave-surfer.component.ts.WaveSurferComponent.onKeyPress (main.bundle.js:13154)
    at Object.eval [as handleEvent] (ng:///LibraryModule/MediaItemEditComponent.ngfactory.js:124)
    at handleEvent (vendor.bundle.js:136586)`

### Wavesurfer.js version(s):
2.0.0-beta01

Other
Agnular : 4.2.6
zone.js: ^0.8.4

### Browser version(s):
 59.0.3071.115 (OSX)

### Use behaviour needed to reproduce the issue: 
```
`  private updateRegionObject(markerPressed: any) {
    if (this.surfer.regions.list[markerPressed.name] !== undefined) {
      this.surfer.regions.list[markerPressed.name].remove();
      var marker = this.createRegionObject(markerPressed.name, markerPressed.color);
      this.surfer.addRegion(marker);
    }
    else {
      var marker = this.createRegionObject(markerPressed.name, markerPressed.color);
      this.surfer.addRegion(marker);
    }
  }
 private createRegionObject(id, color) {
  return {
      id: id,
      start: this.surfer.getCurrentTime(),
      end: this.surfer.getCurrentTime() + 0.2,
      loop: false,
      drag: true,
      resize: false,
      color: color
     }
  };
'
```

**Comment by mspae** [comment]
I'm afraid you'll have to reproduce the issue in a codepen or similiar for us to be able to help you. It could be lots of things causing this issue.

You could also try and use the update method of the regions to accomplish what you are trying to do. (Instead of deleting and recreating them.) – No idea if this has anything to do with the issue, but would probably be a better way of doing it also for performance reasons:

```javascript
    if (this.surfer.regions.list[markerPressed.name] !== undefined) {
      // the id of the region never changes, so this isn't passed to the update function
      this.surfer.regions.list[markerPressed.name].update({
        color: markerPressed.color
      });
    } else {
      var marker = this.createRegionObject(markerPressed.name, markerPressed.color);
      this.surfer.addRegion(marker);
    }
```

**Comment by lukaszozimek** [comment]
@mspae  
Hi, I was on my holiday so I can't replay asap.
I found a problem .
The problem was wrong implementation of callback with  which doesn't pass region object to method.
So sorry for issue and please close it . 
Thanks for your pro tip 👍 

Btw  
When the next release is planed?

**Comment by mspae** [comment]
We try and release beta releases as often as possible and we're trying to move out of beta state as soon as possible. I think the policy can be described as: as soon as possible, as late as necessary ;)

Glad you found a solution!
