### ISSUE TITLE
Cordova - Load file from SD Card

### ISSUE THREAD

**Issue by mikael-onsilva** [katspaugh/wavesurfer.js#1185]
Hello there!

I'm developing a cross platform App using Cordova, and I'm tying to use the Wavesufer on it.
It's kind of a Music Player, based on Web Audio API (I'm not using Ionic or something like that).

The player is working fine loading the files from my Internal Storage.

Now I'm trying to draw the waveform from the audio file the user selects, but I'm not being able to.

Following the example from the docs page, I can draw the waveform from an audio file on a server.

```
var wavesurfer = WaveSurfer.create({
	container: '#wave',
	barWidth: 3
});

wavesurfer.load('http://ia902606.us.archive.org/35/items/shortpoetry_047_librivox/song_cjrg_teasdale_64kb.mp3');

wavesurfer.on('ready', function () {
    wavesurfer.play();
});

```
Is there a way to load a file like this?

`//wavesurfer.load('file:///storage/emulated/0/path/to/file.mp3');`

Thanks in advance!

**Comment by entonbiba** [comment]
@mikael-onsilva you can have a look at the cordova file plugin for more info. It really depends on the device file api. Using the cordova plugin file should help in cross platform.
https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-file/index.html
