### ISSUE TITLE
Possible to detect "loading from network" event using partial content (byte range) requests?

### ISSUE THREAD

**Issue by matixmatix** [katspaugh/wavesurfer.js#1186]
I'm using wavesurfer 2.0.0-beta01, with `MediaElement` backend and pre-prepared peaks.

When I start playing or seek somewhere in the middle of the track, partial content requests (http 206) for specified byte ranges are fired and the track can be played from anywhere with minimal waiting time. That works great!

However, on slower connections the time to start playing could be in a range of multiple seconds. In that time, I would like to display a simple loading spinner. Any idea how to capture these "loading" events?

**Comment by entonbiba** [comment]
@matixmatix you can use `loading` event to display the loading animation, or display the loading animation by default and then in the `canplay` event hide the loading animation.

**Comment by matixmatix** [comment]
These events don't seem to work with `MediaElement`. Any other ides?

**Comment by matixmatix** [comment]
Sorry, it works, but on the backend. Like this:

```
player.backend.on('canplay', () => {
});
```

Thanks!!
