### ISSUE TITLE
Wavesurfer as viewer

### ISSUE THREAD

**Issue by nuthinking** [katspaugh/wavesurfer.js#1187]
I already have an app which analyze the loaded sound through its AnalyserNode. I am wondering if I can use Wavesurfer simply as waveform viewer, without loading and playback capabilities.

Thanks!

**Comment by matixmatix** [comment]
Sure. Just use `MediaElement`, set `forceDecode: false`, have the preloaded peaks ready, and manually trigger render:

```
const trackUrl = ""; // Blank URL
player.load(trackUrl, peaks, 'none');
player.drawBuffer();
```

Tested in  2.0 beta.

**Comment by nuthinking** [comment]
what if I already have the buffer? Thanks!

**Comment by thijstriemstra** [comment]
@nuthinking check the microphone plugin, it shows how to load and draw a buffer.
