### ISSUE TITLE
How to add additional cursors at specific time?

### ISSUE THREAD

**Issue by thedoomx** [katspaugh/wavesurfer.js#1190]
Hello, what is the functionality that is used in the repository's readme screenshot?

I need to add a few of these cursors when the audio loads and display under or above them at what time they are.
They have to be static and different colors if possible.
https://ibb.co/iFj1XQ

Thanks

**Comment by mspae** [comment]
Check the code of the cursor  plugin how this can be achieved. https://github.com/katspaugh/wavesurfer.js/blob/master/src/plugin/cursor.js
