### ISSUE TITLE
addRegion doesn't return a region object

### ISSUE THREAD

**Issue by benfoley** [katspaugh/wavesurfer.js#1204]
According to the documentation, addRegion should return the new region. Using the 2.0.0-beta01 version, the following code logs `undefined`.

```
let region = this.wavesurfer.addRegion(params);
console.log(region);
``` 

Adding a return to the wavesurfer.regions.js file fixes this.. 
```
addRegion: function addRegion(options) {
    if (!this.initialisedPluginList.regions) {
        this.initPlugin('regions');
    }
    return this.regions.add(options);
},
```

**Comment by mspae** [comment]
@benfoley  Should be fixed by #1205 – Thanks for reporting!
