### ISSUE TITLE
Using wavesurfer.js as an audio player without rendering

### ISSUE THREAD

**Issue by floydback** [katspaugh/wavesurfer.js#1206]
Hi!

For a long time I'm looking for a good ES6 audio player with supports Web Audio API. I like wavesurfer.js codes a lot and I want to use it but there is no needs draw waveform in my player. So, is there way to turn off or deactivate Drawer class and what classes are no needed if I refrain from using Canvas WaveForm?

**Comment by infernocloud** [comment]
If you don't want the waveform, you can just use MediaElement.js

https://github.com/mediaelement/mediaelement/
http://www.mediaelementjs.com/

**Comment by mspae** [comment]
Closing. If you still have questions please comment and I'll reopen.

**Comment by neoscopio** [comment]
I have an use case where I want the waveform in some clips, and have other on the same page without.

I'm using "height: 0," parameter on the "create" event, and that works for us.

**Comment by Aparus** [comment]
I'm interested in this functionality too. 
I need player with WebAudio support. Especially I use Regions for playing them (phrases in audio book). But sometimes I need the Drawer for edit time intervals, and sometimes - I don't. But I suppose it takes extra time, calculation and device cpu resources ... 
Draw or not to Draw , that is the question. I suggest to include it to the API. I also will read info for contributors, may be I'll do it by myself ;-)
