### ISSUE TITLE
Break condition in drawLineToContext methode

### ISSUE THREAD

**Issue by GitHubRakeshSharma** [katspaugh/wavesurfer.js#1207]
Hi there,

I had an issue with zooming the waveform. The drawer suddenly stopped at some point. Interestingly it always stopped at the end (or the start) of a fully drawn canvas.
Changing the follwing code helped out:
` if (first > end || last < start) { return; }`

I turned it to
` if (first > last|| end < start) { return; }`

which now does not produce the malfunction.

Any comments?

**Comment by mspae** [comment]
@GitHubRakeshSharma Can you provide a codepen and exact steps to reproduce the issue? The playback stops?

**Comment by GitHubRakeshSharma** [comment]
unfortunately I cannot provide any code since I do not have it on my machine. But let me describe:
I have a panel with links to different audio files. You just choose your audio by clicking on it. When I zoom into a waveform and then change the selection of the audio the waveform (rendered from a peaks array) is only drawn up to a certain point. This will always be the end/start of one of the canvases added by the multicanvas drawer. When I changed the break condition mentioned above everything runs fine.
It might be possible, that the values that are compared were just mixed up since it compares an index to a length in px.

**Comment by awenger63** [comment]
@GitHubRakeshSharma See Zoom render issue in #1399, do you thinks it can be same problem ?

**Comment by thijstriemstra** [comment]
> unfortunately I cannot provide any code since I do not have it on my machine

Then we won't be able to reproduce this or fix it.
