### ISSUE TITLE
exportPCM() returns "[null, null, null, ..., 0, 0]"

### ISSUE THREAD

**Issue by xux9311** [katspaugh/wavesurfer.js#1212]
version 1.4.0
Is that correct?

**Comment by rAthur** [comment]
I have the exact same issue and none of the solutions I could find on internet helped, whatever I'm doing I have an array of _null_ ended bu twa 0... 

The _backend.getPeaks()_ function didn't help either, it gives me an array of _empty_ ended by two 0.
