### ISSUE TITLE
Spectrogram doubled canvas size

### ISSUE THREAD

**Issue by OctavioSI** [katspaugh/wavesurfer.js#1221]
Hi, thanks for this nice plugin! 

I am trying to implement wavesurfer in my ionic cordova app (Ionic 3), which loads my audio files fine. Now I am trying to use the spectrogram plugin. As you see below, spectrogram renders fine but it always streches the canvas to double its size (I've added a red border to my container for clarity purposes).

![screenshot_20171004-183346](https://user-images.githubusercontent.com/8326550/31201197-2a7d8188-a934-11e7-9aa7-d4960fb370b7.png)

I would like to discard this blank area below the spectrogram if possible. I've searched this in the issues, documentation and google, but I was not able to find anything related to that. My code to instantiate wavesurfer is pretty much standard:

`this.wavesurfer = WaveSurfer.create({
        container: '#waveform',
        progressColor: '#5b6570',
        waveColor: '#CCCCCC',
        cursorColor: 'transparent',
        height:100,
        normalize:true,
        plugins: [
            SpectrogramPlugin.create({
                container: "#wave-spectrogram",
                labels: true
            })
        ]
      });`

Any thoughts? Thanks in advance.

**Comment by thijstriemstra** [comment]
@mspae you marked it as a bug, were you able to reproduce this in a non-cordava app? Do we even support that platform?

**Comment by mspae** [comment]
@thijstriemstra I didn't reproduce. But it sounded like something that would happen regardless of the plattform. Having said that: I should have reproduced before adding that label.

@OctavioSI Can you create a codepen with a reproduction of the issue?

**Comment by OctavioSI** [comment]
@mspae Sorry about being late on this issue, but I am struggling quite a bit to make wavesurfer.js work with plunkr (my code is there, but wavesurfer.js not working yet -- https://embed.plnkr.co/DCcXPa/). I've tried codepen but it seems far more complicated to replicate my code there. 

Also, I've tried to implement the changes made in #1231 but the problem remains.

I will try to fix the plunkr to showcase the error and let you know. Thanks!

**Comment by thijstriemstra** [comment]
PR was merged to master.

**Comment by thijstriemstra** [comment]
> PR was merged to master.

Please open report a new issue if the problem still remains (add ref to this issue as well).

**Comment by panosl** [comment]
It does not have a blank space anymore, true. But still the height of the spectrogram is half of that rendered on non retina display.
