### ISSUE TITLE
WAV file length and peaks drawing mismatch issue compared to MP3

### ISSUE THREAD

**Issue by X-Raym** [katspaugh/wavesurfer.js#1223]
Hi !

I detected a problem with wav file length and peak drawing. It appears that the wav version of a file with Media Element will not be played until the end.
Also, the waveform seems offset a bit to the left for the wave file. Here is a picture.

![image](https://monosnap.com/file/V6Iw7wqtHGOCeyNFwXyK4NRJN5gIFG.png)

Can someone confirm this issue ?

Confusing thing, the length of the two files analyses in a DAW shows 3.244... like the wav version but not the mp3 one... so maybe the problem is with the mp3, but it is not the one who seems buggy with play cursor.

Maybe we have two different but intoxicated issue there.

### Wavesurfer.js version(s):
2.0.0 beta 2

### Browser version(s):

FireFox 56

**Comment by entonbiba** [comment]
@X-Raym I fixed the length issue in #941  , just checked V2 and the code seems fine. Can you post the sample code or the audio ? I'll check it against the old version here.
https://codepen.io/entonbiba/pen/apVaJM

**Comment by X-Raym** [comment]
@entonbiba 

- [Oringal WAV](https://www.dropbox.com/s/ndn37c6p9bo6wfn/AnaFeed_liquid_03.wav?dl=0)
- [MP3 conversion](https://www.dropbox.com/s/m4clm03cuyjsxb8/AnaFeed_liquid_03.mp3?dl=0)

The length is 3.2449659863946 for both file according to an external analyzer.

Thanks for taking a look !

**Comment by X-Raym** [comment]
@entonbiba Hi ! Did you have the opportunity to test with the files I sent you ?

**Comment by thijstriemstra** [comment]
@X-Raym is this still the case with 2.0.4 or newer?

**Comment by X-Raym** [comment]
@thijstriemstra Maybe I should create a CodePen pen for that.

Isn't there any CDN delivering the v2.0.4 ?

As it the dist script isn't on GitHub anymore, I can't link it to it with GitHub CDN.

**Comment by thijstriemstra** [comment]
No not yet, see https://github.com/cdnjs/cdnjs/pull/12532 In that pull request you can also find the 2.0.4 dist files.

**Comment by X-Raym** [comment]
@thijstriemstra Yes, but still there.

https://codepen.io/X-Raym/pen/VQRmwo

**Comment by X-Raym** [comment]
@thijstriemstra Yes, bug still there.

https://codepen.io/X-Raym/pen/VQRmwo

**Comment by billlanders** [comment]
Workaround = set the WaveSurfer option **forceDecode=true**.

**Comment by ICYMYM** [comment]
@X-Raym   @thijstriemstra  @entonbiba  I encountered a similar problem, I have an mp3 file with duration 1:00:04, but when I use "MediaElement" and play it,  its duration is about 6 seconds(1:00:10) longer than the actual. But I get the correct duration when I call  "getDuration()", it's weird. I try other mp3 files, they have the same problem.

After initialization, its duartion is 1:00:04,
![image](https://user-images.githubusercontent.com/3919539/69931510-85f89480-1502-11ea-9538-f33ab3b2dd60.png)

When the playback ends, its duration changed to 1:00:10: 
![image](https://user-images.githubusercontent.com/3919539/69931556-ade7f800-1502-11ea-9974-43de639e6510.png)

The code:
```
wave = WaveSurfer.create({
            container: "#waveform",

            barWidth: 2,
            normalize: true,
            closeAudioContext: true,
            
            backend: "MediaElement", //"WebAudio",
            plugins: [
                WaveSurfer.timeline.create({
                    container: "#waveform-timeline"
                })
            ]
        });
```

The mp3 file you could get from here: https://drive.google.com/file/d/1rcbvcFHNqOakD4vsrI7sJ3ymFPrviucK/view

**Comment by entonbiba** [comment]
@X-Raym @ICYMYM not able to replicate with latest version 4.4.0 see sample here:
https://www.entonbiba.com/lab/wavesurfer/1223.html 

the mp3 file needs CORS headers enabled, so we can test it from the source,

reopen this ticket if issue persists.

**Comment by X-Raym** [comment]
@entonbiba just to be clear, have you only tried with providen link ? cause these were not link dor direct tries, but for uploading on test platforms of choice.
So if is just a matter of putting them a on a server with core to allow testing let me know,
but if this the case, please reopen the issue, as I need to keep track to what is still an issue - I have no reopen issue button. Thx !

**Comment by X-Raym** [comment]
@entonbiba Ok I didnt noticed you replicate the issue on this link. Thx ! SO I guess it is solved; I'll try later. Best,

**Comment by entonbiba** [comment]
@X-Raym no problem,

**Comment by candilora28** [comment]
Just FYI, mp3 encoders insert random bits of silence at the beginning of a track. This isn't a bug, this is just how .mp3 encoders function.

**Comment by X-Raym** [comment]
@candilora28 this wasn't the issue there: It was not just random bit in a mp3, it was play cursor being stoped before the end of the sound in the wav. You can see that wavesurfer decoded audio information post last play cursor position on the wav file, so this info exist. It was a play bug.
Also, both file analyzed in other software shows the same file duration, so it is not encoding error.

BTW, I dont know if this bug is still happening.
