### ISSUE TITLE
Bugs with timeline rendering when using the dynamic plugin API/loading new files

### ISSUE THREAD

**Issue by samyoung88** [katspaugh/wavesurfer.js#1226]
Currently initializing Timeline plugin on render. It will show when playing/loading the first track but when selecting next track it disappears, but it will reappear when I resize the browser. In a list of tracks, when clicking individually some will show the timeline canvas and some will not. Please advise.

**Comment by GitHubRakeshSharma** [comment]
I had some similar issue. Each time I selected a new audio the timeline plugin would append a new canvas to the previous timeline canvas. so each time I call the load function i call this code as well:

```
const timeLineContainer = document.getElementById('_DIV_TIMELINE');
        if (timeLineContainer) {
            while (timeLineContainer.hasChildNodes()) {
                timeLineContainer.removeChild(timeLineContainer.lastChild);
            }
        }
```

hope that solves your issue!

**Comment by samyoung88** [comment]
This didn't work for me. But I found that the problem is in the plugin where the `backend.getDuration()` returns an NaN, so the canvas is not getting drawn.

**Comment by mspae** [comment]
Can you provide a code example?

**Comment by mspae** [comment]
@samyoung88 @GitHubRakeshSharma  – I think you are both experiencing different bugs. I'm currently putting together a PR on this. The bugs are:

- Loading a new file/rerendering the timeline does not clear the timeline container from old timeline canvases
- Dynamically loading the timeline plugin with new files does not render correctly in some cases
