### ISSUE TITLE
How i can pause all players after play one?

### ISSUE THREAD

**Issue by myuksektepe** [katspaugh/wavesurfer.js#1227]
Hello,

First of all I would say that it is not as good as English language ability.

I want the other active one to be paused when a player starts playing. I did some research, but I could not find a code.

Also, when I want to use it more than once in a page, I use it like this;

```
var ses001 = WaveSurfer.create ({container: '# ses001', waveColor: '# afafaf', progressColor: '# dd3333', height: '40', hideScrollbar: true, cursorWidth: 0, barWidth: 1,});
ses001.load ( 'assets / sounds / demo.mp3');

var ses002 = WaveSurfer.create ({container: '# ses002', waveColor: '# afafaf', progressColor: '# dd3333', height: '40', hideScrollbar: true, cursorWidth: 0, barWidth: 1,
ses002.load ( 'assets / sounds / baglar_gazoz_jingle.mp3');
```

does this have a shorter method for multi players have some options?

**Comment by mspae** [comment]
@myuksektepe You could try making an array of wavesurfer instances and using iteration to write less.

**Comment by myuksektepe** [comment]
$( document ).ready(function() {
			$(".wave").each(function(index,item){
				var sound_url = $(item).data("sound");
				var sound_id = $(item).find("div").attr("id");
				console.log('sID: '+sound_id + ' / sURL: ' + sound_url);
				// WaveSurfer
				var sound_id = WaveSurfer.create({container: '#'+sound_id ,waveColor: '#afafaf',progressColor: '#dd3333',height: '40',cursorWidth: 0,barWidth: 0,}); 
				sound_id.load(sound_url);
			});
		});

I can not use the pause and play functions for the system I'm doing when I create it with loop. 

I think i'll can find a solution for my project. Thank you for your time and your answer.
