### ISSUE TITLE
Update deprecated babel-preset-es2015

### ISSUE THREAD

**Issue by thijstriemstra** [katspaugh/wavesurfer.js#1241]
Seeing this error on travis (https://travis-ci.org/katspaugh/wavesurfer.js/builds/295353174#L456):

```
deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
```

cc @mspae

**Comment by mspae** [comment]
will do.

btw thanks for checking and merging all the PRs, @thijstriemstra

**Comment by thijstriemstra** [comment]
Most of the packages are outdated in https://github.com/katspaugh/wavesurfer.js/blob/master/package.json#L31(webpack v3 etc), let's upgrade all.

**Comment by mspae** [comment]
@thijstriemstra See #1249
