### ISSUE TITLE
Update changelog with version 2 changes

### ISSUE THREAD

**Issue by mspae** [katspaugh/wavesurfer.js#1242]
The `CHANGES.md` doesn't contain any v2 changes. This should be added.

**Comment by mspae** [comment]
So I've updated the changelog and will open a PR within the next week.

But I want to use this opportunity to discuss how we are going to handle changelogs/releases going forward. I have the feeling maintaining the changelog and releasing are still very ardorous tasks, so I propose we automate it as much as possible. I've been looking into possible solutions and have come across one approach which is being used by the Angular team (and has apparently become very much the norm for larger open source projects recently)

– It's a cli script called [standard-version](https://github.com/conventional-changelog/standard-version]) and it relies on the "conventional commit" standard – ([short intro](https://github.com/conventional-changelog/standard-version#commit-message-convention-at-a-glance), [official spec](https://conventionalcommits.org/))

From the standard-version docs, when you run the script:
- bumps the version in package.json/bower.json (based on your commit history)
- uses conventional-changelog to update CHANGELOG.md
- commits package.json (et al.) and CHANGELOG.md
- tags a new release

Then you can simply publish and push.

It think this would make it much easier and safer to release. Base on the PR description template it would be easy for the people who merge & squash to write the correct commits. (Although it is more work than before of course)

– What do you think @thijstriemstra @katspaugh

**Comment by thijstriemstra** [comment]
@mspae I'm not sure if the average contributor will understand this process..

**Comment by thijstriemstra** [comment]
And btw, did you finish that PR for the changelog?
