### ISSUE TITLE
Fixed frequency range spectrogram plugin 

### ISSUE THREAD

**Issue by pcprince** [katspaugh/wavesurfer.js#1248]
I'm attempting to plot wav files which can possibly have a sample rate of 250kHz in order to pick up bats or as low as 8kHz. I would assume the plugin would take the sample rate into account and draw the spectrogram from 0kHz to half the sample rate, but that's not the case. The spectrogram plugin seems to only show 0kHz to 24kHz, which isn't useful when producing plots requiring a different range of frequencies.

I can't find any documentation on changing the ranges so was wondering if this is simply not an included feature or am I missing something?

**Comment by pcprince** [comment]
Could it have something to do with the fact that, no matter the sample rate of the file being loaded, `wavesurfer.backend.ac.sampleRate` is always 48000?

**Comment by entonbiba** [comment]
@pcprince may you post some test code?

**Comment by pcprince** [comment]
This is using WaveSurfer 2.0.0-beta01:
```
var WaveSurfer = require('wavesurfer.js');
var SpectrogramPlugin = require('wavesurfer.js/dist/plugin/wavesurfer.spectrogram.min.js');

var spectrogram = SpectrogramPlugin.create({
    container: "#wave-spectrogram",
    labels: true
});

var wavesurfer = WaveSurfer.create({
    container: '#waveform',
    waveColor: '#FF0000',
    progressColor: '#46B54D',
    hideScrollbar: true,
    plugins: [
        spectrogram
    ]
});

wavesurfer.load('bat.wav');
console.log(wavesurfer.backend.ac.sampleRate);
```
The bat wav file is a recording at 250kHz. The console outputs 48000 and only shows the spectrogram up to 24kHz. If it actually was a 48kHz file, stopping at 24kHz would make sense. It seems to use that range of 0-24kHz for every file and there doesn't seem to be any way to either change the spectrogram sample rate or make WaveSurfer treat files as having any other sample rates.

**Comment by thijstriemstra** [comment]
Closing question, no feedback.
