### ISSUE TITLE
Playing audio via mouseover event failing on Safari after Safari v11 update

### ISSUE THREAD

**Issue by AugustinePF** [katspaugh/wavesurfer.js#1250]
With the release of the Safari v11 update (which introduced a block to media autoplay: https://webkit.org/blog/7734/auto-play-policy-changes-for-macos/) triggering wavesurfer audio via mouseover / hover events has started failing, returning the error:

"Unhandled Promise Rejection: NotAllowedError (DOM Exception 35): The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission."

Triggering wavesurfer audio via click event method works as usual however. 

Mouseover still triggers audio ok for the HTML5 audio element, but fails for wavesurfer audio.

I have tried all relevant options and alternatives found in the wavesurfer documentation and that I could find in other similar wavesurfer issues (including bindings) and also various hacks without success: the waveform loads ok although the play event triggers that error.

Has anyone encountered and been able to solve this?

Thanks very much

**Comment by mspae** [comment]
Can you post the code you are using, @AugustinePF ?

**Comment by thijstriemstra** [comment]
@roboswank is this still an issue?

**Comment by neculaionutni** [comment]
Same problem here. I'm trying to play an HTML 5 audio using JavaScript mouseover event and getting this error:

`Unhandled Promise Rejection: NotAllowedError (DOM Exception 35): The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.
`

Any fix/workaround for this?

**Comment by thijstriemstra** [comment]
You probably need to use a click or tap instead of a mouse event.
