### ISSUE TITLE
Zoom erase or not rendered leftpart of the wave (without peaks) and rightpart (if peaks) when scrolling

### ISSUE THREAD

**Issue by awenger63** [katspaugh/wavesurfer.js#1261]
Hi, 
In the last version 2.0.0-beta02 I find a regression between 2.0.0-beta01 whit the zoom.
When you zoom the wave, this action automaticly render the wave center at the read position (on pause to make the test).
Then left part of the wave is not visible, but you can see it whit scroll. In the last version , left part not visible will be lost, when you scrolling left there no wave :

![image](https://user-images.githubusercontent.com/16153617/33205608-d5314cea-d107-11e7-815c-87f0d4351133.png)

No need code, I use the demo code to reproduce ([https://wavesurfer-js.org/examples/

](https://wavesurfer-js.org/examples/)) . Same issue in firefox quantum 57.0 and chrome  62.0.3202.94.

Hope this can help.

**Comment by awenger63** [comment]
Hello, there is also in this new version a zoom issue at the end of the wave when you decrease the zoom. 
You can see it if you place the current play nearly of the end, zoom ++ ...++ than zoom - (see it, wave go small left), zoom + (wave seem's ok)
Perharps it come from the same bug ?

**Comment by thijstriemstra** [comment]
> In the last version 2.0.0-beta02 I find a regression between 2.0.0-beta01 whit the zoom.

@awenger63 would be really helpful if you can figure out what exact commit changed this.

**Comment by awenger63** [comment]
@thijstriemstra OK, if I can , I would like to help you. I just need to know how I can get different commit version ? have you a link to explain that ?

**Comment by awenger63** [comment]
@thijstriemstra  I'm sorry but I don't arrive to run npm without issues here...., so it's difficult to be sure, but I fell find change who generated the issue and do the regression : #1198 commit 1e7f598.
Can you verify ? Hope this is correct.

**Comment by thijstriemstra** [comment]
@mspae made that change, I hope he can comment on it.

**Comment by awenger63** [comment]
I don't know if someone have take a look at this issue ? I would like to help you more, but I cannot succeeds install it on my Netbeans/Github to trace exactly.
Tell me more

**Comment by jamiefaye** [comment]
I am seeing this issue with the wave editor I am building now. The drawBuffer code calls drawer.getScrollX() to get the coordinate for the left side of the area in which to draw peaks. This means that the earlier canvases are not refilled, so when you scroll-back, all you see is a flat line. Jamming the start variable to zero makes the problem go away. I will try and come up with a better fix than that.

**Comment by awenger63** [comment]
@jamiefaye OK, thanks to look at this problem. Do you have a line code, that I can put on the zoom process  to jamming the start variable to zero ? 
I saw also other draw issue with the wave when zoom increase a lot. Perhaps it's linked. I will look to define a reproductible case and tell you.

**Comment by jamiefaye** [comment]
I changed line 1024 of wavesurfer.js to look like this:
        let start = 0; // this.drawer.getScrollX();
If I were to make this permanent, I would eliminate the 'start' variable, and just use zero.

**Comment by awenger63** [comment]
@jamiefaye Yes, this work, I make the change on the last v2.0.4 (line 2408) on my local code.

**Comment by awenger63** [comment]
@jamiefaye Same issues but at the end of the wave when **load with peaks** and zoom process. Error appear when add the first new canvas (multicanvas). It's the opposite error ... (with or without start =0; because in this case getPeaks() always return peaks since the begining !)
Error appear since V2.0.0.beta2 regression after V2.0.0.beta1.
It's seem only fisrt canvas contain the wave when redraw it. 
Any other good idea ?

**Comment by awenger63** [comment]
After investigation, problem exist when no barWidht and only on the last canvas when zooming it's in drawLineToContext.
In line 3652, if it's the last canvas there is no draw 
`if (first > end || last < start) {
                return;
            }`
@thijstriemstra perhaps this code was adding in commit 258cfbafec5a47965f34e2f59ef8cd4eb82dd4ff (#909 , #924 ).  Can you explain this ?

I change return line by : 
`last -= 1;`
It's seem to work in render and zoom process with peaks in my local code. Perhaps need more test?
@thijstriemstra what do you think about this change ?

@jamiefaye, with your change and my last change, this issues should be correct. 
Thanks

**Comment by awenger63** [comment]
OK, who can see, @mspae  ?
To be confirm, but I don't really understand this test because it compare two different thing. In my comprehension, fisrt and last are peaks information size, end and start are canvas width. And the comment seem to say, if it's not the last canvas, we add 1 peaks information to make the join between canvas.

**Comment by Fiorello** [comment]
Hi, any news abouts this issue?
It happens to me again, when zoom in.
Im' using wavesurfer-js version 2.1.2

![screenshot 2019-01-28 at 10 31 56](https://user-images.githubusercontent.com/3278942/51826767-1913dd00-22e8-11e9-8f1c-16449ea56919.jpg)

**Comment by awenger63** [comment]
@Fiorello I always have the code change suggest by @jamiefaye  + my [commit](https://github.com/awenger63/wavesurfer.js/commit/884ca73b7e90c38a730a95731b7076b4ee9d6d70) on my local version ...

**Comment by Fiorello** [comment]
Great.. Is there any hope of integrating it in the module?

**Comment by Bran1304** [comment]
Is there any update on this please? @thijstriemstra @katspaugh

**Comment by thijstriemstra** [comment]
if you want to speed things up, hire either of us. Until then someone (else) will eventually fix it.

**Comment by Bran1304** [comment]
@thijstriemstra I thought the change awenger63 suggested fixes the issue, and wondered if it could be implemented. Anyways, I might PM you so we can take this further

**Comment by thijstriemstra** [comment]
> I thought the change awenger63 suggested fixes the issue

Give it a try, and if it does, open a pull request so it can get fixed.
