### ISSUE TITLE
Can you please help me to integrate a waveform (wavesurfer) on mediaelement playlist plugin ?

### ISSUE THREAD

**Issue by vishnu-the-developer** [katspaugh/wavesurfer.js#1262]
Can you please help me to integrate a waveform (wavesurfer) on mediaelement playlist plugin ? I integrated it with a hard coding in mediaelement-and-player.js. Can anybody answer this then i can share my js with you. Please help. Do you have any money policy on this ?
Thanks

**Comment by thijstriemstra** [comment]
No feedback, closing.
