### ISSUE TITLE
2.0 Minimap: canvas click does nothing; Initial load does not display waveform

### ISSUE THREAD

**Issue by PureSqncMedia** [katspaugh/wavesurfer.js#1265]
### Wavesurfer.js version(s):
2.0 beta 2

### Browser version(s):
Chrome Version 62.0.3202.94 (Official Build) (64-bit)

### Code needed to reproduce the issue:
- Angular 1x. 
- wavesurfer.js and Minimap plugin built into vendor.js file via gulp
- directive loads wavesurfer and minimap. 
- controller inits minimap later

### (1) Canvas click issue:
Clicking on minimap canvas scrolled the audio on 1x, now nothing happens. Only main WS container canvas can be intereacted with. Hopefully I am missing some minimap config detail

### (2) Minimap waveform does not display on first initialization?
Minimap will not show waveform on first load. 
** Soution found: Found that the sequence of loading the minimap cleared the problem. 
Im not sure about the operations around promises but toggling the minimap before 'ready' seems to clear for me. code snippet:

` vm.wavesurfer.load(activeUrl || null);
   vm.wavesurfer.once('ready', function () {
    // do stuff
      });
_toggleMinimap();`

**Comment by PureSqncMedia** [comment]
Found that changing the backend to 'mediaelement' seems to clear the minimap render issue, but creates other problems. I think I need to add a timeout or something before loading minimap. does not seem to solve canvas interaction though

**Comment by thijstriemstra** [comment]
@PureSqncMedia can you try with 2.0.1?

**Comment by thijstriemstra** [comment]
related to https://github.com/katspaugh/wavesurfer.js/commit/f08cfbded2c1eb1ff48990733dab48606c882e9b perhaps.

**Comment by thijstriemstra** [comment]
>  Soution found: Found that the sequence of loading the minimap cleared the problem.

And can you make a pull request so we can take a look at the fix?

**Comment by PureSqncMedia** [comment]
@thijstriemstra I tried with 2.0.1 and still no interaction on the minimap canvas. I might try with 'mediaelement' backend, or is that not recommended?

The code I have is just loading sequence for wavesurfer elements. The fix for some reason seems that loading the minimap within ws 'onready' signal was


` 
        function _start() {
            if (vm.player.track) {
                vm.player.wavesurfer.load(vm.activeAudioURL || null);
                vm.player.wavesurfer.once('ready', function () {
                    Player.playTrack(vm.player.trackId).then(playTrackSuccessFn, playTrackErrorFn);
                    $scope.$broadcast('rzSliderForceRender');
                    $scope.length = Math.floor(vm.player.wavesurfer.getDuration()).toString();
                    $interval(function () {
                        $scope.moment = Math.floor(vm.player.wavesurfer.getCurrentTime()).toString();
                    }, vm.momentInterval);

                    vm.player.trackTime = vm.player.wavesurfer.getDuration();
                    play();
                    vm.player.playing = true;
                });

                _toggleMinimap();
            }
            else {
                console.error('No valid audio found during trak player start !');
            }
        }

        function _toggleMinimap() {
            //delete any minimaps first
            angular.forEach(vm.player.wavesurfer.initialisedPluginList, function (value, key) {
                if (key == 'minimap') {
                    vm.player.wavesurfer.destroyPlugin('minimap');
                    console.log("yesahh deleted some minimz")
                }
            });

            //init minimaps
vm.player.wavesurfer.addPlugin(MiniMapPlugin.create(detail_minimap_wave_options)).initPlugin('minimap');
          
        }`

**Comment by PureSqncMedia** [comment]
code example

`
vm.player.wavesurfer.once('ready', function () {
.. do stuff on ready, like play
// loading minimap in here results in first track played not rendering minimap.
// a subsequential load and load minimap seems to display correctly
// so moved the add plugin part outside of ready block
});

//works first load
vm.wavesurfer.addPlugin(MiniMapPlugin.create(detail_minimap_wave_options)).initPlugin('minimap');
`

**Comment by roboswank** [comment]
This could be semi related to https://github.com/katspaugh/wavesurfer.js/issues/1311

minimap.js line 113 (v2.0.3 of wavesurfer)
```
this.renderEvent =
            ws.params.backend === 'MediaElement' ? 'waveform-ready' : 'ready';
```
If I change that to `this.renderEvent = 'ready';`, minimap functions as it did before and can be passed in the plugins array just the same.

I only say it could be related to https://github.com/katspaugh/wavesurfer.js/issues/1311 because it appears in both cases something was expecting there to be peak data but there is not.
Right before `waveform-ready` is fired `this.backend.setPeaks(null);` is called and I do not see anything in that would set the peaks before doing so.

I do not necessarily know what the desired behavior here is. Like what potential negatives would come from utilizing the `ready`.

**Comment by elliottb303** [comment]
@thijstriemstra @roboswank  Just updated and happy to see that minimap canvas works now! Thanks
