### ISSUE TITLE
Incorrect progress shown if the media is playing in a background-tab

### ISSUE THREAD

**Issue by jonas2515** [katspaugh/wavesurfer.js#1267]
### Wavesurfer.js version(s)
master-branch

### Browser version(s):
Newest Firefox and Chrome

If using the media element as a backend, the waveform gets updated [when a new frame is drawn](https://github.com/katspaugh/wavesurfer.js/blob/master/src/mediaelement.js#L63).

So when the user starts playback and switches to another tab, the framerate for the current tab is reduced for energy saving reasons and the waveform gets updated at a slower interval.

And since the waveform doesn't get updated if the player isn't playing, finishing the playback while another tab is active and then switching back to the wavesurfer tab can lead to a progress bar "being stuck" somewhere in the middle of the waveform.

I didn't check if this is also the case with the WebAudio backend, as a fix for this one I propose subscribing to the pause event of the media element and updating the waveform one last time.

**Comment by thijstriemstra** [comment]
can you also check if it's the case for the webaudio backend?

**Comment by jonas2515** [comment]
I don't think it is. In the WebAudio backend, the audioprocess event is fired by ScriptProcessorNode in the browser and just forwarded by wavesurfer.

**Comment by thijstriemstra** [comment]
Merged in 2.0.2.
