### ISSUE TITLE
How to add marker ?

### ISSUE THREAD

**Issue by linzerui** [katspaugh/wavesurfer.js#1270]
I can not find the feature (#152) in the source code. has it been deleted ?

**Comment by GitHubRakeshSharma** [comment]
I think so... So I just wrote a small marker plug-in... pretty close to the region plug-in

**Comment by thijstriemstra** [comment]
@linzerui take a look at the annotations example: http://wavesurfer-js.org/example/annotation/

**Comment by mayurshinde4590** [comment]
hi ,

how to add currunt time marker  on wavesurfer
