### ISSUE TITLE
Timeline not rendered when load with peaks

### ISSUE THREAD

**Issue by awenger63** [katspaugh/wavesurfer.js#1272]
Hi,
When use timeline pluging and load wavesurfer with peaks, timeline is not rendered before you play song.

### Code needed to reproduce the issue:
To reproduce, I use [https://codepen.io/frumbert/pen/MOGrKm](url)  (issue #1260) and add peaks like [https://codepen.io/johnsq/pen/KyVOLd](url)

First load, timeline is not rendered, use play and it's visible.

Hope you can reproduce it and render timeline in first load with peaks data.
Regards

**Comment by awenger63** [comment]
Hi, 
For your help, this is not look like true if you add `backend: 'MediaElement'` parameter.

**Comment by thijstriemstra** [comment]
Can you try with the latest 2.0.1?

**Comment by awenger63** [comment]
Hi @thijstriemstra : Same issue.
So, today I can put backend to MediaElement and timeLine is correct, but for zoom issue #1261 no change too in this latest version.

**Comment by thijstriemstra** [comment]
Ok, thanks for feedback.
