### ISSUE TITLE
Version 2.0.0 broke?

### ISSUE THREAD

**Issue by janhartmann** [katspaugh/wavesurfer.js#1273]
I used the beta versions of the 2.0.0, but today I updated to the non-beta and this error appears:

```Module not found: Error: Can't resolve 'wavesurfer.js' ```

My package.json is: "wavesurfer.js": "^2.0.0"

**Comment by thijstriemstra** [comment]
Yep this happened on friday. Ping @katspaugh

**Comment by thijstriemstra** [comment]
@katspaugh dont forget to bump the version for bower as well. and to make a tag for 2.0.1

**Comment by katspaugh** [comment]
I've just published 2.0.1. Thanks! 👍

**Comment by thijstriemstra** [comment]
@katspaugh yeah but bower is still using the old version nr: https://github.com/katspaugh/wavesurfer.js/blob/master/bower.json#L3
