### ISSUE TITLE
fails to read local file in nwjs/win

### ISSUE THREAD

**Issue by infantilo** [katspaugh/wavesurfer.js#1276]
I'm having troubles with loading local files with windows path urls (e.g. "C:/temp/...") within nwjs on windows and the latest wavesurfer.js.
i'm using the same path on pulse.js and within my functions and it loads fine using XMLHttpRequest, but wavesurfer does not work. ( wafesurfer.js:747 object ProgressEvent)
No waveform gets displayed.
path to subfolder of the main html page (e.g. "sounds/test.mp3") work properly.

SOLUTION: change wavesurfer.js line 744 to 
`if (200 == xhr.status || 206 == xhr.status || 0 == xhr.status) {`

**Comment by thijstriemstra** [comment]
@infantilo what does xhr.status code 0 mean exactly?

**Comment by thijstriemstra** [comment]
it's unfortunate because "Before the request is complete, the value of status will be 0. It is worth noting that browsers report a status of 0 in case of XMLHttpRequest errors too." So this is not a good fix.

**Comment by thijstriemstra** [comment]
No feedback, closing.
