### ISSUE TITLE
Chrome warns about deprecation on Jan 2018

### ISSUE THREAD

**Issue by amrfaisal** [katspaugh/wavesurfer.js#1277]
### Wavesurfer.js version(s):
1.4.0

### Browser version(s):
Chrome Version 63.0.3239.84

### Code needed to reproduce the issue:
Browser log below warning:
`[Deprecation] GainNode.gain.value setter smoothing is deprecated and will be removed in M64, around January 2018. Please use setTargetAtTime() instead if smoothing is needed. See https://www.chromestatus.com/features/5287995770929152 for more details.`

**Comment by thijstriemstra** [comment]
@amrfaisal this is an old version, try 2.0.1.

**Comment by amrfaisal** [comment]
@thijstriemstra Upgraded to `2.0.1` and got the same warning.

**Comment by thijstriemstra** [comment]
@amrfaisal I opened #1279, can you see if that fixes it for you?
