### ISSUE TITLE
How can the generated waveform be saved ?

### ISSUE THREAD

**Issue by the1the** [katspaugh/wavesurfer.js#1278]
Hello,
I didn't find a consitant documentation for saving the generated waveform data.
I've tried 
`  wavesurfer.on('ready', function () {
                // the width of the waveform in double pixels
                var width = wavesurfer.getDuration() * wavesurfer.params.minPxPerSec * wavesurfer.params.pixelRatio;
                var dataJSON = wavesurfer.backend.getPeaks(width);
                console.log (dataJSON);
 });`

But its empty...
What is the best method to do this exportPCM ? backend.getpeaks() ?

Best
P.

**Comment by acollier88** [comment]
@the1the  What are you trying to save exactly the data behind the waveform or an image of the waveform?

**Comment by the1the** [comment]
I want to save the waveform peaks as JSON (to load it the next time).

**Comment by thijstriemstra** [comment]
I don't think we have an export function for that, maybe @mspae has an idea.

**Comment by X-Raym** [comment]
@the1the you can use
`var peaks = object.backend.getPeaks(960);`
... where object is your wavesurfer object.
960 means 1920 long array so it is enoufg from small to widescreen if the waveform is meant to not be zoomed.

Then, just wrap this in a AJAX request to generate your json file. You can add extra infos in it (I personally add audio length and audio URL).

**Comment by thijstriemstra** [comment]
Thanks for the feedback.

**Comment by the1the** [comment]
`        wavesurfer.on('ready', function () {
                // the width of the waveform in double pixels
                //var width = wavesurfer.getDuration() * wavesurfer.params.minPxPerSec * wavesurfer.params.pixelRatio;
                var dataJSON = wavesurfer.backend.getPeaks(960);
                console.log (dataJSON);



            });

Returns array[0]

so what I'm I doing wrong?
Any help very appriciated.`
