### ISSUE TITLE
416 Requested Range Not Satisfiable Error

### ISSUE THREAD

**Issue by silveur** [katspaugh/wavesurfer.js#1282]
Hi I'm having issues loading the waveform with backend option set with: MediaElement
Most of the time I get a bad response from AWS S3 stating a 416 error with the media, also I checked the headers and noticed this:
`Range:bytes=0-`

Any idea what could cause that?
Thanks

**Comment by thijstriemstra** [comment]
This is more suitable for stackoverflow, please re-open if you found an issue in wavesurfer.js.
