### ISSUE TITLE
Limit of peaks data that can be passed to load method

### ISSUE THREAD

**Issue by sau752** [katspaugh/wavesurfer.js#1283]
In my code, I am generating peaks data on the server. The prerendered peaks data is around ~10000 records. Now, when I try to render these many records with wavesurfer.js `load` method, it displays only a part of the waveform. Is there any limit to the `peaks` data that can be passed to `load(url, peaks)` method? 

PS, I see that wavesurfer.js generates peaks around 4600 records for any length file.

**Comment by thijstriemstra** [comment]
you'll have to dig into that particular piece of code of the library?

**Comment by sau752** [comment]
While looking into previous related issues, I found that there have been some developments in v2.0.0-beta02 as mentioned in #1230 issue and has a related example [.](https://codesandbox.io/s/0yloo908pv) which fixes it. But this again fails on the IE11 browser. My main purpose of using peaks data was to support IE11 as it doesn't support WebAudio API. Can anybody help with the permanent fix for this?

**Comment by thijstriemstra** [comment]
Can you try with the latest version (2.0.4 or newer) and paste your code here?

**Comment by suresh2110** [comment]
Is there any update on this issue? I have an an hour of peaks data which I have to render. Would like to know how to go about it.

**Comment by entonbiba** [comment]
@suresh2110 have you tried the renderer: "MultiCanvas" option?

**Comment by suresh2110** [comment]
I am using Multicanvas. I am able to render it.

**Comment by thijstriemstra** [comment]
Thanks for the feedback.
