### ISSUE TITLE
Passing split channel pre-rendered peaks to load method

### ISSUE THREAD

**Issue by sau752** [katspaugh/wavesurfer.js#1284]
For single-channel audio, I know that there is a way to pass pre-rendered peaks to load method using `load(url, peaks)`. Is there a way to pass split channel pre-rendered peaks to load method when I have separate array of peaks for both the channels?

Wavesurfer.js version: 1.4.0

**Comment by thijstriemstra** [comment]
Don't think so, PRs are welcome. ps. use v2.0.1 or newer, 1.4.0 is not supported any longer.

**Comment by thijstriemstra** [comment]
@sau752 you should be able to pass a multi-dimensional array e.g. `[[0, 1, 2], [0,2,3]]`.
