### ISSUE TITLE
isPlaying() method returns false positive when mobile OS blocks playback

### ISSUE THREAD

**Issue by mgoldsteinla** [katspaugh/wavesurfer.js#1285]
Our website has multiple songs to choose from, too many to preload. When the user clicks a song to play, we have to load the file and then call the wavesurfer play method from the wavesurfer.on ready listener. 

Mobile operating systems silently swallow the wavesurfer.play() call and playback never starts, but when I call wavesurfer.isPlaying() it returns true.

I'd like to be able to prompt users to hit the play button when mobile devices block programmatic calls to the play() method. How can I do this? Is there some other way around this issue for mobile devices? 

### Wavesurfer.js version(s):
1.2.1

### Browser version(s):
Safari iOS 11.2.1

### Code needed to reproduce the issue:
```javascript
$('#song1').click(function () {
      wavesurfer.load('audio/BRU_LOCD_0010_00701_Wandering_Minstrel_APM.mp3');
});

wavesurfer.on('ready', function () {
      wavesurfer.play();
});
```

**Comment by thijstriemstra** [comment]
1.2.1 is deprecated, can you try 2.0.1 or newer?

**Comment by mgoldsteinla** [comment]
I tried the 2.0.1 version and it has the same problem.

**Comment by thijstriemstra** [comment]
See https://developers.google.com/web/updates/2017/09/autoplay-policy-changes#webaudio

try:

```javascript
var promise = document.querySelector('audio').play();

if (promise !== undefined) {
  promise.then(_ => {
    // Autoplay started!
  }).catch(error => {
    // Autoplay was prevented.
    // Show a "Play" button so that user can start playback.
  });
}
```
