### ISSUE TITLE
setCurrentTime function bug

### ISSUE THREAD

**Issue by vetulitichev** [katspaugh/wavesurfer.js#1292]
Hi all) trying to use function setCurrentTime but it doesn't work properly. 
Here is my init function:
```javascript
this.player = wavesurfer.create({
            container:this.player,
            waveColor:'red',
            progressColor:'purple',

            plugins:[
                RegionsPlugin.create({
                    dragSelection: true,
                    regions: true,
                    slop: 2,
                    deferInit: true,
                })
            ]

        });
```
Then i'am adding handler to button which should set time to 5 sec position 
```javascript
handlePlay = () => {
        console.log(this.player.getCurrentTime()); // always show 0 cuz player is't played yet
        this.player.setCurrentTime(5)
        console.log(this.player.getCurrentTime()); // all time shows time of the end of track
  };
```
Seems like this.player.setCurrentTime() set current time to end of track

The only issues is when i'am trying to set time to 0. That's work correct.

**Comment by thijstriemstra** [comment]
@vetulitichev this is the code for setCurrentTime:

```javascript
/**
     * Set the current play time in seconds.
     *
     * @param {number} seconds A positive number in seconds. E.g. 10 means 10
     * seconds, 60 means 1 minute
     */
    setCurrentTime(seconds) {
        if (this.getDuration() >= seconds) {
            this.seekTo(1);
        } else {
            this.seekTo(seconds / this.getDuration());
        }
}
```

what does this.player.getDuration() return for you?

**Comment by vetulitichev** [comment]
@thijstriemstra

 I'am using that track https://ia902606.us.archive.org/35/items/shortpoetry_047_librivox/song_cjrg_teasdale_64kb.mp3

For that track it  is 44.

**Comment by thijstriemstra** [comment]
@vetulitichev can you add some console.log statements in that `setCurrentTime` method and report what value it's targeting?

**Comment by roboswank** [comment]
@therewasaguy @vetulitichev 
That condition is backwards
```
this.getDuration() >= seconds
```
That should always be true.

Just need to flip it.
```
 seconds >= this.getDuration();
```
