### ISSUE TITLE
Ability to select audio output device

### ISSUE THREAD

**Issue by johnryan** [katspaugh/wavesurfer.js#1293]
### Wavesurfer.js version(s):
^1.1.11 but seems like it affects all

### Browser version(s):
Chrome

### Code needed to reproduce the issue:
As far as i can tell there's no way to specify the audio output device for wavesurfer. My application has a speaker selector and as such I need to be able to set the output to the default device/bluetooth headset etc. 

Is there any supported / unsupported way to accomplish this?

**Comment by thijstriemstra** [comment]
It's supported by Chrome since v49: https://www.chromestatus.com/feature/4621603249848320 and https://webrtc.github.io/samples/src/content/devices/multi/

But this is not possible yet in wavesurfer.js (e.g. there's no setting). Maybe you can add support for it?
