### ISSUE TITLE
Right to Left Support

### ISSUE THREAD

**Issue by samanmohamadi** [katspaugh/wavesurfer.js#1296]
Thanks for the Great work.
in my project, I need the wave to be right-to-left.
is there any simple way to achieve this?
Does replacing all `right` and `left` in the project do the job?

**Comment by thijstriemstra** [comment]
@samanmohamadi good question.. @katspaugh you have an idea how hard this would be to implement?

**Comment by katspaugh** [comment]
Simply adding `style="transform: rotateY(180deg)"` to the container should do the trick.

**Comment by thijstriemstra** [comment]
Does that work for you @samanmohamadi? If it does, adding an example would be nice.

**Comment by samanmohamadi** [comment]
It works but there is an issue with calculating progress when mouse click.
a little change in  [handleEvent](https://github.com/katspaugh/wavesurfer.js/blob/cec39f9abf48600f58c9d1e0be7a383b0213e09f/src/drawer.js#L86) function will fix it.

**Comment by katspaugh** [comment]
A PR is welcome, @samanmohamadi!

**Comment by samanmohamadi** [comment]
I'm am in the middle of a forced project and my solution to this issue is a little dirty and it not ready for a pr. I will do that as soon as possible.

**Comment by thijstriemstra** [comment]
Maybe related to #1319
