### ISSUE TITLE
project - ChosenMasters.com uses wavesurfer.js

### ISSUE THREAD

**Issue by MileanCo** [katspaugh/wavesurfer.js#1297]
# ChosenMasters.com
Please consider including our project in your examples - [https://app.chosenmasters.com/](https://app.chosenmasters.com/?utm_source=github)

You have to quickly register, upload a track, and you are taken to our Player utilizing wavesurfer.js! Let us know how it goes for you :)

### Wavesurfer.js version(s):
^2.0.2

**Comment by thijstriemstra** [comment]
@MileanCo you can add it to the list here: https://github.com/katspaugh/wavesurfer.js/blob/gh-pages/projects/index.html (click edit button, make change, and create pull request).
