### ISSUE TITLE
Loading Percentage is not reset after new .load(...)

### ISSUE THREAD

**Issue by janhartmann** [katspaugh/wavesurfer.js#1298]
### Wavesurfer.js version(s):

"wavesurfer.js": "^2.0.1",

### Browser version(s):

Chrome, Latest

### Code needed to reproduce the issue:

I have a WaveSurfer which is wrapped inside a React Component and used as an Audio Player. When the component receives a new URL property, the component loads this using the WaveSurfer.

Apparently, the loading percentage is not reset to `0`, when you are loading a new file, while a file is being buffered. The loading percentage will be the last value of the previous file, _until_ the first percentage is received from the new file.

```js
this.wavesurfer.on("loading", percentage => {
     // This percentage has the last value of the previous file, when loading a new file during buffering
});
```

I would expect when a new `.load(...)` method is called, the AJAX request is aborted and the loading percentage is reset to 0.

### Use behaviour needed to reproduce the issue:

Load a large file and while buffering that file, load a new one. The loading indicator is not reset until the request is flowing

**Comment by thijstriemstra** [comment]
@janhartmann sounds like a bug. Can you create a pull request that resets the duration etc?

**Comment by janhartmann** [comment]
Maybe I am not doing this right, as it seems like to should be reset on the .empty() method: https://github.com/katspaugh/wavesurfer.js/blob/master/src/wavesurfer.js#L1426 

Going to play around with it further.

**Comment by thijstriemstra** [comment]
any news @janhartmann?

**Comment by janhartmann** [comment]
Yes, lets close this. I believe I had some issues when I updated some internal component state, after some refactoring it worked without problems.
