### ISSUE TITLE
getDuration() returns 0 on some Android configurations

### ISSUE THREAD

**Issue by retallicka** [katspaugh/wavesurfer.js#1299]
I am listening to the ready event then calling wavesurfer.getDuration()
it is always 0 on some browsers.

Many of our users are mobile users.

I have reproduced it on a number of devices -
HTC One x Android 4.1.1 Chrome 42
Galaxy S4 Android 4.4.2 Chrome 47
Android (Lollipop) Chrome 39
Android (Marshmallow) Chrome 49
S8+ Android 7 (Nougat) Samsung Browser 6.2
S8 Android 7 (Nougat) Samsung Browser 6.2

It is not happening on
S8 Android 7 Chrome 63
Any desktop browsers

so it seems to be happening on older android versions of chrome and samsung internet browser, but not newer versions of Chrome

What can I do to get around this issue?

Here is more info on what we are doing - 

version 2.0.2
but was happening on older versions too
Try http://beta.zedge.net
sign up and upload an mp3 to see it in action, the sliders are set to min 0 and max 0 which is crashing the browser (due to another plugin we use - nouislider)
Setting the max to 30 by default does not crash it, but we need the duration to set the zoom level of wavesurfer accordingly, to show 30 seconds across the timeline if the duration is longer than that, but stretch it out if it is shorter. Is there any other way to get it?
I can share some code snippets if that is useful but should be easy to reproduce

**Comment by thijstriemstra** [comment]
Not sure if there's anything you can do if it's a browser issue. Perhaps calculating the duration elsewhere (e.g. server) and passing that to wavesurfer.js but hacking the getDuration method so it returns the correct value for a particular track?

**Comment by retallicka** [comment]
Listening to `waveform-ready` instead of `ready` appears to have fixed this! 😃
