### ISSUE TITLE
Playing back sound recorded from microphone as blob

### ISSUE THREAD

**Issue by bknill** [katspaugh/wavesurfer.js#1301]
Hi, 

I see this is a common issue, Wavesurfer not being able to decode a blob, and the issues associated with it. 

I'm using wavesurfer to record audio from microphone and display wave, and store an array of 
Int8Array. 

I've been trying all kinds of things to get that into a blob that Wavesurfer can decode in Chrome. The sound file plays back as a blob in Chrome and also converted into an MP3 via LameJs.  I'm even trying this https://github.com/mattdiamond/Recorderjs/blob/master/src/recorder.js that someone else found and convert it into a WAV with no luck. 

I can't get it to play in Wavesurfer. 

The basic thing I'm trying is something like

```
      let blob = new Blob(this.state.dataBuffer, {type: 'audio/mp3'})
      this.wavesurfer.loadBlob(blob)
```

I get this error 

> Cannot read property 'querySelector' of undefined

with
      let blob = new Blob([this.state.dataBuffer], {type: 'audio/mp3'})

I get

>  DOMException: Unable to decode audio data

```
I've also tried 
wavesurfer.loadDecodedBuffer(audioBuffer);
wavesurfer.loadArrayBuffer(arrayBuffer);
```

But I'm not sure how to convert my array of audio data got via

```
    let data = ev.inputBuffer.getChannelData(0)
    if(data.length > 0)
      this.appendToBuffer(data)
```

Into an array buffer or audio buffer. 

Any clues!?

**Comment by thijstriemstra** [comment]
@bknill take a look at my https://github.com/collab-project/videojs-record project that does exactly that, specifically the recorderjs plugin if you want to use that: https://github.com/collab-project/videojs-record/blob/master/src/js/plugins/recorderjs-plugin.js

**Comment by bknill** [comment]
Great thanks. I 'll follow that!
