### ISSUE TITLE
Any way to encode MP3 from backend.buffer with LameJS

### ISSUE THREAD

**Issue by bknill** [katspaugh/wavesurfer.js#1304]
I can encode the samples from the audio events and load them into wavesurfer. 

I'm now making changes using the filters, deleting parts etc. 

I'd like to encode this data into an mp3 and download, 

I've been trying things like this, 
`this.encoder.encodeBuffer(this.wavesurfer.backend.buffer)`

But the MP3 is always corrupted. 

Anyone else found a way to do this?

**Comment by thijstriemstra** [comment]
This is not related to wavesurfer API, use stackoverflow etc for these type of questions.

**Comment by bknill** [comment]
Thanks.. if you can help at all https://stackoverflow.com/questions/48313274/wavesurfer-backend-arraybuffer-to-mp3-using-lame
