### ISSUE TITLE
Trying to delete audio from region

### ISSUE THREAD

**Issue by bknill** [katspaugh/wavesurfer.js#1305]
Hi, 

I'm trying to use regions as a way of deleting parts of the audio. I thought I'd do something clever and store all of the audio events from the microphone in an array, then use the playback time to compare with the region start end and remove those in that timeframe. 

This is working, but the resulting arrayBuffer can't be played

i.e.

```
      const offset = this.state.audioEvents[0].playbackTime
      let events = this.state.audioEvents

      for(let r in this.wavesurfer.regions.list){
        const region = this.wavesurfer.regions.list[r]

        let i = events.length
        while (i--) {
          let t = events[i].playbackTime - offset
          if (t > region.start && t < region.end) {
            events.splice(i, 1)
          }
        }
      }

      this.setState({
        audioEvents : events,
      })

      console.log(this.state.audioEvents)

      this.clearBuffer()
      this.wavesurfer.clearRegions()
      this.encodeEvents(this.state.audioEvents,false)
      let blob = new Blob(this.state.dataBuffer, {type: 'audio/mp3'})

      this.wavesurfer.loadBlob(blob)

```
And my function to convert the events into audio data

    for(let e in events) {
      let data = events[e].inputBuffer.getChannelData(0)

      if(data.length > 0)
          this.appendToBuffer(data)
      
    }
    this.appendToBuffer(this.encoder.flush())
  }`

This function works before removing the events I don't want. 

Is there a better way of doing this?

**Comment by thijstriemstra** [comment]
@bknill can you post a codepen example?

**Comment by thijstriemstra** [comment]
No feedback, closing.
