### ISSUE TITLE
how to use playLoop() ?

### ISSUE THREAD

**Issue by desafinadude** [katspaugh/wavesurfer.js#1306]
Hi

How do I use playLoop() ?
I've tried various ways...

wavesurfer.playLoop(id);
wavesurfer.regions.id.playLoop();
id.playLoop();

None of the above works.
How do I loop or play a region with an id?

Thanks in advance - great library!

**Comment by thijstriemstra** [comment]
Looks like there isn't a loop function available when searching the code, could only find it in regions plugin, see #499. A workaround would be listening for the `finish` event and restart playback there.

**Comment by desafinadude** [comment]
Thanks for the reply. I actually meant for regions. 
Keep getting "not a method" errors.

**Comment by ArTiSTiX** [comment]
playLoop is a Region instance method.
Region instance is returned by add() method, and you can get regions by its id through the region plugin instance.

`wavesurfer.regions.list[id].playLoop();`should work (i don't use v1 though, v2 is a bit different).

You can also use { loop: true } when creating region.
