### ISSUE TITLE
Update examples on website for v2.0

### ISSUE THREAD

**Issue by thijstriemstra** [katspaugh/wavesurfer.js#1309]
The examples on https://wavesurfer-js.org are still using an old wavesurfer version. The content for the site lives in the `gh-pages` branch.

**Comment by thijstriemstra** [comment]
@katspaugh these codepen examples on the website are not really practical since only you can edit/update them afaik. I'd rather use 'local' examples there, thoughts?

**Comment by katspaugh** [comment]
@thijstriemstra I agree. The script is already included in the header template, so we could just use it from every page.

It would be cool to have something like CodeMirror with the example code evaluated live. That's why I went with CodePen initially (but now I see it's a pain to update).

**Comment by thijstriemstra** [comment]
Fixed!
