### ISSUE TITLE
update waveform width when container change width

### ISSUE THREAD

**Issue by goplastic** [katspaugh/wavesurfer.js#131]
Hi, hi have a responsive theme on my website.
I'd like to update the waveform width with js.
How can i do that?

Thank you.
Really nice js plugin!

Luca

**Comment by mikeyshean** [comment]
Nice! this works very well.. just adding to this from a related thread:


Hi, you may want to add a debounce (underscorejs) to that resize as:
```
$(window).resize(_.debounce(function(){
wavesurfer.drawer.containerWidth = wavesurfer.drawer.container.clientWidth;
wavesurfer.drawBuffer();
}, 500));
```
