### ISSUE TITLE
form with direction RTL have render issues with TimeLine + Zoom and other

### ISSUE THREAD

**Issue by awenger63** [katspaugh/wavesurfer.js#1319]
### Wavesurfer.js version(s): 
v2.01

### Browser version(s):
Chrome 64.0.3282.140 , Firefox quantum 58.0.1

### Code needed to reproduce the issue:
Add dir="RTL" on your form and test seek, play ..
I do it on this code  : [https://github.com/katspaugh/wavesurfer.js/issues/new](url)
`<div **dir="RTL"**><div id="waveform"></div>
<div id="waveform-timeline"></div>
</div> ....`

Workarround for me => always put dir="LTR" in wave div !
In this case wavesurfer is alway LTR for all.

**Comment by thijstriemstra** [comment]
@awenger63 what are you suggesting exactly? Any improvements that can be made to this library?

**Comment by awenger63** [comment]
First suggestion can be  : have a default value for dir = "LTR" than wavesurfer always ready when it'is implemented in a RTL form (like the workarround). It's for make a trace that I have created this issue and if someone have same issue.

Second, it's depend of RTL country habits. In this case, users would like the wave on the other side ... This need require to reverse or inverse all functionnality (plugins too) and it should be a little complexe. Today it'snt necessary for my actual end user, wavesurfer's always the same direction. Perhaps nobody need, than first suggestion can be the solution to not inherit dir property.

is it answer the questions ?

**Comment by thijstriemstra** [comment]
@awenger63 can you make a pull request and change the actual code so it's easier to see your intention?

**Comment by thijstriemstra** [comment]
also see #1540

**Comment by awenger63** [comment]
Thanks @thijstriemstra , it will be better than my workarround to have a solution for LTR if it' need for user country usage. Use a param to make it like an option is very friendly because some user (LTR env) would like stay with wave RTL !

**Comment by awenger63** [comment]
Nice, I will test it with the end users when they want to put it in place
