### ISSUE TITLE
Cant use wavesurfer.js in Ember application

### ISSUE THREAD

**Issue by Saidalo** [katspaugh/wavesurfer.js#1320]
Hello

I am trying to use wavesurfer in my ember app. 
node: v0.10.38
npm: 2.11.0

I installed wavesurfer as in official page and some other pages too:
http://chrismasters.net/ember-cli-wavesurfer-js-shim/
https://npm.taobao.org/package/ember-cli-wavesurfer-js-shim

Well in all cases it is not working on anyway.

I am installing on the several ways but everything is useless.

I am trying to use it by importing it into my view like:
import Wavesurfer from 'wavesurfer/wavesurfer.js/ember-cli-wavesurfer-js-shim'

Nothing works. Please help me with this problem

**Comment by thijstriemstra** [comment]
What is `ember-cli-wavesurfer-js-shim`? This does not seem related to wavesurfer, try asking the `ember-cli-wavesurfer-js-shim` project instead.
