### ISSUE TITLE
setVolume() not working correctly on Firefox

### ISSUE THREAD

**Issue by MichaelRoehrig** [katspaugh/wavesurfer.js#1327]
### Wavesurfer.js version(s)
1.4.0

### Browser version(s)
Firefox Quantum 58.0.2 (64-Bit)

### Code needed to reproduce the issue
As seen on https://dateimaschine.de/audio/20389730a3c82adc

### Issue
setVolume() (called by the range slider) does only have an impact after having clicked into the waveform.

### Description
As you might notice when using Firefox, after you hit the play button (or press space) on the website mentioned above, the volume slider _<input type="range">_ does not do anything, except for muting (at value 0 _setMute(true)_ is called). If you click anywhere on the waveform it's working again. This behaviour seems to be Firefox only. Edge and Chrome work fine, Internet Explorer as well (it's got more severe problems, e.g. not showing the waveform at all (dont't care about IE), but - hey -, volume works correctly there!)

### Debugging done
_#volume-slider_ is the range input

```
$('#volume-slider').on('input change', function() {
	wavesurfer.setVolume(parseInt($('#volume-slider').val()) / 100);
	console.log(wavesurfer.getVolume());
});
```

In spite of not audibly reacting to setVolume() the desired getVolume() number gets written to the console! After the song finishes, the same problem occurs again.

However, the initial setVolume() works:

```
wavesurfer.on('ready', function() {
	wavesurfer.setVolume($('#volume-slider').val() / 100);
});
```

It's not the parseInt(), juggled around with that for testing.

**Comment by thijstriemstra** [comment]
@MichaelRoehrig you are using a really old version. Can you reproduce this with the latest version?

**Comment by MichaelRoehrig** [comment]
Oh, didn't see that. Always worked with the one mentioned on wavesurfer-js.org :-)
Switched to the 2.0.0-beta01 version on cloudflare and I isolated everything:

https://jsfiddle.net/83vnwzd3/10/

The problem is still there.

**Comment by thijstriemstra** [comment]
@MichaelRoehrig why do you think beta01 is the latest version?

**Comment by MichaelRoehrig** [comment]
I didn't have npm available earlier. This 2.0.0 version did not seem too old :-).
Now I tried the newest version (2.0.4): works! Easier than I thought... thanks for your help!
