### ISSUE TITLE
Unable to seek-and-play with MediaElement (streaming)

### ISSUE THREAD

**Issue by janhartmann** [katspaugh/wavesurfer.js#1335]
I have a streaming endpoint and I am using the `MediaElement` backend option in order to play the audio, without it needing to be downloaded completely.  

This is working just fine, however I am unable to seek on the audio, even when it has been downloaded completely. The playing just starts from the beginning no matter where I click on the WaveSurfer.

* If the audio is playing and I seek, the audio starts from the beginning
* If I pause the playing and seek and then click pay, the audio starts from the beginning
* If I pause the playing and click play again (without seeking), the file resumes just fine

On initialising the WaveSurfer, we disable interaction and first enable interaction once the `waveform-ready` is fired. This is to prevent seeking forward on a stream, which is not fully downloaded.

I have made this video to demonstrate. The audio stream has been downloaded completely here:

![streaming](https://user-images.githubusercontent.com/1107383/36524117-39249c96-17be-11e8-9a74-703c659fddf5.gif)

I've tried looking and debugging this without any luck, please let me know if you need any information

* WaveSurfer: 2.0.4
* Chrome: 64.0.3282.167

**Comment by janhartmann** [comment]
This was a server issue on our part, we finally found the issue. This has nothing to do with the library.

**Comment by 15838028035** [comment]
@janhartmann  cloud you share you demo?

**Comment by 15838028035** [comment]
is there any memory problems ?  @janhartmann

**Comment by jus37** [comment]
Can you explain the issue you found please?

**Comment by angela83** [comment]
@janhartmann can you share what was the server issue and how it was fixed as we are seeing this as well. thanks!
