### ISSUE TITLE
Is exportPCM working on latest release?

### ISSUE THREAD

**Issue by netgfx** [katspaugh/wavesurfer.js#1340]
### Chrome 64.0.3282.186

I'm using the code below to produce PCM data in order to make something like this: https://codepen.io/entonbiba/pen/VPqvME (the data array)
```
var wavesurfer = WaveSurfer.create({
            container: '#waveform',
            scrollParent: true,
            barWidth: 4,
            fillParent: true,
            normalize: true
        });
        wavesurfer.load("https://freemusicarchive.org/file/music/ccCommunity/Rotten_Bliss/The_Nightwatchman_Sings/Rotten_Bliss_-_08_-_Timer_Erase.mp3");
        wavesurfer.on('ready', function() {
            wavesurfer.play();
            var pcmdata = wavesurfer.exportPCM(1024, 20000, true, 0);
            console.log(pcmdata);
        });
```
but all I get is an array full of `null`

```
[...,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0,0]
```

Is there something wrong with my code or is there something else I'm missing here? I am aware that there are other issues with similar problems. Just wondering if this is still true for version `2.0.4` or if it might be fixed on the next release.

Thanks!

**Comment by thijstriemstra** [comment]
@netgfx there's this note: https://github.com/katspaugh/wavesurfer.js/blob/master/src/wavesurfer.js#L1373

```
* @todo Update exportPCM to work with new getPeaks signature
```

so it's safe to say it's not working in v2..

**Comment by thijstriemstra** [comment]
@netgfx just tested it and it seems to work fine here with 2.0.4 (when I don't supply any params):

```
wavesurfer.exportPCM()
```

**Comment by netgfx** [comment]
Yes it seems to be working. However one last question, my waveform appears like this:
![untitled-2](https://user-images.githubusercontent.com/864248/36887919-f107543c-1dfb-11e8-9eb2-73496090f78d.png)

Which is different from the codepen here: https://codepen.io/entonbiba/pen/VPqvME
I am also adding an array of peaks on `load` and the other parameters are:
```
var wavesurfer = WaveSurfer.create({
            container: '#waveform',
            scrollParent: true
        });
```
any idea why it doesn' appear like the codepen example?

Thanks!

**Comment by netgfx** [comment]
Also it seems that the audio is no longer loading when I use the peaks parameter on the `load`
```
 wavesurfer.load("https://freemusicarchive.org/file/music/ccCommunity/Rotten_Bliss/The_Nightwatchman_Sings/Rotten_Bliss_-_08_-_Timer_Erase.mp3", peaks);
```
Although I see that on the source code there is the `load(url, peaks, preload, duration)` function

**Comment by netgfx** [comment]
My latest comments are because of `* @todo Update exportPCM to work with new getPeaks signature` ?
Otherwise it might be a bug.
