### ISSUE TITLE
Identify container

### ISSUE THREAD

**Issue by JairoFra** [katspaugh/wavesurfer.js#1341]
### Wavesurfer.js version(s):
1.2.3

I have several waves in my webpage and each has an image associated (a container's sibling). I would like to hide the image when reproduction finishes, but I don't know how to identify the wave that has finished. 

I have thought about something like this, but I didn't find a method to get the container.

myTrack.on('finish', function () {
          $(this).<b>¿getContainerMethod?</b>.next().css("display", "none");   
});

**Comment by thijstriemstra** [comment]
Hide the `<wave>` element.
