### ISSUE TITLE
Many players on page

### ISSUE THREAD

**Issue by deniskril** [katspaugh/wavesurfer.js#1349]
Hello,
How can i add two or many player in one page?

its my code:
```html
<script src="player/wavesurfer.min.js"></script>
<center><div class="container">
                <div class="demo">
                                <div id="waveform" style="width: 400px; border: 1px solid #6aa6cb">
                                                <progress id="progress" class="progress progress-striped" value="0" max="100"></progress>
                                </div>

                                <script>
                                                var ctx = document.createElement('canvas').getContext('2d');
                                                var linGrad = ctx.createLinearGradient(0, 64, 0, 200);
                                                linGrad.addColorStop(0.5, 'rgba(106, 166, 203, 1)');
                                                linGrad.addColorStop(0.5, 'rgba(183, 183, 183, 1.000)');
                                                var wavesurfer = WaveSurfer.create({
                                                container: '#waveform',
                                                waveColor: linGrad,
                                                progressColor: 'hsla(200, 100%, 30%, 0.5)',
                                                cursorColor: '#6aa6cb',
                                                normalize: true,
                                                pixelRatio: 1,
                                                height: 40,
                                                barWidth: 1});
                                                wavesurfer.on('loading', function (percents) {
                                                document.getElementById('progress').value = percents;});
                                                wavesurfer.on('ready', function (percents) {
                                                document.getElementById('progress').style.display = 'none';});
                                                wavesurfer.load('/previews/file');

                                </script>

                                <div class="controls"><br/>
                                                <div onclick="wavesurfer.playPause();"><b class="btn btn-primary">[Play / Pause]</b></div> 

                                </div>

                </div>

</div></center>
```

Thank you

**Comment by deniskril** [comment]
Hello,
How can i add two or many player in one page?

its my code:
`<script src="player/wavesurfer.min.js"></script>
<center><div class="container">

                <div class="demo">

                                <div id="waveform" style="width: 400px; border: 1px solid #6aa6cb">
                                                <progress id="progress" class="progress progress-striped" value="0" max="100"></progress>
                                </div>

                                <script>
                                                var ctx = document.createElement('canvas').getContext('2d');
                                                var linGrad = ctx.createLinearGradient(0, 64, 0, 200);
                                                linGrad.addColorStop(0.5, 'rgba(106, 166, 203, 1)');
                                                linGrad.addColorStop(0.5, 'rgba(183, 183, 183, 1.000)');
                                                var wavesurfer = WaveSurfer.create({
                                                container: '#waveform',
                                                waveColor: linGrad,
                                                progressColor: 'hsla(200, 100%, 30%, 0.5)',
                                                cursorColor: '#6aa6cb',
                                                normalize: true,
                                                pixelRatio: 1,
                                                height: 40,
                                                barWidth: 1});
                                                wavesurfer.on('loading', function (percents) {
                                                document.getElementById('progress').value = percents;});
                                                wavesurfer.on('ready', function (percents) {
                                                document.getElementById('progress').style.display = 'none';});
                                                wavesurfer.load('/previews/file');

                                </script>

                                <div class="controls"><br/>
                                                <div onclick="wavesurfer.playPause();"><b class="btn btn-primary">[Play / Pause]</b></div> 

                                </div>

                </div>

</div></center>`

Thank you

**Comment by thijstriemstra** [comment]
add multiple div's for waveform and create them using javascript?

**Comment by deniskril** [comment]
yes

**Comment by thijstriemstra** [comment]
Yes? Ok.
