### ISSUE TITLE
Two channel player

### ISSUE THREAD

**Issue by WernerDS** [katspaugh/wavesurfer.js#1350]
Is it possible to style the Canvas to look anything like this:
![call-recording-with-speaker-percentage](https://user-images.githubusercontent.com/13958753/37511139-6750f73c-2906-11e8-89ea-e2f05f7b04d6.png)
My settings are like this: (closest I can get it to above)

```javascript
var wavesurfer = WaveSurfer.create(
{ 
	   container: '#audio-spectrum',
            progressColor: "#444444",
            waveColor: "rgba(0,0,0,0.2)",
            cursorColor: "rgba(0,0,0,0.2)",
            splitChannels: true,
            barWidth: 2,
            fillParent: true,
            height: 60
});
```

**Comment by thijstriemstra** [comment]
Check custom renderer docs at bottom of page at https://wavesurfer-js.org/docs/ and implement your own renderer.

**Comment by thijstriemstra** [comment]
#1336 looks related.

**Comment by thijstriemstra** [comment]
No feedback, closing.
