### ISSUE TITLE
It cannot draw timeline when height more than 32767px

### ISSUE THREAD

**Issue by PotatoSmith** [katspaugh/wavesurfer.js#1354]
it a great plugin, but I met a issue, I draw lengthways timeline when height more than 32767px it cannot work. Do you have any limit？

**Comment by PotatoSmith** [comment]
@thijstriemstra wavesurfer1.4.0, chrome 65.0.3325.146, ubuntu14.04

**Comment by thijstriemstra** [comment]
@PotatoSmith use latest wavesurfer: 2.0.5 and reopen if the problem is still there.
