### ISSUE TITLE
"responsive" parameter is set to false by default

### ISSUE THREAD

**Issue by MoogyG** [katspaugh/wavesurfer.js#1356]
Wavesurfer.js version: 2.0.5

"responsive" parameter is set to false by default but documentation says it's true.

For me, it should be true by default so a code change is required.

**Comment by thijstriemstra** [comment]
@MoogyG where is this incorrect documentation?

**Comment by thijstriemstra** [comment]
Opened #1358 for this.

**Comment by thijstriemstra** [comment]
Fixed.
