### ISSUE TITLE
Basic example not working, please help

### ISSUE THREAD

**Issue by matt3224** [katspaugh/wavesurfer.js#1359]
https://codepen.io/matt3224/pen/VxKzzG?editors=1010

Hey why on earth doesn't the example above work? I can see that when I click A or B that it gets the file and increases the page size, yet no waveform

**Comment by entonbiba** [comment]
@matt3224 the server that is serving the mp3 files don't have "Access-Control-Allow-Origin" set and chrome blocks it since it's not coming from codepen domain.

https://codepen.io/anon/pen/yjadjW
