### ISSUE TITLE
Peaks exported from server are flat

### ISSUE THREAD

**Issue by netgfx** [katspaugh/wavesurfer.js#1360]
Hello, I try to export Peaks from audiowaveform with the recommended parameters:

`audiowaveform -i some-file.mp3 --pixels-per-second 10 -b 8 -o some-file.json`

but when I import the exported array of values into wavesurfer the result is a straight waveform like on this issue: https://github.com/katspaugh/wavesurfer.js/issues/1230#issuecomment-336590190

But I thought that was fixed on 2.0.0+

### Code needed to reproduce the issue: 
```
var wavesurfer = WaveSurfer.create({
            container: audioEl,
            scrollParent: true,
            barWidth: 4,
            waveColor: 'rgba(119, 119, 119, 0.5)',
            progressColor: 'rgba(255, 164, 0, 1)',
            fillParent: true,
            normalize: false,
            backend: "MediaElement",
            mediaType: "audio",
            barHeight: 6
        });

        var audio = new Audio(source);
        audio.preload = "none";
        audio.crossOrigin = "anonymous";

        wavesurfer.load(source, peaks, "none");
        var audioCtx = new(window.AudioContext || window.webkitAudioContext);
        var mediaSource = audioCtx.createMediaElementSource(audio);
        mediaSource.connect(audioCtx.destination);

wavesurfer.on('ready', function() {
   wavesurder.play();
});
```

**Comment by thijstriemstra** [comment]
@netgfx I'm using these settings: https://github.com/collab-project/videojs-wavesurfer/pull/38#issuecomment-385286097

**Comment by netgfx** [comment]
thanks will give it a try!

**Comment by thijstriemstra** [comment]
Check the FAQ for the official docs: https://wavesurfer-js.org/faq/
