### ISSUE TITLE
Region Sizing Mouse Detection

### ISSUE THREAD

**Issue by bloom510** [katspaugh/wavesurfer.js#1361]
Is there any way to increase the size of the area that initializes the length increase/decrease drag tool for a given region? It's currently very hard to position the cursor in such a small area and even harder with touch.

**Comment by awenger63** [comment]
Hi @bloom510, did you see if zoom can help you ? I use it to get fine seektime on the wave. But I don't have touch solution.

**Comment by thijstriemstra** [comment]
No feedback from @bloom510, closing.
