### ISSUE TITLE
Is there a way to draw a straight line instead of the wave form?

### ISSUE THREAD

**Issue by harvestmedia** [katspaugh/wavesurfer.js#1366]
Hi,

I have 2 views for my player element, large and compact. In the compact view I would like to just draw a straight line instead of the wave form. 

I've tried        

        playerCore.Player.params.height = 8;

        playerCore.Player.params.barWidth = 1000;

        playerCore.Player.drawer.clearWave();

        playerCore.Player.drawBuffer();

But the problem with this approach is that if the beginning of the audio doesn't have anything the waveform ends up looking empty. Also if the width goes above 1000 we start seeing gaps.

Any help would be appreciated. Thanks

**Comment by GitHubRakeshSharma** [comment]
Try giving the load function an array like this: [0,0]. this should do the trick
