### ISSUE TITLE
Loading a second audio file freezes the waveform in safari mac

### ISSUE THREAD

**Issue by matt3224** [katspaugh/wavesurfer.js#1367]
### Wavesurfer.js version(s):
2.0.5

### Browser version(s):
Safari 11.1

### Code needed to reproduce the issue:
`http://dev.topline-music.com`
password is `Cookies!`

### Use behaviour needed to reproduce the issue:
[waveform.zip](https://github.com/katspaugh/wavesurfer.js/files/1987777/waveform.zip)

The above zip is a video which shows how to recreate the issue. This works fine in Chrome, I have gone through and stripped out a lot of my code and the issue will persist, yet if i try a super basic example in codepen it works ok. I'm really hoping that someone can take a look even if it is just to suggest what it could be or what I could do to resolve it.

Thank you!

**Comment by matt3224** [comment]
Ok I have made a test case https://codepen.io/matt3224/pen/ELEpoz?editors=0010

you'll need to click through the numbers and it will freeze but continue to play audio.

its intermittent though so keep playing a few seconds of each track until it freezes, for me it will do it if i do like 1, 2, 3, 1, 2

this is in safari only it seems

**Comment by thijstriemstra** [comment]
~~that~~ safari sucks

**Comment by Jun711** [comment]
@matt3224 your codepen example doesn't seem to play
However, I also have a similar problem with the waveform on safari. On Chrome, it works fine.
