### ISSUE TITLE
When I use TimelinePlugin, I show the overflow in scale. How do I solve this problem?

### ISSUE THREAD

**Issue by CCL1** [katspaugh/wavesurfer.js#1368]
![qq20180514-165736](https://user-images.githubusercontent.com/25790636/39987640-ef24fed2-5797-11e8-8f8a-0bae307f2b9b.png)

**Comment by awenger63** [comment]
@CCL1 I don't have this problem or I'm not sure I understand it. If your problem isn't solve and you need help, please send us more information (version, code of implementation HTML and script ...)

**Comment by thijstriemstra** [comment]
no feedback, closing.
