### ISSUE TITLE
Wavesurfer.microphone guides confusing

### ISSUE THREAD

**Issue by IdiosApps** [katspaugh/wavesurfer.js#1373]
At the following link, 1) js src is out of date (1.2.3 -> 2.0.5), and 2) the .js code didn't work for me:
https://wavesurfer-js.org/plugins/microphone.html

The code that did work for me is at:
https://github.com/katspaugh/wavesurfer.js/blob/master/example/microphone/app.js

It would be worth clearing these things up as it took me a few hours to figure out how to fix things.

**Comment by IdiosApps** [comment]
and http://wavesurfer-js.org/example/microphone/ links to  http://wavesurfer-js.org/plugin/wavesurfer.microphone.js which gives 404

**Comment by thijstriemstra** [comment]
Thanks for the report, will fix this. This is basically a duplicate of #1309, closing.

**Comment by thijstriemstra** [comment]
Example's now updated on the site.
