### ISSUE TITLE
Microphone plugin in iOS 11 not working (example page)

### ISSUE THREAD

**Issue by hburgund** [katspaugh/wavesurfer.js#1377]
I am having trouble implementing the microphone plugin on iOS 11. It works great on every other platform I have tried, including Chrome in Android, but iOS is a problem.

I have tried many different implementations myself, but the fact that the demo page for the microphone plugin doesn't work for me on iOS 11.3 makes me wonder if this is a problem across the board, not just for me.

https://wavesurfer-js.org/plugins/microphone.html

For me, the page asks for access to the microphone as expected and indicates that mic access is live (console states `Device ready!`), but no waveform is displayed when audio input is presented. And when I tap the button to stop the mic, I get this error in the console:
```
TypeError: this.stream.stop is not a function. (In 'this.stream.stop()', 'this.stream.stop' is undefined)
```
I am assuming that this error is because I am trying to stop the stream when no stream has previously been created?
Can anyone get this to work properly? Is this a known issue related to iOS?
Thanks.

**Comment by thijstriemstra** [comment]
@hburgund I think this should work, but take a look at safari issues: https://github.com/katspaugh/wavesurfer.js/search?q=safari&type=Issues

**Comment by hburgund** [comment]
Hi @thijstriemstra...thx for the response. I have looked at some of these issues already with no luck, but I will look again to make sure I haven't missed anything.

Can you confirm that the official example for the mic plugin does in fact work in mobile safari for you? I only have one iOS device running iOS 11, so it is certainly possible that for some reason that device is behaving abnormally. I am working on getting more devices to test and will report back ASAP.

**Comment by thijstriemstra** [comment]
I don't have a device to test it on (atm).

**Comment by hburgund** [comment]
ah, no problem! I will do more testing and if anyone else who sees this wants to add data points, that would be great too. :-)

**Comment by hburgund** [comment]
sure, I can do this and see what I can come up with.

FWIW, I have already done experiments with using wavesurfer to display the waveform of an audio file that was just recorded in the browser using mic access. I have gotten this to work on all major platforms, including mobile Safari in iOS 11. On all other platforms, the mic plugin displays the real-time audio input, but in mobile Safari, nothing is displayed in real-time though the waveform is displayed after the recording is completed.

This is a very rough dev situation right now, but here is my test page: 

https://halseyburgund.com/dev/rw-web-framework/example/

Scroll down to #2 Make Recording; after initializing the recorder, you can make a recording and see wavesurfer, both the mic plugin and the core waveform display.

**Comment by thijstriemstra** [comment]
> FWIW, I have already done experiments with using wavesurfer to display the waveform of an audio file that was just recorded in the browser using mic access.

Also check the videojs-record (and videojs-wavesurfer) projects!

**Comment by hburgund** [comment]
thx for those links. looks like videojs-record and videojs-wavesurfer unfortunately have the same problem in that they don't visualize the mic input in mobile safari. The recorder does work, like my example, and the waveform is displayed after recording is completed; just no real-time display. The console prints out statements that suggest it is working like "wavesurfer.js microphone plugin enabled." and "Start microphone". Weird.

It's looking more and more like this is a universal problem; I will see if I can figure it out and will post back here if I make any substantive progress. Would love any ideas anyone else might have to try.

**Comment by thijstriemstra** [comment]
@hburgund check #1509, should work..

>  looks like videojs-record and videojs-wavesurfer unfortunately have the same problem in that they don't visualize the mic input in mobile safari.

with new wavesurfer.js release that should be fixed there as well.
