### ISSUE TITLE
change start second and format on timeline plugin

### ISSUE THREAD

**Issue by awenger63** [katspaugh/wavesurfer.js#1380]
New needs on Timeline plugin :
 - change start second by real value instead of 0. This case is for use this plugin for a recording, I would like to begining the Timeline by the rigth hour of the record begin.
 - change Timeline format to add hour of the day corresponding at the record date.
see this example screenshot :
![image](https://user-images.githubusercontent.com/16153617/40440504-92d13f6e-5ebe-11e8-9c88-e3e42a5541ca.png)

Could you created a pull request for this, I have make local code can be share with you ? Thanks

**Comment by thijstriemstra** [comment]
> Could you created a pull request for this, I have make local code can be share with you ? Thanks

Pull requests are always welcome!

**Comment by thijstriemstra** [comment]
@awenger63 this should now be possible, see https://github.com/katspaugh/wavesurfer.js/commit/81a1241fc06b35968f3a6cd20ce7c699dd33f242

**Comment by awenger63** [comment]
OK @thijstriemstra. But to know this need alaways exit. in #1458 the start time cannot be change and time line cannot include hour ( see coment : "Here we format as M:SS.frac").
Today I always use a local patch on v2.0.6. because i'm not use npm.  When I do the migration to new version I will post a new PR to do that ...

**Comment by thijstriemstra** [comment]
>  When I do the migration to new version I will post a new PR to do that ...

@awenger63, sounds good.
