### ISSUE TITLE
'region-in' fire multiple times

### ISSUE THREAD

**Issue by jambonbill** [katspaugh/wavesurfer.js#1386]
### Wavesurfer.js version(s):
1.4.0 to 2.0.5 

### Browser version(s):
Firefox 60.0.1 and Chrome Version 63.0.3239.132 (Official Build) (64-bit)
on Ubuntu/Linux

note: I also observe the problem on a Mac (w recent browser)
note: 'region-out' also fire multiple times

### Code needed to reproduce the issue:
https://codepen.io/jambonbill/pen/LrZxqo

``wavesurfer.on('region-in', function(region){console.log('region-in')});``
``wavesurfer.on('region-out', function(region){console.log('region-out')});``

### Use behaviour needed to reproduce the issue:
create a region and 'play'.

**Comment by thijstriemstra** [comment]
Just tested codepen with Firefox 65 and could not reproduce this.
