### ISSUE TITLE
not loading complete audio file

### ISSUE THREAD

**Issue by edward2990** [katspaugh/wavesurfer.js#1387]
I'm using wavesurfer into my angular4 application and all is fine but the audio isn't loading complete, i'm using a local mp3 file. it loads the first 5 seconds only of the audio and the audio is about 3 minutes

**Comment by thijstriemstra** [comment]
@edward2990 without any example code/files, this will be hard to fix.

**Comment by thijstriemstra** [comment]
No feedback, closing.
