### ISSUE TITLE
Wavesurfer and Video Element source sharing

### ISSUE THREAD

**Issue by yarandoo** [katspaugh/wavesurfer.js#1388]
Hi, 

Thanks for this great library!

I am currently using WaveSurfer to analyse the audio of some short videos - the problem is that the browser is actually downloading the files twice. One for the Html5 Video Element, and one for analysing it with wavesurfer.

Is there any way I could optimize this, and have the browser and wavesurfer be using the same media file?

Many Thanks,

Esteban

**Comment by thijstriemstra** [comment]
download it once, after that it should be cached.
