### ISSUE TITLE
Looking for a Developer to help us build on Wavesurfer

### ISSUE THREAD

**Issue by hang1fire** [katspaugh/wavesurfer.js#1394]
We've just launched our new webapp - Alitu: The Podcast Maker (alitu.com) - designed to help podcasters create their shows much more easily. We've heavily integrated wavesurfer as a part of the tool, but our next stage is to start to customise it a LOT to make it even more useful to our audience. We're looking for a developer to help us with that!

We're looking for someone who knows Wavesurfer inside-out and is confident in making big changes to the UX and the design of the tool. If you can also work with React, then even better.

If you have at least a day per week available, or anything up to full-time, then get in touch. You'll find our full details at - https://www.thePodcastHost.com/contact - or get back to me here to start the conversation.

**Comment by thijstriemstra** [comment]
You can send me an email at my git commit email address, we can go from there.

**Comment by hang1fire** [comment]
Thanks for that, I'm afraid I can't spot the email address anywhere though. Could you copy it in here?

**Comment by hang1fire** [comment]
Ok, done, thanks

**Comment by thijstriemstra** [comment]
Assuming this is outdated now, closing.
