### ISSUE TITLE
Bugs,wave static in iOS after interact.

### ISSUE THREAD

**Issue by Joudee** [katspaugh/wavesurfer.js#1398]
#### Then,the wave can't move and the audio is still playing.Another,the finish methods can't be trigger.

**Comment by thijstriemstra** [comment]
Search for `safari` in the issues, this has been reported before and is a known issue I think.

**Comment by Joudee** [comment]
I have fixed this bug.To set 'this.scriptNode.onaudioprocess = () => {}' in wavesurfer.js.The onaudioprocess can't be null.
