### ISSUE TITLE
Zoom rendered and performance

### ISSUE THREAD

**Issue by awenger63** [katspaugh/wavesurfer.js#1399]
Hi, 
Two issues : when I zoom on wavesrufer loaded with peaks, there are rendered issue : blank zone or duplicate peaks on new canvas depend of zoomLevel.

![image](https://user-images.githubusercontent.com/16153617/41603105-97403e0a-73dc-11e8-920c-dfb41a101469.png)
![image](https://user-images.githubusercontent.com/16153617/41603220-d212e4a6-73dc-11e8-93cd-79d8790fe23d.png)

When increase zoom, there si bad performance rendered,
- on Chrome : [Violation] 'requestAnimationFrame' handler took xxxxms
- on FireFox : shutdown process and memory leak ! 

There currently existing rendering issue when zooming and scroll to get all peaks left and right : #1261 
See @jamiefaye and my solution to get all wave rendered.

I Need to merge solution between zooming and scrolling use and without this rendered and bad performance.

### Browser version(s):
Chrome v67, Firefox 60

### Code needed to reproduce the issue:
Apply zoom on waveform with peaks. I do this with mouse wheel and timeOut between scroll=>

```javascript
var zoomLevel;
wavesurfer.on('ready', function () {
// define inital zoom level
                    zoomLevel = Math.trunc(wavesurfer.drawer.getWidth() / wavesurfer.getDuration() / wavesurfer.params.pixelRatio);
                    wavesurfer.container.addEventListener('wheel', wheelZoomHandler);
                });
```

```javascript
var zoomStep = 2;
    var zoomTimeOut;
    // initialise start NO zoom 
 wavesurfer.zoom();
    function wheelZoomHandler(e) {
        var deltaY = 0;
        e.preventDefault();
        if (e.deltaY) { // FireFox 17+ (IE9+, Chrome 31+?)
            deltaY = e.deltaY;
        } else if (e.wheelDelta) {
            deltaY = -e.wheelDelta;
        }
        // Update the bg size:
        clearTimeout(zoomTimeOut);
        if (deltaY &lt; 0) {
                zoomLevel += zoomStep;
                zoomTimeOut = setTimeout(function(){
                    console.log('Zoom increase : ' + zoomLevel);
                    wavesurfer.zoom(zoomLevel);
                },200);
        } else {
            if (zoomLevel &gt; Math.trunc(wavesurfer.drawer.getWidth() / wavesurfer.getDuration() / wavesurfer.params.pixelRatio)){ 
                zoomLevel -= zoomStep;
                zoomTimeOut = setTimeout(function(){
                    console.log('Zoom decrease : ' + zoomLevel);
                    wavesurfer.zoom(zoomLevel); 
                },200);
            } else { // stay zoomlevel at start value
                zoomLevel = Math.trunc(wavesurfer.drawer.getWidth() / wavesurfer.getDuration() / wavesurfer.params.pixelRatio);
                wavesurfer.zoom(); // reinit no zoom
            }
        }
    };
```

### Use behaviour needed to reproduce the issue:

Load file with peaks (example of 30 minutes with little data per second)
Use mouse wheel to increase or decrease zoom and let see rendered, navigator and computer UC/memory  !

I'm working on a solution, but all idea and optimization are welcome ;-)

**Comment by thijstriemstra** [comment]
> I'm working on a solution, but all idea and optimization are welcome ;-)

any news?
