### ISSUE TITLE
Current time indicator does not work in Chrome Version 26.0.1410.64 m 

### ISSUE THREAD

**Issue by everthis** [katspaugh/wavesurfer.js#14]
![capture](https://f.cloud.github.com/assets/3142886/536892/a965b984-c162-11e2-8b78-da2078b1961c.png)

The current time indicator does not work,besides,the waveform is always in this light pink style,which should become darker when the audio is being playing.

**Comment by samyoung88** [comment]
I am also experiencing this issue. The cursor moves on some but not on other. The currentTime is not updating.
