### ISSUE TITLE
Visualizing real-time waveform

### ISSUE THREAD

**Issue by pudg** [katspaugh/wavesurfer.js#1402]
Has anyone tried to visualize real-time audio comming in from a python flask app? I'm currently capturing audio using pyaudio and flask to stream in byte-form, but everything i've found that uses wavesurfer looks like it needs a prerecorded audio file, or the microphone pluggin. Alternatively, if anyone knows a different library to use for this task, I'd greatly appreciate it. Thanks!

**Comment by thijstriemstra** [comment]
@pudg you can feed and redraw your data like this:

```javascript
this.wavesurfer.empty();
this.wavesurfer.loadDecodedBuffer(yourDataChunk);
```

**Comment by thijstriemstra** [comment]
no feedback, closing.

**Comment by humblecoder** [comment]
Is there any way to use this in real-time in combination with `webkitSpeechRecognition`?  I'm looking to fudge a waveform while "capturing" speech.  In your previous answer, I'm not sure what `yourDataChunk` would correlate to?  🤔
