### ISSUE TITLE
Cannot load waveform from external filesystem on Android

### ISSUE THREAD

**Issue by JRR-OSU** [katspaugh/wavesurfer.js#1408]
Hi there. So I'm trying to load a waveform with a file from the external device filesystem on android. I've double and triple checked my permissions. Due to my app being a hybrid one, I'm able to load files from the external file system (that are not loaded through wavesurfer) just fine. I have wavesurfer loading correctly if I load from the app's `www/ `folder, however an `XHR error ` is returned when loading from this.file.externalRootDirectory.  The error returned has no message and no code, and is preceded by a message which says that the GET request was successful. 

How can I fix this issue and be able to load audio files from the device file system on android?

### Wavesurfer.js version(s):

Latest at the time of writing.

### Browser version(s):

Crosswalk webview on android.

### Code needed to reproduce the issue:

```
if(this.platform.is('android')){
          correctedPath = this.file.externalRootDirectory + 'test.3gp';
          this.wavesurfer.load(correctedPath);

}
```

### Use behaviour needed to reproduce the issue:

Run the following code in an Angular (Ionic) Cordova mobile app on android. The waveform will not load.

**Comment by thijstriemstra** [comment]
> however an XHR error is returned when loading from this.file.externalRootDirectory. The error returned has no message and no code, and is preceded by a message which says that the GET request was successful.

can you add a screenshot?

**Comment by JRR-OSU** [comment]
@thijstriemstra Sure. I removed some info in the console logs that is just other debug info for my application (not related to waveform loading).

<img width="1920" alt="bug" src="https://user-images.githubusercontent.com/12603147/42176868-76b415aa-7df8-11e8-95fc-85a0b741f287.PNG">

**Comment by JRR-OSU** [comment]
@thijstriemstra  A closer look... 
![image](https://user-images.githubusercontent.com/12603147/42176938-b395042a-7df8-11e8-90aa-94beb05fa76c.png)

**Comment by JRR-OSU** [comment]
@thijstriemstra I believe I have fixed it. On Android only, waveforms must be loaded with the cdvfile:// url.

I'm not sure why this is, but the Ionic Native File plugin needs much better documentation on this.

**Comment by thijstriemstra** [comment]
Thanks for feedback. Closing.
