### ISSUE TITLE
Propose Logo

### ISSUE THREAD

**Issue by mirzazulfan** [katspaugh/wavesurfer.js#1409]
Hi sir @katspaugh . I'm graphic designer and an open source enthusiast. I would like to contribute to your awesome project. I've designed a logo for your project and its free. if you need something else i'll make it for your project. Thank you
Best Regard. Mirza Zulfan
![wavesurfer](https://user-images.githubusercontent.com/36124339/42202556-0a8a141e-7ec6-11e8-90b4-46cdbbf7a41e.png)

**Comment by katspaugh** [comment]
Hi Mirza!
Thanks a lot for offering your help!
I'd rather see a stylized waveform on the logo, or an actual tidal wave 🌊or a surf board 🏄‍♂️.

**Comment by mirzazulfan** [comment]
Thank for your response sir. I'll make it and shown it to you.

**Comment by mirzazulfan** [comment]
Thanks for your feedback. :) ... i'll try to make it better. :)

**Comment by thijstriemstra** [comment]
awesome initiative @mirzazulfan

**Comment by entonbiba** [comment]
What about this:

![image](https://user-images.githubusercontent.com/5193884/43679720-5255c82e-97f8-11e8-8a03-1660c2fe9b71.png)

**Comment by katspaugh** [comment]
Great idea, @entonbiba! Visually, I like the upper part of the wave.
<img width="156" alt="screen shot 2018-08-05 at 10 54 54" src="https://user-images.githubusercontent.com/381895/43684313-3980895a-989e-11e8-9a70-4c00182515dc.png">
Maybe we could go minimalistic and leave just that?

**Comment by entonbiba** [comment]
@katspaugh yea we can do that, I'll convert it into svg as well today. 
![wavesurfer](https://user-images.githubusercontent.com/5193884/43734758-c06eacf6-9986-11e8-9a63-e4c0f928554f.jpg)

**Comment by thijstriemstra** [comment]
+1
