### ISSUE TITLE
Spectrogram renderer

### ISSUE THREAD

**Issue by julj** [katspaugh/wavesurfer.js#1410]
Is there any plan to make a spectrogram renderer, i.e. to get the spectrogram instead of the waveform in the container specified in `var wavesurfer = WaveSurfer.create({ ... })`?

**Comment by thijstriemstra** [comment]
@julj there's the spectrogram plugin: https://wavesurfer-js.org/plugins/spectrogram.html

**Comment by julj** [comment]
I am aware of the spectrogram plugin but if I can't see how to get the spectrogram as the main audio visualization. It seems that it is only possible to have it **in addition** to the waveform (i.e., in another container). Am I wrong?

**Comment by thijstriemstra** [comment]
You can hide the original waveform using CSS/javascript.

**Comment by julj** [comment]
Well, I know that I can hide it, but that does not answer my question.
To clarify further my question, what I want is a player with the spectrogram as the visualization. I want to be able to click on the spectrogram to set the cursor position, select a segment on the spectrogram to define a region... well, everything that can be done with the default renderer...
According to the [example](https://wavesurfer-js.org/plugins/spectrogram.html), and the code, of the spectrogram plugin, the spectrogram is just an image with no event listener or cursor or anything.

**Comment by julj** [comment]
A spectrogram renderer can be found [here](https://github.com/BlaiMelendezCatalan/BAT/blob/master/annotation_tool/js/annotator/src/wavesurfer.drawer.extended.js).
