### ISSUE TITLE
Audio Decibels per Channel

### ISSUE THREAD

**Issue by waasoojoms** [katspaugh/wavesurfer.js#1411]
Hello Everyone. 

I currently have a Project that for listening a sound. I already got the Balance of left and right channels using panner but my problem is i cannot get the decibels for each channel (left and right).

 Do you know how to get the decibels of the sound?

Thanks.

**Comment by Guisch** [comment]
As Decibels is an audio power mesurement, you can't get it from wavesurfer since it depends on your computer volume, on your audio card amplification and on your speaker.
So either you know each of this caracteristics and do heavy maths to get them, either you use a mic a measure it.

**Comment by thijstriemstra** [comment]
closing, no feedback.

**Comment by mderoide** [comment]
> 

Hello,
Could you tell me how did you get the Balance of left and right channels using panner ?
Thanks,
Martin
