### ISSUE TITLE
SyntaxError: bad method definition (wavesurfer.js)

### ISSUE THREAD

**Issue by julj** [katspaugh/wavesurfer.js#1412]
I am trying to run an example from wavesurfer.js with a local clone of the code (commit  00b1e8185c9987ebaa950188b9bc060b31967626) and the code shown below, but I get the following error (Firefox 60.0.2 on Ubuntu 16.04):

`SyntaxError: bad method definition (wavesurfer.js:179:4)`

Any idea?

<b>index.html</b>

```
<script type='module'>
    import WaveSurfer from "./js/wavesurfer.js/src/wavesurfer.js"
</script>
<script src="js/zoom.js"></script>

<div id="waveform"></div>

...
```

<b>zoom.js</b>

```
var wavesurfer = WaveSurfer.create({
    container: '#waveform',
    waveColor: 'red',
    progressColor: 'purple'
});
    
wavesurfer.load('https://ia902606.us.archive.org/35/items/shortpoetry_047_librivox/song_cjrg_teasdale_64kb.mp3');

    ...
```

**Comment by thijstriemstra** [comment]
Follow these instructions: https://github.com/katspaugh/wavesurfer.js#development

Basically: `npm run start`

**Comment by thijstriemstra** [comment]
@julj you can use it with the script tag. The npm run command ensures all seperate source files are stitched together into one wavesurfer.js file. If you don't change the source code you can simply use the CDN version, and there's no need to use the npm run script: `<script src="//cdnjs.cloudflare.com/ajax/libs/wavesurfer.js/2.0.6/wavesurfer.min.js"></script>`

**Comment by julj** [comment]
If I use the script tag to include wavesurfer.js, I get the error shown in my first message.
I reformulate my question then: How can I use the script tag to include a local version of wavesurfer.js cloned from the repository, untouched, without using npm?

**Comment by thijstriemstra** [comment]
@julj 

* checkout code
* npm install
* npm run build

Resulting wavesurfer.js and wavesurfer.min.js can be found in dist/ folder.

**Comment by julj** [comment]
Ok, so I cannot include directly the file wavesurfer.js which is in src/. I have to use npm.
Thanks.

**Comment by thijstriemstra** [comment]
you also have to use npm to install the build tools, correct.
