### ISSUE TITLE
Audio is not loading on iOS devices (Ionic 3)

### ISSUE THREAD

**Issue by IgorSamer** [katspaugh/wavesurfer.js#1415]
I'm using [wavesurfer.js](https://wavesurfer-js.org/) for audios on my app and it works great on Android (printscreen below).

<img width="308" alt="captura de tela 2018-07-20 as 18 08 31" src="https://user-images.githubusercontent.com/10137870/43026170-e9166110-8c4a-11e8-8074-e2cb1e19f428.png">

And if I tap the play icon all works fine.

But, on iOS (emulator and real devices) looks like audio is not loading. I tried to test with `ionic serve` on Safari and get CORS error. So, I changed my CORS configuration of my AWS S3 bucket to `<AllowedOrigin>*</AllowedOrigin>` and the error seemed to have been solved, at least on Safari browser. Then, I run `ionic cordova build ios` again and on emulator the audio was loaded and waves was drawn, but on real devices (tested on iPhone's with iOS 11.4) the error is still there (error I guess, because waveform visualization is not showed, and tapping the play icon nothing occours). (printscreen below)

<img width="365" alt="captura de tela 2018-07-20 as 18 06 08" src="https://user-images.githubusercontent.com/10137870/43026179-f6251f18-8c4a-11e8-94b0-d107004f6a1f.png">

Excerpt from my code related to loading audio:

    ngAfterViewInit() {
      this.audio = this.audio.nativeElement;

      this.ws = WaveSurfer.create({
          container: this.audio,
          waveColor: "#555555",
          progressColor: "#c51b63",
          barHeight: 4,
          height: 30,
          cursorColor: "#c51b63"
      });
      
      this.ws.load(this.audioSource); // Source loaded from my S3 bucket
    }

Remembering that not works only on iOS, but on Android (and now on Xcode iOS emulator too) works perfectly. With exactly same code.

So, do you have any idea what it can be? Can it be a problem between iOS and XHR used to load the file, or anything else?

**Comment by dezea** [comment]
Make sure you are not trying to load .ogg audio files since Safari does not natively support it. Other than that, in my tests it worked just fine on iOS with .mp3 and .wav. Not the same story with IE though, which is a pitty.

**Comment by thijstriemstra** [comment]
@IgorSamer try this approach: https://github.com/katspaugh/wavesurfer.js/blob/bacb41d0b33d882e8b557ee6875a276f1d80dc85/plugins/microphone.js

Basically ios needs an audiocontext that is created after a click or tap.

**Comment by thijstriemstra** [comment]
no feedback, closing.

**Comment by entonbiba** [comment]
@IgorSamer ios requires user interaction for audio to be played, have a look here how to do that:
https://www.entonbiba.com/lab/wavesurfer/2007.html
