### ISSUE TITLE
How to control volume of two channels

### ISSUE THREAD

**Issue by asystemsaus** [katspaugh/wavesurfer.js#1418]

**Comment by thijstriemstra** [comment]
@asystemsaus what have you tried so far?

**Comment by asystemsaus** [comment]
Is it even possible to achieve what i'm trying to do ?
I need to split the stereo file into 2 channels, control the gian for each and play back as stereo.  
I also need to play back in mono. but I think i'd be able to work that bit out myself

**Comment by asystemsaus** [comment]
Tried a few more things:
         wavesurfer = WaveSurfer.create({
             container: '#waveform',
             waveColor: 'darkorange',
             progressColor: 'purple',
            splitChannels: true,
            mediaControls: true,
            height: wavesize,
            });

          const splitter = wavesurfer.backend.ac.createChannelSplitter(2);
          const merger = wavesurfer.backend.ac.createChannelMerger(2);
          const leftGain = wavesurfer.backend.ac.createGain();
         const rightGain = wavesurfer.backend.ac.createGain();
    
          splitter.connect(leftGain, 0);
          splitter.connect(rightGain, 1);
....
      wavesurfer.on('audioprocess', function() {
           if (wavesurfer.isPlaying()) {
            var speed;
            var totalTime = wavesurfer.getDuration()
            var minutes = Math.floor(totalTime / 60);
          var seconds = totalTime % 60;
          currentTime = wavesurfer.getCurrentTime();
          var currentminutes = Math.floor(currentTime / 60);
          var currentseconds = currentTime % 60;
          remainingTime = totalTime - currentTime;
          var remainingminutes = Math.floor(remainingTime / 60);
          var remainingseconds = remainingTime % 60;
          document.getElementById('time-total').innerText = minutes + " Minutes :" + seconds.toFixed(1);
          document.getElementById('time-current').innerText = currentminutes + " Minutes :" + currentseconds.toFixed(1);
          document.getElementById('time-remaining').innerText = remainingminutes + " Minutes :" + remainingseconds.toFixed(1);
        }
   
       var volumeslider = document.querySelector('#volumeslider');
          volumeslider.oninput = function() {
            var volumeLevel = Number(volumeslider.value);
            wavesurfer.setVolume(volumeLevel);
          };
        var volumeleftslider = document.querySelector('#volumeleftslider');
        volumeleftslider.oninput = function() {
          var volumeleftLevel = Number(volumeleftslider.value);
          leftGain.gain.value = volumeleftLevel;
          console.log("Left vol " + volumeleftLevel);
        };
        var volumerightslider = document.querySelector('#volumerightslider');
        volumerightslider.oninput = function() {
          var volumerightLevel = Number(volumerightslider.value);
          rightGain.gain.value = volumerightLevel;
          console.log("Right vol " + volumerightLevel);
        };
        wavesurfer.backend.setFilters([splitter, leftGain, rightGain, merger]);
      });
Current times and normal volume work beautifully. 
I can see the values change in the console but its not being applied to the seperate channels.
Overall volume works ok as expected.

at one point during my experimenting i managed to get both left/right sliders to control just one channel. But the other channel was muted.
I'm close but still need some advice. if anyone else out there has managed to get left and right channel volume working i'd love to hear from you !

**Comment by kavishatalsania** [comment]
Try this:

this.splitter = this.wavesurfer.backend.ac.createChannelSplitter(2);
this.merger = this.wavesurfer.backend.ac.createChannelMerger(2);
this.leftGain = this.wavesurfer.backend.ac.createGain();
this.rightGain = this.wavesurfer.backend.ac.createGain()
this.splitter.connect(this.leftGain, 0);
this.splitter.connect(this.rightGain, 1);
this.leftGain.connect(this.merger, 0, 0);
this.rightGain.connect(this.merger, 0, 1);
this.wavesurfer.backend.setFilters([this.splitter, this.leftGain, this.merger]);

muteLeftChannel() {
    this.leftGain.gain.value = 0
}

muteRightChannel() {
    this.rightGain.gain.value = 0
}

Also, make backend 'WebAudio'. This will not work with backend 'MediaElement'.
