### ISSUE TITLE
support streaming?

### ISSUE THREAD

**Issue by itamaker** [katspaugh/wavesurfer.js#1419]

**Comment by entonbiba** [comment]
it's possible, do you have any code you've tried?

**Comment by bradley-varol** [comment]
> it's possible, do you have any code you've tried?

Care to explain how this is possible?

**Comment by JPKramer707** [comment]
I argue that it is impossible, and I hereby challenge all collaborators to prove otherwise, preferably with a pull request containing documentation and example code.

**Comment by killia15** [comment]
Curious - has anyone tried: https://stackoverflow.com/questions/35735278/how-to-draw-a-waveform-of-an-audio-stream-in-html5
