### ISSUE TITLE
[QUESTION] Can't access wavesurfer-js.org

### ISSUE THREAD

**Issue by maitrungduc1410** [katspaugh/wavesurfer.js#1421]
Does anyone here can access wavesurfer-js.org. It seems like its server is down? I want to see it api and methods but cannot
Thank you!

**Comment by swampthang** [comment]
I noticed this yesterday and still am unable to access the site. It's a bit of a pain, but you can access the docs via this branch...

https://github.com/katspaugh/wavesurfer.js/tree/gh-pages

**Comment by maitrungduc1410** [comment]
you saved my day!
Thank you!

**Comment by katspaugh** [comment]
Sorry guys, I forgot to renew the domain. Will set up auto-renewal and an alert to avoid this in future. Thanks!
