### ISSUE TITLE
Uncaught (in promise) DOMException: Unable to decode audio data

### ISSUE THREAD

**Issue by scottgrobinson** [katspaugh/wavesurfer.js#1422]
### Use behaviour needed to reproduce the issue:

https://apps.scoutradio.org.uk/CorenellKeepOnJumpin.mp3

When using the above file (and a few others that I'm not able to recall at present) I get the DOMException - Unable to decode audio data, however, the audio player itself is able to play the file without issue.

Is there a problem with the file that wavesurfer does not like?

**Comment by thijstriemstra** [comment]
@scottgrobinson can you try running the `ffprobe` tool on the file and paste the output here? ffprobe is part of ffmpeg.

**Comment by scottgrobinson** [comment]
@thijstriemstra Looks like header is missing - Ran it through mediainfo etc but didn't think of ffprobe.

[mp3float @ 000001b4ca7b0a80] Header missing
    Last message repeated 9 times
[mp3 @ 000001b4ca31dbc0] Estimating duration from bitrate, this may be inaccurate
Input #0, mp3, from 'C:\Users\Scott Robinson\Downloads\Corenell - Keep On Jumpin.mp3':
  Duration: 00:02:57.11, start: 0.000000, bitrate: 320 kb/s
    Stream #0:0: Audio: mp3, 44100 Hz, stereo, fltp, 320 kb/s

Anything wavesurfer can do in this case? Or would it be better for me to just reject the file at our end if it has a missing header and make the user upload a "valid" file. (Annoyingly the file works everywhere else)

**Comment by FrankLiii** [comment]
Hello, I also get this error :"Uncaught (in promise) DOMException: Unable to decode audio data".
I have a try  to use Wavesurfer with Vue.js now.
My code is in this picture, If you can help me , I will be very grateful.  
thanks！
 My email :1071760702@qq.com;
![1538133740 1](https://user-iages.githubusercontent.com/31913690/46205733-5aa17500-c354-11e8-9c77-8e4706a9e18b.jpg)
`

**Comment by thijstriemstra** [comment]
@FrankLiii can you try running the ffprobe tool on the file and paste the output here? ffprobe is part of ffmpeg.

**Comment by manoharreddyporeddy** [comment]
@FrankLiii Please post your solution here. Thank you
