### ISSUE TITLE
Getting performer name from m3u file

### ISSUE THREAD

**Issue by iglota** [katspaugh/wavesurfer.js#1425]
Hi guys.

First of all, I would like to thank everybody envolved in this project which in being totally usefull for me. 
Well, I tryed to get the performer name from m3u file, but I could do it.  Any clue how to do it?

`#EXTM3U
#EXTINF:1,The Godfather Theme Song
https://wavesurfer-js.org/example/media/demo.mp3
#EXTINF:1,Alessandra
editados/alessandra-01.wav
#EXTINF:1,The Godfather Theme Song
https://wavesurfer-js.org/example/media/demo3.mp3`

**Comment by thijstriemstra** [comment]
ping @entonbiba do you have an idea?

**Comment by entonbiba** [comment]
@iglota yes it's possible, I'll update the playlist plugin to include this and possibly other info ;) .

**Comment by entonbiba** [comment]
@iglota you can achieve this by simply creating a m3u file like the following

```
#EXTM3U
#EXTINF:ARTIST NAME, Title
http://linktofile
```

you would then parse the playlist and split the commas keeping the first as the artist and second as the title.
