### ISSUE TITLE
Minimap plugin doesn't seem work with MediaElement

### ISSUE THREAD

**Issue by meathanjay** [katspaugh/wavesurfer.js#1432]
I tried to implement wavesurfer library with minimap plugin but it seems it only works fine with WebAudio backend, don't draw the waveforms and process with WebAudio backend.

Is it any known issue and any solutions? I will dig into the issue but if anyone faced it and have any solution already.

My use-case is one main player on footer and waveforms with progress showing on listing and actions will be sync.

**Comment by entonbiba** [comment]
@meathanjay can you provide sample code you're using?

**Comment by caugner** [comment]
For me, the Minimap plugin *did* work with a MediaElement backend.

**Comment by thijstriemstra** [comment]
no feedback, closing.
