### ISSUE TITLE
Is `dragSelection` in the regions plugin supposed to be an object or a boolean? Conflicting examples/docs

### ISSUE THREAD

**Issue by josephrocca** [katspaugh/wavesurfer.js#1433]
In [the 2.0.6 regions plugin file](https://cdnjs.cloudflare.com/ajax/libs/wavesurfer.js/2.0.6/plugin/wavesurfer.regions.js), there's this comment:
```
/**
 * @typedef {Object} RegionsPluginParams
 * @property {?boolean} dragSelection Enable creating regions by dragging wih
 * the mouse
 * @property {?RegionParams[]} regions Regions that should be added upon
 * initialisation
 * @property {number} slop=2 The sensitivity of the mouse dragging
 * @property {?boolean} deferInit Set to true to manually call
 * `initPlugin('regions')`
 */
```

It says that `dragSelection` is a boolean. But in [this](https://github.com/katspaugh/wavesurfer.js/blob/master/example/regions/app.js) example file (showing how to use the regions plugin), it has this code:

```
dragSelection: {
  slop: 5
}
```

The latter syntax is also seen in [this file](https://wavesurfer-js.org/plugins/regions.js) from [this page](https://wavesurfer-js.org/plugins/regions.html) - which I think might be an earlier version of the above app.js file?

Also, `slop` doesn't seem to be documented [here](https://wavesurfer-js.org/plugins/regions.html).

These aren't huge issues, just figured I'd let you know. Thanks for the great lib!

**Comment by thijstriemstra** [comment]
@josephrocca thanks for the feedback. Can you make these changes and open a pull request?

**Comment by thijstriemstra** [comment]
@josephrocca see https://github.com/katspaugh/wavesurfer.js/blob/master/src/plugin/regions.js#L680, it's either a boolean (you get all default values) or an object where you can use `slop` etc.

**Comment by athJ** [comment]
Will make the necessary changes and send you pull request
