### ISSUE TITLE
Strange asymmetric and buggy waveform rendering

### ISSUE THREAD

**Issue by josephrocca** [katspaugh/wavesurfer.js#1434]
I've produced a minimal example of this bug:

 * Look at the code: https://glitch.com/edit/#!/wavesurfer-js-rendering-bug
 * Run the example: https://wavesurfer-js-rendering-bug.glitch.me/ (it takes a while to load because YouTube heavily rate-limits the glitch.com servers, sorry)
 * Observe the problem:
![image](https://user-images.githubusercontent.com/1167575/44383773-7b53ff00-a54c-11e8-80e6-e8d94c389da4.png)

**Browser version**: 68.0.3440.106 (Official Build) (64-bit)
**WaveSurfer.js version**: 2.0.6

**Comment by thijstriemstra** [comment]
still an issue with 3.2.0?
