### ISSUE TITLE
getting scroll position

### ISSUE THREAD

**Issue by bknill** [katspaugh/wavesurfer.js#1437]
Hi, 

I'm trying to harmonise 2 wavesurfer instances. 

There doesn't seem to be any useful information in the scrollEvent as to the actual scroll position/offset. 

Is there anyway to get this data when scrolling?

**Comment by thijstriemstra** [comment]
not sure, but if you hack something in, make sure to open a pull request @bknill

**Comment by thijstriemstra** [comment]
`wavesurfer.drawer.getScrollX()'

**Comment by whaozl** [comment]
annotator.wavesurfer.drawer.wrapper.scrollLeft, this is so good.
