### ISSUE TITLE
Loading audio from node's FS.readfile

### ISSUE THREAD

**Issue by Je4hel** [katspaugh/wavesurfer.js#1440]
Hello,

I'm trying to use Wavesurfer to display the waveform of an audio file which I read from the filesystem with `fs.readfile`. This file is previously recorded using the standard Web Audio API, in a .webm file.

I can't find how I'm supposed to load the file after I get the buffer from `fs.readfile`. I tried creating a blob and using `wavesurfer.loadBlob` and creating an object URL (`URL.createObjectURL(myblob)`) to use `wavesurfer.load` but nothing works. The error I get is 

> Uncaught (in promise) DOMException: Unable to decode audio data

By the way, I am also using the blob URL to play the sound using an Audio element and it plays fine.

How am I supposed to proceed? Thanks :)

**Comment by thijstriemstra** [comment]
@Je4hel can you run `ffprobe` on that file and paste the output here? ffprobe is part of ffmpeg.

**Comment by thijstriemstra** [comment]
no feedback, closing.
