### ISSUE TITLE
To conserve bandwidth, is it possible to defer loading of the MP3 file until the user clicks "play"?

### ISSUE THREAD

**Issue by axis80** [katspaugh/wavesurfer.js#1442]
I have an infinite-scroll page with many hundreds of Wavesurfer players.  It looks a lot like Soundcloud, if that helps to explain.

I obviously don't want to abuse my users' bandwidth - or run up a big hosting bill - by loading each and every audio file they scroll past. I only want to actually load the MP3 when they click "play".

With either version 1 or 2 of Wavesurfer, is it possible to preload a server-generated JSON waveform, but defer loading of the actual MP3 file until the user actually clicks "play"?

I have looked over the FAQ and documentation several times but can't find an obvious way to do this.

**Comment by thijstriemstra** [comment]
@axis80 https://github.com/katspaugh/wavesurfer.js/pull/1441 looks related.
