### ISSUE TITLE
Height of waveform is max 128? (wavesurfer v2)

### ISSUE THREAD

**Issue by jamesharvey2** [katspaugh/wavesurfer.js#1443]
Hello Katspaugh,

Is there any way to increase waveform's height beyond 128? 
I tried 256, 512 and it looks like this waveform's height is capped at max 128.
I want to have a taller waveform.. what should I do? 

Thanks,

P.S.

I tested it with wavesurfer 1.4 and height property works well above 128 but it doesn't work beyond 128 on wavesurfer v2. 
I wonder how to use height properly on v2.

**Comment by thijstriemstra** [comment]
I just tried `wavesurfer.setHeight(400)` on https://wavesurfer-js.org/ and seems to work fine. Can you provide some example code @jamesharvey2?

**Comment by thijstriemstra** [comment]
No feedback, closing.
