### ISSUE TITLE
Misleading example on the official page

### ISSUE THREAD

**Issue by higuri** [katspaugh/wavesurfer.js#1447]
In the "Quick start" section on https://wavesurfer-js.org, the script is included as follows.
```
<script src="//cdnjs.cloudflare.com/ajax/libs/wavesurfer.js/2.0.6/wavesurfer.min.js"></script>
```

This method does not work on locally placed HTML files.
To make this work, add 'https:'.
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/wavesurfer.js/2.0.6/wavesurfer.min.js"></script>
```

The same description is in the "Getting started" on https://wavesurfer-js.org/docs. These may confuse people trying to use wavesurfer.js for the first time in their local environment.

### Example
Save the following lines to a local file and open it with web browser.
```html
<html>
<meta charset="utf-8"/>
<body>
<script src="//cdnjs.cloudflare.com/ajax/libs/wavesurfer.js/2.0.6/wavesurfer.min.js"></script>
<script>
console.log(WaveSurfer);
</script>
</body>
</html>
```
Output from the developer console:
![img01](https://user-images.githubusercontent.com/35358263/44730925-0b7ddf80-ab1d-11e8-899c-61ad8e9654e5.png)
[Firefox 61.0.2]

### Reference:
[https://stackoverflow.com/a/4832046](https://stackoverflow.com/a/4832046)

**Comment by thijstriemstra** [comment]
@higuri thanks, can you make a pull request and edit the `gh-pages` branch?

**Comment by higuri** [comment]
@thijstriemstra Sure. I'll do it.

**Comment by thijstriemstra** [comment]
Thanks.
