### ISSUE TITLE
Intermittent SyntaxError Thrown on iOS

### ISSUE THREAD

**Issue by DrLongGhost** [katspaugh/wavesurfer.js#1459]
### Wavesurfer.js version(s):
2.0.5 

### Browser version(s):
Seen with 4 different users on the following devices:

Mobile Safari: Version: 11.0
iOS: Version: 11.4.1, 11.2 and 11.2.5
Devices: iPhone and iPad

### Code needed to reproduce the issue:
Unfortunately this issue is not easily reproducible. It arises from having Wavesurfer deployed in a Production environment where large numbers of people are using it. I am using Wavesurfer in a Vue.js app in which Wavesurfer is completely destroyed and then re-created potentially multiple times without a full page reload. For all browsers except iOS Safari, this works great. However, a small number of users appear to be having intermittent issues rendering Wavesurfer on iOS devices.

I can provide the following information based on the stack traces captured by our error reporting/logging.

Users are seeing the following error:

SyntaxError: The string did not match the expected pattern

From this code:

{snip} ndow.OfflineAudioContext||window.webkitOfflineAudioContext)(1,2,e)),window.WaveSurferOfflineAudioContext}}]),s(t,[{key:"init",value:function {snip}

As shown [here](https://github.com/WebKit/webkit/blob/master/LayoutTests/webaudio/offlineaudiocontext-constructor-expected.txt), the error appears to be caused by a falsey value being passed to the getOfflineAudioContext() method in the webaudio.js file.

Beyond this, I do not know what exactly is causing this false value to be passed in and I cannot replicate the error myself. As a result of a description from a user, the syntax error appears to result in Wavesurfer failing to load the desired audio file.

I do see one possible problem in the code in the spot where getOfflineAudioContext() is called:

this.offlineAc = this.getOfflineAudioContext(
  this.ac ? this.ac.sampleRate : 44100
);

The above code is arguably failing to do proper validation because it is checking that "this.ac" is not falsey but it then proceeds to use "this.ac.sampleRate" without explicitly checking to see whether "this.ac.sampleRate" is falsey. It is possible that with this extra validation put in, it would fallback to the default 44100 sample rate and Wavesurfer would render. It is also possible that there are other issues with the AudioContext and this change would not resolve those other issues, whatever they may be. I may try this hotfix myself and see what the result is.

I'm sorry that I can't provide much more information than this, but I figured I would open the ticket in case someone who is more familiar with AudioContext/WaveSurfer might immediately know of cases in mobile Safari or elsewhere in which the AudioContext represented by "this.ac" is set but does not have a sampleRate attribute (or has a falsey value).

### Use behaviour needed to reproduce the issue:

Note that I am using the MediaElement backend in Safari to avoid the playback bug documented in issue #1215. I'm not sure if this is related or a prerequisite to exposing this bug.

This was super confusing to me until I saw this comment from @katspaugh in #676: "By the way, even when you set media element as the playback backend, Web Audio is still used for decoding (if it's supported by the browser and unless you pass pre-generated waveform data)."

So I guess there is no way to avoid executing this code in iOS via toggling the backend.

**Comment by DrLongGhost** [comment]
One other thing I will add is that it's possible the S3-hosted mp3 files which I am passing to Wavesurfer to load are the source of the intermittent issues. They have given me trouble in the past.

However, I suspect that this is NOT the case because if there were intermittent failures with the source audio, one would not expect this to be isolated to only iOS.

Additionally, I know that WebAudio on Webkit/iOS is flaky in general. I have seen this flakiness with using WebRTC to record audio on iOS where it will intermittently stop working and a browser reboot or new tab is required to get it working again. 

If the underlying issue is random failures of AudioContext, is it possible to detect the "bad" AudioContext and generate a new, working one?

**Comment by thijstriemstra** [comment]
> I do see one possible problem in the code in the spot where getOfflineAudioContext() is called:

Looks like #1467 fixed this potential issue.

**Comment by thijstriemstra** [comment]
> Since I can't duplicate the problem myself, it may take a month or so after the fix goes out on our site to be able to know for sure.

@DrLongGhost any news?

**Comment by DrLongGhost** [comment]
No sign of any related errors. Looks fixed to me. Thanks!
