### ISSUE TITLE
Page keep reloading on safari when using load() with particular file.

### ISSUE THREAD

**Issue by alexandreolivepro** [katspaugh/wavesurfer.js#1461]
## Please make sure you provide the following information (if applicable):
When using safari with a particular mp3 file, the page keep reloading until it crashes. I know the issue is coming from the mp3 file. But I couldn't find the issue with the file of find a way to prevent the reloading of the page with some kind of try / catch. 
I'm providing the file in the exemple below. 

### Wavesurfer.js version(s):
2.0.6

### Browser version(s):
Safari : Version 11.1 (13605.1.33.1.2)

### Code needed to reproduce the issue:
app.components.ts
```
import { Component, OnInit, ViewChild } from '@angular/core';
import * as WaveSurfer from 'wavesurfer.js';

@Component({
  selector: 'app-root',
  template: '<div #waveElement></div>',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  @ViewChild('waveElement') waveElement: any;
  wavesurfer: any;

  ngOnInit() {
    this.wavesurfer = WaveSurfer.create({
      container: this.waveElement.nativeElement,
      cursorColor: 'transparent',
      waveColor: '#CCCBD9',
      progressColor: '#69F0AE'
    });
    this.wavesurfer.load("https://s3-ap-northeast-1.amazonaws.com/bav3-dev/595e44622e28e.mp3");
  }
}
```

### Use behaviour needed to reproduce the issue:
- Install a new angular project
- Install the latest WaveSurfer version : npm install wavesurfer.js
- Setup the minimum waverider functionality 
- Serve the project and open it on safari.

**Comment by thijstriemstra** [comment]
can you reproduce this without angular @alexandreolivepro?

**Comment by thijstriemstra** [comment]
no feedback, closing.
