### ISSUE TITLE
minimap not showing when loading pre-rendered peaks

### ISSUE THREAD

**Issue by lloyd-thomas** [katspaugh/wavesurfer.js#1462]
### Wavesurfer.js version(s):

wavesurfer.js 2.0.6

### Browser version(s):

Chrome Version 68.0.3440.106, Safari Version 11.1.1

### Code needed to reproduce the issue:

https://codepen.io/lloyd-thomas/pen/jvpMGQ

Minimap renders fine when loading the audio file without the json, but doesn't seem to render it at all with. What am I doing wrong? It works on earlier versions  i.e v1.4.0 but I need the minimap to be rendered in a separate div container, a property in the current release. 

Wavesurfer is truly great btw thankyou.

**Comment by lloyd-thomas** [comment]
FYI looks like wavesurfer.fireEvent('waveform-ready'); doesn't get fired so minimap doesn't get drawn, if I add that it it works

https://codepen.io/lloyd-thomas/pen/xaMNyN

**Comment by thijstriemstra** [comment]
@lloyd-thomas can you make a pull request?

**Comment by lloyd-thomas** [comment]
Hi Thijs, I'm pretty unfamiliar with git and to be quite honest I'm not sure my code is good enough to be a collaborator.

**Comment by thijstriemstra** [comment]
@lloyd-thomas if it works, it works. at least we can see the change and consider it.

**Comment by entonbiba** [comment]
@lloyd-thomas please test with latest version 4.4.0 and reopen if needed. I'm not able to replicate see sample here:
https://www.entonbiba.com/lab/wavesurfer/1462.html
