### ISSUE TITLE
getDuration method returns different results for a same audio on 32bit Chrome and 64bit Chrome

### ISSUE THREAD

**Issue by wulijun** [katspaugh/wavesurfer.js#1465]
For an audio file, I invoke getDuration method on Chrome 68.0.3440.106 (stable) (64bit), it returns 10.1267 seconds; when I run on Chrome 69.0.3497.92 (stable) (32bit), it returns 9.6068. If someone  also encounter this problem?

**Comment by thijstriemstra** [comment]
@wulijun can you open a ticket for the Chrome webbrowser and let us know the link to that ticket?
