### ISSUE TITLE
Time Hover Problem

### ISSUE THREAD

**Issue by rezafd23** [katspaugh/wavesurfer.js#1471]
anybody can help me? i've got this error
![image](https://user-images.githubusercontent.com/31206753/46249435-6a53b300-c453-11e8-9f72-d2e111c52d05.png)
when i write this code for show the time when cursor hover at the waveform
![image](https://user-images.githubusercontent.com/31206753/46249442-7c355600-c453-11e8-932a-a36a1a8cb9af.png)

**Comment by thijstriemstra** [comment]
@rezafd23 looks like the cursor.min.js plugin was not included on the page/project.
