### ISSUE TITLE
Failed to execute 'stop' on 'AudioScheduledSourceNode': cannot call stop without calling start first.

### ISSUE THREAD

**Issue by antalagota92** [katspaugh/wavesurfer.js#1473]
### Wavesurfer.js version(s):
wavesurfer.js 2.0.6 (Fri Jun 15 2018 10:57:58 GMT+0200 (CEST))

### Browser version(s):
Google Chrome: 69.0.3497.100 (Official Build) (64-bit)

### Code that causes the issue:

        /**
         * Pauses the loaded audio.
         */

    }, {
        key: 'pause',
        value: function pause() {
            this.scheduledPause = null;

            this.startPosition += this.getPlayedTime();
            this.source && this.source.stop(0);

            this.setState(PAUSED);

            this.fireEvent('pause');
        }

-A check is needed before executing this.source && this.source.stop(0);, because due to timing problems it might happen that the audio is not started when the stop is called. 

###
To reproduce the issue, you need to load new audio files, then quickly start and stop them.

**Comment by thijstriemstra** [comment]
@antalagota92 thanks for the report. Can you make a pull request?

**Comment by thijstriemstra** [comment]
no feedback, closing.

**Comment by naumanahmed19** [comment]
any update on this issue?

**Comment by Nadav42** [comment]
this is still an issue

**Comment by Nadav42** [comment]
this is still an issue @thijstriemstra

**Comment by thijstriemstra** [comment]
can you include the wavesurfer.js version/browser/os @Nadav42?

**Comment by Nadav42** [comment]
> can you include the wavesurfer.js version/browser/os @Nadav42?

windows 10 chrome 64bit version 86.0.4240.111
wavesurfer 4.1.1

it happens when calling wavesurfer.pause()

wouldn't adding that check fix this issue? @thijstriemstra

**Comment by thijstriemstra** [comment]
A pull request is always welcome @Nadav42. That fix looks fine.

**Comment by Nadav42** [comment]
@thijstriemstra okay, I'll try it and if it fixes it I'll open a pull request

**Comment by Nadav42** [comment]
hey @thijstriemstra I can't find a way to actually check if the SourceNode started or not

what's intresting is that even when I'm checking if wavesurfer is actually playing before pausing there are still some exceptions:

```
if (wavesurfer.isPlaying()) {
    wavesurfer.pause(); // DOMException: Failed to execute 'stop' on 'AudioScheduledSourceNode' ...
}
```

I even added the same check inside wavesurfer's webaudio.js like this and it still throws the exception:
```
if (!this.isPaused()) {
    this.source && this.source.stop(0); // DOMException: Failed to execute 'stop' on 'AudioScheduledSourceNode' ...
}
```

I'm thinking that maybe this is a rare situation where you call .pause() and even tho the internal state changed to PLAYING by .play() the source buffer didn't start yet because it has small delay?

play code:
```
this.source.start(0, start);
this.resumeAudioContext();
this.setState(PLAYING);

```
--> .play()
--> .pause() is called --> exception
--> browser only starts source buffer here on a later timeframe?
```

anyway adding these checks and also try catch inside wavesurfer's pause() stopped my app from crashing, will you accept a pull request that just adds try catch?

![image](https://user-images.githubusercontent.com/48027340/97222793-8b746280-17d7-11eb-8559-1ed832a276bf.png)
