### ISSUE TITLE
Canvas max-width

### ISSUE THREAD

**Issue by fabianodanz** [katspaugh/wavesurfer.js#1474]
Some front-end frameworks (like Foundation), set canvas max-width to 100%, creating a problem to progress canvas visualization, it would be nice if wavesurfer include the max-width: none in canvas style, just to prevent this problems.

**Comment by thijstriemstra** [comment]
PRs are welcome.

**Comment by HaykoKoryun** [comment]
@fabianodanz I think this is a simple fix, however can you provide a simple codepen or jsFiddle example so I can test against it?

**Comment by thijstriemstra** [comment]
ping @fabianodanz

**Comment by thijstriemstra** [comment]
no feedback, closing.
