### ISSUE TITLE
Document what is needed to load a plugin

### ISSUE THREAD

**Issue by Flimm** [katspaugh/wavesurfer.js#1477]
I am trying to get the Regions plugin to work. To do that, it looks like I need to make sure two Javascript files are loaded, not just one:

```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/wavesurfer.js/2.0.6/wavesurfer.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/wavesurfer.js/2.0.6/plugin/wavesurfer.regions.min.js"></script>
```

I also have to configure the `regions` plugin when creating the `WaveSurfer` instance, like this:

```javascript
const wave = WaveSurfer.create({
  container: "#waveform",
  plugins: [
    WaveSurfer.regions.create({
      regions: [
         {start: 5, end: 6},
      ],
    }),
  ],
});
```

I had to spend some time discovering this, as this process is not documented on the website.

Thank you for this code, it looks really useful!

**Comment by thijstriemstra** [comment]
@Flimm this is clear from the examples (to me). If you want to improve the documentation, take a look at the `gh-pages` branch and make a pull request.

**Comment by Flimm** [comment]
Thanks for accepting my pull request!
