### ISSUE TITLE
playback rate / playing cursor speed

### ISSUE THREAD

**Issue by pitrackster** [katspaugh/wavesurfer.js#148]
If I change the playback rate, the playing cursor is still moving at the same speed

I've searched a little in your code an tried something with <code> getCurrentTime() </code> method by doing <code>this.ac.currentTime \* this.playBackRate</code> 

It seems it's not the good place do do it because it's also make the playing cursor "jump" It's position (maybe the global duration of sound should also be changed... or not)

Any advice ?

**Comment by Kage1989** [comment]
Hi,

I'm playing around with the playback rate and realised that there is a limit on the playback rate (setPlaybackRate=>2.5) before the cursor starts advancing in the waveform container (ie. the cursor doesn't stay in the middle anymore). Any idea what could have caused the problem?

**Comment by thijstriemstra** [comment]
@Kage19897, thanks for the details. Could you make a pull request for that change so we can test it?

**Comment by Kage1989** [comment]
Sorry. I'm a bit new to GitHub. I'm not entirely sure about the procedure for making the pull request. What I've done is forking the repo and editing my copy of the wavesurfer repo. In the "Commit changes" section, I clicked on "Create a new branch for this commit and start a pull request." Is this the right procedure to make the pull request? My edit appears in my repo as a branch under Kage1989-patch-1. But I don't see that branch in the katspaugh repo. Am I doing things correctly?

**Comment by thijstriemstra** [comment]
No problem, after reading https://help.github.com/articles/using-pull-requests/ you should be able to figure it out..

**Comment by Kage1989** [comment]
Yeah! I saw my pull request in katspaugh's repo now. Thanks a lot!
