### ISSUE TITLE
Error: Container element not found when specifying MultiCanvas renderer

### ISSUE THREAD

**Issue by joshcutler** [katspaugh/wavesurfer.js#1482]
### Wavesurfer.js version(s):

2.1.0

### Browser version(s):

Chrome  69.0.3497.100

### Code needed to reproduce the issue:

```
var wavesurfer = WaveSurfer.create({
          container: document.querySelector(".waveform"),
          splitChannels: true,
          renderer: MultiCanvas
        })
```
(Please reduce your code as much as possible and only post the minimum code needed to reproduce the issue. [A Code pen](http://codepen.io/) is an excellent way to share such code)

### Use behaviour needed to reproduce the issue:

This throws the following error:

```
Error: Container element not found
    at new WaveSurfer (wavesurfer.js:2957)
    at WaveSurfer.createDrawer (wavesurfer.js:3238)
    at WaveSurfer.init (wavesurfer.js:3072)
    at Function.create (wavesurfer.js:2878)
```

Note that if I don't specify any renderer, its fine.  But when I specify what is presumable the default it is unable to find the container.  I found this out by trying to write my own renderer.

**Comment by thijstriemstra** [comment]
@joshcutler what does `document.querySelector(".waveform")` return?

**Comment by joshcutler** [comment]
It returns the desired DOM element.  I think I figured out what the issue was.

I was importing `MultiCanvas` incorrectly.  If do somthing like `import MultiCanvas from "wavesurfer.js"` you can recreate this as when the rendering tries to instantiate the "multiCanvas" instance it is really instantiating a new WaveSurfer instance.

This can be closed.
