### ISSUE TITLE
Use exportPCM with jPlayer

### ISSUE THREAD

**Issue by KodeKanyon** [katspaugh/wavesurfer.js#1484]
After I have exported an audio file’s peak data to my server, how can I utilize it with jPlayer, which uses a div for the playbar and div for the progress? Can I draw the peaks to canvas without using wavesurfer? (only using it to exportPCM, not to play the audio). Here’s an example of the jPlayer audio http://jsfiddle.net/onigetoc/Ls8p90y9/4/.

This audio player uses WaveSurfer to generate and draw peak data, but uses its own audio player. I am trying to do this but use jPlayer. https://previews.envatousercontent.com/files/251421118/index.html

Thanks

**Comment by thijstriemstra** [comment]
>  how can I utilize it with jPlayer

ask on stackoverflow. this is not a wavesufer issue or improvement.
