### ISSUE TITLE
getDuration value less real time

### ISSUE THREAD

**Issue by liyuze** [katspaugh/wavesurfer.js#1485]
hi，
i have a mp3 file [get.zip](https://github.com/katspaugh/wavesurfer.js/files/2462923/get.zip).

it's show time 2:54 in audio dom.

but wavesurfer.getDuration() value is 31.752.

**Comment by thijstriemstra** [comment]
@liyuze can you run `ffprobe` on the file and paste it here? ffprobe is part of ffmpeg.

**Comment by liyuze** [comment]
This audio file is made up of two audio splicing. like this recording-pause-recording-stop.

```bash
$ ffprobe ./get.mp3
ffprobe version 4.0.2 Copyright (c) 2007-2018 the FFmpeg developers
  built with gcc 4.4.7 (GCC) 20120313 (Red Hat 4.4.7-23)
  configuration: --enable-shared --enable-libmp3lame
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
[mp3 @ 0x17aeac0] Estimating duration from bitrate, this may be inaccurate
Input #0, mp3, from './get.mp3':
  Duration: 00:02:54.29, start: 0.000000, bitrate: 16 kb/s
    Stream #0:0: Audio: mp3, 16000 Hz, mono, fltp, 16 kb/s
```

**Comment by thijstriemstra** [comment]
> it's show time 2:54 in audio dom.

what browser/OS/waevsurfer version?

**Comment by thijstriemstra** [comment]
ping @liyuze

**Comment by liyuze** [comment]
Sorry, it’s been too long, I can’t find it.

**Comment by mahish** [comment]
@liyuze @thijstriemstra Hey, guys Im having the same problem. This what i get. Looks like the problem is already in DOM or the files.

`"wavesurfer.js": "^2.2.1"`

## MacOS Chrome 75
- audio-1.mp3
```
media.duration = 85.946187
wavesurfer.getDuration() = 86.12571428571428
```

- audio-2.mp3
```
media.duration = 97.948455
wavesurfer.getDuration() = 89.96571428571428
```

## MacOs Firefox 67
- audio-1.mp3
```
media.duration = 89.5194
wavesurfer.getDuration() = 86.08759637188209
```

- audio-2.mp3
```
media.duration = 110.011857
wavesurfer.getDuration() = 89.92759637188209
```

**Comment by mahish** [comment]
Did `ffprobe` for both files:

## audio-1.mp3
```
[mp3 @ 0x7fa604800000] Estimating duration from bitrate, this may be inaccurate
Input #0, mp3, from 'audio-1.mp3':
  Duration: 00:01:25.95, start: 0.000000, bitrate: 83 kb/s
    Stream #0:0: Audio: mp3, 44100 Hz, stereo, fltp, 83 kb/s
```

## audio-2.mp3
```
[mp3 @ 0x7fd89a004800] Estimating duration from bitrate, this may be inaccurate
Input #0, mp3, from 'audio-2.mp3':
  Duration: 00:01:37.95, start: 0.000000, bitrate: 62 kb/s
    Stream #0:0: Audio: mp3, 44100 Hz, mono, fltp, 62 kb/s
```

**Comment by mahish** [comment]
- Chrome's `media.duration` value seems to be closest to what I get from `ffprobe`. 
- Firefox's `media.duration`, on the other hand, looks the most different. 
- `wavesurfer` differs a bit but it returns consistent value across both browsers.

**Comment by mahish** [comment]
The original files were saved with Adobe Audition. If I save convert tem with `ffmpeg -i audio-1.mp3 -c:a copy -b:a 128k -sample_rate 44100 audio-1.mp3` the issue is gone:

```
audio-1.mp3, media.duration = 89.99029
audio-1.mp3, wavesurfer.getDuration() = 86.08759637188209

audio-2.mp3, media.duration = 86.150356
audio-2.mp3, wavesurfer.getDuration() = 89.92759637188209
```

**Comment by lauradP** [comment]
Hi, I'm observing the same issue. My mp3 files are generated using ffmpeg with provided parameters.

Peaks are generatedusing audiowaveform command line using the following parameters:  --pixels-per-second 25 -b 16
