### ISSUE TITLE
Show 1px height bars for silent sections of an audio file

### ISSUE THREAD

**Issue by javaskript** [katspaugh/wavesurfer.js#1487]
Here's how waveforms look when there is a very quiet or silent part. Notice the blank gap:

![u2JjFZT](https://user-images.githubusercontent.com/305679/57002695-88d48500-6bc1-11e9-91da-9f1835b306c5.png)

I'd like for it to look like this for very quiet / silent segments:

![WeaBzu5](https://user-images.githubusercontent.com/305679/57002708-a1dd3600-6bc1-11e9-9610-9f179dd989f3.png)

How would I go about displaying small bars for silent parts of my audio?

**Comment by thijstriemstra** [comment]
Also see #45

**Comment by thijstriemstra** [comment]
@javaskript what wavesurfer params are you using?

**Comment by javaskript** [comment]
@thijstriemstra The default parameters for the most part. I'm only using WaveSurfer to render the waveform, uploading the result to the server via ajax, pulling the .json file, and drawing it on unique canvases (not using it to play the tracks at all, I'm using jPlayer for that). I'm using a custom renderer, however, to make use of gradients and a half-height reflection. Image: https://i.imgur.com/SDJKG6U.png

Still working on improving my custom renderer, but haven't figured out how to show 1px bars for silenced portions of the waveform. It's mostly a cosmetic issue. And I believe Hark that you suggested would not work in the case of pre-rendered waveforms? I'm having the waveform .json generated via WaveSurfer on the client's end. After the rendering event is complete, I'm uploading the .json to the server.

`$.get('/uploads/json/' + trackID + '.json', function(data) {
    if (data) {
        var peaks = data;
        wavesurfer.load('', peaks);
    } else {
        var peaks = '';
        wavesurfer.on('ready', () => {
            let pcm = wavesurfer.exportPCM(1024, 10000, true);
            // Do something with pcm
            $.post('/waveform/json_generate.php', {
                data: pcm,
                songid: trackID
            }, function(result) {
                // success
                console.log('Waveform successfully generated and uploaded to the server.');
            });
            document.getElementById('waveform' + trackID).classList.add('generated-waveform');
        });
        wavesurfer.load(trackIDURL, peaks);
    }
    var responsiveWave = wavesurfer.util.debounce(function() {
        wavesurfer.drawBuffer();
    }, 1);
    window.addEventListener('resize', responsiveWave);
});`

**Comment by youngcitrus** [comment]
would love a minimum height feature for quiet and silent parts as well

**Comment by KonstantinKai** [comment]
`barMinHeight` is available to control this case
