### ISSUE TITLE
Region drags left when drag is set to false and maxLength is exceeded.

### ISSUE THREAD

**Issue by dinhodoes** [katspaugh/wavesurfer.js#1488]
I was trying to use the regions plugin to highlight pieces of audio I wanted to cut from the original **without** overlap from other regions and came across some peculiar dragging behavior...

Basically I'm trying to create two trimming regions (one in the beginning and one in the end of the waveform) and want them anchored in a way so that only the inner handles can resize without overlapping the other region.

First, I took @katspaugh 's advice from [this issue](https://github.com/katspaugh/wavesurfer.js/issues/502#issuecomment-134517626) and added a maxLength to prevent any overlapping after a certain point but noticed that resizing the region from the left handle was different than resizing from the right handle.

To reproduce just drag the left handle to the left passed the maxLength and notice that the region drags. If you drag the right handle to the right passed the maxLength notice that the regions stays put as I would hope. Is this expected?

I forked an existing pen and made some modifications to demonstrate my point [here](https://codepen.io/dinhodoes/pen/yRoQPx). Hope that makes sense and thanks again for creating such a cool library!

**Comment by thijstriemstra** [comment]
@dinhodoes you're using an unsupported version (`<script src="https://cdnjs.cloudflare.com/ajax/libs/wavesurfer.js/1.1.5/wavesurfer.min.js"></script>`), please try the latest.

**Comment by thijstriemstra** [comment]
no feedback, closing.
