### ISSUE TITLE
Calling zoom in .on('ready') callback renders broken waveforms

### ISSUE THREAD

**Issue by Stoyvo** [katspaugh/wavesurfer.js#1489]
### Browser version(s):
Chrome 67

### Code needed to reproduce the issue:
`zoomVal=500;
wavesurfer.on('ready', function() {
            wavesurfer.zoom(zoomVal);
});`

### Use behaviour needed to reproduce the issue:

Load an audio file, then call zoom within ready callback, waveforms render like this:
![image](https://user-images.githubusercontent.com/6148099/46926923-e546cd00-d000-11e8-9e29-ed24d6be8123.png)

Expecting this:
![image](https://user-images.githubusercontent.com/6148099/46926931-f0016200-d000-11e8-831e-feea6569fa2b.png)

### Work Around ###
To work around, zoom out and then back in.

**Comment by asystemsaus** [comment]
Is there any particular reason you need to have it in the .on ready ?
I use it outside. Inside my .js i have the following.
      var zoom = document.querySelector('#zoom');
      zoom.oninput = function() {
        var zoomLevel = Number(zoom.value);
        wavesurfer.zoom(zoomLevel);
In the html i have:
 <span class="font-weight-bold" > Zoom   </span> <input data-action="zoom" id="zoom"  /></div>
and in the           $(document).ready(function() {
        $("#zoom").ionRangeSlider({
                          min: 0,
                          max: 200,
                          from: 0,
                          step : 5,
                            grid : true
                      });
});
Here is the waveform as normal.
![zoom1](https://user-images.githubusercontent.com/32542103/47989936-f2ec0000-e131-11e8-8ea9-0ea7b6563db4.jpg)
Here is the same waveform zoomed
![zoom2](https://user-images.githubusercontent.com/32542103/47989955-ff705880-e131-11e8-93d1-28c9a8e18acb.jpg)
This audio is only 1 channel, but it works perfectly on two channels.
I settled on 200x zoom .

**Comment by thijstriemstra** [comment]
No feedback, closing.
