### ISSUE TITLE
Request: Coloured Waveforms

### ISSUE THREAD

**Issue by Stoyvo** [katspaugh/wavesurfer.js#1490]
I'm looking at ways of creating a plugin to colour waveforms based on frequency.

A good reference would be: https://stackoverflow.com/questions/30366924/code-to-color-waveforms-by-frequency

Currently there is already an AnalyserNode, however an offlineAc needs to be used.

Thoughts on how to do this without creating another AC?

**Comment by kasual1** [comment]
Yes I'm also interested in a solution for that.

**Comment by X-Raym** [comment]
@Stoyvo This is a duplicate of this issue :

https://github.com/katspaugh/wavesurfer.js/issues/160

**Comment by Stoyvo** [comment]
Wow, sorry @X-Raym, I'll close this ticket. So happy to see others interested in this feature :)
