### ISSUE TITLE
reinitialize / redraw on resize ?

### ISSUE THREAD

**Issue by daslicht** [katspaugh/wavesurfer.js#1494]
hi,
what is the best way to redraw the wavefrom once the browser size change ?

Is there a smarter way than calling ```WaveSurfer.create``` ?

~ 
Marc

**Comment by daslicht** [comment]
![](https://i.imgur.com/TaXcUCn.png)

**Comment by daslicht** [comment]
@daslicht  RTFM!

**Comment by whthT** [comment]
`wavesurfer.drawer.fireEvent('redraw')` it works for me
