### ISSUE TITLE
Wave canvas duplicate and update in realtime

### ISSUE THREAD

**Issue by kirilkirkov** [katspaugh/wavesurfer.js#1496]
Can you give me some idea, how to create something like this:

![screenshot from 2018-10-23 15-41-49](https://user-images.githubusercontent.com/3421328/47361368-63c6fd00-d6da-11e8-852f-3575c76aaf6b.png)

I need to duplicate the wave and update it in realtime. The website on the image is written with your wavesurfer :) 
@katspaugh

**Comment by katspaugh** [comment]
You should probably just hack it. Use `cloneNode` on the original canvas element and `appendChild` the clone to the other location.
Do the same with the progress canvas. Subscribe to the wavesurfer.js's `audioprocess` event to update the width of the progress canvas. 🤷‍♂️

**Comment by kirilkirkov** [comment]
hmm, its strange. I do exactly what you say but my copied canvas doesn't have any picture on it.
In selected element on firebug you will see. (screenshot)
![screenshot from 2018-10-23 19-56-25](https://user-images.githubusercontent.com/3421328/47377417-e319f800-d6fd-11e8-8581-a1b519225ed7.png)
Do you have another suggestion. Thanks @katspaugh  !!
You help me a lot with this script. If you need an online store of codeigniter you can check my repository :))

**Comment by kirilkirkov** [comment]
@katspaugh  do you have an idea when i create footer clone of my wavesurfer and than change content of page and remove the original, how to leave sound on?
