### ISSUE TITLE
Unable to mute left or right channel in stereo audio file 

### ISSUE THREAD

**Issue by Vijayalaxmim** [katspaugh/wavesurfer.js#1497]
I am trying to use Audio context from wavesurfer object to play one channel at a time. But it doesnt seem to be working By using wavesurfer.backend.setFilter() and passing channelSplitter object am able to play left channel but the other one never get played.

### Use behaviour needed to reproduce the issue:
Load a single audio mp3 file which has 2 channels .

**Comment by Vijayalaxmim** [comment]
accidentally closed

**Comment by thijstriemstra** [comment]
> 2.0.0-beta02

always try latest version.

**Comment by asystemsaus** [comment]
Here is what it should look like .
![waveplayer2](https://user-images.githubusercontent.com/32542103/47971291-b55c8800-e0db-11e8-8afa-a861942facfe.jpg)

The only issue I have so far is the timeline characters appear to be cutoff. Not a show stopper but something i'd like to get resolved.

**Comment by thijstriemstra** [comment]
thanks for feedback.

**Comment by kavishatalsania** [comment]
I am able to mute channel for the stereo audio file with backend 'WebAudio'. But If I wanted to use backend 'MediaElement', then how can I mute left or right channel as with 'MediaElement' I can not use the setFilter method.

Can someone please help me?

**Comment by mauryanm** [comment]
I want to same thing on backend 'MediaElement'  and also need to Amplify audio in selected region.
Can anyone help me?

**Comment by Grimlek** [comment]
Did anyone find a resolution to make this work with Html 5 Audio and the latest wavesurfer version?
