### ISSUE TITLE
Eating up all memory when displaying graph for large audiofile

### ISSUE THREAD

**Issue by Frezzaldo** [katspaugh/wavesurfer.js#1498]
### Wavesurfer.js version(s):
2.1.0

### Browser version(s):
Chrome 58.0.3029.81

### Code needed to reproduce the issue:
        this.wavesurfer = WaveSurfer.create({
            container: "#waveform",
            waveColor: "white",
            progressColor: "darkGrey",
            cursorColor: "green",
            cursorWidth: 2,
            hideScrollbar: true,
            mediaType: "audio",
            partialRender: false,
            mediaControls: true,
            backend: "MediaElement",
            responsive: true,
            minPxPerSec: 5,
            pixelRatio: 1
        });

### Use behaviour needed to reproduce the issue:
I have a mp3 file that is 77MB and the duration is 56:33.  When wavesurfer tries to load the file it eats up over 2GB of memory. The browser runs out of memory before anything is displayed.

**Comment by Frezzaldo** [comment]
I have now tested with Chrome 67.0.3396.79. This time the browser doesn't run out of memory (or at least not showing an error message), but it still takes up all available memory. When finish rendering it uses 1450MB. It takes about 1minute to render. Is there a way to speed up rendering? I have tried to set partialRender: true, but then nothing happens.

**Comment by thijstriemstra** [comment]
see #1281 @Frezzaldo

**Comment by adjkldd** [comment]
1. use MediaElement as backend
2. load peaks from server

using two step above solved my problem of showing waveform of large audio

**Comment by entonbiba** [comment]
please retest with latest version, should be more optimized and better performance. reopen if issue is still happening for you.

**Comment by thijstriemstra** [comment]
> please retest with latest version

What specific version?

**Comment by entonbiba** [comment]
4.4.0

**Comment by mmswebapp** [comment]
Where can I find the version of min of version 4.4 ?
