### ISSUE TITLE
The cursor show outside the wrapper when try to use cursor plugin.

### ISSUE THREAD

**Issue by ellVin** [katspaugh/wavesurfer.js#1501]
### Code needed to reproduce the issue:

https://codepen.io/ElvinWang/pen/OBGmRg

### Use behaviour needed to reproduce the issue:

I’m new to wavesurferjs and want to use the cursor plugin. Try a simple demo like the code in the codepen. But the cursur show outside the wrapper. I dont know where is wrong, can you help me out. 
Thanks a lot!

**Comment by thijstriemstra** [comment]
@tbogard any ideas?

**Comment by aburai** [comment]
@ellVin  set your wavesurfer container style to `position: relative` cause cursor is set to position absolute

**Comment by thijstriemstra** [comment]
@ellVin is this also happening with the cursor example in the repository? if so, can you fix it there as well and make a pull request?

**Comment by aburai** [comment]
@thijstriemstra the example is correct

examples/css/style.css
```css
90 #waveform {
91     position: relative;
92 }
```
