### ISSUE TITLE
How to draw waveform when audio don't load finsh

### ISSUE THREAD

**Issue by PotatoSmith** [katspaugh/wavesurfer.js#1504]
I met a issue,  the audio file is very big, it need a long time to load.  I want to draw waveform although the audio is loading.   Like I can play it although the audio is incomplete.  Is there a method that I can use it. Thank you very much

**Comment by thijstriemstra** [comment]
@PotatoSmith what code are you using now?

**Comment by fab-1** [comment]
@PotatoSmith As far as I know, there is no way to draw the waveform as the audio decode, but it would be a nice addition to be able to draw async. What I do to prevent the long wait is that I cache the audiodata the first time, then I load it manually so it shows right away
