### ISSUE TITLE
Using credentials with MediaElement

### ISSUE THREAD

**Issue by danielkrich** [katspaugh/wavesurfer.js#1508]
> wavesurfer = WaveSurfer.create({
> container: '#waveform',
> waveColor: 'darkorange',
> progressColor: 'green',
> splitChannels: true,
> height: 80,
> xhr: {requestHeaders: [{
> key: "Authorization",
> value: "Bearer " + make_base_auth(U, P)
> }]}
> });
> ```

Hey there @thijstriemstra, thanks for this comment.
This works, but it works only with "WebAudio" backend. I need to use "MediaElement" because I want partial file loading (start playing before the whole file downloads).
How can I use credentials in this case?

Thanks

_Originally posted by @danielkrich in https://github.com/katspaugh/wavesurfer.js/issues/1038#issuecomment-430618210_

**Comment by danielkrich** [comment]
You answered: (https://github.com/katspaugh/wavesurfer.js/issues/1038#issuecomment-430725606)

> @danielkrich preload it using ajax (e.g. jquery of whatever javascript) into an audio element and pass that audio element to wavesurfer?

BUT, how can you pass an audio element to wavesurfer?
Thanks :)

**Comment by thijstriemstra** [comment]
> How can I use credentials in this case?

no idea.

> how can you pass an audio element to wavesurfer?

Use `loadElt` instead of `load`, see https://github.com/katspaugh/wavesurfer.js/blob/master/src/mediaelement.js#L114
