### ISSUE TITLE
Scale "Reflected" Waveform

### ISSUE THREAD

**Issue by javaskript** [katspaugh/wavesurfer.js#1513]
I am trying to imitate this waveform style:

<img src="https://i.stack.imgur.com/MXAzC.png">

I have seen https://github.com/katspaugh/wavesurfer.js/issues/664#issuecomment-190779795, but am unsure how to implement it, as I think it is an outdated response. The gradient lines between the bars look nice, too.

**Comment by yohanndev** [comment]
Hi, any ideas?  I'm stuck too on the old way to achieve it. I guess there is something to do here to editing how it's drawing but how ?
`key: "drawBars",
    value: function drawBars(peaks, channelIndex, start, end) {
      var _this4 = this;

      return this.prepareDraw(peaks, channelIndex, start, end, function (_ref) {
        var absmax = _ref.absmax,
            hasMinVals = _ref.hasMinVals,
            height = _ref.height,
            offsetY = _ref.offsetY,
            halfH = _ref.halfH,
            peaks = _ref.peaks;

        // if drawBars was called within ws.empty we don't pass a start and
        // don't want anything to happen
        if (start === undefined) {
          return;
        } // Skip every other value if there are negatives.


        var peakIndexScale = hasMinVals ? 2 : 1;
        var length = peaks.length / peakIndexScale;
        var bar = _this4.params.barWidth * _this4.params.pixelRatio;
        var gap = _this4.params.barGap === null ? Math.max(_this4.params.pixelRatio, ~~(bar / 2)) : Math.max(_this4.params.pixelRatio, _this4.params.barGap * _this4.params.pixelRatio);
        var step = bar + gap;
        var scale = length / _this4.width;
        var first = start;
        var last = end;
        var i;

        for (i = first; i < last; i += step) {
          var peak = peaks[Math.floor(i * scale * peakIndexScale)] || 0;
          var h = Math.round(peak / absmax * halfH);

          _this4.fillRect(i + _this4.halfPixel, halfH - h + offsetY, bar + _this4.halfPixel, h * 2);
        }
      });
    }`
