### ISSUE TITLE
What's the npm name

### ISSUE THREAD

**Issue by grosch** [katspaugh/wavesurfer.js#1517]
On your documentation for version 2 you say to do an npm install but you don't provide the specific package name to install.  Is it just "wavesurfer.js"?  I see multiple items in an npm search with wavesurfer in the name.

**Comment by thijstriemstra** [comment]
it's `wavesurfer.js`.

**Comment by belvederef** [comment]
It would be a good idea to add this to the readme, before showing how to import it.

**Comment by thijstriemstra** [comment]
@belvederef good idea, feel free to make the change and open a pull request.
