### ISSUE TITLE
Microphone Waveform Works on Desktop, but not in Mobile browsers nor Hybrid App

### ISSUE THREAD

**Issue by stoltenheim** [katspaugh/wavesurfer.js#1525]
Hi, I have this issue where the wave animation is displaying on desktop browsers, but not in mobile browsers nor in the native app. Everything is working fine on the desktop browser.

My current version is wavesurfer.js version 2.1.1

Thank you.

**Comment by thijstriemstra** [comment]
@stoltenheim mobile browsers? please be more specific (like the ticket guidelines told you to).
