### ISSUE TITLE
Energy Consumption 

### ISSUE THREAD

**Issue by Stoyvo** [katspaugh/wavesurfer.js#1538]
### Wavesurfer.js version(s):
2.1.1

### Browser version(s):
Electron 4.0.0-beta.9

### Code needed to reproduce the issue:
Any example provided in repo. Using the following options:
```javascript
wavesurfer = WaveSurfer.create({
            container: '#playerCanvas',
            dragSelection: false,
            height: 60,
            hideScrollbar: true,
            loopSelection: false,
            maxCanvasWidth: 16384,
            minPxPerSec: 12, // higher = slower zoom
            normalize: false,
            partialRender: false,
            progressColor: '#7c7c7c', // Intentionally the same, so we can have a layer ontop of canvas and less redraw
            quickCenter: true,
            waveColor: '#7c7c7c',
            plugins: [
                WaveSurferRegions.create({
                    resize: false,
                    drag: false,
                    maxLength: null,
                    minLength: null,
                    attributes: null,
                }),
                WaveSurferMinimap.create({
                    barHeight: 1.4,
                    height: 30,
                    progressColor: '#282828',
                    fillParent: false,
                    showRegions: true,
                    showOverview: true,
                    overviewBorderColor: '#14508c',
                    overviewBorderSize: 1,
                    waveColor: '#7c7c7c'
                })
            ]
        });
```

### Use behaviour needed to reproduce the issue:
1) Use a full-pledged audio track (~3-4 minutes)
2) Review energy consumption on your OS (mine is Mac OS High Sierra)

Observation: Typically an electron app sits at at ~8-20, however an canvas render will result in ~110-130). This can drain batteries faster than the laptop can charge!
Reference:
https://developer.apple.com/library/archive/documentation/Performance/Conceptual/power_efficiency_guidelines_osx/MonitoringEnergyUsage.html

**Comment by thijstriemstra** [comment]
PRs are welcome.

**Comment by Stoyvo** [comment]
This was addressed in your latest updates @thijstriemstra ! Thank you.

**Comment by thijstriemstra** [comment]
nice! which ones specifically @Stoyvo?

**Comment by Stoyvo** [comment]
@thijstriemstra It was this commit https://github.com/katspaugh/wavesurfer.js/commit/18cad42e4e3b6e530f2972bbc55dc212d63c9958

Not all heroes wear capes!
