### ISSUE TITLE
when i open some pages , thre brower is dead , could you help me ?

### ISSUE THREAD

**Issue by 15838028035** [katspaugh/wavesurfer.js#1544]
when i open some pages , thre brower is dead , could you help me ?

@therewasaguy

**Comment by aburai** [comment]
Please provide more infos and code to reproduce the issue.

**Comment by 15838028035** [comment]
Hi,when I open a page, about 50mb files loaded,  google memory up to 1G, my customer computer is 2G mem,  how can I solve it, cloud you help me?


发自我的 iPhone

**Comment by thijstriemstra** [comment]
Use the `MediaElement` and pre-generate the peaks on the server. See the https://wavesurfer-js.org/example/audio-element/index.html example.
