### ISSUE TITLE
Internet Explorer 11 on Windows 7 

### ISSUE THREAD

**Issue by kirilkirkov** [katspaugh/wavesurfer.js#1546]
Wavesurfer vesion - wavesurfer.js 2.0.5 

Why dont work? @katspaugh  ? I try to pass peaks in array but the wavesurfer library have errors.

**Comment by kirilkirkov** [comment]
![screenshot from 2018-12-30 09-36-56](https://user-images.githubusercontent.com/3421328/50545301-c6c39b80-0c17-11e9-9352-6cf709fd54c0.png)

**Comment by thijstriemstra** [comment]
You don't supply any example code, so we have no idea what the issue is.

You should also always use the latest wavesurfer.js (2.1.1 at moment of writing this).

**Comment by kirilkirkov** [comment]
@thijstriemstra  I use wavesurfer - wavesurfer.js 2.0.5. You can try with this very simple code not working - http://podobrisebesi.bg/test/asd1.html. 
Is need to use some polyfill to work wavesurfer on internet explorer?

**Comment by thijstriemstra** [comment]
> I use wavesurfer - wavesurfer.js 2.0.5.

Don't. Use the latest.

**Comment by aburai** [comment]
i use v2.2.1 and still have problems with IE, because there is no window.AudioContext or webkitAudioContext and `new (window.AudioContext || window.webkitAudioContext)()`throws an error

**Comment by thijstriemstra** [comment]
@aburai take a look at the changelog for 3.0.0: it includes #1614 that should fix this.

**Comment by thijstriemstra** [comment]
duplicate of #1614

**Comment by aburai** [comment]
thx Thijs
