### ISSUE TITLE
how can i unload wavesure  as quickly as possible ? 

### ISSUE THREAD

**Issue by 15838028035** [katspaugh/wavesurfer.js#1547]
Hi, 
how can i unload wavesure  as quickly as possible ?    i use google,  i want to free memory , i have only 2G memory,  cloud you help me ?

@berio  @rikrd  @tf

**Comment by 15838028035** [comment]
@thijstriemstra

**Comment by thijstriemstra** [comment]
hey @15838028035 can you stop cc-ing random people, fck that, we're not some sort of helpdesk.

**Comment by 15838028035** [comment]
Okay, I do not know who can help me


发自我的 iPhone

**Comment by thijstriemstra** [comment]
@15838028035 use `wavesurfer.destroy()`.
