### ISSUE TITLE
RegionsPlugin undefined?

### ISSUE THREAD

**Issue by MaxwellGover** [katspaugh/wavesurfer.js#1552]
**Version: "2.1.2"**

Any reason why RegionsPlugin would be undefined? I've added the script tag in my react app

`<script src="https://unpkg.com/wavesurfer.js"></script>`

Everything else works fine but when trying to run the following code

```
var RegionsPlugin = WaveSurfer.regions;
const wavesurfer = WaveSurfer.create({
   container: "#waveform",
   waveColor: "violet",
   progressColor: "purple",
   backend: 'MediaElement',
   plugins: [
       RegionsPlugin.create({})
    ]
});
```

I get the following error

![screen shot 2019-01-07 at 8 20 55 pm](https://user-images.githubusercontent.com/11525891/50803917-c97a5c80-12b9-11e9-9a88-c505e6b9647c.png)

Where `RegionsPlugin` is undefined.

**Comment by thijstriemstra** [comment]
you're missing `<script src="https://unpkg.com/wavesurfer.js/dist/plugin/wavesurfer.regions.min.js"></script>`
