### ISSUE TITLE
Updating start & end times of region on drag?

### ISSUE THREAD

**Issue by MaxwellGover** [katspaugh/wavesurfer.js#1555]
I'm struggling with how to grab the updated start and end times of a region after the region is dragged. 

![screen shot 2019-01-09 at 6 09 41 pm](https://user-images.githubusercontent.com/11525891/50937873-b09db280-1443-11e9-8e82-d30af9c2ce72.png)

```
const wavesurfer = window.WaveSurfer.create({
      container: "#waveform",
      waveColor: "violet",
      progressColor: "purple",
      backend: "MediaElement",
      plugins: [
        window.WaveSurfer.regions.create({
          regions: [
            {
              start: 0,
              end: 20,
              color: "hsla(400, 100%, 30%, 0.5)",
              loop: true,
              drag: true
            }
          ],
          dragSelection: {
            slop: 5
          }
        })
      ]
});
```
Then later, 

```
wavesurfer.load(res.link);
    wavesurfer.on('ready', () => {
    console.log(wavesurfer.regions.list);
    console.log(wavesurfer.regions.getCurrentRegion());
            
    wavesurfer.play();
});    
```

I see there is an `onDrag` method but I'm not sure what I should be calling it on. Ideally, I'd like to do something like 

```
wavesurfer.load(res.link);
    wavesurfer.on('ready', () => {
    wavesurfer.regions.list.onDrag(() => {
        wavesurfer.regions.list.getCurrentRegion();
    });            
    wavesurfer.play();
});    
```

Again, I'm not exactly sure the best way to go about this. Any direction would be greatly appreciated.

Thanks!

**Comment by MaxwellGover** [comment]
Update: This seems to work

```
 wavesurfer.on('ready', () => {
        wavesurfer.on('region-updated', (obj) => console.log(obj))
        // wavesurfer.play();
 });
```

**Comment by Ramya-22** [comment]
Hi @MaxwellGover 

`region-updated`

This is called for all mouse move functionality.But  I need Updating start & end values of region on drag.


How can I call onDrag function


![2019-08-01_17-13-03](https://user-images.githubusercontent.com/42537872/62290782-c2967f80-b47f-11e9-8b21-970787717789.png)


cc - @katspaugh  @MaxwellGover
