### ISSUE TITLE
Cannot read property 'waveCtx' of undefined

### ISSUE THREAD

**Issue by Latentimagedesign** [katspaugh/wavesurfer.js#1556]
Wavesurfer.js version(s): 2.1.2
Browser version(s): Chrome Version 71.0.3578.98 (Official Build) (64-bit)
OS: Windows 10 x64

Issue:
I have a user load a video from local storage and wavesurfer.js creates a waveform of the audio. However, when pressing play on the html5 video player the following error is logged in the console:

> Uncaught TypeError: Cannot read property 'waveCtx' of undefined
    at n.value (drawer.multicanvas.js:486)
    at drawer.multicanvas.js:297
    at drawer.multicanvas.js:561
    at frame.js:12

When I pause the video and play again it display the waveform and everything is great again! Just looking for some insight. Thanks!

### Code needed to reproduce the issue:
```
window.wavesurfer = WaveSurfer.create({
              container: '#waveform',
              barHeight: 1.5,
              barWidth: 1,
              fillParent: false,
              minPxPerSec: 1,
              responsive: false,
              hideScrollbar: true,
              interact: false,
              waveColor: "rgba(1, 1, 1,0.7)",
              normalize: false
            });
            wavesurfer.load(settings.srcFile);

<div id="waveform"></div>

```

**Comment by thijstriemstra** [comment]
@Latentimagedesign can you create a codepen that re-creates this issue?

**Comment by thijstriemstra** [comment]
no feedback, closing.
