### ISSUE TITLE
Repeat crashes on iOS v11.03

### ISSUE THREAD

**Issue by kennCK** [katspaugh/wavesurfer.js#1557]
First, Thank you this is cool but I have question why on repeating the audio and seek bar crashes on iOS and all browsers in iOS. 

Here's my code
```
wavesurfer.on('finish', function(){
     wavesurfer.play(0)
     wavesurfer.drawer.progress(0)
 })
```
On other phones and os works smoothly.

**Comment by thijstriemstra** [comment]
> On other phones and os works smoothly.

Why not list them here? And include the wavesurfer.js version nr while you're at it.

**Comment by thijstriemstra** [comment]
no feedback.
