### ISSUE TITLE
Issue with rendering the saved region.

### ISSUE THREAD

**Issue by shobees** [katspaugh/wavesurfer.js#1561]
I have an issue with the region plugin . I want the region display when the the response from the server comes . So How can I update the region .. 
![12344](https://user-images.githubusercontent.com/28486850/51749351-f196f780-20d0-11e9-9c3d-83dcf27f52f0.png)

WaveSurfer.addRegion({
        start: 1.2235695986336466,
        end: 5.0111016225448335,
        attributes: {},
        data: {},
    })

I did this but causing wrapper error of undefined

init: function (wavesurfer) {
        this.wavesurfer = wavesurfer;
        console.log("hi surger");
        console.log(this.wavesurfer);
        this.wrapper = this.wavesurfer.drawer.wrapper;

        this.list = {};

        setInterval(() => {
            console.log(this.list);
        }, 1500)

        this.addEvents();
    },

**Comment by aburai** [comment]
do you use wavesurfer.on('ready')?
