### ISSUE TITLE
Audio files are too large, loading time is too slow, how to optimize? 

### ISSUE THREAD

**Issue by Leo1653** [katspaugh/wavesurfer.js#1563]
If the audio file is too large, such as a few minutes of loading time, is there a way to solve the problem of slow loading?
Lazy loading？update uodate？

**Comment by thijstriemstra** [comment]
Use the `MediaElement` and pre-generate the peaks on the server. See the https://wavesurfer-js.org/example/audio-element/index.html example.

**Comment by sahi1422** [comment]
@thijstriemstra , zoom-in, and zoom-out still takes very long. Seems like wave surfer recreates canvases and plots the entire waveform again. Can we have lazy plotting or something that will improve the zoom performance?

**Comment by msuhov** [comment]
@sahi1422 have you tried with `partialRender=true` param?
https://wavesurfer-js.org/docs/options.html

**Comment by sahi1422** [comment]
@msuhov , with partialRender = false, the browser gets stuck for the first few seconds(11 in my case) on zoom change, and then it is smooth but when I use partialRender = true, the browser gets continuously stuck when audio plays.

I am loading a file of 1 hour with a zoom level of 200 pxPersSec.

**Comment by kilgarenone** [comment]
Zooming is very laggy if I use a 4minutes long mp3 file in this example https://wavesurfer-js.org/example/zoom/index.html

Any advice to make the zoom smooth?
