### ISSUE TITLE
Unable to mute left or right channel in stereo audio file in 2.1.3 #1497

### ISSUE THREAD

**Issue by Vijayalaxmim** [katspaugh/wavesurfer.js#1565]
## Please make sure you provide the following information (if applicable):
This is duplicate of issue #1497 . The solution provided works with older version , but not with latest version. analyser object is not initialised when set filters is called. 
### Wavesurfer.js version(s):
2.1.3

### Code needed to reproduce the issue:

(Please reduce your code as much as possible and only post the minimum code needed to reproduce the issue. [A Code pen](http://codepen.io/) is an excellent way to share such code)

### Use behaviour needed to reproduce the issue:

[](url)

**Comment by thijstriemstra** [comment]
@Vijayalaxmim one very important thing missing: **code needed to reproduce the issue**.

**Comment by Vijayalaxmim** [comment]
I am using wavesurfer.js with React. After I initialise the state with wavesurfer, I split the channels using the below code

```
const splitter = wavesurfer.backend.ac.createChannelSplitter(2);
const merger = wavesurfer.backend.ac.createChannelMerger(2);
this.leftGain = wavesurfer.backend.ac.createGain();
this.rightGain = wavesurfer.backend.ac.createGain();
splitter.connect(this.leftGain, 0);
splitter.connect(this.rightGain, 1);
 this.leftGain.connect(merger, 0, 0);
this.rightGain.connect(merger, 0, 1);
// var analyser = wavesurfer.backend.createAnalyserNode();
//while calling the below line, analyser object is undefined
wavesurfer.backend.setFilters([splitter, this.rightGain, merger]);
```

**Comment by Vijayalaxmim** [comment]
The error stack trace 

```
Uncaught TypeError: Cannot read property 'connect' of null
    at n.value (wavesurfer.min.js:6)
```

**Comment by Vijayalaxmim** [comment]
@thijstriemstra Do you need more information on this?

**Comment by thijstriemstra** [comment]
@Vijayalaxmim yes can you use the normal version of wavesurfer.js (non-minified) and paste the full stacktrace and also create a codepen that reproduces this problem?

**Comment by Vijayalaxmim** [comment]
The issue got solved after using  'WebAudio'  as  backend instead of MediaElement
