### ISSUE TITLE
Waveform hides when scrolling to the end on mediaElement loaded server generated waveform

### ISSUE THREAD

**Issue by rockyhuber** [katspaugh/wavesurfer.js#1566]
### Wavesurfer.js version(s):
"wavesurfer.js": "^2.1.0",

### Browser version(s):
Version 71.0.3578.98

### Code needed to reproduce the issue:

My audio element:

`<audio id="audio"><source src={this.state.audioURL} type="audio/mp3"></source></audio>`

I set the media element;

> this.mediaElt = document.getElementById('audio');

I am loading it like this:
  ```
   this.wavesurfer = WaveSurfer.create({
      container: '#waveform',
      waveColor: 'gray',
      progressColor: 'rgb(14, 204, 208)',
      barWidth: 3,
      partialRender: true,
      responsive: true,
      scrollParent: true,
      scrollSpeed: 3,
      scrollThreshold: 50,
      height: 60,
      normalize: true,
      backend: 'MediaElement'
     })
```

I generate waveform on server:

> `audiowaveform -i ${inputAudio} -o ${outputWaveform} -b 8 --height 25 --pixels-per-second 100`

Once axios fetch returns, I am loading the generated waveform and audio file, and then calling this.mediaElt.load() to tell the media element that the audio source has been updated

`this.wavesurfer.load(this.mediaElt, this.state.waveformURL.data);`

Everything loads and plays nicely, though I am experiencing two key problems.

1. When I scroll left or right, the scroll bar unhides, however when I leave the waveform area, it never unhides again. Sometimes it does, other times it doesn't. It is very random in that sense. This was still occurring when I was using webaudio and not the mediaElement.

2. More importantly, when I scroll to the end of the waveform, it disappears completely and doesn't return. I believe this is an issue with the length of the audio/waveform that is being loaded.

e.target.scrollWidth (scroll width of the container)
34762

scrollWaveLeft (position at the end once I have completed scrolling)
33904

difference
858

So I can't scroll anymore, though it is saying that I still have 858 to scroll. At this point, the waveform completely disappears and I cannot see anything, though the audio still plays all the way to the end. On that note, the waveform does not sit flush with the left hand side of the screen, there is a 155px margin on the left. So I am unsure whether this has anything to do with this issue.

Any suggestions greatly appreciated.

**Comment by thijstriemstra** [comment]
try `hideScrollbar: true`?

**Comment by rockyhuber** [comment]
Thanks for your reply Thijs! I did, though then that doesn't allow me to scroll to beyond 40s of the waveform. I am not sure if I should be passing in a preload option to the load(url, peaks, preload) or not. Though don't think that will make a difference in this case.

**Comment by rockyhuber** [comment]
I hacked a awful scroll bar solution, though didn't solve the waveform disappearing at the end of the scroll. Basically just forced it to disappear when the mouse leaves the waveform.

On mouseleave of the waveform:
`this.wavesurfer.containers.childNodes[1].style.overflow = 'hidden';`

On mousenenter of the waveform:
`this.wavesurfer.container.childNodes[1].style.overflow = 'scroll';`

Still haven't been able to solve the disappearing waveform though ;(

**Comment by rockyhuber** [comment]
The problem occurs when you set partialRender to true. If you set it to false, then it won't occur.

**Comment by rockyhuber** [comment]
So after more research, turns out that it is because the width of the ends up being 1px bigger than the end value of the scroll.

A quick hack fix to add on approximately line 1076 of the wavesurfer.js file:

```
 if (
            this.params.fillParent &&
            (!this.params.scrollParent || nominalWidth < parentWidth)
        ) {
            width = parentWidth;
            start = 0;
            end = width;
        }

        **if (end > width) end = width;**

        let peaks;
        if (this.params.partialRender) {
            const newRanges = this.peakCache.addRangeToPeakCache(
                width,
                start,
                end
            );
            let i;
            for (i = 0; i < newRanges.length; i++) {
                peaks = this.backend.getPeaks(
                    width,
                    newRanges[i][0],
                    newRanges[i][1]
                );
                this.drawer.drawPeaks(
                    peaks,
                    width,
                    newRanges[i][0],
                    newRanges[i][1]
                );
            }
        }
```

**Comment by thijstriemstra** [comment]
@rockyhuber sounds familiar, can you try with 2.2.0?

**Comment by thijstriemstra** [comment]
no feedback, closing.

**Comment by rockyhuber** [comment]
Hi, sorry for the delay mate. Don't receive github notifications in email for some reason. I have done some custom work to wavesurfer, so will need to merge the code bases. Will let you know if the 2.2.0 fixes work in due course.
