### ISSUE TITLE
"ready" never called on safari

### ISSUE THREAD

**Issue by grosch** [katspaugh/wavesurfer.js#1567]
### Wavesurfer.js version(s):

2.1.3

### Browser version(s):

Safari on iOS 12 and Safari 12.0.3 on the mac.

### Code needed to reproduce the issue:

https://stackblitz.com/edit/waveform

### Use behaviour needed to reproduce the issue:

If you open that stackblitz with Safari on the desktop or iOS you'll see that the waveform starts to create as the extra spacing is added to the page, but the 'ready' message is never sent and the graph never fully loads.

If you load the same page with Chrome, things work just fine.

**Comment by thijstriemstra** [comment]
can you check if this safari-workaround (passing in a audiocontext after click/tap) fixes the issue: https://github.com/katspaugh/wavesurfer.js/blob/master/example/microphone/app.js#L12

**Comment by grosch** [comment]
Thank you!

**Comment by sonicviz** [comment]
I'm still getting this on Safari.
The workaround also doesn't work.
I'm using wavesurfer within vue/quasar. Works fine on windows. /chrome etc

Any clues on how to fix it.

**Comment by entonbiba** [comment]
@sonicviz ios requires user interaction for audio to be played, have a look here how to do that:
https://www.entonbiba.com/lab/wavesurfer/2007.html
