### ISSUE TITLE
Anyway to disable wave ?

### ISSUE THREAD

**Issue by naumanahmed19** [katspaugh/wavesurfer.js#1568]
Hi, 

Thanks for this awesome plugin. I want to ask is there any way to disable wave and show just progress bar. I have checked docs couldn't find any option or method.

**Comment by thijstriemstra** [comment]
@naumanahmed19 you can use CSS to hide the wavesurfer canvas element where the waveform is drawn. But to be honest, why use wavesurfer at all if you don't need the waveform?

**Comment by TOPSinfo** [comment]
@thijstriemstra I have a use case where users can minimize the audio player (rendering waves) and just see a progress bar.

**Comment by thijstriemstra** [comment]
@TOPSinfo sure.
