### ISSUE TITLE
Can't resolve 'debounce' in 'node_modules/wavesurfer.js/src/util'

### ISSUE THREAD

**Issue by Gabrielfcs** [katspaugh/wavesurfer.js#1569]
- [ X ] I have checked [the FAQ](https://wavesurfer-js.org/faq/) and it doesn't solve my problem.
- [ X ] I have checked [the documentation](https://wavesurfer-js.org/docs/) and it doesn't solve my problem
- [ X ] I have searched for [already open issues](https://github.com/katspaugh/wavesurfer.js/issues) which desribe my problem.
- [ X ] The issue I'm having is related to and caused by wavesurfer.js, not by other software (which maybe packages and uses wavesurfer incorrectly) – In that case you should open the issue on the respective project pages.

### Wavesurfer.js version(s):
> wavesurfer.js: "^2.1.3"
> angular version:  6.2.9

### Code needed to reproduce the issue:
No code needed, it happens when it runs.

Well, this problem occurs when the angular is compiling. The angular can't resolve the line 10 of archive index.js on util folder. In this case what i need to do? I solved this removing this line and i know why it is happen, but it is a bug, right? so, i believe that needs to be solved by owner of dependency.
I'm sorry if this issue is an idiot issue to be opened, but i need to know if it is possible to resolve. Sorry by my bad english too. 

Follows the attached error photo:

![captura de tela 2019-02-18 as 05 42 20](https://user-images.githubusercontent.com/8412815/52939440-f141f300-3342-11e9-9fd5-0b0940871a62.png)

Ps: I'm using a custom renderer and this error only occurs when I use this custom renderer!

**Comment by thijstriemstra** [comment]
>Well, this problem occurs when the angular is compiling.

Try asking the angular community.

**Comment by DevTash** [comment]
Hi,

I know the issue is closed however I solved this by including the debounce package from npm in my project. I did this because I noticed that line 10 in index.js for the utils directory didn't include './someFile.js' so I figured it was most likely a package that was needed.

Issue is now gone. Could be the wrong approach, the error appears when implementing a custom renderer.

Hope this helps.

**Comment by Gabrielfcs** [comment]
Thanks to everyone who wanted to help me and apologize for the delay of the answer, I solved this problem by excluding the folder node_modules and updating the dependencies. For some reason the debounce that was already in my project was not found by the wavesurfer index.js
