### ISSUE TITLE
Spectrogram keeps adding new listeners for each loaded audio

### ISSUE THREAD

**Issue by jamesshannon** [katspaugh/wavesurfer.js#1572]
Version: 2.1.3

Probably similar root cause as #1571, but I noticed that when listening to multiple  audio files (in series) with spectrogram enabled each load() took progressively longer.

You can see this in the javascript profiler in which I load a file, let it play, then load the next file. I did this 6 times while profiling and each load gets about .5 seconds longer than the previous one.

![image](https://user-images.githubusercontent.com/761381/53296015-0e9c1480-37bc-11e9-98b7-607af4085a1b.png)

That's because render() gets registered within constructor() each time a new file is loaded, and there doesn't appear to be any cleanup of the previous file or event handlers, so each time the audio is loaded render() is called one additional time.

Note that I haven't isolated this into a test case, but I'm not doing anything too out of the ordinary. Basically:

1. Setting up wavesurfer with cursor, timeline, spectrogram
2. Setting `ready` to play the audio automatically
3. A button to go to the next audio, which calls `wavesurfer.empty()` for good measure then `wavesurfer.load()`.
4. Hit button multiple times.

**Comment by jamesshannon** [comment]
I just noticed that the regions plugin is exhibiting a bug that's probably due to similar behavior when multiple audio files have been loaded. 

Specifically: load file, load more files, create a single region. Looking at the HTML elements or wavesurfer.regions.list the regions are duplicated, one for each audio that had been loaded.

**Comment by aburai** [comment]
@jamesshannon i load many files and create many regions and i don't have any problems. have a look at your code and ensure you create valid and unique html for every wavesurfer instance

**Comment by jamesshannon** [comment]
I only have one wavesurfer instance, and one single chunk of HTML. 

As per \#3 in my steps, I'm calling .empty() and .load() repeatedly to load successive files. I don't remember seeing anywhere in the documentation that I need to create a new instance everytime I load a file, but it seems that's probably the direction I need to go to ensure these bugs don't happen?

**Comment by aburai** [comment]
Sorry, i overread the empty() thing. It seems you must also call clearRegions(), empty does not change the regions list.

**Comment by jamesshannon** [comment]
That doesn't do it, either. I only ever create a single region, and I do so on the, e.g., 10th file (not the first 9). And when I do that 10 regions are instantly created.

For good measure I've been using clearRegions(), but that doesn't affect the above.

**Comment by thijstriemstra** [comment]
>  i load many files and create many regions

that sounds unrelated @aburai, because @jamesshannon is not using the regions plugin.

**Comment by jamesshannon** [comment]
https://jsbin.com/kizivenewa/edit?output

**Comment by thijstriemstra** [comment]
@jamesshannon that sample doesn't even use the spectrogram plugin..?

**Comment by jamesshannon** [comment]
No. That's illustrating the half of this bug having to do with regions,
which I described above and I'm pretty confident has the same root problem.

As far as I could tell, there's no programmatic way to demonstrate how many
times the spectrogram gets created, and it'd be too complex to explain how
to use Dev tools.

**Comment by aburai** [comment]
i think there must be removed some event listeners. you create 5 instances, create one region and get 5, one for every event listener

**Comment by thijstriemstra** [comment]
> i think there must be removed some event listeners. you create 5 instances, create one region and get 5, one for every event listener

@jamesshannon can you try master branch, I fixed some of the event handling in the spectrogram plugin.

**Comment by jamesshannon** [comment]
Is there an easy way to get a built file? unpkg doesn't have the dev versions?

**Comment by thijstriemstra** [comment]
Try https://github.com/katspaugh/wavesurfer.js#development

**Comment by jamesshannon** [comment]
The PR might have solved the bug in destroying the spectogram plugin, but it doesn't seem to have done anything for the fact that spectogram is adding new listeners each time a file is loaded.

I assume that this is the same root cause as the bug in the regions plugin, which I demonstrated in the jsbin URL which I posted above. But I think I caused more confusion, so I split that into its own bug and created a test case for the spectogram bug. This test case demonstrates exactly what I showed in the first screenshot, however it doesn't do nearly as good of a job because it relies on the anecdotal timings rather than the fire stack trace flame graph.

https://jsbin.com/kubudom/edit?output

And the output I'm seeing:

![image](https://user-images.githubusercontent.com/761381/55138949-defd6680-50f1-11e9-8864-1377c1476e89.png)

Note how each successive load takes about 500ms longer than the previous one.

**Comment by jamesshannon** [comment]
I think I figured this out locally. 

`enableDragSelection()` creates an anonymous `eventDown()` function locally and then calls `addEventListener()` (https://github.com/katspaugh/wavesurfer.js/blob/master/src/plugin/regions.js#L754).

It seems that calling `enableDragSelection()` on each new file is necessary, so my assumption that this was like the regions bug and `onReady()` was getting called too many times is incorrect.

However, it looks like there might be an assumption that you can call `addEventListener()` multiple times without any adverse affect but [that isn't true in this case](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#Multiple_identical_event_listeners).

My workaround fix was is to call `wavesurfer.disableDragSelection();` before loading a new file.

I tried to make `eventDown()` a non-anonymous function but realized it was relying on `_this8`. So I think the long-term fix will be to unload `eventDown()` (and any other anonymous functions like `onDown()`), or to create actual functions out of them and use binding in `addEventListener()` which, now that I think about it, probably breaks the no-duplicates feature.

**Comment by thijstriemstra** [comment]
Thanks for the test case. I fixed it in the master branch, give it a try if you can.
