### ISSUE TITLE
Couldn't add spectrogram plugin

### ISSUE THREAD

**Issue by achraf-boussaada** [katspaugh/wavesurfer.js#1574]
I'm testing out `wavesurfer` to generate spectrograms from wav files. I added as suggested : 
`<script src="https://unpkg.com/wavesurfer.js"></script>` to my html page and i was able to load my wav file and display it in a container. But i couldn't download the plugin for the spectrograms from  [the website](http://wavesurfer-js.org/example/spectrogram/?scroll). I think the link is broken and it's not accessible. Could you please fix the link or provide us with an other alternative from where we can get the plugin.

**Comment by achraf-boussaada** [comment]
i found this in the documentation `<script src="https://unpkg.com/wavesurfer.js/dist/plugin/wavesurfer.spectrogram.min.js"></script>` and it worked. Still the page linked above need some rework. For instance the quick start example doesn't work. It should be like this : 

       let wavesurfer = WaveSurfer.create({
            container: "#waveform",
            plugins: [
                WaveSurfer.spectrogram.create({
                    container: "#wave-spectrogram",
                })
            ]
        })

**Comment by mak0687** [comment]
Hello @achraf-boussaada ,

I have the same problem. How did you solve this? 
I now also included the url. Thank you for posting this.

**Comment by PickleNik** [comment]
@mak0687, from what I see, your problem is a bit different. Wavesurfer can't find the `container:` element. please double-check if you specified the right tag id (e.g. `container: "#wave-container",` ... `<div id="wave-container" />`,  and make sure it is rendered before you initialize the WaveSurfer. ;)
