### ISSUE TITLE
controls for multiple players one page?

### ISSUE THREAD

**Issue by fine-G** [katspaugh/wavesurfer.js#1575]
How can I play, stop and pause waveform when I have a unspecified number of players on a page?

I create the waveforms in an query each function, this init works fine. but how can I call the instances with the play button? Each waveform has an unique id and each waveform player has its own control buttons.

```
$('.audio').each( function(){
	var audio_src = $(this).find('.waveform-player').attr('data-audio-src');
	var player_id = $(this).find('.waveform-player').attr('id');
	
	var wavesurfer = WaveSurfer.create({
			container: '#' + player_id,
			progressColor: '#a4aa00',
			waveColor: '#9a9a9a',
			cursorColor: '#a4aa00',
			responsive: 'true'
		});
						
	wavesurfer.load(audio_src);
			
	wavesurfer.on('ready', function () {
		wavesurfer.play();
	});
						
});
```

This for example starts all waveform players.
I need something linke "this closest .waveform-player play()…

```
$(document).on('click', '.audio-controls .play', function(){ 
	wavesurfer.play();
});		
```

Can anyone please help me?

**Comment by aburai** [comment]
you can put your wavesurfer instance in data of your source element
`$(this).data('wavesurfer', wavesurfer)`
then search in you click handler for the element and get wavesurfer instance from data
`$(this).closest('.audio').data('wavesurfer').play()`

HTH

**Comment by fine-G** [comment]
perfect! thanks!
