### ISSUE TITLE
Waveform looks different in Chrome and Safari and timestamp does not match

### ISSUE THREAD

**Issue by Bran1304** [katspaugh/wavesurfer.js#1576]
### Code needed to reproduce the issue: N/A

When looking at a waveform with pre-decoded peaks in Chrome and Safari, the wave does not look the same, see screenshots below

Chrome:
<img width="840" alt="screenshot 2019-02-27 at 10 44 33" src="https://user-images.githubusercontent.com/9781704/53481541-bac05280-3a7d-11e9-8681-b661cff532d9.png">

Safari:
<img width="837" alt="screenshot 2019-02-27 at 10 44 26" src="https://user-images.githubusercontent.com/9781704/53481549-bf850680-3a7d-11e9-8c19-45db296e27b3.png">

It would not be such a huge issue, but the position/timestamp of the audio is also different. What you can hear on the 11th second of the audio in Chrome is different than the 11th second of the same audio in Safari.

Can you please have a look at this?

Thanks

**Comment by thijstriemstra** [comment]
@Bran1304 can you compare it to Safari Technology Preview (76) as well?

**Comment by thijstriemstra** [comment]
No feedback, closing.
