### ISSUE TITLE
iOS loadBlob from file input

### ISSUE THREAD

**Issue by grantmac** [katspaugh/wavesurfer.js#1580]
I'm currently calling ```waveform.loadBlob``` with a blob created from a file upload input.
On chrome this works perfectly and the waveform is rendered.
On Safari (mac and iOS) the waveform isn't rendered. In the following:

```
window.offlineAc.decodeAudioData(arraybuffer,
     function(data) {
         return callback(data);
    },
     e => {
        errback();
     }
);
```

The e variable is null and provides no information regarding the error.

Thanks

**Comment by thijstriemstra** [comment]
make sure you create a AudioContext in response to a user gesture on iOS. wavesurfer.backend.ac.state should not be `suspended`. If it is, call `resume` on that `ac`.

**Comment by grantmac** [comment]
Thanks @thijstriemstra - window.offlineAc.state = suspended. Is this an issue too?

**Comment by grantmac** [comment]
Here's a simple example: https://codepen.io/anon/pen/bZBNdz

To reproduce:
- Select an audio file from local device using the file input
- Click "Load Blob"

On Chrome this works fine. On Safari it dosen't. The AudioContext is begin created on the click of #btn

**Comment by grantmac** [comment]
Sorry, to slightly change this. mp3 files work, but I'm trying to get an mp4 video to work. This works in chrome but not safari.

**Comment by thijstriemstra** [comment]
> window.offlineAc.state = suspended. Is this an issue too?

yep.

**Comment by grantmac** [comment]
Thanks @thijstriemstra - I have the codepen working with mp3 files now. Any idea on why it's not working with mp4? 
The solution i'm looking for is for iOS users to be able to upload video files as there's no options to upload sound recordings.

**Comment by grantmac** [comment]
Video demo here: https://codepen.io/anon/pen/OqbVgM
To reproduce:
- Click "load blob" and it will load the wave form from the video element.
- Choose a video file via the input and the video file will be rendered int he <video> element.
- Click "load blob" and the wave form is rendered.

Works everywhere but safari macOS and iOS

**Comment by grantmac** [comment]
okay, mp4s work but not movs. And video uploads in iOS and movs.

**Comment by thijstriemstra** [comment]
> I have the codepen working with mp3 files now. 

Good to hear.
