### ISSUE TITLE
Wavesurfer rarely renders when using Media Element

### ISSUE THREAD

**Issue by bknill** [katspaugh/wavesurfer.js#1583]
Hi, 

I have the MediaEl already in the brower. 

If I try and load the El via load(el), I very rarely get the wave to show, if I load(el.src) then I always get the data. 

If I load the El before readyState > 0 I get a cannot decode data error in Chrome. 

I need to load the Element because I need Wavesurfer to control the playback position. 

### Wavesurfer.js version(s):
2.1.3

### Browser version(s):
Chrome 72
### Code needed to reproduce the issue:

```
    this.wavesurfer = WaveSurfer.create({
      container: this.$waveform,
      waveColor: '#9D66FF',
      progressColor: '#827794',
      backend: 'MediaElement',
      height: 80,
      plugins: plugins,
      hideScrollbar:true,
      partialRender:true,
    })

     if(el.readyState > 0)
        this.loadEl()
     else
      el.addEventListener('canplay', this.loadEl)

  loadEl(){
    const el = document.getElementById('audioEl')
    el.removeEventListener('canplay', this.loadEl)   
    this.createWaveform()
    this.wavesurfer.load(el.src)
  }
```

**Comment by thijstriemstra** [comment]
this is an incomplete example, please post something working that reproduces this issue.

**Comment by thijstriemstra** [comment]
no feedback, closing.
