### ISSUE TITLE
Regions plugin TypeError: Cannot read property 'addEventListener' of undefined

### ISSUE THREAD

**Issue by Bran1304** [katspaugh/wavesurfer.js#1587]
Hello,

I just updated to 2.2.0 and I get this error when I am trying to use the Regions plugin with enableDragSelection.

The error points to regions.js line 754 `this.wrapper.addEventListener('mousedown', eventDown);`

Thanks for your help

**Comment by thijstriemstra** [comment]
@Bran1304 can you provide example code?

**Comment by Bran1304** [comment]
@thijstriemstra 

In my wavesurfer component I create a wavesurfer instance like so

```
const wavesurfer = WaveSurfer.create({
      container: this.waveEl,
      backend: 'MediaElement',
      barWidth: 1,
      normalize: true,
      waveColor: '#BCC0CC',
      progressColor: '#36D2E0',
      minPxPerSec: 50,
      plugins: [
        RegionsPlugin.create({
          deferInit: true,
        }),
      ],
    })
```

and then in the Regions component I do this

```
componentDidMount() {
    const { wavesurfer } = this.props;
    wavesurfer.initPlugin('regions');
  }
```
And then I just call `wavesurfer.enableDragSelection({});` in the component that needs this functionality. This used to work in the previous versions, it only started to break with the above error after the 2.2.0 update.

**Comment by Bran1304** [comment]
I fixed the issue by removing deferInit: true and initialising straight away

**Comment by thijstriemstra** [comment]
@Bran1304 i'd rather make it work again without users having to modify code after upgrading. I'll take a look.

**Comment by thijstriemstra** [comment]
Glad you fixed it.
