### ISSUE TITLE
Multi-Channel Waveform Display

### ISSUE THREAD

**Issue by X-Raym** [katspaugh/wavesurfer.js#159]
Hi !
Your script is very promizing but it needs something more to met my needs.

Context : I would love to use this app in order to show and compare audio files in advanced mixing tutorials.
"This one has a reverb on the left, this one has nothing on the left except a tiny buzz"...

Feature : I wish your player has stereo (at minimum) audio waveform display :)
Even soundcloud don't do that =/

Thanks for listening :P

**Comment by naomiaro** [comment]
Hello, I'm looking into implementing this. I was wondering though @katspaugh if there's a reason this.params.renderer isn't in the docs? Is it just assumed it will be "Canvas" always?

**Comment by katspaugh** [comment]
Hi Naomi!

It would be cool!

Yes, "Canvas" is the only renderer, so...

**Comment by naomiaro** [comment]
I remember at one point there was svg? What happened with that?

**Comment by katspaugh** [comment]
@naomiaro people were complaining SVG waveform was slow to render and I saw no good reason to keep it.

**Comment by Kage1989** [comment]
I am interested in doing this enhancement as I might need it for my work. But before I start working on it, I just wanna know if there's anything that u might have on mind, eg. whether the canvas height should change with the number of channels to ensure the waveform do not get too squashed when viewing stereo audio files.

**Comment by voipmonitor** [comment]
Hello I need stereo waveform visualize to see what is going on in left channel and right channel for VoIP usage - left channel is caller and right channel is called. I'm willing to sponsor this for 150 USD if thats interesting for anyone to push this forward let me know.

**Comment by katspaugh** [comment]
@voipmonitor if mean something like this:

![Imgur](http://i.imgur.com/Q5k3bxq.png)

Then, I'm interested. Email me, katspaugh@gmail.com.

Otherwise, if you mean separate waveform for each channel, then @Kage1989 has already implemented that (see #356).
