### ISSUE TITLE
baby steps please assist

### ISSUE THREAD

**Issue by cristianvogel** [katspaugh/wavesurfer.js#1591]
Hi , 

i am simply trying to get the player to appear on a page and play some audio. 

I am really rather new at front end and I need a little help , I'm sorry if this is annoying... 

I have followed carefully the instructions, and I can neigher get the CodePen to run 

https://codepen.io/cristianvogel/pen/vPRdZb

or a local version on my server.... 

http://endless-process.net/playerDemo.html

Please could anyone just help a new guy out here? thanks

**Comment by thijstriemstra** [comment]
>  Error: Container element not found wavesurfer.js:1:16229

**Comment by cristianvogel** [comment]
ok - thankyou - it was CORS related and I am feeling more confident now. Sorry to bother you
