### ISSUE TITLE
MediaElement backend with .loadBlob

### ISSUE THREAD

**Issue by llenk** [katspaugh/wavesurfer.js#1599]
I'm trying to use .loadBlob with a MediaElement backend, and getting the following error:
```
wavesurfer.js:1493 Uncaught TypeError: Cannot read property 'querySelector' of undefined
    at MediaElement.load (wavesurfer.js:1493)
    at WaveSurfer.loadDecodedBuffer (wavesurfer.js:3929)
    at wavesurfer.js:3914
    at wavesurfer.js:4128
    at OfflineAudioContext.<anonymous> (wavesurfer.js:4759)
```
The line numbers/file names are off because of webpack, but the actual line of code throwing the error is https://github.com/katspaugh/wavesurfer.js/blob/master/src/mediaelement.js#L99

Is using .loadBlob with a MediaElement backend supported use, or should I stick to WebAudio backend?

### Wavesurfer.js version(s):
2.2.0

### Browser version(s):
Chrome 72

### Code needed to reproduce the issue:

https://codepen.io/llenk/pen/eXLRzd

Contains wave with Media element, and wave without Media element, with uploaded audio files.

**Comment by aburai** [comment]
1188 wavesurfer.js
```
    loadDecodedBuffer(buffer) {
        this.backend.load(buffer);
```

load() with backend MediaElement can't consume buffer, it wants url and container
currently you must stick to WebAudio, i think
