### ISSUE TITLE
Prevent auto seeking when user click to canvas

### ISSUE THREAD

**Issue by Wentris71** [katspaugh/wavesurfer.js#1609]
Hi, I need to save all of functionality but also have to cancel seeking position when user works with wavesurfer (create ranges).

I've separated seeking by alternative playback, and I wanna use canvas only for working with ranges and my extension - for seeking. A lot of our real users want it...

It looks like 
<img width="910" alt="Знімок екрана 2019-04-03 о 16 41 56" src="https://user-images.githubusercontent.com/18560311/55484268-e01e1e80-5630-11e9-92bb-38601437cabe.png">

Thx.

**Comment by thijstriemstra** [comment]
`interact: false`?

**Comment by Wentris71** [comment]
doh... sorry for stupid question, I thought this option can cancel creating of ranges. Thx a lot.
