### ISSUE TITLE
wavesurfer.load(url, peaks) with pre-rendered peaks doesn't load

### ISSUE THREAD

**Issue by batatop** [katspaugh/wavesurfer.js#1612]
### Wavesurfer.js version(s):
^2.2.1, 2.1.1

### Browser version(s):
Electron ^3.0.10

### Code needed to reproduce the issue:
```
this.wavesurfer = WaveSurfer.create({
   container: '#waveform',
   waveColor: '#d4d8df',
   progressColor: '#a2bfb4',
   cursorColor: '#DCDCDC',
   responsive: true,
   normalize: true,
   height: 70,
   backend: 'MediaElement',
})
					
this.wavesurfer.load(src, pcm)
this.wavesurfer.init()
```

### Use behaviour needed to reproduce the issue:
Waveform doesn't load when you provide pre-rendered peaks. It works without providing peaks. I generated peaks using `wavesurfer.exportPCM()` function.  I also provided constant peaks such as `[ 0.000030517578125, -0.000030517578125, ...]` to test but I didn't work either.

The examples that I could find online are using version 1.4.0 so I tried testing with that version. `wavesurfer.load(src, peaks)` function worked with version 1.4.0. However, `wavesurfer.exportPCM()` function didn't work this time.  `wavesurfer.exportPCM()` was working with ^2.2.1 and 2.1.1.

**Comment by thijstriemstra** [comment]
give this example a try: https://github.com/katspaugh/wavesurfer.js/tree/master/example/audio-element

**Comment by batatop** [comment]
I couldn't see any difference on the implementation. I use React so I tried to implement similarly. Also as I mentioned, when I don't provide peaks or when I use version 1.4.0, it works. Is there a difference between implementing regularly and with peaks other than `backend: 'MediaElement'` after version 2? Thank you.

**Comment by thijstriemstra** [comment]
>  I couldn't see any difference on the implementation.  I use React so I tried to implement similarly.

hehe, if it works in the example, and it doesn't work in your project, take another look.
