### ISSUE TITLE
code loss

### ISSUE THREAD

**Issue by ThoughtZer** [katspaugh/wavesurfer.js#1625]
![image](https://user-images.githubusercontent.com/23690568/56354752-282f6a80-6207-11e9-8bdc-53d0777714fc.png)

When I used wavesurfer by the cdn, I found that the code was lossed.why?

**Comment by thijstriemstra** [comment]
> When I used wavesurfer by the cdn, I found that the code was lossed.why?

Can you explain in more detail (using google translate)?

**Comment by ThoughtZer** [comment]
sorry， my English is too bad.☹

When I used codepen to practice wavesurfer.js, I found that the code was not the same as the npm package.

eg: https://codepen.io/thoughtzer/pen/NmYpEd

**Comment by ThoughtZer** [comment]
My original question is here.

The wavesurfer introduced by codepen does not have the seeking method, but the npm package has it. So I didn't reproduce the problem through the codepen.

https://github.com/katspaugh/wavesurfer.js/issues/1626#issuecomment-485612639

**Comment by thijstriemstra** [comment]
@ThoughtZer what you see in the master branch is not released yet (as v.3.0.0). So that's why it's missing in the NPM package. Either use master branch, or wait till v3.0.0 is released.
