### ISSUE TITLE
playLoop will not play a region on clips with duration <15s

### ISSUE THREAD

**Issue by rhamnett** [katspaugh/wavesurfer.js#1626]
Create one clip 5 seconds long, select a region and use  wavesurfer.regions.list[e.id].playLoop(); 

Outcome: File plays from the start.

Create one clip 16 seconds long, select a region and use  wavesurfer.regions.list[e.id].playLoop();  

Outcome: Clip plays the dragged region loop

**Comment by ThoughtZer** [comment]
Using the latest version, I found that the play method will be reported incorrectly. The reason is the listening of the seeking method.

**Comment by thijstriemstra** [comment]
> Using the latest version, 

can you be more specific?

**Comment by ThoughtZer** [comment]
version: 2.2.1

https://github.com/katspaugh/wavesurfer.js/blob/faa7d660f758f493914f30341c0983222788ab35/src/mediaelement.js#L158-L162


The timeStamp in this method will affect the execution of the play(start, end) method？The timestamp will be greater than the end to stop playing and jump to the end.

https://github.com/katspaugh/wavesurfer.js/blob/faa7d660f758f493914f30341c0983222788ab35/src/mediaelement.js#L283-L291

This is just one of my debuggers, maybe it is not correct.But after removing the seeking method, it will be ok.

**Comment by thijstriemstra** [comment]
the code you referring to was added to the master branch recently and has not been released yet. Looks like it's buggy.

**Comment by rhamnett** [comment]
This isn't closed. The other commenter is referring to something completely different from the original problem, which exists in the currently stable version of wavesurfer referenced in https://unpkg.com/wavesurfer.js

**Comment by thijstriemstra** [comment]
> This isn't closed. The other commenter is referring to something completely different from the original problem, which exists in the currently stable version of wavesurfer referenced

please open a new ticket with details

**Comment by thijstriemstra** [comment]
@moritzvieli any idea about this regions issue?

**Comment by moritzvieli** [comment]
I cannot reproduce this issue in the current master state form Github. Tested with a 5 seconds WAV file in Chrome and Safari - both worked as expected. @rhamnett Do you have more information? Can you maybe provide the WAV file you're using?

**Comment by ouzhou** [comment]
@moritzvieli hey , try this demo [https://codepen.io/ouzhou/pen/BeYdpJ](https://codepen.io/ouzhou/pen/BeYdpJ)

**Comment by ouzhou** [comment]
any update?

**Comment by thijstriemstra** [comment]
can you try v3.0.0 that was released recently?

**Comment by huanle0610** [comment]
I tried v3.0.0 https://codepen.io/huanle0610/pen/MWgrwEO ,  sometimes it doesn't work.
I hava a workaround.
![image](https://user-images.githubusercontent.com/953028/64351987-d6f50b80-d02d-11e9-82c5-b209f522e6f5.png)
[fork commit](https://github.com/huanle0610/wavesurfer.js/commit/ceaf927ea174ccac9342ef1797bead0f7d0a610a)
At last, I changed the approx to 1e-2.

**Comment by vvvhung** [comment]
I also just try today v3.0.0 but it still not work. It will make chrome freeze afterward. So I come back to v2 and try to implemented using setInterval (or setTimeout). Here is my code that I test it work on chrome (my region start time and end time point are rounded to 3 decimal digits) :
`var interval_obj = null;
var playloop_region = null;
function playloop(region) {
    if (playloop_region && (region != playloop_region)) {
        if (interval_obj) {
            clearInterval(interval_obj);
            interval_obj = null;
        }
    }
    playloop_region = region;
    var start = region.start;
    var end = region.end;
    var interval = Math.ceil(1000 * (end - start));
    interval_obj = setInterval(function(){
        region.play();
    }, interval);
    region.play();
}
wavesurfer.on('pause', function() {
    if (interval_obj) {
        clearInterval(interval_obj);
        interval_obj = null;
    }
});`

I don't know if this way can be consider a good direction for current issue.

**Comment by thijstriemstra** [comment]
@vvvhung can you try the workaround suggested by @huanle0610?

**Comment by vvvhung** [comment]
@thijstriemstra I tried, and it only play 3 times then raise Uncaught (in promise) DOMException.

**Comment by aburai** [comment]
i detected problems with very short regions (1s) and region.play()
i get DOMException ABORT_ERR: pause() interrupt play() multiple times
this is because mediaelement listen on audioprocess to detect onPlayEnd
and then call pause(), but did not use the promise resolve
[see developers.google.com](https://developers.google.com/web/updates/2017/06/play-request-was-interrupted)
in my case i iterate over text segments, create a region, play it and go to next segment when reach
the region end
i listen to the region-out event, but sometimes the onPlayEnd is triggered and no region-out is fired
as a workaround i use now `wavesurfer.play(reg.start)` to play a region

**Comment by huanle0610** [comment]
@vvvhung can you try my new version https://codepen.io/huanle0610/full/MWgrwEO? I have made several regions with 1s, 2s, 5s, 8s ...

**Comment by vvvhung** [comment]
@huanle0610 yes, I see your example work well. I also try to copy your code to may app and it also work (a bit unexpected but seem playLoop already work). cc @thijstriemstra

**Comment by thijstriemstra** [comment]
good to hear it works for you @vvvhung

**Comment by huanle0610** [comment]
@vvvhung sorry, I forgot to explain that the region plugin in codepen demo is a specail version built from my fork(mentioned in my first issue comment).  After u said it didn't work last time, I only ajusted approx threshold. So if someone use region plugin from npm like me, are most vulnerable to this issue.  I'll try to crate a PR, it may helps.
