### ISSUE TITLE
Adjusting the waveforms with offset time in the beginning for multiple tracks

### ISSUE THREAD

**Issue by vikasmagar512** [katspaugh/wavesurfer.js#1627]
# offsetting the waveforms with some time 
Thanks community for building such an awesome library.
I am trying to build up an open source application like [soundtrap](https://www.soundtrap.com)

- I am able to perform basic functions like cut, copy, paste regions
- How to offset tracks with some time in before, between and after a waveform, so that i can decide how to sequence the multiple tracks like way soundtrap does ?
- refer the image https://i.imgur.com/EadG6zA.png
- As well as if someone can guide me on how to store the audio editor state on the server side like Node ?

I am open to sharing code if needed.

Thanks in advance.

**Comment by thijstriemstra** [comment]
please try to build this app, and whenever you encounter a wavesurfer.js-related bug, open a ticket. This is not a forum.

**Comment by marizuccara** [comment]
> I think there is a legitimate question here: does wavesurfer.js allow you to render a waveform with several milliseconds of audio trimmed off the beginning of the track? (Or several ms of silence appended to the beginning?)
> 
> How do you map between x-distance on the canvas and time?

Hi, you can try perform operations on audio data with the WebAudio backend. Decoding audio data, you obtain an AudioBuffer with samples and you can modify this AudioBuffer appending your own samples at the beginning of the buffer. Then you can load directly your decoded buffer with `loadDecodedBuffer` method.
