### ISSUE TITLE
Transformation Matrix throws off interaction

### ISSUE THREAD

**Issue by mayorbyrne** [katspaugh/wavesurfer.js#1629]
Hello, if there is a transformation matrix on the container div, the waveform loads and displays, but the interact portion gets thrown off.

In [this example](https://wavesurfer-js.org/example/audio-element/index.html), you can see for yourself if you add `transform: matrix(0.5, 0, 0, 0.5, 0, 0)` to the `#waveform` div

Is there any way to remedy this or should I disable user interaction and manually listen, setting `seekTo` based on cursor position? If this is the case, how can I set the currentTime with a manual seekTo so when I hit "play" it plays from that point?

**Comment by thijstriemstra** [comment]
@mayorbyrne you probably need to apply the transform on the `waveCtx` in `wavesurfer.drawer.canvases[0].waveCtx` (and do it for every canvas in that `canvases` array).

https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/transform
