### ISSUE TITLE
Load peaks without a media element?

### ISSUE THREAD

**Issue by GregoryWullimann** [katspaugh/wavesurfer.js#1630]
Hi

Currently I'm generating the peaks on the server, and then fetch them with javascript, as explained in the FAQ (https://wavesurfer-js.org/faq/)

Everything is fine but what I want to achieve is to call `load` without passing a media url/element, so I want only to use the peaks array, something like this:

` wavesurfer.load(null, peaks.data);`

Is it possible to achieve it in some way?

**Comment by thijstriemstra** [comment]
> Everything is fine but what I want to achieve is to call load without passing a media url/element, so I want only to use the peaks array, something like this:

Eh, why? Why load without a valid URL (or `HTMLMediaElement`)?

**Comment by aburai** [comment]
do not use load, instead set peaks via `wavesurfer.backend.setPeaks(peaks, duration)` and draw `wavesurfer.drawer.drawBars(peaks, width, 0, width)`
