### ISSUE TITLE
Turn off browser audio pre processing

### ISSUE THREAD

**Issue by rssdave** [katspaugh/wavesurfer.js#1634]
Hello, 

We have noticed that when recording in Chrome and Firefox audio is being be pre-processed by the browsers as detailed here:

https://stackoverflow.com/questions/31426551/get-consistent-audio-quality-with-getusermedia-using-different-browsers?rq=1

Where would we add options to turn this off? It looks like we are required to add:
```javascript
navigator.getUserMedia(

        {

            "audio": {

                "mandatory": {

                    "googEchoCancellation": "false",

                    "googAutoGainControl": "false",

                    "googNoiseSuppression": "false",

                    "googHighpassFilter": "false"

                },

```

**Comment by thijstriemstra** [comment]
You use the `constraints` option of the microphone plugin: https://github.com/katspaugh/wavesurfer.js/blob/master/src/plugin/microphone.js#L3
