### ISSUE TITLE
Not transcribing spaces correctly

### ISSUE THREAD

**Issue by Kailegh** [katspaugh/wavesurfer.js#1636]
Hi, I was trying to use WaveSurfer to transcribe some audios. My problem is that when I type a space in the .lab pane, it is automatically converted to _ . I do not know why spaces are converted to underscores, is there a way to solve this? 
Thanks a lot for your work!

**Comment by aburai** [comment]
I think you should provide more context.

**Comment by Kailegh** [comment]
I load and audio, and using the .lab pane I input some transcript, when I type a space, y get and underscore, as seen in next picture
![image](https://user-images.githubusercontent.com/20105814/56891707-a698d180-6a7d-11e9-8ca9-d5d26465d99e.png)

However if I use the browse option i can type spaces with no problem at all
![image](https://user-images.githubusercontent.com/20105814/56891790-ee1f5d80-6a7d-11e9-888c-65df6ee708e7.png)

I do not know what might be causing this issue

**Comment by thijstriemstra** [comment]
what is a `.lab pane`? please provide some code to reproduce this.

**Comment by thijstriemstra** [comment]
no feedback, closing.
