### ISSUE TITLE
Stop Waveform being processed. Is it possible?

### ISSUE THREAD

**Issue by Ziggy2001** [katspaugh/wavesurfer.js#1639]
Hi, is there a way to stop the waveform being processed?

If I load a piece of audio to wavesurfer then it starts to generate the peaks. However, if I then load another piece of audio instead to the same wavesurfer instance with some pre-rendered peaks then the pre-rendered peaks appear, but then get overwritten by the previous files peaks.

Every file should have pre-rendered peaks in my project and this wouldn't come up normally, but it's a hole and I like to make sure these things are boxed off. Stopping the rendering process would be great when a new file is loaded.

**Comment by thijstriemstra** [comment]
can you lay out in steps when/where you want to abort the process?

**Comment by Ziggy2001** [comment]
This command is raised to load the file and by default will start generating the peaks for the file.

`wavesurfer.load( file1 );`

Before the above file has finished rendering the waveform / peaks, this command is raised, usually by user interaction, and has pre-rendered peak data:

`wavesurfer.load( file2, peaks );`

At this point file2 loads quickly with the waveform.

Then after a few seconds the waveform changes to that of file1 but the sound is file2.

Does that make more sense?

**Comment by Ziggy2001** [comment]
For anyone else having this issue I managed to alleviate it by setting the forceDecode parameter on the fly.

When I find pre-rendered peaks, before loading, I set:

`wavesurfer.params.forceDecode = false;`

When I don't find pre-rendered peaks I set:

`wavesurfer.params.forceDecode = true;`

It appears setting to false before loading pre-rendered peaks, stops the previous rendering, which is what I'm after.
