### ISSUE TITLE
Adding fixed scale to timeline

### ISSUE THREAD

**Issue by nikhilkhedkar** [katspaugh/wavesurfer.js#1641]
While trying to use WaveSurfer, we want to enforce a standard scale to the timeline. At any given point in time, we want only 30 seconds of the audio file to be displayed. For navigating to previous or next sections of the audio file, the user would click on Previous or Next buttons. I think the default functionality of WaveSurfer does not allow for any such scale to be specified. The scrollbars are shown based off the length of the audio file.

Do you have any suggestions to implement the feature?

**Comment by thijstriemstra** [comment]
there's a format time parameter (and others) in the timeline plugin you can use to adjust the scale.
