### ISSUE TITLE
wavesurfer.exportPCM, great - now what?

### ISSUE THREAD

**Issue by conraddeweteuphoria** [katspaugh/wavesurfer.js#1645]
Hi, I'm using wavesurfer quite nicely to achieve what I want - I can record from the Mic using MediaRecorder, or Uploading from my PC... all good.

Now its time to upload the "previewed" audio that wavesurfer has, so I found exportPCM(length, accuracy, noWindow, start), and im pretty sure I can figure out what to supply in length, accuracy, noWindow and start, but want I cant figure out, is: Now what? 

The json is a bunch of what looks like floating point numbers... OK, but how does that become a WAV format.

MediaRecorder only supports either webm or Ogg, and I get that wavesurfer is (probably) RAW PCM - and that's great, because I can use something to convert it from RAW PCM (like SOX). But how do I get it into Blob or Binary as base64?

My intention is to post this to the server (probably base64 in ajax)

**Comment by aburai** [comment]
exportPCM only exports the peaks
to export the audio have a look at https://stackoverflow.com/questions/22560413/html5-web-audio-convert-audio-buffer-into-wav-file
HTH
