### ISSUE TITLE
Logarithm scale on Y axis in Spectrogram plugin

### ISSUE THREAD

**Issue by stouch** [katspaugh/wavesurfer.js#1648]
Hi,

I was wondering if there exists an option to print canva chart of spectrogram plugin using a logarithm scale on Y axis (KHz) in wavesurfer.js 2.2.1 ?

Like this for example :

![690x0w](https://user-images.githubusercontent.com/305679/61191025-a3d57200-a6a5-11e9-8310-6ab8a0d7f0f4.jpg)

It would really useful in certain cases !

Thank you

**Comment by thijstriemstra** [comment]
cc @shershey

**Comment by trekhopton** [comment]
I second this, it would be a useful addition.

**Comment by thijstriemstra** [comment]
maybe @dofuuz is interested in adding this.

**Comment by Tiebe-Vercoutter** [comment]
Hi, I see this is closed as completed but can't seem to find this feature? Where should I looking?
Thanks in advance.

**Comment by katspaugh** [comment]
It wasn't completed, it was closed for the lack of activity. I'm not going to work on this, but PRs are welcome.

**Comment by Tiebe-Vercoutter** [comment]
Ah okay thanks for clarifying

**Comment by jfbaraky** [comment]
Any updates on this? I'm working on a project where the user should be able to select the scale and we're expecting to use Linear, Logarithmic, Mel, Bark and ERB

**Comment by Dabolus** [comment]
I see that this was closed as completed in #3790. However, that PR adds support for different scales but doesn't include support for the logarithmic one, or am I missing something? 🤔

**Comment by Dabolus** [comment]
Thanks for reopening! I'm not a spectrogram expert, but I will try to do something similar to the PR above to add support for logarithmic scale too

**Comment by Dabolus** [comment]
I opened the PR with my initial attempt. Any feedback is welcome!

**Comment by katspaugh** [comment]
Thank you @Dabolus! 🎉 
Merged and released in 7.8.14.
