### ISSUE TITLE
Release 3.0

### ISSUE THREAD

**Issue by thijstriemstra** [katspaugh/wavesurfer.js#1651]
Essential:

- #1365 (fetch api, also see PR #1541)

Nice to have:

- #1642 (desynchronized canvas hint)
- #1640
- #1654 (spectrogram plugin: allow user to specify a colorMap)

**Comment by thijstriemstra** [comment]
I think everything is ready for a 3.0.0 release, except doc stuff:

- updating the docs in the `gh-pages` branch
- updating the `UPGRADE` document in the root of the repository (and `gh-pages`)

want to help out with that @aburai?

**Comment by aburai** [comment]
@thijstriemstra sorry, i am currently busy with customer projects, but i will test v3 when it is released
