### ISSUE TITLE
Webpack error - Cannot find module "wavesurfer.js"

### ISSUE THREAD

**Issue by eugene-ilyin** [katspaugh/wavesurfer.js#1652]
Hello, I have trouble with using Wavesurfer.js through npm.

### Browser and operating system version(s): 
Linux Mint 18.2
npm v6.9.0
nodejs v8.11.4
webpack 2.2.0

### Use behaviour needed to reproduce the issue:
I use an Angular 4.3.6. 
The Wavesurfer.js was installed through `npm install --save wavesurfer.js`
I've imported it as 
`import WebAudio from 'wavesurfer.js';`
And I've got an error.

**Error in browser:** 
> Uncaught Error: Cannot find module "wavesurfer.js"

**Error in the console where I do build:**
> ERROR in /home/eugene/prj/work/CORE/src/app/components/audio-static/audio-static.component.ts
> Module not found: Error: Can't resolve 'wavesurfer.js' in '/home/eugene/prj/work/CORE/src/app/components/audio-static'
>  @ /home/eugene/prj/work/CORE/src/app/components/audio-static/audio-static.component.ts 6:22-46
>  @ /home/eugene/prj/work/CORE/src/app/web-base.ts
>  @ ./src/app/main.ts

CORE is my custom npm package linked to the host project through `npm link`, I don't think that it's important, but I've mentioned it to provide full information.

I've checked file node_modules/wavesurfer.js/dist/wavesurfer.js and I see that there are multiple constructions
```
exports.default = SOMETHING;
module.exports = exports.default;
```
Looks like they override each other, and only the last - "WebAudio" is available for import.

It looks strange to me that the library can be so popular and nobody mentioned this problem. I'm not so strong in a system of modules, and maybe my idea about the root cause of the problem is wrong.
Could someone advise me, how to solve this problem?

**Comment by thijstriemstra** [comment]
> webpack 2.2.0

use webpack 4 and newer

**Comment by eugene-ilyin** [comment]
@thijstriemstra Thank you for a quick response. Yes, it's a good answer. I believe that we will update webpack on this year.
But this project is pretty big, our build has a lot of customizations, we can't just update webpack right now. I think it will take a lot of time. Maybe you or somebody else know some workaround, how to resolve this problem on webpack 2?
