### ISSUE TITLE
Can I load mp3 audio from Google Drive?

### ISSUE THREAD

**Issue by diegoiglesias** [katspaugh/wavesurfer.js#1653]
Hi,

I've been trying to load mp3 audio files to WaveSurfer with no luck. Here is a CodePen: https://codepen.io/anon/pen/XwVPgJ

Example of working demo using HTML5 <audio>:
https://codepen.io/anon/pen/wbpXML

Is it anything I can do to make it work on WaveSurfer? If the wave rendering is the problem, I can create a png on the server and skip that process on the JS to just use it as a player.

Thanks!

**Comment by thijstriemstra** [comment]
no luck? what's the error message?

**Comment by aburai** [comment]
wavesurfer.load uses an ajax request and your source (Google Drive) needs to enable CORS for this
try to google for google drive cors to get more informations

**Comment by diegoiglesias** [comment]
Okay I just solved the problem using a little trick thanks to [this post](https://mnaoumov.wordpress.com/2018/02/05/download-google-drive-file-via-ajax-ignoring-cors/). To skip the CORS issue you just need to prepend "https://cors-anywhere.herokuapp.com/" to the Google Drive URL and it'll work fine :)

I've updated the example in CodePen:
[https://codepen.io/anon/pen/XwVPgJ](https://codepen.io/anon/pen/XwVPgJ)

Hope it helps to anyone having the same issue.
Thanks!
