### ISSUE TITLE
playLoop is not work

### ISSUE THREAD

**Issue by ouzhou** [katspaugh/wavesurfer.js#1655]
try this demo [https://codepen.io/ouzhou/pen/BeYdpJ](https://codepen.io/ouzhou/pen/BeYdpJ)

first , click the input tag and choose a file(wav or mp3) , then select a region and click the region

it will loop at first time, but stop loop later and never loop again

by the way , if you create two regions, click the first region and click the other region quickly , the 'out' event will fire infinite times

**Comment by ouzhou** [comment]
at [https://github.com/katspaugh/wavesurfer.js/blob/master/src/plugin/regions.js#L107](https://github.com/katspaugh/wavesurfer.js/blob/master/src/plugin/regions.js#L107)

and if i dont use `e.stopPropagation();`
region.play() will play until finish... emmm confusing event design? 

waiting for help : )

**Comment by thijstriemstra** [comment]
is this a duplicate of #1626?

**Comment by ouzhou** [comment]
no , because errors can occur in any case. not only <15s condition

**Comment by ouzhou** [comment]
i think it is a bug...

**Comment by ouzhou** [comment]
any help?

**Comment by thijstriemstra** [comment]
@ouzhou can you try the master branch and build wavesurfer using [these instructions](https://github.com/katspaugh/wavesurfer.js#development) and check if the problem still exists?

**Comment by ouzhou** [comment]
:(  3.0 is not work 
choose a region smaller than 3s

**Comment by ThoughtZer** [comment]
@ouzhou 

https://github.com/katspaugh/wavesurfer.js/blob/832e114b7be6436458fc351a57699ba169d08676/src/plugin/regions.js#L233-L238

Try to delete ```Math.round```? or change to ```Math.ceil```?

**Comment by ouzhou** [comment]
i give up, i think if you want to use this repo, you'd better write it by yourself
