### ISSUE TITLE
The AudioContext was not allowed to start

### ISSUE THREAD

**Issue by mmasomi73** [katspaugh/wavesurfer.js#1657]
Hi 

i tired really :(
i see #1531 & #1560

Examples is work correct without Error, But my samples not working, in issues not explain how fix this problem

**Comment by mmasomi73** [comment]
it's my sample: http://play.mmasomi.ir/

**Comment by thijstriemstra** [comment]
@mmasomi73 what browser, what operating system, what wavesurfer.js version etc

**Comment by mmasomi73** [comment]
any supported browser such as _chrome v.74_ 
_wavesurfer.js 2.2.1_
in local system is ok but when put on host not work

please help me, how fix them?

**Comment by mmasomi73** [comment]
all my code: [https://github.com/mmasomi73/player](https://github.com/mmasomi73/player)

**Comment by thijstriemstra** [comment]
you need to call `wavesurfer.backend.ac.resume()` in a button click to work around the autoplay restrictions in chrome i think.

**Comment by mmasomi73** [comment]
thanks, i use that but not working

when i use `<audio>` tag and play once with `<audio>` tag and after reload page is work
and every time reload page show download audio alert

**Comment by moussaeltayeb** [comment]
Have the same problem. `wavesurfer.backend.ac.resume()` does not remove the warning. In addition to that, it does play on safari for iOS, but without any sound. You can try the example at the home page of [https://wavesurfer-js.org](https://wavesurfer-js.org)

**Comment by thijstriemstra** [comment]
> wavesurfer.backend.ac.resume() does not remove the warning

try creating a new audio context in a button click handler, and then create wavesurfer instance and pass in that audio context.

**Comment by thijstriemstra** [comment]
Marking this as a duplicate of #1531.
