### ISSUE TITLE
resizes Cannot adjust selection area size      wavesurfer.regions.js

### ISSUE THREAD

**Issue by chwang9** [katspaugh/wavesurfer.js#1661]
wavesurfer.js regions plugin 2.2.1 (2019-03-18) 
add to       
if (this.drag || this.resize) {
     e.stopPropagation();
}
Cannot adjust selection area size

**Comment by chwang9** [comment]
Someone taught me how to revise it like this.   
Old areas allow coverage of new areas
 if (e.target.tagName === "HANDLE") {
        e.stopPropagation(); 
  }

**Comment by thijstriemstra** [comment]
this change was added in https://github.com/katspaugh/wavesurfer.js/commit/25a0fb40375379e8330bac41c2a80806e0e9b9c8 by @moritzvieli. Can you check this ticket @moritzvieli?

**Comment by moritzvieli** [comment]
@chwang9 sorry, I did not fully understand the issue. Can you tell me exactly, how I need to reproduce it? Thanks a lot!

**Comment by thijstriemstra** [comment]
no feedback, closing.
