### ISSUE TITLE
Player doesn't seek with MediaElement backend

### ISSUE THREAD

**Issue by sujitsagar** [katspaugh/wavesurfer.js#1664]
I am using the MediaElement fallback since the audio files I use are quite large and decoding with Web Audio takes quite a lot of time.

The issue is the cursor doesn't move even though the audio starts playing in the background. When I manually click on a random place on the wave, the cursor starts seeking and plays from there, but throws the errors "Uncaught Error: The error you provided does not contain a stack trace." && "Uncaught (in promise) DOMException"

Are there any fixes for this?

**Comment by thijstriemstra** [comment]
@sujitsagar can you provide example code and let us know what operating system, browser and version of wavesurfer?

**Comment by sujitsagar** [comment]
I am using React-Waves on the top of wavesurfer.

`
<ReactWaves
                    audioFile={this.state.audioFile}
                    className={'react-waves'}
                    //pos={this.state.currenttime}
                    options={{
                        barHeight: 2,
                        barWidth: 1,
                        backend: podcast.backend,
                        cursorWidth: 2,
                        height: 100,
                        hideScrollbar: true,
                        cursorColor: '#564fca',
                        progressColor: '#564fca',
                        responsive: true,
                        waveColor: '#D1D6DA',
                        fillParent: true,
                        loop: false,
                        //loopSelection: false
                        partialRender:  true,
                    }}
                    duration={podcast.length}
                    onAudioprocess={this.onAudioProcess}
                    onLoading={this.onLoading}
                    onReady={this.onWaveformReady}
                    onWaveformReady={this.onWaveformReady}
                    audioPeaks={podcast.peaks}
                    volume={1}
                    zoom={1}
                    loop={false}
                    playing={this.state.playing}
                    onFinish={()=> this.onFinish()}
                    onPosChange ={(time) => {
                        this.setState({ currenttime: time });
                        localStorage.setItem( "podcasttime" + podcast.key, toHHMMSS(time) );
                    }}
                    />
Browser - Chrome on Mac OS
Version: 2.2.1

`

**Comment by thijstriemstra** [comment]
Ask the React-Waves project in that case.
