### ISSUE TITLE
Cannot Resize Regions added during .create

### ISSUE THREAD

**Issue by ecirish** [katspaugh/wavesurfer.js#1669]
I'm looking to utilize Wavesurfer and the `Regions` plugin to create an initial region, and then allow the user to resize it.  I'm able to create the region, and it appears on the instance as expected:

![wavesurfer](https://user-images.githubusercontent.com/2439563/59385823-cda81b80-8d2a-11e9-8d5c-79089961e7c5.PNG)

I also explicitly set `resize` and `drag` to true on creation:

```
var wavesurfer = WaveSurfer.create({
      container: '#waveform',
      backend: 'MediaElement',
      waveColor: 'violet',
      hideScrollbar: true,
      autoCenter: false,
      progressColor: 'purple',
      plugins: [
        WaveSurfer.timeline.create({
          container: '#wave-timeline'
        }),
        WaveSurfer.regions.create({
          regions: [
            {
              id: 0,
              start: self.currentTime,
              end: self.currentTime + 15,
              color: 'hsla(400, 100%, 30%, 0.5)',
              resize: true,
              drag: true
            }
          ]
        })
      ]
    })
```

However, **I'm unable to resize the created region**.  If I enable `dragSelection` in the region options, I can create new regions and resize them, but not initially created regions.

Finally, if I log the created region:
```console.log(wavesurfer.regions.list[0])```

The region indeed reports `drag` and `resize` as being set to true:

```
**attributes: {}
color: "hsla(400, 100%, 30%, 0.5)"
data: {}
drag: true
element: region.wavesurfer-region
end: 15.603342
firedIn: false
firedOut: false
handlers: {remove: Array(3), out: Array(1)}
id: 0
loop: false
maxLength: undefined
minLength: undefined
resize: true
scroll: false
scrollSpeed: 1
scrollThreshold: 10
start: 0.603342
style: ƒ (e,t)
util: {…}
wavesurfer: t {handlers: {…}, defaultParams: {…}, backends: {…}, util: {…}, params: {…}, …}
wrapper: wave
_onRedraw: ƒ ()
__proto__: Object
```

What am I missing? Some of the examples do indeed allow for created regions to be resized.

**Comment by thijstriemstra** [comment]
> What am I missing?

what version of wavesurfer.js? did you try master branch?

**Comment by ecirish** [comment]
Ah, sorry for not including my version #.

I'm using `2.2.1` from `npm`.

**Comment by ecirish** [comment]
Just tried master. Same behaviour.

**Comment by ecirish** [comment]
Couldn't figure out how to get it to work during `.oncreate`, but it does work fine if you add the region after the instance is ready.

```
wavesurfer.on('ready', function () {
      wavesurfer.addRegion({
        id: 0,
        start: self.currentTime,
        end: self.currentTime + 15,
        color: 'hsla(1, 77%, 55%, 0.25)',
        resize: true,
        drag: true
      })
    })
```

**Comment by iamsteadman** [comment]
Sadly that's not the case. The region doesn't appear when you create it using the `ready` event.

**Comment by thijstriemstra** [comment]
@iamsteadman does your PR #1673 fix this issue?

**Comment by HassanAlgoz** [comment]
Still doesn't work. I'm using version `2.2.1`. Any updates on this?
