### ISSUE TITLE
split audio from mono on one channel to play on both channels

### ISSUE THREAD

**Issue by asystemsaus** [katspaugh/wavesurfer.js#1670]
I love wavesurfer, I think its brilliant.
I have one minor question.
I have .mp3 files where audio is on only 1 channel. Can I have it play on both channels. i know its still mono but i need to have it played in both earpieces of headset.

**Comment by asystemsaus** [comment]
I love wavesurfer, I think its brilliant.
I have one minor question.
I have .mp3 files where audio is on only 1 channel. Can I have it play on both channels. i know its still mono but i need to have it played in both earpieces of headset.

**Comment by thijstriemstra** [comment]
Ask on stackoverflow, this is not wavesurfer.js specific.
