### ISSUE TITLE
region double click 

### ISSUE THREAD

**Issue by maxmood** [katspaugh/wavesurfer.js#1671]
I want to use region-dblclick event on my wavesurfer project
this is [code pen](https://codepen.io/anon/pen/VJvRoZ);
Double click on any region, wavesurfer just start playPause() whereever the mouse clicked, but what I wanted was like just play clicked region for once like this [code pen](https://codepen.io/anon/pen/xoweEN)
Plz help me out if there is anyway I can use region-dblclick but still get the same result like single click does .THANKS !

**Comment by thijstriemstra** [comment]
@maxmood you're using an ancient version of wavesurfer.js, please try 2.2.1 or the upcoming 3.0.0.

**Comment by thijstriemstra** [comment]
no feedback, closing.
