### ISSUE TITLE
Zoom in then out doesn't work for larger audio files

### ISSUE THREAD

**Issue by edgework** [katspaugh/wavesurfer.js#1674]
### Wavesurfer.js version(s): 

2.2.1

### Browser and operating system version(s): 

Chrome, Safari, Firefox  all versions.

### Code needed to reproduce the issue:

The Zoom example loading  https://traffic.megaphone.fm/VMP5001295639.mp3  for the audio

### Use behaviour needed to reproduce the issue:

Zoom In  a few clicks

Zoom out all the way

Waveform is not totally zoomed out.

**Comment by thijstriemstra** [comment]
I can see this can be confusing. The minimum value for the `minPxPerSec` is 20, so it'll never go to 0. And to completely reset the zoom, you use `wavesurfer.zoom(false)`.

I will add an initial zoom to the example that matches the min value.
