### ISSUE TITLE
Failed to execute 'decodeAudioData' on 'BaseAudioContext': parameter 1 is not of type 'ArrayBuffer'.

### ISSUE THREAD

**Issue by falseLuffy** [katspaugh/wavesurfer.js#1675]
when I import wavesurfer.js@2.2.1  to vue component ，the console error  “Failed to execute 'decodeAudioData' on 'BaseAudioContext': parameter 1 is not of type 'ArrayBuffer'.”

this is my code .
```
import WaveSurfer from 'wavesurfer.js'
this.wavesurfer = WaveSurfer.create({
        container: '#waveform',
        waveColor: 'violet',
        progressColor: 'purple'
 })
this.wavesurfer.load('../../../../static/audio.mp3')
this.wavesurfer.on('ready', function () {
        this.wavesurfer.play()
})
```

**Comment by thijstriemstra** [comment]
can you make a codepen that reproduces this? what operating system and browser?

**Comment by wildRoseYFL** [comment]
遇到一样的问题，你解决了吗

**Comment by thijstriemstra** [comment]
no feedback, closing.

**Comment by SmileTao** [comment]
这个问题我今天遇到了，应该是他封装的ajax请求对数据做了处理导致解析音频出现参数类型不匹配，需要修改它内置的ajax请求为原生的ajax请求。
我这里的处理是：
window.XMLHttpRequest = window.XMLHttpRequestBAK;

**Comment by SmileTao** [comment]
我今天也遇到了这个问题，我这里原因是没有使用它内置的ajax请求来获取文件导致解析文件参数类型不匹配。
我这里的解决办法是：
window.XMLHttpRequest = window.XMLHttpRequestBAK;

**Comment by v-nhandt21** [comment]
![image](https://github.com/katspaugh/wavesurfer.js/assets/36092323/efefe5ce-fc14-4f52-907a-ce2598d6116c)

I got the same problem, I have checked the audio integrity

'''
"wavesurfer.js": {
      "version": "7.0.0-beta.7",
      "resolved": "https://registry.npmjs.org/wavesurfer.js/-/wavesurfer.js-7.0.0-beta.7.tgz",
      "integrity": "sha512-s/dGecTL8pDg8ApBdegrGSZDEAy1BAlRAUjopjghz26M+YGiZKmdV0p/dIxBbosANdxb8zBOjHIakZ+Oc5Dghg=="
    },
'''

![image](https://github.com/katspaugh/wavesurfer.js/assets/36092323/5dba2df9-8ab5-4b1c-9c7e-77adfde33a8c)
