### ISSUE TITLE
Inspect wavesurfer regions list content

### ISSUE THREAD

**Issue by abeeraleisa** [katspaugh/wavesurfer.js#1678]
Wavesurfer.js version(s):
2.2.1

Browser version(s):

Google Chrome
Version 75.0.3770.100 (Official Build) (64-bit)

Problem
Hey there! I tried to access the regions list but I couldn't. I read all the documentation, issues and searched my issue but I didn't find a way to see the list's content.

Any ideas?
Code:

<img width="522" alt="Screenshot 2019-06-24 at 13 17 39" src="https://user-images.githubusercontent.com/52158762/60011700-0b8a3580-9683-11e9-9b26-19a7654751fa.png">

**Comment by aburai** [comment]
at first look it is ok
what is the exact error?
ensure wavesurfer is the correct instance, seems to be a global var

**Comment by abeeraleisa** [comment]
I went back to the documentation and I solved my issue, It was something about the library.
Thank you.
