### ISSUE TITLE
After upgrade wavesurfer.js from 2.1.3 to 2.2.1 I can't resize and drag old regions 

### ISSUE THREAD

**Issue by Aparus** [katspaugh/wavesurfer.js#1679]
### Wavesurfer.js version(s):
2.2.1

### Browser and operating system version(s):
Google Chrome 75.0.3770.100 , windows 8.1, 64bit

After upgrade wavesurfer.js from 2.1.3 to 2.2.1 Regions plugin doesn't work properly. Even [example on your site ](https://wavesurfer-js.org/plugins/regions.html)
**Old regions** (witch almost exist when create waveform) are not dragable or resizible. But new ones are resizeble and dragable... 

My code is working just like your example. Old regions not resizeble and not drageble. But new ones are.

```
    this.wavesurfer = WaveSurfer.create({
      container: this.waveform,
      scrollParent: true,
      minPxPerSec: 200,
      plugins: [
        RegionsPlugin.create({
          regions,
          dragSelection: true
        }),
        TimelinePlugin.create({
          container: this.timeline
        })
      ]
    });
```

**Comment by andrewjaykeen** [comment]
I also ran into this problem today.  I'll just provide what I've learned so far about this issue.  I was unable to use the regions plugins with the NPM modules, so I just pointed directly to the CDN.  

Such as: 
```    <script src="https://unpkg.com/wavesurfer.js@2.1.3"></script>
    <script src="https://unpkg.com/wavesurfer.js@2.1.3/dist/plugin/wavesurfer.regions.min.js"></script>```

When using version 2.2.1, I can't drag or resize any regions added to the `plugins.regions` array in the WaveSurfer constructor, nor can I drag/resize any regions that are added programmatically with the WaveSurfer `addRegion()` method.  

When using version 2.1.3, however, I CAN drag/resize regions added to the `plugins.regions` array in the WaveSurfer constructor, but still *NOT* with regions created using the `addRegion()` method.   

As the OP mentioned, this is new regions (that the user creates) are allowed to be resizable/draggable, in all versions.

**Comment by thijstriemstra** [comment]
@Aparus can you try the master branch?

**Comment by Aparus** [comment]
@thijstriemstra I'm sorry, I didn't understand... 
**Should I try install wavesurfer.js in different way ?** Please explain with more details. 
I did
`npm i wavesurfer.js` and in package.json I saw change "2.1.3" -> "2.2.1"
then I downgraded 
`npm i wavesurfer.js@2.1.3`

**Comment by thijstriemstra** [comment]
@Aparus https://github.com/katspaugh/wavesurfer.js#development

**Comment by Aparus** [comment]
@thijstriemstra , I use wavesurfer.js like module inside Create React App , and I don't use commands from your link (and I suppose they don't work in CRA). And I didn't see in page, you have sent link on it, what do you mean about "master brach"... (

**Comment by thijstriemstra** [comment]
@Aparus, follow the instructions I linked and copy the resulting `dist/wavesurfer.js` into the `node_modules/wavesurfer.js/dist/` directory of your project.

**Comment by thijstriemstra** [comment]
@Aparus v3.0 was released. Can you try that?

**Comment by Aparus** [comment]
@thijstriemstra, thank you. Yes, I run `npm i wavesurfer.js@3` and plugin updated. And then everything works fine!
