### ISSUE TITLE
Timeline not matching waveform when its scrollParent property is true

### ISSUE THREAD

**Issue by shiyameng** [katspaugh/wavesurfer.js#1680]
Hi Katspaugh,

I create a waveform with the param `scrollParent: true`,
When the audio is too short, the Timeline is stretched to the entire parent container.

To fix wavesurfer.timeline.js line 472
`var width = wsParams.fillParent && !wsParams.scrollParent ? this.drawer.getWidth() : this.drawer.wrapper.scrollWidth * wsParams.pixelRatio;`

I am running a 2.2.1 version of wavesurfer.

Thank you

PS- Here is a screenshot of what I'm talking about:
![image](https://user-images.githubusercontent.com/6477217/60264969-0e9d5400-9917-11e9-9d9f-d3e08f8d262a.png)

**Comment by thijstriemstra** [comment]
@shiyameng I am not able to reproduce this with the git master branch. Can you provide a codepen that reproduces this?

**Comment by shiyameng** [comment]
This is the pencode address. https://codepen.io/shiyameng/pen/JQzPZV

**Comment by aburai** [comment]
You don't want to fill the parent. Decrease the width of your viewport (body) or set `fillParent: true`

**Comment by shiyameng** [comment]
I have different audio lengths, some audio lengths are longer.so I don't want to fill the parent.
This problem occurs when the width of canvas is smaller than that of viewport.
I don't know the width until the canvas rendering is complete
