### ISSUE TITLE
Region selection - scrollbar appears

### ISSUE THREAD

**Issue by klodoma** [katspaugh/wavesurfer.js#1683]
### Wavesurfer.js version(s):
"wavesurfer.js": "^2.2.1",

### Browser and operating system version(s):
Chrome, Win10

### Steps to reproduce:
Open this url on a big-enough screen/browser so that there is no scrollbar in the wavesurfer container. 
https://wavesurfer-js.org/plugins/regions.html

Drag a region then drag the region completely to the right. A scrolllbar appears. 
The same happens if you directly select a region completely to the right. Probably the "region right" selection div goes out of the container. 

![Screenshot_405](https://user-images.githubusercontent.com/944350/60801719-c7655d80-a177-11e9-9d16-4610e50f9933.png)
![Screenshot_406](https://user-images.githubusercontent.com/944350/60801720-c7655d80-a177-11e9-8399-200b0ab01b5f.png)

**Comment by thijstriemstra** [comment]
> Drag a region then drag the region completely to the right. A scrolllbar appears.

I can't reproduce this with v3.0.0 @klodoma (that the website also uses atm).

**Comment by thijstriemstra** [comment]
no feedback, closing.
