### ISSUE TITLE
how to get peaks data

### ISSUE THREAD

**Issue by zzuzsj** [katspaugh/wavesurfer.js#1684]
Hello.I'm here to ask a question about the wavesurfer.
I want to know weather I can get the values rendered in the canvas so i can use it to do other things.
I didn't find api for this.

**Comment by thijstriemstra** [comment]
> the values rendered in the canvas 

what do you specifically mean? the peaks data?

**Comment by zzuzsj** [comment]
Yep.I think it's the data I want

**Comment by aburai** [comment]
`wavesurferInstance.drawer.getPeaks()`

**Comment by zzuzsj** [comment]
![image](https://user-images.githubusercontent.com/20783807/61141145-7cdd3b80-a4ff-11e9-952d-8e7379f6978a.png)
I found the code about getPeaks.And i have a question about this.
Why push min and max values into mergePeaks,instead of use a single data - average value?

**Comment by lionel-lints** [comment]
I just wanted to add in case this is helpful: when using `MediaElement` mode for backend loaded media, I found the mergePeaks at `WaveSurferInstance.backend.mergedPeaks`.

**Comment by psukhanov** [comment]
Trying this on wavesurfer.js 3.3.3 and not seeing a getPeaks() method available on the wavesurfer.drawer instance. Was this moved/removed? Is there an alternative way of getting the peaks data? Or am I doing something wrong? :)

**Comment by marizuccara** [comment]
Hi @psukhanov , you can get peaks calling ` wavesurfer.backend.getPeaks()`. The method is available in `webaudio.js`.

**Comment by SeanBannister** [comment]
For anyone else who finds this `getPeaks()` requires a value to work, for example `getPeaks(512)` the value is "How many subranges to break the waveform into." so the higher the number the more detailed the waveform. If you want the waveform in as much detail as possible it appears `mergedPeaks` does this. Here's an example:

```
  wavesurfer.on('ready', function () {
    console.log(wavesurfer.backend.getPeaks(10));
    console.log(wavesurfer.backend.mergedPeaks);
  });
```
