### ISSUE TITLE
Issue / Question regarding ScriptProcessorNode

### ISSUE THREAD

**Issue by eek** [katspaugh/wavesurfer.js#1689]
Hi there!

I'm having a more advanced-related issue with Wavesurfer (using the latest: 2.2.1, on Chrome 75 on Ubuntu 19.04 - but it's happening an Chrome on Mac as well).

It's a bit hard to send a codepen with what I'm doing since I'm using Wavesurfer in a bit more advanced of a way.

I'm actually processing the audio before feeding it into Wavesurfer, I have a long audio, and I want to show multiple segments of that audio.

So the steps are:

1. Fetch the Audio File
2. Create an Audio Context and Decode the Audio
3. Create another Audio Context with which I create an Audio Buffer and copy the segment interval that I want into the new Buffer.
4. Close all audio context and return the new Audio Segment.

Load it into WaveSurfer with `wavesurfer.loadDecodedBuffer()`

Everything works well, except that on page refresh, the CPU Usage is high (50-60%), media playback (including video) is affected. It seems this happens when I create the elements without having any kind of user interaction for the page.

I debugged to see where the issue was, and it seems that `onaudioprocess` from the `removeOnAudioProcess` key is called many many many times with no call stack (I have no idea who calls it);

The Script Processor Node seems to be in a `running` state (should it have been in a suspended state?)

![image](https://user-images.githubusercontent.com/2953026/61051046-0520eb00-a3f1-11e9-9f1d-ab395e87248e.png)

Every time I pause execution the `currentTime` from the AudioContext increases, although my audio has 6 seconds, `currentTime` increases forever.

I've also print-screen the segments I have (3), one 5.10s, one 0.26s, and one 0.33s

I search a bit around the internet and I've found that the issue might be with `ScriptProcessorNode` which apparently has been deprecated for `AudioWorkletNode`, `createJavaScriptNode` is also deprecated and obsolete.

So my thinking was to replace the audioScriptProcessor with something new, I couldn't with `AudioWorkletNode` since there's no connect so I went for the `AnalyserNode`

I've fed it via the waveSurferParams on `audioScriptProcessor` but the problem is that in order to work I need to create a new Instance, aka `new AnalyserNode()` and I need the `audioContext` which is in wavesurfer which doesn't exist when I want to feed it a new Processor.

I've replaced in `waveSurfer`:  `this.scriptNode = this.params.audioScriptProcessor` in `createScriptNode()` with `this.scriptNode = new this.params.audioScriptProcessor(this.ac);` just to give it a try.

There's no longer a high CPU Usage but there's no longer `this.scriptNode.onaudioprocess` either, playing works but drawing where the currentProgress is doesn't. Weirdly enough, if I take a look at `window.WaveSurferAudioContext` after they load (and they don't play), `currentTime` increases forever as well.

Apparently a quicker fix for me would be to call `window.WaveSurferAudioContext.suspend()` once everything has loaded.

Does anyone have any ideas? :scream: 

PS: On Safari there's no issue because the AudioContext is suspended hence it doesn't increment time.

**Comment by thijstriemstra** [comment]
> this.scriptNode = this.params.audioScriptProcessor 

you can also just create a script processor outside wavesurfer and pass it to wavesurfer using that `audioScriptProcessor` parameter/setting.

**Comment by eek** [comment]
yes, but in order to give it like this:

```javascript
WaveSurfer.create({
  container: this.waveform.current,
  audioScriptProcessor: new AnalyserNode(audioContext),
});
```

And I don't have WaveSurfer's `audioContext` there, and if I create one it errors because it needs to be the same.

**Comment by thijstriemstra** [comment]
@eek and there's also a `audioContext` parameter where you can pass in a custom AudioContext.
