### ISSUE TITLE
Plot more than one waveforms on top of each other

### ISSUE THREAD

**Issue by bebekar** [katspaugh/wavesurfer.js#1691]
I have to plot 2 audios over each other, one being the Expert voice and the other recorded by the user, each with different color. This would help in a visual compare of the 2 audios. 

Any advise

**Comment by thijstriemstra** [comment]
it's a css thing once you created 2 wavesurfer instances using javascript. did you try creating 2 wavesurfer waveforms in seperate html elements?

**Comment by bebekar** [comment]
I want them to be in the same canvas however separate control per instance.  I have tried with your recommended way with core css however found it difficult to implement in UI frameworks

**Comment by thijstriemstra** [comment]
> found it difficult to implement in UI frameworks

any suggestions to improve it in wavesurfer.js are welcome, closing.
