### ISSUE TITLE
How do i skip/ crop leading silent audio from the waveform display

### ISSUE THREAD

**Issue by bebekar** [katspaugh/wavesurfer.js#1692]
Some audio especially recorded have leading silence or low level noise which I would like to eliminate from the waveform. This would involve detecting based on the amplitude and deleting it from the audio.

**Comment by thijstriemstra** [comment]
You would have to use external tools to do this, maybe something like ffmpeg or sox. This is not something wavesurfer.js aims to fix (unless you can make a convincing plugin that can filter noise etc from a stream).
