### ISSUE TITLE
Set minimum bar height

### ISSUE THREAD

**Issue by awkspace** [katspaugh/wavesurfer.js#1693]
Sometimes, particularly with larger audio files (like a podcast), Wavesurfer generates a waveform with gaps.

This by itself is a surprising result. I followed the method [in the FAQ](https://wavesurfer-js.org/faq/) to generate peak waveform data, and there are no gaps in my audio long enough that they should be visible. The position of the gaps also differs depending on the width of the player, which would suggest a bug in the way that Wavesurfer handles a large amount of peak data.

Regardless of the cause, however, I'd like to ensure that the waveform is never drawn with bars with a height of 0. Is there a way to set the minimum bar height to avoid this issue?

**Comment by thijstriemstra** [comment]
`barHeight` option? https://wavesurfer-js.org/docs/options.html

**Comment by MacedonianPepper** [comment]
@awkspace same problem. 
![image](https://user-images.githubusercontent.com/24991543/61952841-a1d0b480-afbd-11e9-80c0-655c2ced0036.png)
![image](https://user-images.githubusercontent.com/24991543/61952891-b7de7500-afbd-11e9-85c3-82b76334620d.png)

**Comment by jimhucksly** [comment]
I have the same problem. Waiting to resolve!

**Comment by MacedonianPepper** [comment]
wavesurfer.js file:
![image](https://user-images.githubusercontent.com/24991543/67279624-0b386480-f4d4-11e9-8894-3a6d07f1a242.png)

**Comment by jimhucksly** [comment]
@thijstriemstra I would be happy if you fix this issue early as possible

**Comment by jimhucksly** [comment]
@MacedonianPepper Thanks! Your fix resolving this bug

**Comment by thijstriemstra** [comment]
thanks @MacedonianPepper, can you make a pull request? I guess we would introduce a new option for this feature?
