### ISSUE TITLE
Generate PCM data through SOX

### ISSUE THREAD

**Issue by Mr-Lopes** [katspaugh/wavesurfer.js#1697]
Hi, guys! Thank you for the awesome plugin!

I am having trouble with memory leak when rendering large files (over 50mb). So, in order to have a workaround, I am generating the pcm data using SOX on the server side (Amazon linux). Everything works, however I haven't gotten the conversion right; the peaks are inverted. Huge peaks on silent moments and none when there is not silent (a person speaking, for example).

Has anyone done this before? I've looked for answers, but I haven't find anything.

SOX command used: "sox audio.mp3 -c 1 -e floating-point audio.dat"
Result:
![image](https://user-images.githubusercontent.com/6962758/61502528-f2cb2200-a999-11e9-99de-13d016f8c5d4.png)

Any help would be very appreciated!
Cheers

**Comment by thijstriemstra** [comment]
@Mr-Lopes you can use the https://github.com/bbcrd/audiowaveform tool for that, see bottom of the faq: https://wavesurfer-js.org/faq/

Hopefully this helps to figure out to get the peaks right with sox. And if you do, please share here so we can add that to the FAQ as well as an alternative method.

**Comment by thijstriemstra** [comment]
Also take a look at https://github.com/azcoppen/waveform-generation (which even uses wavesurfer.js!)

**Comment by Mr-Lopes** [comment]
Thank you for the suggestions, guys. Unfortunately, I wasn't able to generate pcm data using Sox, so I managed to install the waveform on my Amazon server instead.

For those with this issue, I'd indicate adding Centos' mirror for the missing libraries in the Amazon linux:
https://centos.pkgs.org/7/centos-x86_64/
