### ISSUE TITLE
region-created fired multiple times

### ISSUE THREAD

**Issue by klodoma** [katspaugh/wavesurfer.js#1698]
### Wavesurfer.js version(s):
2.2.1
3.0.0

### Code needed to reproduce the issue:
```javascript
wavesurfer.on("ready", function() {
  wavesurfer.regions.enableDragSelection({});
  wavesurfer.regions.enableDragSelection({});
  wavesurfer.regions.enableDragSelection({});
  wavesurfer.regions.enableDragSelection({});
  wavesurfer.regions.enableDragSelection({});
});

wavesurfer.on("region-created", function(region) {
  console.log("region-created", region.id);
});
```
https://codepen.io/klodoma/pen/gVbmmV

### Use behaviour needed to reproduce the issue:
Just select some regions, the region-created event is fired for every **_enableDragSelection_** call

### Workaround
always call disableDragSelection before enableDragSelection.

```javascript
    wavesurfer.regions.disableDragSelection();
    wavesurfer.regions.enableDragSelection({});
```
The result of creating 3 regions: 

![Screenshot_434](https://user-images.githubusercontent.com/944350/61519212-9ef92100-aa0b-11e9-850f-ae2840847fbc.png)

**Comment by klodoma** [comment]
Probably related to #752

**Comment by thijstriemstra** [comment]
at the time @katspaugh mentioned:

> Yes, I can reproduce it. enableDragSelection() adds DOM event listeners every time it's called. I suppose a simple flag wavesurfer.regionsEnabled = true should help. Can you send a pull request?

Interesting in creating such a PR @klodoma?

**Comment by klodoma** [comment]
>  Can you send a pull request?
> Interesting in creating such a PR @klodoma?

Sure :) never did it on github, but I guess it's a good start :)

**Comment by saumyaborwankar** [comment]
This happens in the react component as well. Can someone help? 
const { wavesurfer, isPlaying, currentTime, isReady } = useWavesurfer({
    container: containerRef,
    height: 100,
    waveColor: 'rgb(200, 0, 200)',
    progressColor: 'rgb(100, 0, 100)',
    url: props.post.contentUrl?.replace('mp4', 'mp3'),
    plugins: useMemo(() => [Timeline.create(), regionsPlugin], [regionsPlugin]),
  });
  useEffect(() => {
    if (isReady && wavesurfer) {
      regionsPlugin.enableDragSelection({
        color: 'rgba(154, 207, 111, 0.2)',
      });
    }
  }, [isReady]);
  
  This causes 2 regions to be selected each time. And there is not function for disableDragSelection on regionsPlugin
