### ISSUE TITLE
getChannelData is not a function ?

### ISSUE THREAD

**Issue by K3nn3th2** [katspaugh/wavesurfer.js#1700]
Hey Folks,

I'm currently developing an android application with DroidScript and wavesurfer.js.
It worked wonderfully after i had got past some issues.
All of a sudden, it will not work anymore. get the following error:

Script Error: this.buffer.getChannelData is not a function, Line 1, wavesurfer.min.js

I will try to see what changed..

Can anyone explain to me why this error is occuring? It could help me find and squash the bug..

Thanks a lot!

**Comment by thijstriemstra** [comment]
what version of wavesurfer.js, etc etc?

**Comment by K3nn3th2** [comment]
Originally with wavesurfer 1.2.3
But its the same with other versions as well

**Comment by thijstriemstra** [comment]
@K3nn3th2 please add some example code that reproduces this problem (and operating system/browser version info).

**Comment by K3nn3th2** [comment]
im running on android with DroidScript.
It seems to have something to do with my Android and/or DroidScript version, because it worked on my android 8 phone before. 

i tried a minimum example on my pc which worked, and ran it in droidscript to recieve the same error as stated in the title.

ill try to get my hands on an android 8 phone again to try it there
