### ISSUE TITLE
Playing with no audio on iOS 12.4

### ISSUE THREAD

**Issue by syonip** [katspaugh/wavesurfer.js#1701]
## The issue:
The waveform is rendered, and it seems like it's playing (you see the ticker moving), but there is no audio.
I've tried the audio context workaround suggested in #1415, but to no avail.
Thanks.

### Wavesurfer.js version(s):
latest (whatever https://wavesurfer-js.org uses)

### Browser and operating system version(s):
iOS Safari 12.4

### Use behaviour needed to reproduce the issue:
Just navigate to https://wavesurfer-js.org/ and click play

**Comment by iamomiid** [comment]
Same on iOS 14

**Comment by sundayz** [comment]
iOS 14.5 is now available to the public, which brings huge improvements to audio in iOS. Re-open the issue if the problem persists in 14.5.
