### ISSUE TITLE
Plugin feature not working

### ISSUE THREAD

**Issue by Pratyush1197** [katspaugh/wavesurfer.js#1705]
I want to add Timeline plugin but it is not working. I am getting the error
  `Uncaught TypeError: Cannot read property 'create' of undefined` 
My code is as follows
`var wavesurfer = WaveSurfer.create({
  container: '#waveform',
 waveColor: 'violet',
 progressColor: 'purple'
});`

// adding and initialising a plugin after initialisation
`wavesurfer.addPlugin(WaveSurfer.timeline.create, {
    container: '#wave-timeline'
}).initPlugin('timeline')
wavesurfer.load('sample.mp3');`

Please help!!

**Comment by killia15** [comment]
Can you post your import statements?

Here's what I did:

```
import * as WaveSurfer from 'wavesurfer.js';
import * as TimelinePlugin from 'wavesurfer.js/dist/plugin/wavesurfer.timeline.min.js';
...
         this.waveSurferInstance = WaveSurfer.create({
            container: this.audioWaveformElement,
            plugins: [
               TimelinePlugin.create({
                  container: this.timelineElement
               })
            ]
         });
     this.waveSurferInstance.load(audioFileSource);
```

**Comment by Pratyush1197** [comment]
I am using the cdn which is as follows-
 `<script src="https://cdnjs.cloudflare.com/ajax/libs/wavesurfer.js/1.2.3/wavesurfer.min.js"></script>
  
  <script src="https://unpkg.com/wavesurfer.js/dist/plugin/wavesurfer.timeline.min.js"></script>`

**Comment by thijstriemstra** [comment]
> wavesurfer.js/1.2.3/

that's a really really old version. Try the latest version instead @Pratyush1197:

```html
<script src="https://unpkg.com/wavesurfer.js/dist/wavesurfer.min.js"></script>
<script src="https://unpkg.com/wavesurfer.js/dist/plugin/wavesurfer.timeline.min.js"></script>
```

**Comment by Pratyush1197** [comment]
still getting the same error
`Uncaught TypeError: Cannot read property 'create' of undefined`

**Comment by thijstriemstra** [comment]
Did you try the timeline example? Are you saying that example isn't working for you? https://github.com/katspaugh/wavesurfer.js/blob/master/example/timeline/app.js

**Comment by Pratyush1197** [comment]
Yes I am getting the error that create is undefined

**Comment by aburai** [comment]
wrong placed brackets
```
wavesurfer.addPlugin(WaveSurfer.timeline.create({ container: '#wave-timeline' })).initPlugin('timeline')
```

**Comment by Pratyush1197** [comment]
Still getting the same issue...Can someone tell me what can be the reason behind such error?

**Comment by Pratyush1197** [comment]
Like it is showing create is not defined

**Comment by thijstriemstra** [comment]
the reason is using an ancient version.
