### ISSUE TITLE
when the audioRate of wavesurfer is lower than 0.7, the isPlaying() of wavesurfer is true, but the region using Regions Plugin can't 

### ISSUE THREAD

**Issue by AngleMi** [katspaugh/wavesurfer.js#1707]
### Code needed to reproduce the issue:

![image](https://user-images.githubusercontent.com/38134963/62194202-facc8e00-b3ab-11e9-94b8-7b8d39828e81.png)
![image](https://user-images.githubusercontent.com/38134963/62194080-b04b1180-b3ab-11e9-8a1c-f1c2a118cf84.png)

### Use behaviour needed to reproduce the issue:
I use Regions Plugin to create a region and when it created, it can looply play. When the audioRate of wavesurfer is lower than 0.7, the isPlaying() of wavesurfer is true, but the region using Regions Plugin can't looply paly

**Comment by AngleMi** [comment]
Sorry, the pasting code was written in a wrong place，audioRate: 0.5,

**Comment by thijstriemstra** [comment]
@AngleMi always test with latest version

**Comment by thijstriemstra** [comment]
there is no global `loop` option for the regions plugin, that `loop` option only applies to single regions. After testing with latest master (upcoming 3.1.0 release) this seems fixed.
