### ISSUE TITLE
Pre-Render Waveform from server - Angular

### ISSUE THREAD

**Issue by NavjotKumar** [katspaugh/wavesurfer.js#1711]
I'm working on a soundcloud like app where the user will see a playlist full of waveforms. I want to render all the peak data on the server to avoid having the user load all the songs at once just to display the waveforms.
Is there any solution??

**Comment by thijstriemstra** [comment]
sure, see bottom of FAQ on how to render the peak data using an node.js script that you can run on the server: https://wavesurfer-js.org/faq/

**Comment by NavjotKumar** [comment]
i have tried creating peaks with 
`wavesurfer.exportPCM(1024, 10000, true, 0);`
and storing in on server, i got some array of data but when i a trying to load this generated peaks array with 
`wavesurfer.load( this.song, peakData);`

it does not create peaks, it shows data something like this
![bar](https://user-images.githubusercontent.com/33478668/62515481-0acaee80-b840-11e9-8380-db1a1f4a1bcc.png)

**Comment by aburai** [comment]
seems the peaks are not normalized, have you set this option in Wavesurfer.create to true?

**Comment by NavjotKumar** [comment]
Every thing is working fine now except, event after 
`waveform.play()` 
wave take around 3 - 10 sec to play in all cases, and if peaks are already drawn  why is playing it takes so much time and is there any way to reduce this time to zero??

**Comment by aburai** [comment]
on waveform.play() the audio is loaded and the peaks redraw
i use waveform.loadMediaElement() on play, if not already loaded, to minimize this redraw
