### ISSUE TITLE
How to call onDrag & onResize function in wavesurefer regions ?

### ISSUE THREAD

**Issue by Ramya-22** [katspaugh/wavesurfer.js#1713]
Hi all

I need regions `start and end `value for **region resize**.

How to call onDrag & onResize function in wavesurefer regions ?

REF : https://github.com/katspaugh/wavesurfer.js/issues/1555

![2019-08-01_17-13-03](https://user-images.githubusercontent.com/42537872/62290953-389ae680-b480-11e9-8bfa-da02defe2592.png)

cc - @katspaugh @MaxwellGover

**Comment by thijstriemstra** [comment]
`wavesurfer.regions.onDrag()`?

**Comment by Ramya-22** [comment]
Hi @thijstriemstra 

https://github.com/katspaugh/wavesurfer.js/issues/1713#issuecomment-517455639

Thanks for your time.I have tried.I got this error 

![2019-08-02_9-21-01](https://user-images.githubusercontent.com/42537872/62345027-2f585b00-b50e-11e9-915a-8bc95d1d58d1.png)

**Comment by aburai** [comment]
The method onDrag is located on the Region class and works as wrapper for the update method with the changed start and end for drag events. Same for onResize.

Listen to `region-updated`as mentioned and look for changes in start and end props.

**Comment by aburai** [comment]
second thought: we can add a property to Region like `isDragging` which will be set to true in onDown and to false on onUp. This way a region-updated listener could detect changes while dragging. Same for Resize. I have created a PR, but from wrong master, closed again. So now from upstream master ;) -> https://github.com/katspaugh/wavesurfer.js/pull/1716
