### ISSUE TITLE
Create copy of canvas and set player in footer

### ISSUE THREAD

**Issue by Sapnakarmur** [katspaugh/wavesurfer.js#1718]
I am creating a player like SoundCloud 

How can I make a global player at the bottom of the page (doesn't need to show waveform), like Soundcloud, playing at the same time while the track is playing on the page?

In detail,
It should work as when navigating to another page, the track shows the waveform continuing to play from the current time it's at as well as the global player controls showing the progress bar playing at the same time as the progress bar on the track's page does.

I have referred below links but I am not able to get the answer from the links
https://github.com/katspaugh/wavesurfer.js/issues/519
https://github.com/katspaugh/wavesurfer.js/issues/1496

As in the above link, you told to create cloneNode of the original canvas. cloneNode but it's not showing waveform.

It would be great if you can provide a demo for this

Thank you in advance

**Comment by thijstriemstra** [comment]
maybe  use `wavesurfer.exportImage()`?

**Comment by thijstriemstra** [comment]
no feedback, closing.
