### ISSUE TITLE
Create from existing WaveSurfer instance

### ISSUE THREAD

**Issue by arshaplus** [katspaugh/wavesurfer.js#1719]
Hi all.

I'm using this package on `Angular2+`. In my project, there are many tracks & each track have it's seperate page and wavesurfer object. like soundcloud. I have a `PlayerService` that save current `WaveSurfer object` & `Track object` when a track starts to play.

```
export class PlayerService {
    public wavesurfer: WaveSurfer = null;
    public track: Track = null;
}
```

```
export class TrackComponent implements OnInit {

  private wavesurfer: WaveSurfer;
  private track: Track;

  constructor(private playerService: PlayerService) {}

  onInit(){
      requestAnimationFrame(() => {

        this.wavesurfer = WaveSurfer.create({
          container: '#track-' + this.track.id,
          waveColor: 'violet',
          progressColor: 'purple',
       });
       this.wavesurfer.load(this.track.url);
    });
 }
  
 onPlay(){
      this.playerService.wavesurfer = this.wavesurfer;
      this.playerService.wavesurfer.playPause();
      this.playerService.track = this.track;
 }
}
```

When a track is playing & user navigate to other page, player keep playing. Now when the user come back to current track page again, Wavesurfer create new object & dont create from current player data on PlayerService (Progress bar & play state) !...

I want to when the track is playing, it's wavesurfer object create from current object in PlayerService & progress bar continue from current time. Like soundcloud player & page navigates.

something like this in onInit method : 
```
if( this.track.id == this.playerService.track.id ){
    this.wavesurfer = this.playerService.wavesurfer
}
```

Instead of:
`this.wavesurfer = WaveSurfer.create(...)`

Do you have any idea??

**Comment by thijstriemstra** [comment]
this sounds like a angular2/stackoverflow question, please ask there.
