### ISSUE TITLE
How to use getCurrentRegion function ?

### ISSUE THREAD

**Issue by Ramya-22** [katspaugh/wavesurfer.js#1721]
Hi all

I need currentRegion. and I update the region with given ( start and end value).

How to call getCurrentRegion  function in wavesurfer regions ?

cc - @katspaugh @MaxwellGover

**Comment by thijstriemstra** [comment]
try:
```javascript
 wavesurfer.regions.getCurrentRegion();
```

**Comment by Ramya-22** [comment]
Hi @thijstriemstra ,

 I tried this.https://github.com/katspaugh/wavesurfer.js/issues/1721#issuecomment-522349372

But it returns the value only when the region is  an active state (ie) my current time is in the region. 

```
    $scope.getCurrentRegionClick = function() {
        console.log( wavesurfer.regions.getCurrentRegion())
    };
```


![2019-08-26_14-56-12](https://user-images.githubusercontent.com/42537872/63680857-2d826e80-c812-11e9-84d7-c14a7f9217ce.png)
![2019-08-26_14-58-43](https://user-images.githubusercontent.com/42537872/63680858-2d826e80-c812-11e9-86bb-314aad3c6a67.png)








cc - @katspaugh @MaxwellGover

**Comment by aburai** [comment]
what is "currentRegion" for you?
if you need some focus handling when click on a region, you can easy implement that yourself

**Comment by Ramya-22** [comment]
Hi @aburai ,

Without clicking the current region I need region value. is it possible to get...?

**Comment by aburai** [comment]
you don't answer the question what the current region is
but you have all existing regions in a list
you can always find out what is the current time and find the region you want

**Comment by cargilcm** [comment]
> Would the technique of looking at the time to determine the current region be foolproof? Current regions should be verifiable by id since two regions can have the same start and end time, if I understand?!
