### ISSUE TITLE
exportImage() returns no data (empty base64)

### ISSUE THREAD

**Issue by Ramya-22** [katspaugh/wavesurfer.js#1727]
Hi @katspaugh 

From the new version-3.0.0 I faced the problem, which is wave surfer, `ready` returns empty base64 when am using export image function.  

I debugged your js,  you called the fireEvent `ready` after draw buffer() function,  Once the ready event triggers then only the draw buffer draws. But in version 1.2.3 this problem is not occurring, I submit my code here. if any mistake means kindly knows a solution.  Thanks in advance. 

```
 var wavesurfer = WaveSurfer.create({
        container: '#waveform',
        waveColor: '#D2EDD4',
        progressColor: '#46B54D',
        barHeight: 1.4 
    });
    
    wavesurfer.on('ready', function () {
      console.log(wavesurfer.exportImage())
    });
    
    wavesurfer.load('https://ia800508.us.archive.org/15/items/LoveThemeFromTheGodfather/02LoveThemeFromTheGodfather.mp3');
```

cc: @thijstriemstra

**Comment by aburai** [comment]
@Ramya-22 i have tested your code snippet and it works for me
did you see the waveform of the audio when you get the empty result?
maybe you can test it again in a clean environment and if you have only this code, make sure the document is ready (window.onload)

**Comment by Ramya-22** [comment]
Hi @aburai ,

Thanks for your time.

I am using wavesurfer version 3.0.0 .

REF :    `<script src="https://unpkg.com/wavesurfer.js"></script>`

So, I got empty base64 .


Which version you are using ...?

**Comment by aburai** [comment]
i use v3 too
have you tried to put your code in the window.onload event handler?

**Comment by thijstriemstra** [comment]
ping @Ramya-22

**Comment by thijstriemstra** [comment]
no feedback, closing.

**Comment by Ramya-22** [comment]
Hi @aburai 

https://github.com/katspaugh/wavesurfer.js/issues/1727#issuecomment-526582445

this idea also fails.


cc - @thijstriemstra @katspaugh

**Comment by arsh-sw** [comment]
For me it works if I run it after a timeout. 

 ```
setTimeout(function () {
               var imgSrc = wavesurfer.exportImage();
 }, 800);
```
