### ISSUE TITLE
exportPCM has timing issue

### ISSUE THREAD

**Issue by pmgrace** [katspaugh/wavesurfer.js#1728]
Hi @katspaugh 

In the latest version 3.0.0 does the "exportPCM" function work?

    wavesurfer.on('ready', function() {
        var pcmData = wavesurfer.exportPCM(1024, 1024, true);
        console.log("PCM: "+pcmData);
    });

All that shows in the console is:

    PCM: []

**Comment by thijstriemstra** [comment]
what does `wavesurfer.exportPCM()` return?

**Comment by pmgrace** [comment]
Using just `wavesurfer.exportPCM()` on v3.0.0, v2.2.1 and v2.2.0 just opens a blank new tab and the console still shows `PCM: []`.

**Comment by thijstriemstra** [comment]
can you check the various variables and values in https://github.com/katspaugh/wavesurfer.js/blob/master/src/wavesurfer.js#L1494 and try to figure out what's going wrong there?

**Comment by pmgrace** [comment]
I've been trying various values as well as `wavesurfer.backend.getPeaks()` but nothing is working for and I've got back to v2.0.5 and still not working. Is there someone that can help with this, we're willing to pay for any one to help get this working for us and to help get our player working much faster.

**Comment by aburai** [comment]
@pmgrace 
it is a timing issue, i can reproduce this with the zoom example, when i use
```
    wavesurfer.on('ready', function() {
        setTimeout(() => {
            const pcm = wavesurfer.exportPCM(1024, 1024, true);
            console.log('pcm', pcm);
        }, 1000);
    });
```
i get the pcm data returned

i will try to find a fix, maybe this can help as a hotfix

**Comment by aburai** [comment]
@pmgrace do you use `backend: 'MediaElement'` then try `wavesurfer.on('waveform-ready', () => {})`

**Comment by pmgrace** [comment]
> @pmgrace
> it is a timing issue, i can reproduce this with the zoom example, when i use
> 
> ```
>     wavesurfer.on('ready', function() {
>         setTimeout(() => {
>             const pcm = wavesurfer.exportPCM(1024, 1024, true);
>             console.log('pcm', pcm);
>         }, 1000);
>     });
> ```
> 
> i get the pcm data returned
> 
> i will try to find a fix, maybe this can help as a hotfix

I will try this out.



> @pmgrace do you use `backend: 'MediaElement'` then try `wavesurfer.on('waveform-ready', () => {})`

Yes I do use MediaElement, will also try this out.

**Comment by pmgrace** [comment]
> @pmgrace do you use `backend: 'MediaElement'` then try `wavesurfer.on('waveform-ready', () => {})`

Tested this one first and I now get the pcm data! Finally I can start working on the next part of doing something with this and loading tracks quicker :)

THANK YOU @aburai :)

**Comment by thijstriemstra** [comment]
> it is a timing issue, i can reproduce this with the zoom example, when i use

Instead of closing this issue, is there something we can do here to improve the situation?

**Comment by aburai** [comment]
maybe something for the FAQ section

**Comment by thijstriemstra** [comment]
> maybe something for the FAQ section

can we not fix the timing issue? maybe make it async
