### ISSUE TITLE
Load only waveform and wait for user to press play to download audio

### ISSUE THREAD

**Issue by diegoiglesias** [katspaugh/wavesurfer.js#1732]
I followed the instructions from here https://stackoverflow.com/a/39009549/972813 to load the waveform and wait for the user click to load audio. It works well but it redraws the waveform whilst is loading.

Can I just load and play without redrawing waveform?

**Comment by thijstriemstra** [comment]
@diegoiglesias can you make a codepen that reproduces the problem?

**Comment by aburai** [comment]
try
```
wavesurfer.loadMediaElement(wavesurfer.song, wavesurfer.backend.peaks, true, wavesurfer.getDuration());
```

**Comment by diegoiglesias** [comment]
> try
> 
> ```
> wavesurfer.loadMediaElement(wavesurfer.song, wavesurfer.backend.peaks, true, wavesurfer.getDuration());
> ```

Yes! it worked perfectly!

**Comment by veffev** [comment]
@diegoiglesias could you share your code please ? I have the same problem

**Comment by psavva** [comment]
Do you have any advice to generate the Peaks using c#, and then loading these into wavesurfer?
