### ISSUE TITLE
replace soundwave with spectrogram 

### ISSUE THREAD

**Issue by Athospd** [katspaugh/wavesurfer.js#1734]
Is it possible to make spectrogram the main plot instead of wave? It would be a nice feature, specially for annotation purpose.

**Comment by thijstriemstra** [comment]
@Athospd you can hide the `canvas` element, check `wavesurfer.drawer.canvases`.

**Comment by Athospd** [comment]
But in this case I wouldn't have the same functionalities like regional, cursor, etc, right?

**Comment by thijstriemstra** [comment]
@Athospd have you tried first? regions are drawn in separate canvas elements.

**Comment by Athospd** [comment]
@thijstriemstra Sorry thistriemstra. I don't know even where to start trying. I was expecting something like "visualization_type: 'spectrogram'".

But I'm affraid I'll have to dig int JavaScript tweaks.

Thank you for your time.

**Comment by thijstriemstra** [comment]
>  I don't know even where to start trying.

After you created the player, try this to hide the waveform (but not the spectrogram):

```javascript
wavesurfer.on('ready', function() {
    wavesurfer.drawer.canvases[0].wave.style.display = 'none';
});
```
