### ISSUE TITLE
Regions Plugin - how to render the waveform regions only?

### ISSUE THREAD

**Issue by lionel-lints** [katspaugh/wavesurfer.js#1735]
Wavesurfer.js version(s):
3.0.0

Browser and operating system version(s):
Chrome version 76
Mac 10.14.6

I'm sorry I don't have code to reproduce this issue, but I am trying to display the waveform where regions have been selected and collapse the rest of the waveform. I dug into this, and it seems like there is no clear CSS way to approach this as the regions don't render the waveform directly, and all CSS related visibility and or display methods affect the whole element. Does anyone know of any way to implement this? My goal is to have a function that can toggle the whole waveform and only the selected regions.

Thanks for any thoughts and/or ideas!

**Comment by thijstriemstra** [comment]
the waveform is rendered on a canvas element, you can modify that: wavesurfer.drawer.canvases array.

**Comment by lionel-lints** [comment]
OK I will check it out, thanks for the pointer.
