### ISSUE TITLE
How can I create an AudioContext AFTER loading the waveform?

### ISSUE THREAD

**Issue by shamoons** [katspaugh/wavesurfer.js#1736]
I have:
```
 this.wavesurfer = WaveSurfer.create({
        container: "#wavesurfer-player",
        height: 60,
        barWidth: 2,
        barHeight: 1, // the height of the wave
        barGap: null,
        scrollParent: false
      });
      this.wavesurfer.load(this.url);
      this.wavesurfer.on(
        "loading",
        progress => (this.loadingProgress = progress)
      );
      this.wavesurfer.on("ready", () => {
        let progressBarContainer = document.querySelector(
          ".progress-bar-container"
        );
        progressBarContainer.classList.add("animated", "fadeOut");
        this.loadingProgress = 100;
        this.wavesurfer.un("ready");
        progressBarContainer.addEventListener("animationend", () => {
          this.hideProgressBar = true;
        });
      });

      this.wavesurfer.on("audioprocess", this.audioprocess);
```

On `iOS safari`, this won't play. Apparently, I need to create an AudioContext AFTER a user action. So I can add a button with a `click` event to trigger this. But I want the waveform to show on load. 

If anyone wants to collect imaginary internet points, they can answer [here as well](https://stackoverflow.com/questions/57677569/with-wavesurfer-js-how-can-i-create-an-audiocontext-after-loading-the-waveform).

**Comment by thijstriemstra** [comment]
@shamoons you should create a new `AudioContext` when a user clicks an element, e.g. button, and then pass that audiocontext into the wavesurfer configuration, using the `audioContext` option.

**Comment by shamoons** [comment]
But I want the WaveForm to show immediately. So I want to load the wavesurfer on load. I want the play to be on click

**Comment by thijstriemstra** [comment]
@shamoons that's not possible on iOS. Blame Apple. You could use peaks data to draw the waveform though: https://wavesurfer-js.org/faq/

**Comment by entonbiba** [comment]
@shamoons a pr #2176 is on the way that fixes this, for now here is a sample workaround:
https://www.entonbiba.com/lab/ios2.html
