### ISSUE TITLE
I am getting a gap between the cursor and my mouse position in waveform.how to coincide both postion.

### ISSUE THREAD

**Issue by gocubetech** [katspaugh/wavesurfer.js#1750]

**Comment by thijstriemstra** [comment]
can you add a screenshot? what does the wavesurfer.js config look like?

**Comment by gocubetech** [comment]
![cursor gap](https://user-images.githubusercontent.com/46589776/65743222-4e8bf700-e111-11e9-9610-bc0301b63973.png)

There is a gap between cursor and mouse cursor .

**Comment by thijstriemstra** [comment]
try changing the `cursorWidth` and `responsive` options.

**Comment by gocubetech** [comment]
I have changed the cursorwidth,its only increasing the progress cursor width but not reducing the gap between two.Making Responsive true also has not affected the gap

**Comment by aburai** [comment]
i can not reproduce this, maybe you can create code to test
 [A Code pen](http://codepen.io/)  or test github repository

**Comment by kavishatalsania** [comment]
I've also faced this issue. I am able to solve it with some CSS changes. Try to give position: relative; CSS to your wavesurfer container and remove margins.

**Comment by aburai** [comment]
i think we should add this to the FAQ, position: relative is very important for wavesurfer to work

**Comment by ITachiLab** [comment]
Setting `position: relative;` on the WaveSurfer container element also helped me with the identical issue.

**Comment by thijstriemstra** [comment]
does this also happen with the cursor example on the site? if so it should be added there as well.

**Comment by ITachiLab** [comment]
From what I see, the WaveSurfer's container on the "Cursor example" page has this CSS property already set. If it's removed, the cursor doesn't work properly.

**Comment by thijstriemstra** [comment]
found a fix, closing the ticket.

**Comment by yinruiqing** [comment]
I also met the same problem. You can reproduce it in [audio-annotation](https://github.com/yinruiqing/audio-annotation). By the way, does anyone interested in this project? It aims to display speaker recognition and speech recognition results.  Users could modify and export the interested part.
