### ISSUE TITLE
Force rendering of minimap

### ISSUE THREAD

**Issue by Fiorello** [katspaugh/wavesurfer.js#1754]
### Wavesurfer.js version(s):
2.2.0

### Browser and operating system version(s):
Chrome on macos Mojave

Hi,
i need to change barHeight dynamically, but when i do it the minimap doesn't render again.
This is my code:

```
  protected setBarHeight() {
    const { preAmp } = this.props;
    this.wavesurfer.params.barHeight = preAmp || 1;
    this.wavesurfer.drawBuffer();
    this.wavesurfer.minimap && this.wavesurfer.minimap.render();
  }
```
Even if I'm calling the minimap render method, nothing happens.
How can i force render of minimap?

**Comment by aburai** [comment]
@Fiorello minimap has it own params, set barHeight there too
`this.wavesurfer.minimap.params.barWidth = preAmp || 1`

**Comment by Fiorello** [comment]
> @Fiorello minimap has it own params, set barHeight there too
> `this.wavesurfer.minimap.params.barWidth = preAmp || 1`

It works, thank you @aburai
