### ISSUE TITLE
Unable to load audio from video tag

### ISSUE THREAD

**Issue by qbunt** [katspaugh/wavesurfer.js#1758]
# Hey, thank you for testing and contributing to wavesurfer.js!

## Please make sure you can check all of these points below before opening an issue:

(You don't have to post this section)

- [X] I have checked [the FAQ](https://wavesurfer-js.org/faq/) and it doesn't solve my problem.
- [X] I have checked [the documentation](https://wavesurfer-js.org/docs/) and it doesn't solve my problem
- [X] I have searched for [already open issues](https://github.com/katspaugh/wavesurfer.js/issues) which desribe my problem.
- [X] The issue I'm having is related to and caused by wavesurfer.js, not by other software (which maybe packages and uses wavesurfer incorrectly) – In that case you should open the issue on the respective project pages.

### Wavesurfer.js version(s):
* 3.0.0
* 3.1.0

### Browser and operating system version(s):
Chrome 77.0.3865.90
macOS Mojave 10.14.6

### Code needed to reproduce the issue:

https://codepen.io/qbunt/pen/GRKVBrd
```
let wavesurfer = WaveSurfer.create({
          container: document.querySelector('#waveform'),
          waveColor: '#A8DBA8',
          progressColor: '#3B8686',
          backend: 'MediaElement'
})
let video = document.querySelector('video')
wavesurfer.load(video)
```

### Use behaviour needed to reproduce the issue:
I originally encountered this in Vue, but have since validated that it shows up in **all** contexts and is not related to Vue at all. When attempting to start WaveSurfer with a `MediaElement` backend, and load a video element as the audio source, [as shown in the docs](http://wavesurfer-js.org/example/video-element/index.html), I get the following error consistently in every framework, and back to 3.0.0:

```
Uncaught Error: fetch url missing
    at Object.t.default (fetch.js:118)
    at t.value (wavesurfer.js:1448)
    at t.value (wavesurfer.js:1398)
    at t.value (wavesurfer.js:1322)
    at pen.js:11
```
Either this is something incorrect in the documentation, or something in Chrome changed and the URL isn't landing in the `fetch` call due to an incorrect reference or similar.

Of course, if this is something obvious that I'm doing wrong, I'd be happy to update the docs if that is the issue. Thanks so much, great lib!

**Comment by aburai** [comment]
i don't see that the code from the docs work, the first parameter from load will be used as source
the url that is created is `https://cdpn.io/boomboom/v2/[object%20HTMLVideoElement]`

try `wavesurfer.loadElt(mediaEl)`

**Comment by qbunt** [comment]
I just see:
```
pen.js:10 Uncaught TypeError: wavesurfer.loadElt is not a function
    at pen.js:10
```
Am I missing something?

**Comment by qbunt** [comment]
@aburai for what it's worth, everything I've tried with audio feedback in the current version of chrome outputs this:
```webaudio.js:76 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu```
Possible there was a change in policy that is preventing playback.

**Comment by qbunt** [comment]
I have `<source>` as an extra element underneath video as the spec allows for. If I adhere to this to allow for multiple sources, then I get the above failure. If the `src` attribute is attached to the `<video>` tag itself, it does work correctly after the audio context is defined.

**Comment by aburai** [comment]
sorry it is `wavesurfer.backend.loadElt`
and you must use the promise from play to handle os restrictions
see https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/play

when media has src everythings works well
the above problem was because you uses the video element and the load method
sets the element to src which could not work
`loadElt` skips this part and directly use the media element

**Comment by aburai** [comment]
i look deeper in the code and in the example, `loadElt` does not what you want
your play directs to `loadMediaElement` and this method already check if the argument
is a string (url) or a media element and uses `backend.loadElt)` 

i think we must add support for source tags there

**Comment by qbunt** [comment]
@aburai Do you know off-hand if the spectrogram plugin will load video as an audio element properly? I have the waveform working, the spectrogram plugin is throwing an error because it would appear that the backend (of `MediaElement` type`) does not have a buffer attached to the instance.

```
wavesurfer.spectrogram.js?e59a:609 Uncaught TypeError: Cannot read property 'getChannelData' of null
    at SpectrogramPlugin.getFrequencies (wavesurfer.spectrogram.js?e59a:609)
    at SpectrogramPlugin.render (wavesurfer.spectrogram.js?e59a:574)
    at t.SpectrogramPlugin._onReady (wavesurfer.spectrogram.js?e59a:470)
    at n (wavesurfer.min.js?b9b7:6)
    at eval (wavesurfer.min.js?b9b7:6)
    at Array.forEach (<anonymous>)
    at t.value (wavesurfer.min.js?b9b7:6)
    at t.eval (wavesurfer.min.js?b9b7:6)
    at n (wavesurfer.min.js?b9b7:6)
    at eval (wavesurfer.min.js?b9b7:6)
```

Which leads to:
```
value: function getFrequencies(callback) {
      var fftSamples = this.fftSamples;
      var buffer = this.buffer = this.wavesurfer.backend.buffer;
      var channelOne = buffer.getChannelData(0);
      var bufferLength = buffer.length;
      var sampleRate = buffer.sampleRate;
      var frequencies = [];
```

After setting some breakpoints, it looks like `buffer`, `this.buffer` and `this.wavesurfer.backend.buffer` are all null.

**Comment by aburai** [comment]
sorry no, i'd have to take a closer look.

**Comment by davegravy** [comment]
> @aburai Do you know off-hand if the spectrogram plugin will load video as an audio element properly? I have the waveform working, the spectrogram plugin is throwing an error because it would appear that the backend (of `MediaElement` type`) does not have a buffer attached to the instance.
> 
> ```
> wavesurfer.spectrogram.js?e59a:609 Uncaught TypeError: Cannot read property 'getChannelData' of null
>     at SpectrogramPlugin.getFrequencies (wavesurfer.spectrogram.js?e59a:609)
>     at SpectrogramPlugin.render (wavesurfer.spectrogram.js?e59a:574)
>     at t.SpectrogramPlugin._onReady (wavesurfer.spectrogram.js?e59a:470)
>     at n (wavesurfer.min.js?b9b7:6)
>     at eval (wavesurfer.min.js?b9b7:6)
>     at Array.forEach (<anonymous>)
>     at t.value (wavesurfer.min.js?b9b7:6)
>     at t.eval (wavesurfer.min.js?b9b7:6)
>     at n (wavesurfer.min.js?b9b7:6)
>     at eval (wavesurfer.min.js?b9b7:6)
> ```
> 
> Which leads to:
> 
> ```
> value: function getFrequencies(callback) {
>       var fftSamples = this.fftSamples;
>       var buffer = this.buffer = this.wavesurfer.backend.buffer;
>       var channelOne = buffer.getChannelData(0);
>       var bufferLength = buffer.length;
>       var sampleRate = buffer.sampleRate;
>       var frequencies = [];
> ```
> 
> After setting some breakpoints, it looks like `buffer`, `this.buffer` and `this.wavesurfer.backend.buffer` are all null.

I ran into this same issue

**Comment by ZhouYing-bit** [comment]
I have the same problem

**Comment by Kerinlin** [comment]
> @aburai Do you know off-hand if the spectrogram plugin will load video as an audio element properly? I have the waveform working, the spectrogram plugin is throwing an error because it would appear that the backend (of `MediaElement` type`) does not have a buffer attached to the instance.
> 
> ```
> wavesurfer.spectrogram.js?e59a:609 Uncaught TypeError: Cannot read property 'getChannelData' of null
>     at SpectrogramPlugin.getFrequencies (wavesurfer.spectrogram.js?e59a:609)
>     at SpectrogramPlugin.render (wavesurfer.spectrogram.js?e59a:574)
>     at t.SpectrogramPlugin._onReady (wavesurfer.spectrogram.js?e59a:470)
>     at n (wavesurfer.min.js?b9b7:6)
>     at eval (wavesurfer.min.js?b9b7:6)
>     at Array.forEach (<anonymous>)
>     at t.value (wavesurfer.min.js?b9b7:6)
>     at t.eval (wavesurfer.min.js?b9b7:6)
>     at n (wavesurfer.min.js?b9b7:6)
>     at eval (wavesurfer.min.js?b9b7:6)
> ```
> 
> Which leads to:
> 
> ```
> value: function getFrequencies(callback) {
>       var fftSamples = this.fftSamples;
>       var buffer = this.buffer = this.wavesurfer.backend.buffer;
>       var channelOne = buffer.getChannelData(0);
>       var bufferLength = buffer.length;
>       var sampleRate = buffer.sampleRate;
>       var frequencies = [];
> ```
> 
> After setting some breakpoints, it looks like `buffer`, `this.buffer` and `this.wavesurfer.backend.buffer` are all null.

Do you know how to solve this problem?

**Comment by mayurshinde4590** [comment]
i am getting bellow error can anyone help me in this
vendor.js:61172 ERROR TypeError: Cannot read property 'getChannelData' of null
    at e.value (:4201/default~marineMotors-admin-admin-module~marineMotors-user-user-module.js:174)
    at e.value (:4201/default~marineMotors-admin-admin-module~marineMotors-user-user-module.js:174)
    at WaveSurfer._onReady (:4201/default~marineMotors-admin-admin-module~marineMotors-user-user-module.js:174)
    at fn (:4201/default~marineMotors-admin-admin-module~marineMotors-user-user-module.js:3333)
    at :4201/default~marineMotors-admin-admin-module~marineMotors-user-user-module.js:3389
    at Array.forEach (<anonymous>)
    at WaveSurfer.fireEvent (:4201/default~marineMotors-admin-admin-module~marineMotors-user-user-module.js:3388)
    at MediaElement.<anonymous> (:4201/default~marineMotors-admin-admin-module~marineMotors-user-user-module.js:5164)
    at fn (:4201/default~marineMotors-admin-admin-module~marineMotors-user-user-module.js:3333)
    at :4201/default~marineMotors-admin-admin-module~marineMotors-user-user-module.js:3389
defaultErrorLogger @ vendor.js:61172
DevTools failed to load SourceMap: Could not load content for chrome-extension://fheoggkfdfchfphceeifdbepaooicaho/sourceMap/chrome/content.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

**Comment by jamesfiltness** [comment]
I have the same issue. Are there any plans to support the <source> element?

**Comment by purva15** [comment]
@qbunt @aburai What can I do for this?
let wavesurfer = WaveSurfer.create({
          container: document.querySelector('#waveform'),
          waveColor: '#A8DBA8',
          progressColor: '#3B8686',
          backend: 'MediaElement'
})
let video = document.querySelector('video')
wavesurfer.load(video)

When attempting to start WaveSurfer with a MediaElement backend, and load a video element as the audio source, [as shown in the docs](http://wavesurfer-js.org/example/video-element/index.html), I get the following error consistently in every framework:

Uncaught Error: fetch url missing
    at Object.t.default (fetch.js:118)
    at t.value (wavesurfer.js:1448)
    at t.value (wavesurfer.js:1398)
    at t.value (wavesurfer.js:1322)
    at pen.js:11

**Comment by qbunt** [comment]
@aburai Any chance you can speak to adding support for https://github.com/katspaugh/wavesurfer.js/issues/1758#issuecomment-537641665 as you mentioned? This has been open for a couple years now, maybe this is not worth leaving open?
