### ISSUE TITLE
Super expression must either be null or a function while loading wavesurfer

### ISSUE THREAD

**Issue by kavishatalsania** [katspaugh/wavesurfer.js#1759]
After upgrading to latest version 3.1.0 of wavesurfer. below error is coming while loading wavesurfer.js file. 

```
 ERROR Error: Uncaught (in promise): TypeError: Super expression must either be null or a function (core.js.pre-build-optimizer.js:1449)
TypeError: Super expression must either be null or a function
```
It was working correctly for older version 3.0.0

**Comment by hrkazemi** [comment]
> After upgrading to latest version 3.1.0 of wavesurfer. below error is coming while loading wavesurfer.js file.
> 
> ERROR Error: Uncaught (in promise): TypeError: Super expression must either be null or a function (core.js.pre-build-optimizer.js:1449)
> TypeError: Super expression must either be null or a function
> 
> It was working correctly for older version 3.0.0

I had the same problem, 
use 
const WaveSurfer = require('wavesurfer.js/dist/wavesurfer');
instead of 
import WaveSurfer from 'wavesurfer.js';
and make sure load from "dist" folder not "src".
hope it help.

**Comment by thijstriemstra** [comment]
@kavishatalsania can you add some example code that reproduces the problem?

**Comment by rhaamo** [comment]
@thijstriemstra I'm running into that same error too, but surprisingly it seems to only appears when I run the unit tests, build and serve run fine.

And the traceback doesn't seems very much helpful https://circleci.com/gh/reel2bits/reel2bits/5064

the units fails either under node LTS or 12.x, wavesurfer 3.0.0 wasn't producing any error

**Comment by kavishatalsania** [comment]
@thijstriemstra I've just imported the wavesurfer and created the instance of it.

import WaveSurfer from 'wavesurfer.js';

wavesurfer = WaveSurfer.create({
    container: '#waveform',
    waveColor: 'violet',
    progressColor: 'purple'
});

I am using wavesurfer in my angular project. When I serve my application in local, it works fine. But when I create build and deployed it on server then it is giving an error for 'Super expression must either be null or a function'.

**Comment by hrkazemi** [comment]
@kavishatalsania did you try 
const WaveSurfer = require('wavesurfer.js/dist/wavesurfer');
instead of
import WaveSurfer from 'wavesurfer.js';

**Comment by aburai** [comment]
`const WaveSurfer = require('wavesurfer.js/dist/wavesurfer')` solves the problem for me

**Comment by rhaamo** [comment]
but isn't `require()` going to sort of bypass webpack magic vs `import` ? Which could explain why it works with require and not import.

**Comment by thijstriemstra** [comment]
> I think the problem occurs when "webpack" tries to uglify this library.

can you try building the latest master branch @kavishatalsania and @hrkazemi and see if that fixes it? it's probably related to webpack-terser-plugin (which released a new version) I think.

**Comment by hrkazemi** [comment]
@thijstriemstra, I did installed wavesurfer.js latest version; the problem still exists.

**Comment by thijstriemstra** [comment]
you mean checkout the master branch and build library from source?

**Comment by hrkazemi** [comment]
no, I just removed wavesurfer.js from node_module and installed it with "npm i wavesurfer.js@latest".

**Comment by thijstriemstra** [comment]
try checkout, build from source and copy resulting `dist` folder into `node_modules/wavesurfer.js`

**Comment by aburai** [comment]
maybe we must change `main` definition in package.json and do not use the minified version
i have no time currently to test it

**Comment by thijstriemstra** [comment]
sounds good @aburai. see https://docs.npmjs.com/files/package.json#main
