### ISSUE TITLE
Loading pre-rendered peaks display issue?

### ISSUE THREAD

**Issue by pmgrace** [katspaugh/wavesurfer.js#1768]
Help please, what causes this to happen with pre-rendered peaks?

![image](https://user-images.githubusercontent.com/2545456/66327585-f9c35a00-e922-11e9-90f5-72ae2995bcc6.png)

**Comment by aburai** [comment]
data is not normalized, use the wavesurfer option or make sure the peaks are between -1 and 1

**Comment by pmgrace** [comment]
@aburai Setting `normalize: true` results in no waveform shown at all when loaded with peaks. Confirmed, peaks are between -1 and 1.

I'm using the following command to create the peaks:
`var pcmData = '[' + wavesurfer.backend.getPeaks(500, 0, 500) + ']';`

**Comment by aburai** [comment]
ok, was my first guess
i don't know why you convert the peaks to string, but without more code i have no idea

**Comment by pmgrace** [comment]
@aburai Thank you - The issue was because it was being stored as a string and not an object, I hadn't realised this would have affected it. I was putting the peaks in to `pcmData` to then ajax them into a mySQL database to be stored with the specific track. When retrieving the peaks I just had to do `JSON.parse(pcm)` and it displayed correctly.

Would it be more efficient to store the peaks data in a .json file?

**Comment by aburai** [comment]
more efficient, maybe not, but it is my favorite way to store the peaks
i use audiowaveform on the server side to create the peaks and other audio metadata
