### ISSUE TITLE
pureDrive

### ISSUE THREAD

**Issue by calgarc** [katspaugh/wavesurfer.js#1770]
Hello, I am currently working on an opensource cloud storage platform and I am using wavesurfer.js for audio payback. you can see the project here at http://puredrive.org

I also wanted to note that wavesurfer takes forever to load and create the waveform. is there a way to set it up s it creates the form then buffers the audio?

**Comment by thijstriemstra** [comment]
@calgarc please add it to the list here: https://github.com/katspaugh/wavesurfer.js/edit/gh-pages/projects/index.html and submit it as a pull request.

**Comment by thijstriemstra** [comment]
no feedback, closing.
