### ISSUE TITLE
Unable to get property 'toLowerCase' of undefined or null reference in IE

### ISSUE THREAD

**Issue by Madhukanth** [katspaugh/wavesurfer.js#1771]
I tried to load wavesurfer in IE11 and I got this issue.However it is working fine in chrome.

My code is

```
<!DOCTYPE html>
<html>
  <head>
    <title>Test</title>
  </head>
  <body>
    <script src="https://unpkg.com/wavesurfer.js"></script>
    <script>
      setTimeout(function() {
        var wavesurfer = WaveSurfer.create({
          container: '#waveform',
          waveColor: 'violet',
          progressColor: 'purple',
          backend: 'MediaElement'
        });
        wavesurfer.load('test123.mp3');
      }, 5000);
    </script>
    <div id="waveform"></div>
  </body>
</html>

```
In IE11, I am getting this error.

May be I am missing something.

**Comment by thijstriemstra** [comment]
can you paste the complete error (or screenshot)?

**Comment by thijstriemstra** [comment]
Confirmed issue.

**Comment by Madhukanth** [comment]
![003865](https://user-images.githubusercontent.com/20109264/66654672-635fa300-ec58-11e9-8ae6-f72394fafeb5.jpg)

**Comment by Madhukanth** [comment]
Any fix on this issue??

**Comment by thijstriemstra** [comment]
did you pay anyone to fix it?

**Comment by Madhukanth** [comment]
I didnt get you

**Comment by Madhukanth** [comment]
Do someone need pay to fix it??

**Comment by thijstriemstra** [comment]
it's an opensource project, it's fixed when someone fixes it, unless you pay someone to fix it for you.

**Comment by Madhukanth** [comment]
I see...ok thanks

**Comment by thijstriemstra** [comment]
After fixing that error (and adding the polyfills):

```html
<!-- IE11 polyfills -->
<script src="https://cdn.jsdelivr.net/npm/promise-polyfill@8/dist/polyfill.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/fetch/2.0.4/fetch.js"></script>
```

there was still a vague error, not sure what's going on.
