### ISSUE TITLE
Unable to mute left/right channel in stereo audio file with backend 'MediaElement'

### ISSUE THREAD

**Issue by kavishatalsania** [katspaugh/wavesurfer.js#1777]
Hi,

I am not able to mute one channel with the 'MediaElement' backend. 

I am able to mute the channel with 'WebAudio' backend using the below code.

const splitter = wavesurfer.backend.ac.createChannelSplitter(2);
const merger = wavesurfer.backend.ac.createChannelMerger(2);
this.leftGain = wavesurfer.backend.ac.createGain();
this.rightGain = wavesurfer.backend.ac.createGain();
splitter.connect(this.leftGain, 0);
splitter.connect(this.rightGain, 1);
 this.leftGain.connect(merger, 0, 0);
this.rightGain.connect(merger, 0, 1);
wavesurfer.backend.setFilters([splitter, this.rightGain, merger]);

'WebAudio' is taking much time to ready as it loads whole audio. So I wanted to use 'MediaElement' instead of 'WebAudio'. I can not use .setFilter method with 'MediaElement'. hence it is not working.

Does anyone have a workaround for this?

**Comment by thijstriemstra** [comment]
@kavishatalsania you should try the new `MediaElementWebAudio` backend, see #1767

**Comment by kavishatalsania** [comment]
@thijstriemstra I've cloned master branch. But it does not contain the latest changes. Which branch has latest MediaElementWebAudio backend changes?

**Comment by thijstriemstra** [comment]
it's not in a project branch, it's still a PR, see https://github.com/marizuccara/wavesurfer.js master branch

**Comment by thijstriemstra** [comment]
if you have any feedback, leave comments in the pull request #1767

**Comment by thijstriemstra** [comment]
fixed with #1767
