### ISSUE TITLE
region.playLoop() and region.play() do not get the right start or end time

### ISSUE THREAD

**Issue by liujinliang01** [katspaugh/wavesurfer.js#1779]
Hi Everyone,

I must first thank katspaugh for creating and sharing wavesurfer.js, and other contributors.

I am having problem with the region plugin. When I drag to create a region, its start time is 0 (the beginning of the whole audio file) and the end time is end of the whole file, not the beginning and end of the region. 

I am testing an mp3 file that lasts 19 minutes on Win10, Firefox. 

I sometimes have to drag from right to left because the normal left-to-right drag cannot create a region.

The following is my code:

	wavesurfer.on('region-created', function (region) {
		/*the following will clear all other regions, 
		leaving only the most recently created one
		which is exactly what I want. I don't need more than one regions.
		*/
		wavesurfer.regions.clear();		
		id = region.id;
		alert(id) // upto now it is OK, meaning I can get the id of the recently created region
		
		/*but the following calls don't get the right results: 
		region.start returns 0, i.e. the begining of the whole file 
		rather than the beginning of the region 
		and region.end returns the end of the whole audio file, 
		which are are not right.*/
		
		alert(region.start) // this returns 0
		alert(region.end) // this returns time for the end of the whole audio file
		
		region.playLoop(); // so, this will play from the begining till the end of the whole file
		
		//region.play(); // this also will play from the begining till the end of the whole file
		
		//wavesurfer.play(region.start,region.end); //this doesn't work either.
	});

**Comment by thijstriemstra** [comment]
what version of wavesurfer? what operating system/browser etc

**Comment by liujinliang01** [comment]
Hello Thijs and Katspaugh,


What a pleasant surprise to receive your reply! I recognise you as the masterminds behind the wonderful wavesurfer.js. I am honoured and thank you very much.


Here are my settings:


1. I am using Win10 professional; Firefox 69.0.3, 32bit
2. Version of  wavesurfer is 3.1 which I downloaded from the unpkg.com link in the webpage shown below. 
 


I downloaded it on 20/10/2019, and renamed it "wavesurfer.min.js", which was the file name I was trying to use a few months ago. Back then, I could not get the region plugin to work as I expected either. I could not leave only one region on screen.
 
2. Version of region plugin: I cannot tell the version, but I downloaded the region.js file from here: https://github.com/katspaugh/wavesurfer.js/blob/master/src/plugin/regions.js, which was also downloaded on 20/10/2019.


But the region.js file threw an error when I included it in my html file, saying "TypeError: window.WaveSurfer.regions is undefined". So I kept an older version of “wavesurfer.regions.min.js” in my html script includes. The three wavesurfer.js related files are as follows:
By the way, I have another question: should I use wavesurfer.load() or window.wavesurfer.load(), etc. ? I was using the ones without the prefix of "window."; then I saw from your github page that some people use the window prefix, so I added it, but it does not seem to make a difference. 


I am an English trainer in Beijing, China and am I eager to make wavesurfer.js work for my students so that they can drag to create a region which will right away playLoop until Pause is pressed or another region is created. I will also try to make it possible for the students to click on webvtt lines which will playLoop until another line is clicked. All my audio files have orthographic transcripts. Using forced alignment tool, I have only succeeded in getting sentence-level timestamps, not word-level ones. I would like to have words hightlighted when they are being said.  If your cool wavesurfer.js could be made to work with webvtt / srt / lrc and could generate word-level timestamps, it would be even greater. But that would dreams for the future. Right now, I am stuck with the region playLoop() function, which is not starting from the beginning of the region, but from the beginning of the whole audio file.


I appreciate you help very much.


Looking forward to your reply.
best regards
Jim (my Chinese name is Jinliang, Liu)




At 2019-10-21 18:57:35, "Thijs Triemstra" <notifications@github.com> wrote:


what version of wavesurfer? what operating system/browser etc

**Comment by liujinliang01** [comment]
Thank you aburai very much for your great help.  
I followed you advice and I can get the right start and end time of a region now. 
But the shaded rectangular area of a region is not shown and loop does not work.  Instead, once a region is created by dragging, the playhead goes to the start place all right and plays till the end of the region alright, but it stops there without looping, and without showing the region. 

What I need is - when the user drags to create a region, other regions are cleared and only the one just created is shown, and the region is loop played endlessly until the user clicks Pause/Stop or creates another  region. If another region is created, the previous region will disappear and the region just created will loop endlessly etc.. Could you please help? Thank you again.

**Comment by liujinliang01** [comment]
Update on my above post:
I have downloaded and started using the regions.min.js file from https://unpkg.com/wavesurfer.js/dist/plugin/wavesurfer.regions.min.js
which is  wavesurfer.js regions plugin 3.2.0 (2019-10-25).
With this latest version, I have realized that now it is no longer the case that the wavesurfer.regions.clear() will keep the most recently created region. When I remove the  wavesurfer.regions.clear(), the regions are shown. not like what I mentioned in my post above (regions did not show). 

But I still cannot achieve what I need - when the user drags to create a region, other regions are cleared and only the one just created is shown, and the region is loop played endlessly until the user clicks Pause/Stop or creates another region. If another region is created, the previous region will disappear and the region just created will loop endlessly etc.. 

Now, when I create just one region, the region is shown and looped alright, but when I create another region, the previous region does not disappear and the playhead gets stuck at the beginning of the newly created region, and the Firefox browser freezes, which has to be relaunched.

Could you please help me achieve what I need? Thank you again.

**Comment by liujinliang01** [comment]
Hello André,


Thank you very much for your help with my region plugin problem. Your advice to listen on region-update-end 
instead of "region-created" worked. 


But I still cannot achieve what I need - when a user drags to create a region, other regions are cleared and only the one just created is shown, and the region is loop played endlessly until the user clicks Pause/Stop or until he creates another region. If another region is created, the previous region will disappear and the region just created will loop endlessly etc..


Now, when I create just one region, the region is shown and looped alright, but when I create another region, the previous region does not disappear and the playhead gets stuck at the beginning of the newly created region, and the Firefox browser freezes, which has to be relaunched.
I am using wavesurfer.min.js 3.2.0, and wavesurfer.regions.min.js which says that it is for 3.2.0.
I use Firefox 70.0 32bit on Win10 Prof.
best regards
Jim








在 2019-10-31 02:30:53，"André Bunse" <notifications@github.com> 写道：


to get the correct region.end you must listen to region-update-end

**Comment by aburai** [comment]
sounds like `regions.clear` does not work correct, can you provide a bit of your current code to reproduce the problem?

**Comment by liujinliang01** [comment]
Hi André,


Thank you very much for your kind response.
Could you please have a look at this codepen test snippet:
https://codepen.io/liujinliang01/pen/VwwxQmg
When I click Play,  nothing happens. I can see the error message "region is null" in the developer's console.
The above codepen test is forked from katspaugh's region test. I just made the following changes:
1. In the left HTML panel, updated the wavesurfer.js  and regions plugin to 3.2.0. 
2. In the right JS panel, deleted some addRegion() blocks, and assigned the addRegion() result to the var region, like this: var region = null; and then: region = wavesurfer.addRegion({options}).
3. added region.playLoop()


And then I get "region is null" error.


Thank you again for your help.
best regards
Jim 








At 2019-11-07 09:44:34, "André Bunse" <notifications@github.com> wrote:


sounds like regions.clear does not work correct, can you provide a bit of your current code to reproduce the problem?

**Comment by liujinliang01** [comment]
I am obliged to report that this problem of "region.play() or region.playLoop() not getting the right start / end time"  is solved.

My code is now like the following:
	wavesurfer = create_wavesurfer("#waveform");
	wavesurfer.load(file_name);
	wavesurfer.on('ready', function () {
		wavesurfer.play();
		//wavesurfer.regions.clearRegions();
		wavesurfer.regions.enableDragSelection({loop:true});	
	});
				
	wavesurfer.on('region-click', function (region) {
		wavesurfer.clearRegions();
	});
	
	wavesurfer.on('region-update-end', function (region) {
		region.loop = true;
		region.play();
	});

I don't know why it started working when I tried the above code yesterday. I tried many variations including the above snippet before with no luck. But now it works. 

Thanks to all those who helped me!

My current environment is: Win10 prof. / Firefox 70.0.1 32bit/ wavesurfer.js 3.2 / region plugin for 3.2

**Comment by liujinliang01** [comment]
Hi Andre,


I feel obliged to report the good news that now the region plugin mostly satisfies my needs.


I need three functions:


1. When a region is created, all other regions will be cleared, leaving only the most recent region. - This I still cannot achieve yet. As of now, the user has to click to clear a region before creating a new one. In this case, not only does the user have to do an extra click but also there seems to be bug - when a second region is created, the player gets stuck and if no action is taken quickly, Firefox will freeze and has to be relaunched. The action to take is to quickly click on one of the regions to clear it and then the player will start playing the other region and the freezing of Firefox will be avoided.


2. When a user drags to create a region, the region will start looping right away until Pause is clicked. - This is already working.
  
3. I need a function which takes start and end time from lyric files in srt format, and then creates a region that starts looping endlessly until another region is created or until Pause is clicked. - This is also working.  My code is like the following:


function loopIt(file_name,b,e){ // file_name is the name of the mp3
wavesurfer.clearRegions();
var region = wavesurfer.addRegion({
start: b,
end: e,
loop: true
}); 
region.play();
}


So, I am happy to report that other than the 1st need above, the other two needs are already met. And, though the 1st need is not fully met yet, the workaround of manually clearing a region before creating another is acceptable.   


It would be great if there is an option to leave only one region there.


Thank you for your help.


best regards
Jim



At 2019-11-07 09:44:34, "André Bunse" <notifications@github.com> wrote:


sounds like regions.clear does not work correct, can you provide a bit of your current code to reproduce the problem?

**Comment by myone1010** [comment]
regions.on('region-out', (region) => {
    if (wavesurfer.value.isPlaying()) {
      isPlaying.value = false;
      wavesurfer.value.pause();
    }
  });
