### ISSUE TITLE
Pre render peaks with PHP / Laravel

### ISSUE THREAD

**Issue by GigaMick** [katspaugh/wavesurfer.js#1784]
Is there a way to create the JSON peak data using php / Laravel?

All the packages I can find generate PNG files and not JSON data.

Thanks

**Comment by thijstriemstra** [comment]
use `audiowaveform` tool, see https://wavesurfer-js.org/faq/

**Comment by Reached** [comment]
Yea as @thijstriemstra points out, you can use the audiowaveform tool (it's a cmd tool) and then run that from an artisan command :)

**Comment by GigaMick** [comment]
Thanks @Reached and @thijstriemstra - I'll give this a bash but never used a CMD tool before. Lets see how this goes 🤘

**Comment by Reached** [comment]
@GigaMick Try it out, and let me know if I can help with anything! :)
