### ISSUE TITLE
scale-json.py Issue

### ISSUE THREAD

**Issue by StudentSA** [katspaugh/wavesurfer.js#1787]
Good Day,

On your FAQ section you share some python code (scale-json.py) which I have found to be problematic, especially for larger mp3 files.

When using this command the fractional-parts of the original data is enlarged: 
`new_data.append(x/max_val)`
i.e. for a value of 2.5 when we divide the max value of say 3 we now get "0.8333333333333334"

The reason for using precomputed peaks is to improve loading performance. Hence keeping the file size of our final json low will directly affects this. When running scale-json.py we are increasing the file size 10x as instead of using 3 characters to show (2.5) we now using 18 characters.

The fix is simple just replace with:
`new_data.append(round(x/max_val,2))`

possibly could make the round to a user selectable argument value.

**Comment by thijstriemstra** [comment]
thanks for the report, #1789 fixes this.
