### ISSUE TITLE
ReferenceError: WaveSurfer is not defined

### ISSUE THREAD

**Issue by liujinliang01** [katspaugh/wavesurfer.js#1791]
Hello,

I have noticed that a new version of wavesurfer.js has appeared in the src folder of github, so I downloaded it and started using it. But I get an error.

Error message in Firefox Console: ReferenceError: WaveSurfer is not defined

Code to produce the error: 
```
<script src="js/wavesurfer.js"></script>
	var wavesurfer = WaveSurfer.create({
    container: container_id,
    waveColor: 'violet',
    progressColor: 'purple',
    scrollParent: true,
    plugins: [
    	WaveSurfer.regions.create({})
    ]    
});
```
Operating System: Win10 Prof.
Browser: FireFox 70.0 32bit

Any help is appreciated.
best regards

Jim

**Comment by thijstriemstra** [comment]
hi Jim, you should download the latest release (https://github.com/katspaugh/wavesurfer.js/archive/3.2.0.zip), unpack it and follow these instructions to create a proper `wavesurfer.js` file: https://github.com/katspaugh/wavesurfer.js#development


```
npm install
npm run build
```

or use a CDN like unpckg or cdnjs.

**Comment by liujinliang01** [comment]
Hi Thijs,
I followed your instructions and now wavesurfer.js-3.2.0 is working.
Thank you very much.
best regards
Jim




At 2019-10-29 19:30:31, "Thijs Triemstra" <notifications@github.com> wrote:


hi Jim, you should download the latest release (https://github.com/katspaugh/wavesurfer.js/archive/3.2.0.zip), unpack it and follow these instructions to create a proper wavesurfer.js file: https://github.com/katspaugh/wavesurfer.js#development

npm install
npm run build


or use a CDN like unpckg or cdnjs.
