### ISSUE TITLE
loading event not fired

### ISSUE THREAD

**Issue by LupinoTech** [katspaugh/wavesurfer.js#1797]
((continuing the conversaton in #1597))
I try to catch the file loading progress listening to the `loading` event by using
```
var wavesurfer = WaveSurfer.create({
    container: '#lmp_waveform',
    backend: 'MediaElement',
    normalize: true,
});

wavesurfer.on('loading', function(x){
    console.log("Loading file. Progress:"+x);
});
wavesurfer.load('https://files.lupino.org/lorg/kajott.mp3');
```
but that event is never fired (log stays empty). Where is my mistake?

I'm using wavesurfer.js 3.2.0 (2019-10-25) on firefox 70.0 for Kubuntu 19.10.

**Comment by thijstriemstra** [comment]
you're using the MediaElement and this will not trigger any loading event as far as I know (it loads progressively/instantly).

**Comment by LupinoTech** [comment]
Changing to default (i.e. removing the backend line) didn't work either.

Don't bother, i'm switching to the competition...

**Comment by thijstriemstra** [comment]
> Don't bother, i'm switching to the competition...

👋

**Comment by SGDAT** [comment]
Hi there. Thanks for this amazing plugin.

I too seem to be having an issue with this. This is for mp3 files as large as 60mb. My code is as follows:-

`        wavesurfer = WaveSurfer.create({
            container: '#waveform',
            waveColor: 'black',
            progressColor: 'purple',
            barWidth: 2,
            barHeight: 1, // the height of the wave
            barGap: null
        });

        document.getElementById('startsection').classList.add('d-none');
        document.getElementById('loadingsection').classList.remove('d-none');
        wavesurfer.on('ready', function () {
            wavesurfer.play();
            document.getElementById('playsection').classList.remove('d-none');
            document.getElementById('pausesection').classList.remove('d-none');
            document.getElementById('loadingsection').classList.add('d-none');
        });

        wavesurfer.on("loading", function (progress) {
            document.getElementById('loadingValue').innerText = "%"
        });

        wavesurfer.load(url);`

The ready event works fine. But not loading. Any help will be much appreciated.

**Comment by thijstriemstra** [comment]
please open a new ticket instead.
