### ISSUE TITLE
cursor plugin doesn't show time in version 3.2

### ISSUE THREAD

**Issue by caterinamaria** [katspaugh/wavesurfer.js#1802]
Hi,
I have a problem with wavesurfer cursor plugin after I updated from version 3.0 to version 3.2.
I am running my code on the latest version of Chrome.
I just want to show the time on the cursor.
My code was working with version 3.0.
My plugin is created as follow:
```
WaveSurfer.cursor.create({
      showTime: true,
      container: wavesurferRef,
      opacity: 1
})
```
I have downloaded and debugged locally the code of the plugin and I found that the visibility of the element containig the time in the cursor is never put to visible, so the time is never shown.

This is the piece of code responsible to show the time:
```
if (this.params.showTime) {
        var duration = this.wavesurfer.getDuration();
        var elementWidth = this.wavesurfer.drawer.width / this.wavesurfer.params.pixelRatio;
        var scrollWidth = this.wavesurfer.drawer.getScrollX();
        var scrollTime = duration / this.wavesurfer.drawer.width * scrollWidth;
        var timeValue = Math.max(0, xpos / elementWidth * duration) + scrollTime;
        var formatValue = this.formatTime(timeValue);

        if (flip) {
          var textOffset = this.outerWidth(this.displayTime);
          xpos -= textOffset;
        }

        this.style(this.showTime, {
          left: "".concat(xpos, "px"),
          top: "".concat(ypos, "px"),
          visibility: 'visible'
        });

       *****

        this.displayTime.innerHTML = "".concat(formatValue);
      }
}
```
If I add:
 ```
        this.style(this.displayTime, {
          visibility: 'visible'
        });
```
at the end, where I put *****, the cursor is correctly shown.

I'd like to report this bug so that it can be fixed in the first next release, I have tried it locally and now my code works as before with version 3.0.

**Comment by thijstriemstra** [comment]
probably related to https://github.com/katspaugh/wavesurfer.js/commit/8307f088750ff219f7ef53b27b0ecaa9d0fdf88c#diff-9cf7fd6a13109647dc9a722ee1b997ce

cc @mdtanrikulu

**Comment by caterinamaria** [comment]
Yes, probably it is related to that change because in the previous version the time was correctly shown.

In the code diff you linked, the "visibiliy: hidden" is set to "this.displayTime", but "visibility: visible" is set to "this.showTime" and not to "this.displayTime".
In this way, the element "this.displayTime" that contains the current time is never shown.

**Comment by thijstriemstra** [comment]
@caterinamaria can you make a pull request with a fix?

**Comment by caterinamaria** [comment]
I have made a pull request with this fix
