### ISSUE TITLE
big file has crash too

### ISSUE THREAD

**Issue by lida1984** [katspaugh/wavesurfer.js#1805]
> Yes, correct.

With WebAudio backend, even if i give peaks to draw the waveform, it internally decodes the audio to transform it to an AudioBuffer and put it to AudioBufferSourceNode. So the waveform is drawn without any problems, but in case of big audio files, the browser crashes because it decodes the data in memory. 
If we give an HTML5 tag with peaks, the waveform is drawn without decoding. Moreover, giving the source (HTML tag) to MediaElementSourceNode, it does not decode audio data in memory, so it can be played without any problems (like with MediaElement backend).
So in this way we can add filters and have more controls with audio because we can use API Web Audio,  even with big audio files.

If we give an HTML5 tag with peaks, the waveform is drawn without decoding. Can you give me a demo that an h5 tag with peaks ?  How can i get the peaks ? This is a problem.

**Comment by thijstriemstra** [comment]
>  h5 tag with peaks ? How can i get the peaks ? This is a problem.

What does this mean? Please rephrase and explain.
