### ISSUE TITLE
Wavesurfer Microphone Plugin to attach to open microphone stream on iOS

### ISSUE THREAD

**Issue by nevrologica** [katspaugh/wavesurfer.js#1810]
Hello,

I am currently implementing a web app where i use wavesurfer microphone plugin to present the microphone oscilator to the user. I am using this together with the IBM Watson speech to text javascript sdk.

My problem is that my current status of implementation works perfectly on every other browser except iOS devices such as my iPhone. I am running iOS 13.2.3.

The workflow is that i initialize and open a microphone stream through the Speech to Text API then initialize the Wavesurfer Microphone plugin. Once the later is up and running, the previous open stream is broken and vice versa. When i first initialize the wavesurfer microphone plugin and then the speech to text stream, the microphone plugin brakes.

I was trying to find out if there is a way to share the current open stream of the microphone between the two. Firefox, Chrome, Safari on Windows does it but not on iOS.

One thing i noticed is that whenever i initialize the speech to text stream on ios, and then the microphone plugin, i can then see the microphone plugin active and without having to implement the ios fix code on the initialisation, that means that the speech to text plugin does the trick for ios. Therefore i decided to run the wavesurfer plugin always after the speech to text stream to avoid the hack.

However it will only work for the stream i initialize last. Is there a way for wavesurfer to attach to already open mic streams for ios?

I use the following code as an example :

stream = WatsonSpeech.SpeechToText.recognizeMicrophone(Object.assign(speechToken, {
				model: document.querySelector('#speechModel').value,
				outputElement: '#output'
			}));

			wavesurfer = initMicrophoneVisualizer(wavesurfer, isSafari);			
			wavesurfer.microphone.start();

function initMicrophoneVisualizer(wavesurfer, isSafari){
	
	if (wavesurfer === undefined) {
		
        if(!isSafari)
            barHeight = 2;
		else
			barHeight = 8;
			
		wavesurfer = WaveSurfer.create({
			container           : '#waveform',
			waveColor           : 'red',
			height		        : 100,
			interact            : false,
			cursorWidth         : 0,
			barHeight			: barHeight,
			barRadius 			: 18,
			plugins: [
				WaveSurfer.microphone.create()]
		});
	}
	
	return wavesurfer;
}

Also, the speech to text stream is not a MediaStream like the one in microphone plugin. It's a wrapped object than i can not pull the current microphone stream right now it seems. The only way i can see this go is if the wavesurfer microphone plugin can get smarter in attaching to an already open microphone stream for ios, if that is allowed by the device.

Thanks in advance.

**Comment by thijstriemstra** [comment]
Take a look at the Safari workaround in the microphone example: https://github.com/katspaugh/wavesurfer.js/blob/master/example/microphone/app.js#L12

**Comment by nevrologica** [comment]
I have described that i am using the workaround and the waveform of the microphone shows properly on mobile Safari. My actuall problem is that it blocks an already open microphone stream that another process opened. This has to be reopened. Best case scenario would be for the microphone plugin to attach to an already open microphone stream rather than creating one forcibly every time using the create() method.

**Comment by jeghedderchristoffer** [comment]
I have the same problem. Any updates?

**Comment by jeghedderchristoffer** [comment]
I dived into the source code of the microphone and the solution is to call the `gotStream(streamHere)` instead of `start()`.

**Comment by fatemi2020** [comment]
@jeghedderchristoffer thank you very much, you fixed my issue also and saved hours for me.
