### ISSUE TITLE
Error calling wavesurfer.seekTo, parameter must be a number between 0 and 1

### ISSUE THREAD

**Issue by fuzegit** [katspaugh/wavesurfer.js#1816]
Hi!

Thank you for your work :)

### Wavesurfer.js version: 
3.2.0 

### Browser and operating system version(s):
LinuxMint, Opera 65.0, Firefox70.0.1

### Code needed to reproduce the issue:

```javascript
var wavesurfer = WaveSurfer.create({
    container: '#player-wrap-'+u.data.id,
    waveColor: '#94919C',
    progressColor: '#007DFF',
    height: 50,
    pixelRatio: 1,
    cursorColor: '#fff',
    normalize: true,
    responsive: true
});
// blob in webm format
// and checked with wavesurfer.load('audio.wav');
wavesurfer.loadBlob(u.data.blob);
wavesurfer.on('ready', function () {
    wavesurfer.play();
});
// audioprocess event returns correct data
// wavesurfer.on('audioprocess', updateTimer);
```

### Result if seek

![Выделение_140](https://user-images.githubusercontent.com/13233234/69751611-8db1e500-1160-11ea-9a6c-76f48305f655.png)

**Comment by thijstriemstra** [comment]
> Result if seek

Your example code doesn't include a call to `seekTo`, where and how are you calling this?

**Comment by fuzegit** [comment]
I click on the waveform

**Comment by Christilut** [comment]
I have the same thing happening but I can't reproduce it in a codepen... It happens when the wavesurfer is playing and you click exactly 1 pixel before the start of the waveform. Seems that 1 pixel is causing it to seek to a value below 0. The value was `-0.00375` for me.
This happened on a very small 200px waveform.

![image](https://user-images.githubusercontent.com/3471363/72216716-47a0bd00-3525-11ea-86ee-6a33f8699d10.png)

**Comment by atomoc** [comment]
Yeah, this is a critical mistake.

**Comment by aburai** [comment]
could not reproduce it, but we have seen, it could happen
@thijstriemstra i create a branch with a possible fix, please have a look, after that i create the PR

**Comment by Dexmaster** [comment]
It is reproducible on main page if you click exactly on 0 position...
![image](https://user-images.githubusercontent.com/6061000/82942976-82b9ff00-9fa1-11ea-992c-645bc5d5782c.png)

**Comment by overture8** [comment]
@aburai Your commit here (https://github.com/katspaugh/wavesurfer.js/commit/f3b0561383071f13f5b311d2b0b0490d9380b129) looks good to me. Do you think you'll get a chance to PR this / release soon? Thanks :)

**Comment by r-bechara** [comment]
The same problem happened to me and I solved converting the "position" variable to Number before calling toSeek.

const n = Number(position)
toSeek(n)
