### ISSUE TITLE
cross-site cookies set by wavesurfer distribution library at cloudflare

### ISSUE THREAD

**Issue by LBPSlava** [katspaugh/wavesurfer.js#1818]
This is a great library that allows my pages to do things I would not know how to do otherwise. It has served my users for several years now with no trouble.

Now that Chrome (and others) are implementing restrictions on cross-site cookies, I am seeing this warning from Chrome when the library loads:
====
A cookie associated with a cross-site resource at http://www.cloudflare.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`.
====
I load the wavesurfer library and the regions plugins from:

https://cdnjs.cloudflare.com/ajax/libs/wavesurfer.js/1.1.10/wavesurfer.min.js
and
https://cdnjs.cloudflare.com/ajax/libs/wavesurfer.js/1.1.10/plugin/wavesurfer.regions.min.js

Any advice will be appreciated.

**Comment by thijstriemstra** [comment]
this is probably more a question for the cdnjs repository on github, the ones hosting these files.

You could also try a different CDN, e.g. unpkg.com

**Comment by LBPSlava** [comment]
Thanks, Thijs! I couldn’t find the URL for version 1 on unpkg.com.

**Comment by thijstriemstra** [comment]
True. Any reason not updating to the latest version?

**Comment by LBPSlava** [comment]
Thanks again, Thijs! No specific reason, I just can't find the time to test all my pages with version 2, including the Regions library. Maybe in January, during the winter break at Cornell. Slava
    


-------- Original message --------

**Comment by LBPSlava** [comment]
Besides, version 1 does everything I need just fine. My only wish is for a waveform with regions to resize itself (horizontally) when the user resizes the width of the browser window. 
    


-------- Original message --------

**Comment by thijstriemstra** [comment]
version 1.x is no longer supported so please upgrade. If issue is still there, re-open this ticket.
