### ISSUE TITLE
regions mouse click events not working

### ISSUE THREAD

**Issue by kishan143-jaiswal** [katspaugh/wavesurfer.js#1819]
version:3.2.0

    this.wavesurfer.on('region-update-end', (region) => {
      this.wavesurfer.drawer.un('click');
      if (!this.props.loop) {
        if (selectedRegion != null) {
          //console.log(selectedRegion)
          //Unhighligt old selection
          selectedRegion.update({
            color: 'rgba(0, 255, 0, 0.1)'
          });
        }
        selectedRegion = region;
        this.wavesurfer.drawer.on('click', (e, progress) => {
          setTimeout(() => {
            var seekpos = progress * this.wavesurfer.getDuration();

            if (selectedRegion != null) {

              //Check if clicked outside last selected region...
              if (seekpos < selectedRegion.start || seekpos > selectedRegion.end) {
                //Unhighlight region
                selectedRegion.update({
                  color: 'rgba(0, 255, 0, 0.1)'
                });
                selectedRegion = null;
                this.wavesurfer.backend.seekTo(seekpos);
              }
              else { // end if seekpos...
                selectedRegion.update({
                  color: 'rgba(255, 0, 0, 0.25)'
                });
                selectedRegion = region;
                this.wavesurfer.backend.seekTo(selectedRegion.start, selectedRegion.end);
              }
            } else { // end if selectedRegion..
              this.wavesurfer.backend.seekTo(seekpos);
            }

            this.wavesurfer.drawer.progress(this.wavesurfer.backend.getPlayedPercents());
            // region.playLoop();
          }, 0);
        });
      }
    });
this.wavesurfer.drawer events not detecting  mouse events while creating regions , i have manually click on the region to play from created region start point
and its working fine in older versions 1.1.2

https://github.com/katspaugh/wavesurfer.js/issues/420

followed this solution to listen mouse drag

**Comment by bilalcorbacioglu** [comment]
@kishan143-jaiswal Please check;

https://wavesurfer-js.org/example/annotation/index.html

```
.....
          event.stopPropagation();
          region.play()
.....
```

**Comment by kishan143-jaiswal** [comment]
thanks for response , its worked
