### ISSUE TITLE
Using with jquery .load() function

### ISSUE THREAD

**Issue by fisherman77** [katspaugh/wavesurfer.js#1834]
I trying use this plugin in WordPress.

My problem is that if I have a DIV block "container" on the page with wave surfers listed with the function foreach() and I try to reload this DIV block with the jquery function .load() then I get the above error in console, wave surfer not show:
> Uncaught SyntaxError: Cannot use import statement outside a module

I use code to reload DIV block in the site:
` jQuery(".container").load(location.href + " .container");`

My code:
` 
<div class="container">

        <div id="audio-spectrum"></div>

        
        <input type="button" id="btn-play" value="Play" disabled="disabled"/>
        <input type="button" id="btn-pause" value="Pause" disabled="disabled"/>
        <input type="button" id="btn-stop" value="Stop" disabled="disabled" />';
        
 
        <script>
            // Store the 3 buttons in some object
            var buttons = {
                play: document.getElementById("btn-play"),
                pause: document.getElementById("btn-pause"),
                stop: document.getElementById("btn-stop")
            };

            // Create an instance of wave surfer with its configuration
            var Spectrum = WaveSurfer.create({
                container: '#audio-spectrum',
                progressColor: "#03a9f4",
                barWidth: 3,
                backend: 'MediaElement',
              mediaType:'audio',
                normalize: true
            });

            // Handle Play button
            buttons.play.addEventListener("click", function(){
                Spectrum.play();

                // Enable/Disable respectively buttons
                buttons.stop.disabled = false;
                buttons.pause.disabled = false;
                buttons.play.disabled = true;
            }, false);

            // Handle Pause button
            buttons.pause.addEventListener("click", function(){
                Spectrum.pause();

                // Enable/Disable respectively buttons
                buttons.pause.disabled = true;
                buttons.play.disabled = false;
            }, false);

            // Handle Stop button
            buttons.stop.addEventListener("click", function(){
                Spectrum.stop();

                // Enable/Disable respectively buttons
                buttons.pause.disabled = true;
                buttons.play.disabled = false;
                buttons.stop.disabled = true;
            }, false);

            // Add a listener to enable the play button once it's ready
            Spectrum.on('ready', function () {
                buttons.play.disabled = false;
            });
            
            // If you want a responsive mode (so when the user resizes the window)
            // the spectrum will be still playable
            window.addEventListener("resize", function(){
                // Get the current progress according to the cursor position
                var currentProgress = Spectrum.getCurrentTime() / Spectrum.getDuration();

                // Reset graph
                Spectrum.empty();
                Spectrum.drawBuffer();
                // Set original position
                Spectrum.seekTo(currentProgress);

                // Enable/Disable respectively buttons
                buttons.pause.disabled = true;
                buttons.play.disabled = false;
                buttons.stop.disabled = false;
            }, false);

            // Load the audio file from your domain !
            Spectrum.load('test/test.mp3');
        
        </script>
</div>
`

Could you help solve this problem?

**Comment by thijstriemstra** [comment]
> Uncaught SyntaxError: Cannot use import statement outside a module

how are you including wavesurfer.js in your project?

**Comment by fisherman77** [comment]
In back end in my plugin:

```
> 
>  function includeWS() {
> 
>  $dir = plugins_url();
>          
>                  	wp_register_script('stylewav', $dir . '/site/includes/js/wavesurfer.js');
> 	                wp_enqueue_script('stylewav', $dir . '/site/includes/js/wavesurfer.js');
> 
>      }
>      
>   add_action('wp_enqueue_scripts', 'includeWS');
> 

```

The same happend with plugin "WaveSurfer-WP" for WordPress (https://fi.wordpress.org/plugins/wavesurfer-wp/).

**Comment by thijstriemstra** [comment]
try using a CDN version of wavesurfer.js. The error ` Cannot use import statement outside a module` indicates your not including the minified, compiled version.

**Comment by thijstriemstra** [comment]
no feedback, closing.
