### ISSUE TITLE
regions plugin: add support for contextmenu event on regions

### ISSUE THREAD

**Issue by Frank3K** [katspaugh/wavesurfer.js#1842]
In the current version of waversurfer.js (3.3.0) there are several handlers for events on regions: `mouseenter`, `mouseleave`, `click` and `dblclick` ([source](https://github.com/katspaugh/wavesurfer.js/blob/17d6731e01933d85a786df3f30725b80a3fc7b62/src/plugin/regions.js#L318-L338)).

I would like to show a menu when right-clicking on a region. This could be made possible using the following lines:

```js
        this.element.addEventListener('contextmenu', e => {
            e.preventDefault();
            this.fireEvent('click', e);
            this.wavesurfer.fireEvent('region-contextmenu', this, e);
        });
```

If wanted, I can do a PR for this.

**Comment by thijstriemstra** [comment]
sounds good. with an option to disable/enable.

**Comment by Frank3K** [comment]
> sounds good. with an option to disable/enable.

The current four events can't be disabled / enabled, there is always an event handler added for these. Would it be better to change this generically? For example by supplying a list of events you want to handle (defaulting to the current four)?

**Comment by thijstriemstra** [comment]
i meant an option to enable/disable the context menu.
