### ISSUE TITLE
exportImage returns "empty" data URIs and blobs.

### ISSUE THREAD

**Issue by ghuwe** [katspaugh/wavesurfer.js#1843]
### Wavesurfer.js version(s):
3.3.0 (latest as of this post's date)

### Browser and operating system version(s):
Firefox Dev Edition, 72.0b11
Chromium 79.0
Arch Linux

### Code needed to reproduce the issue:
```
var wavesurfer = WaveSurfer.create({
    container: '#waveform',
    waveColor: 'violet',
    progressColor: 'purple',
    cursorWidth: 0,
    interact: false,
});

wavesurfer.load('audio.mp3');

wavesurfer.on('ready', function () {
    var waveimage = wavesurfer.exportImage();
    document.getElementById('pngwave').innerHTML = '<img src="' + waveimage + '">';
});
```

### Use behaviour needed to reproduce the issue:
Just loading the page returns the <wave> object and it displays nicely. However, the data URI returns empty instead of showing the waveforms. The same happens with blobs.

**Comment by thijstriemstra** [comment]
Go the https://wavesurfer-js.org/, open a console, type `wavesurfer.exportImage()` and it seems to work fine.
