### ISSUE TITLE
Can't stop microphone in react functional components

### ISSUE THREAD

**Issue by sascharissling** [katspaugh/wavesurfer.js#1846]
Wavesurfer: 3.3.0
Chrome: Version 79.0.3945.117 (Official Build) (64-bit)
MacOS: 10.14.6
CODE: https://codepen.io/sascharissling/pen/abzKZwB?editors=0010

Hello there. I'm running wavesurfer with the microphone in a React app using functional components. 

I can start the microphone just fine. But whenever i stop the microphone i get a 
`this.stream.stop is not a function``

This also happens when i call the stop, destroy, stopDevice with a timeout after letting the mic start automatically on rendering inside the useEffect

**Comment by thijstriemstra** [comment]
can you reproduce this with the non-react example? @sascharissling

**Comment by sascharissling** [comment]
I'm working on an mvp right now and time is scarce. So i cant produce a non react example right now. 
But i will get to this once I'm through with that next week :-)

**Comment by thijstriemstra** [comment]
simply try the existing microphone example?

**Comment by sascharissling** [comment]
Sorry, I'm fairly new to web development (three months) and thought i should write my app into non-react. haha. 

in the microphone example the microphone closes. 

I think the issue with my react code is that all microphone methods except starting the microphone have `.this` in them?

**Comment by thijstriemstra** [comment]
> I think the issue with my react code is 

No idea, I don't use/like React. Please use stackoverflow or react forums for that question.

**Comment by sascharissling** [comment]
okay. thanks for your time! :-) love the package. have a great day!
