### ISSUE TITLE
Problem displaying multiple waves

### ISSUE THREAD

**Issue by cesanag** [katspaugh/wavesurfer.js#1847]
I'm trying to display more than one waveform on the same page but I think I'm missing something crucial. Only the first audio from an object is rendered, because they all share the same container. Am I doing it wrong somehow?
Pen for reference:
https://codepen.io/cusanag/pen/abzEmmo

Thank you.

**Comment by thijstriemstra** [comment]
@cesanag you need to create a new div for each waveform and create a new `WaveSurfer` instance for each div

```javascript
var wavesurfer1 = WaveSurfer.create({
            container: "#waveform1",
            backgroundColor: 'rgb(10, 10, 10)'
});

var wavesurfer2 = WaveSurfer.create({
            container: "#waveform2",
            backgroundColor: 'rgb(10, 10, 10)'
});
```

**Comment by cesanag** [comment]
Thank you.

**Comment by ZaurNatok** [comment]
I have a similar problem. Trying to display 2 or more wavesurfe files. Both are loaded and played, but the wave is drawn on only one of them. The div containers are different. Can you suggest what is the problem?

`<div class="otziv">
    <div class="control-bar">
        <img src="./images/play.png" alt="" class="playBtn">
        <img src="./images/pause.png" alt="" class="pauseBtn invisible">
    </div>
    <div id="waveform"></div>
</div>

<br>

<div class="otziv">
    <div class="control-bar">
        <img src="./images/play.png" alt="" class="playBtn2">
        <img src="./images/pause.png" alt="" class="pauseBtn2 invisible">
    </div>
      <div id="waveformSecond"></div>
</div>



  

<script>
let wavesurfer = {};
let wavesurferSecond = {};


const playBtn = document.querySelector('.playBtn');
const pauseBtn = document.querySelector('.pauseBtn');

document.addEventListener('DOMContentLoaded', function() {
    wavesurfer = WaveSurfer.create({
        container: document.querySelector('#waveform'),
        waveColor: 'white',
        progressColor: 'gray',
        barWidth: 2,
        barHeight: 1,
        barGap: null,
        responsive: true
    })
    wavesurfer.load('zvuk.mp3');
});



playBtn.addEventListener('click', () => {
    wavesurfer.play();
    pauseBtn.classList.toggle('invisible');
    playBtn.classList.toggle('invisible');
});

pauseBtn.addEventListener('click', () => {
    wavesurfer.pause();
    pauseBtn.classList.toggle('invisible');
    playBtn.classList.toggle('invisible');
})

const playBtn2 = document.querySelector('.playBtn2');
const pauseBtn2 = document.querySelector('.pauseBtn2');

document.addEventListener('DOMContentLoaded', function() {
wavesurferSecond = WaveSurfer.create({
    container: document.querySelector('#waveformSecond'),
    waveColor: 'blue',
    progressColor: 'yellow',
    barWidth: 2,
    barHeight: 1,
    barGap: null,
    responsive: true
});
wavesurferSecond.load('zvuk2.mp3');
});

playBtn2.addEventListener('click', () => {
    wavesurferSecond.play();
    pauseBtn2.classList.toggle('invisible');
    playBtn2.classList.toggle('invisible');
});

pauseBtn2.addEventListener('click', () => {
    wavesurferSecond.pause();
    pauseBtn2.classList.toggle('invisible');
    playBtn2.classList.toggle('invisible');
})

  </script>`
