### ISSUE TITLE
CORS audio loading

### ISSUE THREAD

**Issue by AravindKumarEmpress** [katspaugh/wavesurfer.js#1856]
i tried to load an audio from s3 bucket using load() method in MVC C# project, but i'm getting `from origin 'http://localhost:50300' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`  i tried to setted up Access-Control-Allow-Origin in web.config, still i'm getting the same error. pls help me.

**Comment by thijstriemstra** [comment]
use the `xhr` option, see bottom of https://wavesurfer-js.org/docs/options.html

for example:

```javscript
let xhr = { cache: 'default', mode: 'cors', method: 'GET', credentials: 'same-origin', redirect: 'follow', referrer: 'client', headers: [ { key: 'Authorization', value: 'my-token' } ]};
```

**Comment by JustinMatthewNewman** [comment]
I have the same issue. Was a solution found?

**Comment by f-deniyi** [comment]
Has this been solved? It’s really affecting me.

**Comment by JustinMatthewNewman** [comment]
> Has this been solved? It’s really affecting me.

for me it was a matter of changing some internal server settings. by default my google firebase storage had cross origin resource sharing disabled. i had to sign into web console and run some commands to enable cors

**Comment by jriffs** [comment]
> > Has this been solved? It’s really affecting me.
> 
> for me it was a matter of changing some internal server settings. by default my google firebase storage had cross origin resource sharing disabled. i had to sign into web console and run some commands to enable cors

@JustinMatthewNewman please could you say what commands you ran, and how you ran them?? I'm also having this issue

**Comment by JustinMatthewNewman** [comment]
yeah so you wanna sign into console.cloud.google.com with the same account linked to firebase. 

then select your firebase project. 

from there you should search cors configuration. 

there is a really nice tutorial on there for setting it up. i also searched the error on stackoverflow and used the default config posted there to allow all cors. hope this helps

**Comment by redimongo** [comment]
We are having the same issue too.

**Comment by katspaugh** [comment]
You need to configure your server to allow CORS.
See https://enable-cors.org/server.html
