### ISSUE TITLE
Wave form to move up instead of the cursor moving down. 

### ISSUE THREAD

**Issue by abinav-07** [katspaugh/wavesurfer.js#1857]
I am trying to move the waveform up and make the cursor static in one position. Can I get some help with that? Plus, my waveform is vertical!! 
And one more thing, Is there a way to increase the length of the cursor ?

**Comment by thijstriemstra** [comment]
can you add a screenshot of what you're trying to achieve?

**Comment by thijstriemstra** [comment]
no feedback, closing.
