### ISSUE TITLE
wavesurfer load() 404 on http://localhost:3000/../[object%20HTMLAudioElement]

### ISSUE THREAD

**Issue by lyvija** [katspaugh/wavesurfer.js#1859]
Hey, 
I'm trying to display waveform of wav audio from my public folder. I got an error wavesurfer.min.js:4 GET http://localhost:3000/record/admin/[object%20HTMLAudioElement] 404 (Not Found). Any advice to fix my problem? Thank you in advance.

 Wavesurfer.js version(s): ^1.4.0
 Browser and operating system version(s): Ubuntu 18.04.3, Chrome/Firefox

Code:
```javascript
 componentDidMount() {
    this.fetchRecord(this.props.match.params.record);
    this.createWaveform();
  };

  createWaveform(){
    const audio = document.querySelector('#audio');
    this.waveform = WaveSurfer.create({
      barWidth: 1,
      cursorWidth: 1,
      container: '#waveform',
     ...
    });
    this.waveform.load(audio);
  }
...
render() {
  return (
   ...
          <div id="waveform" />
         <audio id='audio' src={process.env.PUBLIC_URL+"/"+record.file_address}/>
   ...
```
Behaviour: After click on record in table, try to display page with waveform of current record - wav audio file in my public folder. I got 404 xhr error on http://localhost:3000/../[object%20HTMLAudioElement].

**Comment by thijstriemstra** [comment]
@lyvija you need to specify the specific backend, `MediaElement` in this case:

```javascript
this.waveform = WaveSurfer.create({
      barWidth: 1,
      cursorWidth: 1,
      backend: MediaElement,
      container: '#waveform',
    });
```
