### ISSUE TITLE
Examples not working, wrong paths. Worth to invest anyway?

### ISSUE THREAD

**Issue by codebeat-nl** [katspaugh/wavesurfer.js#1860]
Hi I want to try your software but I can't. Not online because unpkg.com cannot be reached and the current source doesn't work either because it wants to use a directory that doesn't exist: 'dist' I have used the timeline example. 

What I want to know is this, does it provide timing information when processing a wav file. I need this to translate a PWM signal to binary with timing information.

**Comment by thijstriemstra** [comment]
>  unpkg.com cannot be reached 

I think it was a temporary glitch, seems to work fine now.

> current source doesn't work either because it wants to use a directory that doesn't exist: 'dist' I have used the timeline example.

After you download the source (using git or zip file), follow these instructions: https://github.com/katspaugh/wavesurfer.js#development

Or simply install using `npm install wavesurfer.js`
