### ISSUE TITLE
wavesurfer load binary

### ISSUE THREAD

**Issue by andii04** [katspaugh/wavesurfer.js#1862]
Hey Im using wavesurfer, and can load file from local storage like:
wavesurfer.load('voiceMails/' + userFilename + '');

Now im getting the .wav as binary like:  [82, 73, 70,  …]

Is there a way to load this binary ? like above the file ?

**Comment by thijstriemstra** [comment]
yes, turn you .wav file into a `Blob` instance and use `wavesurfer.loadBlob()` to load it.

**Comment by longyarnz** [comment]
Hello, I tried using the `wavesurfer.loadBlob` method to load a blob but I get this error instead:
![image](https://user-images.githubusercontent.com/19750988/75349216-a8e9d900-58a4-11ea-99de-d82332d1887d.png)

**Comment by thijstriemstra** [comment]
what does your wavesurfer.js config look like? this error looks unrelated to wavesurfer, `container` is undefined...

**Comment by longyarnz** [comment]
The snapshots are from the wavesurfer library. This is my config:
```js
             wavesurfer = WaveSurfer.create({
                container: "#waveform",
                waveColor: "#888",
                progressColor: "white",
                height: 52,
                backend: "MediaElement",
                audioRate: rate,
                loopSelection: false,
                cursorWidth: 2,
                cursorColor: "#fff",
                responsive: true,
                hideScrollBar: true,
                partialRender: true
            });

**Comment by longyarnz** [comment]
Thank you for replying @thijstriemstra . I didn't think anyone would try to look into it, so I closed the issue!

**Comment by thijstriemstra** [comment]
you can only use `loadBlob` with the `WebAudio` backend.
