### ISSUE TITLE
Cancel Region Play Loop Properly

### ISSUE THREAD

**Issue by bwang514** [katspaugh/wavesurfer.js#1868]
Hi, thanks for making this fantastic repo!

I'm trying to build a system with which users can freely navigate the video and loop whatever intervals they want. The region plugin seems to work properly at first glance. However,  it seems there are some bugs with the region plugin, specifically associated with looping.

[Problem]
1. Once I start looping on a region, I would not be able to use the native cursor from the wavesufer to navigate the video (you might still be able to select timestamps on the waveform but when you start playing it will jump back to the looping region). The only way to jump to other parts of the video is to click on other regions. 

2. If I loop on multiple regions, the browser would start being overloaded and becomes extremely slow. This happens when I've done looping a region and try to loop on other regions without stop the video first.

[Reproduce]
You could reproduce all these problems with the annotation and video-annotation examples.

I've tried to solve it by myself but haven't succeeded yet. I doubt it's because there's not any function actually "cancel" the looping. Does anyone have an idea?

Thanks

**Comment by cadavre** [comment]
I can confirm. This is related to endlessly chained events that are binded to the wavesurfer and the difference that `this.loop` plays differently than with `playLoop()`. This needs to be unified.
