### ISSUE TITLE
Wavesurfer.loadBlob error

### ISSUE THREAD

**Issue by longyarnz** [katspaugh/wavesurfer.js#1869]
Hello, I tried using the `wavesurfer.loadBlob` method to load a blob but I get this error instead:
![image](https://user-images.githubusercontent.com/19750988/75349216-a8e9d900-58a4-11ea-99de-d82332d1887d.png)

And the error points here:
![image](https://user-images.githubusercontent.com/19750988/75349292-d171d300-58a4-11ea-9a75-c6deac10aac9.png)

_Originally posted by @longyarnz in https://github.com/katspaugh/wavesurfer.js/issues/1862#issuecomment-591426896_

**Comment by zw3428** [comment]
Hi, I met the same error, how did you solve this problem?

**Comment by longyarnz** [comment]
In order for loadBlob to work you'll have to use WebAudio as your backend element instead of MediaElement

**Comment by zw3428** [comment]
Thx, it works!
