### ISSUE TITLE
Do we can implement function on button click it will save selected audio parts?

### ISSUE THREAD

**Issue by surajsonee** [katspaugh/wavesurfer.js#1870]
Hello,
I have implemented a function on selecting audio range(start and end time) clicking on selected audio range its save the audio in a specific folder.

Do we can implement function on button click it will save selected audio parts in a folder.

Thank you

**Comment by thijstriemstra** [comment]
Are you suggesting an enhancement? can you open a pull request?

**Comment by thijstriemstra** [comment]
no feedback, closing.
