### ISSUE TITLE
Is there a way to show Waveform from youtube video? 

### ISSUE THREAD

**Issue by Aparus** [katspaugh/wavesurfer.js#1871]

**Comment by thijstriemstra** [comment]
No, not that I know.

**Comment by Aparus** [comment]
> No, not that I know.

But I think there is a way to extract audio stream from youtube video and give it to wavesurfer ;-) 
Any ideas? I want to do something like youtube subtitles editor, but better :) 
![Screenshot from 2019-09-28 23-18-13](https://user-images.githubusercontent.com/1222611/75552654-d1f69f00-5a47-11ea-83ab-3164adba904b.png)

**Comment by thijstriemstra** [comment]
You can install `youtube-dl` and use that to download it and convert it to mp3 (but you can also use the mp4 video instead):

```console
youtube-dl -x --audio-format mp3 https://www.youtube.com/watch?v=VYOjWnS4cMY
```

Which then can be loaded into youtube.

**Comment by Aparus** [comment]
@thijstriemstra 
> (but you can also use the mp4 video instead)
Oh, thanks, now I have find examples about it :)
https://wavesurfer-js.org/example/video-annotation/index.html
https://wavesurfer-js.org/example/video-element/index.html
Is there any other links about using video? I looked at docs but I haven't find mention of video. 
https://wavesurfer-js.org/doc/

**Comment by thijstriemstra** [comment]
> Is there any other links about using video? I

The examples or source code are available.

**Comment by Aparus** [comment]
@thijstriemstra 
> (but you can also use the mp4 video instead)
Do you mean, that I can extract mp4 from youtube video in my app? If yes, how? :)

**Comment by thijstriemstra** [comment]
yes like I said, using youtube-dl: https://github.com/katspaugh/wavesurfer.js/issues/1871#issuecomment-592515700 Check their documentation for more details.

**Comment by Furkan-Gulsen** [comment]
You can review the following code section. But it does not seem possible to get it directly on youtube. So you can do it either in mp4 or mp3 format or by entering the wave properties as json.
[Link](https://github.com/katspaugh/wavesurfer.js/tree/master/example/mediaelement-webaudio)
