### ISSUE TITLE
Regions

### ISSUE THREAD

**Issue by aphiwemagama** [katspaugh/wavesurfer.js#1874]
How do I play the created region and only that region?

**Comment by bilalcorbacioglu** [comment]
Hi @aphiwemagama,

You have region data right? It's so simple,

`/* Play the audio region. */
    play() {
        this.wavesurfer.play(this.start, this.end);
        this.fireEvent('play');
        this.wavesurfer.fireEvent('region-play', this);
    }`

Please check for more information 
https://wavesurfer-js.org/doc/file/src/plugin/regions.js.html
