### ISSUE TITLE
CORS Audio Loading

### ISSUE THREAD

**Issue by alittlebitweird** [katspaugh/wavesurfer.js#1882]
Struggling to get past the following error when loading audio files from s3:

`MediaElementAudioSource outputs zeroes due to CORS access restrictions for <some s3 url>`

The waveform loads properly but you can't playback the audio.

I'm using the xhr option, but it's unclear what to pass in as the authorization token. I tried using the S3 access key id, I also tried generating this credential string: [s3 credential string](https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-auth-using-authorization-header.html) to no avail.

Here is my CORS policy:
```
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration>
<CORSRule>
    <AllowedOrigin>*</AllowedOrigin>
    <AllowedOrigin>http://*</AllowedOrigin>
    <AllowedOrigin>https://*</AllowedOrigin>
    <AllowedMethod>GET</AllowedMethod>
    <MaxAgeSeconds>3000</MaxAgeSeconds>
    <AllowedHeader>*</AllowedHeader>
</CORSRule>
</CORSConfiguration>
```
I've looked at similar issues but they weren't helpful. Any idea what I'm doing wrong?

**Comment by thijstriemstra** [comment]
have you tried https://docs.sumerian.amazonaws.com/tutorials/create/beginner/s3-video/

**Comment by alittlebitweird** [comment]
@thijstriemstra I'm sorry, I just looked over that three times and it's pretty unclear what that has to do with anything... 

My S3 bucket is fully public and the CORS policy is even less specific

**Comment by thijstriemstra** [comment]
I do not use S3, sorry.

**Comment by aburai** [comment]
this is our s3 configuration
```
<CORSRule>
    <AllowedOrigin>*</AllowedOrigin>
    <AllowedMethod>GET</AllowedMethod>
    <AllowedMethod>HEAD</AllowedMethod>
    <MaxAgeSeconds>3000</MaxAgeSeconds>
    <AllowedHeader>Authorization</AllowedHeader>
</CORSRule>
```

**Comment by thijstriemstra** [comment]
> this is our s3 configuration

And what does your wavesurfer `xhr` option look like @aburai?

**Comment by aburai** [comment]
i use the default options

**Comment by entonbiba** [comment]
@aburai try adding this `<AllowedHeader>*</AllowedHeader>`

**Comment by aburai** [comment]
@entonbiba we have no problems, but @alittlebitweird

**Comment by sundayz** [comment]
I had this problem too, try the solution in #2014

you can create your own Audio object and set crossOrigin = 'anonymous' which seems to let chrome and firefox load cross origin audio.
