### ISSUE TITLE
Sometimes peaks are drawn twice, because of requestAnimationFrame timing

### ISSUE THREAD

**Issue by lorenzos** [katspaugh/wavesurfer.js#1884]
While testing semi-transparent bars (i.e. `waveColor: '#FFFFFF55'`) in a playlist context, I noticed they were more opaque at random times when loading a new track. Turns out they're rendered twice, one on top of the other, suggesting something isn't right in the clearing process.

Upon further investigation, I saw that for some reason [`clearWave`](https://github.com/katspaugh/wavesurfer.js/blob/master/src/drawer.multicanvas.js#L262) and [`drawBars`](https://github.com/katspaugh/wavesurfer.js/blob/master/src/drawer.multicanvas.js#L279) are called twice. The intended order of execution should be, tracing calls, something like:

* `clearWave` → `drawBars` → `clearWave` → `drawBars`

But `drawBars` is wrapped inside a `requestAnimationFrame` (via [`prepareDraw`](https://github.com/katspaugh/wavesurfer.js/blob/master/src/drawer.multicanvas.js#L460)) and `clearWave` is not. So it may happens that `drawBars` gets delayed, resulting in a double draw:

* `clearWave` → `clearWave` → `drawBars` → `drawBars`

I managed to patch it using `requestAnimationFrame` for `clearWave` too in [`drawer.multicanvas.js:262`](https://github.com/katspaugh/wavesurfer.js/blob/master/src/drawer.multicanvas.js#L262):

```js
clearWave() {
    util.frame(() => {
        this.canvases.forEach(entry => entry.clearWave());
    })();
}
```

Now my bars never get more opaque, however:

1. It's not clear why `clearWave` and `drawBars` are called twice in the first place. ~~May also be something wrong in my specific application.~~ I checked the playlist example here, and the calls are the same. However `requestAnimationFrame` never causes a sufficient delay for the issue to occur. It may be that in my application I use it for other stuff too, while the example is pretty clean instead.

2. I'm not 100% sure wrapping `clearWave` in `requestAnimationFrame` is without any side effects.

**Wavesurfer.js version(s):** Latest from NPM: 3.3.1
**Browser and operating system version(s):** Firefox 74.0 on Ubuntu 19.10

**Comment by thijstriemstra** [comment]
Thanks for investigating this and providing details.

> It's not clear why clearWave and drawBars are called twice in the first place.

This sounds like a bug. I assume the tests don't fail with your change? Can you make a pull request so we can take a look @lorenzos?

**Comment by lorenzos** [comment]
I not 100% sure it's a bug; I just traced the calls, but it's difficult to understand the whole picture. I'll try running the tests and making a PR as soon as I have same spare minutes. Thanks for the interest.

**Comment by thijstriemstra** [comment]
> I noticed they were more opaque at random times when loading a new track. 

What happened if you loaded 4 tracks, did it still get called twice or did it draw 4 times?

**Comment by lorenzos** [comment]
I load each track at a time, in a playlist-like app. Every time a new track is loaded, `clearWave` always get called, so there's no way more than 2 waveforms (which are always the same) are drawn on top of each other.
