### ISSUE TITLE
time marker and EDGE support

### ISSUE THREAD

**Issue by adamiusz** [katspaugh/wavesurfer.js#1885]
Is going to style a thin line that moves with time on wave form?

How to make wave form appear in Edge browser?

**Comment by thijstriemstra** [comment]
See #1761 

marking this as a duplicate.

**Comment by adamiusz** [comment]
Thanks for link, but how i can change style for thin line that moves with time on wave form?

**Comment by thijstriemstra** [comment]
Use the `cursorColor` option. See https://wavesurfer-js.org/docs/options.html

**Comment by adamiusz** [comment]
Thank You! Can too change width?

**Comment by thijstriemstra** [comment]
Read the documentation, I already linked it for you.

**Comment by adamiusz** [comment]
It's really nice! Thank You.

**Comment by adamiusz** [comment]
Can wavesurfer.js work in Edge? I checked the post above and found no clear information. Can I have a link to solve the problem or is the problem still unsolved?

If I open https://wavesurfer-js.org/ in Edge, unfortunately the waveform is not displayed.
