### ISSUE TITLE
exportImage() - TypeError: this.drawer.getImage is not a function

### ISSUE THREAD

**Issue by robert8888** [katspaugh/wavesurfer.js#1886]
exportImage() function call drawer.getImage(), but drawer object dos't have function getImage();
drawer.canvas and drawer.muliticanvas have it but it seems that on layer drawer is not connected.

**Comment by thijstriemstra** [comment]
@robert8888 can you a supply a simple example that shows how to reproduce this problem?

**Comment by aburai** [comment]
i think you try to use the function to early. `wavesurfer.drawer.getImage()` exists and works.

**Comment by thijstriemstra** [comment]
no response, closing.
