### ISSUE TITLE
wavesurfer.backend.getPeaks is returning an empty array

### ISSUE THREAD

**Issue by claudioemmanuel** [katspaugh/wavesurfer.js#1891]
@thijstriemstra and @x5engine 
hi, i have a similar problem, i`m using the following library

> 
> <script src="https://cdnjs.cloudflare.com/ajax/libs/wavesurfer.js/1.2.3/wavesurfer.min.js"></script>

below is my code where i was returning the audio peaks in an interval, 3 days ago it was working normally, until yesterday it was working normally,

today it just stopped returning some value and is returning an empty array

>        <script>
>       $(document).ready(function () {
>
>         var wavesurfer = WaveSurfer.create({
>           container: document.querySelector('#waveform'),
>           backend: 'MediaElement',
>           waveColor: 'black',
>           progressColor: 'gray',
>         });
> 
>         wavesurfer.load('http://ia902606.us.archive.org/35/items/shortpoetry_047_librivox/song_cjrg_teasdale_64kb.mp3');
> 
>         wavesurfer.on('ready', function () {
> 
>           var length = 300;
>           var start = 0;
>           var end = 300;
> 
>           console.log(wavesurfer.backend.getPeaks(length, start, end));
> 
>         });
> 
>       });
>     </script>

could someone tell me what am i doing wrong? I spent 6 hours today trying to solve it and I couldn't

how should i install or import the library to use it? thank you, i'll wait

_Originally posted by @claudioemmanuel in https://github.com/katspaugh/wavesurfer.js/issues/1311#issuecomment-604701510_

**Comment by thijstriemstra** [comment]
Try using the latest version: `<script src="https://unpkg.com/wavesurfer.js"></script>`

**Comment by claudioemmanuel** [comment]
@thijstriemstra 
even including the minified script: `<script src="https://unpkg.com/wavesurfer.js"></script>` the problem remains

below is my code where i was returning the audio peaks in an interval, 3 days ago it was working normally, until yesterday it was working normally,

today it just stopped returning some value and is returning an empty array

if i remove the backend option from the setup it does not render my audio on the screen

```
  var wavesurfer = WaveSurfer.create({
      container: document.querySelector('#waveform'),
      // backend: 'MediaElement',
      waveColor: 'black',
      progressColor: 'gray',
    });
```
I will explain my application better, I am sending a file through a form so I pass the file (path)

`$audio = asset('original/'. $file->getClientOriginalName ());`

to the return view

`return view ('result')-> with('audio', $audio);`

and i'm rendering it this way

```
  $(document).ready(function() {

    var wavesurfer = WaveSurfer.create({
      container: document.querySelector('#waveform'),
      backend: 'MediaElement',
      waveColor: 'black',
      progressColor: 'gray',
    });

    var audioElement = document.createElement('audio')

    audioElement.autoplay = true
    audioElement.loop = true
    audioElement.crossOrigin = 'anonymous'
    audioElement.src = '{!! $audio !!}'

    wavesurfer.load(audioElement);

    wavesurfer.on('ready', function() {

      var length  = wavesurfer.getDuration();
      var start   = 0;
      var end     = length;

      console.log(wavesurfer.backend.getPeaks(length, start, end));

    });

  });
```
and in this way, using the backend when creating the WaveSurfer the waves are rendered on screen, if I remove them, the peaks appear but the waves on the screen do not

**Comment by thijstriemstra** [comment]
> below is my code where i was returning the audio peaks in an interval, 3 days ago it was working normally, until yesterday it was working normally,

Ok well, that's an issue on your side I guess. Did you use git? check what changes you made since then..

**Comment by claudioemmanuel** [comment]
> Ok well, that's an issue on your side I guess. Did you use git? check what changes you made since then..

there was no change, I'm using git but there was no change, as I informed the code was working for 2 days, yesterday stopped working and return the values in getPeaks ()

if you have a code snippet and the cdn`s that i can use as an example of returning the audio peaks, i would be grateful
