### ISSUE TITLE
exportPCM Wrong method return type

### ISSUE THREAD

**Issue by azimbialiev** [katspaugh/wavesurfer.js#1896]
I'm actually using wavesurfer.js@3.3.1 with Typescript 3.8
VS Code suggest me that wavesurfer.exportPCM() is not an async function

`WaveSurfer.exportPCM(length: number, accuracy: number, noWindow?: boolean | undefined, start?: number | undefined): string`

But the official documentation says 

`exportPCM(length: number, accuracy: number, noWindow: boolean, start: number, end: number): Promise`

**Comment by thijstriemstra** [comment]
> But the official documentation says

Where did you find this, can you link it?

**Comment by aburai** [comment]
since 3.3.0  `wavesurfer.exportPCM` now accepts an optional `end` argument and returns
  a Promise (#1728)

the doc is correct, but wavesurfer has no typings file so i think vscode do not understand the jsdoc

    /**
     * Exports PCM data into a JSON array and opens in a new window.
     *
     * @param {number} length=1024 The scale in which to export the peaks
     * @param {number} accuracy=10000
     * @param {?boolean} noWindow Set to true to disable opening a new
     * window with the JSON
     * @param {number} start Start index
     * @param {number} end End index
     * @return {Promise} Promise that resolves with array of peaks
     */

**Comment by thijstriemstra** [comment]
> since 3.3.0 wavesurfer.exportPCM now [...] returns a Promise

Closing as fixed.
