### ISSUE TITLE
Is there a way to control the attack of the playback?

### ISSUE THREAD

**Issue by alittlebitweird** [katspaugh/wavesurfer.js#1897]
Would love to be able to ramp the volume of playback to reduce clicks of starting/stopping mid waveform.

**Comment by aburai** [comment]
Did you use `wavesurfer.setVolume()`? I do not understand why you must start/stop?

**Comment by marizuccara** [comment]
If I understood correctly what you meant, and if you're using the `WebAudio` or `MediaElementWebaudio` backend, maybe you can use the `AudioParam.linearRampToValueAtTime(value, endTime)` method, applying it to the `GainNode`.
