### ISSUE TITLE
Safari not playing mp3s from our S3 bucket, others (Chrome etc) being inconsistent

### ISSUE THREAD

**Issue by larryq** [katspaugh/wavesurfer.js#1901]
Hi everyone,

We're working with a client that is using wavesurfer and is having trouble playing files from our Amazon S3 bucket.  We've been testing with version 3.3.1 and  while things work in Chrome and Firefox --for the most part-- unfortunately Safari (latest version) is just not playing them.

What do I mean by 'for the most part'?  Well, if we set some breakpoints in wavesurfer, such as at the fetch() and play() methods and then continue, the mp3s appear to work fine.  But running without any breakpoints (and thereby slowing things down) we don't hear any music.  Monitoring the network calls, we see that the mp3s are downloaded successfully, and the wavesurfer 'ready' event is fired, but calling `play()` thereafter doesn't work.

I've got a short JSFiddle here that demonstrates what we're trying to do:

https://jsfiddle.net/37ns516q/1/

As you can see in the fiddle, we've wrapped the wavesurfer code in a jQuery document.ready() function in the off chance that the document hasn't quite loaded before we try anything with wavesurfer.  That didn't seem to help.  In looking at how we're using wavesurfer, the order of calls, is there something we're missing?  

I should note too that we have a couple of mp3s in the fiddle, of different sizes.  The first, 'birthday' one is only 365k and works more often than the other two, which are 11mb Billie Eilish clips, the c.rdnt.com link pointing to our CDN  while the other is aimed directly at our S3 bucket.  Possible the file size is the culprit here? 

Originally we had some CORS issues but have opened things up, all the Allow-
Access-Control settings are in shape on our bucket, and if we simply embed an `<audio>` tag with the mp3's path on the page we have zero CORS issues, the file plays fine in JSFiddle.  This is really weird and we'd love it anyone has some tips we can try.  Thanks!

[UPDATE] after more testing, it *appears* the wavesurfer library, on Safari only, has trouble playing our mp3 files.  They work fine on Chrome and Firefox, and playing our mp3s in Safari by simple use of an `<audio>` tag works fine.  Does this ring a bell with anyone, possible codec incompatibilities in Safari with your library?...

**Comment by aburai** [comment]
A file embed in an audio tag is streamed and CORS is not relevant.
When you use a link to your bucket, the file is downloaded via ajax and CORS is used.

Ensure your request did not timedout, check your settings on AWS.

Sorry, but i could not try anything with Safari. I recommend to set a breakpoint on the load method and step into wavesurfer.

**Comment by larryq** [comment]
Thanks for your help.  The library works on these mp3 files when used in Chrome and Firefox, but not Safari.  So I don't think it's an AWS or CORS issue from that.  

What we'd really like to know is if anyone has encountered this problem with Safari, where the library is 'pickier' with certain encodings than on Chrome and FF?

**Comment by osheroff** [comment]
Safari disables auto-play of audio by default.  I'm not sure if this is your issue or not, but it's generally not allowed to just start audio playing outside of a `click()` event.  try moving the call the `play()` inside of a `click() handler`

**Comment by osheroff** [comment]
the other question:  how are you instantiating wavesurfer?  what backend are you using?
