### ISSUE TITLE
Style/background color issue after upgrading chrome to version 81

### ISSUE THREAD

**Issue by hot4mix** [katspaugh/wavesurfer.js#1908]
### Wavesurfer.js version(s):
3.3.1 and 3.3.2

### Browser and operating system version(s):
Chrome Version 81.0.4044.92 (Official Build) (64-bit) / Windows 10 1909

### Code needed to reproduce the issue:
```
mounted() {
			this.wave = WaveSurfer.create({
				container: this.$refs.waveform,
				waveColor: '#3686c9',
				progressColor: '#C06C84',
				barWidth: 2,
				cursorColor: 'transparent',
			});

			this.wave.load(this.url);
```

everything was working just fine before chrome updated to 81 last night
this is the appearance i'm after, and as you see it works fine on chrome 80, i downgraded to test that it works.
![image](https://user-images.githubusercontent.com/27101717/78855044-287dd280-7a23-11ea-9bdc-65bfd4155fbe.png)

on chrome 81 when i keep the cursor color set to "transparent", it doesn't show any progress color at all.
![image](https://user-images.githubusercontent.com/27101717/78855203-94603b00-7a23-11ea-852e-187561355a04.png)

if i remove the cursor color as in default or set it to any other color, the whole waveform gets a black background.
![image](https://user-images.githubusercontent.com/27101717/78855293-c96c8d80-7a23-11ea-82c2-06d5b370743d.png)

**Comment by sundayz** [comment]
Can confirm this happens on Chrome as of very recently, doesn't seem to happen in Firefox.

**Comment by hot4mix** [comment]
Yeah, tried with firefox and safari on both windows and mac, but here's the weird thing, is it doesn't happen on latest chrome on Mac.

**Comment by karolpiczak** [comment]
Same issue here on Chrome 81.0.4044.92 / Windows for a couple of days.

**Comment by Dr-Snuggles** [comment]
Me 2

**Comment by DarrenChowles** [comment]
Experiencing the same issue in Chrome 81. No problems in Firefox.

**Comment by thijstriemstra** [comment]
Here are the changes for Chrome 81: https://www.chromestatus.com/features#milestone%3D81

Nothing there seems to be related to this issue though..

**Comment by thijstriemstra** [comment]
@hot4mix did you also try `rgba(0,0,0,0)` instead of `transparent`?

**Comment by PetrKnedlik** [comment]
yeah, same issue Chrome 81. No problems in Firefox.

**Comment by thijstriemstra** [comment]
can you see if it's related to this commit: https://github.com/katspaugh/wavesurfer.js/commit/d0187a9533d9492e950e31cd547583293e6a241a

try setting the `drawingContextAttributes.desynchronized` option to `false`:

```javascript
drawingContextAttributes: {
             // Boolean that hints the user agent to reduce the latency
             // by desynchronizing the canvas paint cycle from the event
             // loop
             desynchronized: false
},
```

**Comment by karolpiczak** [comment]
Switching off `desynchronized` painting seems to fix the issue.

**Comment by thijstriemstra** [comment]
that's good to hear @karolpiczak. If more people can confirm this, then we can make a new release where this option is `false` by default (unless someone has a better suggestion).

**Comment by hot4mix** [comment]
> @hot4mix did you also try `rgba(0,0,0,0)` instead of `transparent`?
i did, and it didn't help.

> try setting the `drawingContextAttributes.desynchronized` option to `false`:
that did the trick, everything looking fine like expected now.

**Comment by DarrenChowles** [comment]
```js
drawingContextAttributes: {
    desynchronized: false
}
```

Worked for me. Thanks, @thijstriemstra

**Comment by mohammadnt** [comment]
I have same issue on chrome in 7.0.0-beta.6 version with angular. could not tested lower version. the issue does not exists on firefox
