### ISSUE TITLE
Elan throws error if tiers is not provided

### ISSUE THREAD

**Issue by bhogan-mitre** [katspaugh/wavesurfer.js#1910]
Elan parameter `tiers` is [documented as optional](https://wavesurfer-js.org/api/typedef/index.html#static-typedef-ElanPluginParams), although it throws an error if it is not provided.

The problematic segment is this [loop](https://github.com/katspaugh/wavesurfer.js/blob/master/src/plugin/elan.js#L235-L242) over `indeces` that refers to `this.params.tiers`:
```
        indeces.forEach(index => {
            const tier = tiers[index];
            const th = document.createElement('th');
            th.className = 'wavesurfer-tier-' + tier.id;
            th.textContent = tier.id;
            th.style.width = this.params.tiers[tier.id];
            headRow.appendChild(th);
        });
```

### Wavesurfer.js version(s):
Latest via https://unpkg.com/wavesurfer.js

### Browser and operating system version(s):
Chrome 81.0.4044.92 on macOS 10.15.4

### Code needed to reproduce the issue:

Borrow from [this example](https://wavesurfer-js.org/example/elan/index.html), but instead of:
```
            WaveSurfer.elan.create({
                url: 'transcripts/001z.xml',
                container: '#annotations',
                tiers: {
                    Text: true,
                    Comments: true
                }
            }),
```

Use undefined `tiers`:
```
            WaveSurfer.elan.create({
                url: 'transcripts/001z.xml',
                container: '#annotations',
                tiers: undefined
            }),
```

**Comment by thijstriemstra** [comment]
> Elan parameter tiers is documented as optional, although it throws an error if it is not provided.

If it's not optional, feel free to open a pull request to update the documentation. If you want to make it optional, go ahead and open a pull request. Thanks!

**Comment by bhogan-mitre** [comment]
PR merged, closing this.
