### ISSUE TITLE
MediaElementWebAudio destroy method

### ISSUE THREAD

**Issue by marizuccara** [katspaugh/wavesurfer.js#1923]
Hi, since MediaElementWebAudio backend inherits from MediaElement backend, when destroy method is called, it calls the MediaElement backend destroy method, which destroy the media audio tag. But, since MediaElementWebAudio uses WebAudio features, it should be better if we destroy also web audio related stuffs, as disconnecting audio nodes, close audio context, destroy it, etc (the same methods which are used in the WebAudio backend destroy).

**Comment by thijstriemstra** [comment]
Sounds good. Please open a pull request if you have a possible solution (without duplicating a lot of code).
