### ISSUE TITLE
On Iphone Volume control mute is not working

### ISSUE THREAD

**Issue by namitgarg** [katspaugh/wavesurfer.js#1931]
Hey when playing on iphone safari browser volume control , mute are not working , i have tested the below page https://wavesurfer-js.org/example/mute/index.html

**Comment by sundayz** [comment]
You need to use the `WebAudio` or `MediaElementWebAudio` backends on iOS safari.


iOS Safari doesn't allow setting volume or playback rate with the default `MediaElement` backend
