### ISSUE TITLE
if click next play button stop current and play next

### ISSUE THREAD

**Issue by adamiusz** [katspaugh/wavesurfer.js#1933]
At the moment I have wavesurfers in the foreach loop and how can I make all the other wavesurfers stop after clicking the next play button? These are individual objects created, not a playlist.

**Comment by marizuccara** [comment]
Maybe you can keep track (e.g in a key-value map) of the various wavesurfers created and of their playback state, so if you click a play button, you update your map, and basing of its values, you stop all the wavesurfers with the negative playback state?

**Comment by adamiusz** [comment]
I create standard wavesurfer:

```
jQuery('.song').each(function(){

            var one =  jQuery(this).attr("container"); 
            var two = jQuery(this).attr("value");

       var Spectrum = WaveSurfer.create({
                container: one,
                progressColor: "#ff5533",              
       });

      Spectrum.on("ready", function(){ 
                  
              jQuery("body").on("click", "#button" + two, function(e) { 

                      Spectrum.playPause();
 
               });
              
       });


 });
```

Where var file is div id contains wavesurfer 

Can please any code, because i dont know how make it?

**Comment by marizuccara** [comment]
share a codesandbox with your code, it's simpler to debug it

**Comment by adamiusz** [comment]
I can't create codesandbox. It's easy, in my code you can see that for each created div.song I create a new object wavesurfer and if one wavesurfer is running and I click on another in the play button, the previous one should stop.

**Comment by marizuccara** [comment]
I don't understand why you call different instances with same name, `Spectrum`.
Btw, you can do that when you create a new wavesurfer instance, you assign to it an id, e.g `SpectrumX.id = myID`. Then, always in a for loop, in a `var myMap = {}` variable that you declared before the loop, you populate it, with `myId` as key (so you know what wavesurfer instance have to play), and a boolean which call you that have to be in pause, e.g `myMap[myID] = false`. Then, when you click one of the buttons (better if you assign them different ids), you change the values of your map, and basing on it, you know which of instances of wavesurfer have to play or not.

**Comment by adamiusz** [comment]
Can you give a sample or structure how to build such a code?

**Comment by adamiusz** [comment]
I have question. How stop wavesurfer if I know only container name, because i dont know how i can make unique var spectrum_name ??

```
            var spectrum_name = WaveSurfer.create({
                container: file,
                height: 40,
                barHeight:2,
                waveColor: '#ffffff',
            });
```

if i make something like this:

```
            var spectrum_name[34] = WaveSurfer.create({
                container: file,
            }
```

Then i get error in console: `unexpected token: [`

**Comment by adamiusz** [comment]
Thanks for help
