### ISSUE TITLE
i want to draw my wav file linear method

### ISSUE THREAD

**Issue by alimatinfar** [katspaugh/wavesurfer.js#1935]
hi
i want to draw my wav file In the form of bottom picture but drawn in the form of top picture

![image](https://user-images.githubusercontent.com/46160045/81064571-265a4700-8eef-11ea-8b31-bf8cf1246c5e.png)

What changes should I make?

**Comment by thijstriemstra** [comment]
> What changes should I make?

To what? Can you share that code?

**Comment by thijstriemstra** [comment]
no feedback, closing.
