### ISSUE TITLE
how to resample my wav file from 2000 Hz to 4000 Hz

### ISSUE THREAD

**Issue by alimatinfar** [katspaugh/wavesurfer.js#1937]
I have a wav file on the server with a sample rate of 2000 Hz and the browser does not support this sample.
Is there a way to change the sample rate of this wav file to 4000 Hz in this library to display it in the browser?

**Comment by thijstriemstra** [comment]
> Is there a way to change the sample rate of this wav file to 4000 Hz in this library

No. Use `ffmpeg` instead.
