### ISSUE TITLE
Android - app crashes after resume

### ISSUE THREAD

**Issue by alefz3r0** [katspaugh/wavesurfer.js#1939]
Hi, I am (successfully) using Wavesurfer in a ionic/angular/cordova project, it works really nice.

However, when i switch to another app (then pausing my app) and then come back to my app, the app crashes without logging errors.

Is there any action I should do on pause and on resume, to avoid this?

Thanks

**Comment by thijstriemstra** [comment]
No idea. Could be anything.

**Comment by alefz3r0** [comment]
I tried to call this.wavesurfer.destroy() on pause, but still it didn't work

It turns out that I needed to also call this.wavesurfer.empty() - that seems to solve the issue, but I don't know why
