### ISSUE TITLE
Spectrogram

### ISSUE THREAD

**Issue by luojuan5** [katspaugh/wavesurfer.js#1944]
Hello, I tried to add multiple spectrograms in the browser, but only one can be displayed. What is the possible reason for this? Hope to get your reply, thanks

![010101](https://user-images.githubusercontent.com/44315066/81951187-6fb93d80-9637-11ea-922f-bf198d3ea96d.png)

**Comment by thijstriemstra** [comment]
can you make a simple example that reproduces the problem and paste it here?

**Comment by luojuan5** [comment]
Thanks, this is the code, and the prompt in google browser
HandleVoice.vue：
<template>
  <div>
    <div id="waveform" ref="waveform" style="width:100%"></div>
    <div id="waveSpectrogram" ref="waveSpectrogram" style="width:100%"></div>
  </div>
</template>

<script>

import WaveSurfer from "wavesurfer.js";
import Timeline from "wavesurfer.js/dist/plugin/wavesurfer.timeline.js";
import SpectrogramPlugin from "wavesurfer.js/dist/plugin/wavesurfer.spectrogram.js";

export default {
  data() {
    document.addEventListener("DOMContentLoaded", function() {
      // Load a colormap json file to be passed to the spectrogram.create method.
      WaveSurfer.util
        .fetchFile({ url: "../../../hot-colormap.json", responseType: "json" })
        .on("success", colorMap => {
          initAndLoadSpectrogram(colorMap);
        });
    });
    return {
      wavesurfer: null,
      waveSpectrogram: null
    };
  },
   watch: {
    voiceData: {
      deep: true,
      handler(val) {
        this.setOptions(val)
      }
    }
  },
  mounted() {
    this.$nextTick(() => {
      console.log(WaveSurfer);
      this.wavesurfer = WaveSurfer.create({
        container: this.$refs.waveform,
        waveColor: "#409EFF",
        progressColor: "blue",
        backend: "MediaElement",
        mediaControls: true,
        audioRate: "1",
        //
        plugins: [
          SpectrogramPlugin.create({
            container: "#waveSpectrogram",
            labels: true,
            fftSamples: 512,
            colorMap: this.colorMap
          })
        ]
      });
      // 
      this.wavesurfer.load(require("./../../../assets/voice/demo.wav"));
    });
  },
  methods: {
    playMusic() {
      //
      this.wavesurfer.playPause.bind(this.wavesurfer)();
    },
  }
};
</script>

and index.vue：
<div style="float:left; height:100%; width:25%;" v-for="item in 4" :key="item">
              <el-col style="background:#fff;padding:16px 16px 0;margin-bottom:32px;">
                <voice />
              </el-col>
            </div>
<script>
import Voice from "./components/HandleVoice";
export default {
  components: {
    Voice
  },
}
<script>
![01](https://user-images.githubusercontent.com/44315066/82003902-20edc100-9694-11ea-8739-c59dca526cec.png)

**Comment by luojuan5** [comment]
Thanks, this is the code and the prompt in google browser
HandleVoice.vue：
![0001](https://user-images.githubusercontent.com/44315066/82004221-f18b8400-9694-11ea-9d1f-1d0238532d81.png)
![0002](https://user-images.githubusercontent.com/44315066/82004261-ffd9a000-9694-11ea-814f-90b138b21b3b.png)
![0003](https://user-images.githubusercontent.com/44315066/82004279-0b2ccb80-9695-11ea-9332-22655d83ee2f.png)
![0004](https://user-images.githubusercontent.com/44315066/82004286-0ec05280-9695-11ea-9ab2-e6b67bcf0f66.png)

**Comment by luojuan5** [comment]
"wavesurfer.js": "^3.3.3"

**Comment by thijstriemstra** [comment]
you're `require`-ing a .wav file? why? please load it using a regular string url and see if that helps.

**Comment by luojuan5** [comment]
Thank you, it can be displayed normally now

**Comment by thijstriemstra** [comment]
great!
