### ISSUE TITLE
Custom time format in regions tootip

### ISSUE THREAD

**Issue by jscrusader** [katspaugh/wavesurfer.js#1948]
It would be nice to have a way to provide custom function that will generate text displayed on region hower. 

Currently there is no way to do so and region tooltip always show m:ss format

**Comment by thijstriemstra** [comment]
the cursor plugin already provides this (`timeformatCallback` something), would be nice if regions implements this as well. Pull requests welcome @jscrusader

**Comment by jscrusader** [comment]
@thijstriemstra sure thing. Here it is https://github.com/katspaugh/wavesurfer.js/pull/1949
