### ISSUE TITLE
Cut section and reload

### ISSUE THREAD

**Issue by aleczratiu** [katspaugh/wavesurfer.js#1952]
Is there a way to cut a section from sound and reload a wave ? 
Example a sound with a duration of 1000ms I try to cut from **start: 0ms** and **end: 500ms** and reload this cut section.

**Comment by thijstriemstra** [comment]
yes, put audio data in Blob, manipulate it and load into wavesurfer using `loadBlob`.

**Comment by peterj35** [comment]
@aleczratiu did this work for you?
