### ISSUE TITLE
Unable to display 2 channel waveform when externally loading peaks

### ISSUE THREAD

**Issue by priitserk** [katspaugh/wavesurfer.js#1954]
Amazing work what you have done! 

Can you please elaborate, if what I am trying to achieve is achievable at all at the moment? The description is below.

* https://wavesurfer-js.org/example/split-channels/index.html
This works like charmed! And everything else is okey with small files. 

But I'm dealing with 100mb+ files and for that I am using audiowaveform to generate peaks. I'm loading it in with:

```
this.wave.load('http://localhost:4200/assets/' + mp3, peaks.data);
```
and initializing wavesurfer:
```
  private initWaveSurfer() {
    this.wave = WaveSurfer.create({
      container: '#waveform',
      backend: 'MediaElementWebAudio',
      pixelRatio: 1,
      height: 80,
      splitChannels: true,
      normalize: true,
      minimap: true,
```
Waveform is displayed nicely, media plays nicely but there's only one merged wave. How can I still have two waveforms separately for each channel as in the example? Is this possible?

* [root@hop build]# ./audiowaveform -i 2_channel.mp3 -b 8 -o 2_channel.json --split-channels
* [root@hop build]# python scale.py 2_channel.json

Unfortunately I cant execute the following command:
this.wavesurfer.exportPCM();
Promise {<resolved>: "[null,null]"}
__proto__: Promise
[[PromiseStatus]]: "resolved"
[[PromiseValue]]: "[null,null]"

Results in exception:
unpkg.com/wavesurfer.js@3.3.3/dist/wavesurfer.js:5240 Not allowed to navigate top frame to data URL: data:application/json;charset=utf-8,%5Bnull%2Cnull%5D

What I wanted to do is to export PCM to see how the different channels are described in the json (as in the same split channel example thats on your webpage). Maybe I just have to write a wrapper to audiowaveform output to format it correctly.

Can you please give advice and maybe also post an example of this.wavesurfer.exportPCM(); when there is a 2 channel mp3 in play.

Thank You

**Comment by thijstriemstra** [comment]
> Unfortunately I cant execute the following command:

try:

```
this.wavesurfer.exportPCM().then(function(result) { console.log(result); });
```

**Comment by priitserk** [comment]
Hi

Unfortunately that did not help (With latest chrome):

1)https://wavesurfer-js.org/example/split-channels/index.html
2) F12
3) Console: this.wavesurfer.exportPCM().then(function(result) { console.log(result); });

Results in
VM149:1 [null,null]
Promise {<resolved>: undefined}__proto__: Promise[[PromiseStatus]]: "resolved"[[PromiseValue]]: undefined

**Comment by thijstriemstra** [comment]
`[null,null]` is bad, it's buggy indeed.

**Comment by guisha** [comment]
请问这个如何解决的，我也碰到了这个问题

**Comment by guisha** [comment]
How to solve this problem, I also encounter this problem

**Comment by entonbiba** [comment]
@priitserk @Guisch yea it's a pretty bad bug for the `splitChannels` I'll have a look and see what's the best way to fix it.

**Comment by entonbiba** [comment]
after some testing `backend.getPeaks()` without any provided parameters returns NaN as seen below. we might want to make it return the full peaks data? If length is provided it will return the proper channel peaks. `wavesurfer.backend.getPeaks(4096,0,10)`

`splitChannels: true` `wavesurfer.backend.getPeaks()`
![image](https://user-images.githubusercontent.com/5193884/105786477-27cf1200-5f4b-11eb-80f6-7e5f99cb3fb9.png)

`splitChannels: true` `wavesurfer.backend.getPeaks(4096,0,10)`
![image](https://user-images.githubusercontent.com/5193884/105786844-cf4c4480-5f4b-11eb-9fe9-04debdb6c903.png)

**Comment by entonbiba** [comment]
could possibly be an issue with this line where `end` doesn't have a default or the length is invalid when exportPCM is called from backend.
https://github.com/katspaugh/wavesurfer.js/blob/d2005178dbd2deeb243b5362af1cafd1f3b29d66/src/wavesurfer.js#L1622

``` javascript
    exportPCM(length, accuracy, noWindow, start, end) {
        length = length || 1024;
        start = start || 0;
        accuracy = accuracy || 10000;
        noWindow = noWindow || false;
        const peaks = this.backend.getPeaks(length, start, end);
```

**Comment by guisha** [comment]
I've solved it. I've made a loop for it：

key: "exportPCM",
				value: function(e, t, r, n) {
					e = e || 1024, n = n || 1024, t = t || 1e4, r = r || !1;
					var list = this.backend.getPeaks(e, n);
					var arr = [];
					for(var i = 0;i<list.length;i++){
						arr.push([].map.call(list[0], function(e) {
							return Math.round(e * t) / t
						}));
					}
					var s = JSON.stringify(arr);
					return r || window.open("data:application/json;charset=utf-8," + encodeURIComponent(s)), s
				}

**Comment by entonbiba** [comment]
great, open a pull request for this?

**Comment by guisha** [comment]
Yes, get the JSON value and display it in the foreground；
Change one of the errors above；


key: "exportPCM",
				value: function(e, t, r, n) {
					e = e || 1024, n = n || 1024, t = t || 1e4, r = r || !1;
					var list = this.backend.getPeaks(e, n);
					
					var arr = [];
					for(var i = 0;i<list.length;i++){
						arr.push([].map.call(list[i], function(e) {
							return Math.round(e * t) / t
						}));
					}
					var s = JSON.stringify(arr);
					return r || window.open("data:application/json;charset=utf-8," + encodeURIComponent(s)), s
				}
