### ISSUE TITLE
getduration returns wrong time

### ISSUE THREAD

**Issue by mkariti2** [katspaugh/wavesurfer.js#1955]
Hi there,
I'm using version 1.2.2 with aac on 'MediaElement'.
For some reason, Firefox returns the wrong time while chrome is acting ok.
On chrome, I get 177 seconds while ff will return 2052 seconds for the same file.
Any idea why this might happen?
Many thanks
mkariti

**Comment by marizuccara** [comment]
Hi @mkariti2 , maybe this link can be useful for you. I think that is a compatibility issue with specific browser..

https://support.mozilla.org/en-US/kb/html5-audio-and-video-firefox

**Comment by mkariti2** [comment]
@marizuccara thanks for the reply. when I'm using the default option of WebAudio all is fine so i guess it is not a compatibility option.

**Comment by thijstriemstra** [comment]
> I'm using version 1.2.2

Right. This is an ancient version. Why are you using this?? Please try the latest version (3.x) and re-open if this issue still exists.

**Comment by mkariti2** [comment]
Hi there, 
Many thanks for your quick reply.
Ive upgraded it to 3.3.3 and the issue is still persisted.
Same issue with the same browser. 
Do I need to open a new bug or can you reopen the current one?

**Comment by marizuccara** [comment]
> @marizuccara thanks for the reply. when I'm using the default option of WebAudio all is fine so i guess it is not a compatibility option.

Hi, WebAudio don't use HTML5 audio tag as source, but MediaElement or MediaElementWebAudio use it. So it is possible that is a compatibility issue with this MediaType.
