### ISSUE TITLE
regions plugin: couple of bugs report 

### ISSUE THREAD

**Issue by Aparus** [katspaugh/wavesurfer.js#1963]
I'm sorry I closed check list "to-do before open issue" once, and I can't reproduce it... 
`wavesurfer.js version is 3.3.3`

I faced with this strange behavior. 
1) If I init waveform and set regions with { resize: false, drag: false } on initialization, then I can't change those fields by region.update() in the future. For now I solve it by don't touching  {resize, drag} on init, and update them all just after initialization. 
2) if I do region.update( { resize: false } ) - cursor 'resize' still appears upon the region (what is not expected).  But if I do this on init, cursor 'resize' doesn't appear, what is expected (good). 

Proposal:
It will be great to have enable/disable for Drag and Resize - affecting all regions (existing and newly created). Like enable/disable DragSelection. 

I hope it will be helpful for you. If you want to see my app where I use Wavesurfer with Regions, please visit [frazy.me](frazy.me) - platform for creating and hosting language learning materials.

Thank you for your great library.

**Comment by thijstriemstra** [comment]
Did you look through the old ticket reports and find similar requests?

**Comment by Aparus** [comment]
> Did you look through the old ticket reports and find similar requests?

Yes. Did I missed something?
