### ISSUE TITLE
automate latest release update on github

### ISSUE THREAD

**Issue by thijstriemstra** [katspaugh/wavesurfer.js#1972]
Github is updating their interface and the latest release will be prominently visible, e.g. right bottom corner:

![Screenshot from 2020-06-17 22-50-22](https://user-images.githubusercontent.com/305679/84949140-0d97a080-b0ed-11ea-8f8d-a087ef9b2628.png)

The latest wavesurfer.js release is an ancient one from 2016, which is incorrect.

cc @katspaugh

**Comment by thijstriemstra** [comment]
I suppose pulling the latest release data from github using their API will also show this old release.

**Comment by katspaugh** [comment]
I suggest we do it manually for 4.0.0 and then eventually automate it via our build and the GitHub API.

**Comment by thijstriemstra** [comment]
> automate it via our build and the GitHub API.

There are github actions nowadays, maybe those can help here.
