### ISSUE TITLE
Cannot read property 'includes' of undefined

### ISSUE THREAD

**Issue by hunterphillips** [katspaugh/wavesurfer.js#1975]
Uncaught TypeError: Cannot read property 'includes' of undefined
    at e.fireEvent (observer.js:125)
    at HTMLUnknownElement.<anonymous> (region.js:349)

### Wavesurfer.js version(s):
https://unpkg.com/wavesurfer.js
https://unpkg.com/wavesurfer.js/dist/plugin/wavesurfer.regions.min.js

### Browser and operating system version(s):
Chrome 83, Windows 10

### Code needed to reproduce the issue:
```
<script src="https://unpkg.com/wavesurfer.js/dist/plugin/wavesurfer.regions.min.js"></script>

// example region
wavesurfer.addRegion({
		id: "pad-1",
		start: 1,
		end: 10,
		color: "blue",
});
```
### Use behaviour needed to reproduce the issue:
Error is produced on interactions with the wavesurfer regions UI
ex. hovering over a region

*edit - the initialized regions appear to load correctly.. but attempting to clearRegions() and load new produces the error above, and the new regions fail.

**Comment by ICYMYM** [comment]
I also encountered the same problem,  when I hover or click the region, will trigger this problem: 

```
observer.js:125 Uncaught TypeError: Cannot read property 'includes' of undefined
    at e.fireEvent (observer.js:125)
    at HTMLUnknownElement.<anonymous> (region.js:354)
```

**Comment by thijstriemstra** [comment]
this bug was introduced with pull request #1960

**Comment by vladbph** [comment]
same problem here as well.

**Comment by thijstriemstra** [comment]
Fixed in v4.0.1.

**Comment by ICYMYM** [comment]
@thijstriemstra 

This problem no longer occurs, but it seems that the region items cannot be clicked, the previous version region is clickable, could you check it?

**Comment by thijstriemstra** [comment]
> This problem no longer occurs, but it seems that the region items cannot be clicked, the previous version region is clickable, could you check it?

Please open a new ticket with all information, don't add it here.
