### ISSUE TITLE
Error thrown on region-created event

### ISSUE THREAD

**Issue by jsbroks** [katspaugh/wavesurfer.js#1982]
## Wavesurfer.js version(s):
4.0.0

### Browser and operating system version(s):
Chrome,Ubuntu

### Code needed to reproduce the issue:

Create an event listener for 'region-created', an error is thrown when a region is created. 'Cannot find 'includes' of undefined.'

Downgraded back to 3.3.3 , no issues.

**Comment by marizuccara** [comment]
Hi @jsbroks , solved with version 4.0.1
