### ISSUE TITLE
remove deprecated util.extend

### ISSUE THREAD

**Issue by thijstriemstra** [katspaugh/wavesurfer.js#1988]
`util.extend` is deprecated since v3.0.0.

**Comment by marizuccara** [comment]
If there won't be backward compatibility problems (since it was deprecated) I agree with removing it. I can open a PR..

**Comment by thijstriemstra** [comment]
It should've been removed in v4.0.0, but I'm fine with removing it in 4.1.0.

> I can open a PR..

Please do.
