### ISSUE TITLE
Wavesurfer with no audio

### ISSUE THREAD

**Issue by bknill** [katspaugh/wavesurfer.js#2004]
I know this is a contradiction in terms.. 

We're using Wavesurfer for some video editing software. We have the case where we have video files with no audio and still want to use the regions and timeline plugins with a known duration. 

I saw a few similar posts on this which suggested loading an empty array i.e. [0,0] but I'm not getting anything drawn. 

is there any other way to handle this?

**Comment by thijstriemstra** [comment]
> I saw a few similar posts on this which suggested loading an empty array i.e. [0,0] but I'm not getting anything drawn.

Can you show code you're using to do this?

**Comment by bknill** [comment]
`wavesurfer.load([0,0])` is what I tried but nothing was rendered.

**Comment by marizuccara** [comment]
Hi, the `load` method requires an audio source. If you have not audio, you could call these methods instead:

` wavesurfer.backend.setPeaks([0,0], 10);` 
` wavesurfer.drawBuffer();`

**Comment by bknill** [comment]
@marizuccara thats awesome thanks. 

I changed `wavesurfer.backend.explicitDuration = videoEl.duration` to get it to the right length as well thanks.

**Comment by bknill** [comment]
I can't get the timeline to initialise with this empty audio. Is there a way to hack that?

**Comment by marizuccara** [comment]
Hi, add  ` wavesurfer.fireEvent('ready');`
