### ISSUE TITLE
How to prevent a region handle from resizing beyond its opposite handle?

### ISSUE THREAD

**Issue by adityakrshnn** [katspaugh/wavesurfer.js#2008]
I wanted to know if there is any way to stop resizing when it touches its opposite handle. Attaching video.

![ezgif-4-32aa03ff4e72](https://user-images.githubusercontent.com/23035769/87847999-ebff2400-c8f9-11ea-80fa-642821f4fb0e.gif)

**Comment by marizuccara** [comment]
https://github.com/katspaugh/wavesurfer.js/pull/2002
