### ISSUE TITLE
Edgescroll does not work for the right edge

### ISSUE THREAD

**Issue by adityakrshnn** [katspaugh/wavesurfer.js#2011]
The edgescroll does not seem to work for the right edge. Attaching video.
![edgescroll_gif](https://user-images.githubusercontent.com/23035769/87923152-ad549f80-ca9a-11ea-8324-63c00a580142.gif)

**Comment by thijstriemstra** [comment]
duplicate of #2006?

**Comment by adityakrshnn** [comment]
Not a duplicate. I am talking about the automatic scroll that happens when you are dragging / resizing and reach the edge of the visible waveform.
