### ISSUE TITLE
[Question] [Regions plugin] How to get time from region-click?

### ISSUE THREAD

**Issue by adityakrshnn** [katspaugh/wavesurfer.js#2013]
I wanted to know if there is anyway to get time from region-click event?

**Comment by marizuccara** [comment]
What time do you mean? Start and end of the region you clicked?

**Comment by adityakrshnn** [comment]
I meant the current time at the position of the click.

**Comment by marizuccara** [comment]
wavesurfer.getCurrentTime()

**Comment by adityakrshnn** [comment]
Maybe I should have framed the question better. I wanted a time from region-click event because I have switched off _interact_ . But, I would like to seek inside the region. This is similar to #1888

**Comment by dakir08** [comment]
@marizuccara  Hey marizuccara, how can I get the start and end time of the region?

**Comment by marizuccara** [comment]
@thijstriemstra, @sundayz , can you give a look? Clicking inside a region, when fires `click` event, not reaches this part of code, even if `interact` is setted to true ..

```
 this.drawer.on('click', (e, progress) => {
            setTimeout(() => this.seekTo(progress), 0);
        });

```

**Comment by sundayz** [comment]
Could it be caused by #1926 ?

In 3.3.3 you can click through regions, in 4.0 you can't

**Comment by marizuccara** [comment]
Exactly.. Removing `e.stopPropagation()` the problem is solved

**Comment by sundayz** [comment]
yeah I think it should be left up to the user to call stopPropagation() if they want.

@iboshkov in your PR you mention "passing the browser event with the region in the handler callback and letting the callback implementation can determine if stopping propagation is needed or not"

doesn't this happen already here? `this.wavesurfer.fireEvent('region-click', this, e);`

so you could just do:
```
wavesurfer.on('region-click', (region, event) => {
    event.stopPropagantion();
    region.play();
});
```

I haven't tested, does this not work?

**Comment by marizuccara** [comment]
mhmm. Or maybe `disableEventEmission`? https://github.com/katspaugh/wavesurfer.js/pull/1960

**Comment by sundayz** [comment]
When using `region.on('click')`, and calling getCurrentTime() you will get the time of the seeker BEFORE it moved due to seeking.
When you use `wavesurfer.on('seek')` and calling getCurrentTime() you get the time AFTER it seeked due to mouse clicking.
The only issue is when 'seek' is called you don't know the cause of the seek: was it triggered by a mouse click, or by the audio playing 🤔

**Comment by adityakrshnn** [comment]
Yes, how would I know the time at the position of the click if interact is set to false? Again, this is similar to #1888
