### ISSUE TITLE
Display preloader while waveform is generating

### ISSUE THREAD

**Issue by realrecordzLab** [katspaugh/wavesurfer.js#2015]
Hi there. I'm using this library into a vue.js project who fetch data from an api and pass the audio to the WaveSurfer.js instance. I'm noticing that the generation process of the waveform is a bit slow, maybe it's due to the files duration.
Is there a way to show a preloader or something similar instead of a blank space while the waveform is generated?

**Comment by sundayz** [comment]
```
<div id="waveform-mount" :class="{ 'is-loading': isLoading }"></div>

...

data() {
  return {
    isLoading: true,
  };
},
````

And set this.isLoading to false when the wavesurfer 'ready' event fires. then style your is-loading class to show whatever you want during loading. look into Vue class and style binding if you're confused

**Comment by realrecordzLab** [comment]
Thank you, I need to test, I've already a preloader in my vue app, I need
only to show something while the load() method of this library is loading
the audio and generating the waveform while fetch the audio from hearthis.at
api. will this be showed instead of the waveform?how I can bind it to the
wavesurfer instance if I already have the `ready` events?

Il giorno mar 21 lug 2020 alle ore 19:05 sundays <notifications@github.com>
ha scritto:

**Comment by sundayz** [comment]
Set a variable in your component data to false, then call wavesurfer.load(). When "ready" fires, set the variable to true. Use that variable to control when your loading indicator shows.

When you call Wavesurfer.create() and you set a `container`, the waveform is placed inside that container, like: <div id="my-waveform-mount"><wave></wave></div> and you can write css for your waveform container to show whatever you want

**Comment by thijstriemstra** [comment]
There's a `progress` event you can listen for @realrecordzLab that should fire during loading.
