### ISSUE TITLE
set wave height to 60px

### ISSUE THREAD

**Issue by realrecordzLab** [katspaugh/wavesurfer.js#2016]
I have this configuration inside a vue method: 

```
      const el = document.getElementById("waveform");
      this.wave = WaweSurfer.create({
        container: el,
        waveColor: "black",
        progressColor: "crimson",
        height: 60
      });
      this.wave.load(this.trackURL);
      this.wave.on('ready', () => {
        this.showPreloader = false;
        this.isLoading = false;
        //this.trackDuration = this.wawe.getDuration();
        this.wave.play();
        this.isPlaying = true;
      });
```

I've set the height of the wave to 60px but it will not be loaded. The audio play works well. Is there a fix or it's a  bug of the library?

**Comment by sundayz** [comment]
Setting the height works fine for me and I'm using vue too. Maybe try setting responsive: true or passing container as a string like '#waveform' to see if those make a difference.

**Comment by realrecordzLab** [comment]
I've found the issue, the problem is with the server where I fetch the
data. I've tried setting the `backend` to MediaElementWebAudio and then to
MediaElement, with the second option all works fine, I think that the
hearthis.at API use MediaElement

Il giorno mar 21 lug 2020 alle ore 19:01 sundays <notifications@github.com>
ha scritto:

**Comment by thijstriemstra** [comment]
> I've found the issue,
