### ISSUE TITLE
 I want to get the three buttons, play, pause and stop, to be grouped into one button

### ISSUE THREAD

**Issue by miguebit** [katspaugh/wavesurfer.js#2027]
Hello, can anyone help me? I am a novice. I want to get the three buttons, play, pause and stop, to be grouped into one button. This is possible?

Here is an example: [https://www.storyblocks.com/audio/stock/indie-rock-energy-bgfynyt8wrk0wyb3se.html](url)

This is what I have:
<img width="912" alt="Captura de pantalla 2020-07-28 a las 13 06 44" src="https://user-images.githubusercontent.com/7389138/88658191-54f15380-d0d3-11ea-929f-e3b17d5c0218.png">

This is the code I am using:
` <div class="content">
                <div id="cajaplay">   
                    <input type="button" id="btn-play" value="Play" disabled="disabled"/>
                    <input type="button" id="btn-pause" value="Pause" disabled="disabled"/>
                    <input type="button" id="btn-stop" value="Stop" disabled="disabled" />
                </div>
            <div id="audio-spectrum"> </div>
            </div>
        
        
      
       
        
       <script src="https://unpkg.com/wavesurfer.js"></script>

        <script>
            // Almacene los 3 botones en algún objeto
            var buttons = {
                play: document.getElementById("btn-play"),
                pause: document.getElementById("btn-pause"),
                stop: document.getElementById("btn-stop")
            };

            // Crear una instancia de waveform con su configuración
            var Spectrum = WaveSurfer.create({
                container: '#audio-spectrum',
                progressColor: "#03a9f4" // Ojo! aqui tenemos el color!
            });

             // //

            // Handle Play button
            buttons.play.addEventListener("click", function(){
                Spectrum.play();

                // Enable/Disable respectively buttons
                buttons.stop.disabled = false;
                buttons.pause.disabled = false;
                buttons.play.disabled = true;
            }, false);

            // Handle Pause button
            buttons.pause.addEventListener("click", function(){
                Spectrum.pause();

                // Enable/Disable respectively buttons
                buttons.pause.disabled = true;
                buttons.play.disabled = false;
            }, false);

            // Handle Stop button
            buttons.stop.addEventListener("click", function(){
                Spectrum.stop();

                // Enable/Disable respectively buttons
                buttons.pause.disabled = true;
                buttons.play.disabled = false;
                buttons.stop.disabled = true;
            }, false);

            // Add a listener to enable the play button once it's ready
            Spectrum.on('ready', function () {
                buttons.play.disabled = false;
            });
            
            // If you want a responsive mode (so when the user resizes the window)
            // the spectrum will be still playable
            window.addEventListener("resize", function(){
                // Get the current progress according to the cursor position
                var currentProgress = Spectrum.getCurrentTime() / Spectrum.getDuration();

                // Reset graph
                Spectrum.empty();
                Spectrum.drawBuffer();
                // Set original position
                Spectrum.seekTo(currentProgress);

                // Enable/Disable respectively buttons
                buttons.pause.disabled = true;
                buttons.play.disabled = false;
                buttons.stop.disabled = false;
            }, false);

            // Load the audio file from your domain !
            Spectrum.load('audio.mp3');

        </script>`

**Comment by sundayz** [comment]
To make a play/pause button you can do:

```js
playPauseButton.addEventListener("click", function() {
  // If audio is playing, pause it when we click the button
  if (Spectrum.isPlaying()) {
      Spectrum.pause();
      playPauseButton.textContent = "Play"; // change button text
  } else {
      // if audio isnt playing, play it when we click the button
      Spectrum.play();
      playPauseButton.textContent = "Pause"; // change button text
  }
});
```

Stop is the same as doing pause() so I don't think you need a 3rd button :)

**Comment by miguebit** [comment]
I have followed his example for hours. But I haven't made it work. Anyway, I really appreciate it.
This is code that I finally tried. And it didn't work either

`<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <title>AudioSpectrum in JavaScript</title>
    </head>
    <body>
        <!-- Create a div where the audio waves will be shown --> 
        <div id="audio-spectrum"></div>

        <!-- Create action buttons -->
        <input type="button" id="play" value="Play" disabled="disabled"/>
        <input type="button" id="pause" value="Pause" disabled="disabled"/>

        <!-- Load the wavesurferscript , in this case from a CDN -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/wavesurfer.js/1.3.7/wavesurfer.min.js"></script>

        <script>
            // Store the 3 buttons in some object
            var buttons = {
                play: document.getElementById("play"),
                pause: document.getElementById("pause"),
        
            };

            // Create an instance of wave surfer with its configuration
            var Spectrum = WaveSurfer.create({
                container: '#audio-spectrum',
                progressColor: "#03a9f4"
            });

           playPauseButton . addEventListener ( "click" ,  function ( )  { 
  // Si se está reproduciendo audio, pausarlo cuando hagamos clic en el botón 
  if  ( Spectrum . isPlaying ( ) )  { 
      Spectrum . pause ( ) ; 
      playPauseButton . textContent  =  "play" ;  // cambiar button text 
  }  else  { 
      // si el audio no se está reproduciendo, reprodúzcalo cuando hagamos clic en el botón 
      Spectrum . play ( ) ;
      playPauseButton . textContent  =  "pausa" ;  // cambiar el texto del botón 
  } 
} ) ;

            // Add a listener to enable the play button once it's ready
            Spectrum.on('ready', function () {
                buttons.play.disabled = false;
            });
            
            // If you want a responsive mode (so when the user resizes the window)
            // the spectrum will be still playable
            window.addEventListener("resize", function(){
                // Get the current progress according to the cursor position
                var currentProgress = Spectrum.getCurrentTime() / Spectrum.getDuration();

                // Reset graph
                Spectrum.empty();
                Spectrum.drawBuffer();
                // Set original position
                Spectrum.seekTo(currentProgress);

                // Enable/Disable respectively buttons
                buttons.pause.disabled = true;
                buttons.play.disabled = false;
                buttons.stop.disabled = false;
            }, false);

            // Load the audio file from your domain !
            Spectrum.load('audio/audio.mp3');
        </script>
    </body>
</html>                                                                                                                                                                                                                                                                                                        `

**Comment by sundayz** [comment]
Change 
```
    <!-- Create action buttons -->
    <input type="button" id="play" value="Play" disabled="disabled"/>
    <input type="button" id="pause" value="Pause" disabled="disabled"/>
```

to

```
<button id="playPause">Play</button>
```
now you have 1 button which will be used as Play/Pause

in your javascript:

```js
var playPauseButton = document.getElementById("playPause");

// then continue with your code:
playPauseButton.addEventListener( "click" ,  function ( )  { 
```

When you do `id="playPause"` it gives the button an ID. Then you can find the button by doing var playPauseButton = document.getElementById("playPause") and then you can listen for the "click" event in the button with addEventListener.

**Comment by miguebit** [comment]
This is what I get. Can you help me please. https://codepen.io/unmedia/pen/abNzNQK

**Comment by miguebit** [comment]
Yessssssss!   Works! Thank you! Thank you! Thank you! You have been very kind.

**Comment by sundayz** [comment]
no problem! 👍
