### ISSUE TITLE
The regions can't be clicked

### ISSUE THREAD

**Issue by ICYMYM** [katspaugh/wavesurfer.js#2029]
# The regions can't be clicked

### The previous version can be clicked and played from the click point.

![wavesurfer_cannot_clicked](https://user-images.githubusercontent.com/3919539/88795524-c237de00-d1d2-11ea-89d9-3055745e024e.gif)

### The previous version can be clicked

![wavesurfer_can_clicked](https://user-images.githubusercontent.com/3919539/88795529-c49a3800-d1d2-11ea-9e3f-3b8d4c5996c3.gif)

**Comment by marizuccara** [comment]
Hi, related to this PR 
https://github.com/katspaugh/wavesurfer.js/pull/2024
