### ISSUE TITLE
FR: Timeline plugin should be drawn at waveform-ready event

### ISSUE THREAD

**Issue by X-Raym** [katspaugh/wavesurfer.js#2032]
Hi,

Wavesurfer v4.0.1

Timeline plugin is currently drawn only at ready event as far as I understood in documentation.

It should also be called at waveform-ready event.

Thanks !

Related issue: https://github.com/katspaugh/wavesurfer.js/issues/2031

**Comment by thijstriemstra** [comment]
@X-Raym pull request welcome!

**Comment by X-Raym** [comment]
@thijstriemstra I would but this issue (which surely needs more consideration) is preventing me to make this simple fix :S

https://github.com/katspaugh/wavesurfer.js/issues/2031

**Comment by X-Raym** [comment]
@thijstriemstra Any news about this ? :)

**Comment by MrdUkk** [comment]
there is more plugins need this change too (elan,markers,regions,minimap,spectrogram), it all listening to 'ready' only event

**Comment by X-Raym** [comment]
@katspaugh how has this been solved?

**Comment by katspaugh** [comment]
@X-Raym I've bulk closed the issues that were last updated more than a year ago.
See the reasoning here: https://github.com/wavesurfer-js/wavesurfer.js/discussions/2684

I'll reopen this one since it's not resolved.

**Comment by katspaugh** [comment]
Closing because it works differently in v7.
