### ISSUE TITLE
Regions: Click inside region doesn't seek

### ISSUE THREAD

**Issue by caugner** [katspaugh/wavesurfer.js#2036]
### Wavesurfer.js version(s):

4.0.1 (2020-06-24)

### Browser and operating system version(s):

Firefox 81.0a1 (2020-08-03)

### Code needed to reproduce the issue:

1. Go to http://wavesurfer-js.org/plugins/regions.html
2. Click outside of region (seek does work).
3. Click inside of region (seek does **not** work).

### Use behaviour needed to reproduce the issue:

(See above.)

**Comment by sundayz** [comment]
Fixed by https://github.com/katspaugh/wavesurfer.js/pull/2024

Will be fixed in version 4.1

You can use wavesurfer 3.3.3 until version 4.1 is released (or compile the master branch yourself I guess)

**Comment by caugner** [comment]
Thanks, downgrading to 3.3.3 solved the issue for us.
