### ISSUE TITLE
Safari / Firefox : S3 hosted audio file and CORS

### ISSUE THREAD

**Issue by mattbryson** [katspaugh/wavesurfer.js#204]
We have files hosted on S3, loading them into wavesurfer.

This works fine in Chrome OSX, but Safari and FireFox report

`Error decoding audiobuffer`

Any ideas?   

You can easily reproduce using the wavesurfer website: 
http://www.wavesurfer.fm/ 
In chrome or safari run this on the console

```
wavesurfer.load('https://s3-eu-west-1.amazonaws.com/soundmites/f5/4779e0c3a111e3b368f97e5bff4d34/coincidence.mp3');
```

**Comment by morganwildermuth** [comment]
I have this exact same issue; can you speak more directly as to how the file needed to be encoded?

**Comment by chinshr** [comment]
The problem for me was that the audio file was not an MP3 even though I thought it was. The (correct for me) way I encode my files to MP3 is:

    cmd = "ffmpeg -y -i #{source_file} -vn -ab #{@mp3_bitrate}k -f mp3 #{mp3_file}   >/dev/null 2>&1"
    system(cmd)

before (the wrong way) was:

    cmd = "ffmpeg -y -i #{source_file} -f mp2 -b #{@mp3_bitrate}k #{mp3_file}   >/dev/null 2>&1"

**Comment by morganwildermuth** [comment]
Thanks. Spoke to the engineer handling the uploading of the file sound now, but he is adamant that there is nothing he can do beyond what he has done (not 100% clear on what that is just yet). So weird that whatever is happening causes no issues with Firefox or our iOS app but is creating mayhem in Chrome.

**Comment by thijstriemstra** [comment]
What's the output of `ffprobe`?

```
ffprobe example/media/demo.wav
```
Output:
```
ffprobe version N-69339-gb04cbbe Copyright (c) 2007-2015 the FFmpeg developers
  built on Jan 27 2015 20:40:04 with llvm-gcc 4.2.1 (LLVM build 2336.11.00)
  configuration: --enable-gpl --enable-version3 --enable-nonfree --enable-postproc --enable-libcelt --enable-libfaac --enable-libfdk-aac --enable-libmp3lame --enable-openssl --enable-libspeex --enable-libtheora --enable-libvo-aacenc --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libxvid --prefix=/usr/local
  libavutil      54. 18.100 / 54. 18.100
  libavcodec     56. 21.100 / 56. 21.100
  libavformat    56. 19.100 / 56. 19.100
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5.  9.101 /  5.  9.101
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  1.100 /  1.  1.100
  libpostproc    53.  3.100 / 53.  3.100
Input #0, wav, from 'example/media/demo.wav':
  Duration: 00:00:21.77, bitrate: 176 kb/s
    Stream #0:0: Audio: pcm_u8 ([1][0][0][0] / 0x0001), 22050 Hz, 1 channels, u8, 176 kb/s
```

**Comment by morganwildermuth** [comment]
ffprobe version 2.2.2 Copyright (c) 2007-2014 the FFmpeg developers
      built on May  7 2014 16:24:57 with Apple LLVM version 5.1 (clang-503.0.40) (based on LLVM 3.4svn)
      configuration: --prefix=/usr/local/Cellar/ffmpeg/2.2.2 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-nonfree --enable-hardcoded-tables --enable-avresample --enable-vda --cc=clang --host-cflags= --host-ldflags= --enable-libx264 --enable-libfaac --enable-libmp3lame --enable-libxvid
      libavutil      52. 66.100 / 52. 66.100
      libavcodec     55. 52.102 / 55. 52.102
      libavformat    55. 33.100 / 55. 33.100
      libavdevice    55. 10.100 / 55. 10.100
      libavfilter     4.  2.100 /  4.  2.100
      libavresample   1.  2.  0 /  1.  2.  0
      libswscale      2.  5.102 /  2.  5.102
      libswresample   0. 18.100 /  0. 18.100
      libpostproc    52.  3.100 / 52.  3.100
    Input #0, wav, from '164_02_25_2015-12_00_39-PST_73393.wav':
    Duration: 00:00:03.50, bitrate: 16 kb/s
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 1000 Hz, 1 channels, s16, 16 kb/s
