### ISSUE TITLE
Fluentcards Not Workking

### ISSUE THREAD

**Issue by glenfordnunez** [katspaugh/wavesurfer.js#2040]
Sorry to write this here but I could not find any other way to contact you about Fluentcards. 
I really love Fluentcards and have been using it faithfully until one day it stopped working. 

The issue happens when fetching definitions. It starts ok but then stops at about 5 or 10 entries depending on the book. 

I have included my vocab.db from kindle. 

I will send money if you can fix this! 
Please assist!

[vocab.db.zip](https://github.com/katspaugh/wavesurfer.js/files/5062083/vocab.db.zip)

**Comment by thijstriemstra** [comment]
You posted this in the wrong repository, wavesurfer.js.
