### ISSUE TITLE
Tests fail because of ajax AbortError

### ISSUE THREAD

**Issue by sundayz** [katspaugh/wavesurfer.js#2042]
### Wavesurfer.js version(s):
4.x

### Browser and operating system version(s):
Firefox, Chrome (CI headless too)

In the stack trace when running tests locally:
Unhandled promise rejection: AbortError: The operation was aborted. 

Caused by:
(test runs correctly) -> destroy -> cancelAjax -> AbortError

Sometimes 1 test fails, other times 20 fail. Probably because of the mp3 files loaded during tests.

I tried wrapping every call to `wavesurfer.destroy()` in the spec folder with:
```js
            try {
                wavesurfer.destroy();
            } catch (err) {
                // Ignore AbortError that can be thrown by cancelAjax during destroy, rethrow all others
                if (err.name !== 'AbortError') {
                    throw err;
                }
            }
```

But the tests still fail, not sure why :) Maybe someone knows how we can ignore AbortError during calls to destroy() with karma.js

**Comment by thijstriemstra** [comment]
I think we need to properly handle the abort call by listening for rejected promise and triggering a new event, something like 'abort' or 'aborted'. I don't think handling them with a catchall for tests would be a good solution. Anyone using `destroy` in their app, outside of tests, could also run into this issue.

**Comment by thijstriemstra** [comment]
ps. I would call this a blocker for the 4.1.0 release, I really don't want to release something with failing test(s).

**Comment by sundayz** [comment]
Oh. If there's promises inside `destroy` then it should definitely be marked async. Then it makes sense why try/catch isnt working.

**Comment by sundayz** [comment]
I think the real issue is that all `destroy` functions should be async and only resolve when everything is destroyed (requests aborted, canvas destroyed, etc)

**Comment by thijstriemstra** [comment]
This looks related, making this a Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1583815

**Comment by sundayz** [comment]
https://github.com/sundayz/wavesurfer.js/commit/4acc9252128e984bb1f3cd74aa6dd22ce4fc608a

This seems to fix the AbortError, but now there's more errors. This one I've seen in production too with the current version on Firefox, during calls to destroy(). The app still works though:
```
Firefox 81.0 (Windows 10) WaveSurfer/MediaElementWebAudio: should toggle mute FAILED
	Unhandled promise rejection: EncodingError: The buffer passed to decodeAudioData contains an unknown content type.
```

And then the tests for the play/pause methods fail. At least in my browser, I have not tried chrome. Did these ever work?

**Comment by thijstriemstra** [comment]
Awesome you found a fix! Let's get that fix merged so I can help looking at these errors from master branch @sundayz

**Comment by sundayz** [comment]
Opened PR. Idk if the test fails are caused by my fix or if they were failing anyway.
