### ISSUE TITLE
Clone wavesurfer's container div without doubling CPU usage, could it be possible?

### ISSUE THREAD

**Issue by The-Linguist** [katspaugh/wavesurfer.js#2050]
I am using WaveSurfer's cool microphone plugin to put a lovely waveform on the screen. It is so good that only ONE is not enough and I want to duplicate and use TWO of them or maybe even more (like clones placed in different locations of the document window). As a result the “GUI” will look only better.
The problem is the unnecessary doubling of CPU usage. Two different container divs with two different WaveSurfer objects doing the same intensive CPU calculation to produce the exact same graph... and I really don't want to hear those CPU fans go crazy.

`cloneNode(true);` is useless. Yet I really would like to be able to clone the visual output without creating a copy of the WaveSurfer process and thus save valuable resources.

Could this ever be possible?
Maybe if I could somehow define two container divs for the same WaveSurfer object... That would be great!

**Comment by sundayz** [comment]
The only solution I found for cloning a canvas element is using getImageData and putImageData but those still use quite a lot of resources, but probably less than calculating the waveforms twice.

From what I understand html5 canvas and webGL don't support sharing a single buffer between multiple canvases. This might change in the future with [SharedArrayBuffer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer) and WebAssembly...

Maybe you can create your own renderer for wavesurfer using something like pixi.js which uses WebGL and is more efficient than the html5 canvas which wavesurfer uses.

**Comment by sundayz** [comment]
You could also have 1 big canvas like this: https://threejs.org/examples/webgl_multiple_elements.html

If you inspect element you can see the single <canvas> stretches over the page.

**Comment by The-Linguist** [comment]
Thank you @sundayz 
Sure, I will take a look.
