### ISSUE TITLE
Can the audio file be loaded from the html code?

### ISSUE THREAD

**Issue by miguebit** [katspaugh/wavesurfer.js#2061]
Hello, I would be very grateful if you could help me.
I am trying to create a music library download website. For this I am using https://wavesurfer-js.org/
But I see that it only allows to load the audio with JS. My question is this:

Can the audio file be loaded from the html code? I see in the examples it only allows file loading from JavaScript
Is there a way to do this. I am trying to dynamically load files from ACF. https://www.advancedcustomfields.com/
You can see a sample of what I'm trying to do from here http://rgmusic.net/waveExample/

You can download all the code here: [ https://www.dropbox.com/s/5viv602w98pliph/waveExample.zip?dl=0](url)

Thank you very much.

**Comment by thijstriemstra** [comment]
Yes, see https://wavesurfer-js.org/example/html-init/index.html

**Comment by miguebit** [comment]
Thank you. This is great. But can I keep my custom play / pause controls as I show here?

> Yes, see https://wavesurfer-js.org/example/html-init/index.html



> Yes, see https://wavesurfer-js.org/example/html-init/index.html

Thank you. This is great. But can I keep my custom play / pause controls as I show here?

**Comment by miguebit** [comment]
> Hello, I would be very grateful if you could help me.
> I am trying to create a music library download website. For this I am using https://wavesurfer-js.org/
> But I see that it only allows to load the audio with JS. My question is this:
> 
> Can the audio file be loaded from the html code? I see in the examples it only allows file loading from JavaScript
> Is there a way to do this. I am trying to dynamically load files from ACF. https://www.advancedcustomfields.com/
> You can see a sample of what I'm trying to do from here http://rgmusic.net/waveExample/
> 
> You can download all the code here: [ https://www.dropbox.com/s/5viv602w98pliph/waveExample.zip?dl=0](url)
> 
> Thank you very much.
