### ISSUE TITLE
this.handlers is undefined

### ISSUE THREAD

**Issue by sundayz** [katspaugh/wavesurfer.js#2067]
### Wavesurfer.js version(s):
4.1.0

### Code needed to reproduce the issue:
Region plugin doesn't load, check example page:

https://wavesurfer-js.org/plugins/regions.html

When calling `this.regions.add(options)`.
Line 199 of regions/index.js registers this event:
```
        region.on('remove', () => {
            delete this.list[region.id];
        });
```

Results in `TypeError: can't access property "remove", this.handlers is undefined`

Last change to observer: https://github.com/katspaugh/wavesurfer.js/commit/590d9ccc96f6c69090849f2e5cfb4587da647ee5
Looks like removing the lazy creation of handlers object broke the regions plugin.

Found this comment in observer.js: `* plugins borrow part of this class without calling the constructor`
Can we do something about that without breaking existing plugins? Not calling the constructor doesn't sound very good.

Worst case scenario we revert to what we were doing before.

**Comment by mstratford** [comment]
I've also seen this issue, breaks our React app.

**Comment by kgritesh** [comment]
same here broke our app.

**Comment by sundayz** [comment]
Proposed fix, assuming we can't change how plugins extend the Observer class (can we?)

In constructor:
`this._handlers = {};`

Getter:
```
get handlers() {
	if (!this._handlers) {
		this._handlers = {};
	}
	return this._handlers;
}
```

And a setter.

Javascript engines should be able to optimize it, the if branch is only executed once?

That or we revert 590d9cc. It was just code cleanup changes. @thijstriemstra

**Comment by thijstriemstra** [comment]
> It was just code cleanup changes.

Well, turns out it changed behavior. Can you start out with a unit test that reproduces the bug and go from there?

**Comment by whthT** [comment]
Change version in package.json to `"wavesurfer.js": "4.0.1"`

an then force install node modules with
`npm i -f` or `yarn install --force`

**Comment by sundayz** [comment]
@thijstriemstra https://github.com/katspaugh/wavesurfer.js/blob/master/src/plugin/regions/index.js#L122

This code just adds the functions of Observer to Region. It doesn't call the constructor so the properties initialized in Observer constuctor aren't added. In the past handlers was initialized outside of the constructor

I don't know WaveSurfer well enough to know why it's done this way. Why doesn't region just do `class Region extends Observer`?

**Comment by julj** [comment]
Same here: broke our app.

**Comment by pushrax** [comment]
The quick start method of including wavesurfer via unpkg is unversioned and updates automatically, and anyone using this has a broken website right now.

**Comment by thijstriemstra** [comment]
> anyone using this has a broken website right now.

Only when using the regions plugin. Pull requests to fix this are welcome.

**Comment by thijstriemstra** [comment]
> Only when using the regions plugin. 

Spoke too soon, it's also affecting wavesurfer.js core, blah.

**Comment by thijstriemstra** [comment]
> Or maybe we should revert 590d9cc. It was just code cleanup changes.

@sundayz please do.

**Comment by thijstriemstra** [comment]
4.1.1 was released and fixes this issue.
