### ISSUE TITLE
Wavesurfer loads network audio resources in Vue across domains

### ISSUE THREAD

**Issue by minbaowang** [katspaugh/wavesurfer.js#2068]

**Comment by sundayz** [comment]
Your server should send CORS headers, here is an example for sending them through Apache config:
```
Header set Access-Control-Allow-Origin "*"
Header always set Access-Control-Allow-Methods "GET"
Header always set Access-Control-Allow-Headers "Content-Type: audio/mpeg"
```

It is up to you to decide how to send them, you can do it from apache, from php, from node js etc. This is not a problem with wavesurfer or vue.
