### ISSUE TITLE
Unable to decode audio data

### ISSUE THREAD

**Issue by delewis13** [katspaugh/wavesurfer.js#2072]
Hello thanks for this fantastic library!

I hit `DOMException: Unable to decode audio data` exception while trying to run `wavesurfer.load(src)` from an empty audio file [likely corrupted]. I've seen a few other issues on the same topic, but none seem to answer my question below.

Is there anyway for me to catch this exception so that I can display some notification to the user that there is a problem with their audio file?

Thanks :)

**Comment by thijstriemstra** [comment]
sounds like a good idea.

**Comment by marizuccara** [comment]
Hi, you can subscribe to the error event emitted by wavesurfer in this way:
`wavesurfer.on('error', e => alert(e))`

**Comment by thijstriemstra** [comment]
@marizuccara I think the point is that this DOMException is not caught and not propogated using the `error` event.

**Comment by delewis13** [comment]
@thijstriemstra I see a recent commit handles this! Thanks very much for your effort on that 👍

**Comment by v3ss0n** [comment]
This is happening back. getting `DOMException: Failed to execute 'decodeAudioData' on 'BaseAudioContext': Unable to decode audio data` out of the blue

**Comment by alex-oleks** [comment]
> This is happening back. getting `DOMException: Failed to execute 'decodeAudioData' on 'BaseAudioContext': Unable to decode audio data` out of the blue

I have the same problem. Have you solved it?

**Comment by katspaugh** [comment]
Please open a new issue and attach a snippet of your code, the audio URL and browser/OS.
