### ISSUE TITLE
Sync Two waves

### ISSUE THREAD

**Issue by naumanahmed19** [katspaugh/wavesurfer.js#2073]
I am want to sync two waves. Is there any way? The current method only works for one. I want to update other if the seek is changed by any of them.
```
   wavesurfer1.on('seek', function (position) {
     wavesurfer2.seekTo(position);
  });

   wavesurfer2.on('seek', function (position) {
     wavesurfer1.seekTo(position);
  });
```

**Comment by sundayz** [comment]
Whats wrong with the code you posted? You want to make it work for more than 2?

**Comment by naumanahmed19** [comment]
Yes, I am using multiple players. I have created a pen. can you please check it 

https://codepen.io/naumanahmed19/pen/eYZXMZP

The problem is both events are calling each other and they get stuck in a loop. And it gives `caught RangeError: Maximum call stack size exceeded `

**Comment by sundayz** [comment]
```js
wavesurfer1.on('seek', position => {
    // Dont emit seek event
    wavesurfer2.setDisabledEventEmissions(['seek'])

    wavesurfer2.seekTo(position);

    // Allow all events to be emitted again
    wavesurfer2.setDisabledEventEmissions([])
});
```

And same thing for wavesurfer2, but the other way around.

Using setDisabledEventEmissions you disable an event temporarily. I recommend you dont use that function a lot, unless you really need to, such as in examples like this.

If you are using an old version of wavesurfer that doesnt have that function there are still ways to achieve this but it will take a bit more code.

**Comment by naumanahmed19** [comment]
@sundayz thanks it's working with the new version.
