### ISSUE TITLE
Applying EQ to file?

### ISSUE THREAD

**Issue by keyonchrist** [katspaugh/wavesurfer.js#2074]
Hi I’ve searched everywhere but having trouble implementing the equalizer to a file that is able to be saved to json data instead of just applying it to the audio file. If someone could point me in the right direction if this is even possible I’d be eternally grateful. Thanks

**Comment by thijstriemstra** [comment]
> implementing the equalizer to a file that is able to be saved to json data instead of just applying it to the audio file.

This sounds confusing. You can save the peaks data of a waveform to a json file, do you have this working? After that, what is it that you want to save to json regarding the equalizer?

**Comment by sundayz** [comment]
Do you mean normalizing json peaks data? https://wavesurfer-js.org/faq/

Under "How to generate waveform data on the server" there is a python script that normalizes peaks saved to json.


If you mean equalizer, then maybe the Web Audio API "audio effects nodes" is what you are looking for? https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API

**Comment by thijstriemstra** [comment]
no feedback, closing.
