### ISSUE TITLE
Wavesurfer.js Microphone does not show waves when multiple device is connected on safari.

### ISSUE THREAD

**Issue by bgakash93** [katspaugh/wavesurfer.js#2078]
### Wavesurfer.js version(s):

wavesurfer.js@2.1.3

### Browser and operating system version(s):

macOS Mojave(10.14.6), Safari Version 14.0 (14610.1.28.1.9)

### Use behaviour needed to reproduce the issue: 

When we connect external bluetooth device and try to access "https://wavesurfer-js.org/plugins/microphone.html" we do not see the wavelines.

**Comment by thijstriemstra** [comment]
@bgakash93 please use wavesurfer.js 4.1.1 or newer, you're using an ancient version. Please re-open if issue still exists.

**Comment by bgakash93** [comment]
> @bgakash93 please use wavesurfer.js 4.1.1 or newer, you're using an ancient version. Please re-open if issue still exists.

@thijstriemstra Verfied on updated version 4.1.1 also, facing the same issue.
