### ISSUE TITLE
microphone plugin does not show waves when multiple device is connected on safari

### ISSUE THREAD

**Issue by bgakash93** [katspaugh/wavesurfer.js#2081]
Wavesurfer.js version(s):4.1.1

### Browser and operating system version(s):
macOS Mojave(10.14.6), Safari Version 14.0 (14610.1.28.1.9)

### Use behaviour needed to reproduce the issue

When we connect external bluetooth device and try to access "https://wavesurfer-js.org/plugins/microphone.html" we do not see the wavelines.

**Comment by lak-16** [comment]
Hi, I have same issue on Mac and iPhone Safari. Any suggestions/workaround to fix this.

**Comment by thijstriemstra** [comment]
You should use [enumerateDevices](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/enumerateDevices) to get the id of the second bluetooth device and pass that to the `constraints` option of the microphone plugin:

```js
if (!navigator.mediaDevices || !navigator.mediaDevices.enumerateDevices) {
  console.log("enumerateDevices() not supported.");
  return;
}

// List cameras and microphones.

navigator.mediaDevices.enumerateDevices()
.then(function(devices) {
  devices.forEach(function(device) {
    console.log(device.kind + ": " + device.label +
                " id = " + device.deviceId);
  });
})
.catch(function(err) {
  console.log(err.name + ": " + err.message);
});
```
