### ISSUE TITLE
How to export SVG ?

### ISSUE THREAD

**Issue by iftkharhussain** [katspaugh/wavesurfer.js#2082]
# Hey, thank you for testing and contributing to wavesurfer.js!

## Please make sure you can check all of these points below before opening an issue:

(You don't have to post this section)

- [x] I have checked [the FAQ](https://wavesurfer-js.org/faq/) and it doesn't solve my problem.
- [x] I have checked [the documentation](https://wavesurfer-js.org/docs/) and it doesn't solve my problem
- [x] I have searched for [already open issues](https://github.com/katspaugh/wavesurfer.js/issues) which desribe my problem.
- [x] The issue I'm having is related to and caused by wavesurfer.js, not by other software (which maybe packages and uses wavesurfer incorrectly) – In that case you should open the issue on the respective project pages.

### Code needed to reproduce the issue:

(Please reduce your code as much as possible and only post the minimum code needed to reproduce the issue. [A Code pen](http://codepen.io/) is an excellent way to share such code)

**Comment by thijstriemstra** [comment]
use an external library like https://github.com/gliffy/canvas2svg

You can access the waveform `canvas` element of wavesurfer using `wavesurfer.drawer.canvases[0].wave`.

**Comment by iftkharhussain** [comment]
> use an external library like https://github.com/gliffy/canvas2svg
> 
> You can access the waveform `canvas` element of wavesurfer using `wavesurfer.drawer.canvases[0].wave`.

Thanks for your help but it is not working actually https://github.com/gliffy/canvas2svg is not for existing canvas
https://stackoverflow.com/questions/63233793/serialize-html-5-canvas-to-svg-to-send-to-server

Please help me how can I get svg, i spent alot of time on this thing ?

**Comment by thijstriemstra** [comment]
>  i spent alot of time on this thing ?

And now we have to?

**Comment by iftkharhussain** [comment]
I think ctx is different
`
var _canvas = wavesurfer.drawer.canvases[0].wave
var _ctx = _canvas.getContext('2d')
`
than
`var ctx = new C2S(500,500)`

**Comment by sundayz** [comment]
https://github.com/antonKalinin/audio-waveform-svg-path

Maybe try another library.

Or you can write your own code to create the SVG from the audio data. Or consider using a PNG instead of svg.

**Comment by iftkharhussain** [comment]
> https://github.com/antonKalinin/audio-waveform-svg-path
> 
> Maybe try another library.
> 
> Or you can write your own code to create the SVG from the audio data. Or consider using a PNG instead of svg.

Thanks @sundayz , @thijstriemstra 
Actually my client requirements is to show the same soundwave like wavesurfer.js, https://i.imgur.com/E4xnbxf.png
i tried to manipulate current wavesurfer.js to get exact CTX like canvas2svg.js requires but no luck, so it would be very helpful for me if you guide me little how can i do this ?

**Comment by TomasHubelbauer** [comment]
Looks like the new wave to access the canvas is `wavesurfer.renderer.canvasWrapper.querySelector('canvas')`. I am a new Wavesurfer user so I might not have this exactly correct but I think this is a result of the v6 to v7 refactoring. Leaving this comment for whoever else ends up sleuthing though the issues for help after me.
