### ISSUE TITLE
Setting Volume on Mobile Devices

### ISSUE THREAD

**Issue by dagreatbrendino** [katspaugh/wavesurfer.js#2085]
### Wavesurfer.js version(s):
wavesurfer.js@3.3.3

### Browser and operating system version(s):
IOS Safari

### Code needed to reproduce the issue:
```this.wavesurfer.setVolume(this.state.volume)```
### Use behaviour needed to reproduce the issue:
Hi, I am trying to set the volume of a player using state controlled by a slider that is an int between 0 & 1. It works fine on desktop browsers, but on iPhone and iPad changing the volume of the player does not change the output volume. Am I missing something?

**Comment by sundayz** [comment]
Safari on iPhone and iPad doesn't allow volume to be changed through javascript, sadly: https://developer.apple.com/library/archive/documentation/AudioVideo/Conceptual/Using_HTML5_Audio_Video/Device-SpecificConsiderations/Device-SpecificConsiderations.html

**Comment by dagreatbrendino** [comment]
@sundayz darn that was my worry. Thanks for the link! Do other browsers/mobile devices allow js to control volume? If so is there a way to detect if the ```setVolume()``` function is unavailable or do I need to do manual device detection?

**Comment by sundayz** [comment]
As far as I know it works everywhere else :) So you could do a useragent check, even if it won't be 100% reliable

```js
const userAgent = window.navigator.userAgent.toLowerCase();
const isMobileSafari = /safari/.test(userAgent) && /iphone/.test(userAgent);
```

Though design guidelines for Android and iOS will tell you that on mobile devices you should let volume only be controlled by the buttons on the phone rather than sliders. But it depends on what you are trying to do.

**Comment by dagreatbrendino** [comment]
Cool cool. Thanks for the help. I'll probably use that + css to make the volume slider hidden on mobile views

**Comment by DaleCam** [comment]
I am actually able to change volume using wavsurfer API using the latest IOS + Safari. Perhaps it was your code @dagreatbrendino ?

**Comment by dagreatbrendino** [comment]
@DaleCam I misspoke. Definitely not an int since it falls between 0 & 1. You accomplished this with wavsurfer.setVolume()? I don't think it's my code since it works to change volume on desktop browsers. Could you post a working snippet that I could play with/test? 

It really doesn't seem possible according to the article that @sundayz posted.

**Comment by DaleCam** [comment]
Hi! Yes I'm simply using setVolume too. As a last resort have you tried a hard coded value ie: 0.1? The article @sundayz posted was written in 2012 so its a little outdated. You could try the channel volume here for a IOS test [https://wavesurfer-js.org/example/mediaelement-webaudio/index.html:](https://wavesurfer-js.org/example/mediaelement-webaudio/index.html)

**Comment by dagreatbrendino** [comment]
hm that example won't even play on my phone. However the mute example worked which has me thinking it might be possible...

**Comment by sundayz** [comment]
Apparently you can use a GainNode to change the volume on iOS with the Web Audio api. So if you really wanted to you could do it that way by using the WebAudio backend option in wavesurfer, instead of MediaElement.  But there are advantages and disadvantages to that.

**Comment by DaleCam** [comment]
@dagreatbrendino actually it also depends on how old your ios device is. Volume control is definately working on the latest devices is all I can tell you!

**Comment by dagreatbrendino** [comment]
Which backend are you using?

**Comment by DaleCam** [comment]
@dagreatbrendino I wasn't setting it explicitly so whatever is default (I cant remember what the default is)



---- On Sun, 11 Oct 2020 17:05:30 -0500 Brendan <notifications@github.com> wrote ----




Which backend are you using?

**Comment by dagreatbrendino** [comment]
As it turns out my use case requires me to use the MediaElement backend because I need the waveform drawn before the audio is fully loaded
