### ISSUE TITLE
Waveform progress for audio preview

### ISSUE THREAD

**Issue by dagreatbrendino** [katspaugh/wavesurfer.js#2086]
Hello, I have a use case where a logged in user only gets a 30 second preview of an audio file, however I still want to render the the waveform for the full file. I have the peaks stored, so I am able to render the full wavefrom fine. 

My issue is that the track progresses as if it is is the full track. Is there some sort of parameter than can change how the waveform progresses?

**Comment by sundayz** [comment]
```js
wavesurfer.on('audioprocess', currentTime => {
    if (currentTime > 30) {
        wavesurfer.pause();
    }
});
```

Maybe something like this?

**Comment by dagreatbrendino** [comment]
Sorry I should have been a bit more clear. What I mean is if the waveform represents a 2 minute song and the preview is 30 seconds. By the end of the 30 seconds the waveform has progressed to the end of the wave.

**Comment by dagreatbrendino** [comment]
[
![waveexample](https://user-images.githubusercontent.com/42331298/95394926-15a96500-08c3-11eb-9289-37ebc6eeef1d.gif)
](url)

Uploaded a gif to show what I mean. This waveform is generated by providing the peaks for the full 2 minute track, and the progress fills up the entire track instead of just the part representing that 30 seconds.

**Comment by dagreatbrendino** [comment]
I was able to come up with this. It gives the desired result but is not super intuitive. Please let me know if you can think of a way that doesn't require manually setting the styles. 
```javascript
    this.trackPlayTime = this.wavesurfer.on('audioprocess', ()=>{
      let formatted = moment.duration(Math.floor(this.wavesurfer.getCurrentTime()), 'seconds').format("m:ss",{forceLength: true, trim: false})
      //the width of the full waveform
      let fullWavWidth = window.getComputedStyle(this.$waveform?.firstChild)?.width
      //the ratio that 30 seconds makes of the full track
      let progressFullWidth = fullWavWidth.split("px")[0] * this.state.ratio 
      //the current progress out of 30 seconds
      let progressCurrent = this.wavesurfer.getCurrentTime()/30 * progressFullWidth \
      // setting the style of the progress wave
      this.$waveform.firstChild.firstChild.style.width = progressCurrent + "px" 
      this.setState({currentTime: formatted})
    })
```


[
![waveexample2](https://user-images.githubusercontent.com/42331298/95397059-eb0ddb00-08c7-11eb-8400-5ff67684c752.gif)
](url)

**Comment by sundayz** [comment]
Looks fine to me, I think that's the best you'll get without writing your own renderer.

**Comment by dagreatbrendino** [comment]
Okay yea this is much easier than doing that. Thanks!
