### ISSUE TITLE
Does it have a way to set the sampling rate? 

### ISSUE THREAD

**Issue by ICYMYM** [katspaugh/wavesurfer.js#2094]
If you input a one-hour mp3, it will be very large after decoding. For some old computers, it may cause the browser to crash.
Is there any way to set the sample rate when decoding the audio?

If wavesurfer.js provides this option, it will be very convenient.

Thanks a lot.

**Comment by thijstriemstra** [comment]
You can pass in your own AudioContext where you can set the samplerate. Use the `audioContext` option.
