### ISSUE TITLE
Projects page

### ISSUE THREAD

**Issue by deju1980** [katspaugh/wavesurfer.js#2098]
Hi,

Just wanted to say thanks for a great app! I teach guitar and have a few apps on my website for my students to use. I used wavesurfer to create a speed changer app on my site and was wondering if you could post a link to it on your projects page? The link is: <a href="https://www.truetoneguitar.co.uk/tools/music-speed-changer">Music Speed Changer</a> - An online web app for changing music speed and pitch in real time,

Thanks!

Derek

**Comment by thijstriemstra** [comment]
please edit this file and open a pull request @deju1980: https://github.com/katspaugh/wavesurfer.js/blob/gh-pages/projects/index.html
