### ISSUE TITLE
Wavesurfer createElement

### ISSUE THREAD

**Issue by gabrielechiossi** [katspaugh/wavesurfer.js#2101]
I am trying to implement wavesurfer in this little project that I am doing.
It is a web recorder, I am trying to make the wavesurfer a const that would move with all my other const in the javascript. 
I will attach some pics and code because it is pobably easier to visualize this than try to explain it. 
![Cattura](https://user-images.githubusercontent.com/59843905/97487524-5aa94000-1933-11eb-8c89-6e999f7f7490.JPG)
As you can see the wave sound does not follow the web player. What I want is the wave sound of the web player with the button and then another wave with its web player and buttons. 

What I tried to do is make the wavesurfer as the other consts (commented code in the pics) but it does not work anybody can help me.
![Cattura2](https://user-images.githubusercontent.com/59843905/97487873-dacfa580-1933-11eb-9d79-7f82f59141d2.JPG)
![Cattura3](https://user-images.githubusercontent.com/59843905/97487871-dacfa580-1933-11eb-85f1-8e4a65f3301a.JPG)

**Comment by thijstriemstra** [comment]
Try `backend: 'MediaElement'`. Having opus in a wav container also seems problematic..

**Comment by gabrielechiossi** [comment]
> 
> 
> Try `backend: 'MediaElement'`. Having opus in a wav container also seems problematic..

Where would I add it? Should I add it for const wavesurfer = document.createElement('div')? Also, what is opus?
I am sorry I am new to js and wavesurfer.

**Comment by sundayz** [comment]
When you create a new waveform you specify its container, and you are setting it to `#waveform`. IDs in HTML need to be unique. Thats why every time you create a waveform theyre all appearing in the same place.

When you create the div which contains the waveform, instead of giving in the id "waveform", do something like this:

```
var myUniqueID = "#waveform" + (Math.random() * 100);
```

And then you specify that uniqueID when you use the function WaveSurfer.create and give it a container.
Math.random() is not the best way of making a unique ID, so know that in the future you will have to do something else :)

**Comment by gabrielechiossi** [comment]
> 
> 
> When you create a new waveform you specify its container, and you are setting it to `#waveform`. IDs in HTML need to be unique. Thats why every time you create a waveform theyre all appearing in the same place.
> 
> When you create the div which contains the waveform, instead of giving in the id "waveform", do something like this:
> 
> ```
> var myUniqueID = "#waveform" + (Math.random() * 100);
> ```
> 
> And then you specify that uniqueID when you use the function WaveSurfer.create and give it a container.
> Math.random() is not the best way of making a unique ID, so know that in the future you will have to do something else :)

Where would I put this myUniqueID?
Line 66 instead of the const wavesurfer?
![immagine](https://user-images.githubusercontent.com/59843905/98023379-d80dfe00-1dd4-11eb-823b-07dd594ed0ac.png)

**Comment by sundayz** [comment]
Sorry, we can't make your app/website for you. Just make unique containers for each wavesurfer, how you do that is up to you.
