### ISSUE TITLE
Migrate to travis-ci.com

### ISSUE THREAD

**Issue by thijstriemstra** [katspaugh/wavesurfer.js#2102]
@katspaugh  can you migrate to .com, it should fix any build delays and should be done before end of dec 2020 anyway.

See https://docs.travis-ci.com/user/migrate/open-source-repository-migration

**Comment by katspaugh** [comment]
Somehow it gives me an error when I press the "Sign up for beta" button. Will try again later.

**Comment by thijstriemstra** [comment]
Weird. I also migrated some projects and that worked okay here. Hope it'll work without contacting support etc.

**Comment by katspaugh** [comment]
I think it worked this time. ✅

**Comment by thijstriemstra** [comment]
thanks.
