### ISSUE TITLE
Force redraw manually

### ISSUE THREAD

**Issue by hovi** [katspaugh/wavesurfer.js#2104]
### Wavesurfer.js version(s):

4.2.0 (currently latest)

Hi!

I know library has `responsive` option, which makes itself to redraw 100ms after "resize" event, if set to true (or different timeout).
In my case I need to respond to resize, that is not caused by "resize" js event. 
In my case, nothing changes with window size, but layout of site changes at one point, causing wave being too long or short for it's resized container, so I need to force redraw manually when necessary. Is there way to do that?

Simple example to give some idea (click on wave to toggle container width):
https://codepen.io/hovi6337/pen/ExydbZd

**Comment by hovi** [comment]
[drawBuffer](https://github.com/katspaugh/wavesurfer.js/blob/f62ad10492862e91729312925f1e8082c86d356f/src/wavesurfer.js#L1199) does the job.

Would be nice to put it into official doc, if it's supposed to be part of public API.

**Comment by thijstriemstra** [comment]
> Would be nice to put it into official doc, if it's supposed to be part of public API.

Feel free to create a pull request @hovi
