### ISSUE TITLE
ScrollEvent?

### ISSUE THREAD

**Issue by larrywal** [katspaugh/wavesurfer.js#2107]
I'm trying to synchronize a wavesurfer timeline with other controls I'm drawing representing the same timeline.  

I hooked the scroll event, but I can't figure out how to get anything useful from it.  Documentation says it sends a ScrollEvent object, but I can't find what that is.

I see a timestamp property but that just continually counts up.  Can someone help?

**Comment by thijstriemstra** [comment]
@larrywal can you share a simplified version of code you're using now?

**Comment by thijstriemstra** [comment]
no feedback, closing.
