### ISSUE TITLE
RFC: Typescript for Wavesurfer.js

### ISSUE THREAD

**Issue by sundayz** [katspaugh/wavesurfer.js#2109]
Hi all.

Over time, more and more people have suggested that wavesurfer uses typescript, or at least provides up to date typescript definitions. (#2038 #1209 etc)

I have started work on incrementally moving Wavesurfer to Typescript.

**Follow the progress here:**
- [ ] Part 1  #2110

Typescript has the following benefits:
- Static type checking means less chance to accidentally write broken code.
- Smaller barrier to entry for new contributors, they can write new code with confidence.
- The end product is still Javascript code, so end users get all the benefits for no extra cost. Typescript users don't have to download separate types.
- Typescript has some useful linting functionalities like no unused variables, etc.

The 3rd party wavesurfer types on the definitely typed repository are outdated. This is causing issues for some people who are trying to use wavesurfer in a typescript project. By slowly adopting typescript we remove the need for separate types which would need to be kept in sync with the project. 

Progress as of right now is that the code builds correctly as far as I can tell, and I moved util/max.js to util/max.ts and it seems like everything is going well.

Let me know what you think, if this is worth it, etc. There is still some things left to configure. We will need to use relaxed typescript rules as we convert js files to ts, then we can apply additional restrictions like no "any", strict function types etc.

**Comment by thijstriemstra** [comment]
Sounds good.

**Comment by sundayz** [comment]
Sure. I’ll start by converting the Wavesurfer class to typescript and we can also look at the tsconfig file for the first PR.

**Comment by thijstriemstra** [comment]
I would start with something simple like util classes. But maybe entry point (Wavesurfer) needs to be done first, dunno.

**Comment by sundayz** [comment]
It doesn't need to be first but I guess it would bring most value. We can start with util classes though.

**Comment by nadineshmo** [comment]
Hi, thanks so much for your work! @sundayz do you have a rough estimate to when the cursor plugin might work for typescript? Just wondering. Thanks!

**Comment by sundayz** [comment]
@nadineshmo Adding type definitions to the code is pretty easy and won't take long, but I have to rework #2110 and I'm a bit busy with work related things right now to do it. I might have time later this week to re-do the PR to change the build system to typescript.

**Comment by caugner** [comment]
@sundayz I opened a PR in the DefinitelyTyped repository to complete the current TypeScript definitions (especially adding those for the Wavesurfer.js plugins) : https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52429

It would be great if you or someone else could have a look and review my changes. 🙏

**Comment by caugner** [comment]
The type definitions are currently up-to-date with 5.0, and the update to 5.1 is pending (waiting for review/approval): https://github.com/DefinitelyTyped/DefinitelyTyped/pull/53984

(Feel free to [review the changes](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/53984/files) and approve them. You don't need to be a member or maintainer to review.)

**Comment by thijstriemstra** [comment]
With these typings, this ticket can be closed @sundayz?

**Comment by sundayz** [comment]
Yes, if you want type hints for wavesurfer, you can now use the DefinitelyTyped repo, thanks to @caugner 🎉
