### ISSUE TITLE
M3U Playlist Plugin example broken

### ISSUE THREAD

**Issue by SeanBannister** [katspaugh/wavesurfer.js#2112]
Just noticed the [M3U Playlist Plugin example](https://wavesurfer-js.org/plugins/playlist.html) is broken, the M3U file is no longer hosted at the location it points to.

**Comment by thijstriemstra** [comment]
because it's a codepen when can't edit it cc @entonbiba

**Comment by thijstriemstra** [comment]
We should probably remove the playlist pen from the site, cc @sundayz @katspaugh

**Comment by entonbiba** [comment]
@thijstriemstra fixed, it will now use demo.wav and stereo.mp3 from the media folder.

**Comment by entonbiba** [comment]
#2155 fixed
