### ISSUE TITLE
calling setPlaybackRate triggers fake pause event

### ISSUE THREAD

**Issue by undefined-ask** [katspaugh/wavesurfer.js#2113]
Wavesurfer version:"wavesurfer.js": "^4.2.0",

Browser and operating system:  Google chrome 87.0.4280.66 Windows 10 Version 1909

im using vue
```
mountWave(){
                ...
                this.wave.on('pause', ()=> {
                    this.pause = true;
                });
...
changeRate(name){
                this.rate = name;
                this.wave.setPlaybackRate(parseFloat(name.split('X')[0]))
            },
            },
```
The problem is , when i call changeRate using a button on my page, my wavesurfer receives a pause event but it's still playing
By the way, whenever i click on the waveform, audio is paused, is there any way that i can keep that playing? Cant find solution in document and google

**Comment by undefined-ask** [comment]
```
changeRate(name){
                this.rate = name;
                this.wave.playBackRate = parseFloat(name.split('X')[0])
            },
```
this works fine,so that must be some problem with wavesurfer.setPlaybackRate

**Comment by marizuccara** [comment]
Hi, you're right. Are you using  `WebAudio` backend? If you're using `WebAudio` backend, the pause event is triggered when setting the playback rate. I don't know for sure why this operation is performed.. 
@thijstriemstra , checking this piece of code, on `setPlaybackRate`:
``` 
            this.pause();
            this.playbackRate = value;
            this.play();
``` 
The rate in this case is only assigned to the variable? Because when the source is created, (in `createSource` method) the playback is assigned in this way:
``` 
  this.source.playbackRate.setValueAtTime(
            this.playbackRate,
            this.ac.currentTime
        );
```

**Comment by thijstriemstra** [comment]
> the pause event is triggered when setting the playback rate. I don't know for sure why this operation is performed..

I would imagine it's to prevent a weird transition from old to new playbackrate. But if it's not helping, hardly noticeable or even buggy, lets remove that pause/play call.

**Comment by marizuccara** [comment]
Okay, later I give it a concrete look, trying directly on code
