### ISSUE TITLE
playing after .stop() trims start of audio

### ISSUE THREAD

**Issue by jakemumu** [katspaugh/wavesurfer.js#2114]
### Wavesurfer.js version(s):
4.2.0

### Browser and operating system version(s):
Mac 10.15.17 - Safari 14

### Code needed to reproduce the issue:

```
wavesurfer.start()
wavesurfer.end() / wavesurfer.seekTo(0)
wavesurfer.start()
```

### Use behaviour needed to reproduce the issue:

I would expect the sample / sound / audio to sound the exact same every time this code is run, however on the second running on start() the beginning of the sample / audio is slightly cutoff. 

Amazing library, I'm using it to demo audio samples on a website, so it's critical I get the start of the audio file. 

Is this a known issue or is there a solution? I couldn't find anything online. 

Thanks, 

Jacob

**Comment by thijstriemstra** [comment]
is this a typo? `wavesurfer.end() / wavesurfer.seekTo(0)`

**Comment by jakemumu** [comment]
Hey sorry no I meant as in either or that line of code -- according to the docs both of those method should bring the audio back to the start of the file. 

But actually apologies I should have updated this -- I found the solution. This issue is only in safari, and only using the the MediaElement backend, switching the backend to WebAudio solves the issue. 

I'm gonna close this -- hopefully if anyone else hits this they can find the solution here, and if anyone whines you'll know the issue : ) 

Thanks for the amazing lib!
