### ISSUE TITLE
Can not detect seek event

### ISSUE THREAD

**Issue by james-jin-0903** [katspaugh/wavesurfer.js#2123]
Hi, 
I am using wavesurfer js with React and it looks great.
But I get an issue now.

I can not detect "seek" event and can not find a reason.

And when I click region it does not go to the current play time.

So please let me know the reason.

This image is when I click none region area.
At this time the playtime goes to the current selected position.
And I can detect seek event in this case.
![1](https://user-images.githubusercontent.com/58896466/100953852-5b467f00-354e-11eb-9c51-87de52310684.png)

But in this case ( when I click a region area) it does not change playtime.
So can not detect seek event too.
![2](https://user-images.githubusercontent.com/58896466/100954010-b5dfdb00-354e-11eb-9018-79330d7f5fcc.png)

Please help me if you know the reason.
Thank you.
```
  const [waveSurfer, setWaveSurfer] = useState(null);

.....
setWaveSurfer(
      WaveSurfer.create({
        container: ".waveform",
        height: 150,
        scrollParent: true,
        normalize: true,
        minimap: true,
        minPxPerSec: 5,
        plugins: [
          RegionsPlugin.create(),
          MinimapPlugin.create({
            height: 30,
            waveColor: "#ddd",
            progressColor: "#999",
            cursorColor: "#999",
          }),
          TimelinePlugin.create({
            container: ".waveformTimeLine",
          }),
        ],
      })
    );
```

```
waveSurfer.on("seek", (e) => {
      console.log(e);
    });
```

**Comment by marizuccara** [comment]
Hi, which version of wavesurfer are you using?

**Comment by thijstriemstra** [comment]
> So please let me know the reason.

can you reproduce the issue without react? Please re-open with non-react example code, closing for now.
