### ISSUE TITLE
How to set cursor height, it covers the entire screen

### ISSUE THREAD

**Issue by dassoop** [katspaugh/wavesurfer.js#2129]
Hey there,

The cursor is spanning the entire screen instead of just the height of the waveform. I have placed it in a div with a height property and tried it in a page with no divs.

Thank you for the amazing library!

**Comment by sundayz** [comment]
That shouldn’t happen. Do you have a short code example? Also what version of the library are you using.

**Comment by marizuccara** [comment]
Hi, I remember that I had this behaviour in older library version. Fixed with `position: 'relative'` style to the parent container of wavesurfer.

**Comment by thijstriemstra** [comment]
>  in older library version. 

Yep. @dassoop didn't bother to include the version information unfortunately, closing.

**Comment by dassoop** [comment]
Oh wow my apologies, you guys went to spam. Thank you very much for
responding.

-Lance
