### ISSUE TITLE
Help, how can i implement these things to my code.

### ISSUE THREAD

**Issue by Nickyg001** [katspaugh/wavesurfer.js#2133]
![wave](https://user-images.githubusercontent.com/33684734/101994636-265fc800-3cc4-11eb-9086-aa55be0780b4.jpg)
Hi, wavesurfer is great, but finding explanations around, tutorials, detailed and simple guides is a mess.

I managed to do some things but I would like to add other things that the documentation says is feasible but does not explain how exactly. if anyone can help me.

I would like to add to this basic setup already done:
1. the toggleMute (on / off) with the mute / unmute icon that changes as it is already done with the play / pause button
2. add a 0-100 slider to adjust the volume, vertically
3. I can put the total time of the track, elapsed time and remaining time, but how can I set it in (hours, minutes, seconds)? 1: 45 ': 12 "-> 00:00:00
4. How can I associate a title, author, year, cover image or other data to each mp3 link, to be recalled when the audio file is loaded into the player?

is it possible to expand the documentation with specific steps, video tutorials etc ?? thanks

**********************
**I post the code:**
[script.zip](https://github.com/katspaugh/wavesurfer.js/files/5683764/script.zip)
***********************

--------
HTML
----------
<!DOCTYPE html>
<html>

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>wavesurfer.js | Playlist</title>

    <link href="data:image/gif;" rel="icon" type="image/x-icon" />

    
    <link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" rel="stylesheet">

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Russo+One&display=swap" rel="stylesheet">

    
    <script src="https://unpkg.com/wavesurfer.js"></script>
    <script src="https://unpkg.com/wavesurfer.js/dist/plugin/wavesurfer.cursor.js"></script>

    
    <script src="app.js"></script>
</head>

<body>
    <div class="container">
        <div class="header">
            <ul class="nav nav-pills pull-right">
                <li><a href="/"><i class="glyphicon glyphicon-home"></i></a></li>
            </ul>

            <h1 itemprop="name">wavesurfer.js Playlist Demo</h1>
        </div>

        <div class="container">

            
            <div class="col-sm-2">
                <button class="btn btn-success btn-block" id="playPause">
                    <span id="play">
                        <i class="glyphicon glyphicon-play"></i>
                        Play
                    </span>

                    <span id="pause" style="display: none">
                        <i class="glyphicon glyphicon-pause"></i>
                        Pause
                    </span>
                </button>

                <button onclick="wavesurfer.toggleMute()">
                <i class="glyphicon glyphicon-volume-off"></i>
                mute
                </button>
            </div>

        </div>
        <div id="demo">
            <div class="row" style="margin: 30px 0">
                <div class="col-sm-12">
                    <div id="waveform">
                        
                    </div>

                </div>

                <div class="tooltip">00:00</div>
                <div>Total time: <span id="time-total">0</span> m:s:ms</div>
                <div>Current time: <span id="time-current">0</span> m:s:ms</div>
                <div>Ramaining time: <span id="time-remaining">0</span>m:s:ms</div>

                
                <div class="list-group" id="playlist">
                    <a href="https://dl.dropboxusercontent.com/s/7ffy6n9q8hnzqqc/Dua%20Lipa.mp3?dl=0" class="list-group-item">
                        <i class="glyphicon glyphicon-play"></i> song n.1
                        <span class="badge">0:21</span>
                    </a>

                    <a href="https://dl.dropboxusercontent.com/s/0hb5yob89y2fjqu/Push%20It%20%28Extended%20Mix%29.mp3?dl=1" class="list-group-item">
                        <i class="glyphicon glyphicon-play"></i> song n.2
                        <span class="badge">0:21</span>
                    </a>

                    <a href="https://stream6.mixcloud.com/secure/c/m4a/64/5/8/6/d/1aa6-0388-442f-986c-1ef7e1551074.m4a?sig=7dRu9zxDTuIj2CjItYe5WA" class="list-group-item">
                        <i class="glyphicon glyphicon-play"></i> song n.1
                        <span class="badge">0:21</span>
                    </a>

                </div>

                
                <div id="playlist">
                    <a href="https://stream11.mixcloud.com/secure/c/m4a/64/5/f/0/f/64c5-a78b-4b15-ad06-5d9e015ce9b6.m4a?sig=xGxFaisDdejvKZUIAWc_dQ" class="btn btn-danger">
                song n.2
                </a>

                </div>

            </div>
        </div>
</body>
</html>

------------------
JavaScript
----------------
// Create a WaveSurfer instance
var wavesurfer;

// Init on DOM ready
document.addEventListener('DOMContentLoaded', function() {
    wavesurfer = WaveSurfer.create({
        container: '#waveform',
        backend: 'MediaElement',
        mediaControl: true,
        waveColor: '#A8DBA8',
        progressColor: '#3B8686',
        barWidth: 3,
        barRadius: 3,
        cursorWidth: 3,
        height: 100,
        barGap: 4,
        cursorColor: 'red',
        responsive: true,
        fillParent: true,
        preload: true,

        plugins: [
            WaveSurfer.cursor.create({
                showTime: true,
                opacity: 1,
                customShowTimeStyle: {
                    'background-color': '#ff0000',
                    color: '#fff',
                    padding: '4px 12px',
                    'border-radius': '0 5px 5px 0',
                    'font-family': 'Russo One',
                    'font-size': '16px',

                }
            })
        ]

    });
});

// Bind controls
document.addEventListener('DOMContentLoaded', function() {

    var playPause = document.querySelector('#playPause');
    playPause.addEventListener('click', function() {
        wavesurfer.playPause();
    });

    // Toggle play/pause text
    wavesurfer.on('play', function() {
        document.querySelector('#play').style.display = 'none';
        document.querySelector('#pause').style.display = '';
    });
    wavesurfer.on('pause', function() {
        document.querySelector('#play').style.display = '';
        document.querySelector('#pause').style.display = 'none';
    });

    // The playlist links ID: #playlist
    var links = document.querySelectorAll('#playlist a');
    var currentTrack = 0;

    // Load a track by index and highlight the corresponding link
    var setCurrentSong = function(index) {
        links[currentTrack].classList.remove('active');
        currentTrack = index;
        links[currentTrack].classList.add('active');
        wavesurfer.load(links[currentTrack].href);
    };

    // Load the track on click
    Array.prototype.forEach.call(links, function(link, index) {
        link.addEventListener('click', function(e) {
            e.preventDefault();
            setCurrentSong(index);
        });
    });

    // Play on audio load
    wavesurfer.on('ready', function() {
        wavesurfer.play();
    });

    wavesurfer.on('error', function(e) {
        console.warn(e);
    });

    // Go to the next track on finish -> (passa alla prossima traccia)
    wavesurfer.on('finish', function() {
        setCurrentSong((currentTrack + 1) % links.length);
    });

    // Load the first track -> (carica la prima traccia)
    setCurrentSong(currentTrack);

    wavesurfer.on('audioprocess', function() {
        if (wavesurfer.isPlaying()) {
            var totalTime = wavesurfer.getDuration(),
                currentTime = wavesurfer.getCurrentTime(),
                remainingTime = totalTime - currentTime;

            document.getElementById('time-total').innerText = totalTime.toFixed(1);

            document.getElementById('time-total').innerText = (totalTime / 60).toFixed(2);

            document.getElementById('time-current').innerText = (currentTime / 60).toFixed(2);
            document.getElementById('time-remaining').innerText = (remainingTime / 60).toFixed(2);
        }
    });

});

**Comment by marizuccara** [comment]
Hi! It would be easier if you wrote your example code in a code sandbox, of something similar, instead of copying it as text or in a zip (which is less safe).
Regarding your questions, I think that they are not very related to wavesurfer, but rather to how bind API that wavesurfer offers, to your code (which can be write in vanilla JS, or using other frameworks, implementing your graphic and DOM elements with plain HTML and CSS or using some graphic framework).

**toogleMute**: 
- implement a button

-  listen to onClick event 

- use `toggleMute()` API

You can find methods at:
https://wavesurfer-js.org/docs/methods.html
or, more detailed, at:
https://wavesurfer-js.org/api/class/src/wavesurfer.js~WaveSurfer.html#instance-method-toggleMute
And example at:
https://wavesurfer-js.org/example/mute/index.html

**Volume**:

- impement a vertical slider with a range 

- listen to onChange event

- assign the current slider value to `setVolume(newValue)` API. `newValue` accepts values between 0 and 1 so, basing which range you assigned to your slider, you may have to do a proportion. 

Documentation at;
https://wavesurfer-js.org/api/class/src/wavesurfer.js~WaveSurfer.html#instance-method-setVolume 

There is not a direct example of volume setting, but we could provide it.

**Formatted time**
Usually time returned from wavesurfer is in seconds. Use some JS method and time conventions to convert seconds in formatted time. For example, you can use:
```
function formatDuration (seconds, giveMilliseconds) {
    const mill = parseFloat(seconds).toFixed(3);
    const secs = Math.floor(seconds % 60);
    const minutes = Math.floor(seconds / 60) % 60;
    const hours = Math.floor(seconds / 3600);
    let res = "";
 
    giveMilliseconds ?
        res = (("00" + hours).slice(-2) + ":" + ("00" + minutes).slice(-2) + ":" + ("00" + secs).slice(-2) + "." + mill.slice(-3))
        :
        res = (("00" + hours).slice(-2) + ":" + ("00" + minutes).slice(-2) + ":" + ("00" + secs).slice(-2))
      
    return res;
}
```
or something else, which you can find googling, for example:
https://stackoverflow.com/questions/1322732/convert-seconds-to-hh-mm-ss-with-javascript

**Association image ecc**
Depends on how you fetch your data and which info you have. Having these info, you can play with JS and HTML to associate them.

**Comment by Nickyg001** [comment]
@marizuccara Maria ma sei Italiana??

**Comment by sundayz** [comment]
We can't make your website or app for you. Maria's guide is pretty detailed. if you have any more questions feel free to ask.
