### ISSUE TITLE
how do I detune wavesurfer audio without changing playback rate

### ISSUE THREAD

**Issue by activekaiser1** [katspaugh/wavesurfer.js#2134]
how do I detune wavesurfer audio without changing playback rate please used to have an example but its been taken off github?

**Comment by activekaiser1** [comment]
found it i was wondering how you could change the playback rate without changing pitch

**Comment by marizuccara** [comment]
Hi! If you're using `WebAudio` backend, you can set `detune` audio param, in `cents`, on source node:
You can do this in this way:
`wavesurfer.backend.source.detune.value = VALUE`

Maybe we can expose an API and perform this operation internally, if needed..

**Comment by thijstriemstra** [comment]
no feedback, closing.
