### ISSUE TITLE
I want to use a 2-channel waveform and save the JSON data generated by the waveform; however, after using exportpcm, the result can only be null

### ISSUE THREAD

**Issue by guisha** [katspaugh/wavesurfer.js#2137]
var wavesurfer = WaveSurfer.create({
			container: '#waveform',
			progressColor: 'red',
			waveColor: "#666666",
			height: 65,
			fillParent:true,
			forceDecode:true,
			partialRender:true,
			pixelRatio:1,
			splitChannels: true,
			barWidth: 0,
			
		
		});
		 wavesurfer.load("music/work.mp3"); 
		wavesurfer.on("ready", function() {
			
			console.log(wavesurfer.exportPCM('1024','10000',true,0));
		})
       result：
         Promise {<resolved>: "[null,null,null,null,null,null]"}；
       How to solve this problem！

**Comment by sundayz** [comment]
#1954 

possibly related #2091 

Does the waveform display, or do you see a single line?

Also, in English please if possible.

**Comment by guisha** [comment]
waveform display

**Comment by guisha** [comment]
I want to use a 2-channel waveform and save the JSON data generated by the waveform; however, after using exportpcm, the result can only be null

**Comment by thijstriemstra** [comment]
@guisha can you rename the ticket title in english?

**Comment by guisha** [comment]
No one?

**Comment by entonbiba** [comment]
continue on this ticket #1954
