### ISSUE TITLE
After remote preload peak data loaded, How to redraw waveform by raw buffer data ?

### ISSUE THREAD

**Issue by jimmyyao88** [katspaugh/wavesurfer.js#2139]
### Wavesurfer.js version(s):
latest version

Hello there. 
I load wavesurfer with peaks params:
` wavesurfer.load(this.audio, peaks.data);`
After trigger the play function, wavesurfer will start to load remote audio file.
And fire the ready event after the audio file was completed loaded. And I call drawBuffer Function within the ready event:
`wavesurfer.on('ready', () => {
        wavesurfer.drawBuffer();
      });`
 But it wont redraw waveform by raw buffer data, it will still use the cached wavefrom json data from remote. I wonder how to make wavesurfer to redraw data not use the provided peaks data after the whole audio file was downloaded. The waveform from origin buffer data will more accurate than server provided I think. Any idea? THX

**Comment by marizuccara** [comment]
Hi, you can first setPeaks and then draw them. In this way:
`  wavesurfer.backend.setPeaks(waveform, duration);`
 `wavesurfer.current.drawBuffer();`

**Comment by jimmyyao88** [comment]
@marizuccara After dig the source code, I set peak to null , then redraw, now everything goes well. THX!
`this.wavesurfer.on('ready', () => {
        this.wavesurfer.backend.setPeaks(null);
        this.wavesurfer.drawBuffer();
      });`
