### ISSUE TITLE
How to revise sampleRate?

### ISSUE THREAD

**Issue by zw76859420** [katspaugh/wavesurfer.js#2141]
Hello, Thanks for this useful program.
  we hava audio data which samplerate is 8K. I want to know how to revise the samplerate when using wavesurfer, and default samplerate is 44100.
Thanks for your kindly reply.

**Comment by whaozl** [comment]
So, ehm, I also have the same problem.

**Comment by thijstriemstra** [comment]
Pass in your own AudioContext with the correct samplerate. Use the `audioContext` option, see https://wavesurfer-js.org/docs/options.html

**Comment by sundayz** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/AudioContext

Scroll down to see `sampleRate` and `latencyHint`. On iOS you cannot set the sample rate, it will be decided by the browser

**Comment by zw76859420** [comment]
> https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/AudioContext
> 
> Scroll down to see `sampleRate` and `latencyHint`. On iOS you cannot set the sample rate, it will be decided by the browser

Thanks a lot, your answer is very useful for me.
By the way, How to plot spectrogram with RGB, not gray mode?

**Comment by whaozl** [comment]
Thank you very much.

**Comment by sundayz** [comment]
> By the way, How to plot spectrogram with RGB, not gray mode?

I don't know how to use the spectrogram plugin. Looks like #1436 might help

In the PR linked in that issue they mention you can use https://www.npmjs.com/package/colormap to generate a color map. 

Open a new issue if you still need help :)
