### ISSUE TITLE
Detect amounts of silence in an audio

### ISSUE THREAD

**Issue by Israel001** [katspaugh/wavesurfer.js#2142]
### Wavesurfer.js version(s):

This is everything related to wavesurfer which i loaded in my header script: 

```
<script src="https://unpkg.com/wavesurfer.js"></script>
<script src="https://unpkg.com/wavesurfer.js@4.1.1/dist/plugin/wavesurfer.microphone.min.js"></script>
<script src="https://unpkg.com/wavesurfer.js@4.1.1/dist/plugin/wavesurfer.timeline.js"></script>
```

### Browser and operating system version(s):

Browser: Chrome v84.x.x
OS: Linux (Ubuntu 20+)

### Code needed to reproduce the issue:

I don't have an issue with this library. I want to ask if it is possible for this library to assist me in implementing a feature. So right now, i am using this library with ```Recorder.js``` library to draw waveforms from sounds recorded via the browser. However, sometimes, no sound is captured, then this library draws a straight line wave, which i am trying to avoid. How can this library help me to detect when the wave has a lot of straight line (i.e. too much silence), so i can choose not to display the wave.

I've tried to check the docs if there is any function i can call or any property i can access on the `WaveSurfer` object but couldn't find any.

**Comment by thijstriemstra** [comment]
did you try searching for 'silence' in this repository: https://github.com/katspaugh/wavesurfer.js/search?q=silence&type=issues

**Comment by entonbiba** [comment]
@Israel001 add `barWidth: 1` this will remove the silent lines.
![image](https://user-images.githubusercontent.com/5193884/105643588-bade4e00-5e5e-11eb-9a88-6654b7821653.png)

**Comment by entonbiba** [comment]
@Israel001 adding barMinHeight: 0, should remove the silent lines, do you have the audio file we can test?

**Comment by Israel001** [comment]
@entonbiba I don't want to remove the silent lines, I want to know if the audio has a specific percentage of silence and then display a message to the user. I have found an alternative way of doing this without using this library. Thanks for trying to help.

**Comment by truong24hdev** [comment]
@Israel001 Hi, I want to detect start time silent in audio files. Could you tell me the way of doing this that you found, please? thank you so much

**Comment by tejasri12345** [comment]
> @Israel001 Hi, I want to detect start time silent in audio files. Could you tell me the way of doing this that you found, please? thank you so much

Hai.. I need this answer can you help me

**Comment by katspaugh** [comment]
You can find an example of silence detection here: https://github.com/wavesurfer-js/wavesurfer.js/blob/master/example/annotation/app.js#L138-L203

**Comment by tejasri12345** [comment]
Thank you so much for your reply. I want to detect silent parts with
timestamps in .wav files. Is this possible?
