### ISSUE TITLE
Throw  "TypeError: the given value is not a Promise"  when I call wavesurfer.load method

### ISSUE THREAD

**Issue by zoonware** [katspaugh/wavesurfer.js#2143]
Throw  TypeError: the given value is not a Promise  when I call wavesurfer.load method
This audio can be played but no minimap can be added to the main waveform.
Environment: Angular 8.0 + Chrome66 + wavesurfer.js 4.3.0  and 3.0.0 and 2.2.1 (I have been tried  three versions)
This is no issues on Chrome 87.

**Comment by thijstriemstra** [comment]
> Chrome66

That's really old.

> This is no issues on Chrome 87.

ok so it's fixed since then. What's the issue?

**Comment by sundayz** [comment]
Don't await `load`, it won't return a promise. Listen for the 'ready' event to know when it loaded successfully. Maybe in future versions we can make load return a promise.
