### ISSUE TITLE
Refactor WebAudio load

### ISSUE THREAD

**Issue by sundayz** [katspaugh/wavesurfer.js#2146]
Hi, I'd like to refactor the load() function used here: https://github.com/katspaugh/wavesurfer.js/blob/master/src/wavesurfer.js#L1428

I've spent an hour trying to make the WebAudio backend fire some kind of ready event, either "ready" or "waveform-ready" unsuccessfully. Can anyone explain why the function currently works like it does so I avoid breaking something when I refactor this?

When I use WebAudio and no peaks, the waveform draws and then no ready event is ever emitted.
When I use WebAudio and peaks, waveform-ready is never fired. It looks like it's also waiting for an "interaction" event to start loading the audio. If I call `wavesurfer.fireEvent("interaction")` myself, it incorrectly sends a request for the audio like `mysite.com/[HTMLMediaElement]`, looks like it's calling toString on an object.

If I clean this up, do I need to wait for user interaction before loading the audio? Only with this backend? Or is the interact event not actually needed here

Related:
#1244
#2007

**Comment by thijstriemstra** [comment]
I'm not sure anymore what the interaction event is supposed to do. Perhaps we can start with making a class/location that organizes all event names into constants. E.g. `const INTERACTION = 'interaction'` and use these event name constants throughout the codebase. Then we can start with refactoring/removing events.

**Comment by sundayz** [comment]
Closing because the issue I had is fixed by 658bd921be60a64192331ce8511bf1bce68cc4ec
