### ISSUE TITLE
Allow arrayOfPeaks to be specified without specifying backend: 'AudioElement'

### ISSUE THREAD

**Issue by SeanBannister** [katspaugh/wavesurfer.js#215]
On http://www.wavesurfer.fm/example/audio-element/ it mentions if you already have the pre-rendered peak data you can specify it as the second value in `wavesurfer.load('demo.mp3', arrayOfPeaks);` currently if you don't specify `backend: 'AudioElement'` it ignores arrayOfPeaks and calculates the waveform using the Web Audio API. I'd like to propose that wavesurfer accepts an arrayOfPeaks even when using the Web Audio API, because it allows us to show the waveform much quicker than loading the file in the browser and calculating the waveform.

My use case for this: I'm loading SoundCloud files on my website and I can grab the arrayOfPeaks from SoundCloud (For example http://waveformjs.org/w?url=http://w1.sndcdn.com/AnWkyYhipXeH_m.png), but I'd still like to use the Web Audio API for the extra features it provides (Thankfully SoundCloud accepts cross origin requests).

I'll eventually get around to coding this but hoping someone beats me to it. I'll also create an example page showing how to use WaveSurfer.js SoundCloud as it makes more sense to use WaveSurfer.js than WaveForm.js due to its extra features.

**Comment by katspaugh** [comment]
Added in #734.
