### ISSUE TITLE
How to set start and end time manually.

### ISSUE THREAD

**Issue by adham-lxt** [katspaugh/wavesurfer.js#2157]
I've been trying to make something like <input> to allow the user to set the start and end date of a specific region instead of using the mouse and drag a region on the waveform.
Dragging actually is working pretty well, but I want the user to have a second option to set manually the start and end time for a region on the waveform through (input fields/text fields ... whatever name fields :D ) and it get drawn too.

So is there anyway to do so ?

**Comment by marizuccara** [comment]
Hi, you can use the method:
`wavesurfer.addRegion(region)`

where region is an object with `start`, `end`, `color`..

For more options, you can see here:

https://wavesurfer-js.org/plugins/regions.html

**Comment by sundayz** [comment]
you can use the region.update() function and pass the new start and end. You don't have to update both at the same time.

```js
const region = wavesurfer.addRegion({ your params here })

// when the input field is updated:
region.update({
    start: 123,
    end: 456,
});
```

**Comment by adham-lxt** [comment]
> Hi, you can use the method:
> `wavesurfer.addRegion(region)`
> 
> where region is an object with `start`, `end`, `color`..
> 
> For more options, you can see here:
> 
> https://wavesurfer-js.org/plugins/regions.html

Thanks for your reply. this actually works,  but I got another issue, where the region is not drawn after being created manually, 
So I get the start, end time from the user, and the color is constant for me, but all what I get is nothing on the screen as show in the screenshot below

![waveform](https://user-images.githubusercontent.com/66368677/104847594-a1328900-58e9-11eb-9e4f-976c1acad5d4.png)

This is the code of button that adds regions :
```
<Button style={{ marginLeft: '15px' }}
                  onClick={() => {
                    if (this.wavesurfer.getDuration() >= Number(this.state.end)) {
                      this.props.addRegion({
                        start: Number(this.state.start), // time in seconds
                        end: Number(this.state.end), // time in seconds
                        color: 'hsla(100, 100%, 30%, 0.1)'
                      })
                    }
                  }}
                > Add Region</Button>
```

**Comment by marizuccara** [comment]
Hi, why `this.props.addRegion(..)` and not `this.wavesurger.addRegion(..)`.
 this. props is wavesurfer for you?

**Comment by adham-lxt** [comment]
> Hi, why `this.props.addRegion(..)` and not `this.wavesurger.addRegion(..)`.
> this. props is wavesurfer for you?

Yes this.props = this.wavesurfer for me

**Comment by marizuccara** [comment]
so why here:
` if (this.wavesurfer.getDuration() >= Number(this.state.end))`
are you using this.wavesurfer?

It's strange that `addRegion` not works. Maybe you can share your example in code sandbox? Because trying creating a region with addRegion works for me

**Comment by adham-lxt** [comment]
> so why here:
> ` if (this.wavesurfer.getDuration() >= Number(this.state.end))`
> are you using this.wavesurfer?
> 
> It's strange that `addRegion` not works. Maybe you can share your example in code sandbox? Because trying creating a region with addRegion works for me

Actually I can't share an example, as this is a part of a project and alot of things are connected together. But I can share with you the full wavesuerfer.js file if this would help and I can share what's inside both this.wavesuerfer and this.props.

please tell me what would be more helpful, and thanks for your help.

**Comment by adham-lxt** [comment]
Thanks it worked :D
