### ISSUE TITLE
Pause when scrolled out of viewport

### ISSUE THREAD

**Issue by Hrishikesh-K** [katspaugh/wavesurfer.js#2159]
This is a question.

I'm trying to add multiple instances of wavesurfer.js on my page. I have my HTML structure like this:

```HTML
<div class = "audio-player" src = "/aud1.mp3"></div>
<div class = "audio-player" src = "/aud2.mp3"></div>
```

and my script is like this (loaded in `<head>` wih `defer` attribute after the `wavesurfer.js` script):

```JS
window.addEventListener('load', function() {
  var mediaA = document.querySelectorAll('.audio-player')
  if (mediaA != null) {
    mediaA.forEach(medium => {
      var wavesurfer = WaveSurfer.create({
        /* wavesurfer config */
      })
      wavesurfer.load(medium.getAttribute('src'))
      window.addEventListener('scroll', function() {
        if (outOfViewport(medium) {
          wavesurfer.pause()
        }
      })
    })
  }
}
```

Basically, I'm trying to pause the wavesurfer instance once it's scrolled out of viewport and for that, this piece of code works perfectly (the `outOfViewport` is a helper function which returns a boolen based on my conditions).

As you can see from my code, I'm adding multiple scroll event listeners to the window and I would like to avoid that. I would like to group all my scroll events into one and make it a single function. However, I don't know how I can access the already created wavesurfer instance.

I'm looking for something like:

```JS
window.addEventListener('scroll', function() {
  /* my other scroll stuff */
  var mediaA = document.querySelectorAll('.audio-player')
  if (mediaA != null) {
    mediaA.forEach(medium => {
      if (outOfViewport(medium) {
        medium.paue()
      }
    }
  }
}
```

except, the `medium.pause()` should actually be called on the wavesurfer instance and not the HTML element (like it's doing in the code I posted).

**Comment by thijstriemstra** [comment]
> However, I don't know how I can access the already created wavesurfer instance.

You create wavesurfer instances like this:

```javascript
var wavesurfer = WaveSurfer.create({
        /* wavesurfer config */
      })
```

so store that instance in an array or object so you can access it later:

```javascript
let surfers = [];

var ws = WaveSurfer.create({
        /* wavesurfer config */
      })
surfers.push(ws);

// later
surfers[0].pause();
```

**Comment by Hrishikesh-K** [comment]
Yes, this was indeed easy. I should have been able to think of it. Thanks a lot for the help!
