### ISSUE TITLE
WaveSurfer.js / ffmpeg.wasm project

### ISSUE THREAD

**Issue by BaileyMcKelway** [katspaugh/wavesurfer.js#2162]
![Screen Shot 2021-01-19 at 4 44 14 PM](https://user-images.githubusercontent.com/25776618/105096994-e388d100-5a75-11eb-86d4-6eb27989003b.png)

[https://mediaedits.io/](https://mediaedits.io/)

Hey recently built a project with WaveSurfer.js. Really enjoyed using this library; there is just such solid documentation and resources online.

I saw you all featured some previous projects; just wanted to share mine! Currently it isn't open source (I want to build it out further) but there is a live demo at mediaedits.io

**Comment by marizuccara** [comment]
Great job! It's fantastic like WebAudio API is so flexible to allow handling audio manipulation in wasm, allowing to play with it in Web!

**Comment by thijstriemstra** [comment]
nice! please open a pr that adds it to https://github.com/katspaugh/wavesurfer.js/blob/gh-pages/projects/index.html

**Comment by BaileyMcKelway** [comment]
Alright copy that!

**Comment by BaileyMcKelway** [comment]
#2169
