### ISSUE TITLE
[Vue warn]: Error in mounted hook: "Error: Container element not found"

### ISSUE THREAD

**Issue by Benoit1980** [katspaugh/wavesurfer.js#2163]
Hello,

I am using Wavesurfer 4.4.0

"wavesurfer.js": "^4.4.0"

In vue, I am trying to use it as:

```
<div id="waveform" ref="waveform"></div>


import WaveSurfer from 'wavesurfer.js';


   mounted() {
        this.createWaveSurfer();
},


methods: {
        createWaveSurfer() {
            var wavesurfer = WaveSurfer.create({
                container: #waveform,
                waveColor: 'violet',
                progressColor: 'purple'
            });
            wavesurfer.on('ready', function () {
                wavesurfer.play();
            });
                wavesurfer.load(
                "https://mywebsite.com/storage/text/1611243371.wav"
            );
        },
}
```

I keep receiving this error:

[Vue warn]: Error in mounted hook: "Error: Container element not found"

Any idea why please?

Thank you.

**Comment by sundayz** [comment]
Change: 
```js
      var wavesurfer = WaveSurfer.create({
          container: #waveform,
          waveColor: 'violet',
          progressColor: 'purple'
      });
```

to:

```js
    var wavesurfer = WaveSurfer.create({
        container: this.$refs.waveform,
        waveColor: 'violet',
        progressColor: 'purple'
    });
```

Using Vue with libraries like wavesurfer can be tricky sometimes.

**Comment by Benoit1980** [comment]
Thanks.
I have already tried that and also this:
```
    var wavesurfer = window.WaveSurfer.create({
        container: this.$refs.waveform,
        waveColor: 'violet',
        progressColor: 'purple'
    });
```

But no luck.

**Comment by sundayz** [comment]
Show the full .vue file

**Comment by Benoit1980** [comment]
No problem thank you

HTML
```
<template>
 <div ref="waveform"></div>
</template>
```

JS:
```
import WaveSurfer from 'wavesurfer.js';

data() {
        return {

       }
    },
   mounted() {
        this.createWaveSurfer();
},

methods: {
        createWaveSurfer() {
           var wavesurfer = WaveSurfer.create({
                container: #waveform,
                waveColor: 'violet',
                progressColor: 'purple'
            });
                wavesurfer.on('ready', function () {
                wavesurfer.play();
            });
                wavesurfer.load(
                "https://mywebsite.com/storage/text/1611243371.wav"
            );
        },
}
```

**Comment by sundayz** [comment]
Are you writing `container: "#waveform"` or `container: #waveform` because there's a difference between the first and the second. The second will not work.

In your latest post you removed the `id` attribute.
`container: "#waveform"` will add wavesurfer to a div that looks like this: `<div id="#waveform"></div>`
While `container: this.$refs.waveform` will look for a div that looks like this: `<div ref="waveform"></div>`

**Comment by Benoit1980** [comment]
My apology, I made a mistake on my last copy and paste. I re-edited the above post.

**Comment by sundayz** [comment]
Are you showing the full component? Are you using `v-if` somewhere to hide the `<div>`?

Refs should be available in the mounted hook, you can test this easily:

```js
<template>
    <div ref="myref"></div>
</template>

<script>
export default {
    mounted() {
        console.log(this.$refs.myref); // should not be undefined
    }
}
</script>
```

In my project I load WaveSufer the same way as you do and it works.

**Comment by Benoit1980** [comment]
Please give me till the weekend, and I will recheck it on my local machine as I am away at the moment.
I will keep you updated.

Thank you so much for your efforts :-)
