### ISSUE TITLE
Waveform is sometimes flat

### ISSUE THREAD

**Issue by Hrishikesh-K** [katspaugh/wavesurfer.js#2165]
Hello.

I'm having troubles with loading the waveform, only sometimes. It's mostly on the first-time page load that the generated waveform is flat, like this:

![image](https://user-images.githubusercontent.com/11403551/105568522-01994e80-5d60-11eb-99e8-c6da88337704.png)

I'm assuming that I can still see each bar because of the `barMinHeight`, or else it would have been invisible.

Generally, after the page is reloaded, the waveform turns out to be correct, like this:

![image](https://user-images.githubusercontent.com/11403551/105568531-17a70f00-5d60-11eb-9b0e-5fffc3eea0df.png)

This doesn't happen in my local development environment, probably because `localhost` is fast enough to load the audio file and I haven't tried simulating slow network yet. However, on the production version on the server (Netlify), this happens almost on every first-time page load in incognito. So, I'm guessing, it's working fine on subsequent page loads due to cache.

The audio file is pretty small, just 39 seconds and < 1 MB in size. Even then, today I tried to supply a generated peak data as mentioned in the documentation. The result is still the same.

I'm supplying the audio file to my `container` like this:

```HTML
<div class = "audio-player" src = "assets/aud1.mp3"></div>
```

and the generated peak data JSON is available at `assets/aud1.json`.

And then loading the waveform like this:

```JS
window.addEventListener('load', function() {
  var mediaA = document.querySelectorAll('.audio-player')
  if (mediaA != null) {
    mediaA.forEach(medium => {
      var wavesurfer = WaveSurfer.create({
        height: 75,
        barWidth: 3,
        pixelRatio: 1,
        barMinHeight: 1,
        normalize: true,
        responsive: true,
        container: medium,
        partialRender: true,
        waveColor: '#FFE078',
        cursorColor: '#03A9F4',
        progressColor: '#03A9F4'
      })
      var source = medium.getAttribute('src')
      fetch(source.substring(0, source.length - 3) + 'json').then(peaks => {
        wavesurfer.load(source, peaks.data)
      })
  }
})
```

The above script is placed in `<head>` after the wavesurfer script and both are using `defer` attribute.

Here's a live demo: https://600ba20690370f0007e10771--hrishikeshk.netlify.app/projects/dropbox/#radio-ads

Can someone please guide me on what I might be doing wrong? I'm using `wavesurfer v4.4.0`.

My website's Hugo source code is available here: https://www.github.com/Hrishikesh-K/Portfolio/tree/v2/

**Comment by sundayz** [comment]
Is your fetch function a custom function made by you, or the browser fetch? Maybe I am wrong but this is how fetch is usually used with JSON:

```fetch('http://example.com/movies.json').then(response => response.json()).then(data => console.log(data));```

I have never seen this bug happen when generated peaks are supplied. So I think your problem is you don’t call response.json() first on the result of fetch, and you’re not actually using the peaks.

**Comment by Hrishikesh-K** [comment]
Oh yes, I was using the browser fetch, so your code does help. Now, the waveform is always shown correctly. Thanks a lot for that.

However, now it seems like the `ready` event is not fired. I now have it setup like this:

```JS
window.addEventListener('load', function() {
  var mediaA = document.querySelectorAll('.audio-player')
  if (mediaA != null) {
    mediaA.forEach(medium => {
      var wavesurfer = WaveSurfer.create({
        /* config as above */
      })
      var source = medium.getAttribute('src')
      fetch(source.substring(0, source.length - 3) + 'json').then(response => response.json()).then(peaks => {
        wavesurfer.load(source, peaks.data)
      })
      wavesurfer.on('ready', function() {
        medium.parentElement.querySelector('.time-display').innerHTML = new Date(wavesurfer.getCurrentTime() * 1000).toISOString().substr(14, 5) + ' / ' + new Date(wavesurfer.getDuration() * 1000).toISOString().substr(14, 5)
      })
  }
})
```

The time is not set unless the file is played. It works when its played because I have added the same function for `audioprocess` event. It was working fine in my previous setup even when the waveform did not generate as you can see in my first screenshot. Is there any workaround for this?

The live version is now available here: https://600bd6e182123b000706a5d9--hrishikeshk.netlify.app/projects/dropbox/#radio-ads

**Comment by entonbiba** [comment]
@Hrishikesh-K try it with the sample wav json data file like below and see if you still experience the issue,

``` javascript
      var source = medium.getAttribute('src')
      fetch('https://wavesurfer-js.org/example/media/demo-peaks.json')
      .then(response => {
            if (!response.ok) {
                  throw new Error('HTTP error ' + response.status);
            }
            return response.json();
      })
      .then(peaks => {

            // load peaks into wavesurfer.js              
            wavesurfer.load(source, peaks);

      })
      .catch(e => {
            console.error('error', e);
      });
```

**Comment by Hrishikesh-K** [comment]
Thanks @entonbiba. I'm now getting mixed results, but it's probably fixed.

With your code from above, I'm getting a waveform + the `ready` event is working fine. All good.

1. So, I replaced, `'https://wavesurfer-js.org/example/media/demo-peaks.json'` with `source.substring(0, source.length - 3) + 'json'` from my code as above and it seems to work fine too.

2. However, just like the demo code from https://wavesurfer-js.org/faq/ and my previous code, when I change `wavesurfer.load(source, peaks)` to `wavesurfer.load(source, peaks.data)`, neither the waveform, nor the `ready` event works.

3. Then, if I keep my code from the previous reply untouched, the `ready` event isn't working as I have mentioned.

4. Finally, if I change `wavesurfer.load(source, peaks.data)` to `wavesurfer.load(source, peaks)` in that code, none of the 2 things work.

So my question is, it seems like, option 1 is working perfectly for my use case, but I don't understand why. Shouldn't it be `peaks.data` instead of `peaks`?

My JSON is available here: https://600bd6e182123b000706a5d9--hrishikeshk.netlify.app/projects/dropbox/assets/aud1.json.

**Comment by Hrishikesh-K** [comment]
After some `console.log` statements, I have figured out that, `peaks.data` is indeed needed and that my code from https://github.com/katspaugh/wavesurfer.js/issues/2165#issuecomment-765886651 was correct. It produces the same result with my JSON and the demo JSON.

**Comment by entonbiba** [comment]
@Hrishikesh-K do you have CORS enabled on that mp3 file? add the headers to the response so we can test your mp3/json using codepen

**Comment by Hrishikesh-K** [comment]
Done. All CORS enabled `(access-control-allow-origin: *)`.

Here's the:
MP3: https://600c60595d5ff20009ef949d--hrishikeshk.netlify.app/projects/dropbox/assets/aud1.mp3
JSON: https://600c60595d5ff20009ef949d--hrishikeshk.netlify.app/projects/dropbox/assets/aud1.json

Thanks for taking a look into this.

**Comment by sundayz** [comment]
To be able to chain promises with .then() syntax you need to return them. so its `return response.json()` not just `response.json()` since that returns a promise.

If hugo supports ES6 (im sure theres a way to make it transpile the code) then I recommend using async/await syntax because you won't be confused by errors like this.

So the solution is:
```js
var source = medium.getAttribute('src')
fetch(source.substring(0, source.length - 3) + 'json').then(response => {
  return response.json() // added return here
}).then(peaks => {
  wavesurfer.load(source, peaks.data)
})
```

or with async syntax:
```js
var source = medium.getAttribute('src')
const response = await fetch(source.substring(0, source.length - 3) + 'json');
const peaks = await response.json();
wavesurfer.load(source, peaks.data);
```

**Comment by Hrishikesh-K** [comment]
Sadly, both of them didn't work. As in, both work to load the waveform, but the `ready` event is still not fired. 😢

**Comment by sundayz** [comment]
Does the ready event run when you click the waveform or when you do waveform.fireEvent('interaction') manually?

**Comment by Hrishikesh-K** [comment]
Yes, it does run when I click the waveform, as reported by my `console.log` statement.

**Comment by sundayz** [comment]
Either add `backend: 'MediaElement'` to your params. This will use HTML5 audio instead of WebAudio API. It has some limitations on iOS for example you cant set the volume or playback rate with that backend.

Or you can keep the deafult backend (WebAudio) and just add `wavesurfer.fireEvent('interaction')` right after your load() call. It won't cause any problems. It's probably like that because mobile browsers expect the user to interact with the site before allowing audio playback. In this case it's not actually being blocked though so it servers no purpose. Maybe in the past the browser behaved differently and that's why the requirement for interaction to fire exists.

**Comment by Hrishikesh-K** [comment]
Since I needed to manipulate volume, I could not use `MediaElement`. But, `wavesurfer.fireEvent('interaction')` worked perfectly. Thanks a lot @sundayz @entonbiba. You guys have helped a lot! Much appreciated.
