### ISSUE TITLE
[question] Help with custom renderer & calculations

### ISSUE THREAD

**Issue by johnpaulmedina** [katspaugh/wavesurfer.js#2174]
@thijstriemstra @sundayz 
Wanted to see if either of you can help me out on a custom renderer. I found other previous issues that showed code examples to setup the CustomRenderer.

So, in short: I got my own renderer running but my issue is that I want to remove the reflections and have the bars come from the bottom up. See screenshots for example:

What I have:
<img width="1225" alt="Screen Shot 2021-01-25 at 1 31 22 PM" src="https://user-images.githubusercontent.com/1139439/105749614-a60ec280-5f11-11eb-9f2a-057d35e5745c.png">

What I want:
<img width="769" alt="Screen Shot 2021-01-25 at 1 33 26 PM" src="https://user-images.githubusercontent.com/1139439/105749808-ee2de500-5f11-11eb-8323-a8a9c880fe05.png">

Additionally, I wanted to know how can I calculate the percentage of overlap that occurs on the channel peaks `splitPeaks`, the amount of silence on the `mergedPeaks`, the percentage of audio on each channel vs the `mergedPeaks`.

Ultimately, I have a split audio with a customer on left and an agent on the right. I would like to be able to see the stats below. I have no understanding of the audio and decoded audio peaks so I am lost.

Agent: 73%
Customer: 27%
Overlap: 3%
Silence: 4%

And if it's not too much to ask - how can I use the annotations to create markers similar to this:

<img width="242" alt="Screen Shot 2021-01-25 at 1 34 26 PM" src="https://user-images.githubusercontent.com/1139439/105749920-11f12b00-5f12-11eb-9a11-808d05f92e49.png">

Any guidance would be appreciated.

**Comment by sundayz** [comment]
Maybe taking a look around here will help with drawing just the top half of the waveform:

https://github.com/katspaugh/wavesurfer.js/blob/d2005178dbd2deeb243b5362af1cafd1f3b29d66/src/drawer.multicanvas.js#L509

https://github.com/katspaugh/wavesurfer.js/blob/d2005178dbd2deeb243b5362af1cafd1f3b29d66/src/drawer.multicanvas.js#L343

To draw annotations you can either use the DOM or assuming your custom renderer uses <canvas> or WebGL then you can just draw those shapes yourself by calculating their X position.

If you want to know at what X position to draw an indicator that should appear 5 seconds into the track then you can use the formula: `(5 / totalDurationInSeconds) * rendererWidth` and that should return the X coordinate on the MultiCanvas renderer of where to draw your indicator. To get the canvas width you can check `wavesurfer.drawer.width` and `wavesurfer.drawer.getWidth()`. They both return the same number for me but I'm not sure what the difference is and which one you should use.

As for calculating % overlap. There's probably some maths involved. What PCM data is ultimately is an array of samples in time, if you have normalized them then 0 would represent total silence and 1 would represent peak loudness.

So lets say you have 2 channels, you can iterate both arrays and find at what index do both arrays contain a 0, and that tells you where you find total silence in both channels at the same time. You have to refine this algorithm yourself, for example to set a limit on what you consider silence e.g. 0.05 or lower. Then you can apply that same principle to find overlaps, but I havent given this too much thought and it definitely will require some maths to achieve.

**Comment by johnpaulmedina** [comment]
Thanks for taking the time to write that up.

Ok so maybe it is the audio file that I am using but when I was playing with the reflectedPeaks area and or using the example of "sound cloud" which makes them smaller what happened is half the audio file went below the middle and the other half stayed above. 

Which brings me to my next question in regards to the 0 and 1 that you mentioned. What I thought was looking at the array of data was to compare similar values to find the overlap but in those arrays how much time does each array index represent? would I just divide that by the total duration and then say ok well at these seconds in time they are similar so increment overlapCount ?

I also noticed I have negative values so technically its not always 0 is it because of the `relativeNormalization` ?

Here is another question that came to mind, completely unrelated. So the audio files are stored on aws and are actually encrypted using a private key. Is it possible to to load the audio in chunks as a stream of decoded data? Obviously this would require some work but I don't know enough about the web-audio API to know if it can support that? I was thinking like chunks loaded into a 'playlist' that would essentially be loaded into a temporary memory cache and destroyed after play. Attempting to keep the encrypted audio as protected as possible. The player is loaded into a chrome extension / chrome app so I have the ability to block dev-tools and inspecting frame on the management computers using GPO.

Any feedback and guidance is much appreciated!

**Comment by sundayz** [comment]
Maybe it's -1 to 1, it's basically this:
https://en.wikipedia.org/wiki/Pulse-code_modulation#/media/File:Pcm.svg

Points on a wave. I'm no expert on the topic to be honest.

I don't know how AWS files are encrypted, but what you're probably looking for is "Encrypted Media Extensions"

https://w3c.github.io/encrypted-media/
https://www.html5rocks.com/en/tutorials/eme/basics/

Once again I'm no expert on the topic. Like that w3c article says, this isn't a form of DRM but an API you can use to encrypt media streams. If you encrypt the file itself but not the audio stream then you haven't achieved anything.
If you want chunked media streams, the HTML5 audio api supports that with ranged requests. To get chunked audio in wavesurfer you need to use the `MediaElement` or `MediaElementWebAudio` backends

**Comment by johnpaulmedina** [comment]
Wow all good stuff. Thank you. 

For the Pulse code modulation I am going to compare that document to what is returned in the arrays and also consider maybe when post processing of the audio "normalizing" it to what ever is easier.

So while the audio file is encrypted it is not done on the AWS side - I am handling that myself on a post audio processing. The reason I was in favor of the chunks was in order to "stream" to the player - it would essentially need to be temporarily decrypted. I think the Encrypted Media Extensions is exactly what I am looking for.

**Comment by sundayz** [comment]
Yes EME probably achieves everything you need and would supporting chunking too.

On drawing the waveform you might have better luck asking someone other than me, I dont know what wavesurfer does to the peaks after it decodes the audio file. In theory web audio always resamples your audio to 48khz but I dont think wavesurfer uses 48,000 samples per second lol.

**Comment by thijstriemstra** [comment]
>  In theory web audio always resamples your audio to 48khz but I dont think wavesurfer uses 48,000 samples per second lol.

why 48k? and not 44.1k, default sample rate of an AudioContext?

**Comment by sundayz** [comment]
I don't know, i've seen it as both, I think it depends on the browser?

**Comment by thijstriemstra** [comment]
See https://github.com/katspaugh/wavesurfer.js/blob/c27243ec96d44ee9a3321799fe8b298cd4c330c3/src/webaudio.js#L348

**Comment by sundayz** [comment]
Do we use 44100 samples per second for drawing the waveform though? Thats what his question was, I don't know how the drawer code works. Does it depend on the minPixelsPerSecond setting? If i check the `peaks` property of the audio on the home page it only has 2048 peaks and the audio is quite long

**Comment by thijstriemstra** [comment]
Just wanted to clarify that " web audio always resamples your audio to 48khz " depends on the sample rate you give to the audio context.

**Comment by johnpaulmedina** [comment]
Ok so web-audio api is handling the resampling? You said depends on the sample rate you give the audio context? Meaning what exactly? Should I be setting an option or just the audio file itself?

**Comment by thijstriemstra** [comment]
Just make sure the audio file's sample rate matches the audiocontext sample rate. You can use things like `ffprobe` to check the sample rate of an audio file.

**Comment by sundayz** [comment]
Yes its irrelevant, it's probably not that hard to make the "mirrored" part of the waveform not show you just have to find the right line of code to change. You shouldn't need to worry too much about things like sample rate.

**Comment by johnpaulmedina** [comment]
Thank you all! I will peak in to those areas of code and try to accomplish what I need.
