### ISSUE TITLE
Builds breaking with Next.js/Vercel

### ISSUE THREAD

**Issue by joshuaiz** [katspaugh/wavesurfer.js#2177]
Posting this as a new issue as it is really stumping me.

Builds are failing in Vercel with Next.js so this PR that seems to fix the issue with Gatsby is not working with Next.js:

https://github.com/katspaugh/wavesurfer.js/pull/1938

Wavesurfer.js v4.4.0

I can change the file locally as referenced here: #1841:

```js
})(window = { devicePixelRatio: 1 }, function() {
```
^^ but this doesn't work for statically generated deploys.

It seems as if the PR to solve this issue doesn't work for SSG outside of Gatsby. Since adding Wavesurfer to my Next.js/Vercel project I'm not able to create a successful build.

Build log:

```bash
23:18:03.407  	> Build error occurred
23:18:03.408  	ReferenceError: window is not defined
23:18:03.408  	    at Object../src/util/request-animation-frame.js (/vercel/workpath0/node_modules/wavesurfer.js/dist/wavesurfer.js:3399:16)
23:18:03.408  	    at __webpack_require__ (/vercel/workpath0/node_modules/wavesurfer.js/dist/wavesurfer.js:35:30)
23:18:03.408  	    at Object../src/util/index.js (/vercel/workpath0/node_modules/wavesurfer.js/dist/wavesurfer.js:3046:53)
23:18:03.410  	    at __webpack_require__ (/vercel/workpath0/node_modules/wavesurfer.js/dist/wavesurfer.js:35:30)
23:18:03.410  	    at Object../src/wavesurfer.js (/vercel/workpath0/node_modules/wavesurfer.js/dist/wavesurfer.js:3459:36)
23:18:03.410  	    at __webpack_require__ (/vercel/workpath0/node_modules/wavesurfer.js/dist/wavesurfer.js:35:30)
23:18:03.410  	    at /vercel/workpath0/node_modules/wavesurfer.js/dist/wavesurfer.js:99:18
23:18:03.410  	    at /vercel/workpath0/node_modules/wavesurfer.js/dist/wavesurfer.js:102:10
23:18:03.410  	    at webpackUniversalModuleDefinition (/vercel/workpath0/node_modules/wavesurfer.js/dist/wavesurfer.js:8:20)
23:18:03.411  	    at Object.<anonymous> (/vercel/workpath0/node_modules/wavesurfer.js/dist/wavesurfer.js:15:3) {
23:18:03.411  	  type: 'ReferenceError'
23:18:03.411  	}
23:18:03.457  	error Command failed with exit code 1.
```

I've also tried using dynamically imported components as shown here: https://nextjs.org/docs/advanced-features/dynamic-import but I can't get those to work in an MDX file.

Open to any other ideas but ideally would love a working PR.

**Comment by thijstriemstra** [comment]
See https://medium.com/frontend-digest/why-is-window-not-defined-in-nextjs-44daf7b4604e

Maybe something like this?

```javascript
import dynamic from "next/dynamic";

const wavesurfer = dynamic(() => import("wavesurfer.js"), { ssr: false });
```

**Comment by joshuaiz** [comment]
HI @thijstriemstra I tried that but I'm using audio players in `.mdx` files and because of the way those files are parsed I could not get that to work.

**Comment by thijstriemstra** [comment]
> I tried that but I'm using audio players in .mdx files and because of the way those files are parsed I could not get that to work.

Ok, this is not an wavesurfer.js issue, please ask elsewhere.
