### ISSUE TITLE
wavesurfer.js included in GitHub Archive Program!

### ISSUE THREAD

**Issue by thijstriemstra** [katspaugh/wavesurfer.js#2179]
wavesurfer.js was included in the "greatest hits" and the code will go to musea around the world :) Congrats to all contributors!

> The “Greatest Hits” are archives of GitHub’s 17,000 most-popular and most-dependended-upon repositories, written to hardened  film designed to last for 1,000 years, enclosed in beautiful museum-quality cases, and donated to three of the world’s great libraries, on three different continents.

See https://archiveprogram.github.com/faq/

cc @katspaugh

**Comment by katspaugh** [comment]
Awesome, congrats! 👏

**Comment by entonbiba** [comment]
awesome stuff! 🚀
