### ISSUE TITLE
playPause() not working when upgraded my wavesurfer

### ISSUE THREAD

**Issue by GigaMick** [katspaugh/wavesurfer.js#2188]
In v4.5.0 the playPause() function isn't firing.

Rather than try to explain this in depth, I've made (crude) codeine that shows the issue.

If you add this script:

`https://unpkg.com/wavesurfer.js `

(this is v4.5.0) then you'll see the alert DOES NOT fire inside the play function.

If you change to this script:

`https://cdnjs.cloudflare.com/ajax/libs/wavesurfer.js/1.2.3/wavesurfer.min.js`

(this is v.1.2.3 which is what I've been using for years) then you see the alert inside the play function DOES fire.

So literally the only difference is switching between my old version and the latest version, and this causes playPause() to not work.

Here is my code pen and apologies once again for the crudeness of it.

https://codepen.io/gigamick/pen/Vwmbmvd

**Comment by thijstriemstra** [comment]
@GigaMick can you try 4.4.0 as well?

**Comment by GigaMick** [comment]
> @GigaMick can you try 4.4.0 as well?

Sure thing, so is this a known bug then? And I'm not crazy?

**Comment by entonbiba** [comment]
@GigaMick your audio source doesn't have CORS enabled, enable cors on the server level so it can be loaded and played from codepen.
https://www2.cs.uic.edu/~i101/SoundFiles/gettysburg.wav
