### ISSUE TITLE
Automatically publish to NPM

### ISSUE THREAD

**Issue by katspaugh** [katspaugh/wavesurfer.js#2191]
I've noticed [this repo](https://github.com/TypeFox/monaco-languageclient/blob/master/.travis.yml) is publishing a `@next` version to NPM on each push to master.

We could do the same for our semver'ed releases based on the branch name. Like if the branch is called `release-4.5.1`, it would release that version.

Would do you think, @thijstriemstra?

**Comment by thijstriemstra** [comment]
Good idea @katspaugh

**Comment by katspaugh** [comment]
Cool, I'll prepare a PR on the weekend.

**Comment by thijstriemstra** [comment]
fixed via #2205
