### ISSUE TITLE
MediaElementWebAudio: Calling play() on one WaveSurfer instance plays all instances

### ISSUE THREAD

**Issue by sundayz** [katspaugh/wavesurfer.js#2193]
### Wavesurfer.js version(s):
4.5.0

### Browser and operating system version(s):
Firefox Desktop, iOS Safari

### Code needed to reproduce the issue:
https://codepen.io/sundays/pen/MWbjRqE

### Use behaviour needed to reproduce the issue:
Click the play button. See the code only calls `ws1.play()` but ws2 plays too.

Seek events are also duplicated between them somehow?? Does Wavesurfer set a global variable that both of these instances are modifying?

I feel like this wasn't happening before but I don't see any recent commits related to this.

MediaElementWebAudio is by far the best backend, I'm trying really hard to fix all the cross browser issues with it, but I have no idea what is happening here?

**Comment by thijstriemstra** [comment]
You're using wavesurfer to control a single Audio instance:

```javascript
let audio = new Audio('https://wavesurfer-js.org/example/media/demo.wav');
audio.crossOrigin = true;
```

so both wavesurfer instances are affected by what you do to one of them. Makes sense to me..

**Comment by sundayz** [comment]
oops, you're rich :S
