### ISSUE TITLE
Scrollbar appears when using video element as a source

### ISSUE THREAD

**Issue by disfated** [katspaugh/wavesurfer.js#2206]
When using `<video>` element as a source at the end of playback the waveform fails to fit the container and an ugly scrollbar appears.

Reproducable example: https://wavesurfer-js.org/example/video-element/index.html

Here's video demonstration: https://user-images.githubusercontent.com/430542/110111115-a54f3300-7dd1-11eb-8033-227bc690ef1d.mp4

Chrome 88.0.4324.190

**Comment by thijstriemstra** [comment]
Try the `hideScrollbar: true` option, see https://wavesurfer-js.org/docs/options.html

**Comment by disfated** [comment]
Thanks for the workaround, though I figured it myself applying `overflow: hidden` to wrapper element, seems like `hideScrolbar: true` does the same thing. But clearly it doesn't solve the underlying problem, since the cursor still appears shifted from the wave at the end of playback. And this doesn't happen with audio sources.
![Fm1eIMHMmJ](https://user-images.githubusercontent.com/430542/110236528-1c163880-7f58-11eb-956a-0fc095c13cce.png)
