### ISSUE TITLE
Play Region with offset from start point 

### ISSUE THREAD

**Issue by dagreatbrendino** [katspaugh/wavesurfer.js#2221]
### Wavesurfer.js version(s):
wavesurfer.js: "3.3.3"

Sorry if I missed something in the documentation, but is there a way to use the region.play() function to play a region with an offset from the set start point?

**Comment by dagreatbrendino** [comment]
Nevermind I was able to figure it out. It seems that regions plugin simply calls `wavesurfer.play(start)` where start is the start of your region. So if you're using something like `myRegion.play()` and you want to play the region with some offset you could simply do `myRegion.play(myRegion.start + someoffset)`.

**Comment by dagreatbrendino** [comment]
Closing this but please let me know if there’s a more intuitive way that I am missing.

**Comment by sundayz** [comment]
The way you're doing it looks fine to me, I see nothing wrong with it 👍
