### ISSUE TITLE
Multiple waveforms in one page

### ISSUE THREAD

**Issue by realworldNeo** [katspaugh/wavesurfer.js#2222]
I'm trying to place dynamically multiple waveforms per page, on a Django project. I create an array of wavesurfers (one per waveform). They render fine but only the last of the wavesurfers plays.

Here is the function that creates each wavesurfer:

```
<script>

    var wavesurfers_array=[];
  
    function wavesurfer_creator(i_, url){

      w= WaveSurfer.create({
        container:'#waveform'+ i_ ,
      });
    
    w.load(url);
    
    wavesurfers_array.push(w);
    
    return w;
    }

    var i=0; //counter of wavesurfers
```

Here is the for loop, in Django Template Language, that builds each waveform

```
 {% for song in song_list %}
      
      <div>

        <a>{{ song.name }}</a>
        
        <div id="waveform"></div>

        <script type="text/javascript">
        
          $("#waveform").attr({id:"waveform"+i}); //change id of waveform div to be compitable with each wavesurfer
        
          wavesurfer_creator(i,url);
        
          wavesurfers_array[i].on('ready', function () {
              wavesurfers_array[i].play();
          });
  
          i+=1;
    
        </script>
        
      </div> 

    {% endfor %}
```

I'm new to programming. I've tried for days to solve this.  If you guys could help me, I would appreciate a lot :)

**Comment by sundayz** [comment]
Your idea and approach is correct, but browsers don't like it in general when you try to play audio without a user first pressing a button. you should have a button that the user clicks, and in the `onclick` handler for the button you can start audio playback. If you tell us what you're trying to achieve we might be able to suggest a way of doing it :)

**Comment by entonbiba** [comment]
You have to make sure each wavesurfer ID is unique.
`$("#waveform").append('<div id="wavesurfer_'+i+'"></div>'); `

have a look at this and see if it helps,
https://www.entonbiba.com/lab/wavesurfer/930.html

**Comment by thijstriemstra** [comment]
no further feedback, closing.
