### ISSUE TITLE
Error decoding audiobuffer

### ISSUE THREAD

**Issue by moon476607596** [katspaugh/wavesurfer.js#2224]
There is a problem happened when loading the audio file before that ready, an error comes 'Error decoding audiobuffer',somtimes is run good and sometimes run error, please help me!!!

**Comment by thijstriemstra** [comment]
you decided to ignore the guidelines for writing a ticket, so can't help you.

**Comment by Linya-IronMan** [comment]
I get this error message too.

**Comment by Linya-IronMan** [comment]
@moon476607596 
I get this. Maybe your media file has no audio stream.
The two issues are about this Error message;
https://github.com/katspaugh/wavesurfer.js/issues/353
https://github.com/katspaugh/wavesurfer.js/issues/204
You can have a try.
Use ffmpeg to parse the media file, and you will see it.

The two issues created 6 years ago. At first I thout it has been resolved or we can get more message from error......
