### ISSUE TITLE
Filters are not applying as expected

### ISSUE THREAD

**Issue by NikitaProkofyevVKDevLab** [katspaugh/wavesurfer.js#2225]
Hi everyone, I'm trying to apply filters to wavesurfer but they not working properly,
what I want tot do is a simple fade in effect.
I tried many ways to use ```setFilters``` method,
and there was a case when filter has been applied, but it was reseted after pausing playback, while being found in filters array by calling ```getFilters``` method.
in the code example, that is now changed, it is not working as expected
couldn't figure out why.
thanks in advance !

I've studied WebAudioApi docs and Wavesurfer docs and couldn't find a proper example how exactly use filters.

### Code needed to reproduce the issue:

https://codepen.io/NikitaProkofyev/pen/VwmOvNm - on this pen it's no working at all

https://codepen.io/NikitaProkofyev/pen/PobroWN - on this pen it works only once
steps to make it work at least once (only on the last pen)
upload audio file
toggle fade radio button
click play
it works! 
but then it doesn't, at all

**Comment by NikitaProkofyevVKDevLab** [comment]
solution is found
in order to apply filter in time, it is necessary to use context property of the gain node itself,
for example 
```
fadeFilter.gain.setValueAtTime(1, fadeFilter.context.currentTime);
fadeFilter.gain.linearRampToValueAtTime(1, fadeFilter.context.currentTime + filterDuration);
```
this.example of course works if we need to apply filter at the beginning.

since the time in the context is not connected to the time in the wavesurfer itself

**Comment by entonbiba** [comment]
yes the context has to be used, we will see and maybe add an option to handle this for the filters within wavesurver in the future.
