### ISSUE TITLE
Example Video Annotation broken

### ISSUE THREAD

**Issue by olafthiele** [katspaugh/wavesurfer.js#2226]
Looks like the new trivia breaks [the example](https://wavesurfer-js.org/example/video-annotation/index.html):

> main.js:1 Uncaught SyntaxError: Identifier 'wavesurfer' has already been declared
> trivia.js:61 Uncaught TypeError: Cannot read property 'querySelectorAll' of null
>     at HTMLDocument.<anonymous> (trivia.js:61)
> (anonymous) @ trivia.js:61

**Comment by thijstriemstra** [comment]
@osheroff made last changes afaik

**Comment by osheroff** [comment]
https://github.com/katspaugh/wavesurfer.js/pull/2227

**Comment by thijstriemstra** [comment]
fixed in 4.7.0
