### ISSUE TITLE
load(url, peaks, preload) – Loads audio from URL via XHR. IOS system cannot play for the first time

### ISSUE THREAD

**Issue by guisha** [katspaugh/wavesurfer.js#2228]

**Comment by sundayz** [comment]
Next time provide more details. Here are some possible issues:

Do you have any CORS warnings in the console?
Have you set CORS headers on your server?

If yes, then try:
```js
const audio = new Audio(your URL here);
audio.crossOrigin = 'anonymous';
wavesurfer.load(audio, peaks, preload);
```

Are you trying to autoplay audio without a user gesture?

**Comment by thijstriemstra** [comment]
no feedback, closing.
