### ISSUE TITLE
Only analyze audio - without rendering

### ISSUE THREAD

**Issue by jellohouse** [katspaugh/wavesurfer.js#2229]
Is there a simple way to use wavesurfer to get the duration (and possibly other data) of the audio file without rendering the waveform?

In part of my app I use wavesurfer to create the visual rendering of the audio, but in another part of my app I would like to simply get the duration of the track without actually rendering anything.

----

I know I could just create the wafesurfer container and hide it, but I feel like that is not very elegant.

**Comment by thijstriemstra** [comment]
you can use `AudioContext.decodeAudioData()` or use something like `ffmpeg` on the serverside to determine the duration.
