### ISSUE TITLE
What is going on with documentation/versions?

### ISSUE THREAD

**Issue by phillyslick** [katspaugh/wavesurfer.js#2230]
Hi,

It's really tough to decipher which documentation goes with which version of wavesurfer. The main docs site mentions something about version 2, but all the docs on github direct to version 1. The docs for version 2 seem autogenerated and not really up to par for using the library. 

And if I look at the changelog, I see now version 4?

Which version do the samples use?

Any help is appreciated, and if I can get an idea of what needs to change, I am happy to issue a PR or two.

**Comment by thijstriemstra** [comment]
there is only upgrade documentation for v2, so that's why it stands out (as latest version) on the site. 

all docs on github direct to version 1.0? where do you see that?

currently the latest is v4.6.0

**Comment by phillyslick** [comment]
This documentation on https://wavesurfer-js.org/docs/methods.html is for the latest version? Or version 1? 
It's just not clear with that Version 2 link sticking out and saying "This is the new version" 

I am also confused as to how the latest version is v2 but then you say the latest is v4.6.0

If section on the gh-pages site that says "Version 2" is really about upgrading from version 1 to version 2, then it should explicitly say that.  As it is now, it seems like it's an upcoming version, different from the rest of the documentation on the site.

Maybe it's just me, but I found this incredibly confusing.

**Comment by thijstriemstra** [comment]
@phillyslick any help on editing these docs would be great! See https://github.com/katspaugh/wavesurfer.js/tree/gh-pages/v2 (the directory is called v2 because it's v2 of the website but that shouldn't show up in the live docs afaik)
