### ISSUE TITLE
releases section not being updated

### ISSUE THREAD

**Issue by thijstriemstra** [katspaugh/wavesurfer.js#2231]
![image](https://user-images.githubusercontent.com/305679/111885958-1b0aef80-89cb-11eb-8eaa-a35ac62c98f1.png)

cc @katspaugh this should be fixed with npm publish action because it creates new tags right?

**Comment by katspaugh** [comment]
AFAIK, tags have no effect on GitHub releases. It should be doable to additionally trigger them from the Action too, though.

I currently don’t have a laptop, will check once a new one comes.

**Comment by thijstriemstra** [comment]
@katspaugh there's a github commandline tool for creating releases: https://docs.github.com/en/rest/reference/repos#create-a-release Perhaps something like that should be added as well to update the releases?

**Comment by katspaugh** [comment]
Cool, thanks! I'll take a look.
