### ISSUE TITLE
Spectrogram for mono files doubles the frequency

### ISSUE THREAD

**Issue by cnolte** [katspaugh/wavesurfer.js#2232]
### Wavesurfer.js version(s):
4.6

### Browser and operating system version(s):
Windows 10; Chrome 89, Firefox 86

### Code needed to reproduce the issue:
The drawSpectrogram function inside the spectrogram plugin has a heightFactor:

const heightFactor = my.buffer ? 2 / my.buffer.numberOfChannels : 1;

For mono files the heightfactor is 2 what is wrong. This should always be 1 because the frequency doesn't change just because it's a mono file.

(Please reduce your code as much as possible and only post the minimum code needed to reproduce the issue. [A Code pen](http://codepen.io/) is an excellent way to share such code)

### Use behaviour needed to reproduce the issue:
Add the spectrogram plugin with labels to any wavesurfer session and load a mono file. The frequencies will be wrong.

**Comment by thijstriemstra** [comment]
@ilovecomputers worked on spectrogram [https://github.com/katspaugh/wavesurfer.js/commit/2be59a0f45c6295c0c96e47a1ec7cdc64bdbdefc],. Any thoughts on this ticket @ilovecomputers?

**Comment by jessems** [comment]
I'd be happy to investigate and if necessary make a pull request.

**Comment by ilovecomputers** [comment]
The `heightFactor` has been part of the Spectogram plugin since [its inception](https://github.com/katspaugh/wavesurfer.js/commit/24fd80b0892982a60a89c213befd2f623d06a8e4#diff-2535e2c225b501788787607a20c9ef36cd53e7e3c94c0cc0e7296365cd558dafR106). TBH, I'm not sure of the reasoning behind the logic, I merely preserved its behavior when I switched to the pixel-by-pixel image drawing. The behavior I observed was that mono audio results in rectangles two pixels high and stereo was one pixel high.

**Comment by ilovecomputers** [comment]
Just for fun, I took demo.wav and turned it into a mirrored stereo audio in Audacity (note their spectro goes up to 8k):

<img width="917" alt="Screen Shot 2021-04-13 at 8 45 51 PM" src="https://user-images.githubusercontent.com/427597/114651727-5a122500-9c99-11eb-8785-1b4bc304dfd8.png">

This is what the spectro of that stereo file looked like in wavesurfer:
<img width="890" alt="Screen Shot 2021-04-13 at 8 48 56 PM" src="https://user-images.githubusercontent.com/427597/114651896-b07f6380-9c99-11eb-8c3f-38409c968757.png">

For reference, here's the original demo:
<img width="905" alt="Screen Shot 2021-04-13 at 8 48 32 PM" src="https://user-images.githubusercontent.com/427597/114651879-a5c4ce80-9c99-11eb-8002-fef576de29a1.png">

**Comment by ilovecomputers** [comment]
If I had to guess, the stereo spectro has half the height of the mono spectro so that two stereo tracks could be stacked on top of another.

**Comment by dofuuz** [comment]
Regardless of number of channels, the `heightFactor` should always be 1.

![Wrong](https://user-images.githubusercontent.com/427597/114651879-a5c4ce80-9c99-11eb-8002-fef576de29a1.png)
↑ This is wrong
Samplerate of demo.wav is 22050Hz, so top of spectrogram should be 11.025kHz. Not 22.1kHz nor 24kHz.
`heightFactor = 2` looks good, but it's incorrect.

It seems like web browser decodes audio to fixed samplerate(in my case, 48kHz) #1248
![Correct](https://user-images.githubusercontent.com/427597/114651896-b07f6380-9c99-11eb-8c3f-38409c968757.png)
↑ So this is correct spectrogram, for now.
Fixing `heightFactor` to 1 will draw spectrogram like this.
