### ISSUE TITLE
Microphone plugin in firefox

### ISSUE THREAD

**Issue by finn1310** [katspaugh/wavesurfer.js#2237]
## Wavesurfer.js version(s):
4.6.0

### Browser and operating system version(s):
Firefox v87.0

### Code needed to reproduce the issue:
      // Init waveSurfer
      waveSurfer = WaveSurfer.create({
        container: "#waveform",
        waveColor: "black",
        backgroundColor: "rgb(255, 248, 237)",
        barRadius: 6,
        barWidth: 4,
        barWidth: 3,
        barGap: 3,
        audioContext: context || null,
        audioScriptProcessor: processor || null,
        scrollParent: true,
        progressColor: "black",
        cursorWidth: 0,
        hideScrollbar: true,
        plugins: [
          WaveSurfer.microphone.create({
            constraints: {
              video: false,
              audio: true,
            },
          }),
        ],
      });

      let mediaRecorder;
      waveSurfer.microphone.on("deviceReady", function (stream) {
        mediaRecorder = new MediaRecorder(stream);
        mediaRecorder.start();
        mediaRecorder.addEventListener("dataavailable", (event) => {
          audioChunks.push(event.data);
        });
        mediaRecorder.addEventListener("stop", () => {
          const audioBlob = new Blob(audioChunks);
          // const audioUrl = URL.createObjectURL(audioBlob);
          waveSurfer.loadBlob(audioBlob);
        });
      });

(Please reduce your code as much as possible and only post the minimum code needed to reproduce the issue. [A Code pen](http://codepen.io/) is an excellent way to share such code)

### Use behaviour needed to reproduce the issue:
After recording with microphone. I have loaded audioBlob into the wave surfer. However, the duration of the sound is much shorter. For example. I recorded for 10 seconds but only played 2.3 seconds.
The code is working in safari, chrome, edge but firefox is not working

**Comment by thijstriemstra** [comment]
> audioContext: context || null,
> audioScriptProcessor: processor || null,

What do these vars look like?

**Comment by finn1310** [comment]
As example microphone plugin. 
`
let context, processor;
if (isSafari) {
        let AudioContext = window.AudioContext || window.webkitAudioContext;
        context = new AudioContext();
        processor = context.createScriptProcessor(1024, 1, 1);
      }`

**Comment by thijstriemstra** [comment]
what operating system?

**Comment by finn1310** [comment]
Thanks. I have added mimeType MediaRecorder options if it's firefox browser. It worked.
`mediaRecorder = new MediaRecorder(stream, {mimeType: "audio/webm"})`
