### ISSUE TITLE
Crash on Google Chrome Beta v90

### ISSUE THREAD

**Issue by MarcoNisi** [katspaugh/wavesurfer.js#2244]
- [x] I have checked [the FAQ](https://wavesurfer-js.org/faq/) and it doesn't solve my problem.
- [x] I have checked [the documentation](https://wavesurfer-js.org/docs/) and it doesn't solve my problem
- [x] I have searched for [already open issues](https://github.com/katspaugh/wavesurfer.js/issues) which desribe my problem.
- [x] The issue I'm having is related to and caused by wavesurfer.js, not by other software (which maybe packages and uses wavesurfer incorrectly)

### Wavesurfer.js version(s):
All

### Browser and operating system version(s):
Google Chrome Beta (version 90)

### Code needed to reproduce the issue:
The homepage of https://wavesurfer-js.org/

### Use behaviour needed to reproduce the issue:
Go to the [homepage of wavesurfer](https://wavesurfer-js.org/) with the provided browser version and click on "Play/Pause" button. The browser will crash almost immediatly after the click.

**Comment by Ronaldmei** [comment]
I've got the same problem error STATUS_BREAKPOINT

**Comment by aendel** [comment]
It's happening to me with Chrome 90 Beta as well as the others.

**Comment by Dacker15** [comment]
I've got the same problem on Google Chrome 90 (Beta)

**Comment by Ronaldmei** [comment]
It looks like the error is happening somewhere in this part of the wavesurfer.js

And Google chrome is displaying the following warning "The ScriptProcessorNode is deprecated. Use AudioWorkletNode instead."

`key: "createScriptNode",
    value: function createScriptNode() {
      if (this.params.audioScriptProcessor) {
        this.scriptNode = this.params.audioScriptProcessor;
      } else {
        if (this.ac.createScriptProcessor) {
          this.scriptNode = this.ac.createScriptProcessor(WebAudio.scriptBufferSize);
        } else {
          this.scriptNode = this.ac.createJavaScriptNode(WebAudio.scriptBufferSize);
        }
      }

      this.scriptNode.connect(this.ac.destination);
    }`

**Comment by SJN1981** [comment]
Same problem here: [Deprecation] The ScriptProcessorNode is deprecated. Use AudioWorkletNode instead. (https://bit.ly/audio-worklet)

**Comment by Ronaldmei** [comment]
Possible solution, in our case adding the line backend: 'MediaElement' solves the problem

new code
```
    wavesurfer = WaveSurfer.create({
            container: document.querySelector('#waveform'),
            backend: 'MediaElement',
            waveColor: '#cccccc',
            progressColor: '#6b8874'
        });

```
old code
```
    wavesurfer = WaveSurfer.create({
            container: document.querySelector('#waveform'),
            waveColor: '#cccccc',
            progressColor: '#6b8874'
        });
```

**Comment by MarcoNisi** [comment]
I confirm that with the latest beta version it works.
