### ISSUE TITLE
UPDATE - ScriptProcessorNode with AudioWorkletNode

### ISSUE THREAD

**Issue by entonbiba** [katspaugh/wavesurfer.js#2245]
Since `ScriptProcessorNode` is now deprecated, we should look into updating it to use `AudioWorkletNode` while keeping the usage of `ScriptProcessorNode` for backward compatibility and for ios safari support.

ScriptProcessorNode
https://developer.mozilla.org/en-US/docs/Web/API/ScriptProcessorNode

AudioWorkletNode
https://developer.mozilla.org/en-US/docs/Web/API/AudioWorkletNode

![image](https://user-images.githubusercontent.com/5193884/114276146-70975280-99f3-11eb-9477-16f154525d3c.png)

#2244 #2100 #1689 #2210 #1281

**Comment by thijstriemstra** [comment]
Looks like a duplicate of #1281 @entonbiba

**Comment by entonbiba** [comment]
I'll close this one,
