### ISSUE TITLE
soundtouch with playlist example generates memory leak.

### ISSUE THREAD

**Issue by bravoice** [katspaugh/wavesurfer.js#2246]
# Hey, thank you for testing and contributing to wavesurfer.js!

## Please make sure you can check all of these points below before opening an issue:

(You don't have to post this section)

- [ ] I have checked [the FAQ](https://wavesurfer-js.org/faq/) and it doesn't solve my problem.
- [ ] I have checked [the documentation](https://wavesurfer-js.org/docs/) and it doesn't solve my problem
- [ ] I have searched for [already open issues](https://github.com/katspaugh/wavesurfer.js/issues) which desribe my problem.
- [ ] The issue I'm having is related to and caused by wavesurfer.js, not by other software (which maybe packages and uses wavesurfer incorrectly) – In that case you should open the issue on the respective project pages.

### Wavesurfer.js version(s):
V3.3.3

### Browser and operating system version(s):
win7 + Chrome v87
win7 + ms edge v89

### Code needed to reproduce the issue:
I just put the main lines of the app.js file in stretcher example to the file app.js in playlist example, and the new js file is in the following link:
https://codepen.io/bravoice/pen/vYgrzdP
(Please reduce your code as much as possible and only post the minimum code needed to reproduce the issue. [A Code pen](http://codepen.io/) is an excellent way to share such code)

### Use behaviour needed to reproduce the issue:
click the play button, and perhaps you need to click it for a second time, and then the page plays the items in the list. Each time the playing item changes, the browser Chrome occupies more memory. This should be so-called "memory leak".

How to solve this problem? please give hints, thanks in advance!

**Comment by entonbiba** [comment]
you can destroy the instance and re load it to clear the memory in the play event for the plugin sample,
`destroy()`

we added this memory leak fix on this pr #2164 which also fixes this ticket #1940

reopen this ticket if the destroy event doesn't clear it for you on that plugin as described above.
