### ISSUE TITLE
Regions for spectrogram?

### ISSUE THREAD

**Issue by Mosman97** [katspaugh/wavesurfer.js#2247]
Hello everyone,

I am using the spectrogram plugin and the region plugin. Is it possible to have the regions in the spectrogram  too?

Version 4.6.0

**Comment by NidusP** [comment]
I think it’s not possible.They are both plugins base on wavesurfer. And `<region></region>` is in `<wave></wave>`,  `<spectrogram></spectrogram>` is a separate one.  There is no API to render spectrogram on wave.

**Comment by thijstriemstra** [comment]
no further feedback, closing.
