### ISSUE TITLE
rendering in wrapped containers

### ISSUE THREAD

**Issue by MrdUkk** [katspaugh/wavesurfer.js#2248]
### Wavesurfer.js version(s):
4.6.0

### Browser and operating system version(s):
Firefox 78.8 on Linux RHEL

### Code needed to reproduce the issue:
if i'm use in "raw" html page control rendered normally. if use in Vue 2.0 popup v-dialog  current position rendered incorrectly (black filled image squashed over original waveform)
![image](https://user-images.githubusercontent.com/26002184/115205195-fa38d580-a101-11eb-9503-3d213f2bd31c.png)
![image](https://user-images.githubusercontent.com/26002184/115205367-281e1a00-a102-11eb-816e-ea74cc3ec857.png)

wavesurfer waveform div is wrapped inside ton's of other div's
![image](https://user-images.githubusercontent.com/26002184/115205663-77fce100-a102-11eb-9e51-fd97623701bb.png)

what i'm doing wrong?

**Comment by thijstriemstra** [comment]
> if i'm use in "raw" html page control rendered normally. if use in Vue 2.0 popup v-dialog current position rendered incorrectly

So there is no issue with wavesurfer.js, but with your vue application. This is not a forum for vue questions, please use stackoverflow or something instead. Closing.

**Comment by MrdUkk** [comment]
i think topic on properly embedding wavesurfer.js in complex html javascript applications (there div in in div scheme used) is viable for anyone. so this must be in FAQ like 'how to use pre-recorded peaks'.
more in FAQ = more friendly control for anyone.

**Comment by thijstriemstra** [comment]
I see what you're saying, I agree an 'architecture' type of document describing the structure of wavesurfer.js is needed.

**Comment by MrdUkk** [comment]
yes. more in FAQ is viable for quick start. This is what really attract to use this control. Few clicks with mouse and few lines of code and BAM you got it working!
VUE and React is a popular frameworks across the globe. So if simple howto use it properly will be in FAQ = cool and more user base!

**Comment by MrdUkk** [comment]
to all. solved problems with this CSS to work properly:
.wavesurf-container {
width: <pixels>px;
position: relative;
}
.wavesurf-container canvas {
max-width: none;
}

second one (canvas) is very very important or rendering will be screwed as in this issue ticket.

**Comment by thijstriemstra** [comment]
@MrdUkk you can always open a pull request and see what response from other devs is.
