### ISSUE TITLE
Question: 4.7.0 release date

### ISSUE THREAD

**Issue by adamteale** [katspaugh/wavesurfer.js#2255]
Hi! 
I would really like to try out the new ability to dispaly a waveform vertically.
Will the 4.7.0 release be available soon?
Thanks!

**Comment by valrus** [comment]
If you need a proper release, I can't help you, but:
If you just want to try it out, there's a live demo here: https://ian.mccowan.space/wavesurfer-vertical-demo/
If you're able to just load a JS file for your purposes, the minified JS is available here: https://ian.mccowan.space/wavesurfer-vertical-demo/static/js/wavesurfer.min.js

**Comment by thijstriemstra** [comment]
Good question. I think the changes in there warrant a major version nr bump, so v5.0.0. I'll make a release branch now.

**Comment by adamteale** [comment]
Thanks @thijstriemstra! I'm looking forward to experimenting with it
