### ISSUE TITLE
Wavesurfer 5.0.0 no longer removing element on .destroy()

### ISSUE THREAD

**Issue by rijk** [katspaugh/wavesurfer.js#2258]
The `<wave>` element is no longer removed from DOM after calling `wavesurfer.destroy()`. This issue popped up after updating from 4.6.0 to 5.0.0. I went back to double check and 4.6.0 doesn't have this issue.

**Comment by thijstriemstra** [comment]
cc @valrus

**Comment by thijstriemstra** [comment]
And unfortunately the unit test for `destroy` doesn't check if these elements are properly removed, so test still passes atm.

**Comment by thijstriemstra** [comment]
Should be fixed in new 5.0.1 release. Thanks for reporting the issue @rijk
