### ISSUE TITLE
Unexpected token error from Regions plugin on 5.0.0

### ISSUE THREAD

**Issue by gavrichards** [katspaugh/wavesurfer.js#2259]
### Wavesurfer.js version(s):

5.0.0

### Browser and operating system version(s):

Firefox 88, macOS Big Sur

### Code needed to reproduce the issue:

Next.js v10.1.3.

```
const regions = RegionsPlugin.create({});
const plugins = [regions];
...
wavesurfer.current = WaveSurfer.create({
      container: ref.current,
      height: 200,
      plugins,
    });
```

### Use behaviour needed to reproduce the issue:

I came from 4.6.0 where this isn't an issue.

```
./node_modules/wavesurfer.js/src/plugin/regions/region.js 46:47
Module parse failed: Unexpected token (46:47)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|         this.data = params.data || {};
|         this.attributes = params.attributes || {};
>         this.showTooltip = params.showTooltip ?? true;
| 
|         this.maxLength = params.maxLength;
```

**Comment by thijstriemstra** [comment]
Looks like we need an additional babel plugin: https://dev.to/bamartindev/es2020-nullish-coalescing-with-babel-plugins-1j8n

I'll make a pr.

**Comment by thijstriemstra** [comment]
It's actually in `@babel/preset-env` which wavesurfer.js uses and correctly transpiled if you look at `dist/plugins/wavesurfer.regions.js`.

So you need to enable it in your next.js build:  https://babeljs.io/docs/en/babel-plugin-proposal-nullish-coalescing-operator

Or submit a pull request that replaces ?? with an oldskool Javascript notation.

**Comment by gavrichards** [comment]
@thijstriemstra The odd thing is I use the ?? notation elsewhere in my application (in my own code) and that works fine, so presumably I don't need to enable it in my next.js build.

**Comment by thijstriemstra** [comment]
> The odd thing

So next.js isn't transpiling external packages for you it seems. I'm not familiar with the framework but I don't think it's an wavesurfer.js issue at this point.

**Comment by gavrichards** [comment]
Ok fair enough, thanks for your help.

**Comment by thijstriemstra** [comment]
If more people run into the issue:

> submit a pull request that replaces ?? with an oldskool Javascript notation, I wouldn't mind changing it.

**Comment by gavrichards** [comment]
I realised my mistake.
I had this:
```
import RegionsPlugin from 'wavesurfer.js/src/plugin/regions';
```
when it should be:
```
import RegionsPlugin from 'wavesurfer.js/dist/plugin/wavesurfer.regions';
```
Problem solved!

**Comment by n0mn0m** [comment]
Thanks @caugner. I do have the types installed, and for just `WaveSurfer` things work and I get the media element.

I started using the imports based on the jest test (to add plugins), and ran into the nullish operator error at the top of this issue. Doing some more reading last night I think I'm running into [this](https://github.com/facebook/create-react-app/issues/9468) issue. I'm going to test some of the suggestions there, but I may have to customize babel a bit to get this all working. Thanks for the links!
