### ISSUE TITLE
Want to set peak limit and its average

### ISSUE THREAD

**Issue by anaskhanstack** [katspaugh/wavesurfer.js#2264]
![image](https://user-images.githubusercontent.com/45259204/117385050-b9143400-aefd-11eb-8daa-48d9aff4e66a.png)

The problem is that i can not set the peak limit and i want to optimize the waveform like i want to give the average height, like above image. Any help would be aprreciated since I can't find a solution by myself
Thankyou 
Regards Anas Khan

**Comment by sundayz** [comment]
I think the only way to do it currently is to either write your own renderer, or to create the output with https://github.com/bbc/audiowaveform yourself (cached peaks)
