### ISSUE TITLE
xhr authorization header not working with MediaElement backend

### ISSUE THREAD

**Issue by madhawik** [katspaugh/wavesurfer.js#2270]
@thijstriemstra @danielkrich  I tried to use xhr authorization header with MediaElement backend, it is not working. How can I use preload? Please share an example. 

@danielkrich preload it using ajax (e.g. jquery of whatever javascript) into an audio element and pass that audio element to wavesurfer?

_Originally posted by @thijstriemstra in https://github.com/katspaugh/wavesurfer.js/issues/1038#issuecomment-430725606_

**Comment by thijstriemstra** [comment]
> tried to use xhr authorization header with MediaElement backend, it is not working. How can I use preload? Please share an example.

Well, let's start with you sharing code, what have you tried that is not working?

**Comment by madhawik** [comment]
In my code,
`
const token="edjflkgflhgf...";
const waveform = window.WaveSurfer.create({
            **backend: "MediaElement",**
            container: "#waveform",
            waveColor: "grey",
            barWidth: 2,
            barHeight: 1,
            barGap: 2,
            minPxPerSec: 30,
            scrollParent: true,
            responsive: true,
            xhr: {
                requestHeaders: [{
                    key: "Authorization", value: "Bearer " + token
                }]
            }
});`
`waveform.load(audioURL, peakjsonData);`

When I use backend:MediaElement, authorization bearer token is not available in request header of the audio URL. But in case of backend:WebAudio, authorization bearer token is available.

**Comment by thijstriemstra** [comment]
Try `crossorigin="use-credentials"` on the `audio` element?

From https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio:

> Sends a cross-origin request with a credential. In other words, it sends the Origin: HTTP header with a cookie, a certificate, or performing HTTP Basic authentication. If the server does not give credentials to the origin site (through Access-Control-Allow-Credentials: HTTP header), the audio will be tainted and its usage restricted.

**Comment by madhawik** [comment]
1. I am using proxy, so origin is same for audio url and web application url.

2. I have referred https://github.com/katspaugh/wavesurfer.js/issues/1856 to add cross-origin.

 xhr = {
            cache: "default", mode: "cors", method: "GET", credentials: "same-origin",
            redirect: "follow", referrer: "client",
            requestHeaders: [{
                key: "Authorization", value: "Bearer " + "my-token"
            }]
        };

3. Issue is not resolved, authorization bearer token is not available in request header of the audio URL when I use backend:MediaElement.

4. why xhr works only with backend:WebAudio and not with backend:MediaElement?

**Comment by thijstriemstra** [comment]
> why xhr works only with backend:WebAudio and not with backend:MediaElement?

Because webaudio uses `fetch` API to load the file. Looks like it's a browser limitation.

**Comment by madhawik** [comment]
I have tested on Google Chrome and Microsoft Edge. It is not working on both browsers.
What is the fix? How can I use backend:MediaElement with authorization token in header?

**Comment by madhawik** [comment]
Hey @thijstriemstra are you looking on this issue?

**Comment by thijstriemstra** [comment]
NO

**Comment by sundayz** [comment]
It depends on your environment, there's a lot of related issues on stackoverflow

**Comment by VanishMax** [comment]
In the current version of Wavesurfer, the property that controls the request is called `fetchParams`:

const wavesurfer = WaveSurfer.create({
    container: `#wave`,
    url: 'https://...',
    fetchParams: {
      mode: 'no-cors',
    },
  });
