### ISSUE TITLE
WaveSurfer.regions.create Uncaught TypeError: Cannot read property 'create' of undefined

### ISSUE THREAD

**Issue by bolatovdarkhan25** [katspaugh/wavesurfer.js#2271]
I've read all similar issues, but could not solve the problem, help please

**Comment by thijstriemstra** [comment]
What code causes this problem?

**Comment by bolatovdarkhan25** [comment]
> What code causes this problem?

        let RegionsPlugin = WaveSurfer.regions;

        let waveform = WaveSurfer.create({
            container: '#waveform',
            waveColor: 'violet',
            progressColor: 'purple',
            backend: 'MediaElement',
            plugins: [
                RegionsPlugin.create({})
            ]
        });

**Comment by thijstriemstra** [comment]
Looks like RegionsPlugin is not properly imported. Can you `console.log(RegionsPlugin)`?

See https://github.com/katspaugh/wavesurfer.js/blob/master/src/plugin/regions/index.js#L48

**Comment by bolatovdarkhan25** [comment]
> Looks like RegionsPlugin is not properly imported. Can you `console.log(RegionsPlugin)`?
> 
> See https://github.com/katspaugh/wavesurfer.js/blob/master/src/plugin/regions/index.js#L48

        let waveform = WaveSurfer.create({
            container: '#waveform',
            waveColor: 'violet',
            progressColor: 'purple',
            backend: 'MediaElement',
            plugins: [
                // RegionsPlugin.create({})
            ]
        });

        let RegionsPlugin = WaveSurfer.regions;

        console.log(RegionsPlugin);

        undefined (index):182

**Comment by bolatovdarkhan25** [comment]
I've found decision. I had to add one more script <script src="{{ asset('js/wavesurfer.js/dist/plugin/wavesurfer.regions.js')}}"></script>. Sorry for bothering.
