### ISSUE TITLE
Getting Cors Error 'Access-Control-Allow-Origin'  after deployment. Tried adding xhr to options.

### ISSUE THREAD

**Issue by coot3** [katspaugh/wavesurfer.js#2272]
Wavesurfer can't load audio files due to Cors policy error.  The rest of my application requests for data function normally, it is only wave surfer that is producing this error.  

I have tried adding xhr to the options as follows:

```
const formWaveSurferOptions = (ref) => ({
    container: ref,
    xhr: { 
        cache: 'default', 
        mode: 'cors', 
        method: 'GET', 
        credentials: 'same-origin', 
        redirect: 'follow', 
        requestHeaders: [ { key: 'Authorization', value: localStorage.getItem("key") } ]}
});

```

My setup worked in development with both backend and frontend on localhost.  My normal axios requests to fetch other data from the api generally look like this:

```
const config = {
            headers: {
                Authorization: localStorage.getItem("key"),
            },
        };
        try {
            const res = await axios.post(
                `${process.env.REACT_APP_API_URL}url/`,
                {
                    position: progressPercent,
                    song: song.id,
                    value: id,
                },
                config
            );
```

If I use the same url I use in wavesurfers.load in a normal html audio element The audio loads fine and is playable
Any ideas why this is occurring? django rest framework backend with react frontend.

Thanks

**Comment by entonbiba** [comment]
@coot3 the cors header has to be added on the server side where the actual audio file is being streamed from not the frontend that is requesting it.

You will find the way to add the header based on your server type from here:
https://enable-cors.org/server.html
