### ISSUE TITLE
Get "variations" of a waveform

### ISSUE THREAD

**Issue by alanrivetta** [katspaugh/wavesurfer.js#2273]
Hello, I hope you are very well!

Is it possible to obtain floating numbers between 0 and 1 based on the graph created by your library?

I show you an example, perhaps it is clearer:
![image](https://user-images.githubusercontent.com/23205280/118839171-abb35e00-b89c-11eb-91d6-3c233e647e45.png)

`variations = [0, 0.3, -0.5, -1, 1, 0.5]`

I hope I was clear.

Thank you!

**Comment by thijstriemstra** [comment]
Use `wavesurfer.exportPCM()`, see https://github.com/katspaugh/wavesurfer.js/blob/master/src/wavesurfer.js#L1624
