### ISSUE TITLE
Error decoding audio buffer on Mac Safari/iOS

### ISSUE THREAD

**Issue by 16BarsHQ** [katspaugh/wavesurfer.js#2275]
Edit: Think we figured it out - it ended up being the source of the mp3 itself where it appears safari/iOS can't handle decoding certain sample rates (48 khz for instance). Switching that to 44.1 khz seems to have fixed this.

I'm using wavesurfer in a NextJS application and currently getting an error (Direct message from wavesurfer: Error decoding audiobuffer) when trying to load the waveform/audio on iOS devices as well as Mac Safari. As a result, it never hits the ready state or finishes loading the audio. I've tried switching the backend option to MediaElement or MediaElementWebAudio and it seems to have some progress, where the wavesurfer is able to process the audio, hit the ready state, and have audio controls like play/pause. But the wavesurfer visuals never load when I use that method and the same error decoding audiobuffer is still hit.

I've tried previously suggested methods for iOS issues like #2182 but they haven't helped. Would really appreciate any context on the potential error or any suggestions. Thank you!

### Wavesurfer.js version(s):
5.0.1

### Browser and operating system version(s):
iOS Chrome v87.0.4280.163
Mac Safari v13.1.3

### Code needed to reproduce the issue:
`
      const xhr = {
        cache: 'default',
        mode: 'cors',
        method: 'GET',
        credentials: 'same-origin',
      };
     
      const wavesurferInstance = WaveSurfer.create({
        container: waveformRef?.current,
        // backend: 'MediaElementWebAudio',
        audioContext: context || null,
        audioScriptProcessor: processor || null,
        waveColor: theme.color.brand.light24,
        progressColor: theme.color.brand.base,
        cursorColor: theme.color.brand.base,
        barWidth: 3,
        barRadius: 3,
        cursorWidth: 0,
        interact: interact,
        scrollParent: false,
        responsive: true,
        height,
        barGap: 3,
        plugins: interact
          ? [
              CursorPlugin.create({
                showTime: true,
                opacity: 1,
                color: theme.color.brand.base,
                width: rem(2),
                customShowTimeStyle: {
                  'background-color': theme.color.brand.base,
                  color: theme.text.alt.primary,
                  padding: theme.spacing.spacing3,
                  'border-radius': theme.radius.sm,
                  'font-size': rem(16),
                },
                formatTimeCallback: (time) =>
                  formatSongLength(Math.floor(time)),
              }),
            ]
          : [],
        xhr,
      });`

**Comment by thijstriemstra** [comment]
>  Edit: Think we figured it out - it ended up being the source of the mp3 itself where it appears safari/iOS can't handle decoding certain sample rates (48 khz for instance). Switching that to 44.1 khz seems to have fixed this.

Godo to hear, closing.
