### ISSUE TITLE
Next.js - WaveSurfer.create is not a function

### ISSUE THREAD

**Issue by arminhupka** [katspaugh/wavesurfer.js#2277]
Hey, i'm trying to create WaveSurfer player in Next.js but i have some issue.

I imported package like this 
```
const WaveSurfer = dynamic(() => { return import('wavesurfer.js') }, {ssr: false})
```
But when i trying to init im getting error **WaveSurfer.create is not a function**

Maybe someone have fix for this?

**Comment by thijstriemstra** [comment]
Please ask on next.js forums.
