### ISSUE TITLE
TypeError: Cannot read property 'decodeArrayBuffer' of null

### ISSUE THREAD

**Issue by vespakoen** [katspaugh/wavesurfer.js#2279]
### Wavesurfer.js version(s):

5.0.1

### Browser and operating system version(s):

Nw.js / Electron

### Code needed to reproduce the issue:

```js
		fs.readFile(file.replace('file://', ''), (err, buffer) => {
			if (err) {
				console.error(err)
				return
			}
			const blob = new window.Blob([new Uint8Array(buffer)])
			this.wavesurfer.loadBlob(blob)
		})
```

### Use behaviour needed to reproduce the issue:

I am using WaveSurfer wrapped in a React component, I have a list of sounds and I can navigate through this list with keyboard shortcuts, when I go very fast through the list, the situation occurs that the wavesurfer's backend is gone and WaveSurfer crashes with: `TypeError: Cannot read property 'decodeArrayBuffer' of null`

 This happens over here: https://github.com/katspaugh/wavesurfer.js/blob/4360968534076ee7ed834e5c0c4ad48279f133a9/src/wavesurfer.js#L1542

I think we are missing a "this.isDestroyed" check over here: https://github.com/katspaugh/wavesurfer.js/blob/4360968534076ee7ed834e5c0c4ad48279f133a9/src/wavesurfer.js#L1326

Because loadBlob is using the FileReader which is asynchronous: https://github.com/katspaugh/wavesurfer.js/blob/4360968534076ee7ed834e5c0c4ad48279f133a9/src/wavesurfer.js#L1358

Here are some screenshots from me walking up the stack:

<img width="1392" alt="Screenshot 2021-05-26 at 15 46 19" src="https://user-images.githubusercontent.com/876117/119671326-f8b5a800-be39-11eb-96f3-1e356a063d8b.png">
<img width="1392" alt="Screenshot 2021-05-26 at 15 46 26" src="https://user-images.githubusercontent.com/876117/119671344-fce1c580-be39-11eb-85c7-fa01328d965b.png">
<img width="1392" alt="Screenshot 2021-05-26 at 15 46 32" src="https://user-images.githubusercontent.com/876117/119671350-fe12f280-be39-11eb-9453-a1c30db59056.png">

**Comment by thijstriemstra** [comment]
Thanks for the detailed report @vespakoen

> I think we are missing a "this.isDestroyed" check over here: 

Sounds reasonable. Can you make a pr?
