### ISSUE TITLE
wavesurfer loop

### ISSUE THREAD

**Issue by massimilianocom** [katspaugh/wavesurfer.js#2282]
Is there a way to loop the wavesurfer?

**Comment by thijstriemstra** [comment]
https://www.w3schools.com/tags/att_audio_loop.asp

**Comment by tuminzee** [comment]
> https://www.w3schools.com/tags/att_audio_loop.asp

sorry, I am not able to understand can you please add an example.

I used  ` <div id="waveform" controls loop>
            </div>`

that doesn't seem to work.
Thank you in advance

**Comment by thijstriemstra** [comment]
you use the loop option with the MediaElement backend. Take a look at audio-element example and add loop to your <audio> tag.
