### ISSUE TITLE
Hello, my brother！I am from China

### ISSUE THREAD

**Issue by ytmsuhsff** [katspaugh/wavesurfer.js#2284]
Hello, my brother！I am from China I saw your article on the Internet. Can I save wavesurfer.js data, I'm not a professional programmer. I don't know how to operate. Can you help me

**Comment by ytmsuhsff** [comment]
![image](https://user-images.githubusercontent.com/85035822/120100980-4b62cd00-c176-11eb-82a2-053f067e4a75.png)

**Comment by ytmsuhsff** [comment]
How to save wave data, can you help me, I am not a programmer, do not know how to operate, hope the author can see can help me, thank you very much, hope to see can contact me, my email 285611750@qq.com

**Comment by ytmsuhsff** [comment]
Loading songs is too laggy.

**Comment by ytmsuhsff** [comment]
Load peak is needed to speed up loading

**Comment by ytmsuhsff** [comment]
Hope to get your help

**Comment by thijstriemstra** [comment]
It's not ok to spam the project like this. Blocked @ytmsuhsff
