### ISSUE TITLE
setplaybackrate set 0.5

### ISSUE THREAD

**Issue by djshox** [katspaugh/wavesurfer.js#2296]
when setplaybackrate set 0.5, the audio girls become audio boy. can be left as it is?

**Comment by sundayz** [comment]
Are you using the WebAudio backend or MediaElement backend

**Comment by Aparus** [comment]
I solved the same issue and wrote report  in #1710

**Comment by wfk007** [comment]
> WebAudio

same issue when backend default to WebAudio, but it works well when set to MediaElement
