### ISSUE TITLE
Rendering issue on Safari (14.1.1)

### ISSUE THREAD

**Issue by ahmadgulzar** [katspaugh/wavesurfer.js#2304]
Hi

It's the same issue reported by @gorkie [#975](https://github.com/katspaugh/wavesurfer.js/issues/975) but closed without feedback.

FireFox
<img width="1027" alt="firefox" src="https://user-images.githubusercontent.com/9460434/121799026-c4fcbf80-cc3a-11eb-87f8-5cc432a79f29.png">

Chrome
<img width="1023" alt="chrome" src="https://user-images.githubusercontent.com/9460434/121799031-caf2a080-cc3a-11eb-93f6-ab12359885b5.png">

Safari (waves are so small, just like a thin line)
<img width="1027" alt="safari" src="https://user-images.githubusercontent.com/9460434/121799039-d219ae80-cc3a-11eb-9027-a111ad9e8080.png">

```
<div class="podcast" id="podcast-4137" data-playerid="waveform_4137">
    <div class="play_action fas fa-play"></div>
    <div id="waveform_4137"></div>
</div>
```

```
var wavesurfer_4137 = WaveSurfer.create({
    container: document.querySelector('#waveform_4137'),
    waveColor: '#707070',
    progressColor: '#00ADED',
    cursorColor: '#011E41',
    forceDecode:true,
    interact: true,
    backend: 'MediaElement',
    barRadius: 3,
    cursorWidth: 1,
    height: 100,
    barGap: 3
});
wavesurfer_4137.load('https://MP3-URL.mp3');


jQuery("#podcast-4137 .play_action").click(function(){
    let action = $(this);
    if(action.hasClass("fa-play")){
        action.removeClass("fa-play").addClass("fa-pause");
		wavesurfer_4137.drawBuffer();
        wavesurfer_4137.play();
    }
    else{
        action.removeClass("fa-pause").addClass("fa-play");
        wavesurfer_4137.pause();
    }
    return false;
});
```

Thank you in advance.

**Comment by thijstriemstra** [comment]
@ahmadgulzar is it also happening with the example(s) on wavesurfer-js.org? if not, can you post an example somewhere online so we can test and reproduce this issue?

**Comment by ahmadgulzar** [comment]
Thanks @thijstriemstra 

[Here's the link: ](http://codegiggs.com/wavesurfer/)

It looks like the problem is with my mp3 file (first one).

<img width="1435" alt="Screenshot 2021-06-17 at 11 41 03 AM" src="https://user-images.githubusercontent.com/9460434/122353227-e7574b80-cf60-11eb-9b6e-da6c925a9606.png">


I just downloaded randomly different mp3 files from internet(podcasts) and the other one is working fine.

Any idea what could be issue with my mp3 file?

Thanks

**Comment by thijstriemstra** [comment]
try running ffprobe (part of ffmpeg) on the mp3 and post output here.

**Comment by ahmadgulzar** [comment]
Out for first audio

```
ffprobe version 4.4 Copyright (c) 2007-2021 the FFmpeg developers
  built with Apple clang version 12.0.5 (clang-1205.0.22.9)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.4_2 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-avresample --enable-videotoolbox
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
[mp3 @ 0x7fb5a4808200] Skipping 323 bytes of junk at 35089.
[mp3 @ 0x7fb5a4808200] Estimating duration from bitrate, this may be inaccurate
Input #0, mp3, from 'path-to-the-file.mp3':
  Metadata:
    encoder         : Lavf58.45.100
    title           : Title of Mp3
    artist          : Artist info
    album           : Album info
    genre           : Podcast
  Duration: 00:03:40.07, start: 0.000000, bitrate: 97 kb/s
  Stream #0:0: Audio: mp3, 44100 Hz, mono, fltp, 96 kb/s
  Stream #0:1: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 600x600 [SAR 1:1 DAR 1:1], 90k tbr, 90k tbn, 90k tbc (attached pic)
    Metadata:
      title           : Episode Artwork
      comment         : Cover (front)
```

Output for second audio

```
ffprobe version 4.4 Copyright (c) 2007-2021 the FFmpeg developers
  built with Apple clang version 12.0.5 (clang-1205.0.22.9)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.4_2 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-avresample --enable-videotoolbox
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, mp3, from 'path-to-the-file.mp3':
  Metadata:
    title           : Ganna music
    track           : 44
  Duration: 00:03:00.43, start: 0.069063, bitrate: 104 kb/s
  Stream #0:0: Audio: mp3, 16000 Hz, stereo, fltp, 104 kb/s
    Metadata:
      encoder         : LAME3.99r
```

**Comment by thijstriemstra** [comment]
Try reconverting the files with ffmpeg to 44khz mp3 and other combos until it works..?

**Comment by sundayz** [comment]
There's a lot of inconsistencies between different backends when it comes to rendering :S I haven't been able to figure why sometimes waveforms appear as a single line, but using pre-calculated peaks reduces the chance of this happening a lot, maybe even fixes it.

Are you seeing this consistently or does it go away when you refresh the page?

**Comment by ahmadgulzar** [comment]
> Try reconverting the files with ffmpeg to 44khz mp3/ogg and other combos until it works..?

Thanks! It worked by converting to 44khz.

**Comment by designerfuzzi** [comment]
Same here. The examples work fine. I am developing an audio app on macOS and implemented just for fun a WKWebView that makes use of wavesurfer.js. For testing purposes i used the Demo.wav that comes with the repository. It plays fine, but the graphics are always a zero-line. Changing barWidth or Height does not matter.. 
So to speak 44khz file as source does not solve it.

**Comment by amccloud** [comment]
For those running into this issue. I'm only running in to this issue when using backend: `MediaElement`, while `webaudio` works fine:

<img width="1496" alt="Screen Shot 2021-12-12 at 9 24 50 AM" src="https://user-images.githubusercontent.com/38463/145722722-b38a0c0c-20a1-437d-894a-e09cc15f155d.png">

I've noticed that resizing my browser, forcing wavesurfer to overflow, and then scrolling the tracks reliably forces the single line to render a waveform with the MediaElement backend.

Once it is rendered I can resize the browser back up, but notice the rendering is not responding with `scrollParent` set to false. Notice blank space at end of song:

<img width="1496" alt="Screen Shot 2021-12-12 at 9 23 29 AM" src="https://user-images.githubusercontent.com/38463/145722661-c8b40785-bc41-4987-9d37-daa00d4a3e3c.png">

With `responsive` true, the resizing trick also appears to work without scrolling:

<img width="1151" alt="Screen Shot 2021-12-12 at 9 37 24 AM" src="https://user-images.githubusercontent.com/38463/145723153-40f9d26e-921a-4b80-b58d-781a7d346f99.png">

(sorry, dev environment so song changed. The waveform appears and spans 100% after browser resize only)

**Comment by theswerd** [comment]
Can someone explain how to do this?

> Try reconverting the files with ffmpeg to 44khz mp3/ogg and other combos until it works..?
