### ISSUE TITLE
wavesurfer is not defined

### ISSUE THREAD

**Issue by massimilianocom** [katspaugh/wavesurfer.js#2306]
Why am I getting the "wavesurfer is not defined" problem?

var track = "/audio/files/audio.mp3";
$(".waveform").each(function(){
     var wavesurfer = WaveSurfer.create({
     container: this,
     waveColor: '#616161',
     progressColor: '#80c2ff',
     barWidth: 1,
     barRadius: 0,
     responsive: true,
     cursorWidth: 0
});
wavesurfer.load(track);
});

**Comment by thijstriemstra** [comment]
Because you didn't include or import the wavesurfer.js script. Take a look at the examples.

**Comment by massimilianocom** [comment]
Of course including it here is the full example:

<script src="https://unpkg.com/wavesurfer.js"></script>
<script>
$(".waveform").each(function(){
            var wavesurfer = WaveSurfer.create({
                container: this,
                waveColor: '#616161',
                progressColor: '#80c2ff',
                barWidth: 1,
                barRadius: 0,
                responsive: true,
                cursorWidth: 0
            });
        });
        var track = "/audio/files/<?php echo $rec['IDUserAccount']."/".$rec['FileAudio']; ?>";
        wavesurfer.load(track);
</script>

...

<div class="waveform"></div>
<div class="waveform"></div>

**Comment by massimilianocom** [comment]
Ovviamente includendolo qui c'è l'esempio completo:

<script src="https://unpkg.com/wavesurfer.js"></script>
<script>
$(".waveform").each(function(){
var wavesurfer = WaveSurfer.create({
container: this,
waveColor: '#616161',
progressColor: '#80c2ff',
barWidth: 1,
barRadius: 0,
responsive: true,
cursorWidth: 0
});
});
var track = "/audio/files/<?php echo $rec['IDUserAccount']."/".$rec['FileAudio']; ?>";
wavesurfer.load(track);
</script>

...

<div class="waveform"></div>
<div class="waveform"></div>
