### ISSUE TITLE
Waveform doesn't render or playing my files - Webflow

### ISSUE THREAD

**Issue by kiwikreativ** [katspaugh/wavesurfer.js#2308]
Hey,

I've tried everything and read all documentations, FAQ and so on ... but ...
After implemented the wavesurfer.js , it doesn't render on my Webflow website. 

Here my Test Site:
https://wave-lp.webflow.io

Can you help me out?

Thank you so much!

**Comment by icecoveredjune** [comment]
You tried to load audio over http:// in https page. So browser block request because of [mixed](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content) content. Use https link instead.
