### ISSUE TITLE
I cannot load multiple times or how to reload the blob

### ISSUE THREAD

**Issue by Thor1016** [katspaugh/wavesurfer.js#2314]
Hello everyone, I used a microphone plugin and get blob from MediaRecorder. when user stop the microphone, I will loadBold and it is work, but the blob cannot be loaded the second timeBut the blob cannot be loaded the second time. It looks like it cannot loadBlob for the second time, this is an empty. how to reload the blob?

wavesurfer.js version (5.1.0)
![image](https://user-images.githubusercontent.com/78396335/123614163-a996d480-d836-11eb-9048-b3e6747ce3f5.png)
![image](https://user-images.githubusercontent.com/78396335/123615131-9801fc80-d837-11eb-9720-359a99fb1ee6.png)

**Comment by thijstriemstra** [comment]
what does the structure of `chunks` object look like?

**Comment by jiangen1016** [comment]
> what does the structure of `chunks` object look like?

That's good, because I forget stop the stream. When I stop the MediaRecorder stream, it is work.

**Comment by thijstriemstra** [comment]
>  it is work.

Good to hear.
