### ISSUE TITLE
Running wavesurfer with nodejs to create peaks for preloading

### ISSUE THREAD

**Issue by httpsterio** [katspaugh/wavesurfer.js#2318]
Is it possible to do a "dry run" of wavesurfer to generate the peaks instead of the documented ffmpeg based method? I'm trying to run wavesurfer in an environment where C and bash based tools don't run and would like to provide the peaks before the users have to load the whole audio file.

**Comment by sundayz** [comment]
You can generate the peaks somewhere that has access to those tools, then serve them from a normal web server as JSON files, and make your page with wavesurfer load the peaks before the mp3 file, they'll only be a few kilobytes.

**Comment by httpsterio** [comment]
Yes, that's possible but it's not what I'm asking about. In my usecase I'm not the one deploying the application, I'm enabling non-tech people to fork my project and manage their own content with as much ease as possible, directly from the browser.

**Comment by sundayz** [comment]
The library is built specifically for the browser and making it run within node is a LOT of work. [audiowaveform](https://github.com/bbc/audiowaveform) or generating peaks in the browser are your best bet, not sure why in your scenario node.js would work but a small 3MB exe wouldn't.

**Comment by thijstriemstra** [comment]
> not sure why in your scenario node.js would work but a small 3MB exe wouldn't.

Also note that audiowaveform library is highly optimized and C++, much faster than any nodejs implementation.

**Comment by weavermedia** [comment]
If you need to do it client side this might help: https://css-tricks.com/making-an-audio-waveform-visualizer-with-vanilla-javascript/

Caveat:
>This is a very, very impractical way of visualizing audio. It runs on the client side, processing millions of data points into a fairly straightforward visualization. But it’s cool!

**Comment by sundayz** [comment]
Closing but feel free to reopen if you provide more details about your deployment environment so we can suggest other ways of achieving what you want to do.
