### ISSUE TITLE
Cannot find package wavesurfer.js.map@latest

### ISSUE THREAD

**Issue by KoniKodes** [katspaugh/wavesurfer.js#2319]
# Hey, thank you for testing and contributing to wavesurfer.js!

## Please make sure you can check all of these points below before opening an issue:

(You don't have to post this section)

- [x ] I have checked [the FAQ](https://wavesurfer-js.org/faq/) and it doesn't solve my problem.
- [x ] I have checked [the documentation](https://wavesurfer-js.org/docs/) and it doesn't solve my problem
- [x] I have searched for [already open issues](https://github.com/katspaugh/wavesurfer.js/issues) which desribe my problem.
- [x] The issue I'm having is related to and caused by wavesurfer.js, not by other software (which maybe packages and uses wavesurfer incorrectly) – In that case you should open the issue on the respective project pages.

### Wavesurfer.js version(s):

today, from https://unpkg.com/wavesurfer.js

### Browser and operating system version(s):
Chrome
On CodePen got an error saying could not map...
copied the url into chrome and got message: Cannot find package wavesurfer.js.map@latest

### Code needed to reproduce the issue:
inspected:
wavesurfer.js:5660 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
wavesurfer.js:5770 [Deprecation] The ScriptProcessorNode is deprecated. Use AudioWorkletNode instead. (https://bit.ly/audio-worklet)
DevTools failed to load source map: Could not load content for https://unpkg.com/wavesurfer.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

(Please reduce your code as much as possible and only post the minimum code needed to reproduce the issue. [A Code pen](http://codepen.io/) is an excellent way to share such code)

https://codepen.io/KoniKodes/pen/mdmEpMV?editors=1111
### Use behaviour needed to reproduce the issue:
I'm still learning to attach...

**Comment by sundayz** [comment]
Specify the version number in the unpkg link: https://unpkg.com/wavesurfer.js@5.1.0/dist/wavesurfer.js

Using `@latest` is bad because if the project publishes a new version in the future then your project might (will) break.

**Comment by KoniKodes** [comment]
Thank you. 

Documentation said to just link as … wavesurfer.js … so I wasn’t aware.

 

Changing to this link did solve my issue.
