### ISSUE TITLE
Longer audio doesn't get the full length, like 30 minutes

### ISSUE THREAD

**Issue by wxhyyy1** [katspaugh/wavesurfer.js#2321]
this.wavesurfer = WaveSurfer.create({
  container: '#waveform',
  skipLength: 5,
  barWidth:2,
  backgroundColor:"#1B2127",
  progressColor:"#DC5E4D",
  waveColor:"#DC5E4D",
  cursorColor:"#DC5E4D",
  cursorWidth:2,
  scrollParent:true
});

 this.wavesurfer.load('https://static.quhouse.com/audio/d7879fbcdfcc436189ce79e643e0aeb8.mp3');
I can only get minutes. What's that because of? Is it an audio format problem

**Comment by thijstriemstra** [comment]
> I can only get minutes. 

Can you explain exactly what you mean with that?

If it's an audio format problem, run ffprobe (part of ffmpeg) on the audio file and paste the output here.

**Comment by wxhyyy1** [comment]
I can't run the FFprobe command here because I don't have an environment to respond to.

https://static.quhouse.com/audio/d7879fbcdfcc436189ce79e643e0aeb8.mp3

The above is the address of the audio, could you please help to check it

**Comment by thijstriemstra** [comment]
ffprobe reports this output:

```
Input #0, mp3, from 'd7879fbcdfcc436189ce79e643e0aeb8.mp3':
  Metadata:
    encoder         : Lavf58.20.100
  Duration: 00:10:04.51, start: 0.066125, bitrate: 32 kb/s
  Stream #0:0: Audio: mp3, 8000 Hz, mono, fltp, 32 kb/s
```


Please explain the problem (and include wavesurfer version, operating system, browser etc).
