### ISSUE TITLE
Regions as colored bars?

### ISSUE THREAD

**Issue by nevahid** [katspaugh/wavesurfer.js#2326]
Hi everyone, is it possible to draw regions as colored bars? I mean like the progress wave, we color the wave (some chosen color) for selected area of the waveform. something like the below image. thanks
![region bars](https://user-images.githubusercontent.com/19144552/125765371-978d3393-d3c0-4a6d-9105-45754dfb2a22.jpg)

**Comment by sundayz** [comment]
The `barGap`, `barWidth` and `barRadius` can get you a similar effect, and for the colors you might be able to use the region divs as CSS masks over the canvas wave, and apply some color filtering using that mask. Would be an easy way without writing your own renderer.

**Comment by nevahid** [comment]
That is what I want to achieve about regions... can you give me an example about adding mask to canvas wave? and what would happen to regular regions? should I override some functions or anything? thanks

**Comment by sundayz** [comment]
![image](https://user-images.githubusercontent.com/11685806/125976455-9974d92a-1e9e-49e9-b682-479b82797b92.png)

I did this by simply applying `backdrop-filter: hue-rotate(120deg);` to a region. The waveform is red, and now the area of the waveform under the region is green. However this doesn't work in Firefox (not even the latest).

You're on your own 😃 It seems like `filter` doesn't affect elements behind the target element, and I don't know if masking helps with that. Maybe you can mask parts of the waveform canvas and apply CSS to those segments only, I don't know. Here's a helpful article: https://css-tricks.com/almanac/properties/c/clip-path/

Other than that, I can't give you any other advice. Worst case scenario you will have to write a custom renderer for Wavesurfer. GL.

**Comment by nevahid** [comment]
Thanks for your response, I will first try mask and clip, if I couldn't succeed I will then try changing the way wave bars are drawn, maybe using svg instead of canvas so that I can manipulate it easily. Thanks again.

**Comment by jadenmazzone** [comment]
@nevahid were you able to figure this out?
