### ISSUE TITLE
[Deprecation] The ScriptProcessorNode is deprecated. Use AudioWorkletNode instead. 

### ISSUE THREAD

**Issue by KoniKodes** [katspaugh/wavesurfer.js#2328]
`(https://bit.ly/audio-worklet) createScriptNode @ webaudio.js:234`

### Wavesurfer.js version(s):
5.1

### Browser and operating system version(s):
Chrome

### Code needed to reproduce the issue:
```
$("#0").on("click", function(){
 var wavesurfer = WaveSurfer.create({
    container: '#waveform',
    waveColor: 'violet',
    progressColor: 'purple'
});
```

**Comment by sundayz** [comment]
Safari finally supports AudioWorklet and (all?) browsers will replace ScriptProcessorNode with it, so we should look at this in the near future.

**Comment by KoniKodes** [comment]
Great! Thank you.

**Comment by sundayz** [comment]
Related:  #1281

**Comment by heresy0-0y** [comment]
ScriptProcessorNode is now deprecated by MDN, and all browsers have full support for AudioWorklet (excepting the processorerror event in Safari).

https://developer.mozilla.org/en-US/docs/Web/API/AudioWorkletNode

**Comment by KoniKodes** [comment]
Thank you.
