### ISSUE TITLE
How to prevent further events from firing

### ISSUE THREAD

**Issue by DonRoden** [katspaugh/wavesurfer.js#2329]
I want to play the region from start to end when double clicking inside, it looks like the region is played but then the `seek` event is fired after the double click and pause/play the audio so it starts again at the location of the click and keeps going after the region ends. Is there a way to prevent further events from interacting with the current audio ?

**Comment by sundayz** [comment]
You can do something like this:

```js
wavesurfer.setDisabledEventEmissions(['seek']);
// Do stuff here, seek wont be emitted.
wavesurfer.setDisabledEventEmissions([]); // set all events to emit once you're done
```

**Comment by tourbillonlabs** [comment]
Hello!

I am trying to achieve this same thing with a double-click on region to play, but also allowing a single-click within the region to seek.

@sundayz Can you please provide a little more info about using the snippet you provided? I've tried something like this (with and without the `stopPropagation` and it still fires the single click actions.

```
wavesurfer.on("region-dblclick", (region, e) => {
  e.stopPropagation();
  wavesurfer.setDisabledEventEmissions(['seek']);
  region.play();
  wavesurfer.setDisabledEventEmissions([]);
});
```

I've implemented a slightly more involved solution which listens for both `region-click` and `region-dblclick` and uses `setTimeout` to track for a single/double that does what I need, but if the snippet you provided offers a more 'in-house' solution for managing double-clicks, that would be ace.
