### ISSUE TITLE
Long MP3 files does not play on Chrome Browser

### ISSUE THREAD

**Issue by jofomah** [katspaugh/wavesurfer.js#2330]
### Wavesurfer.js version(s):

- wavesurfer.js 5.0.1 (2021-05-05)

### Browser and operating system version(s):

Chrome Browser  and Ubuntu 

### Code needed to reproduce the issue:

```js
const options = {
                    backgroundColor: '#FFFFFF',
                    progressColor: '#85A5C2',
                    waveColor: '#FE0D66',
                    responsive: true,
                    height: 105
                };
let waveSurfer = new WaveSurfer.create(options)

const src = '.... any MP3 that last long 5, 10 or 30 mins'
waveSurfer.load(src)
```

### Use behaviour needed to reproduce the issue:

I am able to reproduce this only on Chrome browser, works fine on Firefox and play the whole say 30 mins length but on Chrome, for an MP3 file of 5 mins, it will play only the first 10 seconds.

~bug

**Comment by sundayz** [comment]
In my project often use Wavesurfer to play files of 5+ min and Chrome is by far the best performing browser, are you specifying a backend or using the MediaElement default backend? If you're doing that then wavesurfer uses a pretty standard `<audio>` element which should work fine, have you looked in the Network log in the developer tools to see if maybe there's a network issue, e.g. your server stops sending audio during the stream? Also check the console for any error messages.

**Comment by thijstriemstra** [comment]
> wavesurfer.js 5.0.1 (2021-05-05)

Also make sure to use latest version of wavesurfer.js.

**Comment by thijstriemstra** [comment]
no feedback, closing.
