### ISSUE TITLE
Title for separate Waveforms

### ISSUE THREAD

**Issue by Obayanju** [katspaugh/wavesurfer.js#2344]
This is more of a feature request. When waveforms are split, I want to be able to add some text in between them. I've read the docs and checked previous issues and I don't think it's been brought up before. 

I'm willing to open a PR that creates a plugin for this, but just wanted to be sure that I'm not solving a solved problem :)

### Wavesurfer.js version(s):
3.3

### Browser and operating system version(s):
Chrome Version 91.0.4472.114 (Official Build) (x86_64)

The split waveform example is a good example. Adding a text in between the wave would be the desired outcome
https://wavesurfer-js.org/example/split-channels/index.html

**Comment by thijstriemstra** [comment]
can you make sure to use latest version and maybe add an annotated img/screenshot of what you're trying to achieve?

**Comment by Obayanju** [comment]
Sorry for the late reply. I've now updated my version to 5.2.0

Here's a screenshot
![wave-surfer](https://user-images.githubusercontent.com/23620997/131197385-86e6833e-a296-4891-bdda-21da1e2f29c7.jpg)

**Comment by sundayz** [comment]
you could extend the default renderer class and provide your own:

https://github.com/katspaugh/wavesurfer.js/blob/master/src/drawer.multicanvas.js

I haven't tried, but maybe it can be done by overriding `drawWave` to first draw your custom text, then call the superclass function.

Of course you can also just do it through HTML but in this case both waveforms are drawn on a single canvas so you'd have to absolute position your text element.

**Comment by thijstriemstra** [comment]
no further feedback, closing.
