### ISSUE TITLE
Waveform highlight on hover

### ISSUE THREAD

**Issue by adamiusz** [katspaugh/wavesurfer.js#2347]
I have a question, is it possible to highlight the entire area to the left of the cursor on the waveform to the progress wave - as the red rectangle is shown - this is about this region - when hovering over the waveform?

![img](https://user-images.githubusercontent.com/1034357/130856600-315d01b2-c22d-4218-87a8-4740523c916d.png)

**Comment by Spirit04eK** [comment]
Maybe you try [wavesurfer region plugin](https://wavesurfer-js.org/plugins/regions.html)?

**Comment by entonbiba** [comment]
as a quick solution you can add a transparent div overlay that display when the cursor is hovered. 

have a look at this sample where it uses mouse hover event to display current play time for reference,
https://codepen.io/entonbiba/pen/KaymLp?editors=0110

**Comment by thijstriemstra** [comment]
no further feedback, closing.
