### ISSUE TITLE
How to play audio file in loop by default?

### ISSUE THREAD

**Issue by naveenkumarmca** [katspaugh/wavesurfer.js#2354]
Hi,

I would like to play the audio file in loop whenever the page loads or wavesurfer.on 'ready' function.
Is it possible to do like this?

I see that wavesurfer does not have playLoop() function but it has play() which plays the audio for only 1 time.
I dont want to use the region.playLoop() as I need this functionality in the ready function.

Can you please guide on this?

**Comment by Spirit04eK** [comment]
```
waveform.once('ready', () => {
  waveform.play();
});

waveform.on('finish', () => {
  waveform.play();
});
```
[example](https://codesandbox.io/s/pedantic-mclaren-m1ur1?file=/src/index.js)

**Comment by naveenkumarmca** [comment]
@Spirit04eK thanks a lot!!
