### ISSUE TITLE
Sometimes, I can play audio, but I can't get duration.

### ISSUE THREAD

**Issue by 90ker** [katspaugh/wavesurfer.js#2358]
### Wavesurfer.js version(s):
4.2

### Browser and operating system version(s):
macOS, Chrome the latest version.

### Code needed to reproduce the issue:

![image](https://user-images.githubusercontent.com/35322206/132943681-82e61321-0f45-473a-afd6-a1b61e6fb48d.png)

### Use behaviour needed to reproduce the issue:
When i set backend with WebAudio. I change the play rate it will change the tone of audio.
But i don't want change the tone. So i set the backend with MediaElement.
And it cause new problem that sometime it can't getDuration. While the audio can play.
I can't recurrent the case because it only Occasionally happen in the production environment.

**Comment by thijstriemstra** [comment]
> I can't recurrent the case because it only Occasionally happen in the production environment.

Please log the user agent and other info to see in what browser/operating system it's happening.

**Comment by sundayz** [comment]
Maybe see what happens when you replace the `'ready'` event with `'waveform-ready'`, also does it happen with the same audio file, or does it happen with different audio?

**Comment by thijstriemstra** [comment]
no feedback; closing.
