### ISSUE TITLE
Incorrect typescript for definition for `wavesurfer.regions.list`

### ISSUE THREAD

**Issue by sahi1422** [katspaugh/wavesurfer.js#2361]
### Wavesurfer.js version(s):
"wavesurfer.js": "^5.2.0",
"@types/wavesurfer.js": "^5.2.0"

### Browser and operating system version(s):
Chrome
Mac OS

### Code needed to reproduce the issue:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/1733d8457f1825f4e716b8525d25a4f2f6420da2/types/wavesurfer.js/src/plugin/regions.d.ts#L27

### Use behaviour needed to reproduce the issue:
@caugner @thijstriemstra After logging `ws.regions.list`, it is clear that the type should be `{[key: string]: Region}` instead of `Region[]`.

**Comment by thijstriemstra** [comment]
@sahi1422 please open a pull request against `types/wavesurfer.js/src/plugin/regions.d.ts`, file is not part of this repository.

**Comment by sahi1422** [comment]
@thijstriemstra , the [PR got merged](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/55907). Thanks!
