### ISSUE TITLE
hideCursor

### ISSUE THREAD

**Issue by Raspberry42** [katspaugh/wavesurfer.js#2366]
Hello, I saw that there is a hideCursor() function but it doesn't work.

Is it possible to have an example to use it?
Thanks in advance.

**Comment by entonbiba** [comment]
@Raspberry42 we don't have a function called hideCursor(), it's something we can add as an option instead though. However you can simply add the following css to your page

``` css
wave{
    cursor: none;
}
```

**Comment by entonbiba** [comment]
pr created #2367

**Comment by Raspberry42** [comment]
Yeah I was talking about the waveform marker

**Comment by entonbiba** [comment]
ok we shall add that as well :)

**Comment by entonbiba** [comment]
if you need something quick you can do the following css @Raspberry42 

```
wave > wave{
    border-right: none!important;
}
```

**Comment by sundayz** [comment]
It's very simple to hide the cursor, you just do this:

`wavesurfer.setCursorColor('rgba(0, 0, 0, 0)');`

The numbers for rgb don't matter, alpha 0 is invisible.
