### ISSUE TITLE
Manually add regions when 'interact' is 'false' and 'enableDragSelection' is not enabled

### ISSUE THREAD

**Issue by kilgarenone** [katspaugh/wavesurfer.js#2370]
I would like users to create regions by double-clicking on the waveform that don't have any regions to being with. 

```
wavesurfer.container.addEventListener("dblclick", function (e) {
  // do wavesurfer.addRegion({start, end }) here
});
```
But I couldn't find a way to get the value for the `start` time for `addRegion()` from the double-clicks.

I tried listening to `dblclick` on `wavesurfer`, but no events there either.

Did I miss an official API that does that or I have to calculate them myself?

**Comment by sundayz** [comment]
You have to calculate them yourself, but you are right, this should be part of the Wavesurfer API. 

Here's an example that should work:
```
wavesurfer.container.addEventListener("dblclick", function (e) {
    const rect = e.target.getBoundingClientRect();
    const x = e.clientX - rect.left; // x position along the waveform
    const percent = x / e.target.scrollWidth; // 0 to 1 range, 0 = start, 1 = end
    const time = wavesurfer.getDuration() * percent;
    
   wavesurfer.addRegion({start: time, end: time + 5 });
});
```

**Comment by kilgarenone** [comment]
The example was much appreciated - thank you 🙇
