### ISSUE TITLE
microphone plugin is not work in iOS 15.0

### ISSUE THREAD

**Issue by davidmwt** [katspaugh/wavesurfer.js#2371]
https://wavesurfer-js.org/example/microphone/index.html

This plugin is working fine in android and iOS 14, but no response in iOS15.0.

**Comment by entonbiba** [comment]
will have a look, is this on the safari ios browser and have you given permission to safari browser to use the microphone by default in the ios settings?

**Comment by davidmwt** [comment]
Thank you for your support, Entonbiba. In my project, plugin is running well in android and iOS 14. I've tested it in Safari and Chrome, same issue in iOS 15. 

I use "Start record" and "Stop record". 
"Start record", it works.
"Stop record", no response and there is an alert msg is showed in console after clicked tis button.
_"MediaRecorder API seems unable to record mimeType: – "audio/wav"_

**Comment by thijstriemstra** [comment]
> "MediaRecorder API seems unable to record mimeType: – "audio/wav"

This is not an error message that microphone plugin would create though, it doesn't use the MediaRecorder API.
