### ISSUE TITLE
How can get 'from' position when seek event fires?

### ISSUE THREAD

**Issue by Adrian-Swifter** [katspaugh/wavesurfer.js#2381]
I am getting a position when seek event fires, and that serves as 'to', but I also need a 'from' position and that is something I didn't find looking through docs. Can you please explain how can I achieve this?

**Comment by entonbiba** [comment]
@Adrian-Swifter you can use the `wavesurfer.getCurrentTime()` method that returns the current position by default you know it's the start. So next time the seek event happens inside the function save it as the current time and use that as the from.

We will add this as an enhancement to the current seek event to return the from position as well.

**Comment by entonbiba** [comment]
pr created #2410

**Comment by Gigamick** [comment]
I use this code which I think is what you've suggested:

```
    wavesurfer{{$p}}.on('seek', function () {
        var t = wavesurfer{{$p}}.getCurrentTime();

        $.ajax({
            type: 'POST',
            url: '/updateseek',
            data: {
                trackID: {{$item->track_id}},
                token: "{{$songbox->token}}",
                songbox: "{{$songbox->songbox}}",
                time: t
            }
        });
```

But the getCurrentTime here is the time the users seeks TO, not FROM. Am I missing something?

**Comment by entonbiba** [comment]
@Adrian-Swifter use `wavesurfer.backend.getPlayedTime()`
