### ISSUE TITLE
wavesurfer marker

### ISSUE THREAD

**Issue by nomilk1** [katspaugh/wavesurfer.js#2386]
Helllo, i'm trying to use wavesurfer.js and I have a problem.

I'll like to add markers on a wave form, but I don't know how to do it. 

I'll like to have three type of markers : 
- position marker : which will start the music from its position and saved in the meta data
- region marker : consist of adding 2 markers, the audio will start from the beginning of the first marker and will end at the last one. 
- temporary marker : just like the position marker but not saved in the meta data.

please help, thanks

**Comment by thijstriemstra** [comment]
Take a look at the markers plugin example: https://wavesurfer-js.org/plugins/
