### ISSUE TITLE
I have a problem with the wave peaks of the audios

### ISSUE THREAD

**Issue by Sameer4real** [katspaugh/wavesurfer.js#2388]
Everything was great while using audio saved in my local storage, the peaks were showing and everything was fine.
The problem started showing once I tried to use the audio that I uploaded on AWS, the peaks stoped showing!
Does anyone have an idea?

**Comment by thijstriemstra** [comment]
Something with CORS?

**Comment by Sameer4real** [comment]
My problem is when I try to get audio from the back-end, the peaks of that audio don't show up
if I use audio directly from the client side it shows and works perfectly...
here's a snippet of the code where I have the problem

`wavesurfer = WaveSurfer.create({
      container: waveformRef.current,
      waveColor: "#747993",
      height: 90,
      responsive: true,
      progressColor: "#393F65",
      normalize: true,
      backend: "MediaElement",
      plugins: [
        RegionsPlugin.create({
          dragSelection: {
            slop: 5,
            color: "hsla(9, 100%, 64%, 0.1)",
          },
        }),
        TimelinePlugin.create({
          container: "#timeline",
          formatTimeCallback: formatTimeCallback,
          timeInterval: timeInterval,
          primaryLabelInterval: primaryLabelInterval,
          secondaryLabelInterval: secondaryLabelInterval,
          primaryColor: "#2A045A",
          secondaryColor: "#747993",
          primaryFontColor: "#2A045A",
          secondaryFontColor: "#747993",
          formatTime: "HH:MM:SS",
        }),
      ],
    });

    wavesurfer.load(audioUrl);`
