### ISSUE TITLE
How do I use peaks with an audio coming from the back-end in React Wavesuref?

### ISSUE THREAD

**Issue by Sameer4real** [katspaugh/wavesurfer.js#2392]
I have a problem using back-end media elements with peaks in this library the peaks stopped working or did not appear when I try to get the audio from a database connected to the back-end... on the other hand, when I use the audio directly on the client-side the peaks work just fine because I didn't have to use media elements with this option!

Does anyone have an idea?

**Comment by thijstriemstra** [comment]
not sure what React Wavesurfer is. Please open a ticket in that project instead.
