### ISSUE TITLE
Waveform shorter than container

### ISSUE THREAD

**Issue by SpaceMonkey1** [katspaugh/wavesurfer.js#2393]
I can't get the Wavesurfer.js working with a fixed minPxPerSec value. The container seems to have a correct width (minPxPerSec * duration), but the actual waveform is too short. This means the cursor is out of sync with the waveform.

For example, in this code I set the minPxPerSec to 10:
https://jsfiddle.net/75yvctw8/

I had similar results for 3s audio and minPxPerSec = 200. 

My temporary fix is setting the container to the desired width in this event:

```
const maxWidth = 1000;

this.wavesurfer.on("ready", () => {
      let contWidth = this.wavesurfer.minPxPerSec * this.wavesurfer.getDuration()
      contWidth = Math.min(maxWidth, contWidth)
      // set container width to contWidth here
      this.wavesurfer.drawBuffer()
});
```

### Wavesurfer.js version(s):
5.2.0

### Browser and operating system version(s):
Chrome
Edge

### Code needed to reproduce the issue:

https://jsfiddle.net/75yvctw8/

### Use behaviour needed to reproduce the issue:
Play audio in example

**Comment by entonbiba** [comment]
@SpaceMonkey1 change to `fillParent: true,`

**Comment by SpaceMonkey1** [comment]
@entonbiba in my project I need to have a fixed number of pixels per second (minPxPerSec), so I cannot stretch the waveform by using fillParent: true.

**Comment by entonbiba** [comment]
@SpaceMonkey1 

The div requires a default width set to it if you want it specific vs responsive. You can change the width as you need with the css below.

![image](https://user-images.githubusercontent.com/5193884/143148712-5224f5cd-0bed-4c8a-8774-34052da085f5.png)

```css
#waveform{
  width: 100px;
}
```
```js
    wavesurfer = WaveSurfer.create({
        container: document.querySelector('#waveform'),
        waveColor: '#A8DBA8',
        progressColor: '#3B8686',
        backend: 'MediaElement',
        minPxPerSec: 10
    });
```

**Comment by thijstriemstra** [comment]
no feedback, closing.
