### ISSUE TITLE
How can i get the peak json data of an audio；

### ISSUE THREAD

**Issue by tingshuai** [katspaugh/wavesurfer.js#2394]
**versions:      wavesurfer.js@5.2.0**

> _I want to get the peak json data of an audio,how to do that?_

> _I have not found the api about this;_
could someone help me ?

what i want the peak data just like this :
[
{'x':1.00 ,'y':-66.14356552},
{'x':2.00 ,'y':-66.3397134},
{'x':3.00 ,'y':-66.90808776} 
.....
]

**Comment by Mladja** [comment]
You can read it [here](https://wavesurfer-js.org/faq/). 
Good luck!

**Comment by tingshuai** [comment]
> You can read it [here](https://wavesurfer-js.org/faq/). Good luck!
Is there someway generate waveform data on the client in browser?;

**Comment by entonbiba** [comment]
For now you may follow the `https://github.com/bbcrd/audiowaveform` route as specified in the FAQ here `https://wavesurfer-js.org/faq/`

I had a service that did just this online before, once I update to the new domain I will be adding a api integration for wavesurfer.js project as a plugin.
