### ISSUE TITLE
Draw custom element on existing canvas element? 

### ISSUE THREAD

**Issue by Mladja** [katspaugh/wavesurfer.js#2395]
Tag as a question, please.
First of all, thank you for this awesome library. I was managed to do a lot of cool stuff with it.

My question that I have is it possible to draw some elements beneath waveform but based on the time segment that I'm running on waveform?
I have some speech that starts from { time: 0ms } and ends on { time: 1233ms } and etc.
Basically something like a commercial that is running in the background.

I'm about to try with the div element but I don't really have a clue how I'm going to know how big element should be (width), and another issue that I see coming with that approach is when zooming waveform. Oh yeah, when scrolling too.  
Any ideas? 
Thanks in advance!

![Screenshot 2021-11-03 at 22 29 20](https://user-images.githubusercontent.com/7488636/140195490-305a9986-caae-4169-ba05-c56ad5c3b518.png)

**Comment by thijstriemstra** [comment]
You can draw on the wave canvas: `wavesurfer.drawer.canvases[0].wave.domElement` or progess canvas: `wavesurfer.drawer.canvases[0].progress.domElement`
