### ISSUE TITLE
Destroying wavesurfer region plugin causus events to emit that appear the same as user events

### ISSUE THREAD

**Issue by n0mn0m** [katspaugh/wavesurfer.js#2403]
I've setup a react component with wavesurfer and it works great! One thing I observed that I thought was a bit odd is if I provide functionality where a user interaction causes wavesurfer to be destroyed and recreated there are events emitted during the wavesurfer `destroy()` teardown that seem like internal events mixed with user events.

Specifically for the region plugin when [`destroy`](https://github.com/katspaugh/wavesurfer.js/blob/f04e9253feba0cbcf91e316d1a0c8818db3a363b/src/plugin/regions/index.js#L175) is called [`clear`](https://github.com/katspaugh/wavesurfer.js/blob/f04e9253feba0cbcf91e316d1a0c8818db3a363b/src/plugin/regions/index.js#L225) calls [`remove`](https://github.com/katspaugh/wavesurfer.js/blob/f04e9253feba0cbcf91e316d1a0c8818db3a363b/src/plugin/regions/region.js#L133) from `region.js` which emits `region-removed`. This is the same event that gets emitted when a user interaction causes a region to be removed, but instead it is being emitted because of an internal mechanism in the plugin teardown. It's also a public event in the [docs](https://wavesurfer-js.org/plugins/regions.html) so I think it is meant to be used for tracking user space interactions, not internal wavesurfer events if that makes sense?

This is the stack trace from devtools.

```
remove (region.js:133)
(anonymous) (index.js:220)
clear (index.js:219)
destroy (index.js:175)
destroyPlugin (wavesurfer.js:660)
(anonymous) (wavesurfer.js:674)
destroyAllPlugins (wavesurfer.js:673)
destroy (wavesurfer.js:1740)
```

I wanted to get the maintainers thoughts to see if it makes sense to change the plugin `destroy` and `clear` functions work so that `clear` doesn't emit a `region-removed` event (because it calls `remove`). Instead it would do the same operations, but emit a `regions-destroyed` or other event. I know that `clear` is removing the regions, but this feels like an internal event being mixed with events that can be tied to user interactions. If breaking this up/changing this makes sense I'd be happy to help out with that, just let me know.

### Wavesurfer.js version(s):

- 5.2.0

### Browser and operating system version(s):

- OS: macOS Monterey 12.0.1
- Browser: 
  - edge 95.0.1020.44 
  - chrome 95.0.4638.69 
  - safari 15.1

### Code needed to reproduce the issue:

Tried to setup an [example](https://codepen.io/n0mn0m/pen/XWaPorZ?editors=1010) in codepen, but running into some audio loading errors, hopefully this provides an idea, and it should be able to run locally with an audio file.

### Use behaviour needed to reproduce the issue:

Trigger an event where wavesurfer is destroyed with the region plugin registered and observe the region plugin emit a 'region-removed' event.

**Comment by thijstriemstra** [comment]
> I wanted to get the maintainers thoughts to see if it makes sense to change the plugin destroy and clear functions work so that clear doesn't emit a region-removed event (because it calls remove). Instead it would do the same operations, but emit a regions-destroyed or other event. 

Makes sense to me. Please open a pull request with your suggestions so it can be reviewed.
