### ISSUE TITLE
Uncaught TypeError: this.util.withOrientation is not a function

### ISSUE THREAD

**Issue by bknill** [katspaugh/wavesurfer.js#2405]
Hi, 

Recently upgraded from 3 to 5.20 and am getting this error:

```
TypeError: this.util.withOrientation is not a function
    at Region.render
```
From
` this.element = this.util.withOrientation(this.wrapper.appendChild(document.createElement('region')), this.vertical);`

RegionPlugin is imported  as such` import RegionPlugin from 'wavesurfer.js/dist/plugin/wavesurfer.regions';`

Is there something I'm doing wrong or likely to need a clearout of node_modules and rebuild?

**Comment by bknill** [comment]
Wasn't importing the plugin properly duh

**Comment by GaborTorma** [comment]
Same error message after upgrade version 6 and use Cursor plugin. With version 5 or without Cursor plugin I have no errors.

```
wavesurfer.cursor.js:171 Uncaught TypeError: this.util.withOrientation is not a function
    at CursorPlugin._onReady (wavesurfer.cursor.js:171:1)
    at WaveSurfer.<anonymous> (wavesurfer.cursor.js:235:1)
    at fn (wavesurfer.js:3361:1)
    at wavesurfer.js:3391:1
    at Array.forEach (<anonymous>)
    at WaveSurfer.fireEvent (wavesurfer.js:3390:1)
    at WaveSurfer.loadDecodedBuffer (wavesurfer.js:4942:1)
    at wavesurfer.js:4924:1
    at wavesurfer.js:5151:1
    at OfflineAudioContext.<anonymous> (wavesurfer.js:5821:1)
```
