### ISSUE TITLE
Add audome to list of commercial projects :)

### ISSUE THREAD

**Issue by Reached** [katspaugh/wavesurfer.js#2416]
Hi guys!

We are using Wavesurfer for our web-application Audome which helps audio engineers deliver their projects to their clients and get precise feedback in the form of comments on the waveform.

https://audome.com and https://app.audome.com

If you want to see a demo, check it out here: https://app.audome.com/handovers/4e6aa5d0-21c3-11ec-a51e-f90265710dd2?signature=a1a98a2e5c7f65a3d9ac02dbaee12a6ce949d88b59e1babbd9dfb4b5e2634a63

Btw, Wavesurfer is awesome!

**Comment by thijstriemstra** [comment]
Please add it to https://github.com/katspaugh/wavesurfer.js/blob/gh-pages/projects/index.html

**Comment by Reached** [comment]
@thijstriemstra done :)

https://github.com/katspaugh/wavesurfer.js/pull/2419
