### ISSUE TITLE
thicker lines in the waveform

### ISSUE THREAD

**Issue by ghost** [katspaugh/wavesurfer.js#242]
Is it possible to generate thicker lines like this picture? 
![wave](https://cloud.githubusercontent.com/assets/6660495/4194199/bab7ef44-37aa-11e4-84f0-76cd93e8fb32.png)

**Comment by glebcha** [comment]
This code looks outdated. Can anyone provide working snippet or jsfiddle/plunkr/pastebin demo?

**Comment by audiosync** [comment]
Hi ghost, that looks extremely nice! Thanks for sharing!

Unfortunately I didn't make it work...
I just exchanged drawwave function in current build of drawer.canvas.js, but it just produced a block.
And when using Sebastien's code, I am just getting a straight line:


![block](https://cloud.githubusercontent.com/assets/11797429/7670264/c3944a14-fc9d-11e4-93d6-56a56c5496ba.png)
![line](https://cloud.githubusercontent.com/assets/11797429/7670270/fb64903e-fc9d-11e4-85e0-d56c9592b04c.png)

**Comment by katspaugh** [comment]
Implemented as the `barWidth` parameter.
