### ISSUE TITLE
Do you develop this project using the configuration described on http://wavesurfer-js.org/blog/emacs-javascript.html?

### ISSUE THREAD

**Issue by hongyi-zhao** [katspaugh/wavesurfer.js#2422]
I noticed the wonderful blog written by you [here](http://wavesurfer-js.org/blog/emacs-javascript.html). Now, I also want to use Emacs as an IDE for JavaScript development. So I want to know if you develop this project using the configuration described in the above blog. BTW, see [here](https://www.draketo.de/software/emacs-javascript.html) for a similar guidance.
 
Regards,
HZ

**Comment by thijstriemstra** [comment]
ping @katspaugh

**Comment by katspaugh** [comment]
Thanks @hongyi-zhao!

That article is quite old (2015ish?). I haven't used js2-mode in a while.

You should check out [Tide](https://github.com/ananthakumaran/tide). It works for both TypeScript and JavaScript. In JS, types are inferred.

**Comment by hongyi-zhao** [comment]
But it seems that both [js2-mode](https://github.com/mooz/js2-mode) and [tide](https://github.com/ananthakumaran/tide) are actively developed and maintained. And [tide](https://github.com/ananthakumaran/tide) looks to have more powerful abilities.
