### ISSUE TITLE
Install regions plugin from NPM

### ISSUE THREAD

**Issue by kross-italk** [katspaugh/wavesurfer.js#2427]
How do I install the regions plugin from NPM? The Plugins documentation only provides an example using unpkg which is not suitable. https://wavesurfer-js.org/plugins/

This issue seems to cover my request but it doesn't have any resolution. https://github.com/katspaugh/wavesurfer.js/issues/1077
How do I install the regions plugin from NPM? It's not in `node_modules/wavesurfer.js/dist/` as that issue suggests.

**Comment by thijstriemstra** [comment]
you can `npm install wavesurfer.js` and it will show up in `node_modules/wavesurfer.js/dist/plugins/`

**Comment by thijstriemstra** [comment]
@dhdaines see https://github.com/katspaugh/wavesurfer.js/blob/master/src/plugin/spectrogram/index.js#L42

If you think the docs should be updated, please open a pull request, thanks.
