### ISSUE TITLE
active playing audio file at the top of scrolling div

### ISSUE THREAD

**Issue by fr150-nl** [katspaugh/wavesurfer.js#2430]
Hi,

Thank you so much for introducing waveurfer.js to the world. Really great stuff!

Actually this is more like an enhancement request.

The situation is that i have a playlist that resides within a scrolling DIV.
I'm trying to get the active playing audiofile appear on the top of the list.
Any possible combination of .scrollTo seems totally ineffective.
Even hardcoded within wavesurver.init.js using fixed values doesn't seem to work at my end.

It would be greatly appreciated is such a feature would become available in an upcoming version.

Many thanks in advance for considering!

Best regards,
Eddy

Wavesurfer.js version: 5.2.0
Browser and operating system version: Chrome Version 97.0.4692.71 (Official build) (64-bits) / Windows 10

**Comment by thijstriemstra** [comment]
what code exactly needs to be improved?

**Comment by fr150-nl** [comment]
Hi Thijs,

Thank you so much for replying. Actually I have finally got it to work correctly. (Whilst not being an expert on javascript and jquery.)  Take a look at the website [http://www.frizo.nl/](http://www.frizo.nl/)
Whenever a user clicks on a song the javascript function show_mp3_info() called.
And in wavesurver.init.js whenever setCurrentSong() is called i also call show_mp3_info().
Not an elegant solution, and most likely somewhat redundant but it works.
So at this I withdraw my enhancement request.

Keep up the good work...!
