### ISSUE TITLE
Pre-rendered Peaks Don't Work for Bars Rendering on 6.0.0

### ISSUE THREAD

**Issue by dtcooper** [katspaugh/wavesurfer.js#2439]
### Code needed to reproduce the issue:

The following below **works** on Wavesurfer.js version 5.2.0 but *not* on 6.0.0,

```javascript
let wavesurfer = WaveSurfer.create({
  container: '#wavesurfer,
  backend: 'MediaElement',
  barWidth: 5 // Works when this is omitted, so applies only to bar rendering
})

wavesurfer.load('https://example.com/audio.mp3', arrayOfPeaks)
```

### Use behaviour needed to reproduce the issue:

Observe peaks aren't pre-rendering, and bar rendering is empty/flat/silent. If i omit the `barWidth: 5` option, it works as usual with normal a waveform rendering.

Thanks,

David

**Comment by qadeerabbas49** [comment]
I'm facing an issue with wavesurfer.js 5.2. Whenever I try to load and play the song the internet download manager starts it downloading and the song doesn't load.  What could be the issue?
here is the code:

```
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Player</title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
	<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"/>
</head>
<body>

<div class="container mt-5">
    <div class="row border mt-5">
        <div id="pageDiv"></div>
    </div>
</div>




	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
	<script src="https://unpkg.com/wavesurfer.js@5.2.0/dist/wavesurfer.js"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<script type="text/javascript">
			const wavesurfer1 = WaveSurfer.create({
    					container: "#pageDiv"
		});

				wavesurfer1.load("songs/song1.mp3");

				wavesurfer1.on('load', function(){
					wavesurfer1.play();
				});
	</script>
</body>
</html>
```

**Comment by thijstriemstra** [comment]
> I'm facing an issue with wavesurfer.js 5.2. Whenever I try to load and play the song the internet download manager starts it downloading and the song doesn't load. What could be the issue?

Please open a new ticket and don't hijack unrelated tickets.

**Comment by thijstriemstra** [comment]
@dtcooper this is likely related to the change made by @lorenzos in #2428

**Comment by lorenzos** [comment]
I'll look into it.

**Comment by dtcooper** [comment]
> I'll look into it.

Cheers and thanks

**Comment by lorenzos** [comment]
@dtcooper I tried your code with bars on both 5.2.0 and 6.0.0, without peaks, with peaks, and with positive-only peaks, and it always worked. Could it be something related to your specific `arrayOfPeaks`?

Let me know if you can provide an actual example, with the actual array of peaks. Thanks.

**Comment by dtcooper** [comment]
Okay, thanks for taking a look. I'll come up with a very specific steps to repro tomorrow and post it.

**Comment by dtcooper** [comment]
Hi @lorenzos, below is a repro hosted on CodePen! Thanks.

Here is a repro with WaveSurfer v6.0.0: [CodePen bGYWpOO is **not working**](https://codepen.io/dtcooper/pen/bGYWpOO?editors=1000)

Here is the same code working with WaveSurfer v5.2.0: [CodePen ZEaKWZG is working on older version](https://codepen.io/dtcooper/pen/ZEaKWZG?editors=1000)

Note each CodePen has the FULL html that you can copy to test as a local file, it's not broken up into JS/HTML/CSS.

**Comment by lorenzos** [comment]
@dtcooper I fixed it in #2446. As you can read there, your issue was caused by a regression introduced by me, which occurs only when the given array of peaks alternates negative/positive values (as yours), instead of alternating positive/negative values (as the ones normally produced by wavesurfer itself).

You can test it using my build from here: `https://github.com/lorenzos/wavesurfer.js/releases/download/6.0.0-fix-2439/wavesurfer.js`

**Comment by dtcooper** [comment]
Excellent! Thank you for looking into this, @lorenzos... however, with the fix, the waveform looks really off (very max'd out, with very high peaks).

Using the above fix version, check it out: [CodePen `yLPbZbG` with v6.0.0 + fix](https://codepen.io/dtcooper/pen/yLPbZbG?editors=1000) vs [CodePen `ZEaKWZG` with v5.2.0 has much more varied bars](https://codepen.io/dtcooper/pen/ZEaKWZG?editors=1000).

**Comment by lorenzos** [comment]
@dtcooper I know, the way the bars render has changed in 6.0.0, and your very long audio file really takes that change to extremes. But the fact is, the old rendering method was producing, IMHO, a very arbitrarily shape.

You can find details about that change and examples on #2428.

In fact, if you think about that, there was absolutely no good reason for your file to render the way it did before: an irregular waveform shape, with peaks and valleys that didn't reflect actual changes in the amplitude of the signal. Think about it that way: your file is very long, and each single bar represents a very long speech segment, in which the average audio amplitude stays constant.

As for the "max'd out" looks, yeah, the new rendering method uses the maximum peak value for every audio segment that each bar represent. The avarage value could be used, but it won't change much: in your cause you'll get shorter bars, but their height will be as much "constant" as it is now.

**Comment by lorenzos** [comment]
@dtcooper I don't know `audiowaveform`, I use [`wavesurfer` own `exportPCM`](https://wavesurfer-js.org/docs/methods.html) to generate the peaks array, so, I can't say... That fact is, a "more varied" and "visually appealing" waveform is a bad representation of what your audio file is...

I don't know what's the maintainers opinion on that, if we should roll back or provide an option to get the old rendering method back (I could make a PR if so), that's their decision.

**Comment by dtcooper** [comment]
Okay. I'll make do and experiment with arguments to `audiowaveform` and see if I come up with anything! Regardless, I appreciate the fix. 😸

**Comment by dtcooper** [comment]
> Can you add some screenshots here of that difference?

Really gnarly looking waveforms with the update and fix (6.0.1), but for posterity here's the difference @thijstriemstra (CC: @lorenzos)

Before (version 5.2.0):
<img width="1015" alt="image" src="https://user-images.githubusercontent.com/873944/153813811-ca493626-77d2-47da-864b-84c6572f2f9b.png">

After (version 6.0.1):
<img width="1038" alt="image" src="https://user-images.githubusercontent.com/873944/153813704-eff5e9ad-109d-45c9-8a2c-c12e2ed1e8b2.png">

**Comment by lorenzos** [comment]
@dtcooper Adding an option for the old method is a decision that is not up to me. If mainteiners are ok with it, I can implement that. In the meantime, you can use one of the following builds, I compiled them on top of latest version (6.0.2) but with my change reverted to pre-6.0.0:

```
https://github.com/lorenzos/wavesurfer.js/releases/download/6.0.2-revert-2428/wavesurfer.js
https://github.com/lorenzos/wavesurfer.js/releases/download/6.0.2-revert-2428/wavesurfer.min.js
```

**Comment by thijstriemstra** [comment]
> Adding an option for the old method

Or adding an option for the new method?

**Comment by lorenzos** [comment]
@thijstriemstra As you and @katspaugh prefer, really. When submitting the PR, I proposed the new method as a fix, and honestly didn't though of having it as an option, since the old one is in fact a random visualization (as I thoroughly explained). Now I understand that the change can be quite radical in some cases, so yes, whatever you like.

**Comment by thijstriemstra** [comment]
> I proposed the new method as a fix, and honestly didn't though of having it as an option, since the old one is in fact a random visualization (as I thoroughly explained). 

Agreed. @dtcooper can you also add a screenshot of the waveform without bars option, preferably for old and new wavesurfer.js versions?
