### ISSUE TITLE
Some of the Cursor plugin's options are typed incorrectly

### ISSUE THREAD

**Issue by nicholasrq** [katspaugh/wavesurfer.js#2459]
Currently (according to [the official docs](https://wavesurfer-js.org/api/typedef/index.html)) `followCursorY` and `opacity` are typed incorrectly/confusingly.

Environment:
- wavesurfer.js: 6.0.1
- @types/wavesurfer.js: 6.0.0
- Browser: Safari 15.4
- OS: macOS Catalina
- TypeScript: 4.5.5

The code below gives two TS errors.

```
plugins: [
  CursorPlugin.create({
    color: "#000",
    showTime: true,
    followCursorY: true,
    opacity: 1,
  }),
]
```

For `followCursorY` (must be `boolean |  undefined`):

```
Type 'true' is not assignable to type 'string | false | undefined'.
[cursor.d.ts(54, 5): ]()The expected type comes from property 'followCursorY' which is declared here on type 'CursorPluginParams'
```

For `opacity`  (must be `number |  undefined`):

```
Type 'number' is not assignable to type 'string | undefined'.
[cursor.d.ts(37, 5): ]()The expected type comes from property 'opacity' which is declared here on type 'CursorPluginParams'
```

### Use behaviour needed to reproduce the issue:

Just try initializing the plugin with typescript.

**Comment by thijstriemstra** [comment]
thanks for the report @nicholasrq Can you make a pull request for these fixes?

**Comment by thijstriemstra** [comment]
It's also possible to specify percentage opacity values (in most browsers) or string opacity values like "inherit". See https://developer.mozilla.org/en-US/docs/Web/CSS/opacity
