### ISSUE TITLE
[QUESTION]: how does ignoreSilentMode work?

### ISSUE THREAD

**Issue by pascbeck** [katspaugh/wavesurfer.js#2461]
- [x] I have checked [the FAQ](https://wavesurfer-js.org/faq/) and it doesn't solve my problem.
- [x] I have checked [the documentation](https://wavesurfer-js.org/docs/) and it doesn't solve my problem
- [x] I have searched for [already open issues](https://github.com/katspaugh/wavesurfer.js/issues) which desribe my problem.
- [x] The issue I'm having is related to and caused by wavesurfer.js, not by other software (which maybe packages and uses wavesurfer incorrectly) – In that case you should open the issue on the respective project pages.

### Code needed to reproduce the issue:

    this.wave.instance = WaveSurfer.create({
      container: document.querySelector(`#wave-${this.message.uuid}`),
      backend: 'WebAudio',
      ignoreSilenceMode: true,
      ...this.wave.options
    })

### Question: There does not seem to be an example regarding this exact problem, and my question is basically if my code is wrong. I am trying to play a m4a file while the muted toggle is switched on.

![image](https://user-images.githubusercontent.com/55634271/155303661-7146f326-8448-40c7-b928-b538eee9d8da.png)

**Comment by thijstriemstra** [comment]
> how does ignoreSilentMode work?

take a look at the discussion in the pull request: #2176

**Comment by pascbeck** [comment]
Hey, thanks for the response, problem is I have already tried the things talked about in the thread. Also I have tried to unmute the context via unmutejs and it doesent work somehow. Guess I keep experimenting till it works 🤷.

**Comment by zaptrem** [comment]
@pascbeck What was the fix?
![image](https://github.com/katspaugh/wavesurfer.js/assets/1612230/a81a93b7-edd4-4501-8c40-e2d202069a02)
