### ISSUE TITLE
Percentage of track played

### ISSUE THREAD

**Issue by antonellogatto** [katspaugh/wavesurfer.js#2472]
Is there any way to get a percentage of how much track has been actually played?
If there's nothing similar built-in, do you have a hint on how I can reproduce this measure please?
Thanks

**Comment by thijstriemstra** [comment]
```js
const duration = wavesurfer.getDuration();
const currentTime = wavesurfer.getCurrentTime();
const percentage = (duration / 100) * currentTime;
console.log("Progress: " + percentage + "%");
```

**Comment by thijstriemstra** [comment]
> Not answering what I needed.

Uh. Not clear from your description at all. Glad you got it sorted out.
