### ISSUE TITLE
documentation of `audioprocess` event needs improvement

### ISSUE THREAD

**Issue by othmar52** [katspaugh/wavesurfer.js#2475]
related to [issue #618](https://github.com/katspaugh/wavesurfer.js/issues/618)  

The [documentation](https://wavesurfer-js.org/docs/events.html) reads:  
 - `audioprocess` – Fires continuously as the audio plays. **Also fires on seeking.**  

`Also fires on seeking` is not true when audio is paused  
 
### Wavesurfer.js version:
wavesurfer.js 6.0.2

### Code needed to reproduce the issue:
open https://wavesurfer-js.org/example/minimap/index.html  
open js console and add those 2 lines  
```js
window.wavesurfer.on('audioprocess', (sec) => { console.log('audioprocess', sec); });
window.wavesurfer.on('seek', (value) => { console.log('seek', value); });
```
check console output when seeking during play  
check console output when seeking during pause  `<-- audioprocess event is not fired`  

@thijstriemstra do you think its better to add a note to the documentation like   
`...Also fires on seeking as long as the audio is not paused`  

or does it make sense to fire a single `audioprocess` event after seeking?  
or should the hint `Also fires on seeking` be removed?  
or do you think documentation of the `audioprocess` event is perfect and there is no need to change anything at all?

**Comment by thijstriemstra** [comment]
> should the hint Also fires on seeking be removed?

I would do this first/for now.
