### ISSUE TITLE
minimap plugin: clear minimap when loading a new track

### ISSUE THREAD

**Issue by othmar52** [katspaugh/wavesurfer.js#2479]
maybe related to [issue #617](https://github.com/katspaugh/wavesurfer.js/issues/617)  
### Wavesurfer.js version(s):
wavesurfer.js 6.0.2

### Code needed to reproduce the issue:
open https://wavesurfer-js.org/example/minimap/index.html
open js console and add this line
```js
window.wavesurfer.load('https://ia804502.us.archive.org/13/items/DontWatchTheDJ128BPMDry/Don%27t%20Watch%20The%20DJ%20128BPM%20Dry.mp3');
```
check minimap during load `<-- minimap of previous track still visible until load+analyzing is finished`  

Shouldn't the minimap be cleared automatically when loading a new track?  
or is it necessary to `destroy()` and `initPlugin('minimap')` manually?

**Comment by thijstriemstra** [comment]
> or is it necessary to destroy() and initPlugin('minimap') manually?

Think so.
