### ISSUE TITLE
Many calls to setSinkId results in no sound

### ISSUE THREAD

**Issue by kross-italk** [katspaugh/wavesurfer.js#2481]
- [X] I have searched for [already open issues](https://github.com/katspaugh/wavesurfer.js/issues) which desribe my problem.
https://github.com/katspaugh/wavesurfer.js/issues/2060
- [X] The issue I'm having is related to and caused by wavesurfer.js, not by other software (which maybe packages and uses wavesurfer incorrectly) – In that case you should open the issue on the respective project pages.

### Wavesurfer.js version(s):
Version: 5.2.0

### Browser and operating system version(s):
Browser: Chrome/latest Version 99.0.4844.51 (Official Build) (64-bit)

### Code needed to reproduce the issue:
https://jsfiddle.net/m57h3qcg/4/
1. Run wavesurfer.setSinkId lots of times in any tab
2. After 50+ attempts, new Audio within that tab will stop being heard
3. After 500+ attempts, Browser is now exhausted of audio nodes 
4. Go to YouTube and try to play any video. 
5. You will see Loading, then a play button. Click play and you will see "Audio rendering error"

### Use behaviour needed to reproduce the issue:
We call setSinkId inside a React componentDidMount. If a user saves audio settings and navigates between different players they will eventually run out of audio nodes. 

Here is the code: https://github.com/katspaugh/wavesurfer.js/blob/19afccbe8cde790986989105d99f5935c8088f03/src/webaudio.js#L301

You can see that invoking `setSinkId()` will always create a new Audio node. I suggest moving this audio node to be a member of the enclosing class. Happy to submit a PR.

**Comment by thijstriemstra** [comment]
> Happy to submit a PR.

Sounds good!
