### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'clientWidth')

### ISSUE THREAD

**Issue by milton-producercloud** [katspaugh/wavesurfer.js#2498]
### Wavesurfer.js version(s):
6.1

### Browser and operating system version(s):
All

### Code needed to reproduce the issue:

Hi! Thanks for this great library. One comment: 
When, using react, I set the "responsive" param to true (or any number, **including ZERO**) if I have a hook that gets the screen resolution and I do this:

`	
        if (!isLgAndAbove) {
		return (<WaveSurfer />)
        } else {
       return (<OtherStuff />) 
}
 `

I get an error, because the function doesn't check if the element exists. This should be changed on line 4149 of the /dist version of wavesurfer.js
Instead of 
`      if (prevWidth != _this.drawer.wrapper.clientWidth && !_this.params.scrollParent) {
`

it should be something like 
    `  if (_this.drawer.wrapper && prevWidth != _this.drawer.wrapper.clientWidth && !_this.params.scrollParent) {`

**Comment by uncvrd** [comment]
Tracking, as I literally just ran in to this as well when trying to hide the waveform on mobile with responsive set to `true`!
