### ISSUE TITLE
There is a typo in your NFT.

### ISSUE THREAD

**Issue by nilq** [katspaugh/wavesurfer.js#2500]
The name of the project has been misspelled in the (at the time of writing) $3,079.27 NFT you have up for sale on OpenSea. If this is not a modern art statement, this might be worth fixing.

"The very first commit that started wavesufer.js"

---

I propose changing this to:

"The very first commit that started wavesurfer.js"

**Comment by thijstriemstra** [comment]
it's already been fixed on the master branch, thanks for reporting though.

**Comment by thijstriemstra** [comment]
oh but if there are any typos on the opensea page, @katspaugh would need to take a look at that.

**Comment by nilq** [comment]
> oh but if there are any typos on the opensea page, @katspaugh would need to take a look at that.

There is.

**Comment by katspaugh** [comment]
Oh, dang. That's in the NFT itself, it cannot be changed now.

There's a new project though, https://www.gitpoap.io/, which I'd like to try once they approve us. We can replace the NFT with that then.

Thanks @nilq!
