### ISSUE TITLE
safari FFMPEG Encoding issue

### ISSUE THREAD

**Issue by theswerd** [katspaugh/wavesurfer.js#2504]
### Wavesurfer.js version(s):
6.1.0

### Browser and operating system version(s):

Safari Version 15.0 (17612.1.28.5)
MacOS 12.0 Beta (21A5506j)
Version 100.0.4896.127 (Official Build) (arm64)

### Code needed to reproduce the issue:

```js
ffmpeg().input(stream.Readable.from(src)).duration(15).outputFormat('wav').audioFrequency(44100).audioBitrate('128k').noVideo()
```

### Use behaviour needed to reproduce the issue:
When I encode files, they work in wavesurfer **chrome**, but not on **safari**. This may be a me issue, as I'm pretty new to FFMPEG, but I think it could be a wavesurfer bug as its a different behavior on different browsers.

To take a look at whats going on, see [here](https://www.backyard.events/demos/surfing)

**Comment by thijstriemstra** [comment]
This is not a wavesurfer.js issue.
