### ISSUE TITLE
Wave Surfer not working on MP3

### ISSUE THREAD

**Issue by theswerd** [katspaugh/wavesurfer.js#2505]
### Wavesurfer.js version(s):
6.1.0

### Browser and operating system version(s):

Safari Version 15.0 (17612.1.28.5)
MacOS 12.0 Beta (21A5506j)

Wave surfer doesn't render at all when used on this [MP3](https://backyard-test-api-photos.backyard.events/eventAudios/488c82ed-e72f-49fd-894d-8bea151c36ae.mp3
)

I have already checked, this is not a CORS issue. If you'd like to test with this, I have enabled cors from any origin for this file.

This is only an issue on Safari, however other MP3s do work on Safari, which is why I'm confused.

**Comment by Reached** [comment]
There seems to be issues with Safari (15.4), which seems to break Wavesurfer :/ 

I have no idea what's causing it though, because it seems like the examples on the demo site are working just fine..

**Comment by thijstriemstra** [comment]
> because it seems like the examples on the demo site are working just fine..

Yea, I don't see an issue with Safari 15.4.

**Comment by thijstriemstra** [comment]
> Wave surfer doesn't render at all when used on this [MP3](https://backyard-test-api-photos.backyard.events/eventAudios/488c82ed-e72f-49fd-894d-8bea151c36ae.mp3)

Can you run `ffprobe` (part of ffmpeg) on the file and paste the output here?

**Comment by thijstriemstra** [comment]
no feedback, closing.
