### ISSUE TITLE
[Question] Lower audio quality for mobile phone

### ISSUE THREAD

**Issue by randal923** [katspaugh/wavesurfer.js#2511]
Hi there, I am using wavesurfer just to display the waveform and fill it out while the song plays. I am actually setting it mute when it start playing because the song is playing in another audio component, not the wavesurfer component and I have not found a good way to integrate them, so I actually mute the wavesurfer song. The issue with this is that it loads 2 files at the same time, and I don't need wavesurfer to actually play the song in good quality, it can be the lowest quality possible because it is muted anyawys. Is there a way to do that?

**Comment by thijstriemstra** [comment]
can you describe the problem with some minimal code, what you have tried etc

**Comment by thijstriemstra** [comment]
no feedback, closing.
