### ISSUE TITLE
waveform not being displayed dependant on video

### ISSUE THREAD

**Issue by esukmonica** [katspaugh/wavesurfer.js#2520]
### Wavesurfer.js version(s):
 wavesurfer.js 6.2.0 (2022-05-16)

### Browser and operating system version(s):
Chrome Version 101.0.4951.67 (Official Build) (64-bit)
Windows 10 

### Code needed to reproduce the issue:

I have attached [wavesurfer_not_working.zip](https://github.com/katspaugh/wavesurfer.js/files/8772296/wavesurfer_not_working.zip)
which contains a very simple html file that displays the problem

### Use behaviour needed to reproduce the issue:

Open the html file and you will see that the video plays, but the waveform is not visible. 
![wavesurfer_waveform_NOT_being_display](https://user-images.githubusercontent.com/63296463/170295707-e63e6dab-6f37-4e3e-a799-844542db2f19.PNG)

Would be great if someone could point me in the right direction

Thanks

**Comment by thijstriemstra** [comment]
no feedback, closing.
