### ISSUE TITLE
barMinHeight does not behave as expected

### ISSUE THREAD

**Issue by drinking-code** [katspaugh/wavesurfer.js#2522]
As far as I understand `barMinHeight` should set the absolute minimum bar height, i.e. no bar should have a height that is smaller than specified in the `barMinHeight` option. However, currently only absolute silence is getting raised to the `barMinHeight` value. That means if for example `barMinHeight` is 4 and the peak for a certain bar is 2 this bar is rendered with a height of 2px, but should be rendered with a height of 4px.

That means a waveform with near silence (for the config see below) is expected to look like this:
<img width="448" alt="Bildschirmfoto 2022-05-29 um 16 29 19" src="https://user-images.githubusercontent.com/58665953/170874458-7b999118-33c5-4e08-bec6-918d733fdbbb.png">

But with the current logic looks like this:
<img width="433" alt="Bildschirmfoto 2022-05-29 um 16 29 35" src="https://user-images.githubusercontent.com/58665953/170874498-8f3db0e9-82f9-40c4-9f63-8ddb84d67453.png">

This is due to these lines in the MultiCanvas renderer. https://github.com/katspaugh/wavesurfer.js/blob/0edd6724b89165ea73c1d589d8f635d874a5ee9c/src/drawer.multicanvas.js#L328-L330
It checks if the calculated height is 0 and raises the height to `barMinHeight` if so, but leaves values between 0 and `barMinHeight` untouched.
I suggest using this instead:
```javascript
if (this.params.barMinHeight) { 
    h = Math.max(h, this.params.barMinHeight);
}
```
Which would clip the bar height to `barMinHeight` like you see in the first image.

**Wavesurfer.js version(s)**: 6.2.0 (and below)
**Browser and operating system version(s)**: Tested on Safari 15.5 on macOS 12.4, but applicable to all browsers

### Code needed to reproduce the issue:
Any wavesurfer setup where there is silence in the loaded audio and `barMinHeight` is greater than 1.
The configuration for the examples:
```javascript
WaveSurfer.create({
    waveColor: '#B1B1B1',
    progressColor: '#B1B1B1',

    cursorColor: '#E50000',
    cursorWidth: 2,

    barWidth: 4,
    barGap: 4,
    barRadius: 5,
    barMinHeight: 4,

    height: 250,
    barHeight: 200 / 250,
    minPxPerSec: 71,
    fillParent: false,
    scrollParent: true,
    hideScrollbar: true,
})
```

**Comment by thijstriemstra** [comment]
can you check if there are any related (open) issues that would be fixed by this?

**Comment by drinking-code** [comment]
yes. I have gone through all open issues just now and couldn't find any that would be fixed
