### ISSUE TITLE
Concate multiple mp3 files into one file

### ISSUE THREAD

**Issue by JanVeb** [katspaugh/wavesurfer.js#2524]
Hello there, Is it possible to concate (join) multiple mp3 files, so that for example, if I joined 10 different mp3 and then want to have them rendered as one audio wave element on the screen and be able to play it as one element.

Thank

**Comment by DaniyarSarasenov** [comment]
I have same issue now.
I want to show the wave surface from the combined audios with Tonejs.
We can mix several file to one file and play it using ToneJS.
If anybody have some ideas, please share me. Thanks

**Comment by JanVeb** [comment]
Couldn't figure out if it could be done with wave surfer, if I remember correctly in my search they recommend to use some other library for joining multiple audio files as its not possible in wave.js

Ive used https://github.com/jaggad/crunker

Its really easy to setup and download file, but it can be replayed and more in the app as well

Also check my question about this https://github.com/jaggad/crunker/issues/76
