### ISSUE TITLE
Skeleton overlay till 'ready' fired causes waveform to not render

### ISSUE THREAD

**Issue by heresy0-0y** [katspaugh/wavesurfer.js#2527]
I want to give some sort of ui feedback to indicate that the waveform is loading, but when i try to do so with a simple skeleton, when the 'ready' event fires, the skeleton disappears to reveal the waveform container completely empty.

`<Skeleton isLoaded={!loading}>
   84             <Box>
   85             │ <div minHeight="10%" id="waveform" ref={waveform} />
   86             </Box>
   87           </Skeleton>`

**Comment by msuhov** [comment]
Hi @heresy0-0y  could you please try `waveform-ready` event? It is fired when the waveform is actually drawn

**Comment by thijstriemstra** [comment]
no feedback, closing.
