### ISSUE TITLE
regions plugin: support for drag selection for all channels

### ISSUE THREAD

**Issue by 4ntke** [katspaugh/wavesurfer.js#2529]
### Wavesurfer.js version(s):

6.2.0

### Browser and operating system version(s):

Browser: Chrome
OS: Linux, macOS

### Problem description

1. In the latest version I do not see the possibility of selecting one common region for all channels. Has this opportunity been removed? If so, is it possible to add such an option? 

Support for drag selection to be separated for each channel comes with version 6.0.0: https://github.com/katspaugh/wavesurfer.js/blob/master/CHANGES.md#600-07022022

2. Apart from that, selecting regions for separate channels, in my opinion, is unintuitive. Selecting a region for a given channel and playing a track will play audio from all channels. It seems to me that in such a situation only the audio from the selected channel should be played.

**Comment by thijstriemstra** [comment]
can you try to identify where (what commit or what PR) this functionality was removed?

**Comment by 4ntke** [comment]
> can you try to identify where (what commit or what PR) this functionality was removed?

Found that PR: https://github.com/katspaugh/wavesurfer.js/pull/2380/files

**Comment by thijstriemstra** [comment]
> Found that PR: https://github.com/katspaugh/wavesurfer.js/pull/2380/files

Ping @muhammad-sayed-mahdy

**Comment by muhammad-sayed-mahdy** [comment]
Yes, if you split channels and try to drag, it will drag on that channel only
the use case was for annotating multichannel conversation, with each person on a separate channel
We can just add another option if you want the drag selection to be for all channels

**Comment by thijstriemstra** [comment]
> We can just add another option if you want the drag selection to be for all channels

It sounds like this new option should be the default, what wavesurfer config were/are you using @4ntke?

**Comment by 4ntke** [comment]
> > We can just add another option if you want the drag selection to be for all channels
> 
> It sounds like this new option should be the default, what wavesurfer config were/are you using @4ntke?

That's my config:

```ts
{
    container: "audioElement",
    splitChannels: true,
    responsive: true,
    backend: "MediaElement",
    height: 100,
    plugins: [
       WaveSurferRegions.create({
          maxRegions: [2],
          dragSelection: true,
      }),
    ],
}
  ```

**Comment by ohperhaps** [comment]
Agreed.region play seems better to play the selecting channel,not play all channel.
