### ISSUE TITLE
Click on the waveform to return to the starting point ？

### ISSUE THREAD

**Issue by juyilu** [katspaugh/wavesurfer.js#2530]
![test2](https://user-images.githubusercontent.com/31700936/172352117-0d0c32d7-5150-4953-89ea-10d63056761b.gif)

When interacting with the waveform, click anywhere on the waveform, will the current pointer return to the starting point?

wavesurfer.js version: 6.0.2

wavesurfer.js configure :

  let wavesurfer = WaveSurfer.create({
    container: "#waveform",
    backend: "MediaElement",
    scrollParent: true,
    fillParent: true,
    waveColor:'#ADD8A6',
    backgroundColor:"#fff",
    height:198,
    cursorColor:"#478686",
    cursorWidth:"2",
    forceDecode:false,
    hideScrollbar:true,
    normalize:true,
    progressColor:"#478686",
    minPxPerSec:50,
    plugins: [
      RegionsPlugin.create({}),
      MarkersPlugin.create({})
    ]
  });

If anyone can point out the mistake, that would be really appreciated.

**Comment by thijstriemstra** [comment]
the code you provided doesn't match the gif animation you're showing, not sure how to help.

ps. you're opening a lot of tickets, calm down please.

**Comment by juyilu** [comment]
> the code you provided doesn't match the gif animation you're showing, not sure how to help.
> 
> ps. you're opening a lot of tickets, calm down please.

Sorry, it may be the audio problem on my side. This problem may be encountered by many people in the future. After merging the audio through ffmpeg, and then using the MediaElement loading method of wavesurfer, the gif will appear, (this .media.currentTime = start) allocation is always 0

![image](https://user-images.githubusercontent.com/31700936/172818734-b4c2da05-8fd4-416f-8b34-c3f002ee0ccf.png)

**Comment by gamedilong** [comment]
> > the code you provided doesn't match the gif animation you're showing, not sure how to help.
> > ps. you're opening a lot of tickets, calm down please.
> 
> Sorry, it may be the audio problem on my side. This problem may be encountered by many people in the future. After merging the audio through ffmpeg, and then using the MediaElement loading method of wavesurfer, the gif will appear, (this .media.currentTime = start) allocation is always 0
> 
> ![image](https://user-images.githubusercontent.com/31700936/172818734-b4c2da05-8fd4-416f-8b34-c3f002ee0ccf.png)

这个问题你解决了么，咋整的，官方给的demo没这个问题，一样的代码我也是一拖就回到开始。
