### ISSUE TITLE
Waveform not showing correctly. It is giving spikes.

### ISSUE THREAD

**Issue by puneety95** [katspaugh/wavesurfer.js#2533]
Hi, My waveform is not coming correct. It gives certain spikes due to some reasons. Attaching image for reference.
<img width="910" alt="image" src="https://user-images.githubusercontent.com/79069943/172430509-525c862b-4e00-4b14-b811-f4696eae4d88.png">

**Comment by thijstriemstra** [comment]
please re-read the instructions for submitting a ticket and update the necessary info.
