### ISSUE TITLE
Rendering issue in Cypress

### ISSUE THREAD

**Issue by vitalii-bulyzhyn** [katspaugh/wavesurfer.js#2534]
### Wavesurfer.js version(s): 
- 6.0.4

### Browser and operating system version(s):
- Chrome V102 and Electron v100
- Cypress 10.0.4

### The issue:
I've been writing e2e tests with Cypress and ran into the issue that the wavesurfer is not rendered properly when using Cypress. I can get element and trigger all the events with cypress, however it does not trigger events of wavesurfer

On the first screenshot it seems like it's being rendered, however if I walk through the Cypress test action - there is a blank canvas is being rendered - screenshot 2

<img width="1512" alt="Screenshot 2022-06-09 at 13 17 35" src="https://user-images.githubusercontent.com/46309116/172916793-2867a6f1-2595-45aa-9268-bb0cdceb2b01.png">

<img width="1512" alt="Screenshot 2022-06-09 at 13 17 43" src="https://user-images.githubusercontent.com/46309116/172916817-e4828418-02c7-44d5-affc-327ad3721601.png">

**Comment by thijstriemstra** [comment]
please include a code snippet that reproduces this problem.

**Comment by thijstriemstra** [comment]
no feedback, closing.
