### ISSUE TITLE
Generating Spectrogram as the rendered instead of the waveform.

### ISSUE THREAD

**Issue by puneety95** [katspaugh/wavesurfer.js#2535]
### Browser and operating system version(s): MacOS Monterey v 12.1

I dont know how to change the waveform rendered to show spectrogram instead of the waveform. Please help.

**Comment by thijstriemstra** [comment]
I'm not sure what you mean? can you add a screenshot or example code to explain the issue?

**Comment by thijstriemstra** [comment]
no feedback, closing.
