### ISSUE TITLE
Possible to generate a waveform image, using Node.js?

### ISSUE THREAD

**Issue by lukemorcom** [katspaugh/wavesurfer.js#2539]
Hi, I have been playing with wavesurfer in a React app for a project of mine, but I'd really like to explore creating an API which I can hit to generate a PNG of the waveform. Ideally I'd like to use Node.js to accomplish this.

Is it possible to use wavesurfer.js in that way, or would it be impossible due to relying on Web Audio?

Thanks in advance

**Comment by thijstriemstra** [comment]
I would use https://github.com/bbc/audiowaveform to generate images with node.js.
