### ISSUE TITLE
Frequency label display is fixed instead of absolute, which causes it to "float"

### ISSUE THREAD

**Issue by elarens** [katspaugh/wavesurfer.js#2542]
### Description
In version 6.2.0, frequency label display is fixed instead of absolute to enable consistent size on hi-dpi displays. As a result, the label "floats" as the page gets scrolled up and down

### Wavesurfer.js version(s):
6.2.0

### Browser and operating system version(s):
Chrome version Version 100.0.4896.127

### Code and behaviour needed to reproduce the issue:
See example here: https://wavesurfer-js.org/example/spectrogram/index.html
Behaves similarly in the application I am building.
<img width="709" alt="Screenshot 2022-06-30 at 3 41 17 PM" src="https://user-images.githubusercontent.com/31107130/176621846-2c52ed62-b291-4519-903f-b78f628c2f41.png">

**Comment by musicog** [comment]
I came across this in developing my own app, and have submitted a (miniscule) PR with a fix. In the meantime, you can workaround with CSS:

`spectrogram .spec-labels {
   position:absolute !important;
}`

**Comment by MartinKlimes** [comment]
I guess I figured it out. 
If you have one waveform + spectrogram, simply use:

```
wavesurfer.on('ready', function(){
     document.querySelector(".spec-labels").style.position = 'absolute'
})
```

In my case i had many waveforms and spectrograms saved into wavesurfer, so:
```
    wavesurfer[index].on('ready', function(){
        var labels = document.querySelectorAll(".spec-labels")
        labels.forEach(label => {
            label.style.position = 'absolute'
          });
    })

```
