### ISSUE TITLE
The react render does not reload after a wavesurfer event

### ISSUE THREAD

**Issue by nathanb97** [katspaugh/wavesurfer.js#2543]
I have to realize a specific behavior when the audio enters a region.
For that i use the event [region-in](https://wavesurfer-js.org/example/annotation/index.html)
After the execution of my method the render is not reloaded, while I change a state.
```javascript
useEffect(() => {
   if (wavesurferObj) {

      wavesurferObj.on('region-in', (region) => {
      setCurrentRegion(region)
      });
}, [wavesurferObj]);
```
But render is reloaded after another event saving what happened before.

**Comment by thijstriemstra** [comment]
This is a React-specific question it seems. Please ask on a React forum/stackoverflow etc as we can't help with third-party code.
