### ISSUE TITLE
Showing the wavesurface of combined audio using ToneJS

### ISSUE THREAD

**Issue by DaniyarSarasenov** [katspaugh/wavesurfer.js#2545]
Hi, everybody!
I am trying to show the wavesurface of combined audio using ToneJS.
```
new Tone.Player({ url: 1.wav }).toDestination().sync().start(0)
new Tone.Player({ url: 2.wav }).toDestination().sync().start(0)
new Tone.Player({ url: 3.wav }).toDestination().sync().start(0)
Tone.loaded().then(() => {Tone.Transport.start();});
```
Now it plays the combined audio
I wanna show the wavesurface. Help me!!!

**Comment by thijstriemstra** [comment]
hi @DaniyarSarasenov I am not familiar with ToneJS and what your example code is doing. Are you able to create a Blob with ToneJS that has the combined audio?

**Comment by thijstriemstra** [comment]
no feedback, closing.
