### ISSUE TITLE
wavesurfer.js autoplay on load

### ISSUE THREAD

**Issue by CaptainWeirdBeard** [katspaugh/wavesurfer.js#255]
I am using wavsurfer.js for a site and I have been able to get it working almost the way I want it to. I have several buttons that all load a different track into the player but I would really love to know how to make it is so the the tracks start playing automatically once loaded. for the track selection buttons I have this code that loads the track.

```
<div class="controls"><button class="btn" onclick="wavesurfer.load('wavesurfer/media/song_01.mp3');"> Play </button>
```

Any help  or ideas would be greatly appreciated as I am new to this.
Cheers

**Comment by Rayobeats** [comment]
Hi. My wavesufer autoplays wen i load a page with, i would like to stop auotoplay, how do i stop autoplay.
