### ISSUE TITLE
Minimum Value to Trigger barMinHeight

### ISSUE THREAD

**Issue by flyingatm** [katspaugh/wavesurfer.js#2550]
Hello there, thank you for the nice library!

I guess it would be better to add new option parameter to trigger "barMinHeight" instead of "0" value.

<img width="665" alt="image" src="https://user-images.githubusercontent.com/50561288/178113090-93373d06-387e-4fad-b7e6-26fff6b4ce52.png">

For an example, here in bundled version, I changed line 1344 like this. (changed "0 ==" to "5 <="). So we users can have a more stable graphic when there are a little parasites in the sound that makes bar height between 0 and 5.

Can be named as: "barMinHeightTrigger" as an integer.

**Comment by thijstriemstra** [comment]
@flyingatm does pr #2523 fix this for you?

**Comment by thijstriemstra** [comment]
no feedback, closing.
