### ISSUE TITLE
exportPCM() no longer works as expected

### ISSUE THREAD

**Issue by thespicer21** [katspaugh/wavesurfer.js#2557]
### Wavesurfer.js version(s):
6.2.0

### Browser and operating system version(s):
Firefox , Chrome, Brave (all latest of the date of this comment) / MacOS 10.14.6

### Code needed to reproduce the issue:
(in the console)
`player.exportPCM(1024, 10000, true, 0)`

On the previous version of ws.js I was using (v3.1.0), this used to return an array of plot points :

`"[0.8509,-0.862,0.5302,-0.4398,0.3528,-0.1603,0.228,-0.1364,0.87,-0.8639,0.4331,-0.3503,0.2942,-0.2951,0.1929,-0.2155,0.2661,-0.7897,0.3525,-0.434,0.0945,-0.1324,0.1568,-0.0962,0.5528,-0.2082,0.5093,-0.4377,0.1415,-0.2453,0.3446,-0.1778,0.6097,-0.604,0.4316,-0.3224,0.3661…]"`

It was easy to store these in a json file on the server. 

But on v6.2.0 it returns a promise instead, and I can't seem to access the array <value> from it.

`Promise { <state>: "fulfilled", <value>: (2048) […] }`

**Comment by thijstriemstra** [comment]
@thespicer21 try:

```js
wavesurfer.exportPCM(1024, 10000, true, 0).then(function(data) {
  console.log(data);
});
```
