### ISSUE TITLE
markers plugin: draggable feature only works if there is at least one marker in the initial markers list

### ISSUE THREAD

**Issue by mikesol** [katspaugh/wavesurfer.js#2560]
### Wavesurfer.js version(s):

6.2.0

### Browser and operating system version(s):

Chrome on macOS

### Code needed to reproduce the issue:

```javascript
const ws = WaveSurfer.create({
		container: container,
		plugins: [
			MarkersPlugin.create({
				markers: [],
			}),
	});
	ws.load(url);
	ws.addMarker({
		time: 0.2,
		label: "V1",
		color: "#ff990a",
		draggable: true,
	});
	ws.addMarker({
		time: 1.0,
		label: "V2",
		color: "#00ffcc",
		draggable: true,
	});
```

### Use behaviour needed to reproduce the issue:

Try to drag one of the markers. It won't work. However, if at least one marker is in the initial markers list, it will work.

**Comment by rstefek** [comment]
We came across same issue in our .net wrapper:
https://github.com/beaverlyhillsstudios/wavesurfer-blazor-wrapper/issues/5
