### ISSUE TITLE
Getting error Uncaught TypeError: Cannot read properties of null (reading 'remove') when I create cursor plugin instance?

### ISSUE THREAD

**Issue by jaylenpatterson** [katspaugh/wavesurfer.js#2563]
Version ^6.2.0
```js
 waveform.current = WaveSurfer.create({
       container: "#waveform",
       waveColor: "#00AFCC",
       barGap: 2,
       barWidth: 4,
       barRadius: 3,
       cursorWidth: 2,
       cursorColor: "#567FFF",
       scrollParent: true,
       // Add the regions plugin.
       // More info here https://wavesurfer-js.org/plugins/regions.html
       plugins: [
            WaveformCursorPlugin.create(),
            WaveformMarkersPlugin.create({
            container: "#wave-timeline",
                time: 6,
                label: 'Start',
                color: 'red',
            }),

           WaveformTimelinePlugin.create({
               container: "#wave-timeline",
               height:40, 
               notchPercentHeight: 70,
               primaryFontColor: "rgba(255, 255, 255, 0.1)",
               secondaryFontColor:"rgba(255, 255, 255, 0.3)",
               primaryColor: "rgba(255, 255, 255, 0.3)",
               secondaryColor: "rgba(255, 255, 255, 0.3)",
               unlabeledNotchColor: "rgba(255, 255, 255, 0.1)",
               fontSize:10,
               labelPadding:4,
               formatTimeCallback: formatTimeCallback,
               primaryLabelInterval: primaryLabelInterval,
               secondaryLabelInterval: secondaryLabelInterval
           })
   ]
   
     });

```

**Comment by jaylenpatterson** [comment]
The application renders as normal once the cursor plugin is removed

**Comment by thijstriemstra** [comment]
@jaylenpatterson can you reproduce it with any of the examples?

**Comment by jaylenpatterson** [comment]
> @jaylenpatterson can you reproduce it with any of the examples?

Do you mean the examples from wavesurfer documentation?

**Comment by thijstriemstra** [comment]
yea, live versions are available on https://wavesurfer-js.org/examples/

**Comment by jaylenpatterson** [comment]
I'm unable to get the example working as intended. Are there any solutions for react?

**Comment by thijstriemstra** [comment]
> I'm unable to get the example working as intended. 

Not sure what you mean..

There aren't any specific react examples.

**Comment by jaylenpatterson** [comment]
Is it possible to use the example in a react project? I tried using wave surfer as seen in the example but i wasn’t able to find certain variables

**Comment by thijstriemstra** [comment]
I would give https://www.npmjs.com/package/wavesurfer-react a try.

**Comment by jaylenpatterson** [comment]
Okay thank you, I will give it a try.

**Comment by jaylenpatterson** [comment]
I was able to use the plugin no problem with wavesurfer-react! Thank you so much.

**Comment by thijstriemstra** [comment]
> Cannot read properties of null (reading 'remove')

can't reproduce that with https://wavesurfer-js.org/plugins/cursor.html

**Comment by thijstriemstra** [comment]
we don't provide support for React; take a look at https://www.npmjs.com/package/wavesurfer-react instead.
