### ISSUE TITLE
Duplicated waveform

### ISSUE THREAD

**Issue by violeta-maldonado** [katspaugh/wavesurfer.js#2567]
# Issue
I have updated react to 18 version with Next js, and now the waveform is duplicated but just the below one is played. I would like you can let me know how can I solve this bug. 

### Wavesurfer.js version(s):
"wavesurfer.js": "^6.2.0",

### Browser and operating system version(s):
Brave, Chrome, Edge

### Code needed to reproduce the issue:

```
const formWaveSurferOptions = (ref) => ({
  container: ref,
  backend: 'WebAudio',
  waveColor: '#9c9c9c',
  progressColor: '#4e4e4e',
  height: 25,
  cursorWidth: 1,
  cursorColor: 'transparent',
  barWidth: 2,
  barRadius: 3,
  width: '100%',
  barGap: 4,
  normalize: true,
  responsive: true,
  autoCenter: false,
  fillParent: true,
  hideScrollbar: true,
  partialRender: true,
  closeAudioContext: true,
  xhr: {
    cache: 'default',
    mode: 'cors',
    method: 'GET',
    credentials: 'same-origin',
    headers: [
      { key: 'cache-control', value: 'no-cache' },
      { key: 'pragma', value: 'no-cache' }
    ]
  }
});
useEffect(() => {
    import('wavesurfer.js').then((m) => {
      const WaveSurfer = m.default;
      setPlay(false);
      const options = formWaveSurferOptions(waveformRef.current);
      wavesurfer.current = WaveSurfer?.create(options);

      wavesurfer.current.load(
        url
      );

      wavesurfer.current.on('ready', function () {
        // https://wavesurfer-js.org/docs/methods.html

        // make sure object stillavailable when file loaded
        if (wavesurfer.current) {
          wavesurfer.current.setVolume(1);
        }

      });
    });

    // Removes events, elements and disconnects Web Audio nodes.
    // when component unmount
    return () => { wavesurfer?.current?.destroy() }
  }, []);

```

### Use behaviour needed to reproduce the issue:
Just one waveform should appear
![image](https://user-images.githubusercontent.com/85957327/183483388-10351642-18a5-457a-b530-809581e606be.png)

**Comment by thijstriemstra** [comment]
We can't help with React specific issues. I suggest using https://www.npmjs.com/package/wavesurfer-react

**Comment by violeta-maldonado** [comment]
Fix this error by adding the following in **next.config.js**
`reactStrictMode:  false`
![image](https://user-images.githubusercontent.com/85957327/183965812-a833bcbc-d1f1-4144-b710-04b9a9efa5e8.png)

**Comment by jgentes** [comment]
Note that using strict mode just disables duplicate firing of useEffect hooks in dev mode. It hides the underlying problem, which is that your component is not properly cleaning up the wavesurfer instance in between renders.

Since useEffect mostly ensures wavesurfer only renders once, this is usually fine, but the issue remains that you should ideally cleanup properly with `wavesurfer.destroy()`.
