### ISSUE TITLE
Waveform not rendering in ubuntu & Mac, working fine in windows system.

### ISSUE THREAD

**Issue by bhagwansawant123** [katspaugh/wavesurfer.js#2569]

**Comment by thijstriemstra** [comment]
please provide code that reproduces the issue. Does https://wavesurfer-js.org render on mac/ubuntu? It does here.

**Comment by bhagwansawant123** [comment]
`playAudio(uniqueId, path) {
            console.log(path)
            let wavesurfer = WaveSurfer.create({
                container: '#waveform'+uniqueId.replace('.', ''),
                scrollParent: true,
                responsive: true,
                xhr: {
                    cache: "default",
                    mode: "opaque",
                    method: "GET",
                }
            })
            wavesurfer.load(path)
            wavesurfer.on('ready', function () {
                wavesurfer.play()
            })
        },`
Please check above code waveform not rendering

**Comment by thijstriemstra** [comment]
I can't tell; probably related to `container: '#waveform'+uniqueId.replace('.', ''),`

You didn't answer my question though: 

> Does https://wavesurfer-js.org/ render on mac/ubuntu? It does here.

**Comment by bhagwansawant123** [comment]
Yes it is rendering on your website. Actually it is cors issue, but even adding cors code its not rendering waveforms

**Comment by bhagwansawant123** [comment]
Waveforms not rendering in firefox.
![Screenshot from 2022-08-24 10-59-44](https://user-images.githubusercontent.com/91108254/186336831-cc462aa2-d27d-4ee2-8e19-28630230381a.png)
