### ISSUE TITLE
Waveform not loading when using php echo command

### ISSUE THREAD

**Issue by BlockchainBen** [katspaugh/wavesurfer.js#2576]
# Hey, thank you for testing and contributing to wavesurfer.js!

## Please make sure you can check all of these points below before opening an issue:

(You don't have to post this section)

- [x] I have checked [the FAQ](https://wavesurfer-js.org/faq/) and it doesn't solve my problem.
- [x] I have checked [the documentation](https://wavesurfer-js.org/docs/) and it doesn't solve my problem
- [x] I have searched for [already open issues](https://github.com/katspaugh/wavesurfer.js/issues) which desribe my problem.
- [x] The issue I'm having is related to and caused by wavesurfer.js, not by other software (which maybe packages and uses wavesurfer incorrectly) – In that case you should open the issue on the respective project pages.

### Wavesurfer.js version(s):
Just downloaded today

### Browser and operating system version(s):
Brave. Mac.

### Code needed to reproduce the issue:

(Please reduce your code as much as possible and only post the minimum code needed to reproduce the issue. [A Code pen](http://codepen.io/) is an excellent way to share such code)

I have a foreach loop that's pulling in data from a sql table. Right now, it's hard coded to display the waveform of 1 audio file on our server (for testing puropses). However, the waveform never loads. 

It's also inside a table. 

This section "<div class="audio"></div>" doesn't appear to be going to the main.js script. 

	echo "<td width='35%'style='text-align: center;'>"
		?>
			<div class="audio-container">
				<div class="audio"></div>
					<div class="buttons">
						<span class="play-btn btn">
							<i class="fas fa-play"></i>
							<i class="fas fa-pause"></i>
						</span>
						
						<span class="stop-btn btn">
							<i class="fas fa-stop"></i>
						</span>
						
						<span class="mute-btn btn">
							<i class="fas fa-volume-up"></i>
							<i class="fas fa-volume-mute"></i>
						</span>
						
						<input type="range" min="0" max ="1" step="0.1" value="0.5" class="volume-slider"/>
					</div>
				</div>
				

		<?php
				"</td>";

**Comment by thijstriemstra** [comment]
what waesurfer.js configuration are you using?

**Comment by BlockchainBen** [comment]
Thank you for the reply. I hired a dev that was able to figure it out. 






Ben Kopec
Epitome Music

4,500+ Exclusive Tracks:
DISCO <https://epitomemusic.disco.ac/lib/5128>
SourceAudio <https://epitomemusic.sourceaudio.com/#!albums>

323.874.4081 (office / fax)  | 203.668.7162 (mobile)
***@***.*** ***@***.***>   |   www.EpitomeMusic.com <http://www.epitomemusic.com/> 

Epitome Music provides emotionally powerful music that elevates video content to engage a larger audience.
