### ISSUE TITLE
Cursor Plugin - Uncaught TypeError: Cannot read properties of undefined (reading 'create') 

### ISSUE THREAD

**Issue by andrheapaltao** [katspaugh/wavesurfer.js#2580]
### Wavesurfer.js version(s): 
6.2.0 (2022-05-16)

### Browser and operating system version(s): 
Win 10 
- Edge Version 105.0.1343.27 (Official build) (64-bit)
- Chrome Version 105.0.5195.102 (Official Build) (64-bit)

### Code needed to reproduce the issue:
I cannot re-create the code in codepen because of the loading of external audio file. But here's the code I used:
https://codepen.io/rhea-paltao/pen/rNvLBpV
![image](https://user-images.githubusercontent.com/53431443/189492358-d16e76fb-abe7-40a5-ab68-ffbc37e66235.png)

### Use behaviour needed to reproduce the issue:
Using a pure JS project, CursorPlugin is the only one with the `Uncaught TypeError: Cannot read properties of undefined (reading 'create')` error. Wavesurfer.regions.js can be implemented without much of a problem. Only the cursor plugin. This is the file that I used for the Cursor Plugin: https://unpkg.com/wavesurfer.js@6.2.0/dist/plugin/wavesurfer.cursor.js

### Additional Info:
Please let me know if the file I used is correct or not because in the API documentation the file is not compatible with a PureJS project. I get an error:
![image](https://user-images.githubusercontent.com/53431443/189494237-55c72097-e68c-401e-9535-9fb22744971d.png)

**Comment by thijstriemstra** [comment]
> Using a pure JS project,

You didn't include any code. Can you reproduce it with any of the wavesurfer.js examples?

**Comment by andrheapaltao** [comment]
> I cannot re-create the code in codepen because of the loading of external audio file. But here's the code I used:
https://codepen.io/rhea-paltao/pen/rNvLBpV

I did include a code though. It must be because I'm using `sails.js`. They don't recognize export default class as function. Anyway, thank you for taking the time to check it.
