### ISSUE TITLE
Using wavesurfer and video - not working

### ISSUE THREAD

**Issue by jamesryan-dev** [katspaugh/wavesurfer.js#2585]
Hello,

Curious if anyone's managed to use Wavesurfer ontop of a video component?

Feels like the browser can't handle both at the same time as it simply fails to load the waveform when both are present however if the video is taken away it displays the waveform

**Comment by germancasares** [comment]
You could try to set the containerElement from the waveform, to a div that is on top of your video

**Comment by thijstriemstra** [comment]
no feedback, closing.
