### ISSUE TITLE
Suggestion for the "markers" plugin: tooltips

### ISSUE THREAD

**Issue by szarza** [katspaugh/wavesurfer.js#2589]
Wavesurfer.js version(s): 6.0.2
Browser and operating system version(s): all

First of all, congratulations on the brilliant work all of you have made.

I wanted to use the "markers" plugin but with some sort of tooltip over the labels. My skills in Javascript are very limited, and I only know "classic" Javascript. Nevertheless, it was simple for me to add a tooltip to the label and rebuild the code. I attach the diff file here as a starting point if the author wants to include or improve it.

Regards,
Samuel.

[index.diff.txt](https://github.com/katspaugh/wavesurfer.js/files/9674300/index.diff.txt)

**Comment by thijstriemstra** [comment]
@szarza this could be a nice enhancement for the markers plugin, can you open a pull request and we go from there?
