### ISSUE TITLE
How to save some parts of audio to a wav/mp3 file?

### ISSUE THREAD

**Issue by cahya-wirawan** [katspaugh/wavesurfer.js#2591]
Hi, waveform.js is a great library, I am using it for my audio annotation project. Now I want to save some parts/regions of the loaded waveform as audio file (wav, ogg or mp3), how can I do this? Or at least how can get the raw audio data behind the waveform? Thanks a lot,

**Comment by thijstriemstra** [comment]
try the `wavesurfer.exportPCM` method.

**Comment by thijstriemstra** [comment]
no feedback, closing.

**Comment by katspaugh** [comment]
@nahansans please see https://github.com/katspaugh/wavesurfer.js/discussions/2932
You can extract a portion using `.slice()` on the array.

Something like
```js
const audioData = wavesurfer.getDecodedData()
const channel = audioData.getChannelData(0)
const portion = channel.slice(5 * audioData.sampleRate, 40 * audioData.sampleRate)
```
