### ISSUE TITLE
Have different effect on waveform and minimap

### ISSUE THREAD

**Issue by YZlingyu** [katspaugh/wavesurfer.js#2593]
# Hey, thank you for testing and contributing to wavesurfer.js!

## Please make sure you can check all of these points below before opening an issue:

(You don't have to post this section)

- [x] I have checked [the FAQ](https://wavesurfer-js.org/faq/) and it doesn't solve my problem.
- [x] I have checked [the documentation](https://wavesurfer-js.org/docs/) and it doesn't solve my problem
- [x] I have searched for [already open issues](https://github.com/katspaugh/wavesurfer.js/issues) which desribe my problem.
- [x] The issue I'm having is related to and caused by wavesurfer.js, not by other software (which maybe packages and uses wavesurfer incorrectly) – In that case you should open the issue on the respective project pages.

### Wavesurfer.js version(s):
"wavesurfer": "^1.3.4",
"wavesurfer.js": "^5.2.0",

### Browser and operating system version(s):
windows

### Code needed to reproduce the issue:

(Please reduce your code as much as possible and only post the minimum code needed to reproduce the issue. [A Code pen](http://codepen.io/) is an excellent way to share such code)

### Use behaviour needed to reproduce the issue:
I used the same audio in the plugin, but the effect on waveform and minimap are different. Are they used the same decode methods? Please help to find out the reason. Thank you.
![img_v2_15edb67d-d3d6-4636-b675-b1e146b6c7dg](https://user-images.githubusercontent.com/25507025/194793917-0350751f-f756-4afd-88e9-d2887240ac88.jpg)

**Comment by thijstriemstra** [comment]
Please include the wavesurfer.js config and browser/os you tested it on.

**Comment by thijstriemstra** [comment]
no feedback, closing.
