### ISSUE TITLE
Property 'buffer' does not exist on type 'WaveSurferBackend'

### ISSUE THREAD

**Issue by jriffs** [katspaugh/wavesurfer.js#2601]
In Typescript, after using the `loadBlob` method, i try to get the buffer property,
```
const buffer = ws?.backend?.buffer
```
but it throws an error in the editor saying 

> Property 'buffer' does not exist on type 'WaveSurferBackend' 
Property 'buffer' does not exist on type 'WebAudio'

**Comment by thijstriemstra** [comment]
> In Typescript

Always provide the wavesurfer.js config and a code snippet that reproduces the problem........
