### ISSUE TITLE
cursor plugin: crash when destroy triggered before ready

### ISSUE THREAD

**Issue by SilvaQ** [katspaugh/wavesurfer.js#2602]
we don't provide support for React; take a look at https://www.npmjs.com/package/wavesurfer-react instead.

_Originally posted by @thijstriemstra in https://github.com/katspaugh/wavesurfer.js/issues/2563#issuecomment-1286889167_

**Comment by thijstriemstra** [comment]
thanks for the feedback @SilvaQ Can you make a pull request for this?
