### ISSUE TITLE
Loading Server-Side Generated Audio Url in Wavesurfer

### ISSUE THREAD

**Issue by FerhatAdibelli0** [katspaugh/wavesurfer.js#2603]
I want to add a voice recording feature to my app. I am using wavesurfer.js for this. This is a chat app so there should be more than one Wavesurfer object on a page so I gave the container a dynamic value.

I use S3 to store my files and keep every uploaded file. To be able to preview after the recording is finished, I use blobUrl first, and after uploading, I change the URL to the one on s3.

MY QUESTION IS THIS: When I use the blob URL, Wavesurfer does the loading process without any problems, but when I give the URL from the server, I can't get the same result. Just a straight line or nothing.

**Comment by thijstriemstra** [comment]
Please add your wavesurfer.js config

> MY QUESTION IS THIS: When I use the blob URL, Wavesurfer does the loading process without any problems, but when I give the URL from the server, I can't get the same result. Just a straight line or nothing.

And a code snippet for this.

**Comment by thijstriemstra** [comment]
no feedback, closing.
