### ISSUE TITLE
[question] How do I get sample bit width values from a wave file？

### ISSUE THREAD

**Issue by SilvaQ** [katspaugh/wavesurfer.js#2607]
@therewasaguy 

How do I get sample values from a wave file?

<img width="1089" alt="image" src="https://user-images.githubusercontent.com/46706370/197494354-ca97705a-488f-48eb-b94a-4db5cd7472af.png">

**Comment by thijstriemstra** [comment]
There's not a specific api for this yet, pr is welcome. You can use `wavesurfer.backend.ac.sampleRate`.

**Comment by thijstriemstra** [comment]
Oh you asked for bit width, not sample rate. There is no API for this, see https://stackoverflow.com/questions/70071519/how-to-get-sample-rate-bit-depth-and-number-of-channels-with-web-audio-api

WebAudio has been around for 10 years and I'm always amazed at how incomplete it is.

**Comment by thijstriemstra** [comment]
> extend the RIFF field and only add the metadata information to.wav for the time being, and separate the logic to provide more header structure information in the future?

Sounds good.

**Comment by thijstriemstra** [comment]
> So if we put all buffers together, just like backends, who needs what can get and use it according to their own needs. In my opinion, it is best at this stage.

It's probably easier to give feedback on a pull request. Wavesurfer.js does have performance issues with large files and as long as this change doesn't make things worse it should be ok.

**Comment by thijstriemstra** [comment]
> ** I will submit PR according to this plan**

Did this get submitted?
