### ISSUE TITLE
The waveform not displayed on loading the mp3 File

### ISSUE THREAD

**Issue by darshitr19** [katspaugh/wavesurfer.js#2610]
The library is used with latest version.

The mime type of file is 'application/octet-stream' and it's a mp3 file.

The audio is played but waveform is not loaded.

Browser: Firefox (latest version)

Audio File Link : https://www.texttovoice.online/audios/v_Z_th-TH_6360c6eb007c8.mp3

**Comment by thijstriemstra** [comment]
what is the output of `ffprobe` (part of ffmpeg) for that mp3 file?

What browsers/operating systems have you tested?

> The library is used with latest version.

What version specifically?

**Comment by thijstriemstra** [comment]
no feedback, closing.
