### ISSUE TITLE
Setting `frequencyMax` does nothing

### ISSUE THREAD

**Issue by cameronSlupeiks** [katspaugh/wavesurfer.js#2612]
### Description
This may not be a bug, could just be an issue with my implementation or understanding of this parameter. I am trying to set the max frequency of the spectrogram to 2400Hz (we do not need to display samples up to 24000Hz), but this does not work. We are using a sample rate of 48000Hz. 

### Code needed to reproduce the issue:
```
let wavesurfer: WaveSurfer | undefined;

const colorMap = colormap({
  colormap: "jet",
  nshades: 256,
  format: "float",
});

wavesurfer = WaveSurfer.create({
  container: waveformRef.current,
  waveColor: "#5278a0",
  progressColor: "#0a417a",
  barGap: 3,
  barWidth: 3,
  barRadius: 3,
  barHeight: 3,
  height: 300,
  plugins: [
    SpectrogramPlugin.create({
      wavesurfer,
      container: spectrogramRef.current,
      colorMap,
      labels: true,
      height: 300,
      frequencyMax: 2400,
    }),
  ],
});

wavesurfer.loadBlob(channelAudio);
```

<img width="677" alt="Screenshot 2022-11-03 111826" src="https://user-images.githubusercontent.com/25286794/199761173-6f909caa-cded-4699-beac-084bba5f4fa5.png">

**Comment by thijstriemstra** [comment]
Why are you not testing with the latest wavesurfer.js?
