### ISSUE TITLE
Audio keeps playing after calling `seekTo(1)`

### ISSUE THREAD

**Issue by armiiis** [katspaugh/wavesurfer.js#2619]
### Wavesurfer.js version(s):
6.4.0

### Browser and operating system version(s):
Chrome 107.0.5304.110
macOS  12.6

### Code needed to reproduce the issue:

https://codesandbox.io/s/dazzling-varahamihira-3lpn86?file=/src/_app.js

### Use behaviour needed to reproduce the issue:
I have this issue where user clicks on progress bar at the very end of it and audio is still playing for a few more seconds. **Current time starts exceeding audio duration**. This only happens with long audios. It's hard to reproduce it by clicking, so I've added button which calls `seekTo(1)`, which results in same behavior.

1. Load a long audio file (1h+ in my case)
2. Start playing audio by clicking **Play/Pause** button
3. Anytime when audio plays click **seekTo(1)** button

**Expected behavior**: audio is seeked to the end - stops playing
**Actual result**: audio current time exceeds its duration and continues playing for a few more seconds.

**Comment by entonbiba** [comment]
@armiiis I used the latest version and not able to replicate the issue. Can you provide a link to the actual audio file you are using instead, it might be the issue?

Have a look here:
https://www.entonbiba.com/lab/wavesurfer/2619.html

Config:

``` html

	<div id="wavesurfer">
  
	</div>

	<button onclick="wavesurfer.play()">Play</button>
	<button onclick="wavesurfer.pause()">Pause</button>
	<button onclick="wavesurfer.seekTo(1)">Seek to (1)</button>

    
      <div>
        <p>Progress:</p>
        <span id="current-time">0</span>
        <span>/</span>
        <span id="duration">0</span>
      </div>


```
``` javascript

    var wavesurfer = WaveSurfer.create({
	container: '#wavesurfer',
	backend: 'WebAudio',
	waveColor: '#000',
	progressColor: '#46B54D',
	forceDecode: true,
	responsive: true,
        barMinHeight: 3,
        barWidth: 10
    });
    
    var audioFile = "linktoaudiofilhere";
    wavesurfer.load(audioFile);

    wavesurfer.on("ready", () => {
        var currentTimeElement = document.getElementById("current-time");
        var duration = document.getElementById("duration");

        setInterval(() => {
          currentTimeElement.innerText = Math.floor(
            wavesurfer.getCurrentTime()
          );
        }, 500);

        duration.innerText = Math.floor(wavesurfer.getDuration());
    });



```

**Comment by armiiis** [comment]
@entonbiba Thanks for your reply. As I have mentioned before it only happens with long audio files (1h+). Example audio file could be found in [codesandbox link](https://codesandbox.io/s/dazzling-varahamihira-3lpn86?file=/src/_app.js). Have you tried using 1h+ audio file?

**Comment by entonbiba** [comment]
@armiiis the audio file there can't be downloaded can you upload it somewhere where to download it as it doesn't load in the codesandbox. I'll test that audio file, but yes I've tested with long audio files and seems to be fine.

**Comment by armiiis** [comment]
Here's the audio download link: https://file.io/uYPyUu6a7rKU
Also I think you can download codesandobx project zip: 
![image](https://user-images.githubusercontent.com/12126557/222081600-1a21c7ce-481d-4714-a39f-fd0ee81c0426.png)

**Comment by entonbiba** [comment]
just tested it here seems fine with the audio file you provided:

https://www.entonbiba.com/lab/wavesurfer/2619.html

**Comment by entonbiba** [comment]
@armiiis can you test it outside of codesandbox and confirm? Also test the link I provided above for the test result working.

**Comment by katspaugh** [comment]
I also couldn't reproduce the bug in the codesandbox, it always jumps to 4225. But theoretically it's plausible that some rounding error might accumulate over time, especially for long files, and result in this behavior.

@armiiis does it actually continue playing, as in with the sound coming out, or just moves the cursor on the waveform?
Could you record a video maybe?

**Comment by armiiis** [comment]
@entonbiba I've tried using configuration you provided. Issue is gone when using `backend: 'WebAudio'`. I've also tried running it locally. Having same issues when using `backend: "MediaElement"`. 
I tried playing multiple different 1h+ long audios and none of them had this issue. So I can't reproduce it always. Don't know what is so specific to this exact audio file.

@katspaugh Audio I'm testing is really quite at the end, but I think sound is coming out. 

https://user-images.githubusercontent.com/12126557/227454169-9a8b2d8d-c8cf-42ef-943d-26a65f83c0ac.mov

**Comment by katspaugh** [comment]
There's a similar issue – #2738
There we thought it might be a problem with the rendering (wrong width), but since you're programmatically setting the position and still have issues, it might actually be MediaElement-related.

Could you test the same files with the new alpha version? https://github.com/katspaugh/wavesurfer.ts

**Comment by katspaugh** [comment]
@armiiis any luck with the alpha version?
