### ISSUE TITLE
Feature request, or: add fade-in before the audio / fade-out affter the audio

### ISSUE THREAD

**Issue by sangtv123** [katspaugh/wavesurfer.js#2621]
# Hey, thank you for testing and contributing to wavesurfer.js!

## Please make sure you can check all of these points below before opening an issue:

(You don't have to post this section)

- [x] I have checked [the FAQ](https://wavesurfer-js.org/faq/) and it doesn't solve my problem.
- [x] I have checked [the documentation](https://wavesurfer-js.org/docs/) and it doesn't solve my problem
- [x] I have searched for [already open issues](https://github.com/katspaugh/wavesurfer.js/issues) which desribe my problem.
- [x] The issue I'm having is related to and caused by wavesurfer.js, not by other software (which maybe packages and uses wavesurfer incorrectly) – In that case you should open the issue on the respective project pages.

### Code needed to reproduce the issue:

(Please reduce your code as much as possible and only post the minimum code needed to reproduce the issue. [A Code pen](http://codepen.io/) is an excellent way to share such code)

**Comment by daslicht** [comment]
I solved it manually but just setting teh volume 2 0 before playback and then just fade it in via js

**Comment by entonbiba** [comment]
@quynhanhsang you can do this two ways, one using `requestAnimationFrame`. I'll see if I can add this as a option to the library soon for fade in and fade out effects.

```js
var start = 0;

function fadeIn(time) {
    if (!start){
        start = time;
    }
    var progress = time - start;
    wavesurfer.setVolume(progress / 5000);
    if (progress < 5000) {
        window.requestAnimationFrame(fadeIn);
    }        
}
 
wavesurfer.on('waveform-ready', function () {
    wavesurfer.setVolume(0);
});

wavesurfer.on('play', function () {
    window.requestAnimationFrame(fadeIn);
});

wavesurfer.on('finish', function () {
    start = 0;
});
```
