### ISSUE TITLE
Add sponsors option

### ISSUE THREAD

**Issue by thijstriemstra** [katspaugh/wavesurfer.js#2622]
Github provides support for sponsoring projects: https://github.com/sponsors

cc @katspaugh

**Comment by katspaugh** [comment]
I know, I had registered us there before and some random medical company even sponsored us. But to actually get the money you need to provide US tax details and stuff like that, which I'm not eager to do, so I canceled it.

**Comment by thijstriemstra** [comment]
Interesting. When was this? I'm also using opencollective for some other projects and that seems to work fine. Have you used that before?

**Comment by thijstriemstra** [comment]
> Open collective sounds interesting, does it also entail some sort of tax liability?

Not sure. it's also important that the people sponsoring the project can get a positive tax outcome (because it's non-profit etc) vs the liability. But I'm not a lawyer.

**Comment by nrthbound** [comment]
You guys should definitely suck it up, deal with the tax setup, and accept funding. This is such a massive project and could easily garner some cash because of how useful it is. I'd sponsor it.

**Comment by katspaugh** [comment]
OK, I've filled out the form again. They made it slightly easier with Stripe Connect. It will take a few days to approve.

**Comment by entonbiba** [comment]
@katspaugh @thijstriemstra let me know if you need help with this.
