### ISSUE TITLE
Waveform on top of a background image

### ISSUE THREAD

**Issue by vbspace** [katspaugh/wavesurfer.js#2624]
I was wondering if it is possible to put an image in the background of the waveform, and make the image stretch 100% width and height. 

I am currently looking and studying how the rendering of the waveform is done, please let me know if you have any tip or suggestion it's going to be helpful. Thank you!

**Comment by prakharpbuf** [comment]
You're gonna have to play with the following css properties to achieve it:
1. position
2. opacity
3. z-index
4. and of course height, width, top, bottom and other general properties

**Comment by entonbiba** [comment]
@vbspace you can do this like so:

```html
<style>
#waveform{
    background: url(https://images.unsplash.com/photo-1676306329389-3549138e52a6?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1025&q=80);
    background-repeat: no-repeat;
    background-position: center;
    background-size: auto;
}
</style>
<script src="https://unpkg.com/wavesurfer.js"></script>

<div id="waveform"></div>

<script>
var wavesurfer = WaveSurfer.create({
    container: '#waveform',
    waveColor: 'black',
    progressColor: 'green'
});
<script>
```
