### ISSUE TITLE
Safari: Lag during seeking when utilizing backend: "MediaElement"

### ISSUE THREAD

**Issue by stripedgoat** [katspaugh/wavesurfer.js#2625]
### Wavesurfer.js version(s):
6.4.0

### Browser and operating system version(s):
Safari, mainly happens on iOS (16.1), but sometimes also on macOS 11.7.1

### Code needed to reproduce the issue:
I'm going to use one of the official examples, as some of them are also affected. For example this one:
https://wavesurfer-js.org/example/angular-material/index.html

### Use behaviour needed to reproduce the issue:
When you play a song, and seek in the track (click in the waveform), the audio playback stops for half a second, then continues the playback. This is only present on Safari (both mac and iOS), and interestingly enough, only on some of the official examples. But what's even more weird, is that when I open another example in a new tab which doesn't have this issue, and hit play on that one, then the other one also gets fixed and the lag doesn't exist anymore.

1) So let's say you open this example:
https://wavesurfer-js.org/example/angular-material/index.html

2) Play the track. Try to seek into it. It stops and plays everytime you seek.

3) Open a new tab, and open this one:
https://wavesurfer-js.org/example/bars/index.html

4) Hit play, and you can immediately pause it as well.

5) Go back to your first tab, with the laggy seeking issue. It's no longer lagging!

What's happening here? How do we get rid of this issue?

**UPDATE:**
If I remove backend: "MediaElement", this issue doesn't exist. But that line of code is necessary for my usecase.

**Comment by srdecny** [comment]
I can still observe this issue on macOS + Chrome.

**Comment by skysnolimit08** [comment]
I created a janky workaround for this issue, which was only affecting browsers on my iOS mobile device and has to do with iOS mobile's aggressive pausing of audio contexts (apparently it doesn't even like us loading into, or perhaps even creating, wavesurfer instances before the user has engaged with the site).

Based on @stripedgoat 's note that the audio file at https://wavesurfer-js.org/example/bars/index.html , which is called demo.wav, works alright, I put a copy of that audio on my own site.  My site is a single-page app, so on the containing div (or something akin to it) for the entire app, I put

`@touchstart="resumeAudioContext" @mouseenter="resumeAudioContext"`

Then I wrote this function, which creates a hidden instance of wavesurfer and plays almost none (but a tiny amount) of the demo.wav audio file.  At the end, the function lets the entire app know that audio has been "initialized" for the site and it is safe to load audio files.

`		async resumeAudioContext() {
			if (this.audioReady == 0) { // ensures this initializing function is only run once

				// try to play a moment of audio cure in WebAudio wavesurfer as a janky workaround of bug in iOS a la https://github.com/katspaugh/wavesurfer.js/issues/2625
				// we have to get "audio player initialized" BEFORE the actually desirable audio is loaded.

				const hiddenContainer = document.createElement('div');
				hiddenContainer.style.display = 'none'; // Hide the container
				document.body.appendChild(hiddenContainer); // Attach to DOM (but invisible)

				this.wave3 = WaveSurfer.create({
					container: hiddenContainer, // No DOM element
				});
				const wave3 = this.wave3;
				this.wave3.load(demo);
				await this.wave3.on('ready', () => {
					this.wave3.play()
					this.wave3.pause()
				});
					console.log("audio player initialized")
					this.$store.commit("audioSafe");
					this.audioReady++ // ensures this initializing function is only run once
			}
		}`

Now, I make sure that no wavesurfer instances anywhere else on the site/app are even allowed to be created until the audio player is initialized (which I detect based on "audioSafe" having already run).

I did NOT go back and see whether using a different audio file from demo.wav would work at this point, and I also did not check whether playing demo.wav in a non-wavesurfer player would work to fix the problem vs. this extra wavesurfer instance solution.

Thanks for the tip, @stripedgoat .  If you found a different solution, please let us know!

sidenote: I first noticed this issue in summer 2024, not sure when it actually started.

**Comment by skysnolimit08** [comment]
Update: apparently, for the latest versions of Safari on iOS, the function I wrote needs to actually be triggered on touchend and click events, NOT touchstart and mouseenter events as I wrote above.  I can confirm that this fixed the remaining edge cases for me.

Source: https://github.com/mackron/miniaudio/issues/759
