### ISSUE TITLE
Showing microphone recording wav in realtime?

### ISSUE THREAD

**Issue by mb2140** [katspaugh/wavesurfer.js#263]
Are there any examples online of showing recorded microhpone input in real-time with Wavesurfer?

**Comment by cmarrero01** [comment]
@mb2140 how you solve this?... I was looking something similar, I'm try to record the audio from microfono and save it into a wav file. Could you give me an aprouch to do that?

**Comment by AdolfVonKleist** [comment]
you could probably adapt https://github.com/mattdiamond/Recorderjs

**Comment by cmarrero01** [comment]
@AdolfVonKleist  I already know how to record the audio file without wavesurfer, but, I love the wavesurfer library and I'm looking something that I can use with wavesurfer microphone plugin.

**Comment by thijstriemstra** [comment]
https://github.com/collab-project/videojs-record allows you to record, display and save audio.

**Comment by AbreezaSaleem** [comment]
So, I made a React package where you can record and playback your audio in real-time with the waveform graph animation! If anyone's interested, please check it out here: https://www.npmjs.com/package/react-voice-recorder-player.

(thanks to https://github.com/d0ragon for his playback waveform implementation)
