### ISSUE TITLE
setWaveColor method render issue

### ISSUE THREAD

**Issue by louislspn** [katspaugh/wavesurfer.js#2635]
Hello, I am trying to update the `waveColor` after `Wavesurfer` has been created with `wavesurfer.setWaveColor()` but the canvas is not updated.

```js
const wavesurfer = Wavesurfer.create({
  waveColor: 'black',
  ...
})

// later
wavesurfer.setWaveColor('red')
console.info(wavesurfer.getWaveColor()) // prints "red" but the wave is still black
```

I have already tried the `wavesurfer.drawBuffer()` method to re-render the wave but it doesn't work.

I have found a workaround that consists of zooming in and out to force-update the canvas but it causes performance issues :

```js
// waveColor change is working
wavesurfer.setWaveColor('red')
wavesurfer.zoom(10)
wavesurfer.zoom(0)
```

Thanks for your help.

`wavesurfer.js@6.4.0`

**Comment by entonbiba** [comment]
@louislspn 

```js
setWaveColor("#FF2D00");
```
