### ISSUE TITLE
sometimes, two get requests on playback?

### ISSUE THREAD

**Issue by daslicht** [katspaugh/wavesurfer.js#2638]
Hi,
is that the normal behavior that we get 2 GET requests when loading audio and playing it ?
```
     this.wavesurfer.load(this.audiosrc)
     this.wavesurfer.on('ready', () => {
      this.wavesurfer.drawBuffer()
      this.wavesurfer.play()
     })
```
With the code above, there are 'sometimes' 2 GET requets In the browser network monitor.
Is that the expected behavior ? please?
![](https://i.imgur.com/Wxr2oZl.png)

**Comment by entonbiba** [comment]
@daslicht it's likely the button or function that is triggering the `.load` that's causing it. Do you have more code to see?

**Comment by daslicht** [comment]
> @daslicht it's likely the button or function that is triggering the `.load` that's causing it. Do you have more code to see?

I ahev fixed it meanwhile by loading teh content just on playback. Looks like teh browser couldnt handle so many requests at the 'same time'
