### ISSUE TITLE
how to disable marker click ?

### ISSUE THREAD

**Issue by vishal-4way** [katspaugh/wavesurfer.js#2640]
Is there any way to disable markers click ? please help if is there any .thanks !

**Comment by prakharpbuf** [comment]
Please be more specific with your question.

Do you mean how the audio seeks to whatever position you click on the waveform? If yes, I think you are looking for wavesurfer.toggleInteraction()

**Comment by vishal-4way** [comment]
My question is while using Markers plugin and add a marker ,  when user click on that marker wave seek to that point so is there any way to stop that click function . thanks!

**Comment by prakharpbuf** [comment]
To do what you're trying to do, the only way I can think of involves modifying the WaveSurder code. 
Do you need help with that?

Also, I'm curious, why would you need to disable seek on marker click? By doing this, you are defeating half the purpose of markers plugin.

**Comment by thijstriemstra** [comment]
sounds like you should enable wavesurfer.js `interact` option and set it to false.

**Comment by vishal-4way** [comment]
interact option not woking on marker plugin

> To do what you're trying to do, the only way I can think of involves modifying the WaveSurder code. Do you need help with that?
> 
> Also, I'm curious, why would you need to disable seek on marker click? By doing this, you are defeating half the purpose of markers plugin.

Thanks! for offering help, but I drop that idea for now.

**Comment by vishal-4way** [comment]
> sounds like you should enable wavesurfer.js `interact` option and set it to false.

interact option not work on marker plugin .
