### ISSUE TITLE
Does the library automatically paginate the wavecanvas if audio is too long?

### ISSUE THREAD

**Issue by grant-solomons** [katspaugh/wavesurfer.js#2643]
Hi, I've been assigned an issue that uses the wavesurfer.js library.
This issue is that when an audio is too long, it seems to paginate to the next section of the audio.
Is this a wavesurfer.js related issue or should I look into what the previous dev has done (so far I cannot see anything paginated related). 
Is this part of the wavesurfer.js features?
<img width="814" alt="Screenshot 2023-01-12 at 14 33 29" src="https://user-images.githubusercontent.com/100674583/212067578-99f703d7-8e7a-4d70-8101-3c1543d65d3a.png">

**Comment by prakharpbuf** [comment]
I don't believe wavesurfer.js paginates.
I have only ever seen wavesurfer.js fit the waveform in the div container given to it. It "zooms" accordingly to fit the whole waveform in that div.
If the size of window is increased after waveform is drawn, it does not affect the waveform and stays the same size leaving empty space after the waveform.
If the size of window is decreased, it again, does not affect the waveform, instead the div containing the waveform becomes scrollable horizontally.

This behavior was noted in google chrome browser.

**Comment by prakharpbuf** [comment]
There is a 'scrollParent' [option](https://wavesurfer-js.org/docs/options.html) which, if set to true will render the waveform only according to the 'minPxPerSec' option and give you a scrollbar on the container.
See difference: 
The first image is rendered with default values i.e. scrollParent: false
![image](https://user-images.githubusercontent.com/54688220/215109478-f17556e5-b579-4d10-90c3-a277f1a85601.png)

The second image is rendered with scrollParent: true and default minPxPerSec i.e. 50
![image](https://user-images.githubusercontent.com/54688220/215109993-ff06f36b-a59b-459b-a045-a3fc32cff7f2.png)

The audio shown in both images is 3 mins long.


Please close this issue if not further discussion is required :)
