### ISSUE TITLE
How to get the correct time while zooming using the timeline plugin?

### ISSUE THREAD

**Issue by irakan** [katspaugh/wavesurfer.js#2648]
How can I get the correct time while zooming in/out using the timeline plugin?
https://codepen.io/lise26/pen/mpexma

so in the above link, when I zoom in and click on 10

how can I get that spcefic time label

```js
this.player.on("seek", (postion) => {
  let videoDuration = 15; // in secs
  let zoomLevel = 100;
  let currentTime = postion * videoDuration;

  this.updateVideoCurrentTime(currentTime);
});
```

**Comment by prakharpbuf** [comment]
try wavesurfer.getCurrentTime() ?

**Comment by irakan** [comment]
I tried that before.. it doesnt do the job. 

What I am looking for is:
Open the codepen link.. then **zoom in** .. scroll to the end of the timeline.. click on the time label that is shown on the timeline plugin. for example : 2:45.

I want that time..

Thank you.

**Comment by irakan** [comment]
This is how I did it in case someone was looking for the same thing:
```
<div id="timeline" @click="timelineClickHappend"></div>
```
```js
timelineClickHappend($event) {
  let progress = waveSurfer.drawer.handleEvent($event)
  waveSurfer.seekTo(progress)
  let currentTime = waveSurfer.getCurrentTime()
  console.log(currentTime)
}
```

closing.
