### ISSUE TITLE
Is it possible to refresh WaveSurfer on toggling DOM existence of the container element?

### ISSUE THREAD

**Issue by DrKlonk** [katspaugh/wavesurfer.js#2649]
Hello! 

I am using the awesome package wavesurfer.js to display waves of audio files in a table. The expandable rows that show the waves are added and removed from the DOM. So the container for the WaveSurfer instance is removed from the DOM, not hidden with css.

Is there a way to "refresh" the WaveSurfer waves after the container (with the same id, of course) is in the DOM again?

I don't want to download the file twice by just creating a new WaveSurfer instance and loading the file again and putting it in the new container.

See [this codepen](https://codepen.io/drklonk/pen/wvxmbOM) for what I mean exactly.

**Comment by prakharpbuf** [comment]
With a little change, I think I was able to achieve what you are looking to do.
Idk if you can see the changes I made in the codepen but here's what I did:
![image](https://user-images.githubusercontent.com/54688220/214585093-ebc00224-1dd9-40a0-8b99-4d835e6fcf1a.png)

**Comment by DrKlonk** [comment]
Riiight! If I get it right, I need to keep the instantiation to the element out of the toggle function, so it references the original. And we can append the original element to the DOM again. Makes sense since we pass objects by reference in JS.

Thank you a lot for your help.

**Comment by prakharpbuf** [comment]
Not a problem! 
Please go ahead and close this issue if no further discussion is required.
