### ISSUE TITLE
Getting Current Time of Audio when it is paused

### ISSUE THREAD

**Issue by pokemon963** [katspaugh/wavesurfer.js#2650]
### Wavesurfer.js version(s):
I am using the version at this link: https://unpkg.com/wavesurfer.js

### Browser and operating system version(s):
Browser: Chrome; OS: Windows 11

### Problem

I want to be able to get the current time of the audio when it is paused, meaning that if the audio is not playing and I click on another place in the audio, the current time will change. I know how to change it when the audio is playing. This is the code I have:

```
wavesurfer.on('audioprocess', function() {
        var currentTime = wavesurfer.getCurrentTime();

        document.getElementById('time-current').innerText = (Math.round(currentTime * 1000)/1000);
      });
```

I have tried replacing "audioprocess" with "interaction" to see if this could be achieved. While it does update the current time, it is not accurate. Is there any way I could achieve what I want?

**Comment by prakharpbuf** [comment]
wavesurfer.getCurrentTime() should do what you're looking to do. You don't need to wrap it in an audioprocess event if you're only looking to get the current progress in seconds when it is paused.

> if the audio is not playing and I click on another place in the audio, the current time will change.
You're looking for an onclick handler on your wavesurfer container.

**Comment by pokemon963** [comment]
Thank you so much! The 'seek' event was perfect!
