### ISSUE TITLE
Creating Regions

### ISSUE THREAD

**Issue by pokemon963** [katspaugh/wavesurfer.js#2651]
Hi! I was wondering if it was possible to make Regions like as a method. I only want a region to appear when a certain selection is made to the audio and the length of the region would not be specified until then. I saw that Regions are placed in `var wavesurfer = WaveSurfer.create`. But is there a way to add Regions once the `wavesurfer` has been created (i.e. outside `WaveSurfer.create`)?

**Comment by pokemon963** [comment]
I'm trying to use wavesurfer.addRegion({}) but it is saying function does not exist.

I have imported regions as:
`<script src="https://unpkg.com/wavesurfer.js/dist/plugin/wavesurfer.regions.min.js"></script>`

And I have created the region through this:
`wavesurfer.addRegion({ start: currentTime, end: nextTime, color: 'hsla(400, 100%, 30%, 0.1)' });`

**Comment by prakharpbuf** [comment]
Have you included the regions plugin while creating the wavesurfer instance?
```
var wavesurfer = WaveSurfer.create({
    container: '#waveform',
    plugins: [
        RegionsPlugin.create({})
    ]
});
```

Please note that the way you init the regions plugin depends on what you are using i.e. script tags/import etc. Please see [here ](https://wavesurfer-js.org/api/class/src/plugin/regions/index.js~RegionsPlugin.html)for reference.

**Comment by pokemon963** [comment]
Yeah that fixed it! Thank you!
