### ISSUE TITLE
Interaction event that doesn't include .skip()

### ISSUE THREAD

**Issue by pokemon963** [katspaugh/wavesurfer.js#2652]
I am trying to get a function to run when I interact/select an area on the waveform. I know that there is "interaction" events. However, they include when I use the wavesurfer.skip() function. The function I am trying to call should activate when someone clicks on the waveform but not when .skip() is used as wavesurfer shouldn't respond when .skip() is called by another function but only when the user selects/clicks on a part of the waveform. Is there such an event or function?

**Comment by prakharpbuf** [comment]
I'm not an expert in any way but try having an onclick event on your waveform container?
...or 
Again, I'm not an expert but,
Based on your previous questions, you're getting the wavesurfer library from https://unpkg.com/wavesurfer.js@6.4.0/dist/wavesurfer.js
To do what you're trying to do, I copied all the code from that unpkg, put it in an html file called wavesurfer.js and imported it using a script tag in my code like this:
![image](https://user-images.githubusercontent.com/54688220/215496314-874ddf53-ef0e-4301-9c73-4d4017477c8f.png)

After that, I modified the code in wavesurfer.js a bit to give us an option whether to fire the seek event or no. Here are the changes:
![image](https://user-images.githubusercontent.com/54688220/215496874-4c6d8655-801e-464c-98b8-3f168e5b700e.png)
![image](https://user-images.githubusercontent.com/54688220/215497013-ab636c69-cda9-4dd7-801b-c4db5990807a.png)

Now, where ever in your code when you are calling wavesirfer.skip(seconds), call wavesurfer.skip(seconds, false) instead to prevent the seek event from firing and hope it does not break anything :)

**Comment by pokemon963** [comment]
Thank you! The onclick event worked!

**Comment by pokemon963** [comment]
Hi! I am trying to use your second method as there as some bugs with the onclick event. After I changed the wavesurfer.js code, interacting with the waveform is not considered a seek event anymore. Is there anyway to fix this?

**Comment by prakharpbuf** [comment]
Did you copy the code exactly as shown in the images? Specifically the 'fireSeek=true' part in function arguments.
After doing these changes, I interacted with(clicked on) the waveform and the seek event was fired. I could not replicate your error.
Also, I'm curious, why did the onclick event not work? Something specific to your project or is it something more general that you can share?

**Comment by prakharpbuf** [comment]
As a closing note, other methods like wavesurfer.stop() also fire the 'seek' event. 
If you want to prevent, for example, stop() from firing the seek event, do the same thing you did for skip():
Find the stop function in wavesurfer.js:
line 4261 - 4266 (as of today):
```
    key: "stop",
    value: function stop() {
      this.pause();
      this.seekTo(0);
      this.drawer.progress(0);
    }
```

change it to:
```
    key: "stop",
    value: function stop(fireSeek=true) {
      this.pause();
      this.seekTo(0, fireSeek);
      this.drawer.progress(0);
    }
```
and simply use wavesurfer.stop(false)

**Comment by prakharpbuf** [comment]
I found a cool thing in #2329 

```
wavesurfer.setDisabledEventEmissions(['seek']);
// Do stuff here, seek wont be emitted.
wavesurfer.setDisabledEventEmissions([]); // set all events to emit once you're done
```

You can wrap your .skip() between these functions to prevent seek from firing. This way, you won't have to download and modify the wavesurfer code and you can keep getting wavesurfer from unpkg so that you always have the latest version.

Also, actually I think a better implementation would be:

```
wavesurfer.setDisabledEventEmissions([...wavesurver._disabledEventEmissions ,'seek']);
// Do stuff here, seek wont be emitted.
wavesurfer.setDisabledEventEmissions(wavesurfer._disabledEventEmissions.filter(e => e!= 'seek'); // set all events to emit once you're done
```
