### ISSUE TITLE
live waveform visualization from an audio file.

### ISSUE THREAD

**Issue by prakharpbuf** [katspaugh/wavesurfer.js#2663]
wavesurfer version 6.4.0

I want live waveform like the microphone plugin but from an already existing audio file.

Like, I have an audio file. I don't want to render the whole waveform for that audio at once. I want to visualize that audio live as it is playing (like in the microphone plugin when we speak)

Is there any way to achieve this? Any help would be appreciated!
Thanks!

**Comment by prakharpbuf** [comment]
Hi @entonbiba 
Thank you for taking up this issue.
Is there any way for me to work with you to add this feature? 
I mean, I'd love the opportunity to help and learn more about wavesurfer.js and its development.

Please let me know if there's anything I can do.

Thanks!

**Comment by prakharpbuf** [comment]
I have been answering questions here on github issues so I already have a pretty good understanding of the working of wavesurfer.js 
Now I'd love to dig into the development part.

**Comment by prakharpbuf** [comment]
I was able to achieve this. Here's a react snippet:
```
    useEffect(() => {
        if(playing){
            setScriptProcessor(wsRef.current.backend.ac.createScriptProcessor(4096, 1, 1));
        }
        else {
            if(scriptProcessor) {
                scriptProcessor.onaudioprocess = undefined;
                setScriptProcessor();
            }
        }
    }, [playing])


    useEffect(() => {
        if(scriptProcessor) {
            const ac = wsRef.current.backend.ac;
            const src = new AudioBufferSourceNode(ac, {buffer});
            src.connect(scriptProcessor).connect(ac.destination);
            scriptProcessor.onaudioprocess = e => wsRef.current.loadDecodedBuffer(e.inputBuffer);
            src.start(0);
        }
    }, [scriptProcessor])
```

Basically I create a buffer source and connect it to a script processor node (not recommended tho, its deprecated but eh) and connect the script processor to wavesurfer.backend.ac.destination
Then, on the audioprocess event of the script processor, I get the input buffer from e.inputBuffer and call loadDecodedBuffer() with it.
I referenced code from wavesurfer's microphone plugin's connect() method to come up with this code.

**Comment by entonbiba** [comment]
@prakharpbuf here is a sample of how to achieve this. I'll submit the sample soon on the example page as well.

https://www.entonbiba.com/lab/wavesurfer/2663.html


``` js

    wavesurfer.on("audioprocess", function(dataGET) {
        var thispeaks = wavesurfer.backend.getPeaks(
            dataGET*wavesurfer.params.minPxPerSec,
            wavesurfer.params.minPxPerSec,
            dataGET*wavesurfer.params.minPxPerSec
        )
        wavesurfer.drawer.drawPeaks(
            [thispeaks],
            dataGET*wavesurfer.params.minPxPerSec,
            dataGET,
            dataGET*wavesurfer.params.minPxPerSec
        );
    });

```

**Comment by prakharpbuf** [comment]
Thank you @entonbiba that helps!!

**Comment by fatehux** [comment]
i have the same issue can you help me?
