### ISSUE TITLE
ignoreSilenceMode on iPhone - audio cuts out after a short time

### ISSUE THREAD

**Issue by jroebu14** [katspaugh/wavesurfer.js#2667]
Hi there!

I have noticed a bug on iPhone when `ignoreSilenceMode` is enabled and you play the audio with silent mode switched on then the audio plays for 2 or 3 seconds before the audio stops. I also reported this [here](https://github.com/katspaugh/wavesurfer.js/pull/2176#issuecomment-1398122664) but thought it needed an issue.

### Wavesurfer.js version(s):
I'm using wavesurfer.js v6.4.0

### Browser and operating system version(s):
iPhone 13 Pro
iOS 16.2
Chrome 105.0.5195.147

### Code needed to reproduce the issue:

https://codesandbox.io/s/reverent-dust-xtl33i?file=/src/AudioPlayer.js

### Use behaviour needed to reproduce the issue:

Navigate to https://xtl33i.csb.app/ on an iPhone with silent mode switched on then click the play button when the audio has loaded and the waveform is visible. Observe that the audio cuts out after a short time.

**Comment by katche70** [comment]
Hi, 

I had the same problem. I switched to
backend: 'MediaElement' (ignoreSilenceMode: true is no longer needed )

This seems to solve almost all the problems for me. But I do not know exactly what disadvantages this brings

**Comment by jroebu14** [comment]
Hi @katche70

Thank you for recommending this workaround. I switched to `backend: 'MediaElement` and removed `ignoreSilenceMode: true` as you suggested and can confirm I no longer experience the audio cutting out 🎉 

I had a quick look into what this change means and as far as I can tell, `backend: 'MediaElement'` will use HTML5 audio instead of the WebAudio API. It has some limitations on iOS for example you cant set the volume or playback rate with that backend but these limitations do not affect my use cases.

**Comment by katche70** [comment]
I can set volume and playback on iOS. 
Faster playback is even significantly better and doesn't have the awful chip and chap gopher voices.

**Comment by danbunkr** [comment]
I am having the same issue but cannot seem to switch my code over to MediaElement and get it working. My src is a base64 string that I load in dynamically and not a local or user selected mp3 file.

**Comment by entonbiba** [comment]
@jroebu14 @katche70 @danbunkr  I'll create a PR for this with a fix, essentially it needs a webaudio context to be created on interaction.

You can test it here:
https://www.entonbiba.com/lab/wavesurfer/2667.html

**Comment by entonbiba** [comment]
it's likely the timing that gets triggered in latest ios version now.... we will have to test it in latest version again and see what's possible

**Comment by katspaugh** [comment]
Closing because in v7 there's no WebAudio backend.
