### ISSUE TITLE
Pitch contour plugin

### ISSUE THREAD

**Issue by katspaugh** [katspaugh/wavesurfer.js#269]
Code for reference: http://www.codeproject.com/Articles/375511/Silverlight-Pronunciation-Test#DisplayingPitchContour

http://en.wikipedia.org/wiki/Pitch_detection_algorithm

**Comment by toolowner** [comment]
@katspaugh Sorry for bothering you. Is there anyone make this plugin into real life?

**Comment by toolowner** [comment]
@katspaugh Sorry for bothering you. Can you make this plugin into real life? Thank you

**Comment by katspaugh** [comment]
For anyone googling and finding this issue, the pitch contour example is here:

https://wavesurfer-ts.pages.dev/tutorial/#/examples/pitch.js
