### ISSUE TITLE
`normalize` option removed, waveforms not normalized

### ISSUE THREAD

**Issue by dietmar** [katspaugh/wavesurfer.js#2812]
The README for 7.0.0-beta.5 (https://github.com/katspaugh/wavesurfer.js/blob/7.0.0-beta.5/README.md?plain=1#L105) says that the `normalize` option was removed and that waveforms are now normalized by default. That doesn't seem to be the case, though. In my tests, quiet audio files get drawn with low amplitude peaks and louder files with higher amplitude peaks.

The easiest way I found to reproduce was to use https://wavesurfer.pages.dev/examples/#pitch.js and upload a very low audio file (e.g., use Audacity to amplify down some audio file and re-export):
![image](https://github.com/katspaugh/wavesurfer.js/assets/6614172/09c37805-ec87-4947-9d35-3216da73b677)

I'd also argue that having the choice whether to normalize or not in the `options` makes sense. Consider these two scenarios:
* We only have a single audio file on a page, we want to draw its waveform using all the available vertical space. Here we want to normalize.
* We have multiple audio files on a page and want it to be visually obvious that some of them are overall louder than others. In this case we wouldn't want to normalize.

Therefore, I would wish back the `normalize` option. Maybe its default value could be `true`.

**Comment by katspaugh** [comment]
Makes sense!
v7 normalizes by default to -1..1 but not by max value like the old `normalize: true` option did.

I'm definitely _for_ restoring it. Against stretching by default tho. It should remain false by default, IMHO.

**Comment by katspaugh** [comment]
Peaks need to be in the range from -1 to 1 so it normalizes them if there are values outside of the range. Anyway, it’s a different type of normalization and not a replacement for the old one.
