### ISSUE TITLE
Unable to drag regions on mobile with v7

### ISSUE THREAD

**Issue by katspaugh** [katspaugh/wavesurfer.js#2817]
### Discussed in https://github.com/katspaugh/wavesurfer.js/discussions/2816

<div type='discussions-op-text'>

<sup>Originally posted by **erik-iglikov** May 31, 2023</sup>
Hey [katspaugh](https://github.com/katspaugh), first of all thank you and the folks who help for such a great library, love the work you do!

I'm trying to implement draggable regions on mobile. It works for the desktop but doesn't allow me to drag the region on mobile or mobile simulator in Chrome. I've tested [regions example from docs] (https://wavesurfer-js.org/examples/#regions.js) and didn't work there either (on mobile).

My setting for RegionPlugin:
`
const DEFAULT_REGION_CONFIG: RegionParams = {
  id: 'default',
  start: 0,
  end: 30,
  resize: false,
  drag: true,
};
`

Please let me know your thoughts on it.

</div>

**Comment by katspaugh** [comment]
This is probably due to the fact that we're only assigning mousedown/mousemove events and not touchstart/touchmove. 

We should ideally extract the `makeDraggable` function into a help class or function because the same code is used for dragging the cursor in the core package, the Regions and the Envelope plugin.

**Comment by treio** [comment]
👍 for extracting the function into a helper class/function.

**Comment by katspaugh** [comment]
Fixed in #2824
