### ISSUE TITLE
Mono Playback in Firefox

### ISSUE THREAD

**Issue by ShiroSirius** [katspaugh/wavesurfer.js#282]
Playback in Firefox appears to be in mono. Is this due to Firefox's implementation of the web audio API, or something to do with wavesurfer.js itself?

I've tested this with .mp3, .ogg and .wav files.

**Comment by katspaugh** [comment]
This is due to Web Audio, not wavesurfer.js. Try the `MediaElement` backend instead of `WebAudio`. Closing as wont-fix.
