### ISSUE TITLE
Background color issue in Chrome in version 7

### ISSUE THREAD

**Issue by mohammadnt** [katspaugh/wavesurfer.js#2831]
Created canvas on Chrome has black background while there is no problem in Firefox. im using version 7.0.0-beta.5 in Angular 14.
Chrome:
![wavesurfer_chrome](https://github.com/katspaugh/wavesurfer.js/assets/10488361/a845a792-0db5-44ca-9fec-13baa8e88230)
Firefox:
![wavesurfer_firefox](https://github.com/katspaugh/wavesurfer.js/assets/10488361/77886fba-0f4d-4231-b131-8b9b73b5bf44)

**Comment by IdoBouskila** [comment]
Can you provide the code?

There is an example in the docs: 
[gradient wavesurfer.js](https://wavesurfer-js.org/examples/#gradient.js)

**Comment by mohammadnt** [comment]
I created a project from scratch to test on and found it is drawing black background only when there is both overflow: hidden and border-radius: 16px style applied to container or one of its parents. As it is so strange for me, I provided the project and a film shows the issue
Project :
https://github.com/mohammadnt/WaveSurferBlackBackground
film:

https://github.com/katspaugh/wavesurfer.js/assets/10488361/56657879-4a63-4de0-bca4-2ae68eeb7520
