### ISSUE TITLE
timeline disappeared

### ISSUE THREAD

**Issue by edwardsmarkf** [katspaugh/wavesurfer.js#2832]
https://unpkg.com/wavesurfer.js@beta/dist/plugins/timeline.js no longer available!

Cannot find "/dist/plugin/wavesurfer.timeline.js" in wavesurfer.js@7.0.0-beta.6

https://wavesurfer-js.org/example/timeline/   - this is no longer working.

**Comment by edwardsmarkf** [comment]
something appears to have seriously changed with unpkg.com the past day or so.  

i am unable to get timeline restored, but at least i was able to fix things by referencing this older version:

//www.unpkg.com/wavesurfer@1.3.4/dist/wavesurfer.min.js

is there a version of timeline available from yesterday or the day before?

**Comment by katspaugh** [comment]
Maybe they were down? https://unpkg.com/wavesurfer.js@beta/dist/plugins/timeline.js opens for me now.

**Comment by katspaugh** [comment]
We're also on cdnjs and probably other CDNs out there: https://cdnjs.com/libraries/wavesurfer.js/7.0.0-beta.6
