### ISSUE TITLE
Playback after recording not working on a Safari ios 16

### ISSUE THREAD

**Issue by iiKulakov** [katspaugh/wavesurfer.js#2836]
After getting access rights and recording audio i can see a waveform, but there is no sound when playing.
In Desktop Chrome everything is ok.

### Wavesurfer.js version(s):
beta 7

### Browser and operating system version(s):
Ios 16 Safari
Mac os Safari 16.5

### Code needed to reproduce the issue:
Example have a same issue on Safari: 
https://wavesurfer-js.org/examples/#record.js

### Steps needed to reproduce the issue:
Go to https://wavesurfer-js.org/examples/#record.js -> start to record -> stop recording -> try to play the recording

**Comment by iiKulakov** [comment]
When i changed type to { type: 'audio/mpeg' } in a record.ts and player.ts, playback started to work in a Safari.

**Comment by katspaugh** [comment]
Nice! Can you submit a PR?

**Comment by zetorama** [comment]
Hey folks, lemme join the party, as I was trying to figure out this issue for past few days as well. And once I found your discussion here, I was able to dig down a bit, and after some experimenting and testing submitted a PR #2892.

Please take a look and let me know if this seems to be working for you 🙏
