### ISSUE TITLE
Issue: wavesurfer.js v7@beta - fillParent not working as expected

### ISSUE THREAD

**Issue by IdoBouskila** [katspaugh/wavesurfer.js#2837]
I'm using wavesurfer.js v7@beta and have encountered an issue where the `fillParent` property doesn't work as expected.
The problem is that the wavesurfer child elements have a default height of 128px instead of occupying 100% height when `fillParent` is set to `true`. This default height overrides the parent's 100% height setting.

To address this issue, we need to fix the height of the wavesurfer child element so that it properly fills the parent container when `fillParent` is enabled.

Here is a demo showcasing the issue: [Demo](https://codesandbox.io/s/festive-taussig-u815jh?file=/src/App.js).

**Comment by katspaugh** [comment]
The same was in v6 though. `fillParent` never meant filling the parent vertical, only horizontally.
But I agree overall, it would make sense to use the container height by default, and only fall back to 128 if that height is 0.

**Comment by IdoBouskila** [comment]
> The same was in v6 though. `fillParent` never meant filling the parent vertically, only horizontally.
> 
> But I agree overall, it would make sense to use the container height by default, and only fall back to 128 if that height is 0.

Someone working on this? Or should I try to PR?

**Comment by katspaugh** [comment]
Oh, I've done it already, but I would appreciate if you could review and test it locally. Cheers.

**Comment by IdoBouskila** [comment]
> Oh, I've done it already, but I would appreciate if you could review and test it locally. Cheers.

Sure, I will do it today
