### ISSUE TITLE
Dragging on timeline: interaction event handler no longer reports current time

### ISSUE THREAD

**Issue by brollin** [katspaugh/wavesurfer.js#2844]
### Wavesurfer.js version(s):
`^7.0.0-beta.6`

### Browser and operating system version(s):
Firefox 113.0.2, macOS Monterey 12.6

### Code needed to reproduce the issue:
```javascript
wavesurfer.on("interaction", () => {
  console.log("interaction", wavesurfer.getCurrentTime());
});
```

### Use behaviour needed to reproduce the issue:
After attaching the above event listener, click and drag on the timeline. I'm noticing that the alpha version of wavesurfer will report the time that you have dragged to when `getCurrentTime()` is called, but the beta version of wavesurfer will report the time that you last clicked (mouseup'ed I suppose?) when `getCurrentTime()` is called.

**Comment by brollin** [comment]
@katspaugh just looking into this a bit more, and it seems related to the debouncing of drag interaction events:
https://github.com/katspaugh/wavesurfer.js/blob/f3b6ac435d7189cb24a79bf07643bf0281e79eed/src/wavesurfer.ts#L224-L231

When editing locally, I'm finding that I'm only achieving my desired behavior with the complete removal of the debounce. For example, just manually setting the debounce time to 0 still gives undesired behavior, because of the asynchronous nature of `setTimeout`.

Would you be open to an option that completely ops out of the debouncing? Happy to implement such a thing if it would be helpful.

**Comment by katspaugh** [comment]
I was asked to add the debouncing because otherwise it’s choppy with large files.

Since the interaction event is fired outside of the timeout, and thus reports the wrong time, maybe we can adjust that instead. I.e. pass a calculated new time to the event.
