### ISSUE TITLE
The gap between canvases is too narrow.

### ISSUE THREAD

**Issue by letavocado** [katspaugh/wavesurfer.js#2845]
### Summary
When wavesurfer.js generating multiple canvases, the barGap in canvases appears too narrow. 

### Possible solution:
This can be fixed by setting the barGap to be equal to the barWidth by default.

### Screenshots
![image](https://github.com/katspaugh/wavesurfer.js/assets/31704887/1129afb0-19ba-4eb8-91dd-8b4256e842a0)
![image](https://github.com/katspaugh/wavesurfer.js/assets/31704887/18ed2b71-fcca-45e1-b8ef-329c50cbf186)

**Comment by katspaugh** [comment]
This happens at the edges of canvases when there’s scroll. It’s a bug indeed.

**Comment by katspaugh** [comment]
If you’d like to try your hand at fixing this, the relevant code is here:

https://github.com/katspaugh/wavesurfer.js/blob/beta/src/renderer.ts#L356

It needs to take barWidth/barGap into account when calculating the canvas width. It has to be divisible by barWidth + barGap essentially.

**Comment by letavocado** [comment]
Sure, I can take care of it during the upcoming weekend.

Cheers!
