### ISSUE TITLE
Multitrack cursor not going back to beginning after finish playing and trying to play again

### ISSUE THREAD

**Issue by tmtakashi** [katspaugh/wavesurfer.js#2853]
# Hey, thank you for testing and contributing to wavesurfer.js!

## Please make sure you can check all of these points below before opening an issue:

(You don't have to post this section)

- [x] I have checked [the FAQ](https://wavesurfer-js.org/faq/) and it doesn't solve my problem.
- [x] I have checked [the documentation](https://wavesurfer-js.org/docs/) and it doesn't solve my problem
- [x] I have searched for [already open issues](https://github.com/katspaugh/wavesurfer.js/issues) which desribe my problem.
- [x] The issue I'm having is related to and caused by wavesurfer.js, not by other software (which maybe packages and uses wavesurfer incorrectly) – In that case you should open the issue on the respective project pages.

### Wavesurfer.js version(s):
7.0.0-beta.6

### Browser and operating system version(s):
Chrome, Windows 11

### Code needed to reproduce the issue:
https://wavesurfer.pages.dev/examples/#multitrack.js

(Please reduce your code as much as possible and only post the minimum code needed to reproduce the issue. [A Code pen](http://codepen.io/) is an excellent way to share such code)

### Use behaviour needed to reproduce the issue:

1. Drag the cursor toward near the end of the player.
2. Click "Play" and wait until it finishes playing.
3. Click "Pause"

I expected the cursor to go back to the beginning and play all the tracks simultaneously, but it seems that the cursor is not going back, and only track id 1 is playing.

https://github.com/katspaugh/wavesurfer.js/assets/38929720/16898637-699e-48de-a969-897d794f5637

**Comment by katspaugh** [comment]
It’s not expected to go back. You gotta code it yourself. There’s a “finish” event on media elements that you can listen to and jump back to 0.
