### ISSUE TITLE
Is it possible to have responsive height? Fillparent only seems to fill horizontally

### ISSUE THREAD

**Issue by tombburnell** [katspaugh/wavesurfer.js#2858]
### Wavesurfer.js version(s):
6.6.3

### Browser and operating system version(s):
Chrome

### Code needed to reproduce the issue:

I'm just fill parent:true (which is default)

It stretches horizontally to fit the div but not vertically - I can only seem to control the vertical height using the height attribute.

I need to be able to shrink it vertically on mobile, how can I do this?

thanks, Tom

**Comment by katspaugh** [comment]
This was just added in beta.7: https://github.com/katspaugh/wavesurfer.js/pull/2841
