### ISSUE TITLE
Drag event: manipulate the current play time instead of manipulating the region through the drag event.

### ISSUE THREAD

**Issue by OhWonJu** [katspaugh/wavesurfer.js#2867]
### Wavesurfer.js version(s): 
```
^6.6.3
```

Hello,
I would like to get advice on the following matter.

Rather than manipulating the region through the drag event, I want to manipulate the current play time.
Apart from controlling the currentTime through a click on the waveform, I would like to be able to set the currentTime by dragging the waveform.

**Comment by katspaugh** [comment]
This is implemented in v7 and won’t be added in v6. So please feel free to upgrade.
