### ISSUE TITLE
Progress Canvas Crash

### ISSUE THREAD

**Issue by ardiantutomo** [katspaugh/wavesurfer.js#2883]
Hi @katspaugh,
I found this bug when using Chrome in Mac.
I think this problem comes in progress canvas, and this problem only exist if i'm using long video (in my case 9 minutes video)

<img width="942" alt="image" src="https://github.com/katspaugh/wavesurfer.js/assets/20126113/38b30f18-ab39-470b-8db0-8433883edfcf">

Any suggestion for this? 

Thank you

**Comment by ardiantutomo** [comment]
For example I change the timeline example file to this:
```
// Timeline plugin

import WaveSurfer from 'https://unpkg.com/wavesurfer.js@beta'
import TimelinePlugin from 'https://unpkg.com/wavesurfer.js@beta/plugins/timeline.js'

// Create an instance of WaveSurfer
const ws = WaveSurfer.create({
  container: document.body,
  waveColor: 'rgb(200, 0, 200)',
  progressColor: 'rgb(100, 0, 100)',
  url: 'https://dl.dropboxusercontent.com/s/xvm8b8idhxfheto/645efee298406.mp4?raw=1',
  peaks: [0],
  minPxPerSec: 100,
})

// Initialize the Timeline plugin
ws.registerPlugin(TimelinePlugin.create())

// Play on click
ws.on('interaction', () => {
  ws.play()
})

// Rewind to the beginning on finished playing
ws.on('finish', () => {
  ws.setTime(0)
})
```

**Comment by katspaugh** [comment]
I'll check.

**Comment by ardiantutomo** [comment]
@katspaugh 
I try to remove the Math.ceil function in this line (renderer.ts) and it's good now. Any concern?
[` const end = Math.ceil(start + viewportWidth * scale)`](https://github.com/katspaugh/wavesurfer.js/blob/f27fac077f877226b2b2ecd2c86215ac39f548b6/src/renderer.ts#L359)

**Comment by katspaugh** [comment]
Hmm, strange. What's the value of end before and after your change?

**Comment by ardiantutomo** [comment]
Before is 1, after floating point (0.9xxx)

**Comment by katspaugh** [comment]
I guess it has to do with `peaks: [0],`. There's no `[1]` element, so it fails to render a peak at that index.
You can fix this for now by passing `peaks: [0, 0]`.

**Comment by ardiantutomo** [comment]
Alright, it's good now!
Thank you!

**Comment by katspaugh** [comment]
I see, thanks. I’ll fix it in the `const end` code you mentioned.

**Comment by katspaugh** [comment]
I haven't been able to reproduce the bug anymore.
Pasted the code you posted above here: https://wavesurfer-js.org/examples/#4853b4f471626e748527fb7f08bdd88a
Nothing crashes, it's just empty as expected with zero peaks.

It might've been fixed by some commit in the meanwhile.
