### ISSUE TITLE
Applying custom CSS styling is not working as intended and is not supported.

### ISSUE THREAD

**Issue by TwanLuttik** [katspaugh/wavesurfer.js#2900]
I'm using `"wavesurfer.js": "^7.0.0-beta.8"`

So I'm trying to do some styling and for the most part it works fine but if i try to modify the .progress class it does not want to have effect

This is my code and the first 2 classes i'm trying to change does work but the last one with `progress` doesn't have any effect.
<img width="400" alt="CleanShot 2023-06-16 at 19 26 31@2x" src="https://github.com/katspaugh/wavesurfer.js/assets/19343894/1290fa03-a9fe-4946-9802-c3340d1c110c">

<br/>

Before the styling
<img width="841" alt="CleanShot 2023-06-16 at 19 22 39@2x" src="https://github.com/katspaugh/wavesurfer.js/assets/19343894/98f20e18-7691-4bd5-b915-6812c913694c">

After what it should look like
<img width="839" alt="CleanShot 2023-06-16 at 19 22 55@2x" src="https://github.com/katspaugh/wavesurfer.js/assets/19343894/251c2836-6de1-4507-8e9c-c93008ef6c97">

**Comment by katspaugh** [comment]
Progress isn't exposes as a "part". It doesn't have a `part` attribute. Classes are used only for internal CSS.

Please feel free to add a part attribute and make a PR. Cheers.

<img width="504" alt="Screenshot 2023-06-17 at 09 07 35" src="https://github.com/katspaugh/wavesurfer.js/assets/381895/95a1c301-0f19-43b0-9a7f-3f95ef8908ce">

**Comment by TwanLuttik** [comment]
Oh i see, I definitely will create a PR for this. This is something i explore for the first time but now i understand it.

**Comment by TwanLuttik** [comment]
PR has been created. https://github.com/katspaugh/wavesurfer.js/pull/2907

**Comment by TwanLuttik** [comment]
Tested and works.
https://github.com/katspaugh/wavesurfer.js/assets/19343894/4ade455e-4e7b-4251-b87b-f057534b542e

**Comment by katspaugh** [comment]
Thank you!
