### ISSUE TITLE
Difficulty configuring Jest to test code using Wavesurfer ESM modules

### ISSUE THREAD

**Issue by mflorence99** [katspaugh/wavesurfer.js#2903]
I have a solution to this issue, but it took me a while to find. I thought it might be useful to memorialize in case anyone else finds it helpful -- or can see I'm on the wrong track in the first place!

All my attempts to configure Jest for ESM failed. I finally got Jest to work by configuring `moduleNameMapper` to use the CommonJS modules instead:

```
  "moduleNameMapper": {
    ...
    "^wavesurfer\\.js$": "<rootDir>/node_modules/wavesurfer.js/dist/wavesurfer.min",
    "^wavesurfer\\.js/dist/plugins/regions$": "<rootDir>/node_modules/wavesurfer.js/dist/plugins/regions.min",
    "^wavesurfer\\.js/dist/plugins/timeline$": "<rootDir>/node_modules/wavesurfer.js/dist/plugins/timeline.min",
    ...
  },

```

I'm currently using `v7-beta8`. Just as a question, will this break in the final `v7` release?

**Comment by katspaugh** [comment]
So in your code you import ES modules, but Jest wants UMD modules? Maybe it has some config that you need to specify for it to use ES imports and not CommonJS require?
AFAIK Jest runs on Node which by default uses CommonJS.
Are you building the whole thing with webpack or rollup or some other tool?

**Comment by mflorence99** [comment]
Thanks for your speedy reply! Yes, my actual code is Typescript and, because I'm using Angular, its build pipeline uses Webpack and all that works well with WaveSurfer v7. 

You are correct that Jest runs on Node by default and therefore needs CommonJS modules.

It *does* have a set of complicated and experimental config options for ESM, none of which I could get to work with WaveSurfer. I'm happy with my solution, as long as it won't break with later versions of WaveSurfer -- ie: the `.min` versions are no longer CommonJS modules.

Thank you too for your great work!

**Comment by katspaugh** [comment]
Gotcha, thanks.

Last time I tried `require`'ing this package in  Node, it worked fine but it seems it's not the case anymore. It says:
```
const WaveSurfer = require('wavesurfer.js')
Uncaught:
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/ivan/Sites/wavesurfer/dist/wavesurfer.min.js not supported.
wavesurfer.min.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename wavesurfer.min.js to end in .cjs[...]
```

So I guess I'll rename the exported UMD file to `.min.cjs` for it to be happy.
