### ISSUE TITLE
How can I play audio stream with wavesurfer?

### ISSUE THREAD

**Issue by DvirH** [katspaugh/wavesurfer.js#291]
Is it support the range header to be sent while i'm seek?

**Comment by itsmrwave** [comment]
Hey @katspaugh,

Just seeking clarification (I've been researching on 206 Partial Content and I'm somewhat baffled on how I can improve performance i.e. reduce wait time). Does this mean that WaveSurfer will always download wait until the full audio file is downloaded before you can play? Even if the file is 60MB?

**Comment by itsmrwave** [comment]
@katspaugh Never mind. You've already [gotten so many questions on streaming](https://github.com/katspaugh/wavesurfer.js/search?q=stream&type=Issues&utf8=✓)! 👀

**Comment by katspaugh** [comment]
@itsmrwave yeah, thanks! I need to update the readme file. Just in case, the most recent answer is this:

> This is already the case if you set the backend parameter to MediaElement (see here: http://www.wavesurfer.fm/example/audio-element/). It will start playing as soon as you press play and will display a thin line instead of the waveform until it's ready.

**Comment by itsmrwave** [comment]
@katspaugh Yes. That was actually was the most helpful thread! I've learnt quite a bit by poking through the discussions in the issues. Thanks a lot! :+1:

**Comment by DivySrivastava** [comment]
var xhr = new XMLHttpRequest();
						xhr.open('GET', '/track/smth', true);
						xhr.responseType = 'arraybuffer';
						xhr.onload = function(e) { 
							console.log(xhr.response);
							var context = new AudioContext();
							context.decodeAudioData(xhr.response, function(buffer) {
								this.wavesurfer = WaveSurfer.create({
		            	xhr: { mode: "no-cors" },
		            	container: "#waveform",
		            	waveColor: "rgba(255, 42, 131, 0.5)",
		            	progressColor: "rgb(255, 42, 131)"
		          	});
								this.wavesurfer.loadDecodedBuffer(buffer);
				        this.wavesurfer.on("ready", function() {
									this.wavesurfer.play();
				          app.wavePlaying = true;
				          app.wavesurfer.play();
				        });
              }, null);
						};
						xhr.send();
          }```
```

This code will work for streaming using XMLHTTPRequest.
