### ISSUE TITLE
Wavesurfer not showing on IOS/Ionic/Angular

### ISSUE THREAD

**Issue by maximilien0405** [katspaugh/wavesurfer.js#2912]
Hi, i'm having a bit of a issue when compiling my Ionic (Angular) app to IOS. On the web, the waves are showing and i can do everything normaly, but as soon as i compile my app to IOS nothings shows up.

Web : 
<img width="399" alt="Screenshot 2023-06-18 at 19 47 42" src="https://github.com/katspaugh/wavesurfer.js/assets/46009279/ee21acc4-9c83-43a3-8fa8-ded3c4c3a414">

IOS : 
<img width="399" src="https://github.com/katspaugh/wavesurfer.js/assets/46009279/dd54c77d-db79-48fe-95c3-27c1f5c14573">

So, nothing shows up, exept maybe the container..
I have no idea what could cause this problem, and since there is not a lot of documentation/use cases of Wavesurfer with Ionic/Angular i tought you might be able to explain to me why this dosen't work..
Thanks !

Here is the code i'm using : 

_conversation.component.ts_
```ts
public wave: WaveSurfer;
url = '../../../assets/music.mp3';

onPreviewPressed(): void {
  if (!this.wave) {
    this.generateWaveform();
  }
  this.cdr.detectChanges();
  Promise.resolve().then(() => this.wave.load(this.url)).catch((res: any) => {
    console.log(res)
  });
}

onStopPressed(): void {
  this.wave.stop();
}

generateWaveform(): void {
  Promise.resolve(null).then(() => {
    this.wave = WaveSurfer.create({
      container: '#waveform',
      waveColor: 'violet',
      progressColor: 'purple',
      barWidth: 3,
      height: 50,
    });

    this.wave.on('ready', () => {
      this.wave.play();
    });
  });
}
```

_conversation.component.html_
```html
<div id="waveform"></div>
    
<div *ngIf="wave" class="controls">
  <button (click)="onStopPressed()">Stop</button>
</div>
<button (click)="onPreviewPressed()">Click me</button>
```

**Comment by katspaugh** [comment]
Looks like it never worked on Ionic.
Please search through the closed issues, this one indicates it worked in some version of Ionic but not in the 5th: https://github.com/katspaugh/wavesurfer.js/issues/761
I suggest that you ask in the Ionic community.
