### ISSUE TITLE
Wavesurfer on ready returns undefined as duration

### ISSUE THREAD

**Issue by 698373862** [katspaugh/wavesurfer.js#2914]
In your documentation
https://wavesurfer-js.org/docs/events there is an event `ready: [duration: number];`. However it doesn't return a duration number, instead it returns undefined. Is there mistake in the docs?

```js
wavesurfer.on('ready', (duration) => {
  console.log(duration) //undefined
})
```

This doesn't happen to me with other events such as audioprocess and it returns currentTime correctly.

**Comment by katspaugh** [comment]
Can you paste your entire code?

**Comment by 698373862** [comment]
> Can you paste your entire code?

https://jsfiddle.net/wn0f2kxm/

**Comment by katspaugh** [comment]
Prior to v7-beta, the ready event indeed didn't return anything. In your example, it's using wavesurfer v1.2.3.

Here's a v7 example: https://stackblitz.com/edit/typescript-4ggbcn?file=index.ts
