### ISSUE TITLE
X not calculated correctly when adding a region to the wavesurfer with padding.

### ISSUE THREAD

**Issue by harmadema** [katspaugh/wavesurfer.js#2919]
## Bug description
In the regions.ts the x isn't calculated correctly. 

## Environment
 - Browser: Chrome

## Minimal code snippet
Whenever you add padding to the wavesurfer element you see the effect:
https://wavesurfer-js.org/examples/#regions.js

**Comment by harmadema** [comment]
Why nog just set the start and end the same in the beginning? Inside regions.ts line::425

**Comment by katspaugh** [comment]
I'm actually not sure anymore what's going on in that code. Need to revisit it. Thanks for the report!

**Comment by katspaugh** [comment]
The end is set to something else to give the new region a small initial size because dragging kicks in only after you dragged the mouse at least 5 pixels.
I refactored it a little bit and fixed the bug.

**Comment by harmadema** [comment]
That's great to hear! Just tested it and it works fine now 😄
