### ISSUE TITLE
Wave form slightly stretched, causes lag with audio

### ISSUE THREAD

**Issue by chris-wm** [katspaugh/wavesurfer.js#292]
Great plugin, grateful for the effort that goes into it. Experiencing an issue when used on a live site, works perfectly on the my local demo.  The waveform is ever so slightly stretched which means that it loses some of it's sharpness and definition.  This also means that the waveform plays out of synch with the audio and this becomes more pronounced the longer that the track continues. Can see an example of the issue here: http://www.broadcastcomposers.com/mezzo/search/?query=&searchOptions=genreWmCinematic.  Any help would be appreciated, thanks

**Comment by katspaugh** [comment]
Please reopen if this is still relevant. Screenshots would be useful.

**Comment by thijstriemstra** [comment]
@echo66, still have those screenshots?
