### ISSUE TITLE
v7 Can't target scrollbar

### ISSUE THREAD

**Issue by jgentes** [katspaugh/wavesurfer.js#2933]
I think this doesn't work even using basic CSS, try using this sample code pasted into https://wavesurfer-js.org/examples/#styling.js:
```js
/*
  <html>
    <style>

      #waveform ::part(scroll)::-webkit-scrollbar {
        background-color: green;
        scrollbar-color: red;
        scrollbar-width: thin;
        width: 20px;
      }
    </style>

    <div id="waveform"></div>
  </html>
*/

import WaveSurfer from 'https://unpkg.com/wavesurfer.js@beta'

// Create an instance of WaveSurfer
const ws = WaveSurfer.create({
  container: '#waveform',
  waveColor: 'hotpink',
  progressColor: 'paleturquoise',
  cursorColor: '#57BAB6',
  cursorWidth: 4,
  url: '/examples/audio/audio.wav',
})

ws.on('decode', () => {
  ws.zoom(200)
})
```

Any chance you could take a look?

_Originally posted by @jgentes in https://github.com/katspaugh/wavesurfer.js/discussions/2798#discussioncomment-6031840_

**Comment by katspaugh** [comment]
Sorry, missed your original message. I'll take a look!

**Comment by katspaugh** [comment]
It doesn't work indeed. As a workaround for now you can attach styles directly to the wrapper like this:
```
const style = document.createElement('style')
style.textContent = `::-webkit-scrollbar { background: green; }`
wavesurfer.getWrapper().appendChild(style)
```

**Comment by jgentes** [comment]
Thanks, I had tried working with the shadowRoot directly using querySelector but couldn't get it going. `getWrapper` did the trick - that works for me!

**Comment by Samandar0021305** [comment]
But it doesn't work on Safari, more specifically, how do you make the hover?
@katspaugh
