### ISSUE TITLE
Bug: destroy not working as expected when changing audio url too quickly

### ISSUE THREAD

**Issue by IdoBouskila** [katspaugh/wavesurfer.js#2940]
## Bug description
If it's 'autoplay: true' and the audio url is changed too quickly, the wavesurfer instance is not destroyed, which results in multiple audios instead of destroying the old instance and creating a new one with the updated url.

In order to demonstrate the bug, I have provided a video below and a code using React.js.

## Environment
 - Browser: Firefox and Chrome

## Minimal code snippet
https://codesandbox.io/s/wavesurfer-js-change-song-bug-ylf48s?file=/src/App.js

## Expected result
The audio url should be changed and the previous wavesurfer instance destroyed, instead of multiple audios being used

## Obtained result
Multiple audios 

## Video
https://vimeo.com/839866689?share=copy

**Comment by katspaugh** [comment]
It's most likely a bug in the hook that creates/destroys a wavesurfer instance. 
Your code is based on the [React example](https://wavesurfer-js.org/examples/#react.js) which is just that, an example. If you manage to figure it out, please feel free to make a PR.

Ideally, it shouldn't even create and destroy a new instance on every render. It should instead reuse the same instance and call `load()` to set a new URL, and `setOptions` to set new visual props.

**Comment by katspaugh** [comment]
That said, I did notice an inconsistency in the destroy method of the player, will create a PR to address it shortly.

**Comment by IdoBouskila** [comment]
> That said, I did notice an inconsistency in the destroy method of the player, will create a PR to address it shortly.

Yeah, I had a feeling that the problem was in the `destroy` method.
Thank you for the quick answer, waiting for merge!  🙏🏼
