### ISSUE TITLE
Regions: minLength, maxLength, resize options not working/buggy

### ISSUE THREAD

**Issue by maddestscooter** [katspaugh/wavesurfer.js#2946]
## Bug description
Setting minLength & maxLength options for Region seems to have no effect whatsoever. Setting resize: false will still allow the user to resize the Region by dragging it to either end or "shaking" within the waveform container.   

## Environment
 - Browser: Chrome

## Minimal code snippet
ws.on('decode', () => {
  wsRegions.addRegion({
    start: 0,
    end: 30,
    minLength: 30,
    maxLength: 30, 
    content: 'First region',
    color: randomColor(),
    resize: false,
    drag: true,
  })

## Expected behaviour
The user should not be able to resize the region under or above 30 seconds. The user should not be able to alter the region duration at all. 

## Obtained result
The user is still able to resize the region duration without any limits regardless if resize is set to false and/or min/maxLength is set to certain values.

**Comment by katspaugh** [comment]
Does it say anywhere in the docs that Regions support minLength and maxLength?

**Comment by maddestscooter** [comment]
I can see them mentioned in the options here https://wavesurfer-js.org/plugins/regions but perhaps I have misunderstood

**Comment by katspaugh** [comment]
Oh, I see. That's an old page refers to the v6 version. It's not linked anywhere on the website but it's still googlable apparently. I'll update it.

As for resizing happening when dragging over the edge, it's a bug indeed. Thanks for the report.
