### ISSUE TITLE
 After right-clicking, the playback section follows whenever the mouse pointer is moved.

### ISSUE THREAD

**Issue by siosio34** [katspaugh/wavesurfer.js#2963]
## Bug description

After right-clicking, the playback section follows whenever the mouse pointer is moved.
This is not the behavior I want. Even after right-clicking, I want to move to that section whenever I click as I want.
I will attach a reproduction video from the example code.

https://github.com/katspaugh/wavesurfer.js/assets/7166022/55a70155-ca6e-4424-be0e-07abb3e68f8f

## Environment
 - Browser: Chrome

## Expected result
Even if you right-click the mouse I want to move to that section whenever I click as I want

## Obtained result
After right-clicking, the playback section follows whenever the mouse pointer is moved

**Comment by katspaugh** [comment]
Oof, that's definitely not the behavior we want :)
Thanks for the report!

**Comment by siosio34** [comment]
thanks @katspaugh !
