### ISSUE TITLE
MinLength and MaxLength of the Regions don't work (also not on the demo site)

### ISSUE THREAD

**Issue by Artur-Galstyan** [katspaugh/wavesurfer.js#2968]
## Bug description
On the regions demo:

https://wavesurfer-js.org/examples/#regions.js

the "Cramped Region" has a max length of 10, but you can make it much bigger than 10 seconds. Also, the RegionParams don't even include minLength and maxLength:

```typescript
export type RegionParams = {
    id?: string;
    start: number;
    end?: number;
    drag?: boolean;
    resize?: boolean;
    color?: string;
    content?: string | HTMLElement;
};
```

## Environment
 - Browser: Chrome

**Comment by katspaugh** [comment]
Thanks for letting me know! The site was updated with the latest example, but not the wavesurfer package. I've now pushed beta.13 where min/maxLength were added.

**Comment by katspaugh** [comment]
[Beta 13 is now out](https://github.com/katspaugh/wavesurfer.js/releases/tag/7.0.0-beta.13) and unpkg has already picked it up. The site works as expected now. Thanks!
