### ISSUE TITLE
About babel question.

### ISSUE THREAD

**Issue by tinyRipple** [katspaugh/wavesurfer.js#2969]
## Bug description

Hello, when I use wavesurfer in a simple react project, I miss this question.

<img width="645" alt="image" src="https://github.com/katspaugh/wavesurfer.js/assets/69381867/d6fbab52-1ae3-4acd-a864-89804f0794aa">

## Environment

 - Browser: Chrome
 - react: 18
 - wavesurfer: 7.0.0-beta.13

## Minimal code snippet

```js
/* eslint-disable import/extensions */
import React from 'react';
import WaveSurfer from 'wavesurfer.js';
import RecordPlugin from 'wavesurfer.js/dist/plugins/record';

import Button from 'basic/Button';

const waveSurfer = WaveSurfer.create({
  container: '.audio-record-container',
  height: 24,
  splitChannels: false,
  normalize: false,
  waveColor: '#e8eaed',
  progressColor: '#263030',
  cursorColor: '#ddd5e9',
  cursorWidth: 2,
  barWidth: 2,
  barGap: 4,
  barRadius: 100,
  barHeight: null,
  barAlign: '',
  minPxPerSec: 1,
  fillParent: true,
  media: {},
  autoplay: false,
  interact: true,
  hideScrollbar: false,
  audioRate: 1,
  autoScroll: true,
  autoCenter: true,
  sampleRate: 8000,
});
const record = waveSurfer.registerPlugin(RecordPlugin.create());

const AudioRecord = () => {
  return (
    <div className="audio-record">
      <div className="audio-record-container" />
      <Button>Save</Button>
      {/* <Button
        onCLick={() => {
          record.startRecording().then(() => {
            console.log('success');
          });
        }}
      >
        Record
      </Button> */}
      <Button>Cancel</Button>
    </div>
  );
};

export default AudioRecord;
```

## Expected result

Compile successfully.

## Obtained result

Above issue.

**Comment by katspaugh** [comment]
Looks like your compiler (Babel?) is targeting a lower JavaScript version that doesn’t have the optional chaining operator (`?`).
Could you paste your Babel config?

**Comment by tinyRipple** [comment]
Sure.
```json
"babel": {
    "presets": [
      "react-app"
    ]
  },
```

**Comment by katspaugh** [comment]
Gotcha, thanks. Looks like it's basically the default + JSX.
I'm going to change our compilation target to ES6 (currently it's ES2021), hopefully that'll work everywhere.

**Comment by tinyRipple** [comment]
Yeah, thank you for your support.
But one thing, the current issue seems to be my personal project's issue, because when I recreate a new react project and use the same code to test again, it works fine.
Of course, if you are willing to compile to es6, I believe this is an excellent thing.

**Comment by katspaugh** [comment]
True, the babel config looks quite old too. I didn't have this issue with the latest Babel and a default config.

But anyway, I guess ES6 is safer either way.
