### ISSUE TITLE
Region Plugin: Drag not working (even in the site example)

### ISSUE THREAD

**Issue by Artur-Galstyan** [katspaugh/wavesurfer.js#2978]
## Bug description
In the examples (here: https://wavesurfer-js.org/examples/#regions.js) if you change the second marker like so:

```typescript
wsRegions.addRegion({
    start: 20,
    content: 'Second markerrrr',
    color: randomColor(),
    drag: true
  })
```

Then you still cannot drag the region!

## Environment
 - Browser: Chrome

**Comment by Artur-Galstyan** [comment]
It seems that this only happens if you have only set "start" and not "end".

**Comment by Artur-Galstyan** [comment]
Interestingly, if the region is too small, the dragging is disabled. For instance, this can be dragged:

```typescript
wsRegions.addRegion({
    start: 20,
    end: 20.01,
    resize: false,
    content: 'Second markerrrr',
    color: randomColor(),
    drag: true
  })
```

But this cannot be dragged:

```typescript
wsRegions.addRegion({
    start: 20,
    end: 20.001,
    resize: false,
    content: 'Second markerrrr',
    color: randomColor(),
    drag: true
  })
```

The key difference is, that if the region has 0.001 "duration", I guess it rounds it down to 0 and then stops working.

**Comment by katspaugh** [comment]
That was actually an important use case that I missed in #2957. Regions can have no length but they should be still draggable. Fixed in the PR linked above.
