### ISSUE TITLE
Should the click event for the waveform also fire on the click event for regions?

### ISSUE THREAD

**Issue by killia15** [katspaugh/wavesurfer.js#3010]
## Bug description

In previous version of Wavesurfer if the click event for a region was fired, the click event for wavesurfer wouldn't also be fired. We need to be able to active a region when it's clicked on. We also have it so that clicking on the waveform deactivates an active region. 

## Environment
 - Browser: Chrome

## Minimal code snippet
```
waveSurfer.on('click', () => {
   console.log('also fires on region click');
});

wsRegions.on('region-clicked', (region) => {
   console.log('region clicked');
});
```

## Expected result
Wavesurfer's click event should not fire when the region's click event does.

**Comment by killia15** [comment]
Actually I see that we can use the event and stop propagation. Never mind!

**Comment by katspaugh** [comment]
Yep, I intentionally left this open-ended in case you want your regions resizable and draggable but pass through clicks. Or stop propagation like on your case. Thanks for pointing this out and figuring out the solution.
