### ISSUE TITLE
Regions don't stop playing

### ISSUE THREAD

**Issue by killia15** [katspaugh/wavesurfer.js#3011]
## Bug description
Playing a region used to start at the beginning and end at the end. It looks like the play method on wavesurfer lost the start and end parameters. 
 
## Environment
 - Browser: Chrome

## Minimal code snippet
This is the current code in the regions plugin:
```
      region.on('play', () => {
        this.wavesurfer?.play()
        this.wavesurfer?.setTime(region.start)
      }),
```
And the play method of the player.js file:

```
  /** Start playing the audio */
  public play(): Promise<void> {
    return this.media.play()
  }
  ```
  
This is from v6 in the regions plugin:
```
    play(start) {
        const s = start || this.start;
        this.wavesurfer.play(s, this.end);
        this.fireEvent('play');
        this.wavesurfer.fireEvent('region-play', this);
    }
```

Old v6:
```
    /**
     * Starts playback from the current position. Optional start and end
     * measured in seconds can be used to set the range of audio to play.
     *
     * @param {?number} start Position to start at
     * @param {?number} end Position to end at
     * @emits WaveSurfer#interaction
     * @return {Promise} Result of the backend play method
     * @example
     * // play from second 1 to 5
     * wavesurfer.play(1, 5);
     */
    play(start, end) {
        if (this.params.ignoreSilenceMode) {
            // ignores device hardware silence mode
            util.ignoreSilenceMode();
        }

        this.fireEvent('interaction', () => this.play(start, end));
        return this.backend.play(start, end);
    }
    ```

Is there a way that we could bring back the optional start and stop parameters or at least figure out how to ensure that the regions don't continue playing?

**Comment by killia15** [comment]
It looks like there was logic for handling this with HTML5 audio in v6. Maybe we could bring it back?

```
    /**
     * Plays the loaded audio region.
     *
     * @param {number} start Start offset in seconds, relative to the beginning
     * of a clip.
     * @param {number} end When to stop, relative to the beginning of a clip.
     * @emits MediaElement#play
     * @return {Promise} Result
     */
    play(start, end) {
        this.seekTo(start);
        const promise = this.media.play();
        end && this.setPlayEnd(end);

        return promise;
    }

    /**
     * Set the play end
     *
     * @param {number} end Where to end
     */
    setPlayEnd(end) {
        this.clearPlayEnd();

        this._onPlayEnd = time => {
            if (time >= end) {
                this.pause();
                this.seekTo(end);
            }
        };
        this.on('audioprocess', this._onPlayEnd);
    }
    ```

**Comment by katspaugh** [comment]
I’m a little apprehensive of carrying this over to v7. The old version had to have scheduling because that’s what Web Audio required anyway. V7 is more or less stateless and relies on the media element for tracking time.

I would definitely fix this in Regions though. I.e. stop at the end, and maybe an option to loop or continue playing further.

**Comment by killia15** [comment]
Makes sense if the scheduling was pulled out. You could set a timeout to stop playing at the duration of the region, but I'm not sure how stable that would be.

**Comment by katspaugh** [comment]
A timeout would definitely not be accurate by any means. I would use the `region-out` event to detect when we reach the end of a region. And then either stop or loop. Similar to how it's done in the [regions example](https://wavesurfer-js.org/examples/#regions.js).

**Comment by japostoles** [comment]
I've tried implementing a "play clip" method, similar to how the play() method worked before, using region-out as described, but I'm running into an issue.

If multiple regions share the same end point, an event for only one of the regions is fired.  

Are there any other suggestions for implementing a play method that stops at a predefined point?

**Comment by japostoles** [comment]
@killia15 I was able to get similar functionality by using setTime() to move the playhead to the start of the region, and then adding a `timeupdate` handler to handle the pausing. 

```
function playRegion(start: number, end: number) {
    let handler = function(current: number) {
        if (current > end) {
            wavesurfer.pause()
            wavesurfer.un('timeupdate', handler)
        }
    }

    wavesurfer.setTime(start)
    wavesurfer.on('timeupdate', handler)
    wavesurfer.play()
}

```

**Comment by katspaugh** [comment]
I've decided not to change the play function behavior at this point because the new version with this new behavior has already been out for a while.

Stopping a region at its end can be easily achieved with the region-out event like so:

```js
            const region = wsRegions.addRegion({ ... })

            wavesurfer.once('region-out', (reg) => {
              if (reg === region) {
                this.wavesurfer?.pause()
              }
            })
```
