### ISSUE TITLE
Failed to execute 'start' on 'AudioBufferSourceNode'

### ISSUE THREAD

**Issue by dennisdevulder** [katspaugh/wavesurfer.js#302]
I have my audio editing tool working for FireFox and when checking for chrome compatibility I run into the error output stated in the title.

this is my code:

```
function create_wavesurfer(id, source){
  var instance = Object.create(WaveSurfer);

  instance.init({
    container: document.querySelector("#timeline_" + id),
    waveColor: '#EDC5AA',
    progressColor: '#E88E4B',
    scrollParent: true,
    minPxPerSec: 60
  })

  instance.on('ready', function(){
    instance.play();
  })

  instance.load(source);
}
```

when the play() is called the error is triggered.

Chrome Version 39.0.2171.71 (64-bit)

Any ideas?

EDIT: 
Full output: Uncaught InvalidStateError: Failed to execute 'start' on 'AudioBufferSourceNode': Offset must be a finite non-negative number: -0.702404

**Comment by cskonopka** [comment]
I'm also experiencing the same issue with multiple waveforms and I can't necessarily reinstall due to custom code. Any thoughts on what it could be?
