### ISSUE TITLE
Reference error: self is not defined

### ISSUE THREAD

**Issue by Johnrobmiller** [katspaugh/wavesurfer.js#3021]
This error is back again with Next 13, and the solutions provided no longer work: https://github.com/katspaugh/wavesurfer.js/issues/2350

**Comment by katspaugh** [comment]
Could you paste your tsconfig, next config and the how you import the library in your code?

**Comment by katspaugh** [comment]
I've tested in a Next.js/TypeScript project and the import works correctly in v7.
