### ISSUE TITLE
The AudioContext was not allowed to start.

### ISSUE THREAD

**Issue by DogukanTuncay** [katspaugh/wavesurfer.js#3044]
I saw this error's issue but I can't solving . My error:
The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page

Browser:Brave v1.56.11 Chromium:115.0.5790.102

Html Code:
<script type="text/javascript"src="https://unpkg.com/wavesurfer.js@7/dist/wavesurfer.min.js"></script>
<script src="{{asset('js/wavesurfer.js')}}"></script>

 <div class="row">
               <div id="waveform"></div>
                      <div class="player-wrap">
                                     <div id="audiowave"></div>
                                            <div class="audio-controls">
                                                <div  class="btn btn-toggle-pause">
                                                    <i class="fa fa-play"></i> <i class="fa fa-pause"></i>
                                                </div>
                                                <div class="btn btn-stop">
                                                    <i class="fa fa-stop"></i>
                                                </div>
                                         </div>
                                  </div>
                     </div>
               </div>     
</div>
Wavesurfer Code:

var wavesurfer = WaveSurfer.create({
    container: '#waveform',
    waveColor: "#5df9de",
    progressColor: "#1e594f",
    height: 150,
    responsive: true,
    hideScrollbar: true,
    cursorColor: "#5df9de",
    cursorWidth: 2,
    barWidth: 5,
    barGap: 1.5,
    skipLength: 5,
    url: '../../../audio/bass.mp3'
});
$(".btn-toggle-pause").on("click", function() {
    wavesurfer.playPause();

});
$(".btn-stop").on("click", function() {
    wavesurfer.setTime(0);
    wavesurfer.stop();
});

![image](https://github.com/katspaugh/wavesurfer.js/assets/104570289/e7d54fcf-9a5b-4713-8291-26989e233e4a)

**Comment by katspaugh** [comment]
Is this happening only in Brave for you?

**Comment by DogukanTuncay** [comment]
> Is this happening only in Brave for you?

No, every browser is same. I solved error with these:
HTML:
<div id="see-audio" class=" btn btn-success">AUDIO DETAILS</div>
                                        <div id="audio-details" class="player-wrap">
                                            <div id="audiowave"></div>
                                            <div class="audio-controls">
                                                <div  class="btn btn-toggle-pause">
                                                    <i class="fa fa-play"></i> <i class="fa fa-pause"></i>
                                                </div>
                                                <div class="btn btn-stop">
                                                    <i class="fa fa-stop"></i>
                                                </div>


                                            </div>
                                        </div>
  JAVASCRIPT
  
document.getElementById("audio-details").style.display = "none";

$("#see-audio").on("click",function(){
    document.getElementById("audio-details").style.display = "block";

    var wavesurfer = WaveSurfer.create({
        container: '#waveform',
        waveColor: "#5df9de",
        progressColor: "#1e594f",
        height: 150,
        responsive: true,
        hideScrollbar: true,
        cursorColor: "#5df9de",
        cursorWidth: 2,
        barWidth: 5,
        barGap: 1.5,
        skipLength: 5,
    });
    wavesurfer.load('../../../audio/bass.mp3');
    $(".btn-toggle-pause").on("click", function() {
        wavesurfer.playPause();

    });
    $(".btn-stop").on("click", function() {
        wavesurfer.setTime(0);
        wavesurfer.stop();
    });
    document.getElementById("see-audio").style.display = "none";


});
//////////////////////////////////////////
But I cant see waves now.  There isnt error or any warning.   Should I open new issue ?
