### ISSUE TITLE
Wave made by record plugin not playing full audio

### ISSUE THREAD

**Issue by LeeYoungIn** [katspaugh/wavesurfer.js#3049]
## Bug description
Wave is not playing till the end with using Record plugin.

## Environment
 - Browser: Chrome

## Expected result
Wave should play till the end of the recorded audio.

## Screenshots
<img width="648" alt="image" src="https://github.com/katspaugh/wavesurfer.js/assets/9003864/4cf5fc0a-1289-415e-abc9-b434b96bb8fe">

**Comment by stefanholzapfel** [comment]
I guess its connected with https://github.com/katspaugh/wavesurfer.js/issues/2890?

**Comment by katspaugh** [comment]
Something similar but 100% the same.

**Comment by katspaugh** [comment]
Specifying a specific bit rate solves that issue for the Recorder plugin:

E.g.
```js
RecordPlugin.create({
  audioBitsPerSecond: 12800,
})
```

So I'm going to add a default value for `audioBitsPerSecond` if it's not specified.
