### ISSUE TITLE
Setting the regions start freezes the region

### ISSUE THREAD

**Issue by Artur-Galstyan** [katspaugh/wavesurfer.js#3050]
## Bug description

Lets say you have a point after which a marker must not be dragged, e.g. at s = 10. If the user drags the marker to before this point, the marker should be placed to s = 11 e.g. But doing that freezes the marker. In code:

```typescript
regions.forEach((region, index) => {
		region.on('update', () => {
			if (region.start > SOME_END_VALUE) {
				region.start = SOME_END_VALUE - 1;
				console.log('Went past end');
			}
			if (region.start < SOME_START_VALUE) {
				console.log('Went past start');
                                // trying different syntax...
				region.setOptions({
					start: SOME_START_VALUE + 2,
					end: region.end, // tried to set end, but this also doesn't work.
					drag: true // explicitly setting drag=true, but doesn't help
				});
			}
		});
		region.on('click', () => {
			console.log('Clicked region'); // click event is fired still
		});
	});

```
As you can see, the click event is still fired. But it cannot be moved. Funnily, the region can still be moved when the first IF is triggered. So it works at the END, but not at the START? Even if I just have the second condition or change the event to `update-end` it doesn't work. (`update-end` even works "worse" since the marker's start position is changed, but it's not updated in the waveform until I move the marker again. Since I can't move the marker if it is belove `SOME_START_VALUE`, it's stuck). This is what I mean:
<img width="162" alt="image" src="https://github.com/katspaugh/wavesurfer.js/assets/63471891/1021da80-3ffd-4625-8b9b-cf1a7d64941f">

The purple marker is the one I moved. Now it's stuck.

## Environment
 - Browser: Chrome

**Comment by Artur-Galstyan** [comment]
I think I found the root of this bug. It's when you set the start value to a higher value than it's currently at, then it freezes! I.e. when you change it to:

```typescript
start: SOME_START_VALUE - 10 // smaller value than current region.start value
```

then it doesn't freeze.

**Comment by Artur-Galstyan** [comment]
Workaround discovered:

```typescript
region.setOptions({
					start: selectedSection.start + 3,
					drag: true
				});
				region.setOptions({
					start: selectedSection.start - 2,
					drag: true
				});
```

**Comment by katspaugh** [comment]
Thanks for the report!

**Comment by Artur-Galstyan** [comment]
Another weird bug occurs with this part:

```typescript
if (region.start > SOME_END_VALUE) {
    region.start = SOME_END_VALUE - 1;
    console.log('Went past end');
}
```

It actually stretches the "grabbox" of the marker:

![ezgif com-video-to-gif](https://github.com/katspaugh/wavesurfer.js/assets/63471891/d6034bad-0caf-40f7-b481-a0d3de855de2)

**Comment by katspaugh** [comment]
I've made a minimalistic example based on your code and it doesn't have this issue: https://wavesurfer-js.org/examples/#09060f977d8cfbadaf85dc3242abd0bb

Try to debug your application code and see what exactly causes the freezing.

**Comment by Artur-Galstyan** [comment]
Hi, maybe I should have created 2 separate issues. I've modified your code and now the stretching of the grabbox happens (which is bug 1):
```typescript
// Regions plugin

import WaveSurfer from 'https://unpkg.com/wavesurfer.js@7.0.6/dist/wavesurfer.esm.js'
import RegionsPlugin from 'https://unpkg.com/wavesurfer.js@7/dist/plugins/regions.esm.js'

// Create an instance of WaveSurfer
const ws = WaveSurfer.create({
  container: document.body,
  waveColor: 'rgb(200, 0, 200)',
  progressColor: 'rgb(100, 0, 100)',
  url: '/examples/audio/audio.wav',
})

// Initialize the Regions plugin
const wsRegions = ws.registerPlugin(RegionsPlugin.create())

// Create some regions at specific time ranges
ws.on('decode', () => {
  const region = wsRegions.addRegion({
    start: 2,
    end: 2,
    content: 'Region',
    color: 'rgba(200, 0, 0, 0.5)',
  })

  region.on('update', () => {
    if (region.end > 20) {
      region.setOptions({
        start: 19,
      })
    }
  })
})
```

And in this example:

```typescript
// Regions plugin

import WaveSurfer from 'https://unpkg.com/wavesurfer.js@7.0.6/dist/wavesurfer.esm.js'
import RegionsPlugin from 'https://unpkg.com/wavesurfer.js@7/dist/plugins/regions.esm.js'

// Create an instance of WaveSurfer
const ws = WaveSurfer.create({
  container: document.body,
  waveColor: 'rgb(200, 0, 200)',
  progressColor: 'rgb(100, 0, 100)',
  url: '/examples/audio/audio.wav',
})

// Initialize the Regions plugin
const wsRegions = ws.registerPlugin(RegionsPlugin.create())

// Create some regions at specific time ranges
ws.on('decode', () => {
  const region = wsRegions.addRegion({
    start: 10,
    content: 'Region',
    color: 'rgba(200, 0, 0, 0.5)',
  })

  region.on('update', () => {
    if (region.start < 4) {
      region.setOptions({
        start: 5,
      })
    }
  })
})
```

the freezing still happens (which is bug 2).

**Comment by katspaugh** [comment]
Oh, I see.

1. Stretching is the expected behavior when you update only the start point. It will keep the old `end` position. You need to update both start and end if you want to move a region.
2. I've replicated the marker freezing and will fix that. The reason is that markers inherently have an end position which is equal to the start position, but it's not automatically updated when `start` is updated.

**Comment by katspaugh** [comment]
Hey @Artur-Galstyan, thanks for the sponsorship, I appreciate it!

**Comment by Artur-Galstyan** [comment]
It's not much, no need to mention it:)
