### ISSUE TITLE
isPlaying() gives wrong value initially

### ISSUE THREAD

**Issue by stefanholzapfel** [katspaugh/wavesurfer.js#3054]
## Bug description
When you check the wavesurfer's isPlaying method directly after starting the playback, you get "false", because the media's "currentTime" is still 0. Why do you check for the currentTime in the isPlaying method?

**Comment by katspaugh** [comment]
As clarified [here](https://github.com/katspaugh/wavesurfer.js/discussions/3048), this is the expected behavior as per the MediaElement spec.
