### ISSUE TITLE
`audioRate` does not set playback speed

### ISSUE THREAD

**Issue by stevebauman** [katspaugh/wavesurfer.js#3058]
## Bug description
When you create a new Wavesurfer instance with an `audioRate`, that value does not set the playback speed.

## Environment
 - Browser: Chrome

## Minimal code snippet

```js
import WaveSurfer from 'https://unpkg.com/wavesurfer.js@7/dist/wavesurfer.esm.js'

const wavesurfer = WaveSurfer.create({
  audioRate: 2,
  container: document.body,
  url: '/examples/audio/audio.wav',
})

wavesurfer.once('interaction', () => {
  wavesurfer.play()
})
```

## Reproduce

1. Go to the **Basic** example on the Wavesurfer JS website (https://wavesurfer-js.org/examples/#basic.js)
2. Add the `audioRate` option (set it to anything other than 1)
3. Interact with the waveform
4. The audio does not play at the rate given in the constructor

**Comment by katspaugh** [comment]
Looks like it only works correctly after the audio has loaded sufficiently or is cached to begin with.
