### ISSUE TITLE
detectRegions

### ISSUE THREAD

**Issue by shsavage** [katspaugh/wavesurfer.js#307]
I'm working on implementing the detectRegions function from the regions plugin.  I've pulled the loadRegions and detectRegions functions out of the regions example and dropped them into my javascript file, and replaced 
" var peaks = wavesurfer.backend.peaks;" with "var peaks = wavesurfer.backend.getPeaks();" in detectRegions.  When it runs I get an "invalid arguments" error on line 325 in wavesurfer.min.js:

for (var e = this.buffer, i = e.length / t, r = ~~(i / 10) || 1, s = e.numberOfChannels, a = new Float32Array(t), n = 0; s > n; n++)

Any ideas?

**Comment by maxehnert** [comment]
@katspaugh hey I was just looking over this and I'm trying to get a grasp on what is going on. 

Is ```extractRegions()``` supposed to automagically find and highlight all the peaks in the audio file within set params? 
I'm trying to call ```extractRegions()``` with some params but all I get back is an empty array. I have uncommented out this section: 
```
loadRegions(
                extractRegions(
                    wavesurfer.backend.getPeaks(512),
                    wavesurfer.getDuration()
                )
            );
```
from the regions example. Is there something else I am missing or am I interpreting this function incorrectly?

**Comment by katspaugh** [comment]
Hi Max!

The function finds regions separated by silence. Like separate utterances in speech.

I'm not sure what's missing in your code. Are you trying on the Akutagawa story audio file or your own?

**Comment by maxehnert** [comment]
I have my own file. I'm working with heart sounds. The peaks in my files are only about 0.1 seconds long and often shorter.

**Comment by katspaugh** [comment]
Then you may need to set the `minSeconds` variable to 0.

**Comment by shsavage** [comment]
The only time that variable is used that I can see is in the segmentation
of the audio track into regions.  I'm talking about just changing the
cursor when it's hovering over the annotation marker, which is a region of
no length.  Currently, I'm using this line to add a region as an annotation
marker:

            wavesurfer.addRegion({id: '1', start: ohp.myStart, loop: false,
drag: false, resize: false, color: 'rgba(0,128,0,1)'});

What would happen if I gave it an end option with the same location (end:
ohp.myStart)?

-s

On Fri, Apr 3, 2015 at 1:32 PM, katspaugh <notifications@github.com> wrote:

> Then you may need to set the minSeconds variable to 0.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/katspaugh/wavesurfer.js/issues/307#issuecomment-89411684>
> .
>



-- 
Stephen H. Savage, PhD.
Scientific Software Engineer
OKED/IHR
Arizona State University
Box 876505
Tempe, AZ 85287-6505

Affiliated Investigator - CISA3 Archaeology,
Center of Interdisciplinary Science for Art, Architecture and Archaeology,
Qualcomm Institute, University of California, San Diego

Senior Fellow, George Washington University, Capitol Archaeological
Institute
http://research.columbian.gwu.edu/archaeology/people/150

shsavage@asu.edu
http://gaialab.asu.edu/home

**Comment by maxehnert** [comment]
@shsavage I'm not sure if you were responding to me but I'm doing this with a button to create a marker
```
wavesurfer.addRegion({start: wavesurfer.getCurrentTime(), end: wavesurfer.getCurrentTime() + 0.004, color: 'RGBA(91, 199, 0, 1)', height:'50px'}, saveRegions);
```
If I don't add the 0.004 to the end then nothing shows up since it has no width. 

@katspaugh ```minSeconds``` gets built into ```minLen``` which is only used for filtering silence and region segments 

Just to clarify my original question. Am I correct to assume that calling ```extractRegions()``` is supposed to locate all the peaks in the file that meet the correct params and add regions to them?

**Comment by katspaugh** [comment]
That's another topic, but to create a marker, just don't specify *any* end and it should work.

Back to `extractRegions`, it is supposed to locate continuous segments of audio signal of high intensity, separated by segments of continuous signal of lower intensity ("silence"). The threshold of the intensity is set in the variable `minValue`.

**Comment by maxehnert** [comment]
Thanks @katspaugh I will try some more this week with the extractRegions and see if I can get something working.
