### ISSUE TITLE
broke wavesurfer.cursor.js

### ISSUE THREAD

**Issue by redimongo** [katspaugh/wavesurfer.js#3077]
## Bug description
We use wavesurfer.cursor.js and seems the unpkg has been removed https://unpkg.com/wavesurfer.js/dist/plugin/wavesurfer.cursor.js

get this error **Cannot find "/dist/plugin/wavesurfer.cursor.js" in wavesurfer.js@7.1.1**

**Comment by katspaugh** [comment]
Sorry that it happened.

You should add `@6` to your unpkg scripts if you want to continue using v6. Otherwise please see the upgrade guide for v7 in the readme. Cheers!

https://unpkg.com/wavesurfer.js@6/dist/plugin/wavesurfer.cursor.js
