### ISSUE TITLE
Waveform peak smoothing/rendering changed between v6 & v7

### ISSUE THREAD

**Issue by stevebauman** [katspaugh/wavesurfer.js#3082]
## Bug description
When bars mode is disabled, the waveform generated no longer generates smooth transitions between peaks, and also leaves gaps between peaks, unlike v6. Is there a way I can restore the old rendering behaviour in v7?

**v6**:
<img width="1435" alt="Screenshot 2023-08-04 at 12 05 23 PM" src="https://github.com/katspaugh/wavesurfer.js/assets/6421846/08f6b588-e876-41a6-a63c-2fc22741f23c">

```js
this.waveSurfer = WaveSurfer.create({
    normalize: true,
    responsive: true,
    audioRate: this.speed,
    backend: 'MediaElement',
    waveColor: '#8eacff',
    progressColor: '#738cad',
    height: this.compact ? 80 : 128,
    container: this.$refs.waveform,
    plugins: this.makeWaveSurferPlugins(),
});
```

**v7**:
![Screenshot 2023-08-04 at 11 55 11 AM](https://github.com/katspaugh/wavesurfer.js/assets/6421846/ed62a70d-c44d-40c5-aa92-ce4e408e81c6)

```js
this.waveSurfer = WaveSurfer.create({
    normalize: true,
    audioRate: this.speed,
    waveColor: '#8eacff',
    progressColor: '#738cad',
    height: this.compact ? 80 : 128,
    container: this.$refs.waveform,
    plugins: this.makeWaveSurferPlugins(),
});
```

---

**Comment by katspaugh** [comment]
Looks like a clear-cut bug indeed.

Are you using pre-decoded peaks? If so, what's the size of the array?

**Comment by stevebauman** [comment]
Hi @katspaugh! Sorry for the late reply, and thank you so much for your quick response 🙏 

Yes I'm using pre-decoded peaks built from [wav2json](https://github.com/beschulz/wav2json). It is exactly 800 elements in length:

<details>
<summary>JSON</summary>
<pre>
{
    "_generator": "wav2json version 0.4 on Darwin (http://goo.gl/af7wg)",
    "mid": [
        0.00793457,
        0.00650024,
        0.00793457,
        0.00854492,
        0.056488,
        0.0951843,
        0.0927124,
        0.117706,
        0.0935059,
        0.101868,
        0.116669,
        0.120667,
        0.0878906,
        0.0785217,
        0.118195,
        0.0892029,
        0.0234985,
        0.0922241,
        0.0748291,
        0.0802002,
        0.00521851,
        0.00491333,
        0.00488281,
        0.00521851,
        0.00454712,
        0.0155945,
        0.112915,
        0.0874329,
        0.0978394,
        0.0818176,
        0.0556946,
        0.0986328,
        0.0610046,
        0.138214,
        0.0829163,
        0.0852661,
        0.083252,
        0.102478,
        0.0795898,
        0.116364,
        0.0956116,
        0.11145,
        0.0948792,
        0.0975342,
        0.104584,
        0.0739441,
        0.142548,
        0.125153,
        0.080719,
        0.0707703,
        0.0587463,
        0.0282593,
        0.072998,
        0.0380554,
        0.0262756,
        0.0050354,
        0.0065918,
        0.014801,
        0.0157776,
        0.0153809,
        0.0129089,
        0.0110474,
        0.00915527,
        0.00790405,
        0.00567627,
        0.0104065,
        0.140564,
        0.240662,
        0.178162,
        0.415863,
        0.46225,
        0.481903,
        0.337006,
        0.128784,
        0.0249329,
        0.354126,
        0.33667,
        0.337616,
        0.499817,
        0.458801,
        0.417938,
        0.225983,
        0.311188,
        0.320801,
        0.374969,
        0.290344,
        0.260712,
        0.19754,
        0.337311,
        0.313171,
        0.279297,
        0.248199,
        0.320465,
        0.0164185,
        0.107147,
        0.126373,
        0.150726,
        0.121246,
        0.217865,
        0.306946,
        0.321106,
        0.248688,
        0.16629,
        0.0726013,
        0.135681,
        0.438599,
        0.206848,
        0.259918,
        0.0330811,
        0.00946045,
        0.00857544,
        0.0090332,
        0.00808716,
        0.0108337,
        0.009552,
        0.00912476,
        0.00817871,
        0.0101624,
        0.0128784,
        0.0116882,
        0.165955,
        0.329681,
        0.478699,
        0.424744,
        0.299652,
        0.248688,
        0.310211,
        0.238434,
        0.197418,
        0.138397,
        0.0422363,
        0.148651,
        0.166626,
        0.217896,
        0.143555,
        0.117889,
        0.112762,
        0.112762,
        0.0627747,
        0.0143433,
        0.010498,
        0.0143433,
        0.0162659,
        0.010498,
        0.00582886,
        0.00650024,
        0.00616455,
        0.0071106,
        0.335876,
        0.320465,
        0.238403,
        0.248657,
        0.217896,
        0.0499268,
        0.279449,
        0.299988,
        0.207642,
        0.217896,
        0.17688,
        0.238403,
        0.17688,
        0.112762,
        0.166595,
        0.207642,
        0.228149,
        0.279449,
        0.0704346,
        0.0175476,
        0.0111389,
        0.00918579,
        0.00793457,
        0.00857544,
        0.0111389,
        0.00921631,
        0.00985718,
        0.00793457,
        0.0137024,
        0.0143433,
        0.0653076,
        0.0351868,
        0.0351868,
        0.0185242,
        0.0210571,
        0.0111389,
        0.0117798,
        0.00857544,
        0.0137024,
        0.078125,
        0.258942,
        0.158905,
        0.356384,
        0.258942,
        0.238434,
        0.228149,
        0.0576172,
        0.015625,
        0.00982666,
        0.00793457,
        0.00921631,
        0.00982666,
        0.0117798,
        0.010498,
        0.00985718,
        0.0117493,
        0.0111389,
        0.0576172,
        0.356384,
        0.376892,
        0.438446,
        0.458954,
        0.238403,
        0.248657,
        0.228149,
        0.128143,
        0.269196,
        0.269165,
        0.207672,
        0.112762,
        0.0274963,
        0.0137024,
        0.00680542,
        0.00793457,
        0.00680542,
        0.0111389,
        0.00857544,
        0.00985718,
        0.00857544,
        0.00857544,
        0.00924683,
        0.00793457,
        0.0124207,
        0.00854492,
        0.00790405,
        0.00985718,
        0.00857544,
        0.00790405,
        0.0922546,
        0.107635,
        0.0973816,
        0.238403,
        0.207642,
        0.238403,
        0.197388,
        0.123016,
        0.197357,
        0.310211,
        0.258942,
        0.248657,
        0.187134,
        0.0576172,
        0.0117798,
        0.00793457,
        0.00921631,
        0.00857544,
        0.0111084,
        0.00985718,
        0.010498,
        0.00985718,
        0.00985718,
        0.00985718,
        0.0130615,
        0.00985718,
        0.00793457,
        0.00857544,
        0.0601807,
        0.17688,
        0.143524,
        0.310211,
        0.279449,
        0.228149,
        0.207642,
        0.0338745,
        0.166595,
        0.228149,
        0.248688,
        0.248688,
        0.228149,
        0.197388,
        0.078125,
        0.0274658,
        0.0185242,
        0.010498,
        0.010498,
        0.0130615,
        0.00982666,
        0.0111389,
        0.0162659,
        0.0149841,
        0.0111389,
        0.0755615,
        0.143524,
        0.310211,
        0.320496,
        0.417938,
        0.376892,
        0.299957,
        0.197388,
        0.0175476,
        0.13327,
        0.015625,
        0.207642,
        0.187134,
        0.0679016,
        0.0576172,
        0.0274658,
        0.00985718,
        0.010498,
        0.0124207,
        0.00921631,
        0.0124207,
        0.0111389,
        0.0117798,
        0.0111389,
        0.00985718,
        0.00857544,
        0.00857544,
        0.00857544,
        0.00985718,
        0.0111084,
        0.112762,
        0.148651,
        0.148682,
        0.102509,
        0.217896,
        0.238403,
        0.17688,
        0.166626,
        0.123016,
        0.138397,
        0.187134,
        0.228149,
        0.0601807,
        0.0678711,
        0.0499268,
        0.0550537,
        0.0149841,
        0.0104675,
        0.0137024,
        0.0130615,
        0.0197754,
        0.0117798,
        0.0162659,
        0.0117798,
        0.015625,
        0.0117798,
        0.015625,
        0.0149841,
        0.0136719,
        0.0117798,
        0.0124207,
        0.0111389,
        0.0210571,
        0.0870972,
        0.123016,
        0.123016,
        0.13324,
        0.0973816,
        0.0274658,
        0.0210876,
        0.0249023,
        0.248688,
        0.217896,
        0.158936,
        0.258942,
        0.166626,
        0.0351868,
        0.228149,
        0.279449,
        0.258942,
        0.166626,
        0.0524902,
        0.0185242,
        0.197388,
        0.228149,
        0.217896,
        0.0550537,
        0.0149841,
        0.0130615,
        0.0149536,
        0.0137024,
        0.0287781,
        0.258942,
        0.22818,
        0.078125,
        0.0236206,
        0.0184937,
        0.0124207,
        0.417938,
        0.39743,
        0.376892,
        0.0261841,
        0.00790405,
        0.00793457,
        0.00793457,
        0.00753784,
        0.00891113,
        0.0115356,
        0.0144348,
        0.0176086,
        0.0131226,
        0.0150452,
        0.0551147,
        0.0141602,
        0.00631714,
        0.00552368,
        0.113861,
        0.143341,
        0.238098,
        0.22702,
        0.416809,
        0.481262,
        0.420349,
        0.261566,
        0.0415955,
        0.336029,
        0.358002,
        0.335541,
        0.499359,
        0.398682,
        0.457672,
        0.322083,
        0.281219,
        0.308929,
        0.379517,
        0.306946,
        0.267761,
        0.198181,
        0.278961,
        0.337463,
        0.302887,
        0.276489,
        0.322235,
        0.0506592,
        0.106354,
        0.127167,
        0.148651,
        0.144653,
        0.216461,
        0.279114,
        0.322235,
        0.260529,
        0.177979,
        0.0983276,
        0.135345,
        0.440369,
        0.377869,
        0.262238,
        0.177338,
        0.052002,
        0.340118,
        0.00775146,
        0.00872803,
        0.00979614,
        0.028595,
        0.047821,
        0.111298,
        0.167084,
        0.353424,
        0.0975342,
        0.379852,
        0.462555,
        0.442993,
        0.207306,
        0.271576,
        0.2771,
        0.248657,
        0.279419,
        0.356384,
        0.310242,
        0.248657,
        0.015625,
        0.17688,
        0.0287781,
        0.238403,
        0.258911,
        0.248688,
        0.0550537,
        0.0262146,
        0.00921631,
        0.0422363,
        0.187134,
        0.143524,
        0.197388,
        0.187134,
        0.187134,
        0.269226,
        0.207642,
        0.166626,
        0.117889,
        0.0601807,
        0.0325928,
        0.0678711,
        0.0704346,
        0.0185242,
        0.00921631,
        0.00857544,
        0.00921631,
        0.00921631,
        0.00793457,
        0.0111389,
        0.0105286,
        0.0124512,
        0.010498,
        0.117889,
        0.197388,
        0.27948,
        0.148651,
        0.166595,
        0.0922241,
        0.102509,
        0.0351868,
        0.00985718,
        0.010498,
        0.00918579,
        0.00985718,
        0.00714111,
        0.00982666,
        0.00921631,
        0.00921631,
        0.0111389,
        0.00921631,
        0.00793457,
        0.00982666,
        0.0755615,
        0.320465,
        0.207642,
        0.258942,
        0.238403,
        0.166626,
        0.138397,
        0.197388,
        0.417938,
        0.310211,
        0.0576172,
        0.0704346,
        0.0162659,
        0.031311,
        0.00793457,
        0.00616455,
        0.00714111,
        0.00613403,
        0.00585938,
        0.00744629,
        0.00646973,
        0.00616455,
        0.00985718,
        0.00918579,
        0.00680542,
        0.0067749,
        0.00714111,
        0.00720215,
        0.00662231,
        0.0160217,
        0.0179443,
        0.015686,
        0.0134583,
        0.0105591,
        0.0126343,
        0.00912476,
        0.00759888,
        0.00454712,
        0.128937,
        0.189758,
        0.241058,
        0.32193,
        0.417297,
        0.479614,
        0.418091,
        0.16452,
        0.0262146,
        0.356995,
        0.337128,
        0.340118,
        0.499969,
        0.457031,
        0.417938,
        0.27832,
        0.310852,
        0.269501,
        0.375122,
        0.289551,
        0.257172,
        0.200043,
        0.301575,
        0.337158,
        0.290009,
        0.236481,
        0.320801,
        0.0218506,
        0.107635,
        0.128784,
        0.149139,
        0.123016,
        0.218079,
        0.300598,
        0.321747,
        0.260376,
        0.16925,
        0.0853271,
        0.130615,
        0.438629,
        0.377197,
        0.260864,
        0.0557556,
        0.0124817,
        0.00827026,
        0.00744629,
        0.00952148,
        0.0128174,
        0.0114441,
        0.0072937,
        0.00915527,
        0.00952148,
        0.00906372,
        0.0495911,
        0.157806,
        0.483704,
        0.325989,
        0.281708,
        0.13855,
        0.130219,
        0.17688,
        0.187134,
        0.102509,
        0.00790405,
        0.0351868,
        0.128143,
        0.0819702,
        0.0261841,
        0.117889,
        0.158905,
        0.158905,
        0.138397,
        0.158905,
        0.0499268,
        0.117889,
        0.117889,
        0.0781555,
        0.0249023,
        0.0117798,
        0.00921631,
        0.00857544,
        0.00744629,
        0.0130615,
        0.0124207,
        0.00857544,
        0.148651,
        0.438446,
        0.438446,
        0.279449,
        0.072998,
        0.0973816,
        0.0249329,
        0.0185242,
        0.0351868,
        0.13327,
        0.0524902,
        0.0447998,
        0.0627441,
        0.0162659,
        0.00857544,
        0.00921631,
        0.0104675,
        0.010498,
        0.00857544,
        0.00921631,
        0.00857544,
        0.00744629,
        0.00921631,
        0.00985718,
        0.0111389,
        0.0973816,
        0.117889,
        0.123016,
        0.112732,
        0.289703,
        0.310211,
        0.17688,
        0.176849,
        0.158905,
        0.197388,
        0.102509,
        0.0184937,
        0.0111389,
        0.0124207,
        0.0136719,
        0.010498,
        0.00921631,
        0.015625,
        0.0124207,
        0.0149536,
        0.0185242,
        0.0130615,
        0.0175476,
        0.010498,
        0.0149841,
        0.0149536,
        0.238434,
        0.0601807,
        0.187134,
        0.207642,
        0.138397,
        0.107635,
        0.072998,
        0.0223389,
        0.0185242,
        0.010498,
        0.00985718,
        0.00857544,
        0.00857544,
        0.00921631,
        0.010498,
        0.00793457,
        0.00744629,
        0.00793457,
        0.0055542,
        0.00650024,
        0.00860596,
        0.356384,
        0.376892,
        0.335876,
        0.117889,
        0.0922546,
        0.335876,
        0.376923,
        0.197388,
        0.107635,
        0.075592,
        0.0653381,
        0.0223694,
        0.00918579,
        0.00793457,
        0.00680542,
        0.00793457,
        0.00744629,
        0.0071106,
        0.00790405,
        0.00744629,
        0.00585938,
        0.00793457,
        0.00650024,
        0.00680542,
        0.0184937,
        0.0601807,
        0.0820007,
        0.0300598,
        0.00985718,
        0.00793457,
        0.00985718,
        0.010498,
        0.0124207,
        0.00793457,
        0.00714111,
        0.00985718,
        0.0124207,
        0.0524902,
        0.0364685,
        0.0223694,
        0.0185242,
        0.153809,
        0.166626,
        0.0422363,
        0.0124207,
        0.0111389,
        0.0973816,
        0.078125,
        0.0287476,
        0.015625,
        0.010498,
        0.033905,
        0.0300293,
        0.0149841,
        0.015625,
        0.00985718,
        0.0124207,
        0.031311,
        0.197388,
        0.479492,
        0.376923,
        0.0870972,
        0.0111389,
        0.00985718,
        0.0870972,
        0.0653076,
        0.0986328,
        0.136169,
        0.0860596,
        0.0578613,
        0.0415955,
        0.0150452,
        0.0124207,
        0.00918579,
        0.00424194,
        0.00360107,
        0.0276489,
        0.0895081,
        0.121399,
        0.0819702,
        0.0672302,
        0.0387573
    ],
    "duration": 101.339996
}
</pre>
</details>

**Comment by katspaugh** [comment]
Gotcha, thanks, that’s helpful.
And thank you for the sponsorship, appreciate it! :)
