### ISSUE TITLE
exportImage in v7

### ISSUE THREAD

**Issue by katspaugh** [katspaugh/wavesurfer.js#3089]
### Discussed in https://github.com/katspaugh/wavesurfer.js/discussions/3088

<div type='discussions-op-text'>

<sup>Originally posted by **hanna-becker** August  8, 2023</sup>
Hey there, can we still export the waveform as an image in v7?

In v6, this worked for me:
```
const waveformImageBlob = (await waveSurferInstance.exportImage('image/png', 1, 'blob'))[0];
```

In v7 the exportImage method is removed.</div>

**Comment by jimapl** [comment]
bump!

**Comment by katspaugh** [comment]
Don't bump pleaase unless you want to work on it. It's an open source, volunteer project.

**Comment by jimapl** [comment]
No s! But august was a while ago. And just discovered this feature is gone after updating!

**Comment by hanna-becker** [comment]
Awesome! Will test it tomorrow.
