### ISSUE TITLE
Resource leak when invoking loadBlob during playback.

### ISSUE THREAD

**Issue by rewbs** [katspaugh/wavesurfer.js#3097]
## Bug description
Not sure whether this is a bug or me misunderstanding the API, but if I call `loadBlob` on a wavesurfer instance that is playing, and then attempt to play the newly loaded blob, this results in a resource leak of some kind that eventually causes the browser tab to crash.

It seems like the Timer's recursive tick subscription is never properly unsubscribed in this case, and remains in a continuously ticking state. Interestingly, explicitly calling `wavesurfer.pause()` before loading the new blob does not seem to work around the issue, whereas manually stopping via a button press before loading the new blob does workaround the issue. 

## Environment
 - Browser: Chrome, Safari

## Minimal code snippet

```javascript
// Resource leak when loading a new blob into an existing wavesurfer instance after playback has started.
//
// To recreate:
// 1. Press load/switch to load up an audio blob
// 2. Press play. Audio plays.
// 3. Without stopping audio, press load/switch to load up a new audio blob. 
// 4. Press play. Audio plays.
// 5. Observe that cursor updates become choppy; browser processconsumes CPU & memory and eventually crashes.
// Resource leak when loading a new blob into an existing wavesurfer instance after playback has started.

import WaveSurfer from 'https://unpkg.com/wavesurfer.js@7/dist/wavesurfer.esm.js'

const wavesurfer = WaveSurfer.create({
  container: document.body,
})

async function loadBlobFromURL(url) {
  const response = await fetch(url);
  if (!response.ok) {
      throw new Error('Network response was not ok: ', response.status);
  }
  const blob = await response.blob();
  return blob;
}

// Buttons
{
  const urls = ['/examples/audio/audio.wav', '/examples/audio/stereo.mp3']
  const switchButton = document.querySelector('#switch')
  switchButton.onclick = () => {
    urls.reverse();
    loadBlobFromURL(urls[0]).then(blob => {
      wavesurfer.loadBlob(blob);
    });
  }

  const playButton = document.querySelector('#play')
  playButton.onclick = () => {
    wavesurfer.playPause();
  }  
}

/*
<html>
  <button id="switch">Load / Switch</button>
  <button id="play">Play / Pause</button>
</html>
*/
```

## Expected result
Wavesurfer loads and renders the new blob, and is able to play it.

## Obtained result
Browser tab becomes unresponsive and eventually crashes.

## Screenshots
n/a

**Comment by rewbs** [comment]
A workaround is to modify `loadAudio` to directly call `this.timer.stop()`.

It's not entirely clear to me why this would be necessary, since we're already calling `this.pause()`, which should result in the timer being stopped through the `onMediaEvent` pause handler (indeed, this is exactly what happens when playback is paused via a button press).

**Comment by katspaugh** [comment]
@rewbs thanks for the report! I've reproduced it also with the regular `load`, not just `loadBlob`. Apparently, the pause event isn't triggered when the audio source is changed immediately after. So I fixed it by adding another event to stop the timer – `emptied`.
