### ISSUE TITLE
Keep scroll at the same position when zooming

### ISSUE THREAD

**Issue by katspaugh** [katspaugh/wavesurfer.js#3102]
### Discussed in https://github.com/katspaugh/wavesurfer.js/discussions/3101

<div type='discussions-op-text'>

<sup>Originally posted by **Idletalk** August 11, 2023</sup>
When I scroll the container to a certain point（such as 5s in visible center）, then  I reset zoom,  the render will scroll to 0. 

![img_v2_91afe473-7407-42ab-8c22-baf6c6046fag](https://github.com/katspaugh/wavesurfer.js/assets/38195804/fbf27f04-9773-4ba9-84a2-ad9426aff599)
Is there any way I can set the zoom value ，after this action the point 5s  is also in my windowing center？
</div>

**Comment by gyeongseokKang** [comment]
Im making this function, but I need access to scroll div.

If you can access the scroll div, you will be able to keep it in scroll api.

Please Check issue for getScrollDiv method #3111

**Comment by katspaugh** [comment]
@gyeongseokKang you don’t need any external methods for this. Renderer.js has everything for reading and writing the scroll position. It should listen to the zoom event and recalculate the scroll position, similarly to how it’s done for the playback position.

**Comment by gyeongseokKang** [comment]
Is there a way to access Render method??
i can't find it!!

**Comment by katspaugh** [comment]
I don’t think it’s a good idea to try and fix this then.

**Comment by Serek16** [comment]
You can get wavesurfer.renderer.getScroll() can you set Scroll?

**Comment by HoodyHuo** [comment]
![Peek 2023-10-17 14-01](https://github.com/katspaugh/wavesurfer.js/assets/35290158/7dbdaf08-68fb-4eb0-a364-88f975e9e910)
I have implemented zoom functionality at the mouse hover position by adding a mousewheel event handler. Let's see if anyone needs it.

**Comment by katspaugh** [comment]
I'll close this since the zoom plugin solves this nicely.
