### ISSUE TITLE
cannot get the currentTime using the "interaction" event listener

### ISSUE THREAD

**Issue by Johnrobmiller** [katspaugh/wavesurfer.js#3103]
I found a bug where when you call `getCurrentTime()` inside an "interaction" event listener, it does not give the updated time. So, if I move the waveform position to 10 seconds and previously it was at 5 seconds, calling `getCurrentTime()` will return 5 seconds instead of 10.

As a workaround, I simply wait 35ms before checking to see what the currentTime is:

```
wavesurfer.current.on('interaction', async () => {
    // the wavesurfer currentTime is set async, and won't be ready when this callback is fired.
    // there is no way to listen for when current time changes, so the only option is to set a timeout
    await new Promise((resolve) => setTimeout(resolve, 35))
    if (!wavesurfer.current) return
    setCurrentTime(wavesurfer.current.getCurrentTime())
  })
```

Also, before asking `why keep currentTime in a react useState when you can get it on the waverurfer ref?`, keep in mind that when the ref changes, the components don't rerender, which is a problem when you want to display the currentTime in a component

**Comment by katspaugh** [comment]
I’ll fix the bug with the interaction receiving the previous current time.

However, you should listen to the timeupdate event to keep track of current time.
