### ISSUE TITLE
Timeline not matching waveform

### ISSUE THREAD

**Issue by oddetc** [katspaugh/wavesurfer.js#311]
Hi Katspaugh,

I'm running into an issue where the timeline width (and also notches for timestamps) stop short of the actual clip duration and waveform width.

I am running a 0.x version of wavesurfer, is this fixed in a later version, or is there some sort of workaround I'm unaware of?

Any help is much appreciated.

Thank you,
Trevor

PS- Here is a screenshot of what I'm talking about: 
![screen shot 2014-12-10 at 10 19 10 am](https://cloud.githubusercontent.com/assets/3693123/5381432/0d0169c6-8056-11e4-9a21-21418a7c25a7.png)

**Comment by jayjoshi123** [comment]
toggleScroll() function needs to be updated

OLD Function:
toggleScroll: function () {
        this.params.scrollParent = !this.params.scrollParent;
        this.drawBuffer();
}, 

UPDATED Function:
toggleScroll: function () {
        this.params.scrollParent = !this.params.scrollParent;
        this.drawBuffer();

        //Change by jay
        this.drawer.progress(this.backend.getPlayedPercents());
},

**Comment by katspaugh** [comment]
Looks like the same as #354. Please, reopen if you still can reproduce the bug with the latest code.
