### ISSUE TITLE
how about getScrollDiv method?

### ISSUE THREAD

**Issue by gyeongseokKang** [katspaugh/wavesurfer.js#3111]
<img width="382" alt="image" src="https://github.com/katspaugh/wavesurfer.js/assets/61446585/2293bde1-0f4d-43ed-b569-f709ddd1ac9f">

I want to get scroll div for scroll position after zoom.

However, the only method currently supported is getWrapper.

How about a method like getScrollDiv?

**Comment by katspaugh** [comment]
I’m against adding methods to access internal divs. Btw please don’t create issue for questions.
