### ISSUE TITLE
Setting sinkId to specify input/output device not working in 7.1.4 or 7.1.5

### ISSUE THREAD

**Issue by Codigo-Fuentes** [katspaugh/wavesurfer.js#3144]
## Bug description
Setting sinkId to specify input/output device not working in 7.1.4 or 7.1.5

## Environment
 - Browser: Chrome

## Minimal code snippet
```
useEffect(() => {
    wavesurfers.current.forEach((ws) => {
      if (selectedOutputDevice) {
        ws.setSinkId(selectedOutputDevice)
          .then(() => {
            console.log('Successfully updated the output device.')
          })
          .catch((error) => {
            console.warn('Failed to update the output device:', error)
          })
      }
    })
  }, [selectedOutputDevice])
```

## Expected result
audio plays on selected device

## Obtained result
no change in device. no error.

## Note
works fine in 7.0.5, downgrading as a temp fix but would like to use the latest version

**Comment by katspaugh** [comment]
Might be related to [this change](https://github.com/katspaugh/wavesurfer.js/commit/941cf9fed4bd3744ee594ca6e4c7e5c916fd767c#diff-feb7ceb6e19ece5ccb87c867d2c740d1cd0669de790815c5d1107259c0fc0212R53-R55).

**Comment by katspaugh** [comment]
I couldn't reproduce it, it sets the output device correctly. Please feel free to reopen the issue if you have more info.
