### ISSUE TITLE
Uncaught SyntaxError: The requested module '//unpkg.com/wavesurfer.js@beta' does not provide an export named 'ws'

### ISSUE THREAD

**Issue by edwardsmarkf** [katspaugh/wavesurfer.js#3148]
## Bug description

beta bug -- it now throws a console error.

## Environment

 - Browser: Chrome Version 116.0.5845.111

## Minimal code snippet

//  this is now bad!  (this was 7.2)
import ws                   from //unpkg.com/wavesurfer.js@beta'

// my fix/workaround:
import ws                   from  //unpkg.com/wavesurfer.js@7.1.5/dist/wavesurfer.esm.js

## Expected result

the world's most beautiful and versatile player provided by katspaugh, the greatest software designer that ever lived.

## Obtained result

Uncaught SyntaxError: The requested module '//unpkg.com/wavesurfer.js@beta' does not provide an export named 'ws'

**Comment by katspaugh** [comment]
Hi Marky,
That's the correct behavior – unpkg defaults to a UMD .min.js, which won't work with `import`. Your workaround is the right way to import a ES module. That's also the syntax I use in all of the examples on the website.
Cheers!

**Comment by babul** [comment]
This also works: `import WaveSurfer from 'https://unpkg.com/wavesurfer.js?module'`
