### ISSUE TITLE
Minified plugins

### ISSUE THREAD

**Issue by thijstriemstra** [katspaugh/wavesurfer.js#315]
It would be nice to have minified plugins, next to the normal build of wavesurfer. I'd imagine a `plugins` directory in the `build` directory that contains the plugins with `min` in the filename of the plugin.

**Comment by tomByrer** [comment]
+1
Or just put put all miniified files in the same folder.

**Comment by thijstriemstra** [comment]
@katspaugh, do you want to use `grunt` for this, and remove the 'manual' `Makefile` build script?

**Comment by katspaugh** [comment]
I'm OK with grunt or gulp.

**Comment by thijstriemstra** [comment]
I could use a little feedback before I submit the pull request:

- added a `Gruntfile.js`, got rid of the `Makefile`
- running `grunt` concencates everything into a single file, which is written to `dist/wavesurfer.dev.js`. This file is useful for debugging, but do you want to include this in a release as wel?
- running `grunt` scans the `plugin` folder, minifies each plugin, and places the result in `dist/plugin/wavesurfer.microphone.min.js` for example

Any thoughts?

**Comment by katspaugh** [comment]
Hi Thijs,

`wavesurfer.dev.js` is unnecessary, I think. Source map is better for debugging.

As for the plugins, all sounds good. By the way, I'm planning to promote the regions plugin back to the main code.

**Comment by thijstriemstra** [comment]
Ok. What about the current `build` folder, do we want to:

- keep it, and have a `dist` folder only locally
- replace it with `dist` (and break existing script links out on the web that link to the `build/wavesurfer.min.js` vs `dist/wavesurfer.min.js`
- have both a `dist` and `build` folder in the repository..

**Comment by katspaugh** [comment]
I'd have only `dist`, since it seems to be the npm standard. To break the links they firstly would have to update the package, at which point they could also change the link, I think.

**Comment by tomByrer** [comment]
> promote the regions plugin back to the main code

One of my main uses of wavesurfer, though I'm not everyone will use it.

**Comment by thijstriemstra** [comment]
I think this is ready for a pull request. After running `grunt` from root directory you'll end up with a `dist` that looks like this:

![schermafbeelding 2015-03-02 om 20 28 08](https://cloud.githubusercontent.com/assets/305679/6448514/cb85e8b8-c11a-11e4-91fa-4776b1a28ce0.png)

**Comment by katspaugh** [comment]
Cool, looking forward to the PR!

**Comment by thijstriemstra** [comment]
I haven't tested the json map for debugging but I think it should work (although the paths changed from `build/wavesurfer.min.js` to `wavesurfer.min.js` and from `src/util.js` to `../src/util.js` but hopefully it means the same..)

**Comment by thijstriemstra** [comment]
Ok, thanks for merging. If we can all test our apps with the latest build, hopefully this can be released soon.

**Comment by katspaugh** [comment]
Thijs, I've published a new version to npm today. Git tag (for Bower) will follow soon.

**Comment by thijstriemstra** [comment]
@katspaugh thanks, looking forward to it.

**Comment by thijstriemstra** [comment]
@katspaugh I consider this fixed but perhaps it's best to wait for upcoming release to verify it.
