### ISSUE TITLE
Timeline tick marks do not seem to adjust with zoom factor changes (multi-track demo)

### ISSUE THREAD

**Issue by alankent** [katspaugh/wavesurfer.js#3156]
## Bug description

On the demo site, the multi-track editor example (https://wavesurfer-js.org/examples/?multitrack.js) you can change the Zoom factor, but the timeline tick marks do not move. If you zoom in shouldn't the timeline ticks zoom too, to stay lined up with the same point in the waveform?

## Environment
 - Browser: Chrome

## Minimal code snippet

Demo site code.

## Expected result

Changing the zoom factor should change the spacing of the timeline tick marks.

## Obtained result

The ticks do not move when you change zoom factor.

## Screenshots

Default zoom
<img width="241" alt="image" src="https://github.com/katspaugh/wavesurfer.js/assets/5702163/e869a412-86b7-44a3-8e03-b3f02a96df67">

Max zoom level, the waveform has moved, but the timeline ("30" pointed at) has not changed.
<img width="332" alt="image" src="https://github.com/katspaugh/wavesurfer.js/assets/5702163/36169c10-18e7-4965-a67c-dae46aa0b4fb">

**Comment by katspaugh** [comment]
Thanks! It’s already tracked here: https://github.com/katspaugh/wavesurfer-multitrack/issues/20
