### ISSUE TITLE
In Safari, the Wavesurfer progress bar jumps back briefly after starting playback, then resumes normal operation

### ISSUE THREAD

**Issue by tomhe168** [katspaugh/wavesurfer.js#3158]
## Bug description
In Safari, the Wavesurfer progress bar jumps back briefly after starting playback, then resumes normal operation

## Environment
 - Browser: Safari

## Minimal code snippet
// A super-basic example

import WaveSurfer from 'https://unpkg.com/wavesurfer.js@7/dist/wavesurfer.esm.js'

const wavesurfer = WaveSurfer.create({
  container: document.body,
  waveColor: 'rgb(200, 0, 200)',
  progressColor: 'rgb(100, 0, 100)',
  url: '/examples/audio/audio.wav',
})

wavesurfer.once('interaction', () => {
  wavesurfer.play()
})

## Expected result
fix 

## Screenshots

https://github.com/katspaugh/wavesurfer.js/assets/21154604/6ed32e97-6a0d-496d-b3ce-2de7f56b8894

**Comment by katspaugh** [comment]
It has to do with the browser seeking back and forth in the audio file, especially with VBR audio. Not much we can do to prevent this.

**Comment by vincehi** [comment]
v6 does not suffer from this problem
