### ISSUE TITLE
Load server side generated Waveform image

### ISSUE THREAD

**Issue by Heinerlutscher** [katspaugh/wavesurfer.js#316]
I have large mp3 files and this give me a error.
I would now generate the waveform on my server with lame. The png file would i use to show the waveform. How can i do this?
Thanks

**Comment by engineerKev** [comment]
First time trying out wavesurfer.js and I also had this issue, and this thread helped. However I need a little more information.
@Heinerlutscher Could you share how you loaded the c++ library onto your server? Is it simply just a matter of adding the directory to your code base or is the process more involved?

**Comment by Liguo-Ma** [comment]
Hello everyone 
I can not build audiowaveform by BBC R&D on windows
Could you send audiofwaveform exe file?
Best Regards
