### ISSUE TITLE
CPU overloading when container hasn't width 

### ISSUE THREAD

**Issue by greenreptile** [katspaugh/wavesurfer.js#3240]
Hi

I used below code to active wavesurfer in my project but CPU FAN start working high suddenly! Also nothing was visible in the screen. (DOM code had been created and SVG tag was refreshing continuously)

```
const wavesurfer = WaveSurfer.create({
  container: document.querySelector('#waveform'),
  waveColor: '#ff9000',
  progressColor: '#383351',
  barWidth: 6,
  barGap:4,
  barRadius: 10,
  normalize: true,
  splitChannels: true,
  sampleRate: 3000,
  
  url: 'temp.mp3',
})

```
After some checking, I found out that if main container has width (Percent or PX) even in CSS, problem will be disappeared. 

Is it a bug?

**Comment by katspaugh** [comment]
This can happen if the container is in a flex box and doesn’t have a width. We should probably set a minimum width to prevent these infinite rendering attempts.
