### ISSUE TITLE
Can't scroll long waveform on Iphone 

### ISSUE THREAD

**Issue by Beerwerd** [katspaugh/wavesurfer.js#3257]
## Bug description
Scrolling is unavailable on Iphone. It is reproducible on https://wavesurfer.xyz/examples/?timeline.js example page. 

When I open develop panel and enable "mobile view mode", I still can't scroll waveform by clicking element and moving.
But when I use "2 fingers" scrolling (on mac) it works. I do not know how to do the same on my mobile phone

## Environment
 - Browser: Chrome

## Expected result
scroll should works on Iphone

**Comment by katspaugh** [comment]
Thank you, that’s a great catch. Looks like some event handler is preventing scrolling.
