### ISSUE TITLE
Scrolling on IOS doesn't work with regions plugin

### ISSUE THREAD

**Issue by Beerwerd** [katspaugh/wavesurfer.js#3265]
## Bug description
When you have wavesurfer with region from the begin to the end and try scroll element on IOS (Iphone), it works. but when you scroll again it stop working. moreover all "onClick" events stop working on page.

## Environment
 - Browser: Chrome

**Comment by jagthedrummer** [comment]
I'm not sure if it's exactly the same thing but I just ran into something very similar.

On mobile Safari if I have a zoomed waveform and have set `dragToSeek: true` then things act weird. If you just tap on the waveform it will set the cursor position. If you drag the waveform itself it will set the cursor position and drag the waveform, which I think is reasonable. But if you drag the cursor itself it gets into a state where the _only_ thing you can do on the whole is either drag the cursor or the waveform. Regular taps on the waveform stop working, and regular taps on any other element on the page doesn't work. Like the events are just swallowed somewhere.

If I set `dragToSeek: false` then I can't get it to go into that funky state.

**Comment by jagthedrummer** [comment]
I've also been able to get it to happen when the waveform is not zoomed, but it's _much_ harder to trigger in that case and I don't know exactly what sequence of events triggers the problem. When the waveform is zoomed and `dragToSeek` is `true` it's very easy to trigger.

**Comment by katspaugh** [comment]
Thanks!

I’ll look into using the native drag events instead of pointer events. Hopefully that should fix a lot of weird behaviors on mobile.

**Comment by LeonardoRick** [comment]
Should drag to seek be working in iOS flawlessly? I found an issue on my project that if you try to drag it before playing, it breaks. You can check on https://leonardorick.com/music

**Comment by Lonli-Lokli** [comment]
Still happening, on Android too
