### ISSUE TITLE
Updating height of drawer

### ISSUE THREAD

**Issue by thijstriemstra** [katspaugh/wavesurfer.js#327]
For redrawing at a different height (after going fullscreen for example) I came up with this

```javascript
// destroy old drawing
this.surfer.drawer.destroy();

// set new height
this.surfer.params.height = 900;
this.surfer.createDrawer();

// redraw
this.surfer.drawBuffer();

// make sure playhead is restored at correct position
this.surfer.drawer.progress(this.surfer.backend.getPlayedPercents());
```

It would be nice if this code is maintained here. Can a `setHeight` or something be added?

**Comment by katspaugh** [comment]
I've added the `setHeight` method in https://github.com/katspaugh/wavesurfer.js/commit/1b9189e63963806bcad4a463a83e4fb6d8e3e99c#diff-0333441833ed71523c3686dac5804d80R149
