### ISSUE TITLE
Progress color does not completely fill the wave area

### ISSUE THREAD

**Issue by def0e0** [katspaugh/wavesurfer.js#3270]
The progress area is drawn on top of the main wave area, but it does not fit it. 
![image](https://github.com/katspaugh/wavesurfer.js/assets/71279/4d732459-e104-437e-9ad0-c686823e5650)

Is this by design or is it a bug?
How to make the progress canvas completely overlap the canvas of the main wave?

You can check it on the examples page: [https://wavesurfer.xyz/examples/?all-options.js](https://wavesurfer.xyz/examples/?all-options.js)
Set the progress color to black and the wave color to red for example.

**Comment by katspaugh** [comment]
It's definitely a bug.
