### ISSUE TITLE
Can't add new regions by drag selection when timeline plugin is created with insertPosition 'beforebegin' 

### ISSUE THREAD

**Issue by Biilik** [katspaugh/wavesurfer.js#3293]
## Bug description
Title.

## Environment
 - Browser: Chrome

## Minimal code snippet
Use the [official regions example](https://wavesurfer.xyz/examples/?regions.js): 
Import the timeline plugin, and add it to wavesurfer, with insertPosition 'beforebegin'.

For copying:
import TimelinePlugin from 'https://unpkg.com/wavesurfer.js@7/dist/plugins/timeline.esm.js'
ws.registerPlugin(TimelinePlugin.create({insertPosition: 'beforebegin'}));

## Expected result
You can add regions when dragging on waveform.

## Obtained result
On drag nothing happens.

**Comment by Biilik** [comment]
**Problem**: Regions plugin calls `makeDraggable` on the wrapper `this.wavesurfer?.getWrapper()?.querySelector('div')`.  
When using `TimelinePlugin` with `insertPosition: 'beforebegin'`, the `.timeline` element is return as the wrapper, instead of `.canvases` element.

**Comment by katspaugh** [comment]
Thanks for the report and the analysis!

> this.wavesurfer?.getWrapper()?.querySelector('div')

Not a very robus way to find a container, is it...
