### ISSUE TITLE
Timeline plugin is not rendered until setOptions is called if not created within WaveSurfer.create(...)

### ISSUE THREAD

**Issue by ShiiRochi** [katspaugh/wavesurfer.js#3314]
## Bug description

Timeline plugin is not rendered until I am doing setOptions call when registering plugin with registerPlugin call instead of adding plugin from the very beginning of WaveSurfer lifecycle.

## Environment
 - Browser: Chrome

## Minimal code snippet
I created demo in codesandbox showing bug in action.

Is is using react as UI module, but code is easy to understand, there are two cases can be checked.

https://codesandbox.io/s/wavesurfer-7xx-timeline-plugin-issue-sandbox-z5xxwg

## Expected result
Timeline plugin is rendered like others i.e. visible at least right after registering it with registerPlugin w/o need to call setOptions

## Obtained result
Timeline plugin is rendred after calling registerPlugin and setOptions

**Comment by katspaugh** [comment]
This seems to be something with your code rather than wavesurfer. As you can see on https://wavesurfer.xyz/examples/?timeline-custom.js, it renders just fine right from the start.

**Comment by ShiiRochi** [comment]
But in your code plugin was not removed and added again further

**Comment by ShiiRochi** [comment]
@katspaugh, are you serious?
https://codesandbox.io/s/wavesurferjs-7xx-timeline-issue-nativejs-66lmh2

I made Vanilla JS example of Timeline plugin not appearing after first init and removal

**Comment by katspaugh** [comment]
I see, thanks for clarifying.

https://github.com/katspaugh/wavesurfer.js/blob/main/src/plugins/timeline.ts#L90 – this should probably be `wavesurfer.getDuration()` instead of options.duration.

**Comment by ShiiRochi** [comment]
> I see, thanks for clarifying.
> 
> 
> 
> https://github.com/katspaugh/wavesurfer.js/blob/main/src/plugins/timeline.ts#L90 – this should probably be `wavesurfer.getDuration()` instead of options.duration.

Might it be intentional to use options.duration so it can be left and getDuration added to this if-else?

When using `getDuration` should Timeline plugin check wavesurfer for readiness? For example, due to bad network connection record (even its metadata) can still wait to be downloaded.

**Comment by katspaugh** [comment]
True, good point. A custom duration option was added for the multitrack plugin, where it renders a  timeline for the entire mix with a custom duration. But it has actually been changed recently and doesn’t require this feature. So it’s safe to remove.
