### ISSUE TITLE
Regions Plugin leaves orphaned wrapper div element after destroy()

### ISSUE THREAD

**Issue by alexgdiaz98** [katspaugh/wavesurfer.js#3319]
## Bug description
The Regions Plugin destroy() method leaves an orphaned div element in the wavesurfer container. It successfully removes each region from the DOM, but fails to remove the wrapper div it created upon initialization.

## Environment
 - Browser: Chrome

## Minimal code snippet
```typescript
const regions = RegionsPlugin.create();
this.wavesurfer.registerPlugin(regions);
// At this point, the regions plugin created a new div element as a child of the wavesurfer container.
...
regions.destroy(); // <- after removing the individual regions, the destroy() method should remove the wrapper div element.
```

## Expected result
The wavesurfer container has all its original children except the regions plugin div (and its children).

## Obtained result
The regions plugin div has no children, but the div element remains.

**Comment by katspaugh** [comment]
Good catch!
