### ISSUE TITLE
Multiple Instances on one page ?

### ISSUE THREAD

**Issue by donsenilo** [katspaugh/wavesurfer.js#332]
Hello

is it possible to use wavesurfer multiple times on one page ?

Thank you.

**Comment by PatrickEGorman** [comment]
Yes, you just need to create separate instances with different class names or ids for the container.

**Comment by donsenilo** [comment]
Thank you for your answer.
But I use wavesurfer in a php-forum (phpbb3) via bbode and I don't know how I can implement seperate instances.

**Comment by katspaugh** [comment]
Try StackOverflow.
