### ISSUE TITLE
Recorder plugin: Request flood when recording

### ISSUE THREAD

**Issue by stefanholzapfel** [katspaugh/wavesurfer.js#3324]
## Bug description
Since recently (at least I recognized it recently) in Firefox the record plugin is creating a flood of requests (see screenshot section) when started more than once.

It looks like it's trying to inject an empty string into the media player source but fails since this resolves to a text/html file ofc. 

## Environment
 - Browser: Firefox (not happening in Chromium)

## Minimal code snippet
Originally we discovered that in our own source, but it is reproducible with your example:
https://wavesurfer.xyz/examples/?record.js
-> start two recordings in a row (start / stop / start)

## Expected result
No request flood but loading the correct blob

## Screenshots
![image](https://github.com/katspaugh/wavesurfer.js/assets/9963536/00808b68-f27f-455d-8ede-0bb0c5873a9c)

**Comment by katspaugh** [comment]
Oh good catch.
Looks like this is the offending line: https://github.com/katspaugh/wavesurfer.js/blob/main/src/plugins/record.ts#L106

We should probably add a condition in the load function to not try to fetch an empty URL.
