### ISSUE TITLE
Map file broken?

### ISSUE THREAD

**Issue by tomByrer** [katspaugh/wavesurfer.js#333]
Have you tried the map file out in Chrome & Firefox, without the /src folder being available?  Seems it doesn't work in Chrome & iffy in Firefox.  Not sure if Chrome looks for a `.map` file, or it pointing to non existing files in the map?
ex: http://tombyrer.github.io/wavesurfer.js/

**Comment by katspaugh** [comment]
Works for me here: http://www.wavesurfer.fm/example/audio-element/

It's essential to keep the map file in the same directory as the `min.js` file, while having the `src` directory in the parent directory. So, the file system layout your web server is serving from should look like this:

**Comment by tomByrer** [comment]
Ah Ok, thanks!

**Comment by loorlab** [comment]
Hi @katspaugh , for the current version we do not find the "dist" folder to get this file in the repository, how can we get to this file wavesurfer-js-map.json?

Thanks !
