### ISSUE TITLE
Progress resets to zero on manual and programmatic changes when using video in Wavesurfer.js

### ISSUE THREAD

**Issue by ghhamza** [katspaugh/wavesurfer.js#3358]
**Bug Description:**
When using Wavesurfer.js with a video element (document.querySelector('video')), synchronization between video and audio works as expected. However, any attempt to change the progress, either programmatically or manually (e.g., through user interaction), results in the progress resetting to zero. This issue occurs when using Wavesurfer.js with video elements and persists even when replicating the official examples provided for Wavesurfer.js.

**Environment:**
Browser: Chrome
Wavesurfer.js version: 7.4.7

**Code**
Same code as the example in the docs

**Expected Result:**
The progress should update to the specified position when using the seekTo function or changing the progress, whether programmatically or manually.

**Obtained Result:**
Regardless of the method used (programmatic or manual), the progress resets to zero instead of updating to the specified position.

**Comment by ghhamza** [comment]
Hello, I am working with a 46-second MP4 video in a React application. Initially, I suspected that the issue might be related to specific React issues. To isolate the problem, I tested the[ same code from the Wavesurfer.js example](https://wavesurfer.xyz/examples/?video.js) but replaced it with my video. However, the issue persisted, indicating that it is not exclusively related to the React environment.

**Comment by katspaugh** [comment]
I cannot reproduce it with this example: https://wavesurfer.xyz/examples/?7d87d565736f0b6ba8ae926e29c54fb2
Both setTime and clicks correctly seek to a position.

As @alexgdiaz98, it's likely something with the file or the web server. Make sure the server supports time range requests.

**Comment by ghhamza** [comment]
Yes it was related to supports of time range requests ... you're saving the day!

**Comment by ghhamza** [comment]
BTW it should be added in the doc of video examples ...
