### ISSUE TITLE
Dragging Regions broke in 7.4.1

### ISSUE THREAD

**Issue by killia15** [katspaugh/wavesurfer.js#3369]
## Bug description

In version 7.4.1 you can't initiate a region on a played part. You can only start after and then drag into the area. I'm wondering if there's a z-index issue or something with the renderProgress function that was updated between the two minor versions? The bug persists all the way up to the present.

https://github.com/katspaugh/wavesurfer.js/compare/7.4.0...7.4.1

## Environment
 - Browser: Chrome

## Expected result

You should be able to start dragging a region anywhere in the waveform. This works in 7.4.0

## Obtained result

In version 7.4.1 you can't initiate a region on a played part. You can only start after and then drag into the area.

## Screenshots
![2023-12-02_18-27-47 (1)](https://github.com/katspaugh/wavesurfer.js/assets/30830235/357e1b68-44c6-42d2-8c4c-f588493c8ac6)

**Comment by katspaugh** [comment]
Thanks, this bug is already tracked in #3296
