### ISSUE TITLE
Weird behavior when clicking and dragging a region

### ISSUE THREAD

**Issue by mbenoni** [katspaugh/wavesurfer.js#3381]
## Bug description
If you click on a region, wait a second, and then start dragging, you have to drag (sometimes far) past the point you clicked before the region starts to move. Clicking and immediately start dragging a region, however, works.

## Environment
 - Browser: Chrome, Firefox, Safari

## Minimal code snippet
[See the official plugin example.](https://wavesurfer.xyz/examples/?regions.js)

## Expected result
You should always be able to click and drag from the point you clicked on the region. Also, the grabbing cursor should appear immediately after clicking on a region.

## Obtained result
Dragging only occurs after moving the pointer away from the point you clicked on the region.

## Screenshots
See video.

https://github.com/katspaugh/wavesurfer.js/assets/5700203/4c1be36e-04bb-482f-8f37-2e86c213735b

**Comment by katspaugh** [comment]
I've seen it on 7.4 but not seeing anymore on 7.5. Can it be that you're getting a cached version of the script?

The grabbing cursor, however, is still an issue.

**Comment by bryanathome** [comment]
I think i may be seeing a related issue.   With 7.5 i can only drag to seek backward and forward in the displayed region.   I can't drag backward/forward to start/end of the track (i.e. scroll out of visable region).    I reverted back to 7.4 and i can seek backwards/forward as expected.

**Comment by katspaugh** [comment]
@bryanathome thanks! Please report it as a separate bug, this issue is abour dragging regions, not drag-to-seek.

**Comment by mbenoni** [comment]
Hi! Any reason why this was closed? The issue still persists in the newest version.

**Comment by katspaugh** [comment]
I couldn't reproduce it as I mentioned in a comment above (https://github.com/katspaugh/wavesurfer.js/issues/3381#issuecomment-1838915560). Maybe the reason is I'm using a touchpad where it's hard to click and not move the cursor.
