### ISSUE TITLE
Zoom plugin: shift + scroll to scroll horizontally

### ISSUE THREAD

**Issue by katspaugh** [katspaugh/wavesurfer.js#3389]
When using a mouse wheel, allow scrolling horizontally instead of zooming when holding down the Shift key.

**Comment by ffxsam** [comment]
Is this done? I couldn't find a PR, but it seems to have sneaked its way into 7.5.1. 🙂

**Comment by katspaugh** [comment]
It's not done, the issue is still open. 3388 made it into 7.5.1 tho.

**Comment by ffxsam** [comment]
Weird, I suddenly am able to shift+wheel to scroll horizontally. Does it work for you? And on trackpad, I can just use gestures only to zoom and scroll. Everything's working as expected.

https://github.com/katspaugh/wavesurfer.js/assets/12532733/13e272c0-cefd-4d2f-a725-695328126e4e

**Comment by katspaugh** [comment]
Apparently it's the [default behavior in some OSes](https://superuser.com/a/908318), so it's fixed by #3388. ✅

**Comment by briangrider** [comment]
Hi all! I experience the desired behavior with shift + scroll scrolling horizontally on Mac OS but this doesn't seem to work on Windows 11 on chromium browser, at least on my end. Is there any solution for this?

By the way @ffxsam, that looks great! How did you go about styling the scrollbar at the bottom of the waveform?

**Comment by briangrider** [comment]
Well I built a scroll function for this in the meantime.  If anyone needs it:

```js
const horizontalScrolling = e => {
  if (e.shiftKey) {
    e.preventDefault();
    e.stopPropagation();
    e.target.closest('.scroll').scrollLeft -= e.deltaY;
  }
};
  
const wavesurferWrapper = wavesurferInstance.getWrapper();
wavesurferWrapper.addEventListener('wheel', horizontalScrolling, true);
```
And in your destructor :

```js
wavesurferWrapper.addEventListener('wheel', horizontalScrolling, true);
```
      @ffxsam And I figured out the scroll bar styling!
