### ISSUE TITLE
Update progress in toggleScroll

### ISSUE THREAD

**Issue by katspaugh** [katspaugh/wavesurfer.js#340]
From the comment by @jayjoshi123:

> toggleScroll() function needs to be updated

> OLD Function:

```
toggleScroll: function () {
    this.params.scrollParent = !this.params.scrollParent;
    this.drawBuffer();
},
```

> UPDATED Function:
```
toggleScroll: function () {
this.params.scrollParent = !this.params.scrollParent;
this.drawBuffer();

    //Progress percentage should also be defined
    this.drawer.progress(this.backend.getPlayedPercents());
},
```

**Comment by jayjoshi123** [comment]
The issue notes was that when the waveform changed from full to scroll and vice-versa on toggleScroll, the progress kept jumping to an incorrect location. 
We used a button to toggleScroll()  and a large audio. 

the fix below solved the issue in wavesurfer.js
toggleScroll: function () {
         this.params.scrollParent = !this.params.scrollParent;
         this.drawBuffer();
	//Progress percentage should also be defined
	this.drawer.progress(this.backend.getPlayedPercents());
},
