### ISSUE TITLE
WebAudio and AudioElement not working in Android webview (using cordova)

### ISSUE THREAD

**Issue by luc0** [katspaugh/wavesurfer.js#341]
I don't know if I am doing something wrong, but I can't use 'AudioElement' (neither WebAudio on Android). I get this error:
**On Chrome / Firefox with 'AudioElement' Also on Android with 'WebAudio':**
```js
Uncaught TypeError: Object prototype may only be an Object or null: undefined
```
It seems to be that **WaveSurfer[this.params.backend]** it's actually returning *undefined*:
```js
this.backend = Object.create(WaveSurfer[this.params.backend]);
```
**On Android with 'AudioElement':**
```Object.create(WaveSurfer[this.params.backend]);``` returns an Object but it's strange because after doing ```this.backend.init(this.params);``` then doesn't run anything else, it stucks there.

-This testings are only because I want to run it in my Android (using cordova)
-Using Chrome with WebAudio works.
-I am using the basic example in the main page http://www.wavesurfer.fm/

There's any way to achieve this? thanks a lot.

**Comment by PipStyles** [comment]
Seconded. I have this working very nicely in Chrome (Windows), Intel's App Preview (Cordova/Webkit), but when using Android webview it's not happy. (Android 4.1.2)
I may look at swapping a Cordova Media object in as the audio provider.

**Comment by luc0** [comment]
Nice idea, I recently find out that the problem itself is that AudioContext is not supported by some phones. (http://stackoverflow.com/questions/22977033/audiocontext-doesnt-exist-on-some-phones)

```(window.AudioContext || window.webkitAudioContext);``` returns undefined. (I have also Android 4.1.2)
I'll try this: http://www.createjs.com/#!/Demos/SoundJS/Music-Visualizer. But it would be nice to see if your workaround works

**Comment by katspaugh** [comment]
If you guys come up with a Cordova Media object backend, please make a pull request. I'll be happy to help implementing it, feel free to ask any questions. Closing this issue for now.

**Comment by moein** [comment]
@katspaugh I'm thinking about implementing the Cordova Media object backend.

This is what I understood I have to do. Correct me if I'm wrong.

I'm going to add a new file called mediaelement.cordova.js
In that file I will use the same variables as mediaelement.js which allows people to include the file they need

I also thought about assigning the object to a different variable and then with backend object you can choose the cordova version but this approach obviously needs more changes.

IMO both solutions are completely backward compatible.

I already started with the wrapper for cordova object so let me know if I need to change my approach.

Cheers

**Comment by katspaugh** [comment]
@moein sounds good!

**Comment by luc0** [comment]
@moein thanks!, I stop doing my proyect because of this, later if I have time, I'll try your new implementation. :)

**Comment by moein** [comment]
@luc0 @katspaugh After some checking on cordova audio plugin I found out that they don't provide any functionality to draw the waveform.

In the end I decided to go with crosswalk to fix the problem in the phones that don't support html5 audio api

**Comment by ducklin5** [comment]
You could try Crosswalk 
`cordova plugin add cordova-plugin-crosswalk-webview`
