### ISSUE TITLE
Add new setScroll method

### ISSUE THREAD

**Issue by ffxsam** [katspaugh/wavesurfer.js#3411]
Per https://github.com/katspaugh/wavesurfer.js/discussions/3405, it would be great to have a `setScroll` method (counterpart to `getScroll`), to be able to programmatically set the scroll position.

I'll likely work on this. Feel free to mark this issue as an enhancement.

**Comment by tapeboy7** [comment]
I need this too.
What about having `setScroll` forward the command to the `private scrollIntoView` method in renderer.ts?

**Comment by katspaugh** [comment]
`scrollIntoView` won't set the scroll to an arbitrary point, it only makes sure the playhead is visible.

It should be a new renderer method that simply sets `this.scrollContainer.scrollLeft`.
