### ISSUE TITLE
Resizable regions handlers are too small

### ISSUE THREAD

**Issue by pitrackster** [katspaugh/wavesurfer.js#343]
Hi !

DOM handlers for resizing regions are so small that they are quite impossible to catch. (Tried on annotation demo).
It could be interesting to have options available to change handlers width, max-width and color.

**Comment by katspaugh** [comment]
Yes, currently they are always 1% of the width of the region. Until we add an API to change their appearance, you can tweak it via CSS (use the selector `.wavesurfer-handle`).

**Comment by pitrackster** [comment]
Thanks for your answer !
For now I added some options to the region plugin (because I need other things to be adapt to suit my needs).

Anyway very good work on this plugin !

By the way you removed wavesurfer.markers... Because it's kind of duplicate with regions ?

Regards.

**Comment by katspaugh** [comment]
Thanks! Yes, a region with only a start position is the new marker.
