### ISSUE TITLE
Passing peaks and duration (predecoded) still downloads content in chrome

### ISSUE THREAD

**Issue by mvynhb** [katspaugh/wavesurfer.js#3435]
## Bug description
When passing peaks and duration audio is still downloaded at least partially in chrome. Firefox does not seem to do it.

How to reproduce:
1-Open devtools and check networking tab in chrome
2-Access: https://wavesurfer.xyz/examples/?predecoded.js

You can observer that demo.wav is partially downloaded. Around 200KB is downloaded and when I click play the rest (~400KB) is downloaded.

## Environment
 - Browser: Chrome

## Expected result
Should not download any content, and only on play should start streaming.

**Comment by katspaugh** [comment]
Looks like the reason is this line: https://github.com/katspaugh/wavesurfer.js/blob/main/src/player.ts#L72

When I remove it, it defaults to only loading metadata as per the [`preload`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio#preload) parameter.

**Comment by bernardwiesner** [comment]
Thanks for the quick fix !

**Comment by mvynhb** [comment]
Hi @katspaugh 

I just tested again in chrome and the issue is still persisting. In firefox content is not downloaded on page load, but it chrome it is. https://wavesurfer.xyz/examples/?predecoded.js

Could you check? thanks

**Comment by katspaugh** [comment]
The preload param is relevant for playback/seeking and not for rendering, so I wouldn’t change the default based on passed peaks/duration (which _are_ for rendering).

You can set the preload param by passing a custom media element as shown here: https://wavesurfer.xyz/examples/?video.js

**Comment by mvynhb** [comment]
@katspaugh 

Thanks, yes I am setting the preload depending on if I have the duration or not as a workaround:

```
            const media = new Audio(src)
            media.preload = duration ? 'none' : 'metadata'

            this.surfer = WaveSurfer.create({
                ...
                media: media
            })
```

However I still find it would be nice that this could be handled internally since in the docs it says streaming is supported if you pass peaks/duration, however in chrome it still downloads a lot of content even if you pass peaks/duration. If you have a list of like 50 audios, it could download over 20MB of data even if you pass peaks/duration. On firefox this does not happen.

**Comment by katspaugh** [comment]
I think it comes down to your app requirements. Some apps might want their users to enjoy fast preloaded audio playback, some may prioritize bandwidth. So specifying a custom media property IMO is the way to go. We could alternatively also expose it as a wavesurfer option, I’m open to a PR.

**Comment by dziamid** [comment]
I got around this by passing peaks and duration only initially, so the audio player is not aware of the audio url, but can still render the waveform using peaks and duration. Then, i'm watching user interation (click on waveform and play button) and load the audio url.
