### ISSUE TITLE
Plugin's BasePlugin type is not a class derived from BasePlugin in WaveSurfer

### ISSUE THREAD

**Issue by cheesenrise** [katspaugh/wavesurfer.js#3446]
## Bug description
`Property 'wavesurfer' is protected but type 'BasePlugin<EventTypes, Options>' is not a class derived from 'BasePlugin<EventTypes, Options>'. ts(2345)`

BasePlugin, BasePluginEvents and GenericPlugin types are duplicated from src/base-plugin.ts to dist/wavesurfer.d.ts after rollup-plugin-dts has been added in https://github.com/katspaugh/wavesurfer.js/commit/add8c247b3e638682d69d723178bb1e19d57c9d6 and WaveSurfer.registerPlugin uses it, but plugins use the original ones from src/base-plugin.js

## Screenshots
![image](https://github.com/katspaugh/wavesurfer.js/assets/3999922/6df4dd50-cea3-473e-9518-87919cea6f15)
![image](https://github.com/katspaugh/wavesurfer.js/assets/3999922/be368709-976d-4f93-bcb0-d072533982ef)

**Comment by katspaugh** [comment]
Thanks, on it!

**Comment by katspaugh** [comment]
Fixed in 7.5.7. ✅ 
Thank you for reporting and analyzing the problem!
