### ISSUE TITLE
Plugin Recorder no types, broken import.

### ISSUE THREAD

**Issue by ChristopherTrimboli** [katspaugh/wavesurfer.js#3449]
## Bug description
Upgraded from 7.5.3 -> 7.5.6. 

`import RecordPlugin from "wavesurfer.js/dist/plugins/record.esm.js";`

Next.js project, everything normal. Been running Wavesurfer for months no issues.

```
Could not find a declaration file for module 'wavesurfer.js/dist/plugins/record.esm.js'. '/home/cjft/Documents/github/lalaland/lalaland-app/node_modules/wavesurfer.js/dist/plugins/record.esm.js' implicitly has an 'any' type.
  If the 'wavesurfer.js' package actually exposes this module, consider sending a pull request to amend 'https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/wavesurfer.js't
  ```
  
I have suspicion it's from this commit here: https://github.com/katspaugh/wavesurfer.js/commit/add8c247b3e638682d69d723178bb1e19d57c9d6
  
  Something not correct with plugin types.
  
  Installing: `@types/wavesurfer.js` did not help.
   

## Environment
 - Browser: Chrome

## Minimal code snippet

create-next-app

`import RecordPlugin from "wavesurfer.js/dist/plugins/record.esm.js";`

## Expected result
Recorder plugin imports.

## Obtained result
It breaks everything and fails.

## Screenshots
![image](https://github.com/katspaugh/wavesurfer.js/assets/27584221/eeb7644a-1f1c-44cb-b1f1-9bdb8c0d7377)

**Comment by ChristopherTrimboli** [comment]
downgrading to: `7.5.4` fixes it.

**Comment by katspaugh** [comment]
Thanks for the report! Closing to merge with #3446 (same issue).

**Comment by ChristopherTrimboli** [comment]
> Thanks for the report! Closing to merge with #3446 (same issue).

fastest bug fixer in the metaverse! great work!
