### ISSUE TITLE
The wrapper height is not stretched when the graph component is registered with the registerPlugin method in the dynamic display hidden graph, resulting in the graph being hidden

### ISSUE THREAD

**Issue by Wei-forward** [katspaugh/wavesurfer.js#3463]
## Bug description
![image](https://github.com/katspaugh/wavesurfer.js/assets/155416178/033c38c1-b257-4a54-aa85-3189d2b2f512)

## Environment
 - Browser: Chrome

## Minimal code snippet
btn1.addEventListener('click', (e)=>{
  console.log('-=-=-=-=-');
  spectrogram.destroy();
})

btn2.addEventListener('click', (e)=>{
  console.log('-=-=-=-=-');
  spectrogram  = ws.registerPlugin(
    Spectrogram.create({
      labels: true,
      height: 200,
      splitChannels: true,
    }),
  )
})

## Expected result
Register to show a spectrogram

**Comment by katspaugh** [comment]
@Wei-forward I don't appreciate your creating all the issues. Please keep the discussion in #3460.
