### ISSUE TITLE
Flash version

### ISSUE THREAD

**Issue by laurentvd** [katspaugh/wavesurfer.js#347]
Would you be interested in a PR containing a Flash version of wavesurfer.js? I had to create a Flash fallback for a client to support IE. It doesn't have all functionality as the JS version (yet), but it is a fallback after all ;-) What do you think?

**Comment by allannaranjo** [comment]
My two cents,

I guess it is waste of time, the reason is simple, IE will support all the
features wavesurfer implements, also Microsoft is making a big efford to
update their users their new versions of IE with webaudio api capabilities
ORTC, therefore in the meantime I would prompt my users to use a webrtc
enabled browser, IE will be there soon.

Allan

**Comment by katspaugh** [comment]
Hi Laurent,

I very much appreciate your contribution, but I'm reluctant to support IE in this way. We already provide an audio element fallback, too.

I've received emails asking to support IE commercially. If you like, I would be happy to redirect them to you to buy the Flash version.

Many thanks!

**Comment by allannaranjo** [comment]
If done, I guess I would make use of wavesurfer's api by using the
actionscript ExternalInterface, that way you can leverage the existing
development.

Allan

**Comment by thijstriemstra** [comment]
I used to do a lot of as3 and wouldnt mind reviewing/testing it but i dont think it belongs in this repository. video.js also has a flash fallback but this maintained in a separate repository.

**Comment by laurentvd** [comment]
Thank you all for your feedback. I gave it some more thought, and I think I agree with you @thijstriemstra . I'll set up a separate repo for the Flash fallback. Maybe at some point it can be linked here. Then it's up to the user wether they want to support IE10 and lower using the Flash version.

And @katspaugh , thank you for the kind offer, but I would want this project to remain open source. I have benefit from the work that went into wavesurfer and I'd like to keep that spirit alive.

**Comment by thijstriemstra** [comment]
I dont know if @katspaugh minds if you use the wavesurfer name but id call it wavesurfer.swf ;)

**Comment by katspaugh** [comment]
I support Thijs's idea and will certainly link to wavesurfer.swf from here!

**Comment by laurentvd** [comment]
That's great! I'll clean up the code a bit and push it to github once I find the time. Will keep you updated.

**Comment by laurentvd** [comment]
I've been working on the Flash version at https://github.com/laurentvd/wavesurfer.swf It is still very rough and far from finished, but the basic functionality (showing a waveform ;-)) works now. If you want to try out the demo, you *have* to run it from a webserver (i.e. localhost) due to Flash's security model.

The js currently shown in the demo is just to get it working. I'll make it a lot cleaner once I figured out how to integrate it with wavesurfer.js. Ideally, it should be added as an additional backend, but I'm not sure if this is feasible. Any ideas / directions?

**Comment by katspaugh** [comment]
Thanks, Laurent! I've added the link to the README.

Speaking of backend, I'd go for a pure Flash decoder that would send a JSON array of PCM data back to JavaScript to draw and play. Like we do with the Media Element [here](http://www.wavesurfer.fm/example/audio-element/). In pseudo-code:
    
    wavesurfer.init({ backend: "MediaElement" });
    wavesurfer.load("audio.mp3", flash.decode("audio.mp3"));

**Comment by laurentvd** [comment]
Thanks so much for adding it to the README (already!). I'll do my best to finish the integration asap. 

About the backend solution, I didn't think of using the Flash only as a decoder. That would be the best solution as it saves me a lot of time. However, -and please correct me if I'm wrong- doesn't this mean that the audio file is loaded twice? Once by the Flash and once by the actual MediaElement? 

Also, if we're just using Flash to decode the audio, there's no use for a graphical Flash version, right? Apart from supporting browsers without canvas maybe.

**Comment by laurentvd** [comment]
I just noticed the mappings in the [demo js](http://www.wavesurfer.fm/example/audio-element/main.js) is just a simple array. Does wavesurfer only support single channel (no stereo) audio?

**Comment by thijstriemstra** [comment]
I would like to see flash draw the waveform as well, or make it optionally (and not the default?)

**Comment by katspaugh** [comment]
Yes, that would mean downloading the file twice which is an overhead, but shouldn't affect the speed much as the media element buffers audio sequentially.

And yes, it's a single array of peaks which are maximum values across 2 channels.

**Comment by laurentvd** [comment]
Alright, for now I'll just use Flash as the audio decoder. The implementation will be slightly more complex, because the audio file will need to be loaded before the `flash.decode` method can return the peaks array. So be it ;-)

**Comment by katspaugh** [comment]
You can see here how the Media Element backend handles external decoding:
https://github.com/katspaugh/wavesurfer.js/blob/master/src/wavesurfer.js#L328

It starts playing showing only a thin line instead of a waveform. Meanwhile, it checks whether Web Audio is available and if it is, downloads and decodes the file via Web Audio, and then the thin line is replaced with an actual waveform.

**Comment by laurentvd** [comment]
I've completed the first release of wavesurfer.swf! See https://github.com/laurentvd/wavesurfer.swf

In the end I've decided to not implement it as a backend for the js version. The main reason for this is that wavesurfer.js doesn't work in IE at all. Fixing this would require quite a few changes (ES6 polyfills and more). I've tried to keep it as simple as possible. 

I'm curious what you all think. Feedback is very welcome.

**Comment by katspaugh** [comment]
Cool, thanks! It definitely works!

I think just adding es-shims/es5-shim would do the trick, though. I haven't checked, however.

**Comment by thijstriemstra** [comment]
I tried it on ubuntu 13.04 with FP 11.x and it rendered fine. Not very often I get to spend time behind an ancient Internet Explorer, so that report doesn't help much. Perhaps you can hook it up to travis and get it to test against IE browsers?

**Comment by laurentvd** [comment]
I just ran wavesurfer.js in IE9 (no worries, it's a vitual machine ;-)). It didn't work at first, but it turned out that IE9 was running in quirks mode. For now I'll leave wavesurfer.swf as it is, also rendering the waveform. If someone want's to build a canvas / Flash backend hybrid, they can do so using the exportPCM method. The .swf version also supports this.

I think I'll close this issue for now. For any further discussions or issues with wavesurfer.swf, please open an issue on that repo.

**Comment by katspaugh** [comment]
Many thanks, Lauren!
