### ISSUE TITLE
The hover plugin adds a millisecond parameter

### ISSUE THREAD

**Issue by Wei-forward** [katspaugh/wavesurfer.js#3473]
export type HoverPluginOptions = {
  lineColor?: string
  lineWidth?: string | number
  labelColor?: string
  labelSize?: string | number
  labelBackground?: string
  timeUnit?: string
}
  private formatTime(seconds: number): string {
    const minutes = Math.floor(seconds / 60)
    const secondsRemainder = Math.floor(seconds) % 60
    const paddedSeconds = `0${secondsRemainder}`.slice(-2)
    if(this.options.timeUnit == 'ms') {
      const ms = seconds.toFixed(3).split('.')[1]
      return `${minutes}:${paddedSeconds}:${ms}`
    } else {
      return `${minutes}:${paddedSeconds}`
    }
    
  }

**Comment by katspaugh** [comment]
It looks like you’re trying to submit a patch for the hover plugin. Thanks but this is the wrong way to do it. Please read up about how to create a GitHub pull request.

**Comment by katspaugh** [comment]
And please, stop creating Question issues. I'll have to block you if you do it again.
