### ISSUE TITLE
Play function with end time

### ISSUE THREAD

**Issue by RocAlayo** [katspaugh/wavesurfer.js#348]
The documentation of the play function of Wavesurfer claims you can pass it an endtime. This works when the backend is a `WebAudio` as internally the function calls `this.backend.play()`. But when using `MediaElement` as a backend the endtime doesn't work in part because the function in the backend doesn't knowledge this parameter.

The `play` function of `MediaElement` calls the function `play` of object `media` which is a [DOM Media Element](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement) (video or audio) and as you can see this type of element doesn't have support for playing just a portion of the media. I tried using `setTimeout` as [this stackoverflow post](http://stackoverflow.com/questions/16885878/html5-and-javascript-playing-video-for-a-specific-interval) says but it doesn't work properly. This problem affects the play of the Regions plugins as it uses this same function.

I'm out of ideas of how to resolve this in a proper manner. (As a patch for region you can use 'out' event to stop the playing, but not always stops when it should).

**Comment by katspaugh** [comment]
You are right, this is a lacking feature in the media element backend.

Why is the `setTimeout` solution not working properly?

**Comment by RocAlayo** [comment]
Stops before the end specified (Like a 0.5 seconds before). I don't understand why because the time I specified to the setTimeout is exactly the same (but in miliseconds) as the interval duration.

**Comment by katspaugh** [comment]
I've push a `timeupdate`-based solution. Please, check if it works for you.

**Comment by amundo** [comment]
FWIW, I've found the accuracy on both `timeUpdate` and `setTimeout` approaches to be fairly inaccurate and inconsistent.

**Comment by RocAlayo** [comment]
Yes, it work fine. Thank you.

**Comment by katspaugh** [comment]
Patrick, well, unless anyone knows a better method, let's have the `timeupdate` solution for now.
