### ISSUE TITLE
CSS styling part missing for waveform/canvas

### ISSUE THREAD

**Issue by NILAXY** [katspaugh/wavesurfer.js#3489]
## Bug description
The CSS styling part is missing for waveform/canvas, i noticed that after upgrading the package. Wasn't this there before?

Thanks

**Comment by katspaugh** [comment]
It was never there. Please don’t file bug reports if you’re asking a question and are not sure it’s a bug. Also see a related discussion here: https://github.com/katspaugh/wavesurfer.js/pull/3481#pullrequestreview-1814837000
