### ISSUE TITLE
Adjusting region size while zoomed on part of region cause major render issues

### ISSUE THREAD

**Issue by brian-byassee** [katspaugh/wavesurfer.js#3494]
## Bug description
When the wavesurfer is zoomed in on a region so part of the region is off screen. If the user grabs the visible end of the wavesurfer and starts to drag there is major rendering issues. Please see attached video for example. (It can be reproduced here [wavesrufer regions example](https://wavesurfer.xyz/examples/?regions.js)

https://github.com/katspaugh/wavesurfer.js/assets/47955954/dbb257cb-f449-4d17-b52a-f1d6395184dd

The bug was introduced with this [pull request](https://github.com/katspaugh/wavesurfer.js/pull/3424)
`adjustScroll` is being called for any region update not just when the region is being dragged.

One possible solution might be to add the `side` to the update event and only run `adjustScroll` when it is the region being dragged (`undefinded`) not the `start` or `end`

## Environment
 - Browser: Chrome

## Expected result
The region size is able to be adjusted with out render issues.

## Obtained result
It is impossible to adjust the size of the region in this case.

**Comment by katspaugh** [comment]
Good catch, thank you! Adding a side parameter is a good idea.
