### ISSUE TITLE
Resizing a region with Zoom applied will cause the bottom scroll to become unstable

### ISSUE THREAD

**Issue by NTCarlos** [katspaugh/wavesurfer.js#3502]
## Bug description
If we navigate to https://wavesurfer.xyz/examples/?regions.js and we increase the zoom, when we resize any region that exceeds the horizontal scroll limits, this scroll will start to move randomly to the end of the region.

## Environment
 - Browser: Chrome

## Screenshots
https://youtu.be/PZq5klu_Aw0

**Comment by katspaugh** [comment]
Thanks! It's already been reported in #3494 and fixed. I'll release a new package with the fix now.
