### ISSUE TITLE
Question- GLOBAL_ACTIONS is not defined 

### ISSUE THREAD

**Issue by maxehnert** [katspaugh/wavesurfer.js#351]
I copied the example code for the annotations example, and I cannot delete an annotation and I get an error in the console that GLOBAL_ACTIONS is not defined which is related to the delete function. I do have the plugins included in my build scripts. 

Is there something I am not doing correctly or need to change to make this example work properly?

I just found this plugin yesterday so I am still trying to familiarize myself with it. 

Ultimately I would like to connect a mysql server to load .wav files into this and have annotations made and updated by users.

**Comment by katspaugh** [comment]
`GLOBAL_ACTIONS` is defined in [trivia.js](https://github.com/katspaugh/wavesurfer.js/blob/master/example/trivia.js). You need to include this file as well. Or just define it yourself like this: `var GLOBAL_ACTIONS = {}`.

**Comment by maxehnert** [comment]
Ahh thank you. This worked.
