### ISSUE TITLE
CORS - audio in development and xhr option

### ISSUE THREAD

**Issue by CalvinJamesHeath** [katspaugh/wavesurfer.js#3510]
## Bug description
In development, Wavesurfer is unusable because of CORS problems. 

The documentation also makes no mention of using an XHR object to fix this issue.

## Environment
 - Browser: Chrome

`has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

**Comment by CalvinJamesHeath** [comment]
`WaveSurfer.create({
		container: `#${id}`,
		responsive: true,
		url: fileUrl,
		xhr: {
			cache: 'default',
			mode: 'cors',
			method: 'GET',
			credentials: 'include',
			headers: [
				{ key: 'cache-control', value: 'no-cache' },
				{ key: 'pragma', value: 'no-cache' },
			],
			requestHeaders: [
				{
					key: 'Authorization',
					value: localStorage.getItem('token'),
				},
			],
		},
	})`

I also tried `const myAudio = new Audio( your url to mp3 );
myAudio.crossOrigin = 'anonymous';
wavesurfer.load(myAudio, peaks);` from

[#2014](https://github.com/katspaugh/wavesurfer.js/issues/2014#issuecomment-661910927 )

**Comment by katspaugh** [comment]
Wavesurfer uses fetch to download the audio for rendering, so either CORS must be enabled on the server, or the audio file must be on the same domain as the HTML.

Please learn more about CORS here: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by CalvinJamesHeath** [comment]
Cors is enabled on the server, the response headers don't contain Access-Control-Allow-Origin:
https://mysite.com 

. Still no solution even after I added:

`WaveSurfer.create({
					container: `#${postId}`,
					responsive: true,
					url: fileUrl,
					waveColor: '#D8D8D8',
					progressColor: '#ED2784',
					barRadius: 3,
					cursorColor: 'transparent',
					xhr: {
						cache: 'default',
						mode: 'cors',
						method: 'GET',
						credentials: 'include',
						redirect: 'follow',
						referrer: 'client',
						headers: [
							{
								key: 'Authorization',
								value: localStorage.getItem('token'),
							},
						],
					}})`

How can we tweak the headers?

**Comment by katspaugh** [comment]
The xhr option is now called fetchParams

**Comment by johnbonds** [comment]
My audio files are hosted on S3 behind CloudFront with CORS enabled. I am using CloudFront cookies to download my files. When I specify the following parameters in wavesurfer, it appear to execute an endless loop of attempting to load the file

```
    url: typeof audioData === "string" ? audioData : undefined,
     fetchParams: {
       method: "GET",
       credentials: "include",
     },
```

![image](https://github.com/user-attachments/assets/ce9d1603-5485-4e7c-bdf5-fb1803352781)

Anyone else seeing this issue?

**Comment by thomaskanzig** [comment]
@johnbonds In S3 you can configure CORS for each bucket:

1. Open the Amazon S3 console.
2. Choose the bucket you want to configure.
3. Choose the Permissions tab.
4. Scroll down to the `Cross-origin resource sharing (CORS)` section.
5. Choose Edit.
6. Add a CORS configuration similar to the following:
```bash
[
    {
        "AllowedHeaders": [
            "*"
        ],
        "AllowedMethods": [
            "GET",
            "PUT",
            "POST",
            "DELETE"
        ],
        "AllowedOrigins": [
            "*"
        ],
        "ExposeHeaders": [
            "x-amz-meta-custom-header"
        ]
    }
]
```

Happy coding!

**Comment by johnbonds** [comment]
> @johnbonds In S3 you can configure CORS for each bucket:
> 
> 1. Open the Amazon S3 console.
> 2. Choose the bucket you want to configure.
> 3. Choose the Permissions tab.
> 4. Scroll down to the `Cross-origin resource sharing (CORS)` section.
> 5. Choose Edit.
> 6. Add a CORS configuration similar to the following:
> 
> ```shell
> [
>     {
>         "AllowedHeaders": [
>             "*"
>         ],
>         "AllowedMethods": [
>             "GET",
>             "PUT",
>             "POST",
>             "DELETE"
>         ],
>         "AllowedOrigins": [
>             "*"
>         ],
>         "ExposeHeaders": [
>             "x-amz-meta-custom-header"
>         ]
>     }
> ]
> ```
> 
> Happy coding!

Thanks @thomaskanzig I eventually figured out what the magic formula was in between Cloudfront and S3.
