### ISSUE TITLE
[WebAudio player] Audio out of sync with waveform when changing the playbackrate

### ISSUE THREAD

**Issue by salivity** [katspaugh/wavesurfer.js#3517]
The audio is out of sync with the waveform when using WebAudio backend only MediaElement stays in sync. This is a working example when using MediaElement the problem is that MediaElement does not work with ios safari only WebAudio backend.
As you can see using this link I've changed the project to MediaElement until the problem is fixed. https://davidclews.com/article/286.html when changing the tempo aka the playbackRate the progress bar is out of sync with the audio. I need to find a way to set the progress bar to the correct speed and position like when using MediaElement backend.

**Comment by katspaugh** [comment]
Good catch! The WebAudioPlayer has to take playbackRate into account when tracking time. This was correctly implemented in v6 but not in v7.

**Comment by salivity** [comment]
i created a fix by circular referencing the modified audio stream then running .empty() and .load(object_url) with the updated audio data.
