### ISSUE TITLE
Chrome:  Failed to set the 'buffer' property on 'AudioBufferSourceNode'

### ISSUE THREAD

**Issue by morganwildermuth** [katspaugh/wavesurfer.js#353]
Everything works fine on Firefox and I had this working on Chrome a while back. However, now no wave form appears, the "ready" event never gets fired, and when I click play this error occurs:

**Uncaught TypeError: Failed to set the 'buffer' property on 'AudioBufferSourceNode': The provided value is not of type 'AudioBuffer'.**

The file is .wav

Right now I'm basically calling this behemoth of a function, with the url being the url of the audio file and waveform being equal to Object.create(WaveSurfer):

```
  init: function(waveform, url){
    var waveHeight = ($("#middle-column").outerHeight() - $("#header").outerHeight() - 150);
    waveform.init({
      container     : document.querySelector('#wave'),
      waveColor     : 'grey',
      progressColor : 'darkcyan',
      loaderColor   : 'purple',
      cursorColor   : 'navy',
      markerWidth   : 2,
      dragSelection : false,
      pixelRatio    : 5,
      minPxPerSec   : 15,
      fillParent    : true,
      height        : waveHeight
    });
    waveform.load(url);
    waveform.on('ready', function () {
      $("#timer-current").html("0.00 s");
      $("#timer-end").html(waveform.getDuration().toFixed(2) + ' s');
    });
    waveform.on('finish', function () {
      $("#pause-recording").click();
      $("#timer-current").html("0.00 s");
       waveform.stop();
    });
    $("#start-recording").click(function(){
      waveform.play();
    });
    waveform.on('progress', function () {
      var currentTime = waveform.getCurrentTime().toFixed(2);
      var remainingTime = (waveform.getDuration() - currentTime).toFixed(2);
      $("#timer-end").html(remainingTime + ' s');
      $("#timer-current").html(currentTime + ' s');
    });
    $("#pause-recording").click(function(){
      waveform.pause();
    });
  }
```

Seems this is a known regression with Chrome:
https://code.google.com/p/chromium/issues/detail?id=128826
http://stackoverflow.com/questions/14825030/uncaught-typeerror-value-is-not-of-type-audiobuffer

Still don't quite know easiest way to fix it...

**Comment by thijstriemstra** [comment]
I've seen this happen before and usually its a bug in your own code.. Do you have a link to the tested audio file? Did you test with the latest wavesurfer.js (1.0.16 atm)?

**Comment by morganwildermuth** [comment]
First thing I did was update my version of wavesurfer. Same error. As for the audio file, it's located here (http://yourlisten.com/Morgan.Wildermuth_114_gp/audiosample) but I don't have a publicly accessible waveform version showing the failure. I just used the 'drag-n-drop-n-play' on the main wavesurfer page and it returned the error "Error decoding audiobuffer" in Chrome and worked successfully in Firefox.

So, looking into that now.

**Comment by morganwildermuth** [comment]
This person had the same issue:

https://github.com/katspaugh/wavesurfer.js/issues/204

Not entirely sure how I can fix the encoding, but I'm going to upload a different file and see how that goes. This was a sample wav file anyway. I'll update soon.

**Comment by morganwildermuth** [comment]
No go. Whatever encoding issue is occurring seems to be impacting all the sounds being uploaded to my server.

**Comment by katspaugh** [comment]
This seems specific to your server setup, and I'm not able to help. Please try StackOverflow. If you find a solution, please post it back here. Closing.

**Comment by morganwildermuth** [comment]
Dropping the sound into the browser into the wavesurfer.fm drag-n-play on Firefox works, but the same sound does not work when using the browser chrome wavesurfer.fm site. 

On chrome on wavesurfer.fm drag-n-play, I get this error:

`Error decoding audiobuffermain.js:42 (anonymous function)util.js:125 (anonymous function)util.js:124 WaveSurfer.Observer.fireEvent`

No error on Firefox. Still investigating a workaround, but since I'm using the wavesurfer.fm code and not my own when this error occurs I don't think it's an issue on my end. Any ideas?

**Comment by katspaugh** [comment]
Could you upload/send me the file? I'll try to reproduce.

**Comment by morganwildermuth** [comment]
I sent you an email. I figure it's the same issue as #204 but I have yet to figure out the solution they found. Thanks for any and all insight!

**Comment by morganwildermuth** [comment]
OP at #204 responded to my question. The engineer handling the uploading is adamant there is nothing further he can do; still investigating.

**Comment by katspaugh** [comment]
Yes, I can reproduce the error in Chrome and it works in Firefox.

I've also opened the file you sent me in a desktop audio analyser tool and it says the file's sample rate is 1000 which is quite low.

![screenshot](http://i.imgur.com/tE3SfMQ.png)

Maybe Chrome has a bottom limit on the sample rate in its Web Audio decoder. I wonder if @cwilso could comment on this.

**Comment by hoch** [comment]
Could you file an issue here with a minimum test case? That would be very helpful.

https://code.google.com/p/chromium/issues/entry

**Comment by cwilso** [comment]
@katspaugh @morganwildermuth Can I get a copy of the WAV file also?

**Comment by katspaugh** [comment]
@cwilso I've sent you the file. Thank you for looking at this issue!

**Comment by morganwildermuth** [comment]
We just played with it in Audacity and @katspaugh was dead on that the culprit was the sample rate. We bumped the audio up to a sample rate of 4000 (which will be what our final audio file has...or at least now it will!) and things went swimmingly. Thanks, guys. I don't know much (anything) about audio so didn't really know where to even start to figure out what the heck was happening.

**Comment by titiyoyo** [comment]
Hi, @katspaugh what is the name of the software you used ? It would be of a lot of use !

**Comment by katspaugh** [comment]
Hi, @titiyoyo!

I used a hex editor called "Synalyze It!", but `ffmpeg -i` would do the job as well.

**Comment by titiyoyo** [comment]
Thanks !

**Comment by ddtramp** [comment]
The chromium core support sample rates from 3 kHz to 192 kHz
