### ISSUE TITLE
Media from HLS.js won't play anymore

### ISSUE THREAD

**Issue by dschnabel** [katspaugh/wavesurfer.js#3536]
## Bug description
Up until 7.6.5 it was possible to play an HLS stream using [HLS.js](https://github.com/video-dev/hls.js/tree/master).

HLS.js [removes](https://github.com/video-dev/hls.js/blob/529fe15024945e3199056849c1637dd75af4458d/src/controller/buffer-controller.ts#L204) the source of the video element when attaching the media.

This recent [change](https://github.com/katspaugh/wavesurfer.js/commit/c901fc21f7d493d08655ff8c75b4bc95572af433?diff=unified&w=0#diff-801e0ee54d268fe1d095cb9457beda313bf4d6ad16ab8931f3f0cc94233419e9R95) in wavesurfer prevents playing if media has no source.

If I comment out the check in the `play()` function, the stream starts to play again:
```
        play() {
            return t(this, void 0, void 0, (function*() {
                // if (this.media.src)
                    return this.media.play()
            }
            ))
        }
```

## Environment
 - Browser: Chrome Version 120.0.6099.199 (Official Build) (64-bit)

## Minimal code snippet
```
<head>
  <script src="https://cdn.jsdelivr.net/npm/hls.js@latest"></script>
  <script src="https://unpkg.com/wavesurfer.js@7"></script>
</head>

<body>
  <div id="waveform"></div>
  <script>
    var video = document.createElement('video');
    if (!Hls.isSupported()) {
      throw new Error('HLS not supported!');
    }

    var hls = new Hls();
    hls.loadSource('path/to/playlist/master.m3u8');
    hls.attachMedia(video);

    const wavesurfer = WaveSurfer.create({
      container: '#waveform',
      duration: 100,
      media: video
    });

    wavesurfer.on('finish', () => {
      wavesurfer.setTime(0)
    });
  </script>
  <button onclick="wavesurfer.play()">Play</button>
  <button onclick="wavesurfer.pause()">Pause</button>
  <button onclick="wavesurfer.stop()">Stop</button>
</body>
```

## Expected result
Clicking the play button will start playing the stream.

## Obtained result
Clicking the play button does nothing.

**Comment by mvynhb** [comment]
@dschnabel 

If you do 
```
var video = document.createElement('video');
video.src = 'path/to/playlist/master.m3u8'
...
```

Does it work?

**Comment by dschnabel** [comment]
@mvynhb no, but I got it to work by setting `preferManagedMediaSource` in HLS js to false:
```
var hls = new Hls({preferManagedMediaSource:false});
```

Closing this ticket, since there's a workaround!
