### ISSUE TITLE
Timeline plugin drawn incorrectly on MacBook retina display 

### ISSUE THREAD

**Issue by mahtar** [katspaugh/wavesurfer.js#354]
Only half of the timeline is drawn on MacBook retina display.
Also the canvas is upscaled so it gets blurry.

I edited line 99 to get the whole timeline drawn, from this:

    var width = Math.round(this.drawer.wrapper.scrollWidth / this.wavesurfer.params.pixelRatio);

to this:

    var width = Math.round(this.drawer.wrapper.scrollWidth / this.wavesurfer.params.pixelRatio) * window.devicePixelRatio;

I didn't have time to make the canvas sharp on retina but I'm assuming all the width and height calculations need to take pixel ratio into consideration.

**Comment by thijstriemstra** [comment]
Can you provide a screenshot, I wonder what this looks like..

**Comment by mahtar** [comment]
Here you go
![wavesurfer js timeline plugin](https://cloud.githubusercontent.com/assets/483026/6230231/3fbcd316-b6be-11e4-99d2-2448a4298d75.png)

**Comment by thijstriemstra** [comment]
Right. It looks the same on my Samsung Galaxy S4 mini with Firefox.

**Comment by mahtar** [comment]
I'm guessing it will be the same on all high DPI screens where pixels are doubled by browsers for lower resolution images.

**Comment by katspaugh** [comment]
Should be resolved now. Please reopen, if I missed something.
