### ISSUE TITLE
cannot stop record

### ISSUE THREAD

**Issue by freatraum** [katspaugh/wavesurfer.js#3599]
## Bug description
I cannot stop recording.

## Environment
 - Browser: Chrome
 - React

## Minimal code snippet
```typescript

  const record = wavesurfer?.registerPlugin(RecordPlugin.create({scrollingWaveform:true, renderRecordedAudio: true}))
//this is my stop function.
  const stopRecord=()=>{
    record!.stopRecording()
    setIsRecording(false)
    setRecordStatus("stop")
  }
```

**Comment by katspaugh** [comment]
Please try to create an isolated test case w/o React, as it works perfectly here: https://wavesurfer.xyz/examples/?record.js

**Comment by ayangweb** [comment]
@freatraum Hey, have you solved the problem? `@wavesurfer/react` has super bugs.
