### ISSUE TITLE
Reverse playback

### ISSUE THREAD

**Issue by AlesTsurko** [katspaugh/wavesurfer.js#362]
Is it possible to do reverse playback? When I change playback rate to negative number the cursor is moving backward, but then there is no any sound. Is this a bug or just not implemented yet? Is there another way to reverse playback?

**Comment by katspaugh** [comment]
Setting a negative playback rate will reverse the audio only with the `MediaElement` backend. Try typing `wavesurfer.setPlaybackRate(-1)` in the console here: http://www.wavesurfer.fm/example/audio-element/.

With the `WebAudio` backend you need to reverse the audiobuffer manually, [it seems](http://stackoverflow.com/a/10973392/352796).

**Comment by thijstriemstra** [comment]
```javascript

**Comment by thijstriemstra** [comment]
```function reverseAudio(someBuffer){ Array.prototype.reverse.call(someBuffer.getChannelData(n) ); }
```

**Comment by alittlebitweird** [comment]
> ```js
> function reverseAudio(someBuffer) {
>     Array.prototype.reverse.call(someBuffer.getChannelData(n));
> }
> ```

how can you access / modify the audio buffer directly?
