### ISSUE TITLE
Waveform visually misaligned (bug introduced in version 7.7.7)

### ISSUE THREAD

**Issue by ffxsam** [katspaugh/wavesurfer.js#3632]
## Bug description
As of version 7.7.7, there seems to be a bug where the played waveform & unplayed waveforms are misaligned vertically.

## Environment
 - Browser: Chrome on macOS

## Minimal code snippet
Not sure the code snippet will be useful, as this is pretty standard usage. I didn't see any breaking changes noted in 7.7.7, so I assume I wouldn't have to update our code.
```ts
  wavesurfer = WaveSurfer.create({
    barWidth: 2,
    barGap: 2,
    container: waveformRef.value,
    height: 240,
    minPxPerSec: WAVEFORM_ZOOM_MAX,
    progressColor: theme.current.value.colors.primary,
    waveColor: theme.current.value.colors['on-surface'],
    url: 'https://xxxx',
    plugins: [
      new MinimapPlugin({
        barWidth: 2,
        barGap: 1,
        container: minimapRef.value,
        dragToSeek: true,
        overlayColor: theme.current.value.colors.primary + '60',
        progressColor: theme.current.value.colors.primary,
        waveColor: theme.current.value.colors['on-surface'],
      }),
      new TimelinePlugin({
        formatTimeCallback: (seconds) => {
          return hms(seconds);
        },
        insertPosition: 'beforebegin',
      }),
      new ZoomPlugin({ scale: 0.5, maxZoom: 100 }),
      snippetPlugin,
    ],
  });
```

## Expected result
The waveforms should line up visually.

## Obtained result
The unplayed waveform is lower than it should be.

## Screenshots

https://github.com/katspaugh/wavesurfer.js/assets/12532733/d1215ae9-eea0-4188-8ffd-6a0ab078f548

**Comment by katspaugh** [comment]
Thanks Sam! There was indeed a regression affecting waveforms with a timeline positioned on top but it should be now back to normal in 7.7.8.

**Comment by ffxsam** [comment]
Hey! Sorry for the lack of clarity in my issue. I narrowed it down to 7.7.7 being the culprit, but I'm still seeing this behavior in 7.7.8.

**Comment by ffxsam** [comment]
Oddly enough, the region is also overlapping the UI outside of where the waveform should exist. This didn't occur previous to 7.7.7.

![CleanShot 2024-04-05 at 15 19 17](https://github.com/katspaugh/wavesurfer.js/assets/12532733/2c5d1679-4c22-4291-aca1-304ce0faab26)

**Comment by katspaugh** [comment]
I see, thanks! I'll check!

**Comment by ffxsam** [comment]
@katspaugh Thank you so much!
