### ISSUE TITLE
Modifying DrawWave Method

### ISSUE THREAD

**Issue by morganwildermuth** [katspaugh/wavesurfer.js#364]
I asked about the best way to modify the wave form to mimic a phonocardiogram previously (https://github.com/katspaugh/wavesurfer.js/issues/288) and recently began working on my solution. I thought it would be rather straightforward to modify the original drawWave method: graph without the mirroring and stroke rather than fill. However, the resulting graph is disjointed and "spotty". 
![screen shot 2015-02-23 at 10 12 27 am](https://cloud.githubusercontent.com/assets/4300267/6335490/dc79ddfc-bb50-11e4-847b-da745b84db43.png)

I've spent the past hour researching this with very little success; any idea of what the issue is or where I should focus my search? This is my first time dealing directly with Canvas, so thanks for any and all help/direction!

**Comment by morganwildermuth** [comment]
To be more specific, I changed this code from your drawWave method

            cc.beginPath();
            cc.moveTo($, halfH);

            for (var i = 0; i < length; i++) {
                var h = Math.round(peaks[i] * coef);
                cc.lineTo(i * scale + $, halfH + h);
            }

            cc.lineTo(this.width + $, halfH);
            cc.moveTo($, halfH);

            for (var i = 0; i < length; i++) {
                var h = Math.round(peaks[i] * coef);
                cc.lineTo(i * scale + $, halfH - h);
            }

            cc.lineTo(this.width + $, halfH);
            cc.fill();

            // Always draw a median line
            cc.fillRect(0, halfH - $, this.width, $);
        }, this);

to

            cc.beginPath();
            cc.moveTo($, halfH);

            for (var i = 0; i < length; i++) {
                var h = Math.round(peaks[i] * coef);
                cc.lineTo(i * scale + $, halfH - h);
            }

            cc.stroke();

            // Always draw a median line
            cc.fillRect(0, halfH - $, this.width, $);
        }, this);

**Comment by morganwildermuth** [comment]
It's likely another part of the code interacting with my changes that are causing the issues. I took out the core change I made and just used that to create a fiddle and there's no issue with that; something else must be being called that destroys parts of the waveform. 

https://jsfiddle.net/morgwild/7x3wyhxh/1/

**Comment by morganwildermuth** [comment]
I am a silly. Pixel ratio. Thanks.

**Comment by katspaugh** [comment]
:ok_hand:
