### ISSUE TITLE
Initial height of the playhead wrong

### ISSUE THREAD

**Issue by thijstriemstra** [katspaugh/wavesurfer.js#365]
Since the latest version the initial playhead is always rendered at some default height:

![schermafbeelding](https://cloud.githubusercontent.com/assets/305679/6357085/18c6ec5c-bc62-11e4-8a1a-abb1b8032e89.png)

And then once the waveform rendering is ready, it adjusts to the expected height:

![schermafbeelding](https://cloud.githubusercontent.com/assets/305679/6357101/33c01754-bc62-11e4-97e1-3169ddd2a608.png)

Test it with a large audio file so it'll take a while to render so you can clearly see the difference.

**Comment by katspaugh** [comment]
Yes, I can reproduce it. Good catch!

**Comment by katspaugh** [comment]
Thanks, Thijs, this should be OK now.
