### ISSUE TITLE
URGENT Wavesurfer package not accessible

### ISSUE THREAD

**Issue by Gigamick** [katspaugh/wavesurfer.js#3650]
https://unpkg.com/wavesurfer.js@7/dist/wavesurfer.esm.js

and

<script src="https://unpkg.com/wavesurfer.js@7"></script>

giving Cloudflare error

**Comment by katspaugh** [comment]
Works for me.

Alternative CDNs:
* https://cdnjs.com/libraries/wavesurfer.js
* https://www.jsdelivr.com/package/npm/wavesurfer.js
* http://esm.sh/wavesurfer.js

**Comment by Gigamick** [comment]
<img width="1129" alt="Screenshot 2024-04-12 at 10 49 25" src="https://github.com/katspaugh/wavesurfer.js/assets/22120297/17a99330-c4e8-478f-bb9a-f012f92d1e83">

Thanks for the alternatives

**Comment by katspaugh** [comment]
I'm seeing a 520 now as well :\

**Comment by Gigamick** [comment]
Very annoying but I guess this happens. I've now built in about 4 layers of redundancy.

Thanks for the quick response. I was panicking. Woke up to a bunch of user complaint emails.
