### ISSUE TITLE
feature request: certain docs would benefit from table of contents

### ISSUE THREAD

**Issue by Johnrobmiller** [katspaugh/wavesurfer.js#3677]
As the title says, there is no information on how to install plugins for most users. I say "for must users" because there is, technically speaking, documentation on how to install them using <script> tags (https://wavesurfer.xyz/plugins/). However, probably nearly all devs these days use frameworks like next.js that do not use <script> tags. Therefore, for almost all users, the docs are incomplete and users have no way of knowing how to install plugins.

Maintainers ought to update documentation to reflect this.

**Comment by Johnrobmiller** [comment]
Closing, it's implmeneted by default

**Comment by Johnrobmiller** [comment]
EDIT: I see that further down in those docs there actually is information on to use plugins in NPM.

In that case, it might be helpful to introduce some table of contents, sidebar, etc., anything that gives the reader an idea of what is contained within the docs. Users do not read docs from top to bottom, and if they skim the docs they might miss key information as I did.

**Comment by entonbiba** [comment]
@Johnrobmiller better to add this as a discussion feature request item here
https://github.com/katspaugh/wavesurfer.js/discussions
