### ISSUE TITLE
No longer possible to implement the `MutliCanvas` renderer

### ISSUE THREAD

**Issue by Johnrobmiller** [katspaugh/wavesurfer.js#3678]
Please see: https://github.com/katspaugh/wavesurfer.js/issues/850#issuecomment-2083056000

I see that the new wavesurfer options no longer contains `renderer`. This destroys the option to use MultiCanvas, does it not? Or, if this is not true, then there appears to be no documentation telling users how to implement it, which is also an issue.

**Comment by katspaugh** [comment]
If you’re looking for a way to implement custom rendering, the `renderFunction` is the way to do it in v7.

See this example: https://wavesurfer.xyz/examples/?custom-render.js
