### ISSUE TITLE
Locking screen stops playback on iOS Safari

### ISSUE THREAD

**Issue by lff5** [katspaugh/wavesurfer.js#3679]
## Bug description
The audio stops when I lock the screen on iOS Safari.

I tried all the [examples](https://wavesurfer.xyz/examples/). The examples continue play with locked screen except [Webaudio example](https://wavesurfer.xyz/examples?webaudio.js). This is not expected, but this is not my main concern, since I need to avoid WebAudio.

I need player with playlist, so i tried [the playlist example](https://wavesurfer.xyz/example/playlist/) and it stops when I lock the screen! I checked the source, its not using WebAudio backend.

## Environment
iOS 17.4.1 iPhone 12 Safari 17

## Minimal code snippet
Just open https://wavesurfer.xyz/example/playlist/ in iOS Safari, start playing and lock the screen.
Additionally try out https://wavesurfer.xyz/examples?webaudio.js, it stops too and doesnt produce any audio on MacOS 13.3 Safari 16.4.

## Expected result
The audio should continue playing.

## Obtained result
The audio stops immediately, there is no player controls in control center.

**Comment by katspaugh** [comment]
https://wavesurfer.xyz/example/playlist/ is a legacy example as it's based on v6 wavesurfer. The new examples where you couldn't reproduce the bug are based on wavesurfer v7. 

You should be able to reuse the [playlist code](https://wavesurfer.xyz/example/playlist/app.js) with v7, just update the import.
