### ISSUE TITLE
Unexpected playback results with Playlist example

### ISSUE THREAD

**Issue by michaeldzjap** [katspaugh/wavesurfer.js#368]
Hi,

Not sure if this is a bug or intended behaviour, but it doesn't seem to make logical sense to me anyway. I have noticed that under certain circumstances the order of playback in the Playlist example gives rather unexpected results. 

Correct behaviour:
If on page load you simply do nothing and listen to the three examples from start to finish (or even when skipping to the end of a track, just before it starts playing the next in the playlist automatically), the order of operations is as you would expect: after the last track in the playlist finishes, nothing happens and the last link in the playlist keeps being highlighted/selected.

Inconsistent behaviour:
In comparison; if on page load you select the third track before the first track finishes playing, and then wait until the third track finishes playing by itself (or by skipping to the end manually) for some strange reason playback doesn't simply halt, but instead the second track gets selected and starts playing.

Again, not completely sure if this is a bug or intended behaviour, but it seems rather strange to me. Just thought I would flag it up. Tested it on latest Chrome and Firefox.

Thanks for your help.

**Comment by katspaugh** [comment]
Thanks, this is very interesting!

**Comment by katspaugh** [comment]
Michael, this should be fixed now. Thank you!

**Comment by michaeldzjap** [comment]
Great! Thanks a lot for all your work on this. Much appreciated.
