### ISSUE TITLE
the wavesurfer.js container cannot have `width: fit-content`

### ISSUE THREAD

**Issue by Johnrobmiller** [katspaugh/wavesurfer.js#3681]
I replicated this on a forked version of wavesurfer where I ran `npm run start` to start the local examples.

If the body, i.e., the wavesurfer's container, is given `width: fit-content`, then the wavesurfer will start flicering and redrawing in an infinite loop.

**Comment by entonbiba** [comment]
@Johnrobmiller wrap it with fit-content outside the wavesurfer container instead. Do you have a sample to view online?

```
<div> // fit-conent css to this div
<wavesurver>
</div>
```

**Comment by katspaugh** [comment]
Wavesurfer requires a width to render, so it either takes the width of the container, or a fixed width from the options. E.g.

```
WaveSurfer.create({
  container: '#waveform',
  width: 300
})
```

If you set the container to have `width: fit-content` and no width for wavesurfer, it won't render anything as the container will have an initial width of 0px.
