### ISSUE TITLE
Multitrack not playing audio on iOS 17.4.1

### ISSUE THREAD

**Issue by pierluigi** [katspaugh/wavesurfer.js#3686]
## Bug description

No audio is heard when playing back the [multitrack example](https://wavesurfer.xyz/examples/?multitrack.js) on iOS 17.4.1 Safari.

**Note:** the audio works fine on iPadOS Safari 17.4.1

## Environment
 - Browser: tested on Safari (iOS 17.4.1 ❌ , iPadOS 17.4.1 ✅ ) 
 -

## Minimal code snippet
n/a

**Comment by katspaugh** [comment]
Thanks, this was already reported in #3542
