### ISSUE TITLE
`relativeY` in `click` and `dblclick` events does not have the correct value

### ISSUE THREAD

**Issue by joaopslins** [katspaugh/wavesurfer.js#3687]
## Bug description

Seems like due to a copy-paste the `y` variable is not initialized with the correct value.

https://github.com/katspaugh/wavesurfer.js/blob/43adad5e07654a0f2006f27603207f083db92a68/src/renderer.ts#L75-L82

`const y = e.clientX - rect.left`
Perhaps should have been:
`const y = e.clientY - rect.top`

## Environment
 - Browser: Chrome

## Expected result
`y` value should be correct

## Obtained result
`y` value is not correct

**Comment by katspaugh** [comment]
Oh good catch 🙈
Please feel free to open a PR, I’ll get to it on the weekend otherwise.
