### ISSUE TITLE
getCurrentTime() fails as tracks are ending

### ISSUE THREAD

**Issue by Johnrobmiller** [katspaugh/wavesurfer.js#3708]
I have a track whose duration is `6.81795`, as logged using `ws.getDuration()`. I am also logging `ws.getCurrentTime()` on the `timeupdate` event.

The final log of `ws.getCurrentTime()` is `6.795971`, which is incorrect. It ought to be `6.81795` because the track ended and this was the final time. When a track finishes, calls to `getCurrentTime()` should not be misleadingly reporting any time that is not the final time.

Note, although the call to `getCurrentTime()` is accurate in the `finish` event, the last call to `getCurrentTime` in the `timeupdate` event still ought to equal the song duration because, when a track finishes playing, that is a time update.

**Comment by katspaugh** [comment]
I think this is something to blame the HTMLMediaElement for. We could add a workaround by artificially emit a final event with the exact value of the total duration, though.
