### ISSUE TITLE
Canvas wave image disappears when tab is changed (occurred after the latest chrome update)

### ISSUE THREAD

**Issue by canferman** [katspaugh/wavesurfer.js#3713]
## Bug description
Canvas wave image disappears when tab is changed, occurred after the latest chrome update.

I thought the problem was only in my project, but I saw that the same problem was also present in the wavesurfer examples pages.

## Environment
- OS: Windows, MacOS, Android
Browsers: 
- on windows Chrome: 124.0.6367.225 and 125.0.6422.61 
- on Android Chrome 124.0.6367.179
- on Mac: unknown (feedback from friends)

## Minimal code snippet
available in the codes on all sample pages
[https://wavesurfer.xyz/examples/](https://wavesurfer.xyz/examples/)

## Expected result
The wave view should remains the same before changing tab

## Obtained result
Canvas wave image disappears when tab is changed

## Screenshots
![Screenshot_18](https://github.com/katspaugh/wavesurfer.js/assets/7466948/9dfb060d-6e65-4956-ae64-2229125f4c93)

**Comment by katspaugh** [comment]
What Chrome version is it and what OS? I don’t have this in v126

**Comment by Antonio-Ramon** [comment]
I'm having the same issue, my chrome version is v125.0.6422.60

**Comment by gitdrums** [comment]
Same here

**Comment by gitdrums** [comment]
Same here

**Comment by canferman** [comment]
i) environment info updates on main issue entry

**Comment by canferman** [comment]
i also create an issue on chromium issues: [https://issues.chromium.org/issues/341803761](https://issues.chromium.org/issues/341803761)

**Comment by canferman** [comment]
this bug seems to be solved on Windows wit latest Chrome 125.0.6422.77 and on macos 14.2.1 with latest Chrome 125.0.6422.112

**Comment by katspaugh** [comment]
Thanks @canferman! 🙏

**Comment by omerman** [comment]
Thank you so much!!
