### ISSUE TITLE
Zoom+Regions example shrinks vertical, not just zooms horizontal (Chrome for Mac)

### ISSUE THREAD

**Issue by drscotthawley** [katspaugh/wavesurfer.js#3714]
## Bug description
I've noticed that, when using Chrome or Brave,  in both my own code that uses Regions and the [Regions Demo](https://wavesurfer.xyz/examples/?regions.js), if I move the "Zoom" slider in & out while the audio is playing, the waveform shrinks _vertically_.  And it keeps shrinking the more you move the slider back & forth  to the point where the waveform's  vertical extent approaches that of  a horizontal line. (Screenshot Below) 
<img width="630" alt="Screenshot 2024-05-20 at 2 51 02 PM" src="https://github.com/katspaugh/wavesurfer.js/assets/13925685/1b00a7c7-f878-4c2c-808f-93b3c949bb70">

This strikes me as unexpected behavior, as having the waveform get smaller & smaller as one adjusts a horizontal slider (and never rescaling back to full height) can pose a problem for repeated usage.  

I don't notice any such behavior with the regular Zoom example https://wavesurfer.xyz/examples/?zoom.js
So, somehow the inclusion of Regions is related to this.

## Environment
 - Browsers: 
     - Chrome Version 124.0.6367.208 (Official Build) (arm64) for MacOs
     - Brave Version 1.66.110 Chromium: 125.0.6422.60 (Official Build) (arm64)] for MacOs
 - Does _not_ happen with Safari
 

## Minimal code snippet

https://wavesurfer.xyz/examples/?regions.js

## Steps to reproduce
1. Go to Regions example.  
2. Click on the first region marked "Resize me" to begin playing audio.
3. While audio is playing, move the Zoom slider back & forth.
4. Observe that waveform shrinks vertically as you do this.

## Expected result

Zooming horizontally, i.e., changing pixels-per-second, would not result in (irreversible) changes to the vertical extent of the overall waveform.  

## Obtained result
Tiny vertical extent to waveform after repeated zooms in & out, with no way to restore full height. 

## Screenshots
<img width="630" alt="Screenshot 2024-05-20 at 2 51 02 PM" src="https://github.com/katspaugh/wavesurfer.js/assets/13925685/d3faa68f-b29d-4307-8e28-a64129d6a20f">

**Comment by drscotthawley** [comment]
Just updated to Chrome Version 125.0.6422.61 (Official Build) (arm64) and the problem went away! 

Brave is at the latest version and still shows problematic behavior, but presumably they'll push an update in the next week. 

Since this behavior is demonstrably browser-(version-)specific, this Issue is seems worthy of closing immediately.  
Feel free to close.

**Comment by katspaugh** [comment]
Thanks! Good to know!
