### ISSUE TITLE
loadBlob() error -- inserts the string "blob" into the <audio> element's src

### ISSUE THREAD

**Issue by Johnrobmiller** [katspaugh/wavesurfer.js#3716]
This is probably the same bug reported here, but there's no way to know for sure: https://github.com/katspaugh/wavesurfer.js/issues/3672

As seen in the screenshot, when I use `loadBlob()`, it inserts the string "blob" into the \<audio\> src. I see that the browser treats this as a link to `/blob`, but there is no such resource. Navigating to that resource results in 404. 

I am using Next.js

I am using `loadBlob()` like this, where `ws` is a WaveSurfer instance and `data` is of type `Blob`. 

Code: `ws.loadBlob(track.data)`

![image](https://github.com/katspaugh/wavesurfer.js/assets/55205360/083decd0-54b4-4df3-9503-e00c3ff4f22b)

**Comment by katspaugh** [comment]
Thanks for the report!
Looks like it’s coming from this line: https://github.com/katspaugh/wavesurfer.js/blob/main/src/wavesurfer.ts#L475
