### ISSUE TITLE
Setting height to "auto" with a timeline causes wavesurf to expand indefinitely

### ISSUE THREAD

**Issue by rodsmyname** [katspaugh/wavesurfer.js#3723]
### Discussed in https://github.com/katspaugh/wavesurfer.js/discussions/3722

<div type='discussions-op-text'>

<sup>Originally posted by **rodsmyname** May 29, 2024</sup>
This looks like a bug, but any advice would be great.

Simply setting height to "auto" during initialization and having the timeline plugin (at the bottom) causes wavesurfer to expand vertically indefinitely. This can be seen in the Timeline plugin example:
<img width="1108" alt="Screenshot 2024-05-29 224143" src="https://github.com/katspaugh/wavesurfer.js/assets/111706981/822f5163-d413-45a3-a459-c3812ae13576">

 </div>

**Comment by rodsmyname** [comment]
It doesn't seem to be related to the timeline plugin actually. Setting it to auto causes it to keep expanding regardless of the plugin. A fix on this would be great as I would really like to get the waveform to expand with the height of the div it is in.

I also noticed that the wavesurfer does not shrink vertically after the screen is resized, I am not sure if it is related but it could be due to this bug.

**Comment by katspaugh** [comment]
Indeed, thank you! That's quite a bizarre effect! :) I'll prioritize this for the next release.
