### ISSUE TITLE
loadBlob throws uncaught error when blob.size === 0

### ISSUE THREAD

**Issue by romarybi** [katspaugh/wavesurfer.js#3726]
## Bug description
The bug occurs when a blob with size 0 is loaded. An uncaught error is thrown in player.setSrc(). I found the bug by using the recorder plugin. Sometimes, when the recording is stopped almost immediately, a blob of size 0 is created. After it is loaded into the player 2 possible errors occur depending on the backend option. If HTMLMediaElement is used, the error is "ERR_REQUEST_RANGE_NOT_SATISFIABLE". If WebAudio is used, the error is "DOMException: Failed to execute 'decodeAudioData' on 'BaseAudioContext': Unable to decode audio data".

I can make a pull request if you like but I'm not sure how you want to solve this issue. Either the client/plugin (in this case record plugin) should check that the blob they are loading is playable or setSrc could be changed to something like

```
const newSrc =
      blob instanceof Blob && blob.size > 0 && (this.canPlayType(blob.type) || !url) ? URL.createObjectURL(blob) : url
```

## Environment
 - Browser: Chrome

## Minimal code snippet
```
import WaveSurfer from 'wavesurfer.js'

const wavesurfer = WaveSurfer.create({
  container: document.body
})
const emptyAudioBlob = new Blob([], { type: 'audio/webm;codecs=opus' });
wavesurfer.loadBlob(emptyAudioBlob)
```

## Expected result
The expected result is for no uncaught error to be thrown.

**Comment by katspaugh** [comment]
Thanks for the report!

The way I would suggest to handle this would be to properly reject the loadBlob promise in this case. So I would wrap setSrc into a try-catch and rethrow an async error from the load function. This way you can catch all possible errors from loadBlob and load alike in your application code.

**Comment by romarybi** [comment]
Thanks for the feedback. Upon further investigation, I found that the actual issue was fixed in the latest commit already and the problem is simply a mismatch between the repo and npm versions.

**Comment by katspaugh** [comment]
Thanks! I'll soon publish the current dev version.
