### ISSUE TITLE
misaligned played waveform

### ISSUE THREAD

**Issue by tomByrer** [katspaugh/wavesurfer.js#373]
![wavesurfer-scroll](https://cloud.githubusercontent.com/assets/1308419/6406982/f9dfb91a-bdf4-11e4-80c0-80247732dd1a.gif)
Happens whenever there is a scrollbar.  Likely read if scrollbar is available [here](https://github.com/katspaugh/wavesurfer.js/blob/master/src/drawer.js#L153) & adjust if needed.  It is tricky, IIRC different OS & browsers have different scrollbar widths (& are user-adjustable)?  Not sure if non-native scrollbar is the best.

I don't remember this bug when I first found wavesurfer a few months ago?

Win 7, Chrome & Fx

**Comment by shirshendu** [comment]
I'm getting the same problem on Ubuntu chrome and firefox; is it related to #367 ?
![image](https://cloud.githubusercontent.com/assets/1880361/6440068/70a1cd7e-c0ff-11e4-881d-86230a9062e5.png)

**Comment by katspaugh** [comment]
Thanks, guys! Should be in order now.
