### ISSUE TITLE
ReferenceError: Can't find variable: ResizeObserver

### ISSUE THREAD

**Issue by maxiedaniels** [katspaugh/wavesurfer.js#3732]
Our users that are on Safari 12 seem to be getting this error, but I can't find anything about ResizeObserver on here. We're using Wavesurfer 7.7.15. From googling, it sounds like this could be to do with polyfills but I don't really know what that is to be honest. Hoping someone can point me in the right direction!

**Comment by katspaugh** [comment]
I’m surprised there are still Safari 12 users. It came out in 2018. :)
It should be easy to fix though.

**Comment by katspaugh** [comment]
Yes, you can load a polyfill on your end but I was talking about adding an if in wavesurfer code.
