### ISSUE TITLE
No onReady event firing in React when using pre-computed peaks

### ISSUE THREAD

**Issue by njbair** [katspaugh/wavesurfer.js#3744]
## Bug description
When using `@wavesurfer/react` with pre-computed peaks, the onReady event is never triggered, so there's presumably no occasion to bind the wavesurfer object to state, and thus no opportunity to initialize other controls.

## Environment
 - Browser: Chrome

## Minimal code snippet
Clone this demo repo https://github.com/njbair/wavesurfer-react.git then run `npm start` and browse to _localhost:3000_. Open dev tools to monitor the JS console.

## Expected result
We should get a `ready` event when the file loads.

## Obtained result
- We do not get a `ready` event when the file loads.
- In the version without peaks, the `ready` event is triggered.
- In the Vanilla JS versions, both with and without peaks, the `ready` event is triggered.
- It's not included in this demo repo, but I first encountered this bug while using the `useWavesurfer` hook instead of the `WavesurferPlayer` component. This makes sense to me, since the component is just a basic wrapper around the hook.

## Screenshots
Here is a screenshot of the console only displaying `redraw` and `redrawcomplete` events:

![screenshot](https://github.com/njbair/wavesurfer-react/blob/main/screenshot.png?raw=true)

**Comment by njbair** [comment]
Additional info: my suspicion is that this is a race condition between mounting the component and loading the audio. Since pre-calculated audio loads basically instantly, it looks like the wavesurfer library is emitting the `ready` event before the React component subscribes to it.

I'm testing out a local copy of both _@wavesurfer/react_ and _wavesurfer.js_, adding some console output to confirm my suspicions, and it does indeed look like that's what's happening here:

<img width="369" alt="Screenshot 2024-06-14 at 8 51 26 PM" src="https://github.com/katspaugh/wavesurfer.js/assets/707119/8359a388-6001-4fd6-8061-c098b9d04b66">

**Comment by katspaugh** [comment]
I believe this was fixed in wavesurfer.js, the react package just needs to be updated.

**Comment by njbair** [comment]
> I believe this was fixed in wavesurfer.js, the react package just needs to be updated.

The React package seems to do very little other than pulling in the wavesurfer.js core library and then React-ifying it.

I wonder if there's a way to wrap the wavesurfer `ready` event in a promise, then have that promise handled by useEffect? You would also need to defer loading of the URL until after that event is fired.

Looking at the wavesurfer.js API, I don't see a good place for useEffect to hook into. If you have any suggestions, I would be happy to take a stab at a PR to address this.

Thanks.

**Comment by katspaugh** [comment]
AFAIR this event is already promisified, even with predecoded peaks. Probably use effect is still being triggered too late.

**Comment by katspaugh** [comment]
@njbair a fix is now live in 7.8.1. Cheers!
