### ISSUE TITLE
minimap fails to load occasionally

### ISSUE THREAD

**Issue by maxehnert** [katspaugh/wavesurfer.js#376]
I am still working on localhost but the minimap seems to come and go as I make changes and reload the page. I work in the plugin files a lot (timeline and regions) but I can't see how that would affect it. When it isn't loading I see a straight line in the minimap but the main section is still fine. 
I'm on 1.0.16

**Comment by thijstriemstra** [comment]
We're on 1.0.22 now, try updating first.
