### ISSUE TITLE
Incorrect calculation of waveform canvas width if devicePixelRatio != 1

### ISSUE THREAD

**Issue by baldvic** [katspaugh/wavesurfer.js#3771]
## Bug description
Waveform canvas width calculated incorrectly if devicePixelRatio != 1, i.e. changing browser window zoom.
Origination of bug is that devicePixelRatio  is applied twice.

## Environment
 - Browser: Chrome

## Expected result

![image](https://github.com/katspaugh/wavesurfer.js/assets/63738362/0e179dd0-f596-428c-81ee-e2ae5e624bd1)

## Obtained result

![image](https://github.com/katspaugh/wavesurfer.js/assets/63738362/22205fab-3f99-4520-96f9-7c0528875462)

## Root cause

![image](https://github.com/katspaugh/wavesurfer.js/assets/63738362/571d7b86-9f38-4f06-ae15-713577e87a2e)

render() -> renderChannel() -> renderMultiCanvas() -> renderSingleCanvas()

![image](https://github.com/katspaugh/wavesurfer.js/assets/63738362/792af0ef-ef40-4298-add0-3bd5671f8f0e)

As result, if  devicePixelRatio  less than 1 it reduces final canvas width and makes it smaller than wrapper div

**Comment by katspaugh** [comment]
Good catch!

**Comment by katspaugh** [comment]
Should be fixed in 7.8.1. Thank you!

**Comment by baldvic** [comment]
Confirmed. Thank you!
