### ISSUE TITLE
Feature Request: RegionsPluginEvents -> region-update

### ISSUE THREAD

**Issue by ndeshpande2022** [katspaugh/wavesurfer.js#3779]
We currently have the region-update**D** event that is fired by the region plugin. I was wondering how tricky it would be to also expose "region-update" in order to trigger other functions when a region is being updated (in our case the user drags a region on the timeline). 

This event could be de-bounced as well to only fire every 200ms if it introduces performance issues.

Please let me know any thoughts.

**Comment by katspaugh** [comment]
Sure, makes sense! I will add the new event.

**Comment by katspaugh** [comment]
The `region-update` is now available in 7.8.2 📦. Cheers!
