### ISSUE TITLE
When playing a region, the cursor stops slightly after the end

### ISSUE THREAD

**Issue by jlegoff** [katspaugh/wavesurfer.js#379]
Hi!

I am using wavesurfer's region plugin and I want to be able to play a given selected region. That is, I want the playback to start at the beginning of the region and to stop right at the end. What I noticed is that, many times, the progress bar stops slightly after the end of the region.

After tinkering with the code for a while, I think the problem is the following: wavesurfer.play(start, end) calls backend.play(start, end) in order for the media to play; but the drawing of the progress is handled in restartAnimationLoop, which does not have the start/end parameters. What I think happens is that the requestFrame callback gets called more often than the timeupdate event is fired by the mediaelement. Therefore the progress bar gets painted slightly after the end of the region is reached and stops when timeupdate is fired with time > end.

In order to fix it, I added the start / end parameters to restartAnimationLoop and did something like:

```javascript
if (!my.backend.isPaused() && my.backend.getCurrentTime() <= end) {
  my.drawer.progress(my.backend.getPlayedPercents());
    requestFrame(frame);
}
```

If you think this is a proper way of fixing the issue, I'd be more happy to create a pull request.

**Comment by katspaugh** [comment]
Hi @jlegoff!

Sorry for the delayed reaction. I think we might remove `requestAnimationFrame` completely. Can you check with the commit above if the problem still reproduces?
