### ISSUE TITLE
[Regions] Clicking inside region does not seek

### ISSUE THREAD

**Issue by rorr31** [katspaugh/wavesurfer.js#3804]
Since upgrading from 7.7.11 to 7.8.2, seeking no longer works when clicking inside a region.  Clicking outside a region works fine.  I'm seeing this behavior in both Chrome and Edge.  On Firefox, clicking inside a region seeks the audio to that spot, as expected.

Prior to the upgrade, the audio would seek to the correct spot when clicking inside a region on all browsers.

**Comment by katspaugh** [comment]
Oh that's indeed a regression, thanks for the report! Likely a change in draggable.ts wrt the click handling.

**Comment by katspaugh** [comment]
I've just tested with this example and seems to work as expected: https://wavesurfer.xyz/examples/?48950705f7944e2406b9e41c9e0152cc

Can you create a minimal reproducible code example?

**Comment by rorr31** [comment]
When I have a chance, I will attempt to create a reproducible code example.  However, I was able to confirm that all versions 7.8 and above do not work as expected.  Reverting back to 7.7.15 solved the problem. 

Here is the code snippet that creates the regions:

```
				function addEditTimeRegion(turnItem, orderNo) {

					const
						id = turnItem.data('id'),
						start = convertMsToSeconds(turnItem.data('start-time-ms')),
						end = convertMsToSeconds(turnItem.data('end-time-ms')),
						audible = getAudible(turnItem.data('audible-id')) || null,
						colorProperty = turnItem.data('redacted-item-id') === undefined ? '--lw-review-source-translucent' : '--lw-review-error-translucent',
						content = getEditTimesContentHtml(turnItem.data('original-content'), audible);

					const options = {
						id: `${EDIT_REGION_ID_PREFIX}-${id}`,
						start: start,
						end: end,
						color: getComputedStyle(document.body).getPropertyValue(colorProperty),
						content: content
					};

					const region = wsRegions.addRegion(options);

					region.attributes = {
						turnItemId: id,
						orderNo: orderNo,
						origStart: start,
						origEnd: end,
						anchor: false,
						otherRegions: []
					};

					region.on('update', () => {
						moveTimes(region);
					});

					region.on('update-end', () => {
						updateTimes(region);
					});
				}
```

This snippet is the same regardless of what version of wavesurfer is used.  When clicking within a region with 7.7.15, the player seeks to that point in the audio and plays from there.  With 7.8.0 and above, nothing happens when I click in a region.  The audio continues playing.  I am also using the hover plugin.  I'm not sure if that would make a difference or not.

**Comment by katspaugh** [comment]
It might be related to the fact that you're setting a custom HTML element in the content. I'll test this use case.

**Comment by Olejqua** [comment]
Hey, everybody!
I am facing the same problem, is there any solution?
