### ISSUE TITLE
Spectrogram plugin does render old soundbuffer when loading other soundfile

### ISSUE THREAD

**Issue by xtroce** [katspaugh/wavesurfer.js#381]
The spectrogram plugin still uses the soundbuffer of the soundfile when a new sound is loaded with the load statement. the render function should reload wavesurfers buffer to redraw the new sound instead of the old one.

**Comment by akreal** [comment]
I'll take a look at it.

**Comment by akreal** [comment]
Hi @xtroce, now it should work correct.

**Comment by katspaugh** [comment]
Thanks! @xtroce please reopen if needs be. I haven't published the package yet, so to check you'll have to use the code from master.
