### ISSUE TITLE
Canvases rendering error when width is too high

### ISSUE THREAD

**Issue by Cyp-Leg** [katspaugh/wavesurfer.js#3815]
## Bug description
Same bug as mentionned in this issue : 
https://github.com/katspaugh/wavesurfer.js/issues/3682
When the Wavesurfer container is given a too large width (ie: +80000), only one canvas is rendered with this width instead of multiple canvas of `MAX_CANVAS_WIDTH`px, resulting in an error

This bug was fixed in 7.7.12 but seems to be present again in 7.8.2

## Environment
 - Browser: Chrome

## Minimal code snippet
```
const options = {
  container: 'body',
  height: 128,
  width: 80000,
  normalize: false,
  waveColor: '#ff4e00',
  progressColor: '#dd5e98',
  cursorColor: '#ddd5e9',
  cursorWidth: 2,
  url: '/examples/audio/audio.wav',
  mediaControls: true,
  sampleRate: 8000,
}

const wavesurfer = WaveSurfer.create(options)
```

## Expected result
Multiple canvas of smaller width 
<img width="913" alt="Capture d’écran 2024-08-09 à 16 36 22" src="https://github.com/user-attachments/assets/0735794a-ce08-4150-9cc3-41c4617763a6">

## Obtained result
Single canvas width huge width, resulting in display error
<img width="989" alt="Capture d’écran 2024-08-09 à 16 38 20" src="https://github.com/user-attachments/assets/cbc06deb-55d6-4a19-9b20-1e265b37ffa7">

## Screenshots
![Capture d’écran 2024-08-09 à 16 30 16](https://github.com/user-attachments/assets/e388d366-7e83-4887-8a01-c6faa9184181)

**Comment by katspaugh** [comment]
Thanks for the report!
