### ISSUE TITLE
Using minPxPerSec to create zoom

### ISSUE THREAD

**Issue by maxehnert** [katspaugh/wavesurfer.js#385]
I saw this brought up in an older merge [#132](https://github.com/katspaugh/wavesurfer.js/pull/132) and tried to implement it unsuccessfully. Is there a known way to use a slider or button to create a zoom in/out?

**Comment by katspaugh** [comment]
So, have you found out anything?

**Comment by maxehnert** [comment]
I just used a hack way around it by applying the same principle as what is used in the main example on the landing page. It takes the slider value and uses that for the url endpoint and then uses if statements to set the minPxPerSec value. 

Sorry for bad formatting, I'm not good with markdown.

`
$('#slider').on('slidechange', function () {
 $( "#slider" ).slider( "value" ) * 10;
  var selection = $( "#slider" ).slider( "value" ) * 10;
  location.href= '?' + selection;
}); `

**Comment by katspaugh** [comment]
Oh, I see, thanks go the info!

**Comment by maxehnert** [comment]
@katspaugh 

I've recently made some changes to how I was doing this zoom with the slider. I thought I would share incase it is helpful to others.

It now zooms just the waveform element, and does so without refreshing the page or anything weird (this was important since I'm loading audio files with a blob from the file system). I also set it up so that it will stay on the cursor location while zooming instead of defaulting back to the beginning of the file. 

The timeline scales correctly with this. I haven't found any problems so far.

Here's the code. I'll include everything, but the slider can be done any way you prefer. The important part is at the bottom of the javascript.

```javascript
/**
*** Zoom Slider
**/

$("#slider").each(function () {
      var  datamax = 100,
        amount = $(this).prev('.amount'),
        values = [0];
    $(this).slider({
        min: 10,
        max: datamax,
        values: values,
        step: 10,

        slide: function (event, ui) {
            amount.val(ui.values + "%");
        }
    });
    amount.val($(this).slider("values") + "%");
});

/**
*** Slider function for changing Canvas zoom
**/

$('#slider').on('slidechange', function () {

  var selection = $( "#slider" ).slider( "values" ) * 10;
  console.log(selection);

  // Set the new zoom value to the param
  wavesurfer.params.minPxPerSec = selection;

  // Redraw the waveform with the updated zoom value
  wavesurfer.drawBuffer();

  // Zoom in where cursor location is
  wavesurfer.seekAndCenter(
    wavesurfer.getCurrentTime() / wavesurfer.getDuration()
    );
});
```
HTML
```html
      <label for="amount" class="amount-label"><h4>Zoom</h4></label>
      <input type="text" readonly  class="amount">

      <div data-max="100" data-min="0" id="slider"></div>
```

**Comment by katspaugh** [comment]
Cool, thanks @maxehnert!

**Comment by maxehnert** [comment]
Ya that would be good. I can write up an example with a more simple slider so it's less distracting. Should it just be appended on an existing example or act as a stand alone example?

**Comment by katspaugh** [comment]
Maybe append to the Angular directive example, if you are familiar with angular. Otherwise, in order to keep basic examples simple, a separate page would be perfect.

**Comment by maxehnert** [comment]
Ok I made a new pull request. I made a new folder for it and used the annotations example as a base because I built in functions to redraw the annotations so they scale correctly also.
