### ISSUE TITLE
Type error in region "setOptions" function

### ISSUE THREAD

**Issue by jaredgei** [katspaugh/wavesurfer.js#3873]
## Bug description
The typescript type for region.setOptions requires "start" to be specified, even though there is specific code to handle "start" being undefined.

## Minimal code snippet
```region.setOptions({ color: getColor(word) });```
doesn't work ^

```region.setOptions({ color: getColor(word), start: region.start });```
works ^

## Obtained result
```Argument of type '{ color: string; }' is not assignable to parameter of type 'Omit<RegionParams, "minLength" | "maxLength">'.
  Property 'start' is missing in type '{ color: string; }' but required in type 'Omit<RegionParams, "minLength" | "maxLength">'.ts(2345)```

**Comment by katspaugh** [comment]
Thanks! We should probably add it to the omitted prop list.
