### ISSUE TITLE
Playback issues in Safari

### ISSUE THREAD

**Issue by lucastheis** [katspaugh/wavesurfer.js#3881]
## Bug description

I noticed `currentTime` jumping back in Safari shortly after playback starts. This does not seem to be an issue in Chrome, Firefox, or Edge. If it's a known issue, is there a workaround?

## Environment
 - Browser: Safari 17.5
 - OS: Mac

## Minimal code snippet

```
const wavesurfer = WaveSurfer.create(
	{
		container: '#waveform',
		url: './audio.wav',
	}
)

wavesurfer.on('interaction',
	() => {
		wavesurfer.play()
	}
)
```

## Expected result

Playback moving forward continuously and linearly.

## Obtained result

Playback jumps back. 

## Screenshots

The plot below visualizes 'timeupdate' events:
<img src="https://github.com/user-attachments/assets/49744638-9e44-430b-80db-a06a64c19290" width="320">

See also video below (no audio):
https://github.com/user-attachments/assets/c261b900-ed01-4a13-b527-bd058a7994db

**Comment by katspaugh** [comment]
That's a known quirk with the HTML media element in Safari. You'll see the same plot with a plain <audio> element. A workaround is to use `backend: 'WebAudio'`.
