### ISSUE TITLE
Unable to open https://wavesurfer.xyz/examples/ in Safari

### ISSUE THREAD

**Issue by sfc-gh-nbellante** [katspaugh/wavesurfer.js#3882]
## Bug description
I am struggling with getting the Recording plugin working (being able to download and playback the resulting file) on Safari, so I went to go try the examples in Safari, but am unable to load the page.

## Environment
 - Browser: Safari

## Minimal code snippet
visit https://wavesurfer.xyz/examples/

## Expected result
page loads

## Obtained result
page doesn't load

## Screenshots
<img width="601" alt="image" src="https://github.com/user-attachments/assets/a4b2bf8f-1e9c-4772-b0dc-a29ac2786d94">

**Comment by katspaugh** [comment]
I can open it fine. Probably some temporary issue.

**Comment by sfc-gh-nbellante** [comment]
must've been a transient issue! confirmed it is working now. thanks!
