### ISSUE TITLE
Internet Explorer

### ISSUE THREAD

**Issue by morganwildermuth** [katspaugh/wavesurfer.js#389]
If I wanted to support wavesurfer in IE without using flash where would I begin? I don't need to use the Web Audio component to analyze and retrieve sample points (I'm passing in an array), but I do need support for IE (down to IE8). I've been tinkering away for the past two days with very little progress. Any suggestions would be highly appreciated.

I'm 99% sure this support does not already exist as when I use browserstack to check out the wavesurfer.fm examples (including the fallback example), it's no dice. However, I could have overlooked something, so feel free to correct me.

**Comment by allannaranjo** [comment]
Take a look at the flash implementation from laurentvd:
https://github.com/laurentvd/wavesurfer.swf

**Comment by morganwildermuth** [comment]
I noticed that but I was hoping for a non-flash implementation. Honestly, don't even know if that's possible/reasonable, which is why I'm checking. I thought perhaps since I'm giving the points to draw rather than using Web Audio to analyze them that most of the issues could be solved without bringing in flash. In my code, the earliest failure point in the IE browser is when the event listeners aren't being called correctly which is what I'm currently working on.

**Comment by katspaugh** [comment]
It should work in IE9. IE8 would need es5-shim, some polyfill for addEventListener and maybe some other APIs.

**Comment by morganwildermuth** [comment]
I'm on IE11, Windows 8.1, looking at wavesurfer.fm. The canvas for the
default audio loaded on that example page is rendered but there is no
interaction available with the wave form (click to play from specific
location, for example) or play/pause/forward/toggle mute button. On the
media element fallback page, there is no canvas waveform displayed, but the
play/pause button exists. I checked it on both the remote machine I'm using
(via browserstack) and on my personal computer.

**Comment by katspaugh** [comment]
You need to look in the debugger what errors are being thrown and analyze each error individually. 

On wavesurfer.fm some things may break IE that are not in wavesurfer.js itself, but in the demo application. In the demos I was liberally using newish APIs like classList, dataset and so on. So I'd recommend making your own basic test page with the bare minimum features you need, and explore from there.

**Comment by morganwildermuth** [comment]
Kk, thanks for the advice. Now that I know it does work in that context
it's worth putting in that time; I was working off the assumption it did
not based on wavesurfer.fm.

Thanks again!

**Comment by X-Raym** [comment]
@morganwildermuth Hi ! I face the same issue (I have the array of peaks, but they are not loaded in IE), how did you solve that ? do you have any code to share ? :)

**Comment by kirilkirkov** [comment]
@X-Raym Hi, how do you resolve this problem?
