### ISSUE TITLE
Scroll Bar Automatically Returns to Cursor Position During Audio Playback

### ISSUE THREAD

**Issue by hagay3** [katspaugh/wavesurfer.js#3895]
## Bug description
Hi Team,

I've encountered an issue with Wavesurfer.js where the scroll bar behaves unexpectedly during audio playback. When the audio is playing, the scroll bar automatically returns to the cursor position, preventing manual scrolling. However, when the audio is paused, the scroll bar works as expected, allowing normal scrolling.

Steps to reproduce:
Play any audio using Wavesurfer.js.
Attempt to scroll while the audio is playing (the scroll bar jumps back to the cursor position).
Pause the audio.
Scroll functionality behaves normally without automatically resetting.

Tried also autoCenter: false with no luck
## Environment
 - Browser: Chrome

https://github.com/user-attachments/assets/45b2c889-fb43-4649-b7d6-77f829a620df

**Comment by katspaugh** [comment]
That’s the expected default behavior. You can add autoScroll: false to disable it.

**Comment by hagay3** [comment]
thanks @katspaugh
