### ISSUE TITLE
Waves get disappeared in Safari browser

### ISSUE THREAD

**Issue by salonirathod** [katspaugh/wavesurfer.js#3898]
-> Bug description
Waves are disappearing after continuously clicking on the waveforms of 5-6 different songs

-> Environment
 - Browser: Safari

-> Minimal code snippet

-> Expected result
     The waveform for each song should appear without disappearing after continuous clicks on 5-6 songs, while it works fine in chrome.

-> Obtained result
After clicking on waveforms of 5-6 different songs continuously, the waveforms disappear, and no further wave is displayed.

-> Screenshots
<img width="657" alt="Screenshot 2024-10-03 at 5 11 11 PM" src="https://github.com/user-attachments/assets/74c01490-a7c7-4e0a-a90d-c2232af1140c">

**Comment by katspaugh** [comment]
Sounds like a bug in your app. Please only report it if you can create a minimal reproducible example, ideally without react.
