### ISSUE TITLE
Waveform seems to freeze on sufficiently wide waveforms.

### ISSUE THREAD

**Issue by bobrenjc93** [katspaugh/wavesurfer.js#391]
Waveform doesn't seem to render for widths of 30k+ pixels

Works fine for sufficiently narrow waveforms.

Is there anyway we can configure the library to start drawing from left to write instead of all at once?

**Comment by katspaugh** [comment]
Duplicate of #47.

You can try setting smaller height and minPxPerSec. Also set pixelRatio to 1 if on Retina.

There's currently no Canvas-based frame-by-frame scrolling, but it's planned (see #47).
