### ISSUE TITLE
region-clicked Event Issue on Regions in WaveSurfer Zoomed State for Chrome and Safari

### ISSUE THREAD

**Issue by sug1no** [katspaugh/wavesurfer.js#3911]
## Bug description

- Load https://wavesurfer.xyz/examples/?regions.js
- Use the zoom slider to zoom in until scrolling is enabled.
- Click on a region to start playback: OK.
- Click on the region again:
  -  Firefox (on macOS, Ubuntu, and Windows 11): Playback starts from the beginning of the region, and the region color changes: OK.
  -  Chrome (on macOS, Ubuntu, and Windows 11) and Safari (on macOS): The region-clicked event does not fire: NG.

## Environment
 - Browser: please see above

## Minimal code snippet

please refer to the https://wavesurfer.xyz/examples/?regions.js

```js
...
regions.on('region-clicked', (region, e) => {
    e.stopPropagation() // prevent triggering a click on the waveform
    activeRegion = region
    region.play()
    region.setOptions({ color: randomColor() })
  })
...
```
## Expected result

Please refer to the above.

## Obtained result

Please refer to the above.

## Screenshots

ubuntu: chrome: 

The region-clicked event may does not fire.

<img src="https://github.com/user-attachments/assets/67028b40-d0ef-4d65-8017-3efaf7822c9f" height="200">

**Comment by ruchaheda** [comment]
I'm experiencing the same issue as well. I tested in Safari and Chrome and the event does not fire. I tested in Firefox and this works fine.

**Comment by Olejqua** [comment]
I have the same problem. 
Apparently it's the same problem with [this one](https://github.com/katspaugh/wavesurfer.js/issues/3804).

**Comment by Olejqua** [comment]
I've made a fix for this problem. @katspaugh please take a look.

https://github.com/katspaugh/wavesurfer.js/pull/3945
