### ISSUE TITLE
Cursor glitches in Safari

### ISSUE THREAD

**Issue by bobmulder** [katspaugh/wavesurfer.js#3921]
## Bug description

Hi @katspaugh. First of all: thank you for the awesome work put into this package. It helped me a lot and gave me lots of joy :).

I'm facing a little glitch in Safari. The issue occurs in my environment and in your demo's, so I assume it's a Wavesurfer.js thing.

When playin audio (especially short files), the cursor will glitch in the first 1-2 seconds, by going back a little. Then it continues like normal. 

The issue does not occur in Chrome.

Example from your demo:

https://github.com/user-attachments/assets/9bf45836-a512-4ab6-bdc8-c7ddbdfd5309

Example from my application:

https://github.com/user-attachments/assets/a64de20a-fadc-4b16-beb4-5a173ad3a7f5

Do you have any clue what causes this? I can't find anything in the issues, pull requests or discussion.

## Environment
 - Browser: Safari

## Minimal code snippet

For what it's worth:

```
const options = ref({
    height: 40,
    waveColor: '#B3B3B3',
    progressColor: '#FF9323',
    barGap: 2,
    barWidth: 1,
    barRadius: 8,
    cursorWidth: 10,
    cursorHeight: 2,
    duration: 80,
    dragToSeek: true,
    url: props.message.voice_message_url || "",
})
```

**Comment by katspaugh** [comment]
That’s unfortunately a known issue in Safari. You can fall back to `backend: "WebAudio"` as a workaround.

**Comment by bobmulder** [comment]
Thank you for the quick reply! Changing the `backend` made it work better. I'll do some extra research between the differences of both backends, but I think this solved it. Thank you again! 💪
