### ISSUE TITLE
Wavesurfer incorrectly destroyed / recreated (RangeError: invalid array length)

### ISSUE THREAD

**Issue by grudus** [katspaugh/wavesurfer.js#3923]
## Bug description

Hi
I have problem with wavesurfer after I destroy it and recreate on a page. Consider the following scenario:
1. User clicks the button to start recording (record plugin) -> initializing: WaveSurfer.create and RecordPlugin.create
2. User clicks the button to stop recording -> calling waveSurfer.destroy and recordPlugin.destroy
3. User clicks the button to start recording again ->  initializing: WaveSurfer.create and RecordPlugin.create.

Now what happens: When I reacreate the wavesurfer and try to draw it (3) I got `RangeError: invalid array length` exception in the `renderMultiCanvas.draw` function and the page freezes.

After some debugging I found out there is a problematic code:

```ts
// renderMultiCanvas function

const numCanvases = Math.ceil(totalWidth / singleCanvasWidth);
        // Render all canvases if the waveform doesn't scroll
        if (!this.isScrollable) {
            for (let i = 0; i < numCanvases; i++) {
                draw(i);
            }
            return;
        }

``` 

For some reason `singleCanvasWidth` is 0 so it draws infinitely. I can temporarily fix my use case by doing `const numCanvases = Math.ceil(totalWidth / singleCanvasWidth || 1);` but I know that's not the root case.

Additionally, if I add `console log` inside the `renderMultiCanvas` I can see it is invoked constantly even when I destroy the wavesurfer instance. 

## Environment
 - Browser: Chrome
 - Next js (12.2.5)
 - wavesurfer.js (7.8.4)

## Minimal code snippet

(Some code omitted to make it clearer) 

```tsx

    const visualisationRef = React.useRef<HTMLElement>(null)
    const waveSurfer = React.useRef<WaveSurfer>()
    const recordPlugin = React.useRef<RecordPlugin>()

    const cleanup = () => {

        if (recordPlugin.current) {
            if (recordPlugin.current.isRecording()) {
                recordPlugin.current.stopRecording()
            }
            recordPlugin.current.stopMic()
            recordPlugin.current.unAll()
            recordPlugin.current.destroy()
            recordPlugin.current = undefined
        }

        if (waveSurfer.current) {
            waveSurfer.current.empty()
            waveSurfer.current.unAll()
            waveSurfer.current.destroy()
            waveSurfer.current = undefined
        }
    }

    const initialize = () => {
        cleanup()

        waveSurfer.current = WaveSurfer.create({
            container: visualisationRef.current,
            barAlign: 'bottom',
            barWidth: 5,
            barRadius: 6,
            waveColor: '#fff',
            height: 48,
            cursorWidth: 0,
            barHeight: 4,
            barGap: 2,
            fillParent: true,
            hideScrollbar: true,
            interact: false,
            autoplay: false,
            mediaControls: false,
        })

        recordPlugin.current = waveSurfer.current.registerPlugin(
            RecordPlugin.create({
                renderRecordedAudio: false,
            })
        )
    }

    const startVisualisation = () => {
        initialize()
        recordPlugin.current?.startRecording()
    }

```

## Expected result

Library and plugin is correctly unmounted and it is possible to clean and rerun the initialization

**Comment by rnnyrk** [comment]
Running into this issue quite often as well. Not sure how to fix or what to do to prevent it from happening.

**Comment by TD-jizhijun** [comment]
Hi @katspaugh , today I also met the same error. Have you fixed this problem? I don't know the real reason. Could you give me some advice? (version: 7.8.5) Thanks in advance.
<img width="585" alt="image" src="https://github.com/user-attachments/assets/03fe17cd-dc0d-48ed-94de-dcc1ca594740">

**Comment by katspaugh** [comment]
Not fixed yet. Looks like an error in this function: https://github.com/katspaugh/wavesurfer.js/blob/main/src/renderer.ts#L515

**Comment by katspaugh** [comment]
@grudus thanks for the detailed bug report! 

> For some reason singleCanvasWidth is 0 so it draws infinitely

That seems to be indeed the problem. I've added an early return if the width is zero. Please let me know if the code in #3961 works for you. Cheers!
