### ISSUE TITLE
Timeline rendering zoom broken (7.8.8)

### ISSUE THREAD

**Issue by botoxparty** [katspaugh/wavesurfer.js#3937]
## Bug description

The timeline does not render correctly when zoomed in, particularly when it's scrolled. Video attached, and also a codesandbox to reproduce.

I have seen issue #3918 but I still have this problem on 7.8.8

## Environment
 - Browser: Chrome

## Minimal code snippet

https://codesandbox.io/p/sandbox/x9x2wr

## Expected result

The timeline is zoomed, scrolling, and visible as in the example on the wavesurfer.js documentation.

## Obtained result

As the timeline scrolls, it removes elements from the view that should be there.

## Screenshots

https://github.com/user-attachments/assets/84285583-9338-4f57-8a2e-2df61a5f5481

**Comment by katspaugh** [comment]
This was fixed in #3918.
