### ISSUE TITLE
Multitrack.js - Sometimes Audio is Out Of Synch

### ISSUE THREAD

**Issue by shayAiode** [katspaugh/wavesurfer.js#3944]
Im using WebAudio for the backend.

 - Browser: Chrome/Arc/Safari

General current time of multitrack obj - 
![image](https://github.com/user-attachments/assets/29160288-c2f5-4cf7-bc32-ef835022a37b)

1st track - 
![image](https://github.com/user-attachments/assets/c3cae7d1-6322-417e-a5b2-7f556db53501)

2nd track -
![image](https://github.com/user-attachments/assets/ee85bb6d-662c-4cd4-adca-b134334bc8c2)

What can we do to keep all tracks synch?

Most of the time its happening after adding new track to existing Multitrack instance (using addTrack func)

**Comment by katspaugh** [comment]
Please see https://github.com/katspaugh/wavesurfer-multitrack?tab=readme-ov-file#support
