### ISSUE TITLE
Website broken link in docs

### ISSUE THREAD

**Issue by SteveALee** [katspaugh/wavesurfer.js#3947]
## Bug description

on page `https://wavesurfer.xyz/docs/` there is a link to the options `[options](https://wavesurfer.xyz/docs/#wavesurfer-options)` but there is no such fragment on the page. 

Can't find any link to the options docs. Will check the source to find/

**Comment by SteveALee** [comment]
hmm, no sign of the website src in this repo - not even a branch. And no info I can find on where the repo is. 

PS thanks for a fantastic project - using in a tool to manage recording talking newspapers for the blind (charity)

**Comment by SteveALee** [comment]
Ahah - site is the readme and built examples. But I can't see a file for the options. Other that the [source](https://github.com/katspaugh/wavesurfer.js/blob/e7ceaf9c38fdbcb2930736c17ea9fc5d1641edf3/src/wavesurfer.ts#L10)

**Comment by SteveALee** [comment]
OK, after that I found https://wavesurfer.xyz/docs/types/wavesurfer.WaveSurferOptions.

**Comment by katspaugh** [comment]
I'll check if I can move it up, it's alphabetical atm.
