### ISSUE TITLE
Minimap display error

### ISSUE THREAD

**Issue by AndKiel** [katspaugh/wavesurfer.js#397]
Minimap overview region has wrong height in pixels. It should not be computed, it should be `height: 100%`.
Minimap progressCc canvas is misaligned. It should have `position: absolute` style applied.

Screenshot showing current state:
![zrzut ekranu 2015-03-13 o 12 44 07](https://cloud.githubusercontent.com/assets/953500/6637771/b434389c-c97e-11e4-8e31-557a6b22fbf9.png)

Screenshot after changes to style attributes:
![zrzut ekranu 2015-03-13 o 12 46 12](https://cloud.githubusercontent.com/assets/953500/6637796/f85cd8c6-c97e-11e4-8f47-0edb16c24b8f.png)

**Comment by katspaugh** [comment]
Seems to be related to #373. I'm not sure if it's the same bug.

**Comment by katspaugh** [comment]
Could you maybe make a pull request with your changes? The styles are applied in the file `drawer.canvas.css`.

**Comment by AndKiel** [comment]
In my application I've just made a quick fix by binding to `ready` callback this function (coffeescript):
```  
fixWaveSurferMinimap: ->
    $(@minimap.overviewRegion).css('height', '100%')
    $(@minimap.progressCc.canvas).css('position', 'absolute')
```
where `@minimap` is the instance returned by `@wavesurfer.initMinimap` function.
But this morning I've had some time to analyse wavesurfer's code and overview region height is `wavesurfer.minimap.js` in line 81, I think. As for progressCc.canvas it is `drawer.canvas.js`, line 43 (that's where position absolute should be applied).

**Comment by katspaugh** [comment]
Should be OK now.

**Comment by AndKiel** [comment]
Still not fixed. I've just updated wavesurfer js files in my project and disabled setting styles on `ready` event - nothing has changed:

![zrzut ekranu 2015-03-25 o 08 26 13](https://cloud.githubusercontent.com/assets/953500/6819874/acf4933a-d2c8-11e4-85db-8a206d279044.png)

Minimap progress waveform is still lower than it should be.
Overview still has calculated height instead of 100% (and the calculated value is lower by 2px than it should be in my case).

Also after updating wavesurfer js files my fix with setting `position: absolute` to `@minimap.progressCc.canvas` is not working anymore (minimap progress is not visible at all after setting that style).

**Comment by thijstriemstra** [comment]
@AndKiel any better with the latest version?

**Comment by zzswang** [comment]
This bug is still there.

**Comment by entonbiba** [comment]
This has already been fixed,
