### ISSUE TITLE
Straight-through connection retained when filters added with setFilters(filters)

### ISSUE THREAD

**Issue by nmgtn** [katspaugh/wavesurfer.js#400]
When you use `setFilters(filters)` to add some filters in the 'FX loop' kind of structure that wavesurfer seems to use, the analyser node at the start of the chain of filters remains directly connected to the gain node at the other end of the chain. This means that what you hear is the sum of the unprocessed sound and the sound going through the filter chain. Please excuse me if have misunderstood, and this is by design, but it looks to me like a bug!

## Audio graph, without filters
Without any filters set, analyser is connected directly to gain node, which is sensible:

![wavesurfer-fx-bypass_2](https://cloud.githubusercontent.com/assets/9980206/6648149/3edac49e-c9ce-11e4-8680-0178980b82b3.png)
(picture is Firefox visualisation of the audio graph on the [wavesurfer.fm home page](http://www.wavesurfer.fm/))

## Audio graph, with filters
Adding filters using the `setFilters` method (or `setFilter`)

### Expectation
Analyser node should be disconnected from gain node, and connected to first filter in the chain. Last filter in the chain should be connected to gain node. This means that audio is routed 100% wet through the filter chain.

### Observation
Analyser node retains its direct connection to gain node, and a connection is added to first filter in the chain. Last filter in the chain is connected to gain node, so you get 100% wet + 100% dry signal:

![wavesurfer-fx-bypass](https://cloud.githubusercontent.com/assets/9980206/6648148/3cd4e92c-c9ce-11e4-846f-5ce07301b9e7.png)
(picture is Firefox visualisation of the audio graph on the [panner filter example](http://www.wavesurfer.fm/example/panner/))

## A fix?

I can't see anything in the definition of `setFilters` which is supposed to disconnect analyser node from gain node before connecting each filter in turn. I considered adding a line to `disconnectFilters` to do this, but that doesn't really make sense. Perhaps it's best to add `this.analyser.disconnect()` immediately after [line 79 of webaudio.js](https://github.com/katspaugh/wavesurfer.js/blob/master/src/webaudio.js#L79).

I wanted to check with you that I've understood properly what is supposed to be happening, before I see about fixing the issue - please do let me know if I have misunderstood! If you agree that this is a bug, let me know any pointers you have for solving it and I'll put a pull request together.

**Comment by katspaugh** [comment]
Hi Andy,

Your analysis is correct and a fix is very welcome!

Thanks!

**Comment by nmgtn** [comment]
I will submit a pull request, I just want to be able to test it properly first.

I'm new to this whole workflow. Presumably I need to be testing the minified version that will be distributed? Can you tell me what I should use to get from the individual files in the `/src` directory to the   files in the `/dist` directory?

**Comment by thijstriemstra** [comment]
@nmgtn, first fork the wavesurfer repository, see github docs.

After you cloned your copy, execute once:

```
npm install -g grunt-cli
npm install
```

Afterwards you run `grunt` to build the code, run checks etc.

**Comment by nmgtn** [comment]
Thanks, that works great.
