### ISSUE TITLE
Would it be possible to adjust waveform height based on average amplitude?

### ISSUE THREAD

**Issue by bobrenjc93** [katspaugh/wavesurfer.js#401]
I'm running into problems where different videos have different audio amplitudes. It'd be great if wavesurfer could normalize somehow. Example below.

![screen shot 2015-03-14 at 8 02 16 pm](https://cloud.githubusercontent.com/assets/1324201/6654247/2a24b2c8-ca85-11e4-8e8f-1851c7c80411.png)

**Comment by normington** [comment]
There used to be a normalize option, which I believe is returning in the next minor release, see #367. 

Not sure of a workaround for now - is there a way to get the maximum peak from wavesurfer and then you can multiply the displayed waveform by the right amount using the `height` option of the `init` method and a set container size? I would be interested if you find a clever way of doing it.

**Comment by AlfonsoDR** [comment]
I needed the same functionality added a small function and a param to Drawer.js

max gets set in drawer.drawPeaks()

and could be get by:

wavesurfer.drawer.getMax()

or get/set with:

drawer.params.max = 1 // default

**Comment by bobrenjc93** [comment]
@AlfonsoDR I'm a little bit confused. Can you post a gist with your changes exactly?

**Comment by AlfonsoDR** [comment]
not much really... in Drawer.js add max to params
in Drawer.drawPeaks: max is calculated so: this.max = max

that will do

access it like so:

wavesurfer.drawer.params.max

Or if you like add this little fintion at the bottom of drawer.js

**Comment by katspaugh** [comment]
I've restored the `normalize` option (#367).
