### ISSUE TITLE
Is there anything built into wavesurfer or web audio api for pitch shifting?

### ISSUE THREAD

**Issue by maxehnert** [katspaugh/wavesurfer.js#404]
I need to do a pitch shift when I play back the audio at slower speeds. 

The two options for playback speed are audioRate and setPlaybackRate. Is there a difference between the two? I'm currently using setPlaybackRate to control speed on the fly. 

I saw there is a js library for pitch shifting https://github.com/mikolalysenko/pitch-shift which I'm sure I can pick apart to make work unless there is an easier solution to this already.

**Comment by maxehnert** [comment]
http://webaudio.github.io/web-audio-api/#doppler-shift

**Comment by drjaydenm** [comment]
@maxehnert Did you manage to find a way to change playback speed whilst keeping the same pitch?

**Comment by maxehnert** [comment]
It's been a long time since I touched any of this and cannot remember where if I ever got that going.

I did look over the link I posted http://webaudio.github.io/web-audio-api/#doppler-shift and it appears there is some support now for this.

**Comment by sprycoder** [comment]
@drjaydenm Have you found same way around it?

**Comment by oaeide** [comment]
I am also curious about this

**Comment by katspaugh** [comment]
If you don't mind also changng the speed of the audio, you can call use `setPlaybackRate` with the second parameter (preservePitch) set to false:

```js
wavesurfer.setPlaybackRate(2, false) // shift pitch up by one octave
```
