### ISSUE TITLE
addRegion doubles start and end values when using fill rather than scroll

### ISSUE THREAD

**Issue by neelspatel** [katspaugh/wavesurfer.js#405]
When using addRegion in fill mode, the region created extends from `2 * start` to `2 * end` rather than from `start` to `end`.

On the project homepage (http://www.wavesurfer.fm/?fill), the sample file has a duration of 21 seconds:
```javascript
wavesurfer.getDuration();
21.77387755102041
```

If we create a region from 5 seconds to 10 seconds, we would expect the region to cover the second quarter of the timeline
```javascript
wavesurfer.addRegion({"start": 5, "end": 10})
```
However, it results in this region being created instead:
![screen shot 2015-03-18 at 12 46 13 am](https://cloud.githubusercontent.com/assets/2560285/6702884/009e7142-cd09-11e4-9ca8-e6b16606b24b.png)
By using `getCurrentTime`, we can see that this region actually extends from `10` seconds to `20` seconds.

If we instead use `wavesurfer.addRegion({"start": 5/2, "end": 10/2})`, we see the correct region being created:
![screen shot 2015-03-18 at 12 54 06 am](https://cloud.githubusercontent.com/assets/2560285/6702906/4d9645f6-cd09-11e4-9819-c65361cd3dc8.png)

**Comment by katspaugh** [comment]
Thanks, good catch!
