### ISSUE TITLE
Add Travis build

### ISSUE THREAD

**Issue by thijstriemstra** [katspaugh/wavesurfer.js#408]
Would be nice to have contineous integration using something like Travis, so we'll always catch build errors and can pave the way for adding unit tests at some point.

**Comment by katspaugh** [comment]
That would be great, I'm totally in!

By the way, what unit-test framework do you prefer? I'm familiar with Jasmine and it's quite nice.

**Comment by thijstriemstra** [comment]
I don't have a preference for any framework, haven't done much JS testing, but I'm familiar with qunit and sinon. Whatever it's going to be, without any coverage reports it's hard to measure, and when i used something called blanket I wasn't impressed with it's performance and results.

**Comment by thijstriemstra** [comment]
@katspaugh, this is also working now. I enabled Travis for my local fork and results are here: https://travis-ci.org/thijstriemstra/wavesurfer.js/builds/55739310

You should also enable Travis for wavesurfer before you merge this.

**Comment by katspaugh** [comment]
Great! I've enabled TravisCI.
