### ISSUE TITLE
Add jshint config

### ISSUE THREAD

**Issue by thijstriemstra** [katspaugh/wavesurfer.js#409]
I noticed @katspaugh prefers single quotes over double quotes so it would be useful to add a very permissive katspaugh-style jshint build when running `grunt` that catches these style mistakes.

**Comment by katspaugh** [comment]
Now with Grunt it would be easy :) I'll come up with a list of minimal lint rules this weekend.

**Comment by thijstriemstra** [comment]
@katspaugh added a jshint task with a config that doesn't fail on any of the current code. Perhaps you should tweak the errors a bit (maybe the strict mode should be enabled?) once it's merged.

**Comment by katspaugh** [comment]
Cool, thanks!
