### ISSUE TITLE
What tools to use to generate arrayOfPeaks?

### ISSUE THREAD

**Issue by chinshr** [katspaugh/wavesurfer.js#410]
On your page http://www.wavesurfer.fm/example/audio-element I was reading that it is possible to prove an arrayOfPeaks to wave surfer that is generated prior (on the server). Out of curiosity, what tools do you suggest to generate the arrayOfPeaks or arrive at it? Thanks of your support.

**Comment by katspaugh** [comment]
These programs:

https://github.com/beschulz/wav2json
https://github.com/bbcrd/audiowaveform

Just make sure you generate an array of floats. The length doesn't matter. To keep it small it's often OK to have the floats rounded to 3-4 digits.

**Comment by chinshr** [comment]
Thanks, that's great!
