### ISSUE TITLE
Long mp3 file with peaks

### ISSUE THREAD

**Issue by RocAlayo** [katspaugh/wavesurfer.js#413]
I'm using wavesurfer with this options:
```javascript
{
      container: document.querySelector("div.wave-container"),
      scrollParent: true,
      fillParent: false,
      hideScrollbar: false,
      cursorWidth: 2,
      waveColor     : '#cccccc',
      progressColor : '#0189BE',
      loaderColor   : 'purple',
      cursorColor   : '#ff0000',
      backend: "MediaElement",
      mediaType: "audio"
}
```
 
Then I try to load a long mp3 file (around an hour) and I specify the peaks arra (consequently It's a huge array of about 18000 positions). Then the wavesurfer canvas renders to the needed width with scroll but the wave didn't get printed in the canvas. I debugged the problem and the method `drawWave` seems to work as expected (makes the lines correctly as far as I can tell).

As a test I tried to load the same array of peaks but with an mp3 file of about 3 minutes and this way the wave does get printed.

Any idea of what could be the problem?

**Comment by katspaugh** [comment]
Looks like the same as #47, i.e. canvas size limit.

Try to decrease the number of square pixels on the canvas by setting a lower minPxPerSecond and smaller height.

**Comment by RocAlayo** [comment]
I tried it and it didn't work. This is weird because I'm updating a webpage that already uses wavesurfer with peaks arrays of this size and works fine, but the version of the wavesurfer used is 9 month old.

**Comment by katspaugh** [comment]
Also with a huge waveform it would be necessary to set pixelRatio to 1 so that it doesn't blow Retina up.
