### ISSUE TITLE
Main example not working

### ISSUE THREAD

**Issue by dmmz** [katspaugh/wavesurfer.js#414]
I just cloned an tried the main example in local. And I was getting on Firefox this error:
      "TypeError: this.buffer is null"
And on Chrome, this one:
      "Uncaught TypeError: Failed to set the 'buffer' property on 'AudioBufferSourceNode': The provided value is not of type 'AudioBuffer'."

Debugging, I just found out that it is caused by a change in last commit (6e67fc339770d1c0e3ce7d46de71b7bfa31d4a30) where this.buffer is set to null in disconnectSource() from webaudio.js

**Comment by katspaugh** [comment]
Thank you! Talk about late night commits....
