### ISSUE TITLE
Gradient for progressColor?

### ISSUE THREAD

**Issue by JoshSmith** [katspaugh/wavesurfer.js#415]
Is it possible to render a gradient for the `progressColor`?

**Comment by JoshSmith** [comment]
Naively I'm going to say this is possible to do with https://developer.mozilla.org/en-US/docs/Web/API/CanvasGradient

**Comment by katspaugh** [comment]
It might be possible to pass a Canvas gradient object as `progressColor`, but I'm not sure. Try it.

**Comment by katspaugh** [comment]
Yes, it's actually working. Use this code:

```JavaScript
var linGrad = document.createElement('canvas').getContext('2d').createLinearGradient(0, 0, 1000, 128);
linGrad.addColorStop(0, '#8ED6FF'); 
linGrad.addColorStop(1, '#004CB3');

var wavesurfer = WaveSurfer.create({
  container: '#waveform',
  progressColor: linGrad
});
```

See live demo here: http://plnkr.co/edit/L99eTSvAkuVJDOXtdCDu?p=preview

**Comment by thijstriemstra** [comment]
See #2345 for a better approach.
