### ISSUE TITLE
Capture mouse click seek

### ISSUE THREAD

**Issue by bobrenjc93** [katspaugh/wavesurfer.js#420]
Is there anyway I can have an event handler that listens for when a user clicks on the waveform to seek? I tried binding the mousup event, but it doesn't seem to trigger in the desired case. Importing the regions plugin and creating a region that spans the entire segment seems like overkill. Am I missing something? Or is Region the only way to go?

**Comment by katspaugh** [comment]
You can use the undocumented internal click event:

    wavesurfer.drawer.on('click', function (e) { ... })
