### ISSUE TITLE
playPause() – It works badly.

### ISSUE THREAD

**Issue by look997** [katspaugh/wavesurfer.js#421]
When use playPause e.g.:
To recording lasting 3 minutes.
0:00 - playPause (play)
2:52 - playPause (pause)
3:00 - end plaing
playPause (play) - again begin from 2:52! Not from 0:00.

The same works with every last pause.

**Comment by look997** [comment]
I add to mycode this:
```		wavesurfer.on('finish', function () {
			wavesurfer.stop();
		});```
and work good.

**Comment by katspaugh** [comment]
Thanks, @look997! The problem was we didn't set the finished state correctly. Now it should start playing from the beginning after it finishes.
