### ISSUE TITLE
Document other projects using wavesurfer

### ISSUE THREAD

**Issue by thijstriemstra** [katspaugh/wavesurfer.js#422]
I've seen other projects create a wiki page where users can list their third-party plugins and integrations. Let's make such a page for wavesurfer as well and link it in the README.

PS. wavesurfer is trending javascript project on github today, wooo!!

![wavesurfer-trending-github](https://cloud.githubusercontent.com/assets/305679/6899749/a85180b6-d702-11e4-94a7-e364d01e1250.png)

@katspaugh, you're also a trending developer today, congrats :)

**Comment by thijstriemstra** [comment]
@katspaugh could you enable the wiki for this project in the project settings if you agree with my proposal?

**Comment by katspaugh** [comment]
Cool idea! And thank you! This is due to a nice write up someone did on a popular Russian tech blog :)

**Comment by thijstriemstra** [comment]
Created https://github.com/katspaugh/wavesurfer.js/wiki/Projects with my personal projects, PR with readme updates will follow.

**Comment by thijstriemstra** [comment]
The last 30 stars are mostly russian yes :)

![schermafbeelding 2015-03-31 om 02 09 38](https://cloud.githubusercontent.com/assets/305679/6909855/2228bc04-d74b-11e4-9ea9-9f7000e13f45.png)

@katspaugh, do you have a link for that article?

**Comment by katspaugh** [comment]
Thijs, here: http://m.habrahabr.ru/post/254327/

**Comment by thijstriemstra** [comment]
@katspaugh thanks for merging. Could you put out a new release when you have a moment?

**Comment by katspaugh** [comment]
Sure, will do tonight.

**Comment by thijstriemstra** [comment]
Thanks.
