### ISSUE TITLE
add test suite

### ISSUE THREAD

**Issue by thijstriemstra** [katspaugh/wavesurfer.js#427]
Running `grunt` from root of repository should execute test suite.

Also see http://blog.chrislowis.co.uk/2014/04/30/testing-web-audio.html

**Comment by thijstriemstra** [comment]
Created a jasmine setup with grunt tasks for tests and coverage. PR follows.

**Comment by katspaugh** [comment]
Cool, looking forward!

**Comment by thijstriemstra** [comment]
Also found https://github.com/HumbleSoftware/js-imagediff which might be useful. For now I'm adding tests for util.js only so we can expand on that.

**Comment by thijstriemstra** [comment]
Well, the travis build for my wavesurfer fork is green: https://travis-ci.org/thijstriemstra/wavesurfer.js/builds/58101652

So I think we're good to go. I also added extra checkers (https://github.com/JamieMason/Jasmine-Matchers) because some basic things like startsWith are not included in jasmine.
