### ISSUE TITLE
HTML5 Audio element fallback

### ISSUE THREAD

**Issue by ghost** [katspaugh/wavesurfer.js#43]
Would it be possible to play the audio through an audio element and do only the visualization through canvas?

This would be far more accessible and gives you the option to use the HTML5 audio API.

**Comment by Prity1208** [comment]
Hi Katspaugh,
wavesurfer is not working on Opera web browser. 
I am getting error
Uncaught TypeError: Failed to set the 'buffer' property on 
'AudioBufferSourceNode': The provided value is not of type 'AudioBuffer'.
    at TypeError (native).
Can you tell me what is the problem?

**Comment by CWSites** [comment]
I don't understand why it's agreed that an <audio> element should be added but the issue is closed. Has this been added?

**Comment by katspaugh** [comment]
@CWSites before asking, couldn't you have checked for yourself first?

**Comment by CWSites** [comment]
@katspaugh I've been looking around but I'm a little out of my depth here. I'm just trying to get it working in IE because I have to support it and it doesn't seem like there is a good way around it without using Flash.

**Comment by katspaugh** [comment]
Audio fallback is there. I.E. may still be unsupported, I've never checked it.

**Comment by CWSites** [comment]
Thanks
