### ISSUE TITLE
Play / Pause button doesn't seem to be working.

### ISSUE THREAD

**Issue by Mironius** [katspaugh/wavesurfer.js#433]
http://www.wavesurfer.fm/example/playlist/
 Pause doesn't work

**Comment by katspaugh** [comment]
@Mironius thanks, fixed. The listener was set on the text, so when you pressed outside the text it didn't work. Now I've added the listener on the whole button.

**Comment by Mironius** [comment]
Yeah! Great, thanks.
The same bug is in the example files ( just FYI)

**Comment by katspaugh** [comment]
In which files exactly? I looked through all examples and the button seems to be wholly clickable in all of them.

**Comment by Mironius** [comment]
https://github.com/katspaugh/wavesurfer.js/archive/master.zip

wavesurfer.js-master.zip\wavesurfer.js-master\example\playlist\
