### ISSUE TITLE
Play and control Multiple Tracks - Enhacement

### ISSUE THREAD

**Issue by adhenrique** [katspaugh/wavesurfer.js#436]
Guys, I wonder if there is any way to insert various tracks on the same page, play them and control them simultaneously.
Like a Player of Multitrack Music.

I'm trying to develop this somehow but has not yet found a solution.

Any idea?

**Comment by naomiaro** [comment]
I was experimenting with this in the past here:

https://github.com/naomiaro/waveform-playlist

I'm trying to get back into working on it, feel free to use this for ideas.

**Comment by katspaugh** [comment]
Hi Naomi,

I've added a link to your project to our wiki: https://github.com/katspaugh/wavesurfer.js/wiki/Projects
Thanks!
