### ISSUE TITLE
Gitter.im for wavesurfer - Please add.

### ISSUE THREAD

**Issue by gnetsys** [katspaugh/wavesurfer.js#438]
I would be nice to have a gitter.im account for WaveSurfer repository

**Comment by thijstriemstra** [comment]
@gnetsys what needs to be done to make this happen?

**Comment by andrade1379** [comment]
You can go to: https://gitter.im/ as the repo owner you give Gitter access to your repo and a room is created. Since it's public once someone searches for wavesurfer? your created room should pop up for people to join.

I hope this is accurate 👍

**Comment by thijstriemstra** [comment]
@andrade1379 created a room at https://gitter.im/katspaugh/wavesurfer.js. Feel free to add a pull request with a gitter badge.
