### ISSUE TITLE
AudioElement draws waves without passing array of peaks!

### ISSUE THREAD

**Issue by karimfikry** [katspaugh/wavesurfer.js#440]
I'm trying to use backend: "AudioElement", but something weird happens that it works as if it's WebAudio, even I changed the compiled code and minified ones it still work as WebAudio! Any idea?

I just want it to show line

**Comment by katspaugh** [comment]
Yes, it's a feature. If you don't pass the peaks, it will download the file and decode via Web Audio.

**Comment by karimfikry** [comment]
So it only decode and get the peaks array via web audio, but don't use it to play, right?

**Comment by katspaugh** [comment]
Exactly. If Web Audio is unavailable, it just displays a thin line and the playhead.

**Comment by karimfikry** [comment]
Great!
