### ISSUE TITLE
Double Wave Shifted

### ISSUE THREAD

**Issue by andrerfneves** [katspaugh/wavesurfer.js#441]
Hi, great script. Works perfectly. However, I've been having issues with this one specific waveform. It's generating a doubled identical waveform shifted to the right of the div. 

This is what I have for js and the markup. 
```html
<div id="waveform">
    <div class="progress progress-striped active" id="progress-bar">
        <div class="progress-bar progress-bar-info"></div>
    </div>
    <!-- Here be the waveform -->
</div>
<div class="controls">
    <button class="btn btn-primary" data-action="back">
        <i class="glyphicon glyphicon-step-backward"></i> Backward
    </button>
    <button class="btn btn-primary" data-action="play">
        <i class="glyphicon glyphicon-play"></i> Play /
        <i class="glyphicon glyphicon-pause"></i> Pause
    </button>
    <button class="btn btn-primary" data-action="forth">
        <i class="glyphicon glyphicon-step-forward"></i> Forward
    </button>
    <button class="btn btn-primary" data-action="toggle-mute">
        <i class="glyphicon glyphicon-volume-off"></i> Toggle Mute
    </button>
</div>

```

```javascript
    // Create an instance
    var wavesurfer = Object.create(WaveSurfer);

    // Init & load audio file
    document.addEventListener('DOMContentLoaded', function() {
        var options = {
            container: document.querySelector('#waveform'),
            waveColor: 'violet',
            progressColor: 'purple',
            cursorColor: 'navy'
        };

        if (location.search.match('scroll')) {
            options.minPxPerSec = 100;
            options.scrollParent = true;
        }

        // Init
        wavesurfer.init(options);
        // Load audio from URL
        wavesurfer.load('media/spokenword.wav');
    });

    // Play at once when ready
    // Won't work on iOS until you touch the page
    wavesurfer.on('ready', function() {
        //wavesurfer.play();
    });

    // Report errors
    wavesurfer.on('error', function(err) {
        console.error(err);
    });

    // Do something when the clip is over
    wavesurfer.on('finish', function() {
        console.log('Finished playing');
    });


    /* Progress bar */
    document.addEventListener('DOMContentLoaded', function() {
        var progressDiv = document.querySelector('#progress-bar');
        var progressBar = progressDiv.querySelector('.progress-bar');

        var showProgress = function(percent) {
            progressDiv.style.display = 'block';
            progressBar.style.width = percent + '%';
        };

        var hideProgress = function() {
            progressDiv.style.display = 'none';
        };

        wavesurfer.on('loading', showProgress);
        wavesurfer.on('ready', hideProgress);
        wavesurfer.on('destroy', hideProgress);
        wavesurfer.on('error', hideProgress);
    });
```
I used the same CSS from the wavesurfer.fm demo page.
This is what I get:

![IScreenshot](http://i.imgur.com/efMymn1.png)

Thanks in advance.

Any idea on what is going on here?

**Comment by thijstriemstra** [comment]
What's the URL of the audio file?

**Comment by andrerfneves** [comment]
http://andreneves.me/work/erik/media/spokenword.wav

**Comment by andrerfneves** [comment]
I've tried multiple audio files too. Both .wav's and .mp3's. Not quite sure what I'm doing wrong.

**Comment by andrerfneves** [comment]
So I did some troubleshooting. Everything from the script works perfectly, except that it seems like everything is shifted to the right a few hundred pixels. If you click forward on the waveform to skip to the desired section, the wave thinks the mouse is actually far to the left. I analyzed each div (canvas and wave) and it seems like the canvas one is shifted right for some reason. Any help? Would a link to the page help deciphering the issue?

**Comment by katspaugh** [comment]
I've opened http://andreneves.me/work/erik/player.html and I think I know what the problem is about. Will issue a patch in a bit.

**Comment by andrerfneves** [comment]
Awesome! Thanks @katspaugh. I'll be in the lookout. Cheers

**Comment by katspaugh** [comment]
I've published a new version to NPM. @andrerfneves can you check if the problem is resolved on your website?

By the way, cool rap. Who is the author/performer?

**Comment by andrerfneves** [comment]
@katspaugh works like a charm. Cheers mate

**Comment by Sir-Rumeh** [comment]
> I've published a new version to NPM. @andrerfneves can you check if the problem is resolved on your website?
> 
> By the way, cool rap. Who is the author/performer?

I am facing the same issue using wavesurfer in my next.js application

**Comment by etienne-bondot** [comment]
@Sir-Rumeh The thread is old, but this helps me https://github.com/katspaugh/wavesurfer.js/issues/2567#issuecomment-1210973991.
