### ISSUE TITLE
How can i generate the annotation (XML) file with ELAN plugin

### ISSUE THREAD

**Issue by jquite** [katspaugh/wavesurfer.js#442]
I’m using the wavesufer js with ELAN plugin.
Now my requirement is how can i generate the XML file or annotation.
reference link :http://www.wavesurfer.fm/example/elan/?scroll
thanks

**Comment by thijstriemstra** [comment]
@katspaugh any idea?

**Comment by katspaugh** [comment]
> how can i generate the XML file or annotation.

By using variables, strings and functions. No built-in support.

**Comment by bhagwansawant123** [comment]
@katspaugh any format for creating xml file?
