### ISSUE TITLE
'Error decoding audiobuffer' with .ogg file

### ISSUE THREAD

**Issue by simonmd** [katspaugh/wavesurfer.js#444]
I'm trying to use wavesurfer with .ogg files generated with **[this](https://github.com/chris-rudmin/Recorderjs)** fork of Recorderjs that uses libopus compiled with emscripten. 

Chrome will natively read the files, and will correctly play them using the <audio> element, but I am unable to have them read by wavesurfer. A sample file is **[here](https://drive.google.com/file/d/0B8hM-13ldZlzRzFBQU15NXFPYTQ/view?usp=sharing)**

I would very much like to use wavesurfer but need to encode the audios in this way.

**Comment by katspaugh** [comment]
Decoding is done by browser, so file a bug with the browser.
