### ISSUE TITLE
Check to see if currently playing

### ISSUE THREAD

**Issue by Tidal-Wave** [katspaugh/wavesurfer.js#445]
Is there a method to call to see if wave surfer is currently playing? I have it in a modal and it will continue to play when modal is closed. I have setup a event on modal close to stop, but this will throw an error if it isn't playing when the modal closes. I know I could use the events, but I am trying to avoid having to set and unset on play/pause/stop. A simple `isPlaying()` public method would be a lot simpler..

**Comment by katspaugh** [comment]
There's `wavesurfer.backend.isPaused()`.

You can add `wavesurfer.isPlaying()` if you like, I'll accept a pull request.

**Comment by Tidal-Wave** [comment]
PR sent. Was unsure of your PR requirements so let em know if anything needs adjusting.
