### ISSUE TITLE
audio element showing, i can't protect my file

### ISSUE THREAD

**Issue by aldajulian** [katspaugh/wavesurfer.js#450]
Hello, Sorry to burden you.

I just want for ask, how to don't display the audio element? i create website for private songs before it release, it can be download by user but with limit, but if limit has been fulfilled, it can't be downloaded.

to protect the file i want to hide everything about the url to access the file.

in example that i've been download from repo it show the audio element, but ih example on wavesurfer.js i didn't find any audio element.

i have read all doc about wavesurfer but i can't find how to remove it. 

Thanks.
![screen shot 2015-05-15 at 3 33 45 am](https://cloud.githubusercontent.com/assets/2577932/7641459/13278258-fab4-11e4-9259-70e4e4823d7a.png)

**Comment by katspaugh** [comment]
You can't hide what you download in the browser. It will be listed in the network and resources panel of devtools anyway.

**Comment by allannaranjo** [comment]
Hope this helps,

You can create a dynamically create a url everytime passing a token like
this link (for instance: http://yoururl.com/tracks/:token).

In the server side you can grab the token and decrypt it, the token can
contain name of the track and the limit you mentioned, and "pipe" the
contents of the audio file to the client side.

If you detect the file was served (by looking in a database) you can return
a 401 status to the client side.

Allan

**Comment by Sapnakarmur** [comment]
Is there any solution for hiding audio element using MediaElement? It works fine for WebAudio but not for MediaElement. 
Its necessary to hide audio element otherwise anybody can get actual path using inspect element.
