### ISSUE TITLE
Nothing rendered to canvas on IE 9 / 10 / 11.

### ISSUE THREAD

**Issue by jasonmayes** [katspaugh/wavesurfer.js#455]
As title says, in IE, the waveform is not rendered.

**Comment by thijstriemstra** [comment]
Not even an error message logged somewhere?

**Comment by jasonmayes** [comment]
No errors! It plays sound, just not drawing. :-/

**Comment by katspaugh** [comment]
IE doesn't support WebAudio. If you need to draw the waveform in these browsers, use pre-decoded waveform data. See an example here: http://www.wavesurfer.fm/example/audio-element/ (look for the "Pre-rendered Peaks" section).

**Comment by jasonmayes** [comment]
Argh... IE. I thought it had caught up by now for 11! Thanks.

**Comment by CWSites** [comment]
@katspaugh wavesurfer.fm isn't loading, just a blank white screen... halp!

**Comment by thijstriemstra** [comment]
@CWSites it's wavesurfer-js.org now.

**Comment by CWSites** [comment]
thanks @thijstriemstra

**Comment by CWSites** [comment]
As a heads up, the page is busted in IE. I get an error `MEDIA12899: AUDIO/VIDEO: Unknown MIME type.`
