### ISSUE TITLE
load function doesn't send cookies with request which leads to CROS Error

### ISSUE THREAD

**Issue by MohamedYakout** [katspaugh/wavesurfer.js#459]
I asked this question on stackoverflow: http://stackoverflow.com/questions/30539149/wavesurfer-doesnt-draw-wave-with-cros-error-because-of-cookies 

I send request to AWS to get audio using call to load function, but I got the following error: 
XMLHttpRequest cannot load https://audiotemp.dentalmarketing.net/RE65bbf6f0a2760184ab08b3fbf9f1d249.mp3. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://call.dentalmarketing.net:3000' is therefore not allowed access. The response had HTTP status code 403.

But, If I open the audio's URL on chrome or using REST Client, I got the call, because I send the cookie with request. 

I need to send the cookie when I call load function, or customize the header of request ?

**Comment by katspaugh** [comment]
Cookie has nothing to do with it. It's just that your server isn't allowing XMLHttpRequest from other domains.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

**Comment by allannaranjo** [comment]
If your files are in an amazon bucket make sure you add a policy to allow
cross domain requests
