### ISSUE TITLE
Question - spectrogram - display only f0

### ISSUE THREAD

**Issue by pitrackster** [katspaugh/wavesurfer.js#468]
Hi,
I was wondering if anyone knows how to extract the fundamental frequency from audio / buffer.

I currently use a Praat script to render the f0 curve, but this is not the "greatest solution" as Praat is not a command line tool and might work or not depending on the server libraries...

Regards

**Comment by amundo** [comment]
Extracting pitch is non-trivial, but it’s relevant that Praat has published its pitch extraction algorithm: 

http://www.ucl.ac.uk/~ucjt465/tutorials/praatpitch.html

This topic was mentioned in  #269.

**Comment by thijstriemstra** [comment]
Maybe pitch.js can help: https://github.com/audiocogs/pitch.js

**Comment by katspaugh** [comment]
@thijstriemstra :thumbsup:

**Comment by pitrackster** [comment]
Thanks for your answers !
I'll take a look at pitch.js

**Comment by thijstriemstra** [comment]
Looks like Chrome is also getting AudioBufferSourceNode.detune: https://www.chromestatus.com/features/5677186052784128
