### ISSUE TITLE
minPxPerSec can not be set to anything above 59 (Canvas size limitation)

### ISSUE THREAD

**Issue by muggy8** [katspaugh/wavesurfer.js#47]
So i want to set my minPxPerSec to 100 because I'm making horizontal music thing and it would be nice if the waveform matched everything else but as i have discovered that if minPxPerSec is set to anything more than 59, the waveform it outputs is transparent. Thanks :)

**Comment by tomByrer** [comment]
Just taking a stab at a fast-fix:

1. Look to see if long sample
2. If true, [increase divisor of `sampleSize`](https://github.com/katspaugh/wavesurfer.js/blob/master/src/webaudio.js#L171)

**Comment by chrisparton1991** [comment]
I've created a pull request that should allow greater minPxPerSec values: #679

**Comment by chrisparton1991** [comment]
Can this be closed, @katspaugh?

**Comment by katspaugh** [comment]
Sure, thanks!
