### ISSUE TITLE
Streaming support?

### ISSUE THREAD

**Issue by pierlo-upitup** [katspaugh/wavesurfer.js#470]
Are there any plans to add streaming support in the future? Thanks!

**Comment by katspaugh** [comment]
No. Please also see all the existing issues: https://github.com/katspaugh/wavesurfer.js/search?q=stream&type=Issues&utf8=%E2%9C%93

**Comment by pierlo-upitup** [comment]
OK, thanks! Maybe a good idea to add this info to the README?

**Comment by katspaugh** [comment]
@pierlo-upitup good point! I'll update the readme.

**Comment by pierlo-upitup** [comment]
One last thing, just to be clear – by "streaming" I was not referring to IceCast-style endless live streaming as in the issue you mentioned, but rather to a "play-as-you-download" for regular audio files. Correct me if I'm wrong, but wavesurfer currently waits until the file has been downloaded completely before taking any action. I wonder if that could be changed? I can imagine a solution where a stream is polled every so often and the waveform gets drawn incrementally, in chunks. Could you elaborate what would be the show-stoppers? That would be hugely appreciated! Thank you!

**Comment by katspaugh** [comment]
The show stopper is we need the whole audio clip to decode it into waveform data.

**Comment by pierlo-upitup** [comment]
Makes perfect sense for the waveform drawing part, but wouldn't it be still possible to decouple the audio playback and start playing immediately (maybe on a placeholder-canvas) and only display the waveform when that is finally available?

**Comment by katspaugh** [comment]
This is already the case if you set the `backend` parameter to `MediaElement` (see here: http://www.wavesurfer.fm/example/audio-element/). It will start playing as soon as you press play and will display a thin line instead of the waveform until it's ready.

**Comment by pierlo-upitup** [comment]
Oh! Thanks for the heads up!
