### ISSUE TITLE
Consecutively loading audio causes wavesurfer to ignore all but the first

### ISSUE THREAD

**Issue by Davev4d3** [katspaugh/wavesurfer.js#472]
When wavesurfer loads the audio, the progress bar is displayed. During that time [wavesurfer.on('loading')] if we load another audio file [wavesurfer.load(URL)]  then wavesurfer only loads the first file.

**Comment by katspaugh** [comment]
Thanks, I'll check that!

**Comment by fari-99** [comment]
is it already fixed?

**Comment by katspaugh** [comment]
I've just tried
```
wavesurfer.load('/example/media/demo.wav');
setTimeout(function () { wavesurfer.load('/example/elan/transcripts/001z.mp3') }, 10);
```
in the console on http://wavesurfer-js.org/ and the second audio is loaded.
