### ISSUE TITLE
disable dragSelection?

### ISSUE THREAD

**Issue by bongjun** [katspaugh/wavesurfer.js#476]
Hi Thanks for this great lib. 

I am trying to make a button to turn on and off Drag-selection. It seems there is a only "enableDragSelection" function. How do I disable it? I don't mean disabling all mouse interactions, I want to disable only the feature, generating new region by dragging.

**Comment by katspaugh** [comment]
There's no such function at this time. I'll mark this as a feature request.

**Comment by katspaugh** [comment]
Should be solved by #643.

**Comment by thijstriemstra** [comment]
> Should be solved by #643.

Yep, closing.

**Comment by Flimm** [comment]
This function is not documented on the website.
