### ISSUE TITLE
Wave surfer crash on chrome / firefox with linear PCM

### ISSUE THREAD

**Issue by majorgilles** [katspaugh/wavesurfer.js#479]
audio format is 'audio/l16'
sample rate 44100
2 channels
.caf file extension

firefox error: 'The buffer passed to decodeAudioData contains an unknown content type'
chrome: file loads after a while, but is played all at once with an audible 'click' (I trigger play() when the file is loaded)

Everything works fine in Safari.

If it's any information, I'm using wave surfer in a Meteor app buy including wavesurfer.min.js in client/compatibility folder. The local server is run on osx yosemite.

**Comment by katspaugh** [comment]
Maybe try checking what Content-Type header you server responses with for that file?

**Comment by majorgilles** [comment]
Hello, it's audio/x-caf

**Comment by katspaugh** [comment]
Oh, it's a proprietary container from Apple, isn't it? I guess Chrome and Firefox cannot decode this format.

**Comment by majorgilles** [comment]
Yes, sorry about that.
