### ISSUE TITLE
Wavesurfer not rendering on Safari 5.1.7 (for windows)

### ISSUE THREAD

**Issue by benjaminpageaud** [katspaugh/wavesurfer.js#480]
Hi,
It looks like wavesurfer is not working on *Safari 5.1.7 for Windows.*
I tried to load both local and external audio files but none of it worked.

Unfortunately, I don't have either a Mac or an iPhone to do more tests, and see if it's only the windows build which is bugged.

The Wavesurfer instance on wavesurfer.fm also doesnt render.
However, I found that the audio tag is empty when looking into the DevTools (I suppose the audio tag is present because of the fallback).
Is there a known issue about wavesurfer not displaying/playing on Safari ?

![capturewavesurfersafari](https://cloud.githubusercontent.com/assets/12715361/8651956/26a5f3f4-297c-11e5-8034-bb940043f824.PNG)
^Screenshot of the DevTools on Safari

**Comment by katspaugh** [comment]
They discontinued this version of Safari long time ago. The current version of OS X Safari is 8. If you need to test in Safari, use [BrowserStack](https://www.browserstack.com/) or a local virtual machine.
