### ISSUE TITLE
Wavesurfer is crashing the tab in Chrome and gracefully erroring in Firefox with a single large MP3 file

### ISSUE THREAD

**Issue by infernocloud** [katspaugh/wavesurfer.js#481]
I've been having some users report "randomly" their browser tabs are crashing when they are on pages using Wavesurfer. I have a pretty beefy machine so I have never seen this in normal usage, but I found a 10MB MP3 file to test and I can reproduce it every time with that file.

There is only one instance of Wavesurfer (minified 1.0.26) on the page, and it is not doing anything clever. No other plugins are loaded, I'm just loading an mp3 URL and playing it.

When Wavesurfer starts to process the downloaded 10MB MP3 file:
The tab in Chrome crashes and so far I haven't been able to get any debug information from it. Even a try/catch around wavesurfer.load() won't catch the error, it just hard crashes the Chrome tab.

Firefox does not crash but Wavesurfer's "error" callback runs with the message "Error decoding audiobuffer" and Firefox's console displays "An unknown error occured while processing decodeAudioData." and then shortly after that "EncodingError: The given encoding is not supported." I suspect the EncodingError console error is just a part of Wavesurfer trying to process the data that had not successfully been decoded previously.

Let me know if any additional information or debugging steps would help. I can provide metadata about the mp3 files but I cannot provide the actual mp3s themselves.

**Comment by katspaugh** [comment]
Yes, I've seen Chrome crashing during the [`decodeAudioBuffer`[(https://github.com/katspaugh/wavesurfer.js/blob/master/src/webaudio.js#L172-L174) call. It's a bug in Chrome's Web Audio implementation.

For your particular application, I suggest you replace the problematic file with a file that can be decoded successfully.

**Comment by infernocloud** [comment]
Well, it's not a problematic file. It's any of the mp3s I'm using that are "too large" where "too large" seems to change depending on the computer processing the file. On my machine it takes an mp3 that is several hours long, but on some of my users' less-powerful machines it is failing at mp3s as little as 15 minutes long. I'm sorry if that was not explained well.

Some more troubleshooting:
* So far only the very big file (10MB) actually causes the tab crash in Chrome. I've tried some files that are slightly less large (about 6MB) and there is no crash, but Wavesurfer's error callback runs with the message "Error decoding audiobuffer"
* The mp3s I'm using are only 8kbps bitrate. (Let me know if this could be causing some issues itself)

I don't know that we can just say this is a bug in Chrome's Web Audio implementation because the underlying "Error decoding audiobuffer" error happens in both Chrome and Firefox. I urge you to reconsider this bug report.

Just starting to dig into the code and the AudioBuffer spec to see if I can be of any help. Is it possible  to split up the decodeAudioData() processing into several passes with each pass limited in memory usage?

**Comment by katspaugh** [comment]
> The mp3s I'm using are only 8kbps bitrate. (Let me know if this could be causing some issues itself)

I remember a similar issue with a low bitrate files: https://github.com/katspaugh/wavesurfer.js/issues/353

**Comment by bkentdev** [comment]
I'm still seeing an issue with `error decoding audiobuffer` when trying to load very small audio clips into wavesurfer
