### ISSUE TITLE
Angular example : create is not a function

### ISSUE THREAD

**Issue by pureseqgh** [katspaugh/wavesurfer.js#482]
Hello,
Thanks for this plugin, its great. I've used it as script tag js plugin, and now trying the Angular example. I'm running into a init error though:

Error: WaveSurfer.create is not a function

I can see from my IDE that indeed WaveSurfer.create does not seem to be available. Am I loading wavesurfer.min.js wrong somehow? Im using require.js, heres the modified directive:

##########

define(['components/player/playerModule', 'wavesurfer'], function (module) {

    'use strict';

    module.registerDirective('Player', function () {
        return {

            controller: 'PlayerController',
            controllerAs: 'vm',
            restrict: 'E',
            //scope: {
            //    player: '='
            //},

        link: function ($scope, $element, $attrs) {
            $element.css('display', 'block');

            var options = angular.extend({ container: $element[0] }, $attrs);
            var wavesurfer = WaveSurfer.create(options);
            //var blah = WaveSurfer.createDrawer(options);

            if ($attrs.url) {
                wavesurfer.load($attrs.url, $attrs.data || null);
            }

            $scope.$emit('wavesurferInit', wavesurfer);
        }

        }
    });
});

Thanks in advance

**Comment by pureseqgh** [comment]
the first part of the directive... importing the wavesurfer js:

define(['components/player/playerModule', 'wavesurfer'], function (module) {

    'use strict';
...

**Comment by katspaugh** [comment]
Try actually passing the second dependency in the function:

```
define(['components/player/playerModule', 'wavesurfer'], function (module, WaveSurfer) {
```

**Comment by pureseqgh** [comment]
I've tried that with no luck, but also additional dependecies aren't needed there, like in this example:

define(['components/tracks/tracksModule', 'bootstrap-validator', 'bootstrap-tagsinput', 'select2'], function (module) {

    'use strict';
...
Any other ideas? Heres a screen shot of fx that IDE sees as available as well, not sure if this may help:

<img width="725" alt="screen shot 2015-07-14 at 2 03 03 pm" src="https://cloud.githubusercontent.com/assets/3844597/8683656/852671c8-2a31-11e5-8240-20c6426c2551.png">
<img width="742" alt="screen shot 2015-07-14 at 2 02 36 pm" src="https://cloud.githubusercontent.com/assets/3844597/8683659/889ec878-2a31-11e5-9c8d-a92068970cf3.png">

**Comment by pureseqgh** [comment]
If I use the CreateBackend function, I get some WaveSurfer errors, so I'm pretty sure the plugin is getting loaded correctly. Couple questions on ways to implement other ways, maybe you can approve one or the other;

1 - follow regular JS example using init() ect

2 - set the appropriate items with dot syntax instead of function; ie WaveSurfer.create.url = blahblah

thanks for any input

**Comment by katspaugh** [comment]
Yes, you should try the regular examples. The second suggestion won't work.
