### ISSUE TITLE
NPM inconsistency

### ISSUE THREAD

**Issue by moonwave99** [katspaugh/wavesurfer.js#483]
Hey there, I `npm install`ed the package, and I found the following inconsistency:

`main`entry of `package.json`points to `dist/wavesurfer.cjs.js`, while package contains only `/dist/wavesurfer.cjs.js`.

Current repo looks fine, so I think you just  need to run `npm publish`, would you please look into that? Thank you so much!

**Comment by katspaugh** [comment]
Hi! I've published just recently. Maybe you need to `npm update`?

**Comment by katspaugh** [comment]
Should be fixed: https://github.com/katspaugh/wavesurfer.js/blob/master/package.json#L5
