### ISSUE TITLE
Insert buttons directly over the waveform

### ISSUE THREAD

**Issue by majorgilles** [katspaugh/wavesurfer.js#484]
Hello, for my current application, I would need to insert different buttons over the waveform, so that the user can click on the button and position the marker at that point in time in the audio file (even if that part is hidden because of the scrolling).

For example:
- Button 1 would represent an offset of 0.3 sec and is positioned at that point in the waveform.
- Button 2 => 2.5 secs and so on.

I would like to know if it's possible to do that without modifying the source code and inserting buttons directly when creating the waveform.

Is it possible to access the width of the canvas element and insert buttons over it.

Thanks in advance

**Comment by katspaugh** [comment]
As they often ask on StackOverflow, "what have you tried?". The canvas element is a regular DOM element and you can get from the `clientWidth` property. Or better, use your container element's `scrollWidth`. I don't see anything that might prevent you from adding buttons inside the container element (or outside but layered over it).

**Comment by majorgilles** [comment]
Ok great news. Thanks for your answer.

Sorry if my questions are too simple, I am very inexperienced regarding web
development. I should probably more research on my own before posting.


2015-07-17 14:01 GMT+02:00 katspaugh <notifications@github.com>:

**Comment by maxehnert** [comment]
Having the button appear off the screen means this approach may not work, but maybe it will help you on the right path. 

I use jQueries [.offset()](http://api.jquery.com/offset/) to position a button in my project and positioning based on the cursor's position within the canvas element. However maybe there's a way to use `getDuration()` to calculate the correct position in the canvas element. 

Just some ideas to think about.

**Comment by majorgilles** [comment]
Since my wave form had to be scrollable, I ended up making a wave surfer
plugin and inserting buttons directly in the canvas.

2015-07-24 19:58 GMT+02:00 Max Ehnert <notifications@github.com>:

**Comment by dalzinm** [comment]
I'm confused as to how the canvas is a regular DOM element. When I try to use it with the DOM properties, it returns undefined no matter what the property is. Also, majorgilles, do you have your plugin publically available? I can't find it in any of your repositories.
