### ISSUE TITLE
text-align on container should be left

### ISSUE THREAD

**Issue by pan100** [katspaugh/wavesurfer.js#485]
I am using reveal.js to make a presentation and I also use reveal.js. reveal.css sets text-align: center on all divs. This bugs up the view of the wave.

Proposal: force text-align:left on the container element in initialization.

**Comment by katspaugh** [comment]
I'll accept a PR for that. Be careful not to change the `container` element itself (the one passed in the parameter), but the inner wrapper we create.

**Comment by thijstriemstra** [comment]
Closing (open PR referencing this ticket to re-open).
