### ISSUE TITLE
Progress wave incorrectly aligned on Retina Macbook

### ISSUE THREAD

**Issue by maxehnert** [katspaugh/wavesurfer.js#486]
On a Macbook Retina the progress wave is rendering below the normal waveform. I guess this must be due to the pixel density. @katspaugh do you know of other people having an issue with this on Retina? 
It could be that I've changed something and unknowingly caused it. 
I haven't been able to determine yet where in `drawer.canvas.js` that I could add an offset to the progress wave. 
I have some custom timeline features that are off slightly as well when I zoom the waveform, but that has to do with the math to calc the timeline I believe. 
<img width="1128" alt="waveform retina" src="https://cloud.githubusercontent.com/assets/8755250/8881645/6e650edc-320f-11e5-8098-621d877e6d62.png">

**Comment by katspaugh** [comment]
@maxehnert can you create a page demonstrating the problem?

**Comment by maxehnert** [comment]
I'm not sure I understand what you mean. Do you want a repo I can share with you to clone?

**Comment by kjantzer** [comment]
@maxehnert – I think creating a demo HTML page is what is being requested. That way other people can test your bug. Maybe use [jsfiddle.net](http://jsfiddle.net)?

**Comment by thijstriemstra** [comment]
Or clone wavesurfer.js and create a gh-pages branch so you can publish Github Pages.

**Comment by maxehnert** [comment]
I'm sorry but I'm going to have to close this as I no longer have access to a retina macbook. 

I'm going to take a guess that if this was the first time this problem has come up that the problem is within the changes I've made to my local wavesurfer copy.  Unfortunately I can no longer test this case. 

Feel free to reopen it if you think it needs to be investigated further.
