### ISSUE TITLE
How does 'saveRegion' work?

### ISSUE THREAD

**Issue by jolacaleb** [katspaugh/wavesurfer.js#487]
Hello!
First of all, I thank all the contributors for this pretty nice plugin!

I want to an explanation of how saveRegion and loadRegion works so I come to write this article.

I'm using wavesurfer to implement my work. What I want to find out is saving regions.

I checked source code on www.wavesurfer.fm/example/annotation/ and in app.js, there is a method which name is supposed to save regions!
If I can do that, I think I can use wavesurfer more easily and efficiently.

But when I check the documentation, there's no explanation of how it works and saved.
Even I only know how it saved and how to load it (whether it's JSON or something), I can use this plugin much better.

**Comment by katspaugh** [comment]
To store regions in the `localStorage`, call `saveRegions()`, to load the stored regions–call `loadRegions(JSON.parse(localStorage.regions))`.

These functions aren't part of the plugin, it's just a thin wrapper around the regular [`localStorage`](https://developer.mozilla.org/en/docs/Web/API/Window/localStorage).

**Comment by jolacaleb** [comment]
thank you for commenting ! that was real help for me.
