### ISSUE TITLE
Can drawing be done as file loads?

### ISSUE THREAD

**Issue by redtopia** [katspaugh/wavesurfer.js#488]
Would it be possible to draw the waves as the file is loading? This would not only show loading progress, but would also open the door for rendering streaming requests where the app doesn't want the entire file to load unless the user listens to the whole thing.

**Comment by katspaugh** [comment]
[No.](https://github.com/katspaugh/wavesurfer.js/issues?utf8=%E2%9C%93&q=stream+in%3Atitle)

**Comment by katspaugh** [comment]
Added this question to FAQ: https://github.com/katspaugh/wavesurfer.js#faq
Thanks for the nice formulation.

**Comment by redtopia** [comment]
Can you add something that discusses how to create the wave form that you would use to preload?

**Comment by katspaugh** [comment]
I'll add some tips to the MediaElement example page.
In short, if it's a one-off thing, you can generate the waveform data through wavesurfer.js in the browser by running `wavesurfer.exportPCM()` in the console and saving it's result into a file.

If you need to generate the data in batch, I don't have a ready-to-use recipe, but various programs can do that: [bbcrd/audiowaveform](https://github.com/bbcrd/audiowaveform), [jhurliman/node-pcm](https://github.com/jhurliman/node-pcm), [ffmpeg](https://www.ffmpeg.org/) etc.

**Comment by redtopia** [comment]
Yea we would need to do it on the backend, probably using ffmpeg. Would the resulting image be mapped the same way as the rendered image on the canvas, and zoom would still work? If so, what would be the point of re-rendering?

**Comment by katspaugh** [comment]
It takes the pre-decoded (which in my ling is the same as pre-rendered–not the image, the data) array of data and renders an image, the same as it woud do with data decoded on-the-fly in the browser.

If zoom would work depends on how dense your data would be (how many data-points aka peaks).

**Comment by redtopia** [comment]
If a project needs to support large files, and considering that there are memory problems with large files, and you would need to pre-render anyway, is there a reason why you would use this library if you only needed to support zooming and drag selection? Seems like I could do that using an image file.

**Comment by katspaugh** [comment]
Sure, why not.
