### ISSUE TITLE
Need Example for adding data points.

### ISSUE THREAD

**Issue by prateekjadhwani** [katspaugh/wavesurfer.js#493]
Hi, 

I am using wavesurfer.js in an open source project called https://github.com/prateekjadhwani/podcast-player . And this is how I am initializing it.

```javascript
this.wavesurfer.init({
	container: this.$.wavecontainer,
	waveColor: this.wavecolor,
	progressColor: this.progresscolor,
	fillParent: true,
	height: 100,
	backend: 'AudioElement'
});
```

Right now, if the file is larger than 50MB, it crashes after downloading the file. And it triggers the `error` event. Live example is http://www.thewebplatform.today/ . I am not sure why that is happening. Can someone confirm if this is a known issue? If you see in the network calls, the file downloads without any issue, but crashes during the process of creating the waveform.

![image](https://github.com/prateekjadhwani/podcast-player/raw/master/screenshot.gif)

The way I am thinking of fixing this problem is to compute the waveform on the server side and pass these in the waveform as a parameter. Can anyone please refer me to an example that I can use to 
- Compute the waveform at the backeend
- Pass the data points for waveform as a parameter in the library

Thank You

**Comment by katspaugh** [comment]
Yes, it's a known problem with large files.

To decode on the server, use a program like ffmpeg, node-pcm or [bbcrd/audiowaveform](https://github.com/bbcrd/audiowaveform).

The format of the audio isn't documented, but you can look at this example: http://www.wavesurfer.fm/example/audio-element/

You can also go to the console and type `wavesurfer.exportPCM()` and it will give you an idea of how the JSON data should look like.

[Pass the data](https://github.com/katspaugh/wavesurfer.js/blob/master/example/audio-element/main.js#L26) alongside the audio file to the `load()` method like this:

```wavesurfer.load('example/media/demo.mp3', waveformData);```

**Comment by prateekjadhwani** [comment]
Thanks @katspaugh 
Just one more question. If I pass the `waveformData` in the `load` method, will the wavesurfer library parse the media file again to create the waveform?

**Comment by prateekjadhwani** [comment]
nvm, i doesnt do that. Thanks @katspaugh for helping me out.
Keep up the good work.
