### ISSUE TITLE
Support for only region part of waveform to be selected with darker color

### ISSUE THREAD

**Issue by gapipro** [katspaugh/wavesurfer.js#495]
So it would like to have something like this:

http://postimg.org/image/mz0llz6ab/

**Comment by katspaugh** [comment]
That's exactly what the regions plugin does.

**Comment by gapipro** [comment]
Actually it doesn't. Check your coloring and my image example. Difference is that only selected part of waveform is darker not the whole waveform from 0 to selected region.

**Comment by katspaugh** [comment]
@gapipro I see what you mean. I've checked your PR again and still think it's a bit of an overkill in terms of how much code is needed for a very particular feature. Thanks for your contribution, anyway!
