### ISSUE TITLE
Pre-rendered Peaks visualization

### ISSUE THREAD

**Issue by berio** [katspaugh/wavesurfer.js#497]
I am trying to implement Pre-rendered Peaks, but the waveform doesn't display as it should. I run the example (audio-element) that comes with the last version of wavesurfer.js, just for double check if I am doing something wrong, but the visualization of the waveform also looks weird there. 
What could be going wrong?
Thank you!

**Comment by katspaugh** [comment]
It looks weird because it has too few datapoints. If you look at this page: https://github.com/katspaugh/wavesurfer.js/tree/master/example/annotation – it has a nicer looking waveform, because it has sufficiently many peaks in the JSON file.

**Comment by berio** [comment]
Thank you kastpaugh. 
I got it working using exportPCM method. BTW Is there a way to load the waveform faster?

**Comment by katspaugh** [comment]
If I knew a way to make it faster, it would be the default :smile:
