### ISSUE TITLE
Choppy playhead movement/scrolling when setting backend: 'MediaElement'

### ISSUE THREAD

**Issue by stephenlaughton** [katspaugh/wavesurfer.js#498]
I am getting really choppy playhead scrolling on all the examples where backend is set to MediaElement. When remove any backend setting from init (using default WebAudio backend) scrolling becomes smooth.

Anyone else seeing this sort of behaviour? I am testing in the latest versions of Chrome and FireFox.

**Comment by katspaugh** [comment]
I don't see any difference in scrolling smoothness between http://wavesurfer-js.org/example/annotation/ and the rest of demo pages.

If you can find out the immediate problem or a way to reproduce it consistently, please feel free to reopen this issue.
