### ISSUE TITLE
The source is much older than dist and doesn't play some mp3s in Firefox

### ISSUE THREAD

**Issue by Dingo64** [katspaugh/wavesurfer.js#500]
It doesn't play some mp3s in Firefox and since the source is much older than the dist (.min) file I cannot fix myself. I can send you the problematic mp3 file, just cannot post it here (copyrights and stuff).

**Comment by katspaugh** [comment]
The source cannot be older, because the distribution is built from it. Regarding the mp3 support in Firefox, please try the Firefox'es bugtracker.
