### ISSUE TITLE
How to handle the drag feature of region handlers in wavesurfer

### ISSUE THREAD

**Issue by aloknath1** [katspaugh/wavesurfer.js#502]
I had created a custom region using region tag. Now I want to get handling on region dragging so that it won't overlap on another regions.

**Comment by katspaugh** [comment]
Regions have [`minLength` and `maxLength` params](https://github.com/katspaugh/wavesurfer.js/blob/master/plugin/wavesurfer.regions.js#L92-L93) which you can use to limit the size of individual regions. You'll need to calculate these limits in your app (like `region.maxLength = region.start + nextRegion.start`).

**Comment by mikevercoelen** [comment]
@katspaugh got an example on how to exactly get the `nextRegion`? Don't see that anywhere.

**Comment by richardbonneau** [comment]
@katspaugh I think this doesn't prevent overlap, unless your regions are all exactly next to each other. 
Would you have another solution to prevent overlap?
