### ISSUE TITLE
Zooming in makes waveform disappear eventually

### ISSUE THREAD

**Issue by ffxsam** [katspaugh/wavesurfer.js#504]
Any reason this would happen?

![licecap](https://cloud.githubusercontent.com/assets/12532733/9422539/b4db3254-484b-11e5-8723-f5834631f4af.gif)

**Comment by ffxsam** [comment]
Ahh, when the width goes past about 30000px, it vanishes. :) I guess that's bad. Maybe there should be a hard limit that stops it from zooming at that point?

**Comment by katspaugh** [comment]
Duplicate of #458.
