### ISSUE TITLE
getCurrentTime() always returns 0 when play() takes non-empty arguments

### ISSUE THREAD

**Issue by victoryhb** [katspaugh/wavesurfer.js#505]
Hi everyone,
I am experimenting with wavesurfer and have encountered the following issue:
When I pause the audio and then replay a section of it using:

```
wavesurfer.play(startTime, endTime);
```

I want to get the current time by calling:

```
wavesurfer.getCurrentTime();
```

but the function above always returns 0 instead of the exact time as expected. 
Is this a bug?
Thanks a lot in advance!

**Comment by thijstriemstra** [comment]
See https://github.com/katspaugh/wavesurfer.js/issues/669#issuecomment-213200504
