### ISSUE TITLE
How do i get current duration to increase as i play

### ISSUE THREAD

**Issue by interwap** [katspaugh/wavesurfer.js#506]
Hi, ive been able to get the actual duration of the audio file, via this code
function addZero(i) {
					  	
						    if (i < 10) {
						        i = "0" + i;
						    }
						    return i;
						}

						// Gets the duration of the music file from seconds to minutes
						//Elapsed and actual duration;
					function getduration(){	

					  var duration = wavesurfer.getDuration();
					  var minutes = addZero(Math.floor(duration/60));
					  var seconds = addZero(Math.floor(duration - (minutes * 60)));
					  var durationplaceholder = document.getElementById('duration');
					  durationplaceholder.innerHTML = minutes + ":" + seconds;
My dilemma is getting the current time to increase for 00:00 as i play using the getcurrentime function. it should also update as i drag the seekbar either left or right. Thank you

**Comment by katspaugh** [comment]
Subscribe to the `audioprocess` event like this:

```javascript
wavesurfer.on('audioprocess', function (time) {
    var minutes = Math.floor((time % 3600) / 60);
    var seconds = ('00' + Math.floor(time % 60)).slice(-2);

    var currentTimePlaceholder = document.getElementById('current-time');
    currentTimePlaceholder.textContent = minutes + ':' + seconds;
});
```

**Comment by interwap** [comment]
Thank you katspaugh, worked like magic. The audioprocess was not in the readme file. If we could get a full list of update events and functions. That will come in handy too

**Comment by james-hoegerl** [comment]
Oh man yah I was using a timeout.

**Comment by interwap** [comment]
created my own interval at first and them kats showed me a much easier method
