### ISSUE TITLE
Compatibility issue with new version 1.0.29

### ISSUE THREAD

**Issue by aloknath1** [katspaugh/wavesurfer.js#508]
I have an issue while using the wavesurfer.min.js v 1.0.29. I am unable to create the instance of the wavesurfer. The backend option in wavesurfer is displaying an error. The waveform is not generating when I use backend as an option 'WebAudio'. But when I use 'WebAudioBuffer' as a backend, the waveform generates.

Which option to use as a backend?

**Comment by katspaugh** [comment]
Backend can be either `WebAudio` or `MediaElement`. There weren't any changes in this regard.
Please don't make guesses. If you want me to help you figure it out, send the exact error message and a way to reproduce (preferably a JSFiddle).
