### ISSUE TITLE
iOS Compatibility 

### ISSUE THREAD

**Issue by james-hoegerl** [katspaugh/wavesurfer.js#509]
Having an issue where I integrated wavesurfer and it works wonderfully on all platforms but iOS. Was wondering if I'm implementing ok. Made up a fiddle to demonstrate.

Open this with an iPhone or iPad

https://jsfiddle.net/jjh47/kp9akr2e/4/embedded/result/

On clicking load, you will get a loaded waveform but the song will not play.

However if you seek then click play it will start playing.

Any help would be appreciated, it works so well on other platforms and is so beautiful I really want to use it.

Thanks
Original fiddle link
https://jsfiddle.net/jjh47/kp9akr2e/4/

**Comment by katspaugh** [comment]
It's a [known issue](https://github.com/katspaugh/wavesurfer.js/blob/master/example/main.js#L34) that iOS won't allow you to play the audio programmatically. It won't play unless the user clicks on the page. It's a power/bandwidth-saving feature of Safari.

**Comment by james-hoegerl** [comment]
Thanks

**Comment by james-hoegerl** [comment]
Is there any reason I should have to click the play button twice @katspaugh?

When I first click play it seems to load the song into the audio element somehow because the duration and current time go from NaN's to numbers. Then I click play again and it actually plays.

Thanks for your responses btw.

**Comment by katspaugh** [comment]
Not sure. Maybe we need to add `autoplay`.

**Comment by james-hoegerl** [comment]
No luck changing the autoplay property to true on the audio element. Actually disables programatic play on Chrome.

**Comment by james-hoegerl** [comment]
Odd. From https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio#Attributes

autoplay
A Boolean attribute; if specified (even if the value is "false"!), the audio will automatically begin to play back as soon as it can do so without stopping to finish loading the data.

**Comment by katspaugh** [comment]
Looks like this is not an issue anymore. I can successfully play the audio by clicking once on http://wavesurfer-js.org/example/audio-element/ on iOS 10.

**Comment by samyoung88** [comment]
I am experiencing this issue. When hitting play it will only load the player, I will have to click the play button a second time for it to really play  the track. However, I am clicking play from a list of tracks and not directly on the player for reference.
