### ISSUE TITLE
Video playback with Wavesurfer

### ISSUE THREAD

**Issue by chinshr** [katspaugh/wavesurfer.js#510]
I would like to get video playback to work with wavesurfer, particularly, a video file playing alongside the waveform underneath. There is a [videojs plugin](https://github.com/collab-project/videojs-wavesurfer) with a [demo](http://collab-project.github.io/videojs-wavesurfer/examples/video.html) supporting something like that, but I don't see the video playing along the waveform, nor do I see how to configure wavesurfer in a similar fashion I would standalone, e.g. loading waveform, using minimaps, listening on events ('region-click', 'region-updated'), etc.

**Comment by thijstriemstra** [comment]
I think this is something that I can make optional in the videojs-wavesurfer plugin.

**Comment by chinshr** [comment]
@thijstriemstra Rolling the video would be great. The additional granularity of control of the wavesurfer instance would be great as well. 

My ultimate goal is to playback a [YT video](https://github.com/eXon/videojs-youtube), showing a waveform, loaded from waveform.js, and supporting regions.

**Comment by thijstriemstra** [comment]
Calling it an enhancement for now, @katspaugh feel free to change that etc.

**Comment by chinshr** [comment]
FYI I am going with the approach in PR #707 and #698.

**Comment by katspaugh** [comment]
Added in #707.
