### ISSUE TITLE
How do i get bitrate and filesize?

### ISSUE THREAD

**Issue by interwap** [katspaugh/wavesurfer.js#513]
Hello, how do i get the bitrate and filesize of the audio using wavesurfer. I know this must be pretty basic but i can't seem to get a hang of it just yet. Thanks

**Comment by katspaugh** [comment]
Please don't spam, otherwise I'll have to block you.

**Comment by interwap** [comment]
i'll be glad if i get an answer to my question. Thanks

**Comment by thijstriemstra** [comment]
Seems like something we could expose in wavesurfer?

**Comment by interwap** [comment]
hows that done?

**Comment by entonbiba** [comment]
@interwap `wavesurfer.backend.buffer.length` `wavesurfer.backend.buffer.sampleRate`
