### ISSUE TITLE
Waveform selecting dynamically created object

### ISSUE THREAD

**Issue by sentiasa** [katspaugh/wavesurfer.js#515]
I have a div that is dynamically created that is using jQuery and I am trying to use Wavesurfer.js which requires the element to be selected using document.querySelector. Since the elements are dynamically created using jQuery, the selector does not recognise the elements.

    $( document ).ready(function() {
        $("#audio").append('<div class="row" id="wave6" class="wave"></div>');

        $('#audio').on('DOMNodeInserted', 'div', function () {
        var id = 6;
        window['waveForm' + id] = Object.create(WaveSurfer);

        window['waveForm' + id].init({
            container: document.querySelector('wave' + id),
            waveColor: 'violet',
            progressColor: 'purple'
        });

        window['waveForm' + id].on('ready', function () {
            window['waveForm' + id].play();
        });

        window['waveForm' + id].load(id + '.mp3');
    });

This is my code so far. `id` is assigned by jQuery when dynamically creating the elements.

The error I am getting: `Uncaught Error: Container element not found`

**Comment by katspaugh** [comment]
It should be `document.querySelector('#wave' + id)`. In future, please use StackOverflow for this kind of questions.

**Comment by sentiasa** [comment]
I tried your suggestion but still get the same error. I posted my question also on StackOverflow and received this answer: http://stackoverflow.com/a/32293351/4705339. I couldn't run it on JSFiddle so I tried to run it on my local machine. Now, I receive no errors and the div is created but the waveform itself does not load.
