### ISSUE TITLE
How to stop region overlap in wavesurfer?

### ISSUE THREAD

**Issue by aloknath1** [katspaugh/wavesurfer.js#516]

**Comment by katspaugh** [comment]
I already answered you here: https://github.com/katspaugh/wavesurfer.js/issues/502#issuecomment-134517626

**Comment by HassanAslam** [comment]
Hey @katspaugh i cannot solve regions overlapping issue can u help plz?

**Comment by gaona233** [comment]
resloved? i have same problem

**Comment by gaona233** [comment]
resloved? i have same problem

**Comment by katspaugh** [comment]
There's no anti-overlapping functionality in wavesurfer, you gotta code it yourself.
