### ISSUE TITLE
Bower main is empty

### ISSUE THREAD

**Issue by Ti-webdev** [katspaugh/wavesurfer.js#522]
I use bower-main-files for inject all bower libraries, but wavesurfer.js not contains dist/wavesurfer.min.js there after remove bower.json file :( on 8a342dafb43930c56318933bed64c86d3685a455 commit

**Comment by katspaugh** [comment]
Restored, thanks!

**Comment by Ti-webdev** [comment]
Thank you very much. Can you update bower too?

**Comment by Ti-webdev** [comment]
I mean pump version and register it over bower cli

**Comment by katspaugh** [comment]
Done.
