### ISSUE TITLE
when loading multiple tracks, abort all but the last

### ISSUE THREAD

**Issue by icyz** [katspaugh/wavesurfer.js#523]
when I trying to loading few tracks simultaneously, before starting to play the track, it need all loaded tracks before start.

I need (when there are tracks in queue) abort all tracks and load only the last track.

how can i do?

**Comment by icyz** [comment]
found xhr.abort()... I'll try it

**Comment by nahuelhds** [comment]
@icyz how you did that? Where in the Wavesurfer instance the XHR is saved? I'm tryingo to cancel the request when another song is loaded, so it only loads the last loaded song and save resources...

Thanks in advance

**Comment by nahuelhds** [comment]
Had an older version. Just downloaded the 1.1.x one and I've just seen the cancelAjax method. Thank god I've seen this thread xD

**Comment by katspaugh** [comment]
@nahuelhds I'll add `cancelAjax` to the documentation.
