### ISSUE TITLE
Waveform loading takes lot of time for larger sized videos

### ISSUE THREAD

**Issue by gintelllect** [katspaugh/wavesurfer.js#525]
Hi @katspaugh
This is similar or same as #107 issue. But still wanted to understand this.

With the current code in master, page shows a canvas with a wave only after a complete video is downloaded and processed. For smaller videos it is fine. But for larger videos, our observation is it takes 20 odd minutes to show up the the wave.

I was wondering if there is any way the waves can be generated while the video is being downloaded?

Also if there is none, is there caching mechanism that you suggest to avoid this delay?

Please suggest. Thanks in advance.

**Comment by katspaugh** [comment]
See #410 and #488.

**Comment by apurvgandhwani** [comment]
@gintelllect were you able to solve it?

**Comment by CredibleIO** [comment]
Nope. I could not get over this issue.
