### ISSUE TITLE
Media Source Extensions

### ISSUE THREAD

**Issue by antferr** [katspaugh/wavesurfer.js#532]
wavesurfer.js support Media Source Extensions?

**Comment by katspaugh** [comment]
I don't know what that is.

**Comment by antferr** [comment]
https://w3c.github.io/media-source/

**Comment by katspaugh** [comment]
A TL;DR and why we should support it, maybe?

**Comment by thijstriemstra** [comment]
"use cases like adaptive streaming and time shifting live streams."...

**Comment by nlocnila** [comment]
:+1:
