### ISSUE TITLE
Documentation for Button Actions

### ISSUE THREAD

**Issue by CWSites** [katspaugh/wavesurfer.js#533]
The demos have buttons which is nice but none of the documentation mentions how to hook everything in and when I used the code from the demo it doesn't work. I know it's trivial but it would help.

**Comment by katspaugh** [comment]
You are right. I think the demos bind actions to HTML in an unnecessarily complex way. We need to use something simple like this:
```
<button onclick="wavesurfer.play()">Play</button>
```

**Comment by joshuaiz** [comment]
How I got it working was to go through this site linked to in the Wiki: http://feltmusic.com/production-music in Chrome Dev Tools.

They rewrote the code in jQuery which was much easier to follow. It took a few hours but I was able to rewrite my instance(s) in jQuery as well and used that example which has much simpler HTML than the examples on here.

**Comment by CWSites** [comment]
Thanks everyone, this is what I ended up doing

## HTML
```
    <div class="controls">
      <button class="btn btn-primary" data-action="back">Backward</button>
      <button class="btn btn-primary" data-action="play">Play / Pause</button>
      <button class="btn btn-primary" data-action="forward">Forward</button>
      <button class="btn btn-primary" data-action="mute">Toggle Mute</button>
    </div>
```

## JavaScript
```javascript
    $('.controls .btn').on('click', function(){
      var action = $(this).data('action');
      console.log(action);
      switch (action) {
        case 'play':
          wavesurfer.playPause();
          break;
        case 'back':
          wavesurfer.skipBackward();
          break;
        case 'forward':
          wavesurfer.skipForward();
          break;
        case 'mute':
          wavesurfer.toggleMute();
          break;
      }
    });
```
