### ISSUE TITLE
Visualization on Internet Explorer

### ISSUE THREAD

**Issue by CWSites** [katspaugh/wavesurfer.js#537]
I only need to support IE9-11 which supports the audio element but none of the visualization is displaying on my site. There is no documentation for the fallback of this library so I'm wondering if anyone know's how to get it working?

Other than that I noticed that in IE 9 & 10 the cursor for the audio isn't moving when I am playing the audio.

## Chrome, Firefox, Safari
![screen shot 2015-10-05 at 11 16 08 am](https://cloud.githubusercontent.com/assets/1242102/10284652/0a547edc-6b53-11e5-9a5e-9c4feac0ec02.png)

## IE 11
![screen shot 2015-10-05 at 11 19 51 am](https://cloud.githubusercontent.com/assets/1242102/10284655/0e7c5b42-6b53-11e5-8929-5dedbf5bc8c8.png)

## IE 9 & 10
![screen shot 2015-10-05 at 11 17 02 am](https://cloud.githubusercontent.com/assets/1242102/10284657/15041978-6b53-11e5-958a-fcc0a348670a.png)

**Comment by jsniff** [comment]
Anyone have any ideas?

**Comment by Agshealth-Raj** [comment]
now i have faced same issue. please someone help me...

**Comment by katspaugh** [comment]
Web Audio is not supported by IE11. See http://caniuse.com/#search=web%20audio

**Comment by X-Raym** [comment]
@katspaugh Web Audio is needed for decoded the audio to generate the peaks, but what if we already have the peaks ?
It doesn't seems to work either (just a thin line is drawn).

Is it possible to make IE works with cached peaks loading, without using the flash based fallback ?

Thanks for your support !
