### ISSUE TITLE
Feature request: loading indicator

### ISSUE THREAD

**Issue by Joshfindit** [katspaugh/wavesurfer.js#538]
Doesn't have to be anything fancy.
Even an animation that is loaded when the player is rendered, then dumped when the file is loaded and waveform is displayed.

**Comment by katspaugh** [comment]
A pull request is welcome.

**Comment by Joshfindit** [comment]
@mikeyshean I thought I saw a loading bar on trackstack.audio; any interest in coding up a quick loading indicator for wavesurfer?

**Comment by mikeyshean** [comment]
hey @Joshfindit .. yeah I did have a loading bar at one point, but I ended up switching it to for pre-rendered peaks.  

I actually just added a div within the audio element that could be modified from within the wavesurfer `loading` event callback. It passes an integer indicating the loading progress (0-100) which I used to adjust the width of the progress div.  But yeah, it would be nice to have it or something like it as an option in wavesurfer.  I'll look into it!
