### ISSUE TITLE
Normalize doesn't affect output volume?

### ISSUE THREAD

**Issue by Joshfindit** [katspaugh/wavesurfer.js#540]
In testing the normalize option, I was expecting that the volume would be normalized, but only the display is normalized.

Is this by design?

OSX 10.11, Chrome 45.0.2454.101 (64-bit)

Edit: Example of a very quiet sample

Normalize: false
![screenshot 2015-10-05 15 17 21](https://cloud.githubusercontent.com/assets/1937155/10289339/36922424-6b74-11e5-9ad1-f5e3920fb805.png)

Normalize: true
![screenshot 2015-10-05 15 16 27](https://cloud.githubusercontent.com/assets/1937155/10289319/1f854b30-6b74-11e5-8734-fb28d0c0c3e3.png)

Audio volume is the same in both cases

**Comment by katspaugh** [comment]
Yes.
