### ISSUE TITLE
wavesurfer link broken

### ISSUE THREAD

**Issue by thijstriemstra** [katspaugh/wavesurfer.js#544]
wavesurfer.fm is still linked on https://katspaugh.github.io/

**Comment by katspaugh** [comment]
Oh, good catch, thank you!

**Comment by katspaugh** [comment]
Updated in https://github.com/katspaugh/katspaugh.github.io/commit/fab92f6733bbf7bf13318b3b9f0e6fcc3fd67926.
Thanks!
