### ISSUE TITLE
Hide waveform

### ISSUE THREAD

**Issue by icyz** [katspaugh/wavesurfer.js#547]
there is an easy way to not render the waveform? I'll using MediaElement backend

**Comment by CWSites** [comment]
The whole point of this library is for the waveform. That being said you could use CSS `wave {display: none !important;}`

**Comment by icyz** [comment]
sorry for unclear question. 

I want this result: (instead waveform, cause for it I need to have full-loaded track)

![image](https://cloud.githubusercontent.com/assets/1923633/10453212/c4172240-71aa-11e5-8c6c-1d45ee28468d.png)

**Comment by thijstriemstra** [comment]
Its stil unclear what you want.

**Comment by icyz** [comment]
I want this 
![](https://cloud.githubusercontent.com/assets/1923633/10453212/c4172240-71aa-11e5-8c6c-1d45ee28468d.png)

instead of this

![image](https://cloud.githubusercontent.com/assets/1923633/10453656/5d0e833c-71ae-11e5-8fe7-5aea584ca1ae.png)

**Comment by icyz** [comment]
is this possible? 
live demo here: http://deejayvinyl.com/

thanks

**Comment by Tpona** [comment]
You can made it using Web Audio Api directly http://webaudio.github.io/web-audio-api/

**Comment by katspaugh** [comment]
I think the question has been answered in the second comment.
