### ISSUE TITLE
Firefox: Console Errors

### ISSUE THREAD

**Issue by CWSites** [katspaugh/wavesurfer.js#548]
I'm seeing the following console error, even on the demo website in latest Firefox.

`NotSupportedError: Operation is not supported`

**Comment by thijstriemstra** [comment]
I've been seeing the same lately but thought it was related to Firefox (41.0.1) osx..

**Comment by CWSites** [comment]
Any ideas on what it could be? I was also seeing this error on earlier versions of Firefox. I have a browserstack account so I'll investigate the infected versions.

**Comment by thijstriemstra** [comment]
No idea but I'd also try some older wavesurfer.js version.

**Comment by CWSites** [comment]
@thijstriemstra I've verified that it's only on Firefox 41.0.1 on OSX. I tested 40 on both Windows 7 and OSX and it's fine. I don't know what Firefox changed in that patch but that's certainly something that broke your library.

**Comment by PaulKish** [comment]
Console errors appearing on Windows Firefox 44.0 same error message `NotSupportedError: Operation is not supported`

**Comment by thijstriemstra** [comment]
I'm afraid trying to find this bug involves dissecting all of the source code, a long process.
