### ISSUE TITLE
Redraw the waveform

### ISSUE THREAD

**Issue by pedrodj46** [katspaugh/wavesurfer.js#550]
Hi! I've developed a simple web application from the example 'Equalizer'. Is there a method to redraw the waveform when I change an input range of the equalizer?
Thanks

**Comment by tweed** [comment]
And/Or: is there a way to have the entire equalizer shrink responsive-style when page is resized? It ends up as two rows with same size equalizer faders in smaller views, i think, though for sure it remains original size when page is resized on desktop machine browser (which is the only way I've tested)

MANY THANKS!

**Comment by pedrodj46** [comment]
In my application, I've resolved with a normal responsive website with the equalizer in a container div with a static width. The container div has two important css properties: `overflow-y:auto;` and `-webkit-overflow-scrolling:touch;`.
With these properties, when you resize the page and the width of container div has higher than the browser's viewport, you have the equalizer in a scrolling row for change all input range.

**Comment by wilsonlmh** [comment]
wavesurfer.params.height = (waveformFrame.offsetHeight - 30); //30px is the time code height, may different in your environment
    wavesurfer.drawer.setHeight((waveformFrame.offsetHeight - 30));
    wavesurfer.drawBuffer();

**Comment by pedrodj46** [comment]
Hi @wilsonlmh, this answer is for @tweed, but for my question isn't there no solution?
Thanks

**Comment by wilsonlmh** [comment]
I can't say. I'm newbie on WebAudioAPI. I can only say the concept is to generate buffer from the `audioContext`'s destination, read this,
https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API
Maybe you can get some hints from the list of methods.
