### ISSUE TITLE
Multiple instances and getting current instance in event

### ISSUE THREAD

**Issue by Tpona** [katspaugh/wavesurfer.js#551]
Hi!
First of all, nice app, thx!

I try to make multiple instances in one page app with multiple waveform.

```
                for (i=0; i<data.answers.length; i++ ) {
                    var answer = data.answers[i];
                    var wavesurfer = Object.create(WaveSurfer);
                    wavesurfer.init({
                        height      : 50,
                        container   : document.querySelector('.answer-wave[data-id="'+answer.id+'"]'),
                        cursorColor : '#ccc',
                        waveColor   : '#ccc',
                        progressColor: '#337ab7'
                    });
                    wavesurfer.load(getSoundUrl(answer.sound));
                    wavesurfer.on('ready', function () { 
                        console.log('ready');
                    });
                    $('.answer-wave[data-id="'+answer.id+'"]').data({ws:wavesurfer});
                    waveforms.push(wavesurfer);
                }
```

But i want to get instance, then get container option, inside "ready" event for handling some issues with it's container (for example, change ready state, show some controls etc).

It is possible?

**Comment by katspaugh** [comment]
`wavesurfer.params.container`

**Comment by Tpona** [comment]
As you see, wavesurfer object is deep local variable, and in this way i get only the last created object.

**Comment by katspaugh** [comment]
That's why I said you should use `forEach`.

**Comment by Tpona** [comment]
katspaugh, thanks for reply.
I have little skill in javascript. 
Can you give me a small example, because i dont understand where i must to use forEach?
Thx

**Comment by Tpona** [comment]
I did it!
"foreach" tnstead "for"
Thx!
