### ISSUE TITLE
Save selected region as mp3

### ISSUE THREAD

**Issue by designscripting** [katspaugh/wavesurfer.js#553]
Thanks for the wonderful library.

I want to save the selected region as mp3. How could I do that from the wavesurfer.backend.buffer? Or Do i need to use some other method.

Thanks
Saravanan B

**Comment by designscripting** [comment]
Below code I am execution,the data downloads as .wav file but looks corrupt;

Please show me any idea of what is happening, We can run the code in code after selection of waveform


var param = {};
param.start = startPoint;
param.end = endPoint;
param.wavesurfer = wavesurfer;
app.trimBlob(param);

var app = {
 trimBlob : function(params){

/*
 EXTRACTED FROM A PRIVATE PROJECT
IF YOU NEED MORE INFO LET ME KNOW:

allan.naranjo@gmail.com
---------------------------------------------
This method works with wavesurfer.
Make a selection, using wavesurfer api take the start and end.
---------------------------------------------
The function will take the buffer used to create the waveform and will
create
a new blob with the selected area from the original blob using the
offlineAudioContext

*/

var self = this;
var start = params.start;
var end = params.end;

var originalAudioBuffer;


originalAudioBuffer = params.wavesurfer.backend.buffer;

var lengthInSamples = Math.floor( (end - start) *
originalAudioBuffer.sampleRate );

var offlineAudioContext = new OfflineAudioContext(1, 2,
originalAudioBuffer.sampleRate );
 var
new_channel_data,empty_segment_data,original_channel_data,before_data,after_data;

var emptySegment = offlineAudioContext.createBuffer(
originalAudioBuffer.numberOfChannels,lengthInSamples,
originalAudioBuffer.sampleRate );

var newAudioBuffer = offlineAudioContext.createBuffer(
originalAudioBuffer.numberOfChannels,
(start === 0 ? (originalAudioBuffer.length - emptySegment.length) :
originalAudioBuffer.length)
, originalAudioBuffer.sampleRate);

for (var channel = 0; channel < originalAudioBuffer.numberOfChannels;
channel++) {

new_channel_data = newAudioBuffer.getChannelData(channel);
empty_segment_data = emptySegment.getChannelData(channel);
original_channel_data = originalAudioBuffer.getChannelData(channel);

before_data = original_channel_data.subarray(0, start *
originalAudioBuffer.sampleRate);
after_data = original_channel_data.subarray(Math.floor(end *
originalAudioBuffer.sampleRate), (originalAudioBuffer.length *
originalAudioBuffer.sampleRate));

if(start > 0){
new_channel_data.set(before_data);
new_channel_data.set(empty_segment_data,(start *
newAudioBuffer.sampleRate));
new_channel_data.set(after_data,(end * newAudioBuffer.sampleRate));
} else {
new_channel_data.set(after_data);
}

}
//https://github.com/sb2702/audioRecord.js
//https://github.com/zhuker/lamejs/issues/7
console.log("newAudioBuffer"+newAudioBuffer);
//Float32Array
var float32 = newAudioBuffer.getChannelData(0);

var dataview = encodeWAV(float32);
var audioBlob = new Blob([dataview], { type: 'audio/wav'});

var url = (window.URL || window.webkitURL).createObjectURL(audioBlob);
var link = window.document.createElement('a');
link.href = url;
link.download = 'output.wav';
var click = document.createEvent("Event");
click.initEvent("click", true, true);
link.dispatchEvent(click);

function floatTo16BitPCM(output, offset, input){
  for (var i = 0; i < input.length; i++, offset+=2){
    var s = Math.max(-1, Math.min(1, input[i]));
    output.setInt16(offset, s < 0 ? s * 0x8000 : s * 0x7FFF, true);
  }
}

function writeString(view, offset, string){
  for (var i = 0; i < string.length; i++){
    view.setUint8(offset + i, string.charCodeAt(i));
  }
}

function encodeWAV(samples){
  var buffer = new ArrayBuffer(44 + samples.length * 2);
  var view = new DataView(buffer);
  var numChannels =1;
  var sampleRate = 48000;

  /* RIFF identifier */
  writeString(view, 0, 'RIFF');
  /* RIFF chunk length */
  view.setUint32(4, 36 + samples.length * 2, true);
  /* RIFF type */
  writeString(view, 8, 'WAVE');
  /* format chunk identifier */
  writeString(view, 12, 'fmt ');
  /* format chunk length */
  view.setUint32(16, 16, true);
  /* sample format (raw) */
  view.setUint16(20, 1, true);
  /* channel count */
  view.setUint16(22, numChannels, true);
  /* sample rate */
  view.setUint32(24, sampleRate, true);
  /* byte rate (sample rate * block align) */
  view.setUint32(28, sampleRate * 4, true);
  /* block align (channel count * bytes per sample) */
  view.setUint16(32, numChannels * 2, true);
  /* bits per sample */
  view.setUint16(34, 16, true);
  /* data chunk identifier */
  writeString(view, 36, 'data');
  /* data chunk length */
  view.setUint32(40, samples.length * 2, true);

  floatTo16BitPCM(view, 44, samples);

  return view;
}

 }
}

**Comment by katspaugh** [comment]
Try looking at this library: https://github.com/zzarcon/microm
