### ISSUE TITLE
How to save wavesurfer.backend.buffer as file

### ISSUE THREAD

**Issue by designscripting** [katspaugh/wavesurfer.js#554]
Hi,

Is there way we can save wavesurfer.backend.buffer to file?
Will be helpful.

Thanks
Saravanan B

**Comment by thijstriemstra** [comment]
I'll add an example or documentation for this.

**Comment by katspaugh** [comment]
Apparently, [RecordJS](https://github.com/mattdiamond/Recorderjs) has a method to export into a file. It uses a Web Worker for that.
