### ISSUE TITLE
fiveLoadSub

### ISSUE THREAD

**Issue by wilsonlmh** [katspaugh/wavesurfer.js#556]
Hi, I wrote an web-based subtitling app with waversurfer.js. I'd like ask if you can add it into the `Project` list(https://github.com/katspaugh/wavesurfer.js/wiki/Projects). Please find my project here:
https://wilsonlmh.github.io/fiveLoadSub/
Thank you very much!

**Comment by thijstriemstra** [comment]
Cool! You can edit the page yourself and it there, it's a wiki! :)

**Comment by katspaugh** [comment]
I'll add it, the wiki is writable only by contributors.

Nice project! I made a similar app, btw: http://katspaugh.github.io/videobook/

**Comment by wilsonlmh** [comment]
Thank you very much and hope you will enjoy and share my app. Also currently fiveLoadSub cannot work with large file. I guess it's mostly relate to wavesurfer. I will try to figure some way to reduce memory usage and contribute back to here. Thanks again!

**Comment by katspaugh** [comment]
@wilsonlmh yes, it's because of wavesurfer. In videobook I don't have crashes with big files, because it's not using wavesurfer. It will be awesome if you find out the reason! :thumbsup:
