### ISSUE TITLE
Waveform is not drawn in annotations when pixelRatio set to default on retina display

### ISSUE THREAD

**Issue by chinshr** [katspaugh/wavesurfer.js#558]
I am running into issues in your [annotations example](https://github.com/katspaugh/wavesurfer.js/blob/master/example/annotation/app.js#L14) and setting `pixelRatio: 2`. The waveform is not drawn at all, only inside the minimap. When I set `pixelRatio` back to `1` it works fine. Is there any workaround for retina displays?

<img width="898" alt="screen shot 2015-10-25 at 11 52 02 pm" src="https://cloud.githubusercontent.com/assets/29537/10722984/70859382-7b73-11e5-9ee4-9593ae168ee4.png">

Here is the [line of code](https://github.com/katspaugh/wavesurfer.js/blob/master/example/annotation/app.js#L14) I modified in `examples/annotation/app.js`:

```
    wavesurfer.init({
        container: '#waveform',
        height: 100,
        pixelRatio: 2,  // instead of `1` as set in the example
        ...
    });
```

**Comment by katspaugh** [comment]
The waveform on that page is very big, so it gets over size restrictions in Canvas. I have one idea though, stay tuned for a patch.

**Comment by chinshr** [comment]
Great, thanks for giving it some thought, I am curious about your approach? I will definitely watch out for some updates. 

Interestingly the MiniMap shows the waveform. The average duration of most of the media files I am going to be dealing with could be more than 20 mins in length (more like 60 mins), would that be a problem?

Are there any other measures you can think of that I can take to prevent over size restricting on canvas? For example, reducing the waveform pre-calculated sampling rate? Currently, I am using 30 samples per second, shall I try to use less? Would reducing audio quality change anything?

**Comment by chinshr** [comment]
@katspaugh Let me know if I can help in any way or if there are any quick wins? Currently, any audio >20 minutes is not displayed correctly. That's a blocker in the app I am working on right now. I understand, that the workaround is setting the `pixelRatio` to 1, which, I estimate, would work for audio up to 40 mins.

**Comment by katspaugh** [comment]
The trick I had in mind didn't work. A proper solution will be tracked here: #512. See also #458.

**Comment by chinshr** [comment]
Sorry to hear that it didn't work. Thanks for the pointers. Multiple consecutive canvases with chunked audio? You can probably go ahead and close this issue.
