### ISSUE TITLE
How can I determine if an audio waveform can fit in width?

### ISSUE THREAD

**Issue by chinshr** [katspaugh/wavesurfer.js#559]
Sometimes, my audios are short enough and can fit inside the entire width, so I won't need to use a Minimap to navigate. How can I determine easily if the current audio fits inside the display width? As I am resizing the window, the waveform may not fit anymore, in that case I would like to enable the Minimap again. How would that work inside the code?

<img width="1072" alt="screen shot 2015-10-25 at 11 58 42 pm" src="https://cloud.githubusercontent.com/assets/29537/10723076/5ca56206-7b74-11e5-9078-97e0b5eebb3d.png">

**Comment by katspaugh** [comment]
You can do `wavesurfer.drawer.width / wavesurfer.params.pixelRatio > wavesurfer.drawer.wrapper.clientWidth`.

You can add a method `wavesurfer.hasScroll` with this code if you want, I'll accept a PR.

**Comment by chinshr** [comment]
@katspaugh thanks for the sample code. Good idea, I want to spend some time on a PR to support `wavesurfer.hasScroll` this week.

**Comment by chinshr** [comment]
Follow up question: how can I toggle hide and show the minimap?
