### ISSUE TITLE
How can I toggle hide and show the minimap?

### ISSUE THREAD

**Issue by chinshr** [katspaugh/wavesurfer.js#562]
In case the full waveform fits on the screen without scrolling, I would like to hide the minimap until I would need it again, for example, if I resize the browser window, the waveform may need scrolling for which I would like to enable the minimap again (relates to #559).

If there is currently no easy way to do that, I can work on a pull request, if you want to give me some hints?

**Comment by katspaugh** [comment]
Just hide/show it via CSS?

**Comment by chinshr** [comment]
Yeap, got it, thanks.

**Comment by jbeyer05** [comment]
Naive question, chinshr, but how did you select the minimap?  There isn't a unique id or class for the html element, and there doesn't seem to be a clean way to give the minimap a unique id or class.  Thanks in advance.

**Comment by chinshr** [comment]
Ideally, I would want to use something like this `this.wavesurfer.minimap.hide()`. There is no super clean way to select the minimap, but it is possible, and good enough for me at this point.

**Comment by jbeyer05** [comment]
chinshr, did you end up with a decent solution?  I ended up modifying Drawer.createWrapper( ) with the line below.  I could then pass in an HTML id to wave_surfer.initMinimap( ).  If you have a solution that didn't involve modify wave surfer source, I'd love to hear it.
if( this.params.id ) { this.wrapper.id = this.params.id; }

**Comment by chinshr** [comment]
I will give it a try, I played with the display none briefly and hacked something. Thanks for the code. I would have to submit a PR if I wanted to change the behavior.
