### ISSUE TITLE
Zoom and Regions plugins don't work cleanly together

### ISSUE THREAD

**Issue by jbeyer05** [katspaugh/wavesurfer.js#563]
Unless I'm doing something very wrong with the two, if I combine the zoom and regions plugin, they don't work properly together.
As an example, if I'm zoomed out fully, and select the region from 0:00 to 0:10, and then zoom in 2x, the selected region is now 0:00 to 0:05.  Does it seem like I'm doing something wrong, or are they simply incompatible at the present time?
Thanks in advance.

**Comment by jbeyer05** [comment]
It would appear that I was a few versions behind for wavesurfer.js.  Didn't really the project was moving so quickly.  I'll report back in a few hours, but I believe the newer version fires the zoom event and should handle properly.

**Comment by LuganOcode** [comment]
Did you get this to work?  I am seeing the same issue, despite using the latest CDN version (1.1.5).

**Comment by jbeyer05** [comment]
Yes, everything worked when I upgraded to what was the latest version at the time.  Don't have access to the project right now, so I couldn't tell you what version that was.

**Comment by LuganOcode** [comment]
Thanks for the reply.  It seems to be related to minPxPerSec, and the size of the window.  If I set minPxPerSec sufficiently high, it always works correctly, but if the value is too low (again, depends on the size of the window when you load file), it will screw up until the zoom activates the scrollbar.  The downside to setting a high default for the minPxPerSec is that after first zooming, you cannot seem to go back to zero-level zoom.

Seems to be something to do with the 'zoom' not actually zooming right away - if that makes any kind of sense.
