### ISSUE TITLE
load from file:///

### ISSUE THREAD

**Issue by smolleyes** [katspaugh/wavesurfer.js#566]
hi

i start a new project for fun with nwjs and koajs, wavesurfer is right but i can t load files from file:// protocol i have an xhr error with the arraybuffer

``` Exception: DOMException: Failed to read the 'responseText' property from 'XMLHttpRequest': The value is only accessible if the object's 'responseType' is '' or 'text' (was 'arraybuffer') ```

no way to support this file protocol ?

thanks

**Comment by smolleyes** [comment]
if i use mediaElement backend it works but i can t get wave displayed :/ just the flat line...

**Comment by katspaugh** [comment]
No.
