### ISSUE TITLE
add visualisation plugin ?

### ISSUE THREAD

**Issue by smolleyes** [katspaugh/wavesurfer.js#567]
hello

no way to add a simple visualisation system like this ?

https://developer.mozilla.org/en/demos/detail/html5-audio-spectrum-visualizer

thanks !

**Comment by katspaugh** [comment]
Not sure what you asking. We have a plugin that renders a spectrogram – http://wavesurfer-js.org/example/spectrogram/. Realtime spectrum analyser is built into Web Audio, see this tutorial: http://www.smartjava.org/content/exploring-html5-web-audio-visualizing-sound.

**Comment by smolleyes** [comment]
hi

little bit fast to close my questions no Oo ?

i  ask if it s possible to draw this 

http://www.smartjava.org/examples/webaudio/example3.html

in another canvas in the same time than wavesurfer display his waveform and read the file .... 

thnaks
