### ISSUE TITLE
Play .m3u playlists

### ISSUE THREAD

**Issue by chinshr** [katspaugh/wavesurfer.js#571]
I love wavesurfer.js! It would be great to have a way to play .m3u [playlists](http://www.boutell.com/newfaq/creating/playlist.html) in wavesurfer.js, because m3u playlists reference smaller mp3 snippets within. The idea is to (a) employ it to use it as streaming audio format, and, (b) consecutively play smaller mp3 "snippets" that can be loaded and rendered properly, given they are small enough (solve some of these #558, #512 or #458). In my case, I am pre-generating the waveform (json) ahead, so I could also provide smaller waveform snippets along with the mp3 equivalent and reference them from within the m3u (if that's possible). Essentially, something like this:

``` js
var wavesurfer = WaveSurfer.create({
    container: '#wave',
});
wavesurfer.load('http://example.com/audio.m3u');
```

Would love to hear your thoughts on this and if you think this is the right approach to some of the problems we are seeing with larger files? If this makes sense, I am more than willing to sponsor a development effort. Please outline in enough detail on how someone could implement it?

**Comment by katspaugh** [comment]
The outline of the work to be done:

 * Replace the scroll bar with in-canvas "scrolling" (a la peaks.js)
 * Add the ability to display a list of audio tracks as a single waveform
 * Read m3u files (not sure if you really want this—can just pass a list of URLs directly to load).

**Comment by chinshr** [comment]
Thanks for the outline. Looking into peaks.js, I am wondering where the two libraries significantly differ from each other. I want to explore peaks.js, mainly for the architectural difference that larger audio files can be rendered properly.

**Comment by entonbiba** [comment]
@katspaugh @chinshr I'll create a parser for m3u files. Essentially it would create an array of mp3 lists which can be switched via a "next" and "prev" methods. Not sure if combining all the files from a .m3u file would be feasible due to size and browser resources for now.

**Comment by thijstriemstra** [comment]
There's a playlist plugin now that handles this.
