### ISSUE TITLE
seekTo and seek event fires when creating a region

### ISSUE THREAD

**Issue by jbeyer05** [katspaugh/wavesurfer.js#572]
Thanks in advance for a wonderful tool.  I have a fairly simple project with regions.  When a new region is created, wavesurfer seems to seekTo to the point of the mouseup action and fires a corresponding seek event.
This would seem to be unintended behavior.  Or is this the intended behavior?

**Comment by jbeyer05** [comment]
One other area where there seems to be similar unintended behavior is when the user drags a region.  When the user drags a region, a click and seekTo event is fired at the area where the user stops dragging the region.

**Comment by jbeyer05** [comment]
One more comment.  If this is indeed unintended behavior, I have created a fairly ugly hack, but I'm not sure how to integrate cleanly.  When the region event listener eventUp( ) senses the end of a completed region, I log the time in a global variable.  In the 'click' event listener in wavesurfer.js, I compare the timestamp in the global variable to the current time.  If it happened in the last 200ms, I do not call seekTo( ).

**Comment by katspaugh** [comment]
Try adding [`stopPropagation`](https://developer.mozilla.org/en/docs/Web/API/Event/stopPropagation) in the `mouseup` handler instead.

**Comment by David-Crty** [comment]
Hello,

 I have tried the stopPropagation function on mouseup but not working.
```javascript
var wave = $('#wave');
var wavesurfer = WaveSurfer.create({
    container: '#wave'
 });
wave.on('mouseup', '.add-comment', function (event) {
    console.log('mouseup');
    event.stopPropagation();
});
```
I see the log mouseup when i click on .add-comment but the seek event fire all the time :(

**Comment by thijstriemstra** [comment]
#1295 seems to fix this, please re-open or leave comment if this is not fixed in 2.x.
