### ISSUE TITLE
undefined is not a constructor (evaluating 'new window.OfflineAudioContext(1, buffer.length, buffer.sampleRate)')

### ISSUE THREAD

**Issue by hems** [katspaugh/wavesurfer.js#577]
I got this error on Safari ( running latest version on El Capitan ).

![screen shot 2015-11-10 at 17 38 27](https://cloud.githubusercontent.com/assets/27327/11070136/e116b800-87d1-11e5-9e31-8540838511ab.png)

chrome doesn't display errors, but renders weirdly short and then stretch:

![screen shot 2015-11-10 at 17 39 45](https://cloud.githubusercontent.com/assets/27327/11070174/1a054500-87d2-11e5-9134-c56f9f68a1bd.png)

**Comment by katspaugh** [comment]
I think Safari still needs a `webkit` prefix for `OfflineAudioContext`.

> but renders weirdly short and then stretch

Yeah, it's a known issue with this plugin. That's the way offline rendering works, very unreliable. Cannot fix.

**Comment by katspaugh** [comment]
Solved in #619.
