### ISSUE TITLE
Help drawing the waveform real time ( using data stream instead of WebAudio / mediaElement ) ?

### ISSUE THREAD

**Issue by hems** [katspaugh/wavesurfer.js#578]
I'm currently receiving my stereo audio data as two float numbers, one for left and another one for right channel and i would like to draw the waveform in real time, scrolling from he right to the left side of the screen.

The perfect reference is [Schwa Schope](http://www.stillwellaudio.com/plugins/schope/), since it let's you "zoom out" horizontally, so you can actually see the shape of the sound, for instance, a kick drum will look like a kick drum going from the right to the left of the "window", in other words the user will see a couple of seconds of the waveform instead of a very short buffer. 

There is also an [example here](http://www.waveformjs.org/#fly), once the "window is full" then it works the way i would like to make it, as in, scrolling from right to left!

I had a look on the microphone example trying to figure out where to inject my 0's and 1's, but i couldn't really find it. Any tips would be more than appreciated !

The idea would be fore every frame received from my data stream i would push a "frame" to waveform.js, like the [waveform.update from wavefom.js](http://www.waveformjs.org/#functions) but i would render it "split" channels as the example in wavesufer.js' website!

After this i'll also be interested in drawing the same kind of waveform in real time from an audio tag on the HTML, but for now using my data stream is the real problem.

Thank you very much for such nice project! Any help is more than appreciated!

**Comment by hems** [comment]
So i manage to achieve that with waveform.js by pre-populating the "data" object with an array full of "0" and then calling waveform.update() on every frame !

Would be nice to test it using wavesurfer.js !

**Comment by X-Raym** [comment]
@hems 
So, if I understand, you are trying to find a way to be able to make the waveform to be drawn as the file is downloading, while allowing play ?
Can you show us on example on how to archive this ?

**Comment by hems** [comment]
So i first setup my dom to have 1 pixel width per item in the "data" array, and pre populate "data" with 0.03 instead of 0 so i always get a solid horizontal line on my canvas.
 
````coffeescript
    MAX_WIDTH = 301
    VOL_FLOOR = 0.03

    # setup my dom element 
    @dom.width  MAX_WIDTH
    @dom.height 31

    data = []

    # pre populate data with VOL_FLOOR, so i always have 1 px solid line horizontaly
    for i in [0...MAX_WIDTH]
      data.push VOL_FLOOR

    waveform = new Waveform
      container: @dom[0]
      data     : []
      width    : MAX_WIDTH
      height   : 31
      innerColor : "#dedede"
      interpolate: false

    ctx = waveform.context;

    gradient = ctx.createLinearGradient(0, 0, 0, waveform.height);
    gradient.addColorStop( 0.2,  "#fff" );
    gradient.addColorStop( 0.49, "#999" );
    gradient.addColorStop( 0.51, "#999" );
    gradient.addColorStop( 0.8,  "#fff" );

    waveform.innerColor = gradient;

    waveform.update data: data
````

i have a function "set_volume" which receives the audio buffer from my audio player, and update the current_volume variable using the left channel ( i still need to figure out a smart way of drawing the stereo, like the half top of the canvas would be left and the bottom would be right, or two colours overlapping... i'm still not sure...

````coffeescript

  set_volume: ( buff ) ->
     
    # Math.min to VOL_FLOOR to keep the horizontal line
    current_volume = Math.max( buff[0], VOL_FLOOR )

````

I redraw the graph on every frame:
````coffeescript
draw = ->
  data.push Math.max( current_volume, VOL_FLOOR )

  data = data.slice( -MAX_WIDTH )

  waveform.update data: data

  animation_id = window.requestAnimationFrame( draw )
````

You can try the application from your browser: http://beta.loopcast.fm !

**Comment by X-Raym** [comment]
Thanks for the infos :) It looks clever !
I don't see where is the waveforms preview on this page (or site). I don't even see wavesurfer.min.js in the ressources. Can you point us to a demo ?

**Comment by thijstriemstra** [comment]
yeah @hems a demo would be very nice

**Comment by hems** [comment]
@X-Raym / @thijstriemstra  you have to click "Start Stream", then you "create a room", you will be asked to download a little "app", which works like dropbox.. it's just a simple "agent" on your taskbar, once you do that, you will be able to select any audio input from your computer and see the waveform in real time.

When you press "Go live" you can send the link to a friend to listen your audio streaming, or press "start recording" for the server to start recording your audio input!

Let me know how if works for you!

**Comment by X-Raym** [comment]
@hems 
Wow ok, this is a whole web app integration (nicely done BTW :P), thanks for the detailed explanations.

So there is things a bit different that I was expected, your player looks closer ton an advance use of the Microphone plugin than the standard method (loading a file), so I have a question:
The waveforms is being drawn continuously from the right of the wavesurfer element, and moved to the left progressively. Do you think your trick could be easily transfmorm to make it work on static waveforms (loaded from left to right), according to an audio file length (no a "analysis window" like you have) ?

Bravo again for your integration, it looks very pro and is very efficient (no visible latency... Quite impressing).

**Comment by hems** [comment]
@X-Raym thanks!

We decided to go with a desktop application so we can be compatible with all the browsers and also in case the browser crash the "agent" will keep streaming !

Yes indeed this is some sort of "microphone input" kind of application, but that doesn't really matter if you expose an "update" method like waveform.js does!

This way people can use your drawing API in an agnostic way, without strings attached to an audio tag or some "browser.getMultimediaCapabilitiesW3CES6CamelCaseFromHellMethod()" !
