### ISSUE TITLE
No LICENSE file included with the NPM module

### ISSUE THREAD

**Issue by odzb** [katspaugh/wavesurfer.js#580]
Unfortunately, without the a LICENSE file (with full license text) being included in the NPM package, official legal status of wavesurfer.js becomes dubious. I know that the license is linked from the package page at npmjs.com, but from legal point of view that's not enough. It's not legally clear what EXACT license text is the module distributed under.

This causes the legal department of our "BigCorp" to preclude us from including such modules in our apps. So this is indeed a big issue, not something cosmetic. We like wavesurfer, but we'll be forced to find a replacement for it if this issue is not fixed.

**Comment by thijstriemstra** [comment]
Could you make a pull request with the full text of CC-by-3.0, I don't see why including it would be a problem.
