### ISSUE TITLE
Bug in documentation

### ISSUE THREAD

**Issue by SeanBannister** [katspaugh/wavesurfer.js#581]
In the README.md and on http://wavesurfer-js.org (in multiple locations) there's the following code example:
```
wavesurfer.init({
    container: '#wave',
    waveColor: 'violet',
    progressColor: 'purple'
});
```

Which should be:
```
wavesurfer.init({
    container: document.getElementById('#wave'),
    waveColor: 'violet',
    progressColor: 'purple'
});
```

**Comment by katspaugh** [comment]
`document.getElementById('#wave')` is wrong. You probably meant `document.getElementById('wave')`. In any case, the `container` param accepts both a selector string and a DOM element.

**Comment by SeanBannister** [comment]
I'm so sorry totally my mistake, 2am here :)

**Comment by katspaugh** [comment]
No problem, thanks for reading it through!
