### ISSUE TITLE
Possible bug with barWidth or SoundCloud's peak data?

### ISSUE THREAD

**Issue by SeanBannister** [katspaugh/wavesurfer.js#582]
I have a waveform that looks like this:
![image](https://cloud.githubusercontent.com/assets/197231/11094786/668ab80e-88dd-11e5-98df-de857f5d7a18.png)

But when I use barWidth it looks like this:
![image](https://cloud.githubusercontent.com/assets/197231/11094725/1b88cc24-88dd-11e5-9dd6-ff33c16a3e83.png)

I partly understand why this is happening, I'm not generating the peak data with Wavesurfer (when I do it does displays correctly) I'm grabbing this peak data from SoundCloud [(here)](http://www.waveformjs.org/w?url=https://w1.sndcdn.com/zSGGi0P9EJZF_m.png) which you'll notice only provides mono peak data (top half of the waveform) I generate the bottom half by looping through the array and generating a negative of every number.

I totally understand this isn't Wavesurfers fault but I'm trying to figure out why the peak data looks fine without barWidth and so mangled with it? As it would be great if users could use Soundclouds peak data to avoid generating it client side.

There's a full demo here http://codepen.io/SeanBannister/pen/rOQqEN

**Comment by katspaugh** [comment]
`barWidth` is probably a bit broken. You can try adding `reflection: true` as a quick fix:
http://codepen.io/katspaugh/pen/NGEeMb?editors=101
