### ISSUE TITLE
Wav File Errors 32-bit & 64-bit Bits Per Sample

### ISSUE THREAD

**Issue by bleib1dj** [katspaugh/wavesurfer.js#585]
I'm using wavesurfer to load up audio files in an Electron (0.33.6) application. Everything works great for wave files that are 16 bits per sample but any wave files that I attempt to load via `wavesurfer.loadBlob(request.response)` that are 32 or 64 bits per sample cause the following errors:

    (anonymous function) @ wavesurfer.min.js:4
    WaveSurfer.Observer.fireEvent @ wavesurfer.min.js:4

I was looking through the documentation and didn't see any options to specify the expected bits per sample but I could have missed something.

### Example of Working Files ###
Sample Rate: 44,100
Bits per Sample: 16
https://s3.amazonaws.com/esg-auto-test/audio03.wav

Sample Rate: 44,100
Bits per Sample: 16
https://s3.amazonaws.com/esg-auto-test/audio06.wav

### Example Non-Working Files ###
Sample Rate: 44,100
Bits per Sample: 32
https://s3.amazonaws.com/esg-auto-test/Test-channel03.wav

Sample Rate: 8,000
Bits per Sample: 64
https://s3.amazonaws.com/esg-auto-test/audio02.wav

**Comment by katspaugh** [comment]
Thanks for the detailed report. Why don't you file a bug with Chromium?

**Comment by bleib1dj** [comment]
That's a great question :). I originally thought it was a wavesurfer issue but did some more testing and each of the audio files works great in Safari 9.0.1 and continue to fail out in Chrome 46.0.2490.86. I'll open up a ticket with chromium. Thanks for the assistance.
