### ISSUE TITLE
Extract region function not working

### ISSUE THREAD

**Issue by abhiit61** [katspaugh/wavesurfer.js#587]
Hi,

I want to draw region when the audio loads in browser. I found one function "extractRegions" for that. It works for the sample audio used in example but not with my audio files. I have to change the minValue for that. But it is different for different audio files.

Let me know if any other changes needed to work extract region function with all audio files.

Thanks

**Comment by katspaugh** [comment]
Try tweaking both `minValue` and `minSeconds`: https://github.com/katspaugh/wavesurfer.js/blob/51e2b3db0cd9b3ed1ab070c4890ad986929c570f/example/annotation/app.js#L140-L141

`minSeconds` is the minimum length of the region.

**Comment by abhiit61** [comment]
Thanks for the reply.

I tried changing both the values. But as I said it doesn't work for all the audio files. The default value works for the sample audio in sample example but not with my audio. If I change it then it worked for my audio but not for sample audio.

I think there should be some calculation so that we can make it work for all the audio.

Thanks again for the response.
