### ISSUE TITLE
WaveSurfer-WP — A WordPress Integration for WaveSurfer

### ISSUE THREAD

**Issue by X-Raym** [katspaugh/wavesurfer.js#590]
Thanks to the new HTML initialization, I manage to make wavesurfer.js avaible for WordPress.

It hooks the regular audio shortcode for being activated on already online articles. It also allows to have an audio player within the visual editor.
Waveforms colors are customizable within the WaveSurfer Settings page.
I also integrated split channels attribute.

[Demo here](https://www.youtube.com/watch?v=TbwWU2hUz3k&feature=youtu.be).

More infos and release soon!

@katspaugh 
I hope you will like it :)

**Comment by katspaugh** [comment]
Very cool, thank youl! Please keep us posted, I'll update the project wiki with a link to your plugin.

**Comment by X-Raym** [comment]
The plugin is now downloadable on the WordPress official plugin repo !
[WordPress › WaveSurfer-WP « WordPress Plugins](https://wordpress.org/plugins/wavesurfer-wp/)

:+1:

**Comment by X-Raym** [comment]
V2.0.0 has WebAudio initialization !
Maybe it deserve a place on the project wiki list now ? :)

**Comment by katspaugh** [comment]
Sorry, I totally forgot. [Added](https://github.com/katspaugh/wavesurfer.js/wiki/Projects). Thanks!
