### ISSUE TITLE
Supported Formats

### ISSUE THREAD

**Issue by X-Raym** [katspaugh/wavesurfer.js#591]
Hi,
It seems that WaveSurfer is not able to draw waveforms for certain audio format.
Can you please update a list of different extension-format-codec-bitdepth-sample rate that it can support ?
Thanks :)

**Comment by X-Raym** [comment]
Ok it seems that limitations I faced are browser limitations.like 24 bits wav in Firefox.

**Comment by katspaugh** [comment]
As you said, audio formats support depends on browsers.
