### ISSUE TITLE
Cursor Position Refreshing Rate

### ISSUE THREAD

**Issue by X-Raym** [katspaugh/wavesurfer.js#592]
Hi,
I was wondering
the cursor position (in HTML init) is based on audio element current time value.
Is it possible to have a higher refreshing rate, so that the cursor move more smoothly ?
Currently, it is just a bit jumpy (not as fluid as other players).

Thanks ! :)

**Comment by katspaugh** [comment]
Are you talking about the Web Audio's `audioprocess` event or the Media Element's `timeupdate`? The frequency of the former is rather hight, so I would think it should be even capped down.

On the other hand, `timeupdate` might be rather slow indeed. Maybe adding CSS transition would help.

**Comment by X-Raym** [comment]
@katspaugh 
I'm talking about the speed of the cursor (don't don't what event is related to it).
If you compare HTML init version and regular jQuery init version,
you will see that jQuery version has a very more fluid cursor.

On your website, the cursor is very fluid,
but if you compare HTML init version of your [codepen](http://codepen.io/katspaugh/pen/WQXzpB), you will see that the cursor is a bit "jumpy".

Do you think it can be more fluid for HTML init version ?

**Comment by katspaugh** [comment]
I see what you mean. This is because Media Element's `timeupdate` event's frequency is quite low. CSS transition didn't help. HTML version uses Media Element for the sake of the built-in player UI it provides.

Since you are creating your own player, you could use the JavaScript init instead, with `WebAudio` as the backend.

**Comment by X-Raym** [comment]
@katspaugh 
Do you mean adding data-backend="WebAudio" on wavesurfer HTML Tag ? this doesn't produce audio tag... How could I play the sound then ?
I think I have to use HTML init because it is how WordPress shortcodes (in post content) are render, it can't push javascript datas (as far as I know), only pure html.
That's why I had to make my own buttons.

I'm not that experienced in javascript/jQuery (this project is a way to learn a bit more), so maybe there was more optimum ways to do. Still a bit hard to put all this together.

Anyway, thanks for your support, it helps !

**Comment by katspaugh** [comment]
As far as I understood you still use some JavaScript to bind the buttons. So I suppose you could insert `<div id="wavesurfer_0"></div>` in place of the shortcode and bootstrap wavesurfer.js from JavaScript (like in the readme).

**Comment by X-Raym** [comment]
Replacing by the shortcode by the div is possible, I'm not quite sure how to handle the javascript behind that (in a dynamic way, so that each audio shortcodes are replaced by a wavesurfer player), I guess I'll need to make some tests,
and re-read the readme very very carefully !

**Comment by X-Raym** [comment]
Hi !
So I manage to have WebAudio init, and to push infos from the HTML block to the Init function, so that it be modified from a WordPress render output.
The cursor refresh is nicer and it seems to work fine !

But I struggle to rebuild my own buttons controller, I'm pretty sure it is a small thing but I can't figure it out.
Can you take a look ?

Here is the [CodePen Link](http://codepen.io/X-Raym/pen/GoNrML).

When I press "play/plause", it triggers all the wavesurfer player on the page.

What did I do wrong ?

I think I will be able to rebuild all my other buttons from here but for the moment I'm a bit stuck.

Thanks for your support !

**Comment by X-Raym** [comment]
Fixed !
