### ISSUE TITLE
Split Channel??

### ISSUE THREAD

**Issue by abhiit61** [katspaugh/wavesurfer.js#594]
Hi,

Can any one tell me what is the use of Split Channel functionality and how to use it?

Actually I want to show waveforms for multiple audio files but all will have one play/pause button and the cursor. The Split Channel example looks like the same what I want but I don't understand how I can use it as I have multiple audio files.

**Comment by katspaugh** [comment]
Split channel does exactly what it says on the tin, i.e. splits left and right channels into two waveforms.

> Actually I want to show waveforms for multiple audio files but all will have one play/pause button and the cursor.

It's not what split channel does. You need to program this behaviour in your app.
