### ISSUE TITLE
timer in waveform

### ISSUE THREAD

**Issue by marcjonesdinero14** [katspaugh/wavesurfer.js#595]
Hello,

How i could have the timer on the waveform on prgress bar or above it.

THanks in adavnce

**Comment by katspaugh** [comment]
Use the [`audioprocess` event](https://github.com/katspaugh/wavesurfer.js#wavesurfer-events) like this:

```
wavesurfer.on('audioprocess', function (seconds) {
    document.querySelector('#timer').textContent = seconds.toFixed(2);
});
```

Codepen: http://codepen.io/katspaugh/pen/xwPYaw?editors=101

**Comment by marcjonesdinero14** [comment]
is there other way that when a user select on the waveform the timer will also be updated?depending on the location on which the user click on it?

Thanks in advance
