### ISSUE TITLE
Interchangeable Player

### ISSUE THREAD

**Issue by marcjonesdinero14** [katspaugh/wavesurfer.js#596]
Hi,

I would like to ask if how can we achieve this.
We have a list of the player. this will change when we click the play button on each list

How can we make that when i click the play it automatically plays and not the other player?
Also how can we stop the player when i click to a new one.. Right now when i play music 1 and click on to play music 2 it is also playing in the background and 2 files are playing at the same time..

How could we achieve this?

Thanks in advance

link: http://111.67.5.55/~robtransini/library-music/?f1=t_Fast&f2=&f3=&f4=

**Comment by katspaugh** [comment]
Try StackOverflow.
