### ISSUE TITLE
Convert second time into a minute second in this wave form

### ISSUE THREAD

**Issue by marcjonesdinero14** [katspaugh/wavesurfer.js#597]
Hello,

How i could convert my time from seconds to minute:seconds timeframe

Thanks

**Comment by katspaugh** [comment]
Please don't ask JavaScript questions here. Use Google, StackOverflow etc. I'll have to block you otherwise.

**Comment by marcjonesdinero14** [comment]
Im very sorry, i just want o convert the code you have given me to a minute second frame.. 

Sorry again i will not ask again in the future..

**Comment by katspaugh** [comment]
No worries, thank you.
