### ISSUE TITLE
Draw audio waveform using JSON data

### ISSUE THREAD

**Issue by cherishsantosh** [katspaugh/wavesurfer.js#599]
Can we draw audio waveform using JSON data

**Comment by katspaugh** [comment]
Yes, like this: http://codepen.io/katspaugh/pen/NGEeMb?editors=101
It's also in the README.

**Comment by cherishsantosh** [comment]
This example using [https://api.soundcloud.com/tracks/114419538/stream] API. I have my song, dont want to play, just draw a waveform visualization and playing animation.
