### ISSUE TITLE
Annotations from Database

### ISSUE THREAD

**Issue by Mamadou99** [katspaugh/wavesurfer.js#601]
Hi everybody, 
i want to know if it's possible to store annotations in Mysql, because with the downloadable source, there are only json files (rashomon.json and annotations.json) and it stores all the annotations in the same file and whatever the page i open it shows me the same annotations. i want the annotations to be linked to each file , and i think MYSQL would be perfect for it. But if i can do it with Json too, i would like to know how. 
Thanks !

**Comment by CWSites** [comment]
+1

**Comment by katspaugh** [comment]
Yes, you can store your data in a database. That's the purpose of databases. How you create regions from that data is a problem of your application. Use the API described in the README. If something specific is unclear or missing, ask/create a PR. Otherwise, buy a book or ask on StackOverflow.

**Comment by Mamadou99** [comment]
Lol wow. Okay thx
