### ISSUE TITLE
auto update timer 

### ISSUE THREAD

**Issue by marcjonesdinero14** [katspaugh/wavesurfer.js#603]
Hello,

I would like to ask if we could update the timer shown when i click on a specific location in the waveform.. It only automatically change when the music is playing but what if is in on pause state.. how i could update it automatically

Thanks in advance

**Comment by katspaugh** [comment]
Use the `seek` event which is documented in the README (have you tried reading it?). 
http://codepen.io/katspaugh/pen/xwPYaw?editors=101
