### ISSUE TITLE
how can i create a thumbnail (as jpg)?

### ISSUE THREAD

**Issue by KKopf** [katspaugh/wavesurfer.js#605]
hi,

i would create a thumbnail on my webserver (from a mp3 file).

(thumbnail load is faster for a mp3 gallery, as ever load all mp3 files).

how can this make?

**Comment by katspaugh** [comment]
Try googling "waveform png".

For example these links come out first:

https://trac.ffmpeg.org/wiki/Create%20a%20Waveform%20Image%20from%20an%20Audio%20Stream
https://github.com/beschulz/wav2png
