### ISSUE TITLE
Bring Back CommonJS Support?

### ISSUE THREAD

**Issue by skorlir** [katspaugh/wavesurfer.js#608]
It looks like WaveSurfer still has an NPM module, but there's (seemingly) no longer a CommonJS module being exported in the code. Which makes me sad, since I'm using Browserify and it would be supremely convenient to be able to `require` wavesurfer.js from NPM.

Is there a reason why #139 got rolled back? It looks like you made a move from Makefile to Grunt, so could that be why?

If there's anything I can contribute to make this possible, let me know.

**Comment by katspaugh** [comment]
There's a task in the grunt file to build a CommonJS package: https://github.com/katspaugh/wavesurfer.js/blob/master/Gruntfile.js#L40

I'm not sure why we stopped saving it into the repository. Let's add it back.

**Comment by skorlir** [comment]
:+1:

Awesome, thanks!

**Comment by thijstriemstra** [comment]
@skorlir yes thanks! This would also eliminate the 'amd build' target in the grunt file. We should also look at how this affects the plugins, perhaps they should also need a universal umd/amd etc header.

**Comment by skorlir** [comment]
As best I can tell from my most recent `npm i wavesurfer.js` install (just now), `wavesurfer.cjs.js` is tracked, but the package.json `main` entry isn't right for NPM to resolve the module.

That's all I have so far. https://github.com/skorlir/wavesurfer.js

Plugins are currently inconsistent. `wavesurfer.microphone.js` and `wavesurfer.timeline.js` have an AMD header, but not UMD/CJS. `wavesurfer.minimap.js` is written entirely inside of a single call to `WaveSurfer.util.extend`, and then directly modifies the `WaveSurfer` object at the end. The others add fields to the `WaveSurfer` object directly, then use `WaveSurfer.util.extend` to implement `WaveSurfer.Observer`. I don't quite understand everything going on with plugins.

In a Node/CommonJS context, it makes sense to me that WaveSurfer plugins would be registered programmatically. `WaveSurfer.registerPlugin(require('wavesurfer.js-microphone-plugin'))`, or some such. The existing system could be adapted without such a major refactor, I am sure.

[This](https://github.com/umdjs/umd/blob/master/templates/returnExports.js) appears to me to be the relevant UMD approach for adapting plugins. I'm looking into that now.

**Comment by mspae** [comment]
+1 for this issue. I'm currently working on a wrapper for React (https://github.com/mspae/react-wavesurfer) but it's a bit difficult without proper UMD support.

**Comment by skorlir** [comment]
Working on it today! I'm planning a PR to add UMD headers to plugins. Being cautious so far. Hence the research update. Will post here again when there's more to share.

**Comment by katspaugh** [comment]
Sounds cool! Looking forward to the PR!

**Comment by daversm** [comment]
:+1:

**Comment by thijstriemstra** [comment]
Looks like this still isn't fixed, the minified files are appended to. @skorlir looks like a clean step could be necessary.

**Comment by thijstriemstra** [comment]
@skorlir can you check if everything's working now? and what about https://github.com/katspaugh/wavesurfer.js/blob/master/.npmignore, should the plugins be added there, or should we get rid of this file?

**Comment by skorlir** [comment]
Well, we don't want to ignore any of the stuff in there anymore. And unless you're planning to bundle plugins and publish them to NPM separately, they should be tracked, too.

However, now that I'm looking at it, .npmignore should probably ignore tests, the README, and things like that. You don't want to download all those things every time you run `npm install`.

I think we should still have one, and ignore dev files that you don't want or need to download when you're using NPM.

What do you think?

**Comment by katspaugh** [comment]
We shouldn't ignore readme, I think.

**Comment by skorlir** [comment]
For NPM, though? I mean, if I was using WaveSurfer for production, I would drop in the wavesurfer.min.js file, I wouldn't download the readme. Same thing if I'm using it with Node, or even on the front-end with browserify or something.

**Comment by thijstriemstra** [comment]
@skorlir sounds good, can you make a PR we can discuss?

**Comment by katspaugh** [comment]
From [NPM docs](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package):

> The following paths and files are never ignored, so adding them to .npmignore is pointless:
package.json
README (and its variants)
CHANGELOG (and its variants)
LICENSE / LICENCE

**Comment by skorlir** [comment]
@katspaugh interesting; I didn't know that about NPM.

**Comment by thijstriemstra** [comment]
Having `wavesurfer.dev.js` in the NPM package wouldn't hurt either. I would use that during development or debugging issues.

**Comment by skorlir** [comment]
Sounds good. I'll submit a PR soon.

**Comment by whenov** [comment]
Is there any update on this?

**Comment by skorlir** [comment]
@whenov The issue title becomes a bit outdated by the time you get to the end of the thread. CommonJS support has been available (or, UMD support, actually) for a while. We were talking about hiding tests in .npmignore so that people using wavesurfer via NPM don't have to download them every time.

Then I got really busy and forgot all about it.

To avoid confusion, I'm going to re-close this issue. If tests were never added to .npmignore, a separate issue can be opened for that.
