### ISSUE TITLE
WebVTT Annotations

### ISSUE THREAD

**Issue by X-Raym** [katspaugh/wavesurfer.js#609]
Hi !
It would be nice if the annotations module support WebVTT captions
Just like the ELAN plugin, but with a WebVTT file as referance rather than an ELAN XML.

WebVTT are easier to create (then can be created manually if needed, which make theme technically very accessible),
and it is now part of the web standards format, so there is a lot of tools free to manage them.

[WebVTT - Reference Web API | MDN](https://developer.mozilla.org/fr/docs/Web/API/Web_Video_Text_Tracks_Format)

Also, because it is derived from the popular SRT subtitles format, it is very easy to use use SRT subtitles creation tools to export into to WebVTT.

What do you think of that ?

(I took a look at the elan.js wavesurfer plugin but I have to admit it is a bit off my league now :rabbit:  )

Thanks for your consideration,
and for WaveSurfer in general :yum:

**Comment by katspaugh** [comment]
Hi!
I've used WebVTT in another project (called [Videobook](https://github.com/katspaugh/videobook)), and it's nice indeed, especially for simple use-cases like subtitles (unlike ELAN which is used by linguists to annotate speech with multiple layers of annotations).

**Comment by X-Raym** [comment]
@katspaugh 
Oh cool ! so you know the beast :P
Does this mean that you plan to work to make a WebVTT intregration for WaveSurfer ? :)

**Comment by X-Raym** [comment]
Hi !
I dig this subject and I realized that maybe it is not needed to add code to WaveSurfer-js to make this work.

Here is a demo:
[Interactive Markers and Transcript for WaveSurfer-WP Premium](https://www.extremraym.com/en/wavesurfer-wp-markers/)

The markers code is public on this [Pen](http://codepen.io/X-Raym/pen/XNOmQb).

As you can see, we can make interactive transcripts already. Also, passing through a SRT parser first allow to makes text formatting (essentially, create paragraphs, more readable than having a line per subtitles).

What do you think about that ?

**Comment by katspaugh** [comment]
Good job! Looks really nice!

**Comment by X-Raym** [comment]
@katspaugh Cool :)
Well I close the issue then, I don't think a native solution is still needed, as it can be hand made. :P
