### ISSUE TITLE
ability to click and drag to move the cursor?

### ISSUE THREAD

**Issue by wolfbiter** [katspaugh/wavesurfer.js#61]
it seems like natural behavior, and what people are used to from things like music players and soundcloud.

**edit**: hmmm after thinking about it i realized i can implement this in my app with an onkeyevent bound to the div holding the waveform, and then calling seek from the handler. it would still be kinda cool if this could be implemented internally. 

... for that matter, a marker on hover would be cool too. same story.

**Comment by f-deniyi** [comment]
How do I implement click and drag,?

**Comment by tombburnell** [comment]
I see this is old but drag to seek would be very useful for those of us who have players that don't need any kind of selection -  many mobile users are asking me for it on my web player. They don't find the tap to seek intuitive.
Could it be an option when selection is not in use?

**Comment by katspaugh** [comment]
@tombburnell it's now implemented, pass `dragToSeek: true` in the options.

**Comment by tombburnell** [comment]
ok great thanks! I must have missed the option.

**Comment by tslater** [comment]
@katspaugh Can I confirm the intended behavior for the dragToSeek? In my current app, it doesn't seek until the drag is complete. Is that a bug or the way it is designed? What I'm looking for is a continuous seek (albeit throttled for performance) while the user drags.

**Comment by katspaugh** [comment]
There’s a [200ms debounce](https://github.com/katspaugh/wavesurfer.js/blob/main/src/wavesurfer.ts#L266) on the drag event but I’m open to removing it if it leads to a worse UX. Feel free to make a separate issue for it.
