### ISSUE TITLE
Safari support?

### ISSUE THREAD

**Issue by yzohar** [katspaugh/wavesurfer.js#616]
Is wavesurfer.js supports safari browser?

I'm going with safari to http://wavesurfer-js.org/ and the clip is not loaded (I get an image instead of the wave).
Thanks

**Comment by katspaugh** [comment]
It works in my Safari 9.0.2 (and was working in previous versions), as well as mobile Safari.

**Comment by yzohar** [comment]
I'm using Safari on Windows (safari 5.1.7 on win 10) and it is not loading anything, and there is not error message or anything

**Comment by katspaugh** [comment]
See #480.
