### ISSUE TITLE
audioprocess event is not fired on seeking

### ISSUE THREAD

**Issue by mspae** [katspaugh/wavesurfer.js#618]
The documentation states that `audioprocess` fires on seeking, however this is not the case when using `WebAudio`

~~This issue occurs with the default backend setting. When setting the backend to `MediaElement` the `audioprocess` gets fired on `seekTo`, however it doesn't actually do the seeking.~~

The `seek` event is fired correctly.

Here's my code for testing. Notice the different console log messages when (un)commenting the `backend` option when clicking the button. EDIT: Here's a codepen: http://codepen.io/anon/pen/RrxaKM

This is on Chrome 46.0.2490.86 and Firefox 42.0 for Linux.

``` html
<button id="seek-btn">Seek</button>
<div id="wave"></div>

<script src="node_modules/wavesurfer.js/dist/wavesurfer.umd.js"></script>
<script>
  (function(document) {
    var wavesurfer = WaveSurfer.create({
      container: '#wave',
      waveColor: 'violet',
      //backend: 'MediaElement',
      progressColor: 'purple'
    });
    wavesurfer.load('demo.wav');

    wavesurfer.on('audioprocess', function() {
      console.log('audioprocess fired!');
    });

    wavesurfer.on('seek', function() {
      console.log('seek fired!');
    });

    document.querySelector('#seek-btn').addEventListener('click', function() {
      wavesurfer.seekTo(0.5);
    });

  })(document);
</script>
```

**Comment by moshedri** [comment]
yep i have the some issue with that i had to name my function and call it with the two events one ofter another

```
wavesurfer.on('seek',showProgress);
wavesurfer.on('audioprocess', showProgress);
```

**Comment by mspae** [comment]
I'm labelling this v1 because the v2 docs don't mention that `audioprocess` should be called on `seekTo` :chicken:  and IMHO I think it's good we have two events for this (even if it does mean more code).

(I know I'm contradicting the me from two years ago, but I now think `audioprocess` should be reserved for when the audio is actually playing)

I've tested this with both backends (in v2) and they seem to be consistent:
- seekTo fires seek
- playback fires audioprocess

**Comment by thijstriemstra** [comment]
stale issue, closing.
