### ISSUE TITLE
mouse clicks on far right end of waveform don't seek all the way to mouse pointer

### ISSUE THREAD

**Issue by wolfbiter** [katspaugh/wavesurfer.js#62]
found this out with having waveform at 100% width of screen.

clicks on the left side of the seek to the mouse pointer. as clicks go further and further right, the seek falls behind. by the right side of the screen, the seek is behind by about an inch.

**Comment by belackriv** [comment]
I know this is old, but I was having the same issue.  I found a work around by setting css on the element containing the wavesurfer to 
```
#wavesurfer-container{
    overflow: hidden;
    zoom: 101%;
}
```
Maybe this will help someone.
