### ISSUE TITLE
[meta] wiki page permissions?

### ISSUE THREAD

**Issue by rozap** [katspaugh/wavesurfer.js#620]
Attempted to add my project [μsic](https://usic.space) but i don't think the edit permissions on the wiki are open enough, and afaik there's no PR workflow for wikis. 

thanks for the library btw, it works well for my use case :heart:

**Comment by katspaugh** [comment]
I'll add it for you. Just give me a short description of the project, please.

**Comment by thijstriemstra** [comment]
@rozap have a description?

**Comment by rozap** [comment]
Oops, sorry. 

It's a tool for learning songs by ear. You can slow down youtube audio without change pitch, and add section annotations.

**Comment by katspaugh** [comment]
Added, thanks!
