### ISSUE TITLE
Load all audio and play it from the left to the right

### ISSUE THREAD

**Issue by fari-99** [katspaugh/wavesurfer.js#622]
Hello, I want to know how to load all audio file and play it from the left to the right, I'm using example/playlist file to testing. so, after the first file finish, it will automatically play the second file.
in the playlist example just one file load, and after it finishes it will load the second one.

here's what I have done [ScreenShoot](https://drive.google.com/open?id=0Bx2zX0PaEY-HbTIyRE5ZdGNSZkk)

because the noob me all audio is loaded, but they are playing together. I just want the second one to play after the first one finish.
Tips will be really appreciated.

Thanks.

The code for [index.html](https://drive.google.com/file/d/0Bx2zX0PaEY-HNTVFWjNRMTN1Tzg/view?usp=sharing) and [app.js](https://drive.google.com/file/d/0Bx2zX0PaEY-HeTlIRUJ6QjJ4WUU/view?usp=sharing)

**Comment by katspaugh** [comment]
Basically, you need to trigger `play()` of the second wavesurfer from the `finish` event of the first one.

```
var wavesurfers = [ 0, 1, 2, 3, 4 ].map(function (index) {
    var surfer = WaveSurfer.create({ ... });
    surfer.on('finish', function () { wavesurfers[index + 1].play(); });
    return surfer;
});
```
