### ISSUE TITLE
Weird sound on iOS

### ISSUE THREAD

**Issue by martyLauders** [katspaugh/wavesurfer.js#624]
I'm using the plugin in an Ionic app. It's working really well, but on iOS I get a very ugly sound. It gets the music from preview files from spotify. Could that has something to do with it? On desktop it works perfectly, so it seems to be iOS related.

**Comment by mxmtsk** [comment]
+1 I have the same thing on iOS - the sound is somehow very noisy
http://ulrikejährling.de/referenzen/

**Comment by cankemik** [comment]
same here. any solutions to this issue ?

**Comment by kaitlynhova** [comment]
I'm having the same issue -- anyone have any ideas?

**Comment by cankemik** [comment]
@kaitlynhova i've tested on iphone 5s and 6. both are ios 9.

**Comment by martyLauders** [comment]
Me too, iOS9.

**Comment by AdolfVonKleist** [comment]
Maybe this?

http://www.html5gamedevs.com/topic/17326-ios-9-webaudio-issues/

http://www.holovaty.com/writing/ios9-web-audio/

Both suggest using 'touchend' instead of 'touchstart' (I have not yet
checked whether this could really be the issue here in the source, but it
seems plausible)

**Comment by katspaugh** [comment]
I experienced the coarse techno-like sound distortion in iOS Safari yesterday, too. It disappeared after a reload.

**Comment by a4jp-com** [comment]
I also heard this the first time I played recordings on my site just the first time on an iPad Pro. After everything had loaded, I pressed refresh everything played smoothly.

**Comment by juliusosokinas** [comment]
:+1:

**Comment by hobbes7878** [comment]
Continue to get distortion on iOS 9 on first load of the audio file.

**Comment by weavermedia** [comment]
Same here. Tested on iPhone 5S on iOS 9.3. Always disappears after a page refresh.

The sound is like a music production effect called a 'bitcrusher' which deliberately discards some of the audio information as a creative effect.

https://en.wikipedia.org/wiki/Bitcrusher

Hoping my description might help track down the cause. It could just be an iOS issue, although I haven't heard this distortion on any other audio clips on any other sites on my phone.

**Comment by katspaugh** [comment]
While I don't have a proper solution for this, a work-around would be to use the `backend: 'MediaElement` option if it's suitable for your application.

**Comment by sritej** [comment]
I am trying to use this plugin in a ionic app. I have copied the controller part and the html links to wavesurfer file. I am able to play the audio but the seekbar is not getting updated and when i select an other audio, the waves are not getting updated. Is there any one got it worked with an ionic app.

Any help is very much appreciated.
