### ISSUE TITLE
evnt mouseup don't triggered

### ISSUE THREAD

**Issue by beppetech** [katspaugh/wavesurfer.js#626]
Hello,
I'm trying to use mouseup event but it isn't triggered.
If I click on the wave form, the progression bar is moving correctly but my mouse event don't triggered.
Please could someone help me?
Thank you.

My code is like:
wavesurfer = Object.create(WaveSurfer);
timeline = Object.create(WaveSurfer.Timeline);
wavesurfer = WaveSurfer.create({
	audioContext: audioContext,
	container: '#wave2',
        waveColor: 'violet',
         progressColor: 'purple',
});

wavesurfer.setVolume(0);
			
wavesurfer.on('ready', function () {
	time=wavesurfer.getDuration();
	timeline.init({
				wavesurfer: wavesurfer,
				container: "#time-list"
	});
});

wavesurfer.on('mouseup', function (e) {
		do something;
});

**Comment by katspaugh** [comment]
There used to be this event, but it's not provided anymore.

If you need to listen to DOM events, listen directly on the container element.
In your case:
```
document.querySelector('#wave2').addEventListener('mouseup', function (e) {
    // do something
});
```
