### ISSUE TITLE
Microphone plugin on ios cordova

### ISSUE THREAD

**Issue by cankemik** [katspaugh/wavesurfer.js#628]
Is it possible to make microphone plugin on ios cordova ? I'm trying to  generate realtime waveform while recording audio.

when it try to trigger `microphone.start()` it get the error `Device error: Error: getUserMedia is not supported` . Are there any possible ways to make this work ?

**Comment by thijstriemstra** [comment]
There's no support for getUserMedia but you can try https://github.com/apache/cordova-plugin-media-capture and modify the microphone plugin a little.

**Comment by james-hoegerl** [comment]
Have you had any luck with this @cankemik ?

**Comment by thijstriemstra** [comment]
I don't think this will work for visualizing live recordings in realtime, only the full recording after you press stop. There doesn't seem to be a way to capture the live frames, only a success handler:

```javascript
navigator.device.capture.captureAudio(
    CaptureCB captureSuccess, CaptureErrorCB captureError,  [CaptureAudioOptions options]
);
```

**Comment by thijstriemstra** [comment]
#761 is related.

**Comment by thijstriemstra** [comment]
Can't fix anything here, cordova needs to add support (if it hasn't done already), closing.
