### ISSUE TITLE
WaveSurfer rendering in Internet Explorer

### ISSUE THREAD

**Issue by jsniff** [katspaugh/wavesurfer.js#629]
Hey Guys,

It seems that wavesurfer.js does not render in internet explorer correctly. Does anyone know a patch fix? If not, does anyone know a similar Audio Waveform Visualizer that can work in internet explorer? I was hoping not to have to code something from scratch. Any ideas/thoughts are appreciated.

Best,
Jacob

**Comment by katspaugh** [comment]
From the readme:
> wavesurfer.js works only in modern browsers supporting Web Audio.
> It will fallback to Audio Element in other browsers (without graphics). You can also try wavesurfer.swf which is a Flash-based fallback with graphics.

You can also decode your audio server-side and use the decoded data in pair with the Audio Element mode.

See an example here: https://github.com/katspaugh/wavesurfer.js/blob/master/example/audio-element/main.js#L26-L28

**Comment by jsniff** [comment]
Does any non-flash based solution exist? I want to make sure graphics work. I want the drag and drop functionality.

**Comment by thijstriemstra** [comment]
What version of internet explorer are you targeting?

**Comment by thijstriemstra** [comment]
@jsniff also see #576

**Comment by jsniff** [comment]
@thijstriemstra I'm targeting ie9 and up. I will try it. I'll believe it works when I see it. I want to make sure the graphic works to drag and drop and select audio regions.
