### ISSUE TITLE
Short MP3 files not playing. Any fixes?

### ISSUE THREAD

**Issue by a4jp-com** [katspaugh/wavesurfer.js#638]
I have a website where I'm making a free study program for people but none of the short MP3s play. Any ideas?

http://agreatdream.com/phrases/

**Comment by katspaugh** [comment]
大変ですね。見ましょう。

@X-Raym can you to take a look (it's the WordPress plugin)?

**Comment by a4jp-com** [comment]
Okay. That would be nice.

ありがとうございました。どうすればいいですか？

**Comment by a4jp-com** [comment]
Here are two sample files:

http://agreatdream.com/audio/hi-agreatdream-com-glen-charles-rowell.mp3

http://agreatdream.com/audio/good-morning---agreatdream-com---glen-charles-rowell.mp3

**Comment by X-Raym** [comment]
@katspaugh Ok, I'm on it !

@a4jp-com Can you please open a thread on the [WordPress support fourm page](https://wordpress.org/support/plugin/wavesurfer-wp) of the plugin ?

Your error seems to come from the WordPress integration, not from original WaveSurfer-js script.

**Comment by a4jp-com** [comment]
Okay. Thank you so much. I'll post the link here after too just for reference.

**Comment by a4jp-com** [comment]
https://wordpress.org/support/topic/i-have-a-page-where-the-short-mp3s-dont-work

Thank you so much for the super fast reply.

Do you live in Japan @katspaugh?

**Comment by katspaugh** [comment]
@X-Raym thank you! :thumbsup:

@a4jp-com nope. I've been learning Japanese for 2 years but haven't even been to Japan yet. :smile:

**Comment by a4jp-com** [comment]
If you need any help send me a message anytime ^^

I've been living in Japan for 14 years.

**Comment by X-Raym** [comment]
@a4jp-com , @katspaugh 
I think it is a wavesurfer or a file compatibility issue.

I tested http://agreatdream.com/quiz/audio/test4.mp3 with http://codepen.io/katspaugh/pen/GozaaG and it doesnt' work.

here the file properties :
```
MPEG layer 3, @ 48000 Hz 2 channels
Length: 0:02.784
Encoding: CBR (no header)
Bitrate (average): 129 kbps
117 frames in file [indexed]
```

**Comment by a4jp-com** [comment]
Oh no. That sounds bad. 
Is there anything I can do to help?
What settings are best for making MP3 files?

@X-Raym that file was the one that worked on the test page I made before but the other files had problems for me. 
If it's okay could you see if any of the other files work in that other program?

**Comment by a4jp-com** [comment]
I used Adobe Audition to record the files before.

**Comment by a4jp-com** [comment]
One of my students couldn't get any of the sounds to play on her Android phone (4.4.2) Sony SO-01F. The sounds that were working from before play on my phone though.

**Comment by a4jp-com** [comment]
The sample on http://codepen.io/katspaugh/pen/GozaaG didn't play on the Android phone either.

**Comment by X-Raym** [comment]
@a4jp-com compatibility of audio is mostly based on the browser. For eg, firefox cannot play 24 bit audio.
You have to check the compatibility of your file with your browser first.

**Comment by katspaugh** [comment]
@X-Raym is there an option in the WordPress plugin to use `backend: 'MediaElement'`? It may work better for more audio formats.

**Comment by a4jp-com** [comment]
http://developer.android.com/guide/appendix/media-formats.html

MP3	 	•	Mono/Stereo 8-320Kbps constant (CBR) or variable bit-rate (VBR)	MP3 (.mp3)

My file looks perfect and when I turn off wavesurfer the file plays through a black bar perfectly.

**Comment by X-Raym** [comment]
@katspaugh That's how the first version of the plugin worked, but I rewrite all the JS to make it work with web audio only becuase of this issue : https://github.com/katspaugh/wavesurfer.js/issues/592
I had other problems with using MediaElement (like sometimes the audio length was NaN, I know it is just me not knowing javascript enough, but it was a lot easier with WebAudio). So I don't plan to roll back.

@a4jp-com 
Yep, the black bar is the default WordPress media player. I created a default shortcode option to roll back to standard WordPress player (infos on plugin page).
But I wonder if the  problem doesn't came from your unsual bitrate (129kb/s instead of 128).
Try to encode your file with 128 cbr and reupload it in WordPress.
If this is not the problem, I'm afraid WaveSurfer-WP cannot satisfy your need at this time.

**Comment by katspaugh** [comment]
> So I don't plan to roll back.

Since the issue in #592 is fixed, maybe support MediaElement optionally? I'm not sure it will solve @a4jp-com's issue, though.

When you said
> I tested http://agreatdream.com/quiz/audio/test4.mp3 with http://codepen.io/katspaugh/pen/GozaaG and it doesnt' work.

It could also not work simply because it cannot load the file from that domain. The server should have CORS enabled for that to work.

**Comment by a4jp-com** [comment]
I'll try making some new files in Audition or another program if the Audition isn't any good. Is there anything you recommend for making MP3 files?  

@X-Raym if you download the file, do you have the same problem?

**Comment by X-Raym** [comment]
@a4jp-com I downloaded your file and uploaded it on a local wordpress install running wavesurfer and it works, so I think the problem came from your host server, like @katspaugh suggest. It is often teh case.
Check [this](https://wordpress.org/plugins/wavesurfer-wp/faq/).

@katspaugh Oh I didn't know it was fixed !
Just tested the MediaElement fallback and it seems more easy to implement that I thout it would be.
But maybe another time, as the problem doesn't come from that :)

**Comment by a4jp-com** [comment]
I use CloudFlare and I have purged the cache so everything should work in theory.

CloudFlare Support   Knowledge Base   CloudFlare's CDN (Content Delivery Network)  > Why can't I see my CORS headers?
Why can't I see my CORS headers?
Avatar	Simon October 02, 2014 17:49	
As covered in our article Does CloudFlare support Cross-origin resource sharing (CORS)? we offer support for CORS headers. Access-Control-Allow-Origin headers are often applied to cacheable content - font files, for example.

A web server will often respond with different Access-Control-* headers depending on the Origin header the browser sends in the request, and for that reason these requests are cached separately to each other.

If you have added or changed your CORS configuration on your web server, purging the CloudFlare cache by URL will not show you the latest headers. To force CloudFlare to retrieve the new version of the file, you can do one of two things:

1. Change the filename or URL - this will bypass the cache and CloudFlare will retrieve the latest headers immediately.

2. Purge everything and update the Last-Modified timestamp on your web server. Completing a full CDN purge will force CloudFlare to revalidate any items in its cache, but for this to get the new version of the file, you may need to update your server's last-modified time for the file. You can do this by running touch at the command line on the file  e.g. "touch yourfile.extension" or by re-uploading the file via your FTP client. 

Details on Purge Everything is here:

https://support.cloudflare.com/hc/en-us/articles/200169246-How-do-I-purge-my-cache-

A future version of our API will allow URL purging for the different CORS requests to make this process easier.

**Comment by a4jp-com** [comment]
http://www.webconfs.com/http-header-check.php

HTTP/1.1 200 OK => 
Date => Thu, 18 Feb 2016 03:15:57 GMT
Content-Type => text/html; charset=UTF-8
Connection => close
Set-Cookie => mc_session_ids[multi][4]=ba6a480ca734b5e1c9f7a57fcf3a8346597dbea1; expires=Thu, 18-Feb-2016 04:55:56 GMT; path=/
X-Powered-By => PHP/5.3.3
X-Pingback => http://agreatdream.com/xmlrpc.php
Link => ; rel="https://api.w.org/", ; rel=shortlink
Vary => Accept-Encoding
Cache-Control => max-age=0
Expires => Thu, 18 Feb 2016 03:15:56 GMT
Access-Control-Allow-Origin => *
Server => cloudflare-nginx
CF-RAY => 27669204fd670508-SEA

**Comment by a4jp-com** [comment]
I'm updating my .htaccess file with this

`Header add Access-Control-Allow-Origin "*"
Header add Access-Control-Allow-Headers "origin, x-requested-with, content-type"
Header add Access-Control-Allow-Methods "PUT, GET, POST, DELETE, OPTIONS"`

**Comment by a4jp-com** [comment]
I got a waveform to show up ^^

Here are the Adobe CS6 Audition settings if anyone else has the same problems:

MP3

Preset: 44.1 kHz, stereo, 16-bit (Adaptive Noise Shaping)
44100
Stereo
Bith Depth 16
Advanced > Dithering: Disabled

Constant
128Kbps

-------------------------

I just need to see if Android phones work now ^^

**Comment by a4jp-com** [comment]
Good news on the Android front. I went to an electronics shop and saw the files played on an Android phone. My student's phone was just a big dodgy. 

I can't figure out how to convert the files I have to working files though.

Maybe I have to record everything again...

**Comment by a4jp-com** [comment]
I found out the program can't recognize files by itself so when I changed src to mp3 the file loaded properly.

`[audio src="http://agreatdream.com/audio/good-morning-4.mp3"]`

↓

`[audio mp3="http://agreatdream.com/audio/good-morning-4.mp3"]`

**Comment by X-Raym** [comment]
@a4jp-com The two shortcodes produce a different results ? that's weird because...

https://github.com/X-Raym/wavesurfer-wp/blob/master/wavesurfer-wp.php#L374

As you can see there is already a way to make src tag compatible, and there is no need to determine source format from the shortcode all what is needed is the link.

I'll get back to you on wordpress forum, I guess @katspaugh can close this issue if this is the last problem you have.

**Comment by a4jp-com** [comment]
Okay. It's nice I found a way to play the files though ^^

**Comment by katspaugh** [comment]
@X-Raym thank you! I'm glad you guys figured it out.

**Comment by a4jp-com** [comment]
We still might need your help as the code doesn't recognize the extension for some reason when using scr.

**Comment by katspaugh** [comment]
It might be a combination of 2 reasons:

 * The server doesn't recognize the files as mp3s without the extension, and doesn't send the corresponding Content-Type HTTP header (`audio/mpeg`).
 * The browser doesn't recognize some of your files as mp3s without the HTTP header.

So I'd suggest configuring your server in such way that it always adds `Content-Type: audio/mpeg` in response to URLs matching some pattern (like `/mp3-files/*`), with or without the `mp3` extension.

**Comment by a4jp-com** [comment]
Thank you for the advice. @X-Raym also found the main mistake was a typo on my part. scr → src

**Comment by katspaugh** [comment]
Oh :)

**Comment by a4jp-com** [comment]
^^
