### ISSUE TITLE
Delay between audio and cursor

### ISSUE THREAD

**Issue by RamyElkest** [katspaugh/wavesurfer.js#639]
I currently have a nasty ~500ms delay between the audio and the cursor. (Cursor is ahead of the audio). I get same effect on the demo page.

Is it just me? If not, is there any way around it?

**Comment by katspaugh** [comment]
Might be related to #633.

**Comment by katspaugh** [comment]
Please check if you have the same with the latest version, 1.1.2. Closing for now.

**Comment by RamyElkest** [comment]
Will do, thanks
