### ISSUE TITLE
how to delete waves and their respective audio file from cache?

### ISSUE THREAD

**Issue by wolfbiter** [katspaugh/wavesurfer.js#64]
having problems with this in this issue: https://github.com/wolfbiter/linx/issues/133

in my case, each audio file is loaded into a new WaveSurfer object. however, even with deleting all references to that object, the audio stays cached => my page totally fills the cache, which is bad.

i tested the single WaveSurfer object case using wavesurfer.fm, and this problem doesn't exist: loading a new audio file removes the old one from the cache (i confirmed this by watching the task manager in chrome)

@katspaugh: any ideas?

**edit**: note that i also tried wave.empty(), and that didn't clear the audio from the cache (it totally should, shouldn't it? logically speaking)

**Comment by MrXiaoHui** [comment]
@katspaugh @wolfbiter  Have you solved this memory usage problem?

**Comment by chigozieorunta** [comment]
@katspaugh Please I would love to know if the memory usage problem has been resolved. I'm having a bit of a challenge with this as my angularjs app keeps crashing every time I try to reload a new audio. What do I do?
