### ISSUE TITLE
trying to use flexbox breaks player

### ISSUE THREAD

**Issue by omerts** [katspaugh/wavesurfer.js#642]
Without using flexbox everything works fine. Whenever I wrap the player with a horizontal flexbox the wave just disappears.

**Comment by katspaugh** [comment]
Any idea why? Can you submit a PR?

**Comment by omerts** [comment]
Under investigation will update once I have any updates.

**Comment by omerts** [comment]
By the way, I am using react-wavesurfer. Wrapping the player in a div with width: 100%, solved the problem for me.

**Comment by katspaugh** [comment]
OK! :thumbsup:
