### ISSUE TITLE
zoom but don't scroll while playing

### ISSUE THREAD

**Issue by chrisvaughn** [katspaugh/wavesurfer.js#649]
Thanks for taking the time read this.  The library is fantastic.

For my application I use the regions plugin for the purpose of highlighting a section of the wave. I want to show the region centered and play the region without scrolling. In order to achieve this it feels like I'm fighting the library a bit. I have to turn on scrollParent: true when I initialize (so the wave doesn't overrun the container) but right before I play I have to `wavesurfer.params.scrollParent = false;` instead of using toggleScroll() because toggleScroll redraws the wave. Below are what I believe are the relevant sections of code for what I've describing here.  This code accomplishes what I'm wanting when using the WebAudio backend.  

A few questions:
1. Is there a better way to accomplish this? I feel like I might be missing something obvious.
2. since I never really want scrolling should I be able to do this without ever turning scrollParent on?
3. This same code doesn't work if I set the backend to 'MediaElement'.  I'm attempting to use MediaElement to get around the memory issues with some browsers and WebAudio like #77.  When using the MediaElement backend the region is not visible on the screen. I found that when I comment out the `wavesurfer.params.scrollParent = false;` line the region is centered as expect but this means that it scrolls during playback.  Any advice or direction on where to head with getting my code to do what I want and have it work with both backends? 

``` javascript
var options = {
  container: element,
  pixelRatio: 1,
  fillParent: false,
  normalize: true,
  scrollParent: true,
  hideScrollbar: true
}

var wavesurfer = WaveSurfer.create(options);

wavesurfer.on('ready', function () {
  start = 4.621;
  end = 8.243;

  // figure out how many pixels per second to show to fit whole region on screen
  var audioLength = (end - start) + 5;
  var pixPerSecond = $element.width() / audioLength;

  // figure out where the center of the region will be
  var centerOfRegion = (start + (end - start)/2)/wavesurfer.getDuration();

  // show the proper amount of the wave and scroll to it
  wavesurfer.zoom(pixPerSecond);
  wavesurfer.seekAndCenter(centerOfRegion);

  //add a region
  var region = wavesurfer.addRegion({
    'start':start,
    'end':end,
    'data':{},
    'color':'rgba(167,210,229,0.3)'
  });

  // we don't want to scroll while playing so disable
  // using toggleScroll redraws the wave and messes up centering
  wavesurfer.params.scrollParent = false;
  region.play();
}
```

**Comment by katspaugh** [comment]
Try adding `hideScrollbar: true` to your options. Here's a demo: http://codepen.io/katspaugh/pen/PZrBeE

**Comment by chrisvaughn** [comment]
Thanks for the reply.  I do have ```hideScrollbar: true``` set in my options.  The problem I'm trying to solve isn't in the demo.  Imagine if the you took the zoom part (that's in the demo) but when you pressed the play the wave form didn't scroll.  I know this doesn't make sense to do in all cases but in my case I'm zooming so that all the audio I want played is shown and there for scrolling isn't necessary.

**Comment by thijstriemstra** [comment]
Closing.
