### ISSUE TITLE
broken link in readme

### ISSUE THREAD

**Issue by thijstriemstra** [katspaugh/wavesurfer.js#650]
there's a link to https://github.com/katspaugh/wavesurfer.js/blob/master/example/main.js in the readme but the examples are gone. Why are they removed and where do they live now?

**Comment by katspaugh** [comment]
They are now in the gh-pages branch. I think I'll create a demo page in the master branch as well. I want to have just one HTML with a [dat.gui](http://workshop.chromeexperiments.com/examples/gui/#1--Basic-Usage) interface to toggle different option combinations.
