### ISSUE TITLE
angular example and regions

### ISSUE THREAD

**Issue by tenchugecko** [katspaugh/wavesurfer.js#658]
i loaded wavesurfer, regions plugin, timelineplugin, then the angular directive from the example

 control.surfer.on('ready', function () {
               console.log('adding region');
            control.surfer.addRegion(control.regions.region);
}

Results in
control.surfer.addRegion is not a function

how do i hadd the regions plugin to the angular directive?

**Comment by katspaugh** [comment]
It shouldn't be different from the regular JavaScript usage: http://wavesurfer-js.org/plugins/regions.html

When you add the script to your HTML, it makes `addRegion` available:
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/wavesurfer.js/1.0.57/wavesurfer.min.js"></script>
```

**Comment by tenchugecko** [comment]
1.0.57 doesnt change a thing. i need to try an example .

**Comment by tenchugecko** [comment]
index.html had multiple entries for wavesurfer ... grrrrrrrrrrrrrrrrrrrr

but now i'm almost connected into the mean stack :)
