### ISSUE TITLE
audio waveform does not create on iPhone (ios 5) 

### ISSUE THREAD

**Issue by sanketnaphade** [katspaugh/wavesurfer.js#66]
Hello,
         I am using wavesurfer in my app .it worked properly on ios 6 and 7 bt it won't works on ios 5. i thnk it's because of html 5 but not confirmed. So will you please help me what to do.

**Comment by Prity1208** [comment]
Hi,
Audio waveform is not creating on opera web browser and mac OS. Can you please help me out?

**Comment by katspaugh** [comment]
@Prity1208 if it works in Chrome but not in Opera, it's an Opera bug. Ask their support please.

**Comment by Prity1208** [comment]
Hi Katspaugh,

Thanks for help. I am facing one another problem, I am using iPhone version 6.1.4(10B350), I cant see the waveform and also unable to play audio. Can you give a solution for this?

Thanks,
Prity

**Comment by Prity1208** [comment]
Hi Katspaugh,
I am still waiting for your reply. Can you please help me in resolving my issue?
Thanks,
Prity

**Comment by katspaugh** [comment]
Hi Prity,

I've just checked http://wavesufer.fm, and it works on iPhone 6.

**Comment by Prity1208** [comment]
I am using iPhone 5  with iOS 6.1.4(10B350). And here is the url of my website:
http://www.onlinechurch.tk/media_details/ZE10Nk5qOTJyT1hHcjVoMVR4bE4wZz09LS1xZld4ZUhER1UzVnJQSDBwREdaVlZnPT0=--cfa647804c78b2b55182b26388595acf1c2f8858

**Comment by katspaugh** [comment]
I don't know. Try updating you iOS.
