### ISSUE TITLE
What draw this lines?(photo attached)

### ISSUE THREAD

**Issue by AndrewsK30** [katspaugh/wavesurfer.js#664]
I am try to mimic the souncloud player, and i wanna know what draw this lines in the script?

![sem titulo](https://cloud.githubusercontent.com/assets/13906420/13419434/f4796400-df5c-11e5-9775-0efa890b55d7.png)

**Comment by katspaugh** [comment]
You can use linear gradient for the waveform color like this:

```javascript
var ctx = document.createElement('canvas').getContext('2d');
var linGrad = ctx.createLinearGradient(0, 64, 0, 200);
linGrad.addColorStop(0.5, 'rgba(116, 116, 116, 1.000)');
linGrad.addColorStop(0.5, 'rgba(183, 183, 183, 1.000)');

var wavesurfer = WaveSurfer.create({
  container: '#waveform',
  waveColor: linGrad,
  barWidth: 3
});
```
See demo: http://codepen.io/katspaugh/pen/WwbMYe?editors=1010

**Comment by AndrewsK30** [comment]
Sorry for my question was not clear, the png attached is what i have(i changed  the script) to 
decrease at the bottom and erase the mid of all bars, but my qustion is what are these lines marked in the picture?(What location of the script.)

**Comment by AndrewsK30** [comment]
Ok this problem with chrome zoom.

**Comment by katspaugh** [comment]
So closing this?

**Comment by AndrewsK30** [comment]
yes can close, for who whants mmic the souncloud style change this on script:`drawBars: function (peaks, channelIndex) {
        // Split channels
        if (peaks[0] instanceof Array) {
            var channels = peaks;
            if (this.params.splitChannels) {
                this.setHeight(channels.length * this.params.height * this.params.pixelRatio);
                channels.forEach(this.drawBars, this);
                return;
            } else {
                peaks = channels[0];
            }
        }

        // Bar wave draws the bottom only as a reflection of the top,
        // so we don't need negative values
        var hasMinVals = [].some.call(peaks, function (val) { return val < 0; });
        if (hasMinVals) {
            peaks = [].filter.call(peaks, function (_, index) { return index % 2 == 0; });
        }

        // A half-pixel offset makes lines crisp
        var $ = 0.5 / this.params.pixelRatio;
        var width = this.width;
        var height = this.params.height * this.params.pixelRatio;
        var offsetY = height * channelIndex || 0;
        var halfH = height / 2;
        var length = peaks.length;
        var bar = this.params.barWidth * this.params.pixelRatio;
        var gap = Math.max(this.params.pixelRatio, ~~(bar / 2));
        var step = bar + gap;

        var absmax = 1;
        if (this.params.normalize) {
            absmax = Math.max.apply(Math, peaks);
        }

        var scale = length / width;

        this.waveCc.fillStyle = this.params.waveColor;
        if (this.progressCc) {
            this.progressCc.fillStyle = this.params.progressColor;
        }

        [ this.waveCc, this.progressCc ].forEach(function (cc) {
            if (!cc) { return; }

            for (var i = 0; i < width; i += step) {
                var h = Math.round(peaks[Math.floor(i * scale)] / absmax * halfH);
                cc.fillRect(i + $, halfH - h + offsetY, bar + $, h * 2);
            }
        }, this);
    },`

**Comment by katspaugh** [comment]
Nice, thanks! I'll probably document this on the website.

**Comment by chrisparton1991** [comment]
This is still open @katspaugh, seems like it can be closed?

**Comment by katspaugh** [comment]
Yep, thanks!
