### ISSUE TITLE
Toggle between mic visualization and recorder waveform

### ISSUE THREAD

**Issue by daversm** [katspaugh/wavesurfer.js#665]
Is there a way to toggle between mic visualization( via microphone plugin) and showing the loaded audio waveform, using the same wavesurfer object. Currently I am having to create and destroy wavesurfer objects, when I am showing mic visualization and then want to show a loaded audio's waveform.

**Comment by daversm** [comment]
please?

**Comment by thijstriemstra** [comment]
@daversm maybe the https://github.com/collab-project/videojs-wavesurfer project has some clues

**Comment by thijstriemstra** [comment]
@daversm can you show the code you're using now? Perhaps something in wavesurfer.js can be refactored to make things easier for you.

**Comment by daversm** [comment]
Hi, 

Been some time since I looked at my code, so unfortunately I'm not even sure what I was doing myself.

But basically I wanted to be able to show a loaded waveform in a wavesurfer object, and in the same object have an option to start showing a live mic visulatization, switch between loaded audio and mic visulatation. 


 this.microphone.destroy();
 this.wavesurfer.empty();
 this.wavesurfer.destroy();
 this.wavesurfer = Object.create(WaveSurfer);
 this.wavesurfer.init({
          container     : "#" + outerThis.props.trackName,
          waveColor     : "#848383",
          interact      : false,
          cursorWidth   : 0,
          height        : 170
        });
        this.microphone = Object.create(WaveSurfer.Microphone);
        this.microphone.init({
            wavesurfer: this.wavesurfer
        });
        this.microphone.gotStream(mediaStream);
        this.currentlyRecording = true;
        this.microphone.play();

**Comment by katspaugh** [comment]
Added Pentatonic to https://wavesurfer-js.org/projects/.
