### ISSUE TITLE
How to create two players and sync ?

### ISSUE THREAD

**Issue by AndrewsK30** [katspaugh/wavesurfer.js#667]
Like souncloud one is in the page with waveform and one is in the bottom and its linear and sync both?(easy way)
![sem tit22ulo](https://cloud.githubusercontent.com/assets/13906420/13503291/6e2354e0-e14d-11e5-8ad5-273d2dc1fe13.png)

**Comment by thijstriemstra** [comment]
You can use the wavesurfer methods to control the wavesurfer player on the top from the UI above. I think there's not much we can help you with here.

**Comment by AndrewsK30** [comment]
Yea i have to do this can close
