### ISSUE TITLE
How to load only waveform and wait to user click 'play' to download the audio?

### ISSUE THREAD

**Issue by AndrewsK30** [katspaugh/wavesurfer.js#668]
i am already using a array format to display the waveform first in `.load(audio_url,[array of floats])`, but in the page has a lot instances to diferent audio files and this slow the page because has to download a lot of audio files.So how can i load the the canvas with the waveform and when i press play to certain wavesurfer instance then download the audio file?

**Comment by katspaugh** [comment]
There's no such a built in way to do it. You could add a new method that takes just the array and draws the waveform.

**Comment by AndrewsK30** [comment]
ok

**Comment by drhouse7** [comment]
I have the same issue, any news about this?

**Comment by drhouse7** [comment]
Sorry @katspaugh but is there any working demo of this here around? Could you please give me a little hand on make it works, because otherwise I cannot use at all this tool.
I need to load mp3 file only after hit play (I don't understand why all others say nothing about this :S)

**Comment by drhouse7** [comment]
I've opened a question here http://stackoverflow.com/questions/38918909/how-can-i-load-only-waveform-and-wait-to-user-click-play-to-download-the-audio Really appreciate if someone could help me!

**Comment by katspaugh** [comment]
@drhouse7 I see you are using `MediaElement`. Maybe try passing an audio element you create yourself in HTML with `preload="false"`, like this:
```
<audio id="song" style="display: none" preload="false" src="'http://api.soundcloud.com/tracks/45398925..."></audio>
```

And then pass this audio element instead of the URL:
```
wavesurfer.load(document.querySelector('#song'), [ 0.0218, 0.0183, 0.0165, 0.0198, 0.2137, ... ]);
```

Also try experimenting with setting the `src` of the audio element *after* the user presses play. It might or might not work, I haven't checked.

**Comment by drhouse7** [comment]
Thanks for reply, 
I tried it here http://codepen.io/dreammy/pen/QEYjYW but it's not working (it doesn't draw the waveform)

I thought this 
> Also try experimenting with setting the src of the audio element after the user presses play
was generating an error on init.
I'll try onclick function.

**Comment by drhouse7** [comment]
@katspaugh well I think I should edit the `wavesurfer.js`, big problem since I'm not very good in JS.
Any help is really appreciate, thanks :)

**Comment by drhouse7** [comment]
@katspaugh I play with draw_buffer but I'm not able to make it works. Also did you see my code on codepen? is it that what you suggested before?

**Comment by katspaugh** [comment]
In your codepen you had tripple quotes around the audio src. I've fixed it for you: http://codepen.io/katspaugh/pen/oLmwoZ

**Comment by drhouse7** [comment]
I'm speechless and really greatful, tomorrow I'll test it!

**Comment by drhouse7** [comment]
@katspaugh I tried your eg. but it download the mp3 again on load.

**Comment by drhouse7** [comment]
@katspaugh bad luck, here is my new [try](http://codepen.io/dreammy/pen/dXaRwd), but it draws the waveform only after clicked on play

**Comment by daslicht** [comment]
Anyone ever found a solution for this please?
