### ISSUE TITLE
getDuration method returns 0

### ISSUE THREAD

**Issue by LuigiFrattolillo** [katspaugh/wavesurfer.js#669]
Hi, I can't retrieve the duration at all typing:

wavesurfer.getDuration();

All other methods work correctly instead.

any idea?

**Comment by katspaugh** [comment]
It may be caused by bad/missing headers in the audio file.

**Comment by thijstriemstra** [comment]
Related to #505?

**Comment by chrisparton1991** [comment]
This can occur if you're attempting to retrieve the duration before wavesurfer fires its `ready` event. See codepen: http://codepen.io/chrisparton1991/pen/EKpNxq.
