### ISSUE TITLE
Height of bars

### ISSUE THREAD

**Issue by brnck** [katspaugh/wavesurfer.js#671]
![screenshot_2](https://cloud.githubusercontent.com/assets/14329469/13598383/29a56290-e526-11e5-8150-af25e41350c0.png)

Hi.

As you can see from the screenshot I need to get height of every bar in soundwave. Also I need to remove spaces between bars. 

All peaks could be returned in an array

Any help would be aprreciated since I can't find a solution by myself

**Comment by katspaugh** [comment]
To get the peaks array: `wavesurfer.backend.getPeaks(2000)` (the number is the length of the array).

To remove the space: no built-in option, but you can modify this method: https://github.com/katspaugh/wavesurfer.js/blob/master/src/drawer.canvas.js#L96

**Comment by brnck** [comment]
Thanks for a quick answer but it seems that the problem still persists. 

I solved spaces problem but I still can't get peaks array. 

http://prntscr.com/acn8rd

http://prnt.sc/acn8cg

**Comment by katspaugh** [comment]
You can only call `getPeaks` when the audio is loaded. It's loaded asynchronously.

```javascript
wavesurfer.on('ready', function () {
    // the width of the waveform in double pixels
    var width = wavesurfer.getDuration() * wavesurfer.params.minPxPerSec * wavesurfer.params.pixelRatio;
    wavesurfer.backend.getPeaks(width);
});
```

**Comment by brnck** [comment]
Thanks. Works perfectly!
