### ISSUE TITLE
Regarding issue #458: Zoom-In Maximum

### ISSUE THREAD

**Issue by ErikOmberg** [katspaugh/wavesurfer.js#672]
This question is closely related to issue #458.

Is there a calculation that can be done to figure out how far in zoom should work before exceeding the canvas limits? 

If yes, then I could set my slider max accordingly, right? 
I'm not sure how to attack this problem, so any direction would be helpful. 

In Chrome, I noticed that the waveform fails to render when peaks.length is 72840, and it succeeds in rendering when peaks.length is 60000. That seems like a lead, but it also seems wasteful to calculate peaks for several zoom levels as soon as the file is loaded. Any alternate suggestions are welcome. Thank you.

**Comment by ErikOmberg** [comment]
Would an alternate solution be to only render the part of the waveform showing along the horizontal scroll? Would that be too slow for playback as it scrolls?

**Comment by katspaugh** [comment]
The limitation is imposed on the Canvas size in pixels. The limit differs across the browsers. Here's a list from 2012: http://stackoverflow.com/a/11585939/352796

Thus, to calculate the maximum zoom you would multiply `wavesurfer.getDuration() * wavesurfer.params.minPxPerSec * wavesurfer.params.pixelRatio` (width of the waveform) and `wavesurfer.params.height * wavesurfer.params.pixelRatio` (height of the waveform), where `wavesurfer.params.minPxPerSec` is the zoom level.

> Would an alternate solution be to only render the part of the waveform showing along the horizontal scroll?
Yes, that would be the solution. [Peaks.js](https://github.com/bbcrd/peaks.js), for instance, does that.

**Comment by ErikOmberg** [comment]
Thank you for your response. It has been very helpful.
