### ISSUE TITLE
How to put wavesurfer objects into array?

### ISSUE THREAD

**Issue by Artimal** [katspaugh/wavesurfer.js#673]
I don't know how to solve problem of many players on one site. I am tryingi to use arrays but I get only undefined errors. Can you help me please? Let's look at this:
A) When I am using standard for one song:
```
wavesurfer = WaveSurfer.create({
  container: waveform1,
  waveColor: '#5C6366',
  progressColor: 'white',
  height: 100,
  normalize: 1
});
wavesurfer.load("audio/before1.mp3");
```
B) But if I put waveform1 variable and array "container is not found":
```
var wavesurfer = [];
wavesurfer[i*2] = WaveSurfer.create({
  container: waveform1,
  waveColor: '#5C6366',
  progressColor: 'white',
  height: 100,
  normalize: 1
});
wavesurfer[i*2].load("audio/before" + song + ".mp3");
```

Of course I have divs with id like waveform1. "i" is from for of my bigger code.

**Comment by katspaugh** [comment]
Try StackOverflow.
