### ISSUE TITLE
Timeline Final Value Cutoff

### ISSUE THREAD

**Issue by ErikOmberg** [katspaugh/wavesurfer.js#675]
I'm using the timeline plugin and the final time marker value is cutoff. This happens for both zoom-in and full-zoom-out.

Is there some css padding I should apply, or is there another route to solving this?
Thank you.

Here's a screenshot:

![image](https://cloud.githubusercontent.com/assets/8632110/13823272/da6fd820-eb76-11e5-8ff9-105dab35aadf.png)

**Comment by katspaugh** [comment]
The time labels are drawn on Canvas. Check out this code: https://github.com/katspaugh/wavesurfer.js/blob/master/plugin/wavesurfer.timeline.js#L171-L191

We could add a special case for the last label so that it's drawn with an offset to the left.

**Comment by ErikOmberg** [comment]
Thank you for the spot in the code. I feel a left offset might look strange, so I put a condition around the filltext parts. I used 33 px less than width as the cutoff. I'm sure there's a better dynamic way to do it, but this seems to work for me.

The good part of this solution is that is is dynamic as I zoom in as shown by the screenshots below.

`
if(curPixel + 33 < width) 
`

![image](https://cloud.githubusercontent.com/assets/8632110/13828665/a14a9458-eb90-11e5-9988-c9b5628a3eca.png)
