### ISSUE TITLE
Waveforms only visible on Chrome (mac)

### ISSUE THREAD

**Issue by Henry-Cullen** [katspaugh/wavesurfer.js#690]
Hi

I'm using the WP plug in of wavesurfer written by X-raym
https://github.com/X-Raym/wavesurfer-wp

He has confirmed that he can reproduce my issue which is that waveforms only render in chrome, not Firefox or Safari (Mac)

I am using AWS S3 to serve the files and have adjusted the CORS permissions file to allow the XML request to process the waveform, the waveform ARE obviously being processed.

The audio files are standard MP3s at 128Khz and are roughly 2min long
The audio plays back fine with or without waveform, just the waveform does not appear in Firefox or Safari

You can see the issue here : http://drummer-dev.davethedrummer.co.uk/downloads/hydraulix-06
I have tried using the backend var MediaElement
If I try using var WebAudio I get nothing loading at all.

Does anyone have any knowledge of this bug? I didn't see a post about it.

many thanks

**Comment by thijstriemstra** [comment]
> He has confirmed that he can reproduce my issue which is that waveforms only render in chrome, not Firefox or Safari (Mac)
Any ticket reference for that?

**Comment by Henry-Cullen** [comment]
Not as such, just the conversation between myself and the author on the plug in support page
https://wordpress.org/support/topic/waveform-only-generating-in-chrome-mac
I

**Comment by katspaugh** [comment]
I've debugged your page in Safari, and it appears Web Audio cannot decode your files in this browser. Maybe some optional mp3 headers are missing, or it doesn't like the bitrate or something like that.

I suggest you to try different encoding options. Closing this issue. If you find a working solution, please share with us.
