### ISSUE TITLE
Canvas is blank if canvas.width>32767

### ISSUE THREAD

**Issue by whenov** [katspaugh/wavesurfer.js#692]
Chrome and Firefox have a canvas size limit, check [this link](http://stackoverflow.com/questions/6081483/maximum-size-of-a-canvas-element) for detail.

**Comment by chrisparton1991** [comment]
I recently implemented the `MultiCanvas` renderer. See #679. To activate, use the `renderer: 'MultiCanvas'` property. It works by tiling multiple canvases horizontally. 

The default canvas width is 4000px (to support older browsers like IE mobile), but you could raise this to something like `32750` if you only care about the latest browsers. I recommend leaving using a number less than 32767 as a small overlap is added to each canvas to ensure a smooth transition between canvases.

This renderer is available as of version 1.1.0.

**Comment by whenov** [comment]
@chrisparton1991 Good job! I'll try it, thanks!

**Comment by chrisparton1991** [comment]
Cool, let me know how you go @whenov :)
