### ISSUE TITLE
Wavesurfer project: Aikuma-NG

### ISSUE THREAD

**Issue by Lingomat** [katspaugh/wavesurfer.js#694]
I'd thought I'd let you know about our project that uses Wavesurfer. An ofline Chrome App called Aikuma-ng which is aimed at annotating speech an producing video captions and what have you. It's been developed as a part of a research initiative into helping endangered language speakers to record and document their own language. More details and screenshots on Chrome Web store:

https://chrome.google.com/webstore/detail/aikuma-ng/mkcflkabncgflgkbagmafecnligbfkfg

And the Github repo:
https://github.com/aikuma/aikuma-ng

Free of course.

**Comment by katspaugh** [comment]
Awesome, thank you very much!

**Comment by katspaugh** [comment]
Added in 681235d0ed18c02a44f9b017f365dc809217f44b (see http://wavesurfer-js.org/projects/).
