### ISSUE TITLE
Multi canvas approach for timeline plugin?

### ISSUE THREAD

**Issue by chinshr** [katspaugh/wavesurfer.js#696]
On longer waveforms with timelines it can happen that the timeline is not rendered due to limitations on the canvas size. It would be great to get some of the excellent multi-canvas magic by @chrisparton1991 to work in the timeline plugin. 

BTW I integrated MultiCanvas into the minimap plugin and it works well, of course it is less prone to run out of "canvas space". But if anyone is interested, I can share my code in a PR?

**Comment by katspaugh** [comment]
Sure, a PR is always appreciated!

**Comment by chrisparton1991** [comment]
I'll take a look at this at some point, but it may be a while before I can get around to it due to other commitments.

**Comment by chrisparton1991** [comment]
I've taken a look at the code for the timeline plugin. I think it'll be easier to convert it over to MultiCanvas than the main renderer was.

The only potentially tricky bit is the text that's rendered. I've done some tests and it looks like rendering text partially past the right end of a canvas, or using negative coordinates to render partially before the left end of a canvas works fine, so it shouldn't be a huge issue to render text that falls between two canvases.

**Comment by chinshr** [comment]
Oh, that sounds great. It would take me forever to figur this out. I can help test and code review if you like?

**Comment by chrisparton1991** [comment]
Sure, that would be great when I get around to it @chinshr.

I think you'd be able to implement the MultiCanvas renderer too, I'm definitely no mathematical genius or anything. I had to discard my first attempt because it was garbage, but the second attempt went a lot more smoothly because of it.

I just hope nobody asks for some kind of MultiCanvas thing that requires drawing lines more complex than the current waveforms, I'd be lost on how to implement that!

**Comment by chinshr** [comment]
Ok, will take a look at it. Thanks.

**Comment by chrisparton1991** [comment]
Sure thing @chinshr. I'm happy to review and test your code. I'm also happy to have a go at implementing it if the need arises.

**Comment by chinshr** [comment]
You mentioned that you had looked at how to implement drawing labels. If there is any approach worth posting here, I would pick it up. Thanks.

**Comment by chrisparton1991** [comment]
Hey @chinshr, I just wrote a Codepen (http://codepen.io/chrisparton1991/pen/bpKoqm) that shows how to render text across canvases. I've added comments to (hopefully) make the code clearer. Let me know if it makes sense and if you still want to have a go at implementing this feature.

**Comment by chinshr** [comment]
Thanks for sharing. The text renders well on mobile safari. I will try to have a look and implement this, stay tuned.

**Comment by jeremylach** [comment]
Any update on the multicanvas plugin for the wavesurfer timeline?  Definitely could use this.

**Comment by chinshr** [comment]
Sorry, did not have time to implement, yet.

**Comment by chrisparton1991** [comment]
Hey @jeremylach, I'll try and have a look at that sometime in the next week. Can't make any promises, but hopefully It won't be too tricky to implement. If I get time to take a look, I'll keep you posted.
