### ISSUE TITLE
customFilter (pass node to wavesurfer)

### ISSUE THREAD

**Issue by floydback** [katspaugh/wavesurfer.js#697]
I want to add pitch-shifter. I find out https://github.com/also/soundtouch-js and try to merge wavesurfer and soundtouch.

I need help. 
soundtouch work like this:

> st = new soundtouch.SoundTouch(sampleRate);
> filter = new soundtouch.SimpleFilter(new soundtouch.WebAudioBufferSource(source), st);
> node = soundtouch.getWebAudioNode(context, filter);
> node.connect(context.destination)

How integrate this code into wavesurfer? 

As I understand I need to add to wavesurfer new scriptNode with onaudioprocess function with soundtouch code above.

How do this? Where put this code? webaudio.js or wavesurfer.js?

**Comment by katspaugh** [comment]
Use `setFilter` to add your pitch-shift filter into the wavesurfer.js' graph:
```
wavesurfer.backend.setFilter(filter);
```

**Comment by floydback** [comment]
Yes, it's work like you say, for example, with [soundbank-pitch-shift](https://github.com/mmckegg/soundbank-pitch-shift) I think the problem is in [soundtouch-js](https://github.com/also/soundtouch-js). I can't use it like filter with wavesurfer. Unfortunately soundtouch has the best sound, other ones sounds much worse ;(

**Comment by katspaugh** [comment]
It appears, `setFilters` was broken since April 2 (see #724). Please try again with the latest version (1.1.2).
