### ISSUE TITLE
bower "main" field cannot contain minified files

### ISSUE THREAD

**Issue by thijstriemstra** [katspaugh/wavesurfer.js#699]
Seeing this error:

```
bower wavesurfer.js#>=1.0.57         invalid-meta The "main" field cannot contain minified files
bower wavesurfer.js#>=1.0.57             resolved https://github.com/katspaugh/wavesurfer.js.git#1.1.1
```

**Comment by chrisparton1991** [comment]
I'm only a fledgling Bower user myself, but I suspect best practice is to provide non-minified versions as output to Bower, which gives consumers the option of minifying themselves using a Grunt/Gulp task etc.

I think the fix here is, as suggested by the error, to not minify/uglify the file in Grunt (although it may be possible to trick bower by not naming the file `.min.js`).

Thoughts, @katspaugh?

**Comment by katspaugh** [comment]
Yes, I guess we need to add a new, not minified, file in the distribution.

**Comment by Lingomat** [comment]
Yep, Aikuma's gulp file builds wavesurfer.js and has overridea in the bower package. Bit ugly, but no huge deal.

**Comment by katspaugh** [comment]
I've added the uniminified file to the build and updated the version.
