### ISSUE TITLE
only render a segment of the waveform

### ISSUE THREAD

**Issue by therewasaguy** [katspaugh/wavesurfer.js#700]
I'd like "to only render the part of the waveform showing along the horizontal scroll" as described by @ErikOmberg and @katspaugh in #672. I'm wondering if anyone has any insight for how to make it possible with wavesurfer?

I am working with long audio files (using MediaElement and pre-analyzed waveform .json). I don't need to show the entire file, I'm only trying to zoom in very close on one segment at a time. As I zoom, the main canvas exceeds the max number of pixels (as mentioned before https://github.com/katspaugh/wavesurfer.js/issues/458 https://github.com/katspaugh/wavesurfer.js/issues/692).

I can keep zooming with MultiCanvas (thanks for your work on this, @chrisparton1991). But I only need to show the zoomed in segment, and MultiCanvas is using up resources to draw canvases that aren't visible. 

Would it make sense to adapt MultiCanvas, and tell it not to create/draw the extra canvases if `scrollParent` is false? Or does this call for a custom renderer, like SegmentRenderer? Is anybody else interested/working on this?

**Comment by katspaugh** [comment]
I like the approach that [peaks.js](https://github.com/bbcrd/peaks.js) has taken: they use only one canvas to render the currently visible segment. They redraw the canvas as the track is being navigated.

**Comment by therewasaguy** [comment]
I've made some progress in [this branch](https://github.com/therewasaguy/wavesurfer.js/tree/drawer-segment)

For now, the drawer is called `drawer.segment`.

It depends on two new variables: `segmentStart` and `segmentDuration`. Using those, and the total duration, we can re-map the [`progress`](https://github.com/therewasaguy/wavesurfer.js/commit/2aed3942f85561e78e1c93d68ee262db4ac8fd76#diff-a0b88b7610fd427ae516cc0625bd5ac9R280) method and [`handleEvent`](https://github.com/therewasaguy/wavesurfer.js/commit/2aed3942f85561e78e1c93d68ee262db4ac8fd76#diff-a0b88b7610fd427ae516cc0625bd5ac9R69) (click event handler)

Next I'm thinking about:
- how to handle the variables in the API since they only apply to this drawer. Should they stay in the drawer or move to wavesurfer? Should segmentDuration be based on / tied to zoom? 
- the other drawers depend on scrollLeft to determine position, so I think this one will need a new way to handle navigation / scroll events, recenter and centerOnPosition methods
- how this can integrate with plugins, like the regions plugin

**Comment by mspae** [comment]
@therewasaguy Check the partialRender parameter.

**Comment by rockyhuber** [comment]
@therewasaguy hey mate, how did you go with this? Any updates?

**Comment by entonbiba** [comment]
@rockyhuber see this about rendering custom peaks https://github.com/katspaugh/wavesurfer.js/issues/2058#issuecomment-761284236
