### ISSUE TITLE
Unable to decode audio data with .ogg

### ISSUE THREAD

**Issue by WiS3** [katspaugh/wavesurfer.js#703]
This is the error i get in the console while trying to load an ogg/opus audio file.

`undefined:1 Uncaught (in promise) DOMException: Unable to decode audio data`

The default Chrome Audio element play the file fine.

**Comment by katspaugh** [comment]
It's a bug in Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=409402

**Comment by bkentdev** [comment]
Is there a workaround for this issue?
