### ISSUE TITLE
Soundmanager

### ISSUE THREAD

**Issue by Filoz** [katspaugh/wavesurfer.js#704]
Hi, 
your library looks fantastic!
is it possible to combine wavesurfer with soundmanager (http://www.schillmania.com/projects/soundmanager2/ )?

**Comment by christophwolff** [comment]
+1

**Comment by katspaugh** [comment]
I haven't tried, but I think it should be possible. You need to take the same audio element that Soundmanager is playing and pass it to wavesurfer.js, like here: https://github.com/katspaugh/wavesurfer.js/blob/master/example/video-element/main.js#L17-L19

**Comment by joshuaiz** [comment]
I'm trying to do this too and I got the waveform to generate using Bar UI and some simple jQuery:

    $('.sm2-playlist-bd li a').on('click', function() {
    	var tURL = $(this).attr('href');
    	wavesurfer.load(tURL);
    });

This generates the waveform but I'm having no luck binding seek changes from wavesurfer to the Bar UI progress or vice-versa. 

Ideally, when you mouse click in the waveform (using the wavesurfer seek method) to apply those changes to the SM2 progress bar/ball and likewise when changing the progress bar/ball in SM2, update the seek location in the wavesurfer waveform.

I've tried with this with no luck:

     wavesurfer.on('seek', function (position) {
         var currentTime = position * wavesurfer.getDuration();
         var trackTime = wavesurfer.getCurrentTime(position);
         var ttime = fmtMSS(trackTime);

         // none of these stick
         $('.sm2-progress-bar').attr('style', 'width:' + currentTime + '%');
         $('.sm2-progress-ball').attr('style', 'left:' + currentTime + '%');
         $('.sm2-inline-time').html(ttime);

    });

    function fmtMSS(s){return(s-(s%=60))/60+(9<s?':':':0')+s} // turns raw seconds into mm:ss

Any ideas on how to do that?
