### ISSUE TITLE
playPause button does not work 

### ISSUE THREAD

**Issue by sardari-shervin** [katspaugh/wavesurfer.js#705]
Hi everyone ! 

I have a problem trying to create an audio with wavesurfer.js 

Everything is fine the music is load but the playPayse button doesn't work 

here is my code 

HTML
```
<div id="waveform"></div>
 <button class="btn btn-primary" data-action="play" onclick="wavesurfer.playPause()">Play / Pause</button>
```

JS
```
var wavesurfer = WaveSurfer.create({
	  container: '#waveform',
	  waveColor: '#fff',
	  progressColor: 'FDD670',
	});


	wavesurfer.load('http://ia902606.us.archive.org/35/items/shortpoetry_047_librivox/song_cjrg_teasdale_64kb.mp3');
```

Here is what i get : 
<img width="1310" alt="capture d ecran 2016-04-24 a 13 40 15" src="https://cloud.githubusercontent.com/assets/10119648/14767275/2d11b99e-0a22-11e6-84c5-4a99ede04964.png">

I try to do it on google chrome safari and firefox but this damn button doesn't want to work and i don't find explanation about the playPause function on the website. 

Thank you for your help

**Comment by sardari-shervin** [comment]
I just find the solution the code was right but i had a shitty z-index for something transparent and the button was unclickable ! :p 

thanks anyway !

**Comment by yogesh0296** [comment]
Hello all,

I have a problem trying to play audio with wavesurfer.js in safari browser.
when i click on play button it's show me error only safari.

TypeError: 'undefined' is not a function (evaluating 'this.ac.createGainNode()')
app.js:23
TypeError: 'undefined' is not an object (evaluating 'wavesurfer.on')
app.js:19
TypeError: 'undefined' is not an object (evaluating 'wavesurfer.playPause')

Please help me. How to solve this problem.
Thanks in advance.
