### ISSUE TITLE
Anyone Tried Realtime with Cordova

### ISSUE THREAD

**Issue by james-hoegerl** [katspaugh/wavesurfer.js#711]
Does anyone have any experience generating waveforms in real time with Cordoa/PhoneGap or Ionic? @katspaugh ?

**Comment by katspaugh** [comment]
Try searching in the issues. There've been several postings incl. some very useful code snippets.

**Comment by james-hoegerl** [comment]
Great thanks.

**Comment by katspaugh** [comment]
Particularly this issue: #677.
