### ISSUE TITLE
[region] event for update-start (due to dragging or resizing) ?

### ISSUE THREAD

**Issue by arnaudbey** [katspaugh/wavesurfer.js#712]
Hey

First of all, congrats for the really nice piece of code you have here... really helpful !

I got a little problem. I'm using region and I'd want them to not overlap. Is there any way to catch the start of a drag or resize event in order to save the original position of a region and possibly restore it if it overlaps with another one ? 

Thanks : :+1:

**Comment by thijstriemstra** [comment]
Closing.
