### ISSUE TITLE
Is there a provision to just show the waveform and highlight using JSON structure without actually loading the audio file?

### ISSUE THREAD

**Issue by cyberinferno** [katspaugh/wavesurfer.js#713]

**Comment by katspaugh** [comment]
This use case isn't supported, but you could call an internal method to just draw the waveform:

    this.drawer.drawPeaks(peaks, width);

Where `peaks` are an array of floats (your JSON), and `width` is the desired width of the resulting waveform in pixels.

**Comment by btomashvili** [comment]
Hi @katspaugh   do you have any sample how to draw  waveform without loading full audio file  ?

**Comment by katspaugh** [comment]
Yes, this one: https://github.com/katspaugh/wavesurfer.js/blob/master/example/audio-element/main.js
The main point is to use `backend: 'MediaElement'` and pass an array of peaks to the `load` method.
