### ISSUE TITLE
Region drag changes its size

### ISSUE THREAD

**Issue by ghost** [katspaugh/wavesurfer.js#717]
I want to add some fixed regions that you can drag but not resize.

But when you drag a region to the beginning or ending of the wave it gets resized and becomes smaller, even if it's not "resizable".

**Comment by katspaugh** [comment]
I think it was made on purpose as a feature. I assume, you would expect the region to simply stop moving when dragged to the edge?

**Comment by Syrenne** [comment]
Yes, that's exactly what I'd like. Is it possible to do it?

**Comment by katspaugh** [comment]
I think it's makes more sense than resizing, too. It should be possible by adding a check here:
https://github.com/katspaugh/wavesurfer.js/blob/0a0e6757174919f3c03bc1f7798f8f9247b04dcf/plugin/wavesurfer.regions.js#L343

```
var maxEnd = this.wavesurfer.getDuration();
var excess = this.end + delta - maxEnd;
if (excess > 0) {
    delta -= excess;
}
```

Can you test it and create a PR?

**Comment by thijstriemstra** [comment]
> Can you test it and create a PR?

No feedback, closing.
