### ISSUE TITLE
High CPU usage?

### ISSUE THREAD

**Issue by Joshfindit** [katspaugh/wavesurfer.js#718]
Issue: When playing audio, the CPU usage jumps way up, and the browser tab has a chance of going unresponsive.

Ran across this when embedding on a page but figured it was a local problem (or at least an implementation problem), but it's happened on a second, totally unrelated page.

http://goo.gl/Y8m7CJ

Is there something I'm missing?

**Comment by katspaugh** [comment]
Yes, decoding a 56-minute m4a in the browser into an array of JavaScript numbers can be intensive. You could try pre-decoding the file on the server and load it like this: https://github.com/katspaugh/wavesurfer.js/blob/master/example/audio-element/main.js#L26-L28

**Comment by Joshfindit** [comment]
That makes sense, thanks.
Is it just the peaks that need to be calculated?
(As in; if the peaks are pre-calculated, the cpu usage will be minimal even with large files)

**Comment by katspaugh** [comment]
We have to options: `backend: 'WebAudio'` (the default) and `backend: 'MediaElement'`. The former uses the decoded data for both playback and peaks, the latter–only for peaks. So yes, if you use `MediaElement` + pre-decoded peaks, the CPU usage is supposed to be minimal. The same as simply playing `<audio>`, almost.
