### ISSUE TITLE
Where can I get unminified version of the wavesurfer.js?

### ISSUE THREAD

**Issue by joseph2** [katspaugh/wavesurfer.js#721]

**Comment by katspaugh** [comment]
We provide only a minified build along with a source map.

**Comment by pitrackster** [comment]
@joseph2 you can clone this repo and get unminified files from src folder. The only thing to be aware of is the order of file inclusion in your HTML depending on what you want to use...

Here is what works in my use case :
1 - wavesurfer.js
2 - util.js
3 - drawer.js
4 - drawer.canvas.js
5 - html-init.js
6 - webaudio.js
7 - mediaelement.js
8 - wavesurfer.timeline.js
9 - wavesurfer.regions.js
10 - wavesurfer.minimap.js
