### ISSUE TITLE
Audio and peaks out of sync

### ISSUE THREAD

**Issue by mgibson8** [katspaugh/wavesurfer.js#722]
I seem to be having some issues with the sync between peaks and the audio. I'm loading JSON peaks created by wav2json, and this works reasonably well for short audio. However, longer audio is totally out of sync and seems to get progressively worse.

Take this example:
![image](https://cloud.githubusercontent.com/assets/13867790/15251993/d9c8fb88-1923-11e6-82fe-801bda5bf909.png)

The audio starts where the play bar is, however it should've begun earlier as you can see. I would render the peaks with wavesurfer, however, with the length of audio I generally use (usually 30-90mins) this isn't possible for performance reasons. Initially I figured the problem would be with wav2json, however, others don't seem to have this issue.

Any suggestions?

**Comment by katspaugh** [comment]
Could you provide an example of wave2json output and the corresponding audio file? Even better, a codepen with a working example.

**Comment by mgibson8** [comment]
I've attached some sample audio and the wav2json output here. Due to the sensitive nature of the audio I work with I have just used some audio from the BBC and looped it as an example, it still demonstrates the issue though.

![image](https://cloud.githubusercontent.com/assets/13867790/15320094/a034c432-1c26-11e6-85dc-ba23de5e8072.png)
The play bar here shows where the audio begins, but the peaks start slightly after.

Here are the test files:
[wavesurfer_test.zip](https://github.com/katspaugh/wavesurfer.js/files/267996/wavesurfer_test.zip)

Sorry I couldn't provide a codepen, I think I need a Pro account to demonstrate it properly, which I do not have unfortunately.

Thanks for looking into this!

**Comment by berio** [comment]
Hi all,
same problem here, have you found any solution to this?

**Comment by entonbiba** [comment]
@mgibson8 @berio can you provide the code that you are using in a codepen or zip folder?

**Comment by thijstriemstra** [comment]
The `audiowaveform` tool should be used for generating peaks, see the FAQ for more info: https://wavesurfer-js.org/faq/

If there's another way to generate peaks using `wav2json`, post them here and we can add that to the FAQ as well.
