### ISSUE TITLE
Provide wavesurfer.js as an ES6 module

### ISSUE THREAD

**Issue by fpena06** [katspaugh/wavesurfer.js#723]
Hi everyone. Can this be used with ES6?

**Comment by katspaugh** [comment]
I'm not sure what exactly you are asking. ES5 in which wavesurfer.js is written, is a subset of ES6. So yes, you can load and use the library in ES6 code.

**Comment by fpena06** [comment]
Thanks for your reply. I can use the library fine with IonicJS if I include the library in index.html. But when trying to use the method below I can’t access wave surfer.

import * as WaveSurfer from 'wavesurfer.js';

**Comment by katspaugh** [comment]
Ah, no. Unfortunately, `import` is not supported at the moment. I'll reopen this ticket to add it.

**Comment by fpena06** [comment]
thanks mate!

**Comment by pitrackster** [comment]
:+1:  on this request !
Would be really great to be able to use wavesurfer lib and plugins via ES6 import !

**Comment by thijstriemstra** [comment]
pull requests are welcome!

**Comment by mspae** [comment]
FYI I'm currently working on a PR for this.

**Comment by mspae** [comment]
https://github.com/katspaugh/wavesurfer.js/pull/861
