### ISSUE TITLE
Restore splitter-merger to play well with setFilters

### ISSUE THREAD

**Issue by nathansnider** [katspaugh/wavesurfer.js#724]
When trying to add nodes to a WebAudio graph using the `setFilters` method in version 1.1.1, I get the following error:

> Uncaught TypeError: Failed to execute 'connect' on 'AudioNode': No function was found that matched the signature provided.

The error is in reference to [this line](https://github.com/katspaugh/wavesurfer.js/blob/c7e96c36af4096659069075ea8ec756a298ae8be/src/webaudio.js#L94) of the `setFilters` method, which was changed in [PR#689](https://github.com/katspaugh/wavesurfer.js/pull/689). 

I'm not doing anything fancy - just mixing three separate mono waveforms into stereo, with one of them panned center and the others panned left and right. The relevant code for one of them (called `waveLeft`) looks like this:

```
var centerGain = 0.3;

var pannerLeft = waveLeft.backend.ac.createStereoPanner();
pannerLeft.pan.value = -1;

var gainL = waveLeft.backend.ac.createGain();
gainL.gain.value = 1 - centerGain;

waveLeft.backend.setFilters([pannerLeft, gainL]);
```

It was still working as of v1.1.0:

http://fiddle.jshell.net/nathansnider/qqtjko16/

but produces the error (and does not add any panner and gain nodes) in v1.1.1:

http://fiddle.jshell.net/nathansnider/Lty0kfdq/

**Comment by katspaugh** [comment]
The regression seems to be introduced in #689. @whenov could you take a look?

**Comment by whenov** [comment]
The error goes away if `setFilters` is executed in the `ready` event handler of wavesurfer:
``` javascript
waveLeft.on('ready', function() {
	var pannerLeft = waveLeft.backend.ac.createStereoPanner();
	pannerLeft.pan.value = -1;
	var gainL = waveLeft.backend.ac.createGain();
	gainL.gain.value = 1 - centerGain;
	waveLeft.backend.setFilters([pannerLeft, gainL]);
})
```

Because `WaveSurfer.load` is an asynchronous function, the `setFilters` in your code is called after `WaveSurfer` object is created and before `load` ends its execution.

In 1.1.0, `setFilters` will connect your last filter in the list to `WaveSurfer.backend.gainNode`, which is created in the creation of `WaveSurfer`. But in 1.1.1, your last filter will be connected to `WaveSurfer.backend.splitter`, which is created after `load`, that's the reason of the error.

The `splitter` can't be created before `load` is called, because it needs the number of channels of the loaded audio for its creation.

**Comment by katspaugh** [comment]
@whenov maybe the splitter can be implemented in terms of `setFilter`? Then we could insert the splitter on demand in `setChannel` instead of creating them on load.

Something like this:

```
setChannel: function (channel) {
    var channels = this.buffer.numberOfChannels;
    var splitter = this.ac.createChannelSplitter(channels);
    var merger = this.ac.createChannelMerger(channels);
    splitter.connect(merger, channel);
    this.setFilters([ splitter, merger ]);
}
```

**Comment by katspaugh** [comment]
@nathansnider I've released a new version 1.1.2. Please check if `setFilters` is working again.

**Comment by whenov** [comment]
Well, just revert it then, maybe the `setChannel` function should be implemented in user code using `setFilters` anyway. It's better to keep the default filters as simple as possible.

**Comment by nathansnider** [comment]
Yes, `setFilters` is working again in 1.1.2. Thanks, @katspaugh! Looks like we can close this issue, unless you want to keep it open for future work on the splitter-merger.
