### ISSUE TITLE
Cannot pass the wavesurfer object

### ISSUE THREAD

**Issue by Mikirevo** [katspaugh/wavesurfer.js#725]
Hi, the problem is that I have more tracks on the page. The scope was that to create the wavesurfer object only if the play button is clicked. The same button, after the wave is created, has only to work as playPause button. I cannot pass thw wavesurfer object to the 'else' code.
`<button class='tasto' id='".$record[4]."' onclick='Create(this);'>Play</button>
var play = 0;

function Create(oggetto_tasto){

if(play == 0){

 var tastoN = oggetto_tasto.parentNode.childNodes[4].id; /*tastoN*/
 alert("valore: "+tastoN);
 var songN = oggetto_tasto.parentNode.childNodes[7].id; /*song1*/
 alert("valore: "+songN);
 
 var id_wave = tastoN.slice(5);
 var wave = "#waveform"+id_wave; /*waveformN*/
 var wavesurferN = "wavesurfer"+id_wave;
 var timeN = "time"+id_wave;
 alert(wave);
 alert(wavesurferN);
 
 wavesurferN = new WaveSurfer;
 
 creaOnda();
 
 
 play = 1;
           }
           
 else{
   alert("else")
   var tastoN = oggetto_tasto.parentNode.childNodes[4].id; /*tastoN*/
   var id_wave = tastoN.slice(5);
   var wavesurferN = "wavesurfer"+id_wave;
   alert(wavesurferN)
   wavesurferN.playPause();
   play = 0;
 }

function creaOnda(){ 
    alert("speremo")
 
  wavesurferN = WaveSurfer.create({ /*waveform N, dove N è il numero della traccia */
    container: wave,  
    waveColor: '#333',
    progressColor: '#35a9fc',
    barWidth: '4',
    height: '64',
    backend: 'MediaElement',
    mediaType: 'audio'
  });
  
  //**** Al click della classe tasto leggere src della traccia (id)
wavesurferN.load("songs/"+songN+".mp3");  /*wavsurfer N . load e traccia presa da db*/

wavesurferN.play();

wavesurferN.on("audioprocess", function (time) {
    var duration = wavesurferN.getDuration();
    var min1 = Math.floor((duration % 3600) / 60);
    var sec1 = ("00" + Math.floor(duration % 60)).slice(-2);

    var currentTimePlaceholder = document.getElementById(timeN);
    currentTimePlaceholder.textContent = min1 + ":" + sec1;
});
}

}`

Can you help me?

**Comment by katspaugh** [comment]
This seems to be a generic JavaScript question. Please try to look for help on StackOverflow.
