### ISSUE TITLE
Wrong file plays after loading multiple times in short succession

### ISSUE THREAD

**Issue by rijk** [katspaugh/wavesurfer.js#727]
Great library, thanks so much for putting this out.

I have a list of tracks the user can loop through, each time triggering a `WaveSurfer.load()` call. I've noticed a bug that I can reproduce by pressing the next button at just the 'right' intervals — the song that ends up playing is not the last one loaded, but the one loaded before it.

Unfortunately, this is deeply embedded in an application, so I cannot share a quick reproduction repo, but I've been plowing through the source code and adding `console.log` statements to track down this issue.

I've found out that the problem occurs when the `load` call is executed, while the `decodeArrayBuffer` is still running. The `tmpEvents` are cleared, which is why [the callback](https://github.com/katspaugh/wavesurfer.js/blob/master/dist/wavesurfer.js#L405-L407) is not executed. So far, so good, but when the aforementioned callback is re-scheduled and executed after loading the *last* file, [the buffer that's loaded](https://github.com/katspaugh/wavesurfer.js/blob/master/dist/wavesurfer.js#L296) is actually the data from the *second-to-last file*! This is really strange, and I am not sure why this happens yet. Probably as a result of [the `this` binding](https://github.com/katspaugh/wavesurfer.js/blob/master/dist/wavesurfer.js#L295-L297) that's going on [everywhere](https://github.com/katspaugh/wavesurfer.js/blob/master/dist/wavesurfer.js#L347).

What I've also found, is that when I change [this code](https://github.com/katspaugh/wavesurfer.js/blob/master/dist/wavesurfer.js#L400-L407) from:

        this.backend.decodeArrayBuffer(
            arraybuffer,
            this.fireEvent.bind(this, 'decoded'),
            this.fireEvent.bind(this, 'error', 'Error decoding audiobuffer')
        );
        this.tmpEvents.push(
            this.once('decoded', callback)
        );

to:

        this.backend.decodeArrayBuffer(
            arraybuffer,
            callback,
            this.fireEvent.bind(this, 'error', 'Error decoding audiobuffer')
        );

(making it call the callback directly, instead of via an event), the loading issue is fixed and the audio correctly plays the last loaded version. But now, the waveform shows both waves at the same time.

So, I'm submitting this ticket, because I think someone who has a little more insight into the events approach chosen has to look at what the best fix for this issue would be.

**Comment by katspaugh** [comment]
Thanks for the report, I'll take a look.

**Comment by katspaugh** [comment]
I think I've understood what is happens.

 * We load Audio A.
 * Audio A is being decoded.
 * We load Audio B.
 * The temporary events are cleared.
 * Audio B is being decoded.
 * Audio B sets its callback on `decoded`.
 * Audio A is finished decoding.
 * Callback of Audio B is fired with Audio A's buffer.

**Comment by rijk** [comment]
Awesome. That could explain it I think.

**Comment by rijk** [comment]
I can confirm the issue is fixed! Great work.

**Comment by katspaugh** [comment]
Thanks for the detailed info! It really helped figure out this long-standing issue.
