### ISSUE TITLE
Add my project to your list please

### ISSUE THREAD

**Issue by avesgit** [katspaugh/wavesurfer.js#728]
https://en.inettools.net/app/audio/index/1 CutMp3 Online

**Comment by chrisparton1991** [comment]
Hey @avesgit, I've added a pull request (#793) to add your project to the "Commercial" section of the projects list.

Your app works well, given my limited testing. Good stuff :)

A couple of suggestions for your app:
- Hide your `Play/Pause` button initially, and show it inside a `ready` event callback, e.g.:
```
wavesurfer.on('ready', function () {
    $('#my-button').show();
});
```
  I can currently click the button before the waveform has loaded, and a JavaScript exception is thrown.
- Change `Sing In` text to `Sign In`.

**Comment by chrisparton1991** [comment]
Added :)
