### ISSUE TITLE
Microphone example on wavesurfer-js.org not working in Chrome (non-HTTPS)

### ISSUE THREAD

**Issue by thijstriemstra** [katspaugh/wavesurfer.js#729]
http://wavesurfer-js.org/plugins/microphone.html will not work from a non-HTTPS domain in Chrome. @katspaugh is a free SSL certificate from LetsEncrypt an option for you?

**Comment by katspaugh** [comment]
The site is hosted on GitHub. I'm not sure if you can add HTTPS here. We can either move it to S3 or make the microphone example an external link to codepen.

**Comment by thijstriemstra** [comment]
Theres a cloudflare option: http://davidensinger.com/2014/04/transferring-the-dns-from-namecheap-to-cloudflare-for-github-pages/

**Comment by katspaugh** [comment]
Thanks, I'll try that!

**Comment by katspaugh** [comment]
@thijstriemstra I've added a CloudFlare DNS for wavesurfer-js.org and a rule to always redirect to HTTPS. So when the DNS finishes propagating (hopefully in several hours), this issue should be resolved.

**Comment by thijstriemstra** [comment]
@katspaugh for now this is only an issue in Chrome and I don't have that installed here but if you say it's fixed (y) I guess we should go through all documentation and use https where applicable.
