### ISSUE TITLE
Song only plays on page refresh in Safari

### ISSUE THREAD

**Issue by Robo-romeski** [katspaugh/wavesurfer.js#731]
I have loaded a basic case for the plugin with waveform - no special implementation. works seamlessly with Firefox and Chrome. But in iOS, the autoplay doesn't work, and neither do the play or play pause methods. clicking the stop button  produces this error: 
```
[Error] InvalidStateError: DOM Exception 11: An attempt was made to use an object that is not, or is no longer, usable.
	stop (wavesurfer.min.js:4:13207)
	pause (wavesurfer.min.js:4:13207)
	pause (wavesurfer.min.js:4:2614)
	stop (wavesurfer.min.js:4:3398)
	onclick (www.justbonita.com:112)
```

looking in my sources, all elements for wave surfer are loaded into browser.

this is what my js looks like:

```
var wavesurfer = WaveSurfer.create({
    container: '#waveform',
    scrollParent: true,
    waveColor: 'white',
    progressColor: '#d3165e',
    height: '75',
    fillParent: false
});
wavesurfer.load('audio/magnet.mp3');
 if (navigator.userAgent.indexOf('Safari') && !navigator.userAgent.indexOf('Firefox') && !navigator.userAgent.indexOf('Chrome')) {
          wavesurfer.init({autoplay:true});
        };
wavesurfer.on('ready', function () {
    wavesurfer.play();
});
```
And HTML:

       <div class="wavectrl">
       <div id="waveform"></div> 
      <div class="buttongrp">
      <button type="button" id="playpause" class="btn btn-play btn-primary outline" onclick="wavesurfer.playPause()" data-toggle="button">
      <i class="glyphicon glyphicon-pause"></i></button>
      <button type="button" id="playpause" class="btn btn-play btn-primary outline" onclick="wavesurfer.stop()" data-toggle="button">
      <i class="glyphicon glyphicon-stop"></i></button>
      <button type="button" id="playpause" class="btn btn-play btn-primary outline" onclick="wavesurfer.play()" data-toggle="button">
    <i class="glyphicon glyphicon-play"></i></button>
    
  </button><br></div></div>

Strangely on refresh, everything including the autoplay works. any ideas on this?

**Comment by katspaugh** [comment]
Firstly, the `autoplay` parameter` only works with `backend: 'MediaElement'`.
Secondly, when `WaveSurfer.create` already calls `init`. So when you call it the second time, you overwrite the options.
Finally, on iOS autoplay won't work [by design (of Safari)](https://developer.apple.com/library/iad/documentation/AudioVideo/Conceptual/Using_HTML5_Audio_Video/AudioandVideoTagBasics/AudioandVideoTagBasics.html#//apple_ref/doc/uid/TP40009523-CH2-DontLinkElementID_7):

>  To prevent unsolicited downloads over cellular networks at the user’s expense, embedded media cannot be played automatically in Safari on iOS—the user always initiates playback.

On refresh, I guess, the audio is already downloaded and cached.

**Comment by Robo-romeski** [comment]
You'll have to excuse me; I didn't comment that code out - I got it from one of the other previous threads in my searches for a solution. Thank you for the clarification. But getting it to work on safari when wavesurfer.play(); is invoked the issue. any ideas?

**Comment by katspaugh** [comment]
As noted above and in our [FAQ](http://wavesurfer-js.org/faq/):

> It's a known issue that iOS won't allow you to play the audio programmatically. It won't play unless the user clicks on the page. It's a power/bandwidth-saving feature of iOS Safari.

**Comment by Robo-romeski** [comment]
I think you misunderstood me. To make sure it was not a problem with my code, I have tested using the demo. (wavesurfer-js.org) when the demo page is opened initially in safari in a private window, it loads as it should, but does nothing when you call it. only upon page refresh. I have replicated the issue multiple times and on multiple machines....

**Comment by katspaugh** [comment]
> it loads as it should, but does nothing when you call it
I don't understand what you mean. I've just opened wavesurfer-js.org in iOS Safari and it works.
