### ISSUE TITLE
Get click/seek event time?

### ISSUE THREAD

**Issue by skookie000** [katspaugh/wavesurfer.js#732]
Is it possible to get the seek time on a click event?  Right now it looks like I have to wait for the player to be playing for getCurrentTime to return the new time.  I see handleEvent, but wasn't sure how to get that out.

I'm looking to have wavesurfer chase a video player, basically making it the timeline, and updating WS playhead every few seconds with where the video player is at.  Right now a user has to double-click between the updates to get the seek value.  Can't have WS playing.

Something like:
```
document.getElementById("#waveform").addEventListener("click", function(e) {
	videoplayer.seek( wavesurfer on click seek time here );
});
```

**Comment by skookie000** [comment]
This project is just amazing too by the way... I'm so geeked out on it.

**Comment by katspaugh** [comment]
You can listen to the [seek event](http://wavesurfer-js.org/docs/events.html).

```
wavesurfer.on('seek', function (position) {
    var currentTime = position * wavesurfer.getDuration();
})
```

It might be better to return a position in seconds in the first place, but it so happened historically that the event returns you the current position as a fraction of duration.

**Comment by skookie000** [comment]
That's what I thought!  But for some reason I was stuck in a loop, and the unsubscribe event wasn't firing, but now it is.  GAH!  Thank you!  I'm using this on a recording department site, so awesome.
