### ISSUE TITLE
ready event fires before waveform appears

### ISSUE THREAD

**Issue by tctc91** [katspaugh/wavesurfer.js#736]
In the docs, it says that the 'ready' event should fire when "audio is loaded, decoded and the waveform drawn.". However, for me it is firing as soon as the audio starts playing (BEFORE the waveform is drawn).

Edit-

I see this is a duplicate of #429. Could we have a separate event fired for the waveform? From what I understand, the solution in #429 won't work for me as I need the track to start playing before the waveform is loaded.

**Comment by katspaugh** [comment]
Do you have a proposal for the new event name?

**Comment by tctc91** [comment]
Nothing nice and simple like the other event names! 

waveformReady / waveformready ?

**Comment by belackriv** [comment]
this seems to work in the meantime:
```js
wavesurfer.once('redraw', ()=>{
      debugger;
    });
```

**Comment by KainLaVey** [comment]
I really need an Event that is fired when the waveform is drawn, too. :(

**Comment by tctc91** [comment]
Any update on this issue :) ?

**Comment by KainLaVey** [comment]
You can use the loading event and wait until it has load the track 100%. 

`wavesurfer.on('loading', function(e){ if(e == 100){ //doSomething; } });`

Its nearly the same as to wait the waveform drawn, because it will be drawn immediately after the track is loaded 100%.

**Comment by X-Raym** [comment]
The mentioned didn't work for me :/ too bad; it would really help me build my peak cache system.

**Comment by X-Raym** [comment]
I found that having an event which fires when waveform is decoded from audio loaded with media element backend is very useful to create peaks file. No other native events works as nicely, so I think it could be good to have it.
https://github.com/X-Raym/wavesurfer.js/commit/250cde1410622b68d219f23ec2a3571cf1e30e26

I can make a pull request if you are interested :)

**Comment by X-Raym** [comment]
@katspaugh Hi,
Are you ok for a pull request with the event mentionned above ?
I use it for WaveSurfer-WP-Premium, and it is especially useful for peaks file creation, as this event is only trigger if wavesurfer is loaded with MediaElement and without peaks.

**Comment by katspaugh** [comment]
@X-Raym I'm all for it, but I don't get why you named it "noPeaks". In the`decodeArrayBuffer`, callback peaks are, on the opposite – present.

**Comment by X-Raym** [comment]
@katspaugh 'noPeaks' because it is trigger only if no peaks have be passed as parameter of the `load` function. This event is called when waveform is drawn from audio analysis, and not from other sources (like a peaks file).

But really, you can choose another name which would fit more your actual events naming conventions.

**Comment by katspaugh** [comment]
I'm OK with what was suggested here before: `waveform-ready`.

**Comment by X-Raym** [comment]
**@katspaugh** 
Sounds good,
I'm on it 🐙

**Comment by katspaugh** [comment]
Published version 1.2.3 on npm with the new event. Thanks @X-Raym!
