### ISSUE TITLE
How to separate an audio into left or right channel?

### ISSUE THREAD

**Issue by gjzhappy** [katspaugh/wavesurfer.js#739]
I want to achieve a function which can switch the channel manually,and here is my question,how to filter the channel?I checked the web audio API and read the chart  'ChannelSplitterNode' , but I still don't how to do this exactly

**Comment by katspaugh** [comment]
Basically, you need to create this splitter node and insert it between the buffer source and the destination.

In case of wavesurfer.js, you can do it by passing the splitter node to the `wavesurfer.setFilter` method (check the docs on our homepage).

**Comment by gjzhappy** [comment]
I appreciate your advice,but unfortunately the doc is not sufficiently detailed,and below is my code,Somehow the left channel is just not work out while the right channel function seem to be right,I connect splitter and gain and merger node together to filter the sound，as you see:
if ('left' == channel) {
            console.log("--left channel--")
            var splitter = wavesurfer.backend.ac.createChannelSplitter(2);//default is 6
            var merger = wavesurfer.backend.ac.createChannelMerger(1);
            var gain = wavesurfer.backend.ac.createGain();
            gain.value = 0;
            splitter.connect(gain, 1);
            gain.connect(merger);
            this.backend.setFilters(merger);
        } else if ('right' == channel) {
            console.log("--right channel--")
            var splitter = wavesurfer.backend.ac.createChannelSplitter(2);//default is 6
            var merger = wavesurfer.backend.ac.createChannelMerger(1);
            var gain = wavesurfer.backend.ac.createGain();
            gain.value = 0;
            splitter.connect(gain, 0);
            gain.connect(merger);
            this.backend.setFilters(merger);
}

**Comment by katspaugh** [comment]
You need to pass both splitter and merger to `setFilters`. Set filters will connect them together.
Take a look at the source code of `setFilters`: https://github.com/katspaugh/wavesurfer.js/blob/master/src/webaudio.js#L79

Feel free to update the docs if you figure out a solution.

**Comment by gjzhappy** [comment]
Yes,I've read the source code before,it seems function setFilters() just simply connect each node,but I think we should use 2 or more parameters in connect() like connect(para1,para2,para2) if we want to specify the channel we want to operate as Web Audio API describes,and I still try to figure out how to achieve this in wavefurfer.js.

**Comment by gjzhappy** [comment]
It seems that I have to write my own 'setFilters()',appreciate your time any way.

**Comment by gjzhappy** [comment]
Here am I again,this is my code about setFilters(),however it does not seem to work well,actually when it runs,the audio will generated noise,I just can't find out the problems with it,hope you can give me some suggestions,thank you.
==========code1===================
var splitter = wavesurfer.backend.ac.createChannelSplitter(2);//default is 6
var merger = wavesurfer.backend.ac.createChannelMerger(1);
this.backend.setCustFilters(splitter,merger,'right');//or left
==========code2===================
 setCustFilters:function(splitter,merger,flag) {
        this.disconnectFilters();
        if (flag == 'left'){
            console.log("====left channel====")
            this.analyser.connect(splitter).connect(merger,0).connect(this.gainNode);
        } else if (flag == 'right'){
            console.log("====right channel====")
            this.analyser.connect(splitter).connect(merger,1).connect(this.gainNode);
        }
    },

**Comment by gjzhappy** [comment]
PR#689 has solved my problems,this issue can be closed now.

**Comment by Vasant-JS** [comment]
Hi guys, kindly help me,
I wanna pass 2 different audio files into 2 channels, but i m not getting how to do it...

**Comment by gjzhappy** [comment]
@Vasant-JS  https://github.com/naomiaro/waveform-playlist，ple check this.
