### ISSUE TITLE
what about filtering the waves based on frequency (ie cut spectrum into highs, mids, lows), and have different colors for the different freq regions?

### ISSUE THREAD

**Issue by wolfbiter** [katspaugh/wavesurfer.js#74]
this is a little more of a wishlist thing, buuuut... it would be reeeeally sweet.... and i know webaudio has the capability (i'm sure there are plenty of examples online). i would possibly consider doing it myself, but this wouldn't take priority until the far future

**Comment by feng-x-w** [comment]
Why is the spectrum not colored?I think that might be better
