### ISSUE TITLE
Scheduled pause (play range) doesn't update start position

### ISSUE THREAD

**Issue by cwleonard** [katspaugh/wavesurfer.js#741]
I'm not sure if this is intentional or not, but when playing a range of the audio the start position is not updated when the scheduled pause takes place. This results in the next call to `play` (without a range specified) picking up at a previous start position.

I fixed it in my fork by calling `pause()` in webaudio.js when the time is >= scheduledPause instead of calling `setState` and `fireEvent` directly.

If the original behavior is intentional, I would like to request an option to change that behavior. If it was not intentional, I can submit a pull request.

Thanks.

**Comment by katspaugh** [comment]
Looks like a bug. A PR would be nice! Calling `pause` in this case is fine, but I think the same code also runs when the audio is finished. I might be wrong though. Let's talk in the PR.
