### ISSUE TITLE
Failed to set the 'currentTime' property on 'HTMLMediaElement'

### ISSUE THREAD

**Issue by yoko10000** [katspaugh/wavesurfer.js#745]
big wav file.1:20:32.wrong:
wavesurfer.js:1257 Uncaught TypeError: Failed to set the 'currentTime' property on 'HTMLMediaElement': The provided double value is non-finite.

**Comment by thijstriemstra** [comment]
@yoko10000 can you show a code example that reproduces this?

**Comment by harrytarzan2000** [comment]
@thijstriemstra If found that when the funtion had (start value as NaN)  for below code , the error occured. 
     `seekTo: function (start) {
        if (start != null) {
            this.media.currentTime = start;
        }`

**Comment by tjamps** [comment]
A bit late on this, but check that your server returns the correct header for "Content-Length" (this was the problem for me, when set everything is working).

**Comment by entonbiba** [comment]
@yoko10000 what is the value that you are setting for wavesurfer.seekTo(**VALUE**)?

If you are getting the value from an input in the html with jquery for example with $('input').val(), make sure it exists and the value is a valid number. Sometimes when the html or even the audio/video file is not loaded yet, it will return undefined which will cause that error.

**Comment by agamemnus** [comment]
Also, if you're using a `MediaElement` as the backend, and your audio is not streamed/ (chunked?), you won't be able to set the currentTime...

**Comment by mspae** [comment]
I think this is probably caused by some faulty calculation below https://github.com/katspaugh/wavesurfer.js/blob/master/src/drawer.js#L99

Apparently this happens on Firefox when clicking (I haven't been able to reproduce) but we need a reproducible test case beyond passing a non-number to `seekTo` (which will and should fail for obvious reasons).
