### ISSUE TITLE
wavesurfer.util is undefined always and doesnt create the oscillator.

### ISSUE THREAD

**Issue by deepika-Gopala** [katspaugh/wavesurfer.js#746]
im using wavesurfer plugin to generate an oscillaotr but i always get " Uncaught TypeError: Cannot read property 'extend' of undefined "  while creating the wavesurfer.create({}) , as on debugging i see that : "wavesurfer.util " is undefined  

Im adding the sample code that i am using.

i am dynamically generating the waveform element and then creating the wavesurfer  which is giving the above error.
			$("<div id='waveform'></div>").appendTo(r);
				var waves = WaveSurfer.create({
					container:"#waveform",
					waveColor:"red",
					progressColor:"black"
				});
waves.load("D:\$TUDI@\TONESWADESH.mp3");   ------------or--------
waves.load('http://ia902606.us.archive.org/35/items/shortpoetry_047_librivox/song_cjrg_teasdale_64kb.mp3');

Can anyone help me out on this, ASAP please!

**Comment by thijstriemstra** [comment]
@deepika-Gopala what about

```javascript
var wavesurfer = Object.create(WaveSurfer);
wavesurfer.init({
    container: '#waveform',
    waveColor: 'violet',
    progressColor: 'purple'
});
```

**Comment by deepika-Gopala** [comment]
Hi thij,

Thanks, My mistake,  the plugin that i had downloaded did not have a util function. So i just replaace it with the fresh content of the wavesurfer.js and its working fine now.

Thanks for getting back. Cheers!
