### ISSUE TITLE
Using Analyser with wavesurfer

### ISSUE THREAD

**Issue by bzp13** [katspaugh/wavesurfer.js#747]
How can I connect AudioContext Analyser to wavesurfer?

I want to show visualisation bars graph and control audio playback through wavesurfer

**Comment by katspaugh** [comment]
Pass the analyzer note to `setFilters`. It will insert it between the source and destination.

**Comment by bzp13** [comment]
Thank you!

```
var analyser = wavesurfer.backend.createAnalyserNode();
wavesurfer.backend.setFilters(analyser);
```

**Comment by conceptualspace** [comment]
^^ the code above not working for me :/

to be clear, i was trying to add an _additional_ analyser node. but it seems i can't get any nodes to insert (like a delay).

btw, waversurfer-js.org doc says to use `wavesurfer.backend.ac.createAnalyser()` but the code above reads `wavesurfer.backend.createAnalyserNode()`?

i actually tried both but to no avail. will look into the src here, but maybe u have some insight? thanks!

**Comment by bzp13** [comment]
Do you use developer console? What error do you get?      You can find correct method using developer tools in browser

**Comment by conceptualspace** [comment]
woop, backend.ac did the trick after all
