### ISSUE TITLE
Not working on first load with Safari 9.1.1

### ISSUE THREAD

**Issue by mklz1** [katspaugh/wavesurfer.js#749]
On first visit of the page there is no sound on play click.
After reload of the page - it woks.

**Comment by katspaugh** [comment]
Thanks! I confirm.

**Comment by Robo-romeski** [comment]
This is what I was talking about in ticket #731 - which was closed 25 days ago.

**Comment by katspaugh** [comment]
@Robo-romeski I couldn't reproduce it at that time 😅

**Comment by Robo-romeski** [comment]
@katspaugh It's cool - just curious as to why it's happening.

**Comment by katspaugh** [comment]
Published the npm package at version 1.2.4 with a work around. The root cause was Safari having the Web Audio context suspended on the first page-load.
