### ISSUE TITLE
Audio resets after clicking Foward or Backward  on controls.

### ISSUE THREAD

**Issue by nickreale** [katspaugh/wavesurfer.js#750]
Been using wavesurer.js for about a year now with many different audio types. They are retrieved from remote servers using a GET statement returned by the audio host server.

 wavesurfer.load('<? echo urldecode($_GET['al']) ?>');

Been working flawlessly. (Thank you for such an awesome product). 

Now for the problem. One particular server is returning the .wav file appropriately and the files plays but, when you try to move through the wav it resets back to the beginning and plays again.

This does not happen from any of the other servers I interact with. Also, on this server the waveform is never drawn either.

Any suggestions or help?

Thanks,

Nick

**Comment by katspaugh** [comment]
Are you using `backend: 'MediaElement'` or the default backend?

**Comment by nickreale** [comment]
Default

<? echo urldecode($_GET['al']) ?>
<table><tr><td width="500">
      <div class="container">
          <div id="waveform">
            <progress id="progress" class="progress progress-striped" value="0" max="100"></progress>
          </div>

          <script>
            var wavesurfer = WaveSurfer.create({
              container: '#waveform',
             
              progressColor: 'hsla(200, 100%, 30%, 0.5)',
              cursorColor: '#000',
			  splitChannels: true,
			  height: 150,
			  minPxPerSec: 8,
			  fillParent: false,
			  backend: 'MediaElement'
            });

            wavesurfer.on('loading', function (percents) {
              document.getElementById('progress').value = percents;
            });

            wavesurfer.on('ready', function (percents) {
              document.getElementById('progress').style.display = 'none';
            });

            wavesurfer.load('<? echo urldecode($_GET['al']) ?>');
          </script>

          <div class="controls">
            <button class="btn btn-primary" onclick="wavesurfer.skipBackward()">
              <i class="fa fa-step-backward"></i>
              Backward
            </button>

            <button class="btn btn-primary" onclick="wavesurfer.playPause()">
              <i class="fa fa-play"></i>
              Play
              /
              <i class="fa fa-pause"></i>
              Pause
            </button>

            <button class="btn btn-primary" onclick="wavesurfer.skipForward()">
              <i class="fa fa-step-forward"></i>
              Forward
            </button>

            <button class="btn btn-primary" onclick="wavesurfer.toggleMute()">
              <i class="fa fa-volume-off"></i>
              Toggle Mute
            </button>
          </div>

**Comment by nickreale** [comment]
nope media elemnet.. sorry

**Comment by katspaugh** [comment]
I've had this problem with media element and certain HTTP servers, too. Some servers don't send the correct headers for audio files.

See here as well: http://stackoverflow.com/a/9565178/352796

**Comment by katspaugh** [comment]
No, the solution is to use a HTTP 1.1 server. Or use the default backend.

**Comment by lorenzfischer** [comment]
I had a similar problem with wavesurfer resetting onClick in the Waveform and resolved it by sending the correct (byte range query enabled) headers from the backend. I have put my code as a comment to the respective issue: https://github.com/katspaugh/wavesurfer.js/issues/492

**Comment by Ankush-techwinlabs** [comment]
I am also facing similar problem with WaveSurfer resetting onClick on the wave form & forward/backward controls.
This problem is only showing i use `backend: MediaElement`. Is there any solution ?

**Comment by katspaugh** [comment]
I suspect this is server-related. Some servers don't handle media seeking that well.
If you insert the same audio as just a plain <audio> element, does setting the `currentTime` work for you?
