### ISSUE TITLE
window is undefined

### ISSUE THREAD

**Issue by omerts** [katspaugh/wavesurfer.js#751]
First of all thanks for this great library. 

I am trying to use this project in server-side environment, but it fails with:
```
window is undefined
```

The reason for this is because different references to window across the code, specifically `window.devicePixelRatio`, and there is no window object at the server-side. 

If you are asking yourself, why do I need it in server side, it is because I am doing server-side rendering (React.js app).

**Comment by katspaugh** [comment]
I have no idea how this code can work outside of the browser. React has an abstraction layer above DOM, but wavesurfer.js is using some very specific browser APIs. Unless you have a NodeJS Web Audio implementation, I doubt that you can run wavesurfer.js on Node. Feel free to send a PR, though.

**Comment by omerts** [comment]
@katspaugh  I am not trying to run it, but just to render it and pass it rendered to the browser. The problem is mainly because window.devicePixelRatio is used event before any wavesurfer has been actually created.

**Comment by katspaugh** [comment]
> I am not trying to run it, but just to render it and pass it rendered to the browser.

Then it's an easy fix. Set the default pixel ratio to 1 and in the init function conditionally assign to `window.devicePixelRatio` if no param was passed.

**Comment by omerts** [comment]
@katspaugh  Thanks alot!

**Comment by cco3** [comment]
Any chance this can be reopened?  I can't import during SSR on 3.3.3.

**Comment by Aparus** [comment]
> Any chance this can be reopened? I can't import during SSR on 3.3.3.

may be it'll help you? advice for next.js : 
https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr
