### ISSUE TITLE
Calling EnableDragSelection multiple times creates duplicate regions

### ISSUE THREAD

**Issue by olafvisker** [katspaugh/wavesurfer.js#752]
Hello,

I've noticed that calling enableDragSelection() multiple times also causes every "drawn" region to be a duplicate. So in the instance where you are trying to create one region you are actually creating as many as the times you've called enableDragSelection. Of course I can just call the function once, but it seems to me that this behaviour was not intended.

You can easily recreate this problem by copy pasting enableDragSelection a couple of times [over here](http://codepen.io/katspaugh/pen/obmOXV?editors=1010) and then selecting a region. If you then try to move it out of the way, you'll notice the duplicates.

Kind regards

**Comment by katspaugh** [comment]
Yes, I can reproduce it. `enableDragSelection()` adds DOM event listeners every time it's called. I suppose a simple flag `wavesurfer.regionsEnabled = true` should help. Can you send a pull request?

**Comment by Flimm** [comment]
Is this fixed now?

**Comment by thijstriemstra** [comment]
@Flimm no doesn't look like it, see #1698 for new ticket.
