### ISSUE TITLE
Duration and CurrentTime

### ISSUE THREAD

**Issue by amichel86** [katspaugh/wavesurfer.js#753]
Hi, thank you for this awesome player, it's working well! I was wondering if it is possible to have something like my screenshot below.

- Remove the vertical progress bar
- Have a 3 digit counter for the current time 
- Have 3 digit counter for the duration

Thanks and keep up the good work!

![image](https://cloud.githubusercontent.com/assets/5871701/16269969/8482a620-3862-11e6-9fd1-d77493b10ea1.png)

**Comment by katspaugh** [comment]
For cursor: `cursorWidth: 0`.

For the timers:
 * use the [event](http://wavesurfer-js.org/docs/events.html) `audioprocess` to update the timers.
 * Current time: `getCurrentTime()`
 * Duration: `getDuration()`.
 * It's up to you to format the time in seconds however you like.

See http://wavesurfer-js.org/docs/methods.html.

**Comment by amichel86** [comment]
Awesome, thank you for your quick response. Concerning the formatting of the time would you be able to direct me on a tutorial on how to do this? I am not a big JS expert so I am trying to figure it out by myself :)

Right now it looks like this:

![image](https://cloud.githubusercontent.com/assets/5871701/16270635/024e636c-3865-11e6-8bb1-e8d9c3d2a29e.png)

Thanks a bunch!

**Comment by katspaugh** [comment]
Here's something you can start with: https://github.com/katspaugh/wavesurfer.js/blob/master/plugin/wavesurfer.regions.js#L245-L252

    var formatTime = function (time) {
        return [
            Math.floor((time % 3600) / 60), // minutes
            ('00' + Math.floor(time % 60)).slice(-2) // seconds
        ].join(':');
    };

**Comment by amichel86** [comment]
Well thank you I will look into this :)

**Comment by amichel86** [comment]
If I need additional help, do you accept money to help me out? Because by looking at the formatTime function I don't really know what to do so that CurrentTime and Duration get formatted. Thanks!

**Comment by katspaugh** [comment]
Sure, drop me an email at katspaugh@gmail.com.

**Comment by amichel86** [comment]
Sent!

**Comment by katspaugh** [comment]
For posterity (I've been asked about this again), here's the code:

```javascript
var formatTime = function (time) {
    return [
        Math.floor((time % 3600) / 60), // minutes
        ('00' + Math.floor(time % 60)).slice(-2) // seconds
    ].join(':');
};

// Show current time
wavesurfer.on('audioprocess', function () {
    $('.waveform__counter').text( formatTime(wavesurfer.getCurrentTime()) );
});

// Show clip duration
wavesurfer.on('ready', function () {
    $('.waveform__duration').text( formatTime(wavesurfer.getDuration()) );
});
```

**Comment by wangzhaoming132** [comment]
our answer let me solve the problem! Thank you very much!

**Comment by meteorplus** [comment]
thank you but may be add this in the docs? :)

**Comment by LangsamNil** [comment]
wavesurfer is awesome and compact, great job really but please, increase the doc :D

**Comment by fleshka779** [comment]
You can also use:

```
import CursorPlugin from 'wavesurfer.js/dist/plugin/wavesurfer.cursor.js';

CursorPlugin.prototype.formatTime = function (cursorTime) {
    return cursorTime;
};
```
