### ISSUE TITLE
MediaElement fallback - Wait for song to start playing before start XHR for drawing

### ISSUE THREAD

**Issue by nahuelhds** [katspaugh/wavesurfer.js#756]
Not an issue, but maybe a feature if you will, of course.

In my project I needed the songs to start as soon as possible, so I've used the MediaElement backend fallback, but I've notice that when you don't provide peaks two requests are done, the audio one and the XHR at the same time.

This means you always are downloading the double of the size of the song.

In my case, I hacked the WaveSurfer.util.ajax method in order to wait fo the song to start playing before triggering the XHR request.

I used a flag in the ready event (startedPlaying, false by default and true when ready event is triggered). Then, in the ajax method when startedPlayed is true, then I start the XHR.

This wait the browser downloads the temporary audio buffer that needs to play the song fast, and then I start XHR knowing that the user is listening the song, which is the most important in my case.

Excellent plugin!

**Comment by katspaugh** [comment]
You can use the Media Element backend with an existing [`<audio>` element](https://developer.mozilla.org/en/docs/Web/HTML/Element/audio). So, to control the loading and playback:

 * Insert the audio tag with `preload=true`.
 * When the user presses the play button, play the audio and load this element into wavesurfer.js (just call the load method with a reference to the element instead of a URL).

**Comment by nahuelhds** [comment]
Thanks for the feedback, @katspaugh but that's one of the things I've tried.
The problem is that when you don't provide peaks, an XHR start simultaneously with the Audio load, so the bandwidth is divided in those two requests. As you cannot set priority, I needed to give max priority to the actual audio in some way.
What I mentioned is a way to give preference to the audio to load before the the audio to be drawn. Of course, just an idea, or maybe a use case for my particular issue.

The component is excellent, by the way!

**Comment by katspaugh** [comment]
Then you can first load it with an empty array (fake peaks), and when the user starts playing, load the same audio element without the fake peaks. Or maybe you don't even need to initialize wavesurfer.js before the user presses the play button.

**Comment by nahuelhds** [comment]
Good to know. Just sharing my experience and my use case, maybe other people have the same issues. Thanks!
