### ISSUE TITLE
Change audioRate dynamically?

### ISSUE THREAD

**Issue by andrewhaining** [katspaugh/wavesurfer.js#757]
I would like to add a button for the user to choose the playback speed, is it possible to change the  audioRate dynamically via a method?

Thanks

**Comment by katspaugh** [comment]
Have you tried reading [the docs](http://wavesurfer-js.org/docs/methods.html) before asking?

> setPlaybackRate(rate) – Sets the speed of playback (0.5 is half speed, 1 is normal speed, 2 is double speed and so on).

**Comment by andrewhaining** [comment]
Apologies, I missed that one.
