### ISSUE TITLE
cannot load from absolute path with drive letter

### ISSUE THREAD

**Issue by conceptualspace** [katspaugh/wavesurfer.js#759]
`wavesurfer.load('C:\\wavesurfer\\music\\song.mp3')` fails silently

paths without a drive letter succeed, for example `wavesurfer.load('..\\music\\song.mp3')`

if i try escaping the : chrome just treats it as a relative path

on win10x64

**Comment by katspaugh** [comment]
Why would you expect local filesystem paths to work in a browser? `..\\music\\song.mp3` works, I guess, only because there's some local web server working in the background which serves the file as `../music/song.mp3`.

**Comment by conceptualspace** [comment]
running it in an electron app, where chromium is permitted local file access

**Comment by conceptualspace** [comment]
i guess the path is unexpected in wavesurfer and gets mangled somewhere

**Comment by conceptualspace** [comment]
looks like there is already have a solution -- loadBlob; so just have to create the fileobject from the path first
