### ISSUE TITLE
Beginners failing at:  -- AJAX .html page containing wavesurfer

### ISSUE THREAD

**Issue by tweed** [katspaugh/wavesurfer.js#760]
**Common Problem** ?

My HTML file (c01.html) shows waveform and plays fine by itself --
When called via AJAX "c01.html" doesn't show waveform or play.

My index.html i use the script below to call html page "c01.html" into a DIV via AJAX- is there a correct way to change the script below it to call my **c01.html** page via ajax?

**Below is what's in my index.html with my WRONG? script which has the DIV**

```html
        <div id="c01" class="vjs-fluid">

          <script>
          var xhr= new XMLHttpRequest();
          xhr.open('GET', 'c01.html', true);
          xhr.onreadystatechange= function() {
          if (this.readyState!==4) return;
          if (this.status!==200) return; // or whatever error handling you want
          document.getElementById('c01').innerHTML= this.responseText;
          };
          xhr.send();
          </script>
          </div>`

````

**Below is in the html i try to AJAX into the DIV above**

**HTML File Name: c01.html**
I took the exact code from the main wavesurfer homepage example.
Many seasons now trying *-)
cannot get c01.html named page called by ajax to play or show waveform.

````HTML

<header class="overview"> 
  <div class="container"> 
    <div class="demo"> 
  <div id="waveform"> 
    <progress id="progress" class="progress progress-striped" value="0" max="100"></progress> 
  </div> 

  <script> 
    var ctx = document.createElement('canvas').getContext('2d'); 
    var linGrad = ctx.createLinearGradient(0, 64, 0, 200); 
    linGrad.addColorStop(0.5, 'rgba(255, 255, 255, 1.000)'); 
    linGrad.addColorStop(0.5, 'rgba(183, 183, 183, 1.000)'); 

    var wavesurfer = WaveSurfer.create({ 
      container: '#waveform', 
      waveColor: linGrad, 
      progressColor: 'hsla(200, 100%, 30%, 0.5)', 
      cursorColor: '#fff', 
      normalize: true, 
      barWidth: 3 
    }); 

    wavesurfer.on('loading', function (percents) { 
      document.getElementById('progress').value = percents;
    });

    wavesurfer.on('ready', function (percents) {
      document.getElementById('progress').style.display = 'none';
    });

    wavesurfer.load('https://ia801404.us.archive.org/23/items/gd79-09-04.sbd.clugston.9452.sbeok.shnf/gd79-09-04Sbdd1t03.mp3');
  </script>

  <div class="controls">
    <button class="btn btn-primary" onclick="wavesurfer.skipBackward()">
      <i class="fa fa-step-backward"></i>
    </button>

    <button class="btn btn-primary" onclick="wavesurfer.playPause()">
      <i class="fa fa-play"></i>
      Play
      /
      <i class="fa fa-pause"></i>
      Pause
    </button>

    <button class="btn btn-primary" onclick="wavesurfer.skipForward()">
      <i class="fa fa-step-forward"></i>
      Forward
    </button>

    <button class="btn btn-primary" onclick="wavesurfer.toggleMute()">
      <i class="fa fa-volume-off"></i>
      Toggle Mute
    </button>
  </div>

  <p align="right">
    <small class="text-muted">
      The recording is from the <a href="https://archive.org/details/gd79-09-04.sbd.clugston.9452.sbeok.shnf">Internet Archive</a>.
    </small>
  </p>
</div>

  </div>
</header>
````

**Comment by katspaugh** [comment]
When you insert HTML via `innerHTML`, the scripts inside the inserted HTML are not evaluated. That's how it is. You need to somehow call the JavaScript from the parent page after you insert the HTML.

**Comment by tweed** [comment]
kind... -- thanks!
yep, i've known that the problem - i've looked everywhere for a solution i can understand/use.
funnily, video.js works fine so i had hope that the fairly recent wavesurfer changes to include "calling via inner-html" etc. might have helped.

I eventually wrote here as i bet lots of us are having problems calling wavesurfer. 

Anyone able to see what's wrong with my script? -- the first bit of code above

**Comment by tweed** [comment]
Ended up (for now*-) using jquery instead of vanilla JS which i'd rather use.
this works:
````HTML
                  <script>

        $( "#c01" ).load( "c01.html" );

                  </script>
````

**Comment by fisherman77** [comment]
Hi I have identical problem.

I try use jQuery function .load() to refresh container with wave forms from wavesurfer.js and wavesurfer-WP plugin and if I call function .load(), then I get errors in console and waveforms not showing.

I have div container #div witch waveforms in frontend and I use load method:

`jQuery("#div").load(location.href + " #div");`
I want make no refresh site.

Some have this problem and how I can fix this?
