### ISSUE TITLE
Update scroll is not working well when integrating both timeline and spectrogram plugin

### ISSUE THREAD

**Issue by TangHao1987** [katspaugh/wavesurfer.js#762]
Here is the issue:
As this line doing assign instead of adding observer:
`wavesurfer.drawer.wrapper.onscroll = this.updateScroll.bind(this);` 

so when integrating more than one plugins, the earlier initialized plugin onscroll will be overridden by later initialized plugin. In the end only the last initialized plugin onscroll will work.

**Comment by katspaugh** [comment]
Good catch! Can you send a pull request with `addEventListener`?

**Comment by TangHao1987** [comment]
Sure. :) I will open a pull request later for this.

**Comment by katspaugh** [comment]
I've publish v. 1.1.8 with your changes.
