### ISSUE TITLE
bower.json question

### ISSUE THREAD

**Issue by pitrackster** [katspaugh/wavesurfer.js#767]
Hi !
I'm currently trying to use wavesurfer with webpack / ES6 / angular...
I have a problem with the folder name created via the bower command (ie wavesurfer.js) because webpack search for a file named wavesurfer.js but find a folder so it get stuck...

If I change the name of the folder (removing the `.js`) it works ...

So I am wondering if it is possible to change the package name so that it will not create a folder with `.js` ?

**Comment by thijstriemstra** [comment]
You should be able to work aroind this issur in webpack, there's no chance the folder name is going to get changed anytime soon, just to accomodate webpack functionality

**Comment by pitrackster** [comment]
Ok thanks anyway

**Comment by xbill82** [comment]
@pitrackster you can add an alias in your webpack config file

```javascript
module.exports = {
  resolve: {
    alias: {
      'wavesurfer': path.resolve(__dirname, './node_modules/wavesurfer.js/dist/wavesurfer.js')
    }
  }
}
```

**Comment by katspaugh** [comment]
Thanks, @xbill82! Adding to the readme.
