### ISSUE TITLE
Ready Event starts before drawing waveform

### ISSUE THREAD

**Issue by KainLaVey** [katspaugh/wavesurfer.js#770]
First i have to say: Thank you for this nice software! <3

I have an Problem with the "ready" Event. It gets triggered when der track is playing. But i need an Event that is only triggered when the waveform is drawn.

Somehink like waveform.on('waveformdrawn', function(){...});

Is there any other solution to do something after the waveform is drawn?

**Comment by KainLaVey** [comment]
I found a little workaround.

I use the 'loading' Event. And when the callback return 100 the song is loaded complete, an so the waveform will be drawn immediately.

**Comment by katspaugh** [comment]
Closing as duplicate of #736. Thanks for the work around!
