### ISSUE TITLE
Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().

### ISSUE THREAD

**Issue by Fiorello** [katspaugh/wavesurfer.js#771]
Hi, i'm trying to use wavesurfer.js with MediaElement backend, and external audio tag.
When i seek into the wave while playing i get this error:

`Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().`

Maybe it depends by the size of the audio file, 16 minutes about 4 MB.
When i use loop function, with regions plugins, the browser tab freeze for a while, generating an huge amount of this error.

I've tried to use your "audio-element"and preload peaks with my audio file, and the error is the same.
![screen shot 2016-07-08 at 17 18 44](https://cloud.githubusercontent.com/assets/3278942/16692289/72d1a7fc-4530-11e6-9361-67c3e4699a04.jpg)

Can you help me, please?

**Comment by mkadutskyi** [comment]
I have something the same. When I have this option backend: 'MediaElement', I can't seek. It just paused. And throughs the same error

**Comment by mspae** [comment]
I can confirm that this also happens in the annotations example, which uses the MediaElement backend to get around CORS restriction for the remote audio file.

**Comment by entonbiba** [comment]
@Fiorello @mkadutskyi @mspae may you check with the latest version, the following fix was applied #977 which might be related.

**Comment by mspae** [comment]
@entonbiba Yes awesome! – I found https://github.com/katspaugh/wavesurfer.js/issues/994 while checking.

**Comment by vvillalo** [comment]
How was your xhr configuration in the waveconfig?
