### ISSUE TITLE
The 'backend.buffer' is not always ready when the 'ready' event fires

### ISSUE THREAD

**Issue by AdolfVonKleist** [katspaugh/wavesurfer.js#776]
I'm trying to get ahold of the `backend.buffer` via `wavesurfer.on ('ready', function () {...})`:

<pre>wavesurfer.on ('ready', function () {
  var originalBuffer = wavesurfer.backend.buffer;
  console.log (originalBuffer);
}</pre>

More often than not, the console log prints 'null'.  If on the other hand, I tie this same bit to 'seek' or some other event, it always works, and the buffer object is printed.  

Am I doing something wrong with this access approach?  I based this on something I found on SO:
- http://stackoverflow.com/a/24596314

**Comment by AdolfVonKleist** [comment]
I resolved this, at least for the case where we use `loadMediaElement` with a url.  In this case the `backend.buffer` is `null` until this block:

<code>
        // If no pre-decoded peaks provided, attempt to download the
        // audio file and decode it with Web Audio.
        if (url && !peaks && this.backend.supportsWebAudio()) {
            this.getArrayBuffer(url, (function (arraybuffer) {
                this.decodeArrayBuffer(arraybuffer, (function (buffer) {
                    this.backend.buffer = buffer;
                    this.drawBuffer();
                    //The buffer is now ACTUALLY READY!
                    this.fireEvent ("loaded-buffer", buffer.length);
                }).bind(this));
            }).bind(this));
        }
</code>

 I added a new event: ` this.fireEvent ("loaded-buffer", buffer.length);`.   When this fires the `backend.buffer` is always actually ready and non null, if it exists.

I wanted this so that I could draw individual subsegments.  Now I can use the buffer + region information, reconstruct a new .wav file from the sub-segment and render this independently.  This was the best hack I was able to come up with for solving the issue of rendering just a sub-segment of a given audio file.

**Comment by katspaugh** [comment]
I'll accept a PR if you wish. If you do it, please keep in mind that the new event should fire for both backends.

**Comment by thijstriemstra** [comment]
can we not fire the `ready` event at the right time when using `loadMediaElement`? Why introduce a new event?

**Comment by katspaugh** [comment]
A new event `waveform-ready` added in #860.
