### ISSUE TITLE
project using wavesurfer

### ISSUE THREAD

**Issue by jspear29** [katspaugh/wavesurfer.js#779]
I'm using wavesurfer in this project I've been working on.  It definitely a work in progress.

https://github.com/jspear29/electro

**Comment by chrisparton1991** [comment]
Did you want this added to the wavesurfer.js project list, @jspear29?

**Comment by jspear29** [comment]
Heck yeah!  That's awesome.  It's still going through a lot of changes, but I think I will be ready for my first packaged release soon. ++Motivation.  I was super stoked just to get the thumbs up emoji. Thanks for the killer library.

**Comment by chrisparton1991** [comment]
Awesome :) I'm working on my own side project that uses wavesurfer too, I might add it to the projects list as well: https://github.com/chrisparton1991/sparkled.

Most of the credit for the library goes to @katspaugh :)

**Comment by chrisparton1991** [comment]
Pull request created for both our projects: #794.

Electro and Sparkled sound like names that could be part of the same product suite haha. Keep up the good work @jspear29, your project looks cool!
