### ISSUE TITLE
Zooming in and out on wave makes audio stutter 

### ISSUE THREAD

**Issue by anatoliyg** [katspaugh/wavesurfer.js#780]
I noticed that while zooming in, this.seekAndCenter is called. Is there a real reason to do that? I would think that on zoom, no seeking needs to be done since the audio should continue playing as is, and only the waves be redrawn

**Comment by Stoyvo** [comment]
@anatoliyg Please review my merge request. Should solve the stuttering.

**Comment by chrisparton1991** [comment]
@anatoliyg can you please test this once a new release has been made and close the issue if it works?

Is there an ETA on a release with this fix, @katspaugh?

**Comment by katspaugh** [comment]
I've published v. 1.1.12.

**Comment by thijstriemstra** [comment]
No feedback, closing, considering it fixed.
