### ISSUE TITLE
Programatically set current time.

### ISSUE THREAD

**Issue by swordsreversed** [katspaugh/wavesurfer.js#783]
Hi, I want to use a button to set the timeline to a certain point on the timeline, say 30 sconds in. I tried seekTo but it didn't seem to work. Here's a pen:

[http://codepen.io/anon/pen/AXaydZ?editors=1010#anon-login](http://codepen.io/anon/pen/AXaydZ?editors=1010#anon-login)

How would I do this?

**Comment by katspaugh** [comment]
`seekTo` takes a fraction of duration (i.e. a percentage), not seconds.
Try `wavesurfer.seekTo(30 / wavesurfer.getDuration())` instead of wavesurfer.seekTo(30)`.
