### ISSUE TITLE
unable to create wave charts for songs at amazon s3

### ISSUE THREAD

**Issue by neeraj24a** [katspaugh/wavesurfer.js#784]
When ever i am calling my s3 mp3 files to plot the waves of a songs. it gives me below error.

Failed to load resource: the server responded with a status of 404 (Not Found)
test.html:1 XMLHttpRequest cannot load http://neeraj-f0b1ea.s3.amazonaws.com/Desiigner%20-%20Timmy%20Turner%20%28D…TQKEKGZSJDLKSA&Expires=1469689916&Signature=yfExCQd0CkPweIhDTxfQyHK1NEA%3D. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:9090' is therefore not allowed access.

Can you please guide.

**Comment by katspaugh** [comment]
Search in Google for "S3 how to enable CORS".

**Comment by monikasaran293** [comment]
I am also facing the same issue. The audio is loading, I can here it but waveform is not creating. CORS is already added in S3. The audio is playing perfectly in audio tag.
