### ISSUE TITLE
I load a mp3 file with Pre-rendered Peaks,and I also want to play/draw one channel specified by parameter,is there a demo to do so?

### ISSUE THREAD

**Issue by gjzhappy** [katspaugh/wavesurfer.js#787]
I got a demo in doc which load the media with pre-rendered peaks(http://wavesurfer-js.org/example/audio-element/) , and I found it works,I also know how to pick one channel to play from this(https://github.com/katspaugh/wavesurfer.js/pull/689/files#diff-268e184f68ebebc7a4772c6e3a47c2abR310) , but I couldn't make them work together,do you have some ideas about this issue?

**Comment by thijstriemstra** [comment]
no feedback, closing.
