### ISSUE TITLE
Audiowaveform JSON generated

### ISSUE THREAD

**Issue by drhouse7** [katspaugh/wavesurfer.js#791]
Hi katspaugh,
first I wanna thank you and say that I love your JS, it's a brilliant job!

I tried to use Audiowaveform to generate JSON, but I don't understand why the output is something like

`{ ... "data":[0,0,0,0,-46,37 ...`

Instead your JS needs decimal. In this manner I must array_map and divide objects by 100.

Is it correct this or am I missing something?

Best regards

**Comment by katspaugh** [comment]
I cannot check it right now, but I think you can pass `normalize: true` as a wavesurfer.js param and it will accept peaks in any range (and normalize them to decimal fractions).

You might also need to filter out negative values as in:

```
var output = { ... "data":[0,0,0,0,-46,37 ...
var peaks = output.data.filter(function (value) { return value >= 0; });
```

**Comment by drhouse7** [comment]
From your demo page I tried 
```
'use strict';

// Create an instance
var wavesurfer = Object.create(WaveSurfer);

// Init & load audio file
document.addEventListener('DOMContentLoaded', function () {
    // Init
    wavesurfer.init({
        container: document.querySelector('#waveform'),
        waveColor: '#A8DBA8',
        progressColor: '#3B8686',
        backend: 'MediaElement',
        normalize:true
    });

    // Load audio from URL
    wavesurfer.load('../media/demo.wav');

    document.querySelector(
        '[data-action="play"]'
    ).addEventListener('click', wavesurfer.playPause.bind(wavesurfer));

    document.querySelector(
        '[data-action="peaks"]'
    ).addEventListener('click', function () {
        wavesurfer.load('../media/demo.wav', [
21, 28, 23, 15, 25, 25, 23
        ]);
        document.body.scrollTop = 0;
    });
});
```

But the waveform generated is not normalized (all bars are at highest level)

**Comment by katspaugh** [comment]
Ah, I see. Then yes, you need to divide them by 100.
