### ISSUE TITLE
Playing long duration files

### ISSUE THREAD

**Issue by harrietsCreativeDabblets** [katspaugh/wavesurfer.js#796]
Hi,
Did anyone have success playing long duration files? I am trying with a 90minute file, and the browser does not give any type of error, but it bombs out with a "aw snap" error message after some time.

I really need to get this working, as the we support longer duration files.

Thanks!

**Comment by katspaugh** [comment]
Duplicate of #143. Citing a response from that issue:

> the technology we are relying on (WebAudio's bufferSourceNode) isn't supposed to be used with big audio clips.

You can use `backend: "MediaElement"`, decode files offline and provide the decoded data to the `load` function. See https://wavesurfer-js.org/example/audio-element/

**Comment by swaheed2** [comment]
If anyone has any php solution for server side decoding please provide.

**Comment by harrietsCreativeDabblets** [comment]
What is the longest duration for an audio file that is supported then?

**Comment by harrietsCreativeDabblets** [comment]
So I gather from reading around a bit, that there is only a solution where the audio file content is downloaded and decoded, before the canvas can load the sound wave graph.

Is there a way to make the process less resource intensive? I have tried the backend: 'MediaElement' setting, and as far as I understand this will allow the audio to be played back while the content is still being downloaded, and if pre-rendered peaks are provided, the file does not need to be decoded. I do not have pre-rendered peaks from the server though - how would I generate such a file?

I take it there is no streaming solution available, where only a certain fraction of the audio is placed into a buffer for display &/|| playback at a certain time? This has been an issue for some time - and I am wondering if anyone has found a solution they are willing to share, that will allow playback of larger files?

**Comment by harrietsCreativeDabblets** [comment]
So I gather from reading around a bit, that there is only a solution where the audio file content is downloaded and decoded, before the canvas can load the sound wave graph.

Is there a way to make the process less resource intensive? I have tried the backend: 'MediaElement' setting, and as far as I understand this will allow the audio to be played back while the content is still being downloaded, and if pre-rendered peaks are provided, the file does not need to be decoded. I do not have pre-rendered peaks from the server though - how would I generate such a file?

I take it there is no streaming solution available, where only a certain fraction of the audio is placed into a buffer for display &/|| playback at a certain time? This has been an issue for some time - and I am wondering if anyone has found a solution they are willing to share, that will allow playback of larger files?

**Comment by harrietsCreativeDabblets** [comment]
hi - is there a dedicated person behind this support page? :) 
I'm just trying to determine whether I will get an answer or just accept it as is?

**Comment by chrisparton1991** [comment]
I don't think this is a day job for any of us, I'm afraid.

As @katspaugh mentioned above, this is a browser limitation with WebAudio. MediaElement will be the way to go, but it's trickier to get up and running (I've never tried it myself, to be honest).

There's a [CodePen](http://codepen.io/katspaugh/pen/oLmwoZ) by @katspaugh that uses prerendered peaks, passed to `wavesurfer.load()` as an array of values.

The idea is that you:

1. Use MediaElement to allow playback of larger files.
2. Generate pre-rendered peaks (see the last question in http://wavesurfer-js.org/faq/)
3. Load those pre-rendered peaks into your app (e.g. using AJAX, to retrieve them from a server. or hard-coding them into your javascript like the codepen does).

Wavesurfer supports the use of prerendered peaks, but how the peaks are loaded (e.g. from a database, file or other source) is outside the scope of the library.

**Comment by harrietsCreativeDabblets** [comment]
Thank you Chris, I understand that it will take some time. I am closing this ticket, although should such a solution ever become available I would be very interested.

**Comment by daslicht** [comment]
> To decode audio offline I recommend [`audiowaveform`](https://github.com/bbcrd/audiowaveform). Also see https://wavesurfer-js.org/faq/

How about using the exportPCM function and save that generated array ?
