### ISSUE TITLE
Maximum Stack Size Exceeded

### ISSUE THREAD

**Issue by pyros-endgame** [katspaugh/wavesurfer.js#797]
When this chunk of code is executed while loading json created peaks it will fail if the json content is too large (maybe around 84k or 100+k) 

       var absmax = 1;
        if (this.params.normalize) {
            var max = Math.max.apply(Math, peaks);
            var min = Math.min.apply(Math, peaks);
            absmax = -min > max ? -min : max;
        }

After looking around it seems like the issue is most likely the prototype.apply function (taken from this post http://stackoverflow.com/questions/18308700/chrome-how-to-solve-maximum-call-stack-size-exceeded-errors-on-math-max-apply). Maybe we could implement it as a standard for loop?

**Comment by chrisparton1991** [comment]
I have already fixed this in the MultiCanvas renderer. It was a simple case of rewriting to use a regular loop, as you said. It will be quick to do the same here. I can sort this out sometime soon.
