### ISSUE TITLE
Inability to set the media.preload type

### ISSUE THREAD

**Issue by pyros-endgame** [katspaugh/wavesurfer.js#798]
Was wondering if we have have the media.preload types as a parameter. Right now it defaults to 'auto' which will load the entire media piece when the page loads but for faster loads we can switch to 'metadata.'

If one of the wavesurfer params could include this that would be useful :P

**Comment by katspaugh** [comment]
Good point! Can a you create a PR for this?

**Comment by katspaugh** [comment]
Added in #854.
