### ISSUE TITLE
how to fill canvas until waveform is loaded when using MediaElement

### ISSUE THREAD

**Issue by swaheed2** [katspaugh/wavesurfer.js#799]
Hello, Is it possible to fill the canvas up to the thin line to show media is playing until waveform is loaded.

**Example:** 

Currently (when the waveform is still loading and audio is playing): 

![image](https://cloud.githubusercontent.com/assets/8592912/17833526/8af91564-66e5-11e6-9ea7-79fc0409d811.png)

Desired (something like this until waveform is loaded):

![image](https://cloud.githubusercontent.com/assets/8592912/17833548/37d7bfce-66e6-11e6-89de-fa67635a3f84.png)

**Comment by katspaugh** [comment]
You can do it with CSS. Use `#container-id>wave>wave` as the selector.

**Comment by swaheed2** [comment]
Thank for the quick reply! works!.
