### ISSUE TITLE
display straight horizontal line for empty audio files

### ISSUE THREAD

**Issue by harrietsCreativeDabblets** [katspaugh/wavesurfer.js#800]
Is it possible to draw a default straight horizontal line on the player, to display when an empty recording is selected? This of course will be replaced by the wave graphic when the user clicks on another recording that does have audio...

**Comment by chrisparton1991** [comment]
I don't think wavesurfer has a built in way of doing this, but take a look at @katspaugh's suggestion on #799.

You should be able to use CSS to style the waveform (and/or the progress waveform) however you like (e.g. by using a `background-image`). You could add a CSS class to your wavesurfer container and dynamically remove it inside the `wavesurfer.on('ready', ...)` call.

**Comment by chrisparton1991** [comment]
I've created a [CodePen example](http://codepen.io/chrisparton1991/pen/QERBLg) that displays a grey line whilst the waveform is loading. I'm using an online service to get my grey line background image, but you could use a local image, or any other CSS you wish.

**Comment by harrietsCreativeDabblets** [comment]
Hi Chris, thanks for your time and trouble! I decided to go for a spinner while the file is loading, and in my case I can have empty recordings as well, so in that case just a straight line is my thing!
