### ISSUE TITLE
Change http to https in examples

### ISSUE THREAD

**Issue by harrietsCreativeDabblets** [katspaugh/wavesurfer.js#801]
I use your site, https://wavesurfer-js.org to view documentation etc.

It might be compromised, as all I see when I open the site, is a picture of some headers, being repeated over and over again.

**Comment by chrisparton1991** [comment]
The site works fine for me @harrietsCreativeDabblets. Is there a specific page you're having trouble with?

Some of the website's CSS is served over CloudFlare, which was having issues in Kiev yesterday (https://www.cloudflarestatus.com/incidents/7h0z4wn9p4b7). No idea if you're from near there, but it's something to consider.

You could try clearing your browser's cache, or using `Ctrl+Shift+R` (Windows) or `Cmd+Shift+R` (Mac) to do a hard refresh of the page.

**Comment by chrisparton1991** [comment]
That said, I've noticed that some of the examples on https://wavesurfer-js.org/examples/ aren't working @katspaugh. The MP3 files in the examples are being requested over HTTP, the URLs just need to be changed to HTTPS.

**Comment by katspaugh** [comment]
@chrisparton1991 thanks! I'll change them asap.

**Comment by harrietsCreativeDabblets** [comment]
Thanks I can see the site again - however there are some examples not working as mentioned by Chris.

**Comment by thijstriemstra** [comment]
@katspaugh i can visit https://wavesurfer-js.org securely, but https://wavesurfer-js.org/docs/ always redirects to the http version?
