### ISSUE TITLE
Timer plugins

### ISSUE THREAD

**Issue by harrietsCreativeDabblets** [katspaugh/wavesurfer.js#804]
Hi,

Has anyone played around with indicating the time of the recordings (as in an alternative to using the timer plugin)?

 I am thinking a standard counter in the format 00:00:00, where the number shown in this counter indicates how far you are in your recording, and if you drag the players cursor, it updates the counter.

**Comment by chrisparton1991** [comment]
This can be achieved by hooking into wavesurfer's [events](https://wavesurfer-js.org/docs/events.html).

Codepen example: http://codepen.io/chrisparton1991/pen/PzvvPL

**Comment by Stoyvo** [comment]
@chrisparton1991 Why use: `currentTime = progressPercent * duration;`
over: `wavesurfer.getCurrentTime();`?

**Comment by harrietsCreativeDabblets** [comment]
Thank you Chris, this will help me tremendously!
