### ISSUE TITLE
Region - Enabled Loop breaks other region start times

### ISSUE THREAD

**Issue by Stoyvo** [katspaugh/wavesurfer.js#808]
Steps to Reproduce:
1) Create two regions:

```
wavesurfer.addRegion({
    start: 5,
    end: 6,
    loop: false,
    color: '#ff0000'
});
wavesurfer.addRegion({
    start: 15,
    end: 25,
    loop: true,
    color: 'rgba(50,100,50,0.5)'
});
```

2) Play first region: `regionObj1.play()` (works)
3) Play Loop: `regionObj2.play()` (works)
4) Play first region again: `regionObj1.play()`

Result:
Playing first region after loop region will start at loop region start (15sec)

Expected:
Seek to first region start (5sec)

**Comment by Stoyvo** [comment]
From investigating, I noticed that even though my event called regionObj1.play(), somehow the `onProcess` anonymous function is still being called by event `audioprocess`
https://github.com/katspaugh/wavesurfer.js/blob/master/plugin/wavesurfer.regions.js#L311

**Comment by Stoyvo** [comment]
If you update a region and set loop: true, play region, then update region and set loop: false, region still loops.

Another fact: Changing browser tab while looping does not keep loop.

**Comment by Stoyvo** [comment]
Workaround:
Find region with loop: true, update({ loop: false });

**Comment by Stoyvo** [comment]
My mistake. An event was calling the incorrect region on click.

**Comment by thijstriemstra** [comment]
@Stoyvo why did you reopen this? Seems you found a workaround, closing.

**Comment by Stoyvo** [comment]
@thijstriemstra Workaround doesn't always mean bug fixed :)
