### ISSUE TITLE
can store the wave data to a json file?

### ISSUE THREAD

**Issue by guoxiangke** [katspaugh/wavesurfer.js#809]
Or have a pre_load function? it's spent lot time to load whole mp3.
thanks.

**Comment by Stoyvo** [comment]
This has been discussed before. @arian1123 has posted a good response here on how to save peaks: https://github.com/katspaugh/wavesurfer.js/issues/535#issuecomment-145982732

To load the peaks, use: load('media.mp3', peaks);
