### ISSUE TITLE
Spectrogram vertical frequency label

### ISSUE THREAD

**Issue by JulieMarie** [katspaugh/wavesurfer.js#810]
This is actually an enhancement request for the Spectrogram plugin to display a vertical axis frequency label.  I'm using the timeline plugin for the horizontal axis which works well and now I'm just missing the frequency labels.

I'm trying to figure it out on my own, but not there yet!

**Comment by entonbiba** [comment]
@JulieMarie I created a sample that displays the labels for you. When I get a chance I'll add it to the official plugin.
http://codepen.io/entonbiba/pen/Bpmqrq

**Comment by JulieMarie** [comment]
Thanks @entonbiba, I'll check it out!

**Comment by entonbiba** [comment]
@JulieMarie I've updated the spectrogram with khz labels, the labels with custom font/color etc will be available in the next version,

**Comment by JulieMarie** [comment]
Fantastic... Thank you so much!

**Comment by entonbiba** [comment]
The spectrogram frequency labels parameter is now available in the latest version. #984
