### ISSUE TITLE
audio play on the given start and  end point.

### ISSUE THREAD

**Issue by chanchaldas8890** [katspaugh/wavesurfer.js#812]
When I tried to play wavesurfer using wavesurfer.play(a,b) where a,b values comes from database and each a and b has values stored in array.
But while executing wavesurfer.play(a,b) it always executes the last value say for (8,9.0)
e.g. :
var a=[1,4.5,7.8]
var b=[3.0,6.7,9.0]
for(var i:i<a.length;i++)
{
wavesurfer.play(a[i],b[i]);
}

**Comment by katspaugh** [comment]
Sounds like a closure-related error somewhere in your app.

**Comment by chanchaldas8890** [comment]
Thks for the reply but it is not the problem of closure
