### ISSUE TITLE
Support for Flac meadia type

### ISSUE THREAD

**Issue by omer-sds** [katspaugh/wavesurfer.js#816]
can wavesurfer play a flac file , i tried to play it but it could not load and gave erorr 

> The buffer passed to decodeAudioData contains an unknown content type

can we have support for this media type in future

**Comment by katspaugh** [comment]
The support of media formats is on the browser's side. You should ask in the corresponding browser's bug tracker.

As a fallback, you can use `MediaElement` + pre-decoded waveform JSON.
