### ISSUE TITLE
JS crash occurs after audio data has been decoded, if the WaveSurfer instance has been destroyed in the meantime

### ISSUE THREAD

**Issue by ebbe-brandstrup** [katspaugh/wavesurfer.js#818]
Thanks for a cool library/component!

I get the below error if I quickly do next, next, next in a list of audio files, where each "next" action destroys the current wavesurfer and creates a new instance.

This happens because the "onDone" callback when calling ```decodeArrayBuffer``` is then executed after I have destroyed the wavesurfer instance and thereby its ```drawer```, causing the ```drawer.style``` function to crash because its wrapper property is gone.

![screen shot 2016-09-08 at 14 08 33](https://cloud.githubusercontent.com/assets/4715559/18346202/26956218-75d0-11e6-8190-6e0505658acb.png)

**Comment by ebbe-brandstrup** [comment]
Created #819.

Notice that some other PRs had been merged into your master where only the dist files had been changed. That meant that after modifying the src files and running ```grunt``` those changes were overwritten... I had to manually copy them into the src files and build again

**Comment by katspaugh** [comment]
Oh wow. How did I miss that 🤔 Thanks!

**Comment by thijstriemstra** [comment]
PR was merged, closing.
