### ISSUE TITLE
Q: Media Element on ready FallBack and Peaks Values

### ISSUE THREAD

**Issue by X-Raym** [katspaugh/wavesurfer.js#821]
Hi,

I'm trying to get an array of peak value for generating peaks file.

The trick is to use `wavesurfer.backend.getPeaks(960)` as you describe in this issue. https://github.com/katspaugh/wavesurfer.js/issues/240

I use it with the `.on('ready')` event so that I can get the peak values after the waveform is drawn.

With WebAudio backend, it works all fine. An array of peak data is returned. (I use the console.log to debug).
With MediaElement backend, it return an empty array.

It seems that `.on('ready)` event is called before peaks are drawn when using MediaElement, wich is not the case with WebAudio.

Do you confirm ?
Is this a normal behavior ?

Thanks again for your support !

**Comment by katspaugh** [comment]
Yes, the two backends are inconsistent in this regard. It's already reported in #736. Please watch for the progress of that issue.
