### ISSUE TITLE
Introduce change log

### ISSUE THREAD

**Issue by thijstriemstra** [katspaugh/wavesurfer.js#824]
If there are no objections I'll add a changelog markdown document soon. After that is merged we should expect that the author of a new pull request adds new changes to that document, or the person that merges the PR should add the information to the change log itself.

**Comment by X-Raym** [comment]
Where is actual changelog detailed ? In only found [this one](https://allmychanges.com/p/javascript/wavesurfer.js/).

I think it would be cool if @katspaugh could write in in the [releases page](https://github.com/katspaugh/wavesurfer.js/releases). :P

**Comment by thijstriemstra** [comment]
@X-Raym it's at the root of the repository, CHANGES.md. I think @katspaugh will copy/paste from there into releases each time.

**Comment by X-Raym** [comment]
@thijstriemstra oh yes ok, I was looking for a changelog which already add info on it hehe :P
anyway, this markdown file is a great initiative.
