### ISSUE TITLE
Cannot convert object to primitive value

### ISSUE THREAD

**Issue by cyb-ahmadh** [katspaugh/wavesurfer.js#827]
Any idea about this issue?
```
Uncaught TypeError: Cannot convert object to primitive value
```
Refer screen shot for more details
![screenshot from 2016-09-22 20 35 32](https://cloud.githubusercontent.com/assets/17269118/18753873/57ef8cc8-8104-11e6-90ba-49321513f027.png)

**Comment by katspaugh** [comment]
Steps to reproduce?

**Comment by cyb-ahmadh** [comment]
I'm still not aware about how this error came through. It's just one day that i started getting these errors.

**Background:** 

I'm displaying `wavesurfer` using pcm data through `npm-pcm` module.
The data generated by `node-pcm` is huge so attaching the screenshot such that you have an idea about the `pcm data`.

**Code for displaying wavesurfer**

```
wavesurfer.load($scope.video, pcm-data);
```
**PCM code:**

```
var pcm = require('pcm');

var min = 1.0;
var max = -1.0;
var arr = [];
var arguments = process.argv[2] ;
pcm.getPcmData(arguments, { stereo: true, sampleRate: 10 },
  function(sample, channel) {
    min = Math.min(min, sample);
    max = Math.max(max, sample);
    console.log(sample);
  },
  function(err, output) {
    if (err)
      throw new Error(err);
      return arr;
  }
);
```

I hope this helps.

Thanks
![screenshot from 2016-09-22 21 14 29](https://cloud.githubusercontent.com/assets/17269118/18755425/d68cdaf4-8109-11e6-9bfa-69ae0257fdd9.png)

**Comment by katspaugh** [comment]
There reason might be the negative values in the node-pcm output.

There's already a bug for that: https://github.com/katspaugh/wavesurfer.js/issues/715. The resolution there is to add `Math.abs`.

**Comment by cyb-ahmadh** [comment]
Like this:

```
var pcm = require('pcm');

var min = 1.0;
var max = -1.0;
var arr = [];
var arguments = process.argv[2] ;
pcm.getPcmData(arguments, { stereo: true, sampleRate: 10 },
  function(sample, channel) {
    min = Math.abs(min, sample);
    max = Math.abs(max, sample);
    console.log(sample);
  },
  function(err, output) {
    if (err)
      throw new Error(err);
      return arr;
  }
);
```

**Comment by cyb-ahmadh** [comment]
I tried removing negative values but it dint work. :(

**Comment by cyb-ahmadh** [comment]
HI @katspaugh,

Thanks for your suggestion. It worked. I made a mistake in the previously mentioned code.

```
var pcm = require('pcm');

var min = 1.0;
var max = -1.0;
var arr = [];
var arguments = process.argv[2] ;
pcm.getPcmData(arguments, { stereo: true, sampleRate: 10 },
  function(sample, channel) {
    min = Math.min(min, sample);
    max = Math.max(max, sample);
    console.log(Math.abs(sample));
  },
  function(err, output) {
    if (err)
      throw new Error(err);
      return arr;
  }
);
```
