### ISSUE TITLE
Audio file without extention will not play in Safari 

### ISSUE THREAD

**Issue by Rafff** [katspaugh/wavesurfer.js#829]
Hello!

I just discovered that WaveSurfer.js in Safari 9.0.1 (it works in 9.0.2 because of WebAudio added support, but still not works in MediaElement in 9.0.2) will not play a file (streaming from Amazon S3, CORS working) when the extension is not specified.

When specifying the file extension, everything works well.

Is there any tricks/tips to make this work ?

Thanks a lot!

**Comment by katspaugh** [comment]
I guess Safari relies on either the extension or HTTP headers (most likely `Content-Type`). So the solution might be to send the right HTTP header.

**Comment by BruceWouaigne** [comment]
Indeed, no more problem when using audio/mpeg instead of application/octet-stream Content-Type.

**Comment by Rafff** [comment]
Thanks for the intel @katspaugh !
