### ISSUE TITLE
Error While Scrolling and Region Creation

### ISSUE THREAD

**Issue by stoi2m1** [katspaugh/wavesurfer.js#830]
Ive been having an issue when zoomed in and trying to scroll by grabbing the scrollbar. Each time I try to scroll it creates a new region. I want it to only create a region when clicking in the canvas area, not when trying to scroll.

I have found within the region enableDragSelection there is an eventDown click event is firing for both clicking in the waveform area and clicking on the scrollbar. I then determined when clicking on the scrollbar the tag type is Wave and when clicking within the waveform area the tag type is Canvas.

So I created a method within enableDragSelection called isCanvas

```
`isCanvas: function (evt) {
    if ( evt.target.tagName == 'CANVAS' ) {
        return true;
    } 
    return false;
}`
```

I then added in an if to check when its NOT the canvas just return out of the eventDown method

```
`if (!my.wavesurfer.Region.isCanvas(e)) { return; }`
```

Is there a better way to handle this oddity? Or is it a wanted feature?

**Comment by mspae** [comment]
maybe related to https://github.com/katspaugh/wavesurfer.js/issues/843 ?

**Comment by stoi2m1** [comment]
@mspae you are right it is exactly that. I will read that thread over and close this when I find some time over the weekend.

**Comment by stoi2m1** [comment]
@mspae the issue is related but has no solution and is worthless to me, would have been better to let the other issue know of my solution.

**Comment by ffxsam** [comment]
Unfortunately this doesn't solve the issue. When clicking ahead of the cursor, the event tagname is "CANVAS", but when clicking behind the cursor, the tagname is "WAVE". However, the two wave nodes (the actual waveform and the scrollbar) are slightly different. So I can use these differences to maybe pinpoint when the user clicks the scrollbar and prevent it from doing anything.

**Comment by ffxsam** [comment]
Ok cool, I can check `e.target.childElementCount` and if it's greater than zero, ignore the `eventDown`. Will submit a PR shortly, after testing.
