### ISSUE TITLE
error on load Safari only

### ISSUE THREAD

**Issue by elevenpast** [katspaugh/wavesurfer.js#833]
Would appreciate any tips, as I'm stuck on this. 

build: 1.2.0 and older
Error: SyntaxError: DOM Exception 12: An invalid or illegal string was specified.
Safari 9.1 (works fine on Firefox and Chrome)

wavesurfer.js line 732

```
fireEvent: function (event) {
        if (!this.handlers) { return; }
        var handlers = this.handlers[event];
        var args = Array.prototype.slice.call(arguments, 1);
        handlers && handlers.forEach(function (fn) {
            fn.apply(null, args);
        });
    }
```

My javascript snippets...

`
wavesurfer = WaveSurfer.create({
        container: '#lWave1',
        waveColor: 'red',
        progressColor: '#183B8C',
        height: '30',
        width: '200'
    });
    
wavesurfer.load(fileUrl);
`

**Comment by elevenpast** [comment]
Just realized, I got the wrong code from waverunner.js.  Here is the correct bit...

```
getOfflineAudioContext: function (sampleRate) {
        if (!WaveSurfer.WebAudio.offlineAudioContext) {
            WaveSurfer.WebAudio.offlineAudioContext = new (
                window.OfflineAudioContext || window.webkitOfflineAudioContext
            )(1, 2, sampleRate);
        }
        return WaveSurfer.WebAudio.offlineAudioContext;
    },
```

**Comment by katspaugh** [comment]
Closing, though I'm not sure if you solved it or not. Please feel free to reopen if not.
