### ISSUE TITLE
How to use `exportPCM` function

### ISSUE THREAD

**Issue by cyb-ahmadh** [katspaugh/wavesurfer.js#837]
Can you please give an example on how to use exportPCM[https://github.com/katspaugh/wavesurfer.js/blob/gh-pages/dist/wavesurfer.js#L470](url).

I tried using this way:
```
	var wavesurfer = Object.create(WaveSurfer);
    options = {
      container: document.querySelector('#waveform'),
      waveColor: 'blue',
      progressColor: 'black',
      waveformHeight: 10,
      cursorColor: 'black',
      normalize: true,
      backend: 'AudioElement',
      height: 150
    };
    wavesurfer.init(options);
    var wavedata = [.....]
    wavesurfer.load('remote url of the video or audio file')
    wavesurfer.on('ready', function() {
    	console.log("Wavefrm loaded successfully!!!");
      wavesurfer.exportPCM();
    });
```

It pops out a new window with blank array. 

Please suggest some working example. 

Thanks

**Comment by cyb-ahmadh** [comment]
Got it working. Thanks

**Comment by weavermedia** [comment]
@cyb-ahmadh How did you get it working?

**Comment by gorkie** [comment]
Would you tell me how you fixed it? I have the same problem @cyb-ahmadh

**Comment by cyb-ahmadh** [comment]
I understood `exportPCM()` as it will generate the PCM data for me but it pops out the utilised the PCM data in a seperate window. Nothing else.

**Comment by katspaugh** [comment]
https://github.com/katspaugh/wavesurfer.js/blob/master/src/wavesurfer.js#L478

The third parameter tells it to return the PCM instead of poping up the window.

So you need to call it like this:

```
var pcmData = wavesurfer.exportPCM(1024, 10000, false);
```

**Comment by ibnYusrat** [comment]
> Got it working. Thanks

This is one of the worst things a developer can possibly come across.

**Comment by ibnYusrat** [comment]
> https://github.com/katspaugh/wavesurfer.js/blob/master/src/wavesurfer.js#L478
> 
> The third parameter tells it to return the PCM instead of poping up the window.
> 
> So you need to call it like this:
> 
> ```
> var pcmData = wavesurfer.exportPCM(1024, 10000, false);
> ```

It doesn't work. It still pops up the PCM data.

**Comment by ibnYusrat** [comment]
> https://github.com/katspaugh/wavesurfer.js/blob/master/src/wavesurfer.js#L478
> 
> The third parameter tells it to return the PCM instead of poping up the window.
> 
> So you need to call it like this:
> 
> ```
> var pcmData = wavesurfer.exportPCM(1024, 10000, false);
> ```

Third parameter should be set to 'true' instead of false if you don't want to see the popup Window.

**Comment by Dereking** [comment]
> So you need to call it like this:
Same issue, got a empty array object: [NaN] 
`var sectors = [];
      this.wavesurfer.exportPCM(1024, 10000, true).then(
        (dats) => {
          console.log("exportPCM", dats);
          for (let index = 0; index < dats.length; index++) {
            const dat = dats[index];
            var r = {};
            r.start = dat.start;
            r.end = dat.end;
            r.loop = true;
            sectors.push(r);
          }
        },
        (reason) => {
          console.log("reject", reason);
        }
      );`

console.log output: 
`exportPCM (2) [NaN, NaN]`

Had anyone succsess on this function?
