### ISSUE TITLE
Inconsistency in waveforms

### ISSUE THREAD

**Issue by cyb-prajaktac** [katspaugh/wavesurfer.js#838]
I'm using `node-pcm` to generate PCM data but the waveform generated by the data of `node-pcm` is different than the waveform generated by wavesurfer. I've compared the data generated by node-pcm and wavesurfer, then it is different as well. Can you suggest something ?

```
 pcm.getPcmData("syntel.mp3", {stereo: true, sampleRate:10},
   function(sample, channel) {
     min = Math.min(min, sample);
     max = Math.max(max, sample);
     data.push(Math.abs(sample));
        console.log(Math.abs(sample));
   },
   function(err, output) {
     console.log('END');
     console.log(new Date());
     if (err) {
       throw new Error(err);
     else 
       console.log(arr);
     }
   }
 );
```

Here is the screen shot of the wave form:
![waveform](https://cloud.githubusercontent.com/assets/14269792/19005419/2bfd763c-8778-11e6-89b2-9f99cbe6b1ff.png)

Do you any other workaround to get the PCM data for the waveform similar to the run time waveform.?

**Comment by katspaugh** [comment]
node-pcm provides some examples how to normalize the PCM data ffmpeg produces:
https://github.com/jhurliman/node-pcm/blob/master/examples/waveform.js#L75

You can play with the coefficients to achieve values similar to what Web Audio's produces.

**Comment by cyb-ahmadh** [comment]
Thanks for the reference @katspaugh. I'll update about it in some days.

**Comment by binal24** [comment]
I have been using node-pcm to create waveform data in JSON format.
But, going in infinite loop.
