### ISSUE TITLE
Regions plugin - programmatically delete region

### ISSUE THREAD

**Issue by harrietsCreativeDabblets** [katspaugh/wavesurfer.js#842]
Hi,
I am currently working with the regions plugin and would like to be able to delete a specific region in my program. My first requirement is that only one region should be allowed at any given time, and I have done that by modifying the code to delete any previous regions upon adding a new region.
Now my next requirement is to be able to delete this region when certain events happen. I have tried calling wavesurfer.clearRegions() on my wavesurfer object - but it does not seem to work.

**Comment by mounaTay** [comment]
were you able to solve this?
