### ISSUE TITLE
Firefox bug - scrolling by dragging scrollbars creates a region

### ISSUE THREAD

**Issue by ffxsam** [katspaugh/wavesurfer.js#843]
See screencap below. This is only an issue in Firefox. In Chrome and Safari, it works fine.

![licecap](https://cloud.githubusercontent.com/assets/12532733/19428443/0d3ecd70-93ff-11e6-8e56-ce4711532149.gif)

If no one gets around to this, I might fix it first if I can figure out what's going on. If anyone has an idea, let me know!

**Comment by harrietsCreativeDabblets** [comment]
Hey ffxsam - I notice that when you add your region, the cursor does not move. Can you perhaps tell me how you accomplished that? My cursor moves to the last place where your mouse dragged to, and its kinda undesired for me tbh. Would appreciate your answering back. BR, Harriet.

**Comment by ffxsam** [comment]
Hey Harriet

I just tested this out. Only on Firefox, if your region starts before the cursor and ends after it (as above), it won't move the cursor. Otherwise, if you drag a region before or after the cursor, it jumps.

In other browsers like Chrome, the cursor always jumps.

**Comment by harrietsCreativeDabblets** [comment]
Thanks for your reply Sam - it's the same behavior I am experiencing... I'm trying to figure out how to let the cursor jump to the start of the region instead of the end (in case region is dragged left to right). I'm only doing Google Chrome for now.

**Comment by stoi2m1** [comment]
I was having this same issue and came up with a solution. Im not sure if its the best way but it does work.
[Issue #830](https://github.com/katspaugh/wavesurfer.js/issues/830)

**Comment by ffxsam** [comment]
@stoi2m1 My usual thinking goes, if it works then it works! Are you planning on doing a PR?

**Comment by stoi2m1** [comment]
@ffxsam I'm not sure how to do that. I'm not very familiar with using github and it's processes.

**Comment by ffxsam** [comment]
@stoi2m1 No worries! I'll take your fix and do a PR so it gets merged into the official package. Thanks for the help!
