### ISSUE TITLE
Place cursor at the start of region

### ISSUE THREAD

**Issue by harrietsCreativeDabblets** [katspaugh/wavesurfer.js#844]
Hi,
I was wondering if you could help me in putting the cursor at the start of a newly defined region, instead of having the cursor at the point where the mouse last clicked.
For instance, if you drag a region from right to left, the cursor will be on the left (start) of the region. Versus if you drag from left to right, the cursor will be on the right (end) of the region, and the user will have to move it manually to be in the region. I want it to always be at the start of the region, regardless of what direction the user dragged.
Any ideas welcomed,
Harriet

**Comment by mspae** [comment]
So the logic as I understand it should basically look like this:

Add a listener to the event `region-update-end` (it gets passed the updated region object – https://wavesurfer-js.org/plugins/regions.html), inside that use the `seekTo` method to update playback position  to the start value of the updated region.

**Comment by harrietsCreativeDabblets** [comment]
Thank you for this - I have tried adding an event listener to the event you mentioned, and can see that it is executing at the end of when a region is created. However, how do I get access to the region that has just been created? Seeing that I did not create an instance of the region object in my own code, I only said loop: true, and enableDragSelection.

**Comment by mspae** [comment]
The `region-update-end` callback function is called with the region object as parameter.

**Comment by harrietsCreativeDabblets** [comment]
this is my [code pen](http://codepen.io/BusyBee/pen/bwXYmx).
I do not understand how I would access the region in my on event handler.

**Comment by harrietsCreativeDabblets** [comment]
I added a listener to the event region-update-end, gave the function a region object as input, and updated the cursor via the seekTo method, to the starting point of the newly defined region.
However, the cursor is now always moved to the start of the waveform, which indicates that seekTo is called again after the one that initially sets the cursor to the start of the newly defined region,
It might have something to do with the say in witch the objects are nested. If anyone knows how to prevent the other seekTo from overriding the first value, please let me know.

**Comment by katspaugh** [comment]
I think you are confused by what parameters `seekTo` takes. It accepts a fraction of the total duration as its input. For example, to seek to the middle of the clip, you give it `0.5`. The beginning is 0, the end is 1.

It's in the docs.

<img width="607" alt="screen shot 2016-12-06 at 14 56 47" src="https://cloud.githubusercontent.com/assets/381895/20928030/3c713a8c-bbc4-11e6-9705-34b8b0a6ad78.png">

**Comment by wangzhaoming132** [comment]
Can you tell me what your problem is?

**Comment by wangzhaoming132** [comment]
你的问题是怎么解决的?

**Comment by mdahlgrengadd** [comment]
@wangzhaoming132  Don't know if this is an issue anymore, but here's @harrietsCreativeDabblets codepen doing what I think was requested.

http://codepen.io/mdahlgrengadd/pen/MmVeYB

One problem i ran into was that the drawer listens to the click event and, if not overridden, will cause the cursor to be placed at the end of region bacause it gets called after region-update-end.

Probably theres a more elegant solution, but this seems to work anyway.
