### ISSUE TITLE
Using <audio> already on the page

### ISSUE THREAD

**Issue by tonkku107** [katspaugh/wavesurfer.js#845]
I found this #174 issue, but I didn't understand how and I didn't want to wake that up from the dead.

How do I provide the URL for it? The documents didn't have any option for an url and doing `load` creates a new audio element

The reason why I need this is because I have another audio player and the waveform may be removed and re-added as the user navigates around

**Comment by katspaugh** [comment]
You need to pass a reference to the audio DOM-Element to the load method instead of the URL. This info is missing from the docs.
