### ISSUE TITLE
Looking for assistance with the MultiCanvas option

### ISSUE THREAD

**Issue by mastermalone** [katspaugh/wavesurfer.js#850]
Hello.  Currently, I am using version 1.0.10 of this script.  I am rendering large waveform patterns with it but there is a limitation on the canvas width.  I saw that there is an option for the renderer called MMultiCanvas" which looks like it could alleviate the canvas width limitation.  I tried setting this option in the WaveSurfer.init() method's param object but it seems that this breaks the script.  Any advice would be greatly appreciated.

**Comment by chrisparton1991** [comment]
Hey @mastermalone, you generally set the `renderer` parameter in the `create` method, e.g.:

```
WaveSurfer.create({
  container: '#waveform',
  renderer: 'MultiCanvas'
});
```

Here's a [CodePen](http://codepen.io/chrisparton1991/pen/XKgvgv) that shows how to use MultiCanvas. The Pen has a very low `maxCanvasWidth` for demonstration purposes. In a real-world scenario you'd want to delete that line.

Let me know how you go after looking at that example.

**Comment by mastermalone** [comment]
Thank you so much!  This will help a lot!  From the looks of the application code that I've been given to update/fix, they are using a much older version of wavesurfer.js and it does not contain the .create() method, only an .init({}).  Everything else looks to be mostly the same.  I just wish the previous developers who used this awesome tool did not tightly couple it with their own custom objects.  They assigned the values of the wavesurfer methods/properties to their own objects and executing the referenced methods throughout the code.  I now have to hunt down these references and decouple them as well as update the app to use the new version of wavesurfer.js.  Once again, thanks you!

**Comment by chrisparton1991** [comment]
Happy to help @mastermalone, I'm glad you got it working :)

**Comment by mastermalone** [comment]
Once again, thank you so much!

**Comment by Johnrobmiller** [comment]
this is outdated. `renderer` is not a valid arg for `create()`. Does anybody know the up-to-date solution?
