### ISSUE TITLE
Project syntax used and learning material to get started

### ISSUE THREAD

**Issue by harrietsCreativeDabblets** [katspaugh/wavesurfer.js#853]
I need to get some issues fixed for project of mine - specifically surrounding the behaviour of the regions plugin. 

What type of object literal syntax is used in the javascript code, as I need to read up on that a bit more in order to make my changes? Do you perhaps have some references to learning material to get me started on it?

**Comment by mspae** [comment]
http://bdcampbell.net/javascript/book/javascript_the_good_parts.pdf
