### ISSUE TITLE
How to display the waveform multiple times?

### ISSUE THREAD

**Issue by Bernardodinex** [katspaugh/wavesurfer.js#855]
Hi, I'm creating a project where mp3 files are displayed as waveform and I'm doing it with wavesurfer.js but I can't display the waveform for each audio file or display more than 1 waveform in same page.

**Comment by mspae** [comment]
You want to render multiple audio files with multiple instances of the wavesurfer.js plugin? Or do you want to want to render one audio file with multiple waveforms rendered by one instance of the wavesurfer.js plugin?

**Comment by Bernardodinex** [comment]
Yes, I want to render multiple audio files with multiple instances of the wavesurfer.js plugin. For instance like soundcloud.com.

**Comment by mspae** [comment]
Here is an example of how you could use a utility function to accomplish that without having to repeat yourself too much: http://codepen.io/mspae/pen/MbagWR

**Comment by Bernardodinex** [comment]
Yeah, cool! But I meant how to make all of this rendered waveforms to audio players.

**Comment by katspaugh** [comment]
@Bernardodinex I think you were given enough help to figure out the rest on your own. This is not a code dojo. Please use stackoverflow for this kind of questions.

**Comment by loretoparisi** [comment]
@mspae is it possibile to have one audio and link audio events to all these waveforms?
