### ISSUE TITLE
How is the position of the cursor determined

### ISSUE THREAD

**Issue by harrietsCreativeDabblets** [katspaugh/wavesurfer.js#858]
Can someone please tell me what variables controls the position of the cursor on the canvas?

I have added the regions plugin to my project, and when I have added multiple regions, it becomes difficult to control the position of the cursor by clicking different areas on the canvas. 

When one region is currently playing (looping) and I click outside of the region, I expect the cursor to move to that region, and start playing at this point. 
Also I am having trouble switching between regions, playing one after the other, by clicking within the region I want to play next. 

I would very much like to delve into the code as such to fix these issues, but I need some help figuring out how the cursor is being controlled, and whether the cursor position is tied to the position where the player will continue playing etc.

It seems that there are more than one variable controlling the cursor, the start play position and being within a region or not - and all these comes into effect resulting in a user experience that leaves much to be desired. 

I would of course appreciate any help on the matter of figuring out how it all ties together.
BR, Harriet

**Comment by katspaugh** [comment]
The inconsistency you describe sounds like a bug in the way region looping is implemented. The cursor shouldn't be controlled by anything except for the [audioprogress event](https://github.com/katspaugh/wavesurfer.js/blob/master/src/wavesurfer.js#L131-L134).

**Comment by wangzhaoming132** [comment]
Has the problem been solved?

**Comment by thijstriemstra** [comment]
No feedback regarding katspaugh comment, closing. Open a new ticket if you can reproduce this with 2.x.
