### ISSUE TITLE
Delete region using a button on the region itself

### ISSUE THREAD

**Issue by harrietsCreativeDabblets** [katspaugh/wavesurfer.js#859]
I have added a font -awesome button on a region - in order to delete the region; It looks like this:
![image](https://cloud.githubusercontent.com/assets/11888335/20138962/3bbd8a20-a68c-11e6-871f-86518275cb1f.png)
here is the code that I added to the render function in the wavesurfer.regions.js:
```	 
 /* add a delete button */
	  var deleteButton = regionEl.appendChild(document.createElement('i'));
	  deleteButton.className = 'fa fa-trash';
	  deleteButton.onclick = "wavesurfer.clearRegions();";
	  deleteButton.title = "Delete region";

	  var css = {
		display: 'block',
		float: 'right',
		padding: '3px',
		position: 'relative',
		zIndex: 10,
		cursor: 'pointer',
		cursor: 'hand',
		color: '#129fdd'
	  };
	  this.style(deleteButton, css);
```

When I look at the HTML rendered, it does not contain the onclick event; And obviously when clicked it does nothing. 
How do I get the onclick event to show in the rendered HTML first and foremost?
Second what is the propery way to get the clearRegions method do execute?

Tkx

**Comment by mspae** [comment]
Adding event listeners in javascript can be done in two ways.

* Imperatively by defining for example the property onclick (as you did). You have to assign it a function value, not a string value:
```javascript
deleteButton.onClick = function(e) {
  wavesurfer.clearRegions();
};
```

* Or, by adding an event listener (this is the preferred way):
```javascript
deleteButton.addEventListener('click', function(e) {
  wavesurfer.clearRegions();
});
```

**Comment by harrietsCreativeDabblets** [comment]
Martin thanks for your answer.
How would I delete the specific region associated to the button?

**Comment by taylorvc** [comment]
Hey @harrietsCreativeDabblets 
Not sure if you were still wondering how to delete a specific region, but I have been messing around with cutting specific regions of the waveform out and was able to clear individual ones:
```

var deleteRegion = a.appendChild(document.createElement('i'));
deleteRegion.className = "fa fa-trash";
deleteRegion.addEventListener('click', function() {
   a.remove();
});
```
