### ISSUE TITLE
WaveSurfer Hover Background

### ISSUE THREAD

**Issue by dsslimshaddy** [katspaugh/wavesurfer.js#864]
Can anyone add or explain from where to do the hover effect like in soundcloud ?
Im not talking bout hover cursor but the whole wavecolor from 0th position to hover position. 

I want to change the waveprgress color till the part where the mouse is hovered. Any Tricks ?

**Comment by katspaugh** [comment]
There's no built-in option for this, but you can hack it to change the `progressColor` parameter on hover like this:

```
wavesurfer.container.addEventListener('mouseenter', (e) => {
  wavesurfer.params.progressColor = 'red';
  wavesurfer.drawBuffer();
});

wavesurfer.container.addEventListener('mouseleave', (e) => {
  wavesurfer.params.progressColor = 'green';
  wavesurfer.drawBuffer();
});
```

**Comment by katspaugh** [comment]
Ah, now I see what you mean. From 0 to the position of the mouse, independent from the playback progress. No, we don't have this functionality.

**Comment by dsslimshaddy** [comment]
How about creating **two progressWave** 
1st The original one, 

Other One will be a different color and its "width" will change as we hover(to mouseposition)
and on mouseleave(width = 0)

is this possible ?

**Comment by katspaugh** [comment]
Yes, it's possible.
