### ISSUE TITLE
load waveform as the audio loads

### ISSUE THREAD

**Issue by theoutaboy** [katspaugh/wavesurfer.js#869]
Hi Katspaugh!

Is there a way to load in the wave form as the audio is being downloaded to the client-side? 

For example: the waveform is just a straight line, and as pieces of the audio are being downloaded, the waveform is creating the peaks, allowing the user to play music as it loads.

Thanks!

**Comment by katspaugh** [comment]
Duplicate of #488. Tl;dr: no.
