### ISSUE TITLE
How to receive wavesurfer ready event more quickly?

### ISSUE THREAD

**Issue by CheeBam** [katspaugh/wavesurfer.js#874]
Hi, Katspaugh!

Why do I have a delay between pressing play button and player readiness for playback on my remote server? `backend` : `'MediaElement'` option helps only to skip wait for rendering waves. Player starts playing approximately when loaded 70% of the track, and this delay is about 4-6 sec. The page has around 100 tracks so preloading can't helps. 
How I can increase the speed of the player availability or is it possible to make play after loading the first, for example, 30 seconds of track and then download the track completely and then allow user to interact with waveline. What I need to do?
My users can wait 2-3 seconds but not 4-6((
Also can depend time of player readiness of server computing power?

Many thanks!)

**Comment by katspaugh** [comment]
The `<audio>` tag is slower than it can be on some servers. GitHub Pages, for instance, are particularly slow to respond with audio files. When I hosted wavesurfer.js's homepage on S3, it was loading the audio significantly faster. I think it has to do with how the server is configured. Particularly, the support for HTTP/1.1 media headers is very important.
