### ISSUE TITLE
Any plan to Upgrade for Angular 2?

### ISSUE THREAD

**Issue by ibnbd** [katspaugh/wavesurfer.js#884]
Hey there, I am really fan of your work. I loved your plugin. As you know Angular chaining it's version. And I was wondering if you planning to upgrade for Angular 2? Or do you have any easy ideas so I can give a try. I am sorry I am not so expert here.

Thanks

**Comment by katspaugh** [comment]
This project is not using Angular, except for one tutorial example. If you want, you can create an example (preferably a codepen) of using wavesurfer with Angular 2. I would be happy to add it on the homepage. Please re-open this issue if you create a codepen.
