### ISSUE TITLE
The order of script tags for plugins should not be affecting initialization

### ISSUE THREAD

**Issue by katspaugh** [katspaugh/wavesurfer.js#895]
Quoting #825:

> I modified your zoom example as a codepen, to match my wavesurfer config, and at first I could not figure out why it seemed to be working on the codepen but not my site. I then realized that if I removed the regions altogether, or added them to the wavesurfer BEFORE I initialize the timeline then it works like your example. In my code, I added the regions AFTER I initialized the timeline. I am not sure if this is significant or something to note in the docs/change in the code but this seems to have fixed the problem.

> Here we see how my code was set up, regions added after the timeline, and the bug I've been describing is present.
http://codepen.io/jeremylach/pen/zoWdyo?editors=1011

Solution: either make the order of scripts idempotent or add a note in the docs.

**Comment by mspae** [comment]
Will be fixed in next version through Plugin api.

**Comment by thijstriemstra** [comment]
Should be fixed in v2.0 as noted by @mspae, closing.

**Comment by heitorb** [comment]
I have 2.0.6 and I am seeing this issue. The last comment says if should be fixed in 2.0. Did anyone actually verified this fix?
