### ISSUE TITLE
playback point

### ISSUE THREAD

**Issue by jsphweid** [katspaugh/wavesurfer.js#897]
Play/Pause begins playback from the point where it stopped, which makes sense. But is there a better way than the below plunker to start playback at a particular point (thus making it easy to listen to an exact point in time over and over). 

Go full screen for it. I know it doesn't line up when it's scrolled over and other problems. Main thing I'm trying to show is functionality (spacebar stop/restart). 
https://plnkr.co/edit/5ECTmie60FRxExXDrgNN

I tried searching to code to see if there is a better way of handling this, but I couldn't find it.

(On a semi-related note, I'd also be interested to know if, when using the regions plugin, there is an easy way to start the playback (and change this 'restart point') at the beginning of the region.)

**Comment by jsphweid** [comment]
Ok, well, after some work, I managed to do everything I want to do. I'm not sure it's the best way and if there were a more native / integrated way of doing it, I'd be interested to know. Here's the code that implements a restart point AND begins regions at the beginning upon creation (allowing only 1 region at a time).

https://plnkr.co/edit/ZrYRBZdhTnxF4cbyTJSq

**Comment by katspaugh** [comment]
Looks good! The only suggestion I can make is to keep a reference to the created region like this:

```
        var region = null;

	wavesurfer.on('region-created', function(reg) {
		if (region) region.destroy()
                region = reg;
	});
```
