### ISSUE TITLE
Waveform not rendering on hidden div.

### ISSUE THREAD

**Issue by interwap** [katspaugh/wavesurfer.js#899]
I'm using wavesurfer.js for this cool music player, awesome stuff but the waves don't render when the display of the parent div is set to none.

```
<div id="parent" style="display:none">
     <div id="waveform"></div>
</div>
```

ideally, when the page load, the player is hidden and when i click on the play button, shows. But when it does the waveform isn't rendered. Any ideas why??

**Comment by jsphweid** [comment]
So you want the div to display on a button click? Isn't that just a bit of jQuery?

`$('parent').css('display', '');`

https://plnkr.co/edit/WTkrRzkjAZ4HbB0NJMoN

Or am I missing something?

**Comment by chrisparton1991** [comment]
Elements with `display: none` don't have their dimensions calculated, so my suspicion is that wavesurfer is seeing your element as a 0px by 0px div and rendering accordingly.

I'm not sure of your exact requirements, but as a test you could try replacing `display: none` with `visibility: hidden` and changing to `visibility: visible` once the play button is clicked. The difference you'll likely notice is that the (hidden) wavesurfer element still takes up space on the page, which may or may not be desirable.

Note that you'll also want to disable the play button until wavesurfer itself has finished loading the audio file.

**Comment by interwap** [comment]
@jsphweid yes is basic jquery. I've seen your plunker but i think your audio size is small, thats why this show. try loading a larger mp3. @chrisparton1991  thanks, you really do understand issues. when the div is hidden with visibility, it renders just fine. May just be the display none config

**Comment by thijstriemstra** [comment]
So this can be closed @interwap?

**Comment by interwap** [comment]
no @thijstriemstr , the problem persists

**Comment by jsphweid** [comment]
Ok, I'm beginning to see the problem. I tried an hour long album and I saw nothing. You're right. So I made a bunch of wav files with white noise at various lengths to see which ones would render like expected. On my machine at least, a 13 minute file shows but a 14 minute file does not.

Putting a debugger on `drawBars()` I can see that even a 14 minute + file has what seems to be all the proper values flowing through. It even has, what appears to be, valid h values in `var h = Math.round(peaks[Math.floor(i * scale)] / absmax * halfH);` which is where the actual bar to bar drawing happens.

I'm a little stumped. Anyone else have ideas?

**Comment by chrisparton1991** [comment]
Sounds like you need to switch over to the `MultiCanvas` renderer. Browsers have maximum canvas size limits. Once you go past them, the browser won't render anything to the canvas. 

The MultiCanvas renderer works around this my using multiple adjacent canvases when required.

To enable, add a `renderer: 'MultiCanvas'` option to your wavesurfer config.

**Comment by chrisparton1991** [comment]
@jsphweid Your issue also sounds different to the issue @interwap had. Seems like his problem has been solved.

**Comment by shaliniidea** [comment]
[4B45C80004EF.zip](https://github.com/katspaugh/wavesurfer.js/files/1246512/4B45C80004EF.zip)
@chrisparton1991 I can hear the audio of the file but it does not generate a waveform. I also tried the `renderer : 'MultiVanvas'`opyion to my wavesurfer config.

Can you please help? Attaching the audio file here in zipped folder.

**Comment by mspae** [comment]
see issue #1197 (@shaliniidea I think this issue is unrelated to the one you reported)
