### ISSUE TITLE
Seeking errors with media element fallback

### ISSUE THREAD

**Issue by taylorvc** [katspaugh/wavesurfer.js#900]
I am using the media element fallback, since the majority of my audio files are quite large and I don't want them to be decoded with Web Audio.  However, I noticed an issue with seeking while the audio is playing. When I attempt to seek backward, the audio will update its current time to the clicked position, but the actual playhead in the waveform does not move. Sometimes if you click to seek backward a couple times, the playhead will move and update its position as normal. Again, this is only when the audio element is playing. If it is paused, the seek position updates as normal. I was able to replicate it on your fallback example, if you attempt to click back in the audio a few times while playing:
https://wavesurfer-js.org/example/audio-element/

Are there any fixes to this? I think this is just an issue with the 'MediaElement' option, because when I removed it from my init function the seeking worked fine. Without the fallback though, it takes super long to load my audio files and often crashes the browser since they are so large.

I appreciate any feedback, and also want to say that I am so impressed with this project! :) I have been trying to build my own custom in-browser editor using AudioWaveform for months and this is a tremendous help.

**Comment by katspaugh** [comment]
It's the way the media element works in browsers. It's pretty well known. There's no workaround for this.

**Comment by janjon** [comment]
@katspaugh  audio element no problem

**Comment by katspaugh** [comment]
@janjon you mean, when using a standalone `<audio>` tag – no issues with seeking?

**Comment by janjon** [comment]
@katspaugh sorry, I mean, there is no problem in using chrom native audio element regression, https://wavesurfer-js.org/example/audio-element/ regression sound accurate, schedule lines again returned back

**Comment by entonbiba** [comment]
@janjon please test it with the latest version, I implemented a fix to ensure the correct playback time is returned at all times when using MediaElement. #941

**Comment by entonbiba** [comment]
closing #941 fixes this
