### ISSUE TITLE
Playback doesn't start on iOS when load and playback are initiated by tapping a button - how to fix?

### ISSUE THREAD

**Issue by leolabs** [katspaugh/wavesurfer.js#902]
I have the following situation: I have a list of tracks that can be played. When the user clicks on one of the tracks, it is loaded into WaveSurfer and an event listener gets attached to the ready event of the player and starts the playback immediately. This works on all tested OSes except for iOS where the track is loaded by clicking on the button, but playback doesn't start. Is there a workaround to this problem yet?

**Comment by ToJen** [comment]
I'm having a similar issue. The function, `onClick` doesn't work on touchscreen devices. I'm still trying to get a way round it with `touchstart`.

**Comment by tptshoe** [comment]
Same issue here. Works everywhere but iOS.

**Comment by tptshoe** [comment]
I found a fix for this, using touchend. See this article:

http://marketdeers.com/2015/07/thoughts-about-jquerys-click-touchend/

**Comment by entonbiba** [comment]
@leolabs @ToJen @tptshoe can you provide a codepen sample that is not working in ios? Is this happening with ios 10?

@leolabs How large are the tracks?

**Comment by leolabs** [comment]
@entonbiba this example works flawless on desktop but on iOS it doesn't play the file after loading: http://codepen.io/leolabs/pen/ZLROOV

The mp3 files are not larger than 3 MB.

**Comment by entonbiba** [comment]
@leolabs here you go, now works on iphone.
http://codepen.io/entonbiba/pen/WRyxga

**Comment by leolabs** [comment]
@entonbiba thank you! 😊

**Comment by grosch** [comment]
I just went to the URL you showed last, @entonbiba and when I click on the load button nothing happens on my iOS device.
