### ISSUE TITLE
Can wavesurfer play audio in chunks like soundcloud?

### ISSUE THREAD

**Issue by interwap** [katspaugh/wavesurfer.js#905]
if you've ever tried to download music on soundcloud or tidal using idm (internet download manager), you'll discover that they tend to be serving their audio files in chunks. This make it difficult for idm to grab the file as its served in small kilobytes (250kb). I'm trying to apply the same technique on a project i'm working on but can't get it figured out just yet.

I'm using WaveSurfer to play the audio file (mp3) via a url which reads the file on the server (PHP). How do i get it to play/stream the audio file in partials/chunks

**Comment by katspaugh** [comment]
Have you tried StackOverflow?

**Comment by interwap** [comment]
Yes please similar question here: http://stackoverflow.com/questions/41385292/how-to-read-audio-file-in-chunks-like-soundcloud-php

**Comment by daslicht** [comment]
The stackoverflow post is no longer available, idea?

**Comment by entonbiba** [comment]
@daslicht @interwap  seems stackoverlow removed it for moderation issue, you may use hls to achieve this as it will send chunks based on a playlist of the actual file. 

see this comment for hls usage, continue on this ticket #1078 
https://github.com/katspaugh/wavesurfer.js/issues/1078#issuecomment-713392663
