### ISSUE TITLE
Can wavesurfer preload "webaudio" like it does "media element"?

### ISSUE THREAD

**Issue by interwap** [katspaugh/wavesurfer.js#908]
I notice that if the backend is set to webaudio, you can't play until the waveform has been drawn. Is there a workaround for this because i'll love to play before the waveform is drawn.

**Comment by katspaugh** [comment]
It depends on what you need Web Audio for. You can use the [MediaElementAudioSourceNode](https://developer.mozilla.org/en-US/docs/Web/API/MediaElementAudioSourceNode) to have access to stuff like filters.

```
const audio = new Audio(url);
audio.volume = 0;
wavesurfer.load(audio);

// do web audio stuff with the audioCtx and mediaSource
const audioCtx = new AudioContext();
const mediaSource = audioCtx.createMediaElementSource(audio);
mediaSource.connect(audioCtx.destination);
```

**Comment by interwap** [comment]
now it doesnt work...

**Comment by katspaugh** [comment]
Works for me: http://codepen.io/anon/pen/mRbqwK
(There's no sound, because of the CORS restrictions of that audio).

**Comment by interwap** [comment]
it only works when backend is mediaelement. Doesn't work using webaudio. That what i'm trying to point out...

**Comment by MileanCo** [comment]
I got this to work using MediaElement, but I get this error when calling wavesurfer.load:
`Failed to construct 'AudioContext': The number of hardware contexts provided (6) is greater than or equal to the maximum bound (6).`

From this code snippet:
```
  function _load(url, peaks) {
   let audio = new Audio(url);
   audio.crossOrigin = "anonymous";
   if (peaks) {
     self.wavesurfer.load(audio, peaks);
   } else {
     self.wavesurfer.load(audio);
   }
   const audioCtx = new (window.AudioContext || window.webkitAudioContext);
   const mediaSource = audioCtx.createMediaElementSource(audio);
   mediaSource.connect(audioCtx.destination);
  }
```
