### ISSUE TITLE
Multiple waveform instances do not generate waveform.

### ISSUE THREAD

**Issue by benbenedek** [katspaugh/wavesurfer.js#910]
Hi,

Let me start off by saying I love your lib.

Trying to implement a slider (with multiple wavesurfer instances, some are "hidden"), using wavesurefr v1.0.53. Currently the waveform is generated in the FE. The code which generates them looks like this:

``` $('.waveform').each(function(idx, item) {
    var $parentContainer = $(item.closest('.slide')),
        $smallAudioPlayButton = $parentContainer.find('.js-audio-play'),
        $bigAudioPlayButton = $parentContainer.find('.js-slider-audio-play'),
        $currentLength = $parentContainer.find('.js-audio-current-position'),
        $totalLength = $parentContainer.find('.js-audio-total-length');

    var player = wavesurfer.create({
        audioContext: ctx,
        container: item,
        waveColor: 'white',
        progressColor: '#00B22D',
        barWidth: '2',
        backend: 'MediaElement',
        height: '60'
    });

    player.load(item.getAttribute('src'));

    player.on('finish', function() {
        $smallAudioPlayButton.removeClass('fa-pause-circle');
        $smallAudioPlayButton.addClass('fa-play-circle');
        player.seekTo(0); // rewind!
    });

    player.on('audioprocess', function(currentDuration) {
        // wavesurfer bug.
        if (currentDuration < 1) {
            return;
        }
        $currentLength.text(durationToText(currentDuration));
    });

    player.on('ready', function() {
        $totalLength.text(durationToText(player.getDuration()));
    });

    m.audioPlayers.push(player);

});
```

The problem I'm facing is that the waveform for the first audio is generated, but then the rest don't, no console/js errors.

Any help / entry point to start debugging would be greatly appreciated.

Best regards & Happy new years!
Ben.

**Comment by katspaugh** [comment]
Looks like the code you posted is not complete. I don't see any loops that would create multiple waveforms. Can you post your full code on codepen.io?

**Comment by benbenedek** [comment]
Thanks for the quick response.

Sorry, left out the first line:
``` 
$('.waveform').each(function(idx, item) {
    var $parentContainer = $(item.closest('.slide')),
        $smallAudioPlayButton = $parentContainer.find('.js-audio-play'),
        $bigAudioPlayButton = $parentContainer.find('.js-slider-audio-play'),
        $currentLength = $parentContainer.find('.js-audio-current-position'),
        $totalLength = $parentContainer.find('.js-audio-total-length');

    var player = wavesurfer.create({
        audioContext: ctx,
        container: item,
        waveColor: 'white',
        progressColor: '#00B22D',
        barWidth: '2',
        backend: 'MediaElement',
        height: '60'
    });

    player.load(item.getAttribute('src'));

    player.on('finish', function() {
        $smallAudioPlayButton.removeClass('fa-pause-circle');
        $smallAudioPlayButton.addClass('fa-play-circle');
        player.seekTo(0); // rewind!
    });

    player.on('audioprocess', function(currentDuration) {
        // wavesurfer bug.
        if (currentDuration < 1) {
            return;
        }
        $currentLength.text(durationToText(currentDuration));
    });

    player.on('ready', function() {
        $totalLength.text(durationToText(player.getDuration()));
    });

    m.audioPlayers.push(player);

}); 
```

Since there is HBS and multiple components it would be a bit harder for me to get a working example. Please allow until tomorrow. 

If there's anything wrong which pops up for you in this code LMK.

Best regards,
Ben.

**Comment by chrisparton1991** [comment]
Hi Ben,

Any wavesurfer containers with `display: none` will not render. When wavesurfer gets the dimensions of the hidden container element, the browser will say it has no width and no height. Therefore, wavesurfer will render nothing.

I don't have your HTML here, so I can't say for certain that this is the case, but it was for another user who raised an issue recently.

If you are indeed hiding your elements by setting `display: none`, you can try setting `visibility: hidden` instead. This will probably exhibit undesirable behaviour, but it should tell us if this is indeed the case, and we can move forward from there.

**Comment by katspaugh** [comment]
If I were a soothsayer, I would say the `src` attribute on the container looks weird. Is it an audio element? Also, what is the `ctx` in `audioContext: ctx`? Have you tried without it?

**Comment by benbenedek** [comment]
@chrisparton1991 tried replacing the `display: none` with `visibility: hidden`, didn't help.
@katspaugh  tried without the `ctx`, didn't help.

I'm also noticing it is inconsistent, meaning, it sometime renders the waveform and sometimes doesn't.

**Comment by chrisparton1991** [comment]
Is there any chance of you making a CodePen that reproduces the issue? You could also try updating to a later version of Wavesurfer if that's possible for your project, there have been quite a few changes since v1.0.53.

**Comment by benbenedek** [comment]
Hi @chrisparton1991 @katspaugh 
Apparently as @chrisparton1991 suggested the `visibility: hidden` solution worked, and I've missed a parent container which had `display: none`. 

Thank you for your help and sorry to have wasted your time. Keep up the awesome job, this project is great!
