### ISSUE TITLE
Pass argument

### ISSUE THREAD

**Issue by csimpi** [katspaugh/wavesurfer.js#912]
Hi!

I have 2 play button with data-filename parameter.
If one button clicked, this button changes to loading button AND this script runs: 
wavesurfer.load($(this).data(filename));

I would like to get $(this) element when wavesurfer READY event fired, because i would like to change the clicked loading button pack to play button.
I can't figure out how to do that.

 
```
                var wavesurfer = WaveSurfer.create({
                    container: '.waveform',
                    barWidth: 3,
                    waveColor: '#fff',
                });
                
                
                wavesurfer.on('ready', function () {
                    console.log('Start Playing');
                    wavesurfer.play();
                    //$this.data('state','playing');
                    //$this.attr('data-state','playing');
                    //$this.find('i').addClass('fa-pause-circle');
                    //$this.find('i').removeClass('fa-spinner');
                });
                
            
            
            $('.play-audio').on('click', function(){
                var $this = $(this);
                var file = CURR_TEMPLATE_DIR+$this.data('audio-file');
                wavesurfer.load(file);
           });

```
Thanks,
Peter

**Comment by katspaugh** [comment]
Define the button as a variable:

              var button = $('.play-audio');

               button.on('click', function(){
                    var file = CURR_TEMPLATE_DIR + button.data('audio-file');
                    wavesurfer.load(file);
               });

                wavesurfer.on('ready', function () {
                    console.log('Start Playing');
                    wavesurfer.play();
                    button.data('state','playing');
                    button.attr('data-state','playing');
                    // etc
                });

Please note that this is a JavaScript question that has nothing to do with wavesurfer.js specifics. Please use StackOverflow for this kind of questions in future.

**Comment by csimpi** [comment]
Thank you! I supposed that can be a solution but i hoped there is a cleaner solution, this is a bit ugly. Thanks ,
Peter

**Comment by csimpi** [comment]
Ah, sorry but it doesn't work because i still don't know which button was clicked... 
I have 2 play button... How can i know what was the clicked? :) Please reopen the ticket.

**Comment by csimpi** [comment]
Find out.

```

            var $clickedPlayBtn;
               
            $('.play-audio').on('click', function(){
                $clickedPlayBtn = $(this);
                var file = CURR_TEMPLATE_DIR+$clickedPlayBtn.data('audio-file');
            });

            if($(".waveform").length){
                var wavesurfer = WaveSurfer.create({
                    container: '.waveform',
                    barWidth: 3,
                    waveColor: '#fff',
                    /*maxCanvasWidth:0px*/
                });
                
                
                wavesurfer.on('ready', function () {
                    console.log('Start Playing');
                    wavesurfer.play();
                    $clickedPlayBtn.data('state','playing');
                    $clickedPlayBtn.attr('data-state','playing');
                });
                
            

```
