### ISSUE TITLE
Wavesurfer not working if I open another browser such as chrome

### ISSUE THREAD

**Issue by iulianflst** [katspaugh/wavesurfer.js#913]
If I open another browser or new tab in firefox the sounds stop playing

here is an example 

Step 1: https://www.sodasi.com/product/waterfall/ 
Step 2: Open soundcloude and play something in chrome for example
step 3: go back to firefox and play again
Result: in firefox waveform is not working at all although the waveform is being generated!

**Comment by katspaugh** [comment]
For me it keeps playing (Firefox 50.1 on macOS). Sounds like something better asked in Firefox's bugtracker.

**Comment by katspaugh** [comment]
Try using `backend: 'MediaElement'`.

**Comment by iulianflst** [comment]
awesome, it works now!

Thank you!
