### ISSUE TITLE
Loading of audio file fails with: 'XHR error: ""'

### ISSUE THREAD

**Issue by apeidos** [katspaugh/wavesurfer.js#914]
We are not able to get the most simple example running:
![screen shot 2017-01-10 at 00 47 06](https://cloud.githubusercontent.com/assets/22212675/21788356/85737d56-d6ce-11e6-9adf-5e2c207eb28d.png)
Tested with:
- Safari [10.0.1]
- Chrome [55.0.2883.95]
- macOS
- several different mp3 and wav files

'audio.mp3' is a file located in the same directory as 'index.html'

This is the error we are seeing:
![screen shot 2017-01-10 at 00 50 45](https://cloud.githubusercontent.com/assets/22212675/21788484/3ad2e31c-d6cf-11e6-8bff-90e3c3cc0997.png)

Strangely, some html is inserted in the 'waveform' container element, but its width is set to 0px:
![screen shot 2017-01-10 at 00 47 18](https://cloud.githubusercontent.com/assets/22212675/21788503/5d468246-d6cf-11e6-9f39-6b23cd54ce74.png)

Is this just a blunder on our side or is this a known issue?

**Comment by chrisparton1991** [comment]
You're attempting to load a local file over XHR, which is something your browser won't allow. I suspect the Network tab might give you more information on that.

At any rate, try replacing your `audio.mp3` with `http://ia902606.us.archive.org/35/items/shortpoetry_047_librivox/song_cjrg_teasdale_64kb.mp3` for testing purposes. This is a random MP3 from the Internet Archive, which allows cross-origin requests.

Once you get it working with that URL, you can work towards getting your own audio files working. For that, you will want to run a local webserver (or a remote server with CORS enabled, depending on your requirements).

Let me know how you go.

**Comment by apeidos** [comment]
Thanks a lot for your prompt response.
It is indeed working with the remote test mp3.
However, the use case we want to implement requires us to process local files:
User selects a local mp3 file via the default file browser dialog -> we display this file as a waveform and let the user operate on it -> the user hits submit and we upload the mp3 to our server.
Maybe in the end, we'll need to build our own custom solution using WebAudio, but thanks anyway for your help :)

**Comment by chrisparton1991** [comment]
You're welcome :)

I've never done this exact thing myself; my personal project uploads local MP3s to my server and they are played back in a different place in my webapp.

Still, I think it should be possible to do what you want.

I've never used it personally, but Wavesurfer has a `loadBlob` method (see https://wavesurfer-js.org/docs/methods.html). If you can get your local MP3 into a blob using `FileReader`, Wavesurfer should be able to read it.

Alternately, you could try `FileReader.readAsDataURL()` and pass the data URL to Wavesurfer. Again, I haven't tried this so it may or may not work.

For both of the above approaches, https://www.html5rocks.com/en/tutorials/file/dndfiles/ will serve as a useful guide. Even if you choose to implement your own solution from scratch, I think you'd have to do the same thing, so it's worth trying it with Wavesurfer first :)

**Comment by apeidos** [comment]
Awesome. Thank you so much!

**Comment by chrisparton1991** [comment]
No problem, Good luck!

**Comment by melvinma** [comment]
@apeidos Could you please tell us what you did to make it work? I need to get this working too. I noticed that if backend:'MediaElement', I could playback the local audio specified in relative path, but it does not draw wav forms. Can we add this (play back local file) as an additional feature? 

Thanks!
