### ISSUE TITLE
spectrogram on large number of files

### ISSUE THREAD

**Issue by arianestolfi** [katspaugh/wavesurfer.js#917]
Hi, 
thank you for the for the work, its really great!

I'm using wavesurfer to analyze a large collection of samples for my thesis, 

I've tried to do something based on angular example
http://www.codigo.xyz/sampleplayer/example/banda/
but I couldn't bind the play button to each sample

so I've got this based on angular-material documentation
http://www.codigo.xyz/sampleplayer/
repeating multiple instances of the player instead of the sources

```
  <md-wavesurfer-audio player-wave-color="gray" player-progress-color="black"
                       player-backend="MediaElement" ng-repeat="item in longList">
    <md-wavesurfer-source src="{{item.url}}"
                          title="{{item.title}}" ></md-wavesurfer-source>
  </md-wavesurfer-audio>
```

i'ts pretty nice already, but, for academic purposes, 
I need to draw a spectrogram for each sample also
do you know if it's possible? and how should I try?

I couldn't find where can I place the 
spectrogram.init function in the wavesurfer directive
do you have any clue on where to put this function?

thank you a lot!
any help is welcome!

**Comment by arianestolfi** [comment]
Hi, if anyone is interested, I've figure it ou how to do it,
I've publhished at  
[https://github.com/arianestolfi/spectrogramplayer](https://github.com/arianestolfi/spectrogramplayer)

there's an online version on [spectro.codigo.xyz/spectrogramplayer/](http://spectro.codigo.xyz/spectrogramplayer/)

probably not the best solution, but it's working for the purpose I got, that was to print audio samples...

**Comment by 15838028035** [comment]
@arianestolfi  i have see project   https://github.com/arianestolfi/spectrogramplayer,  
 i also have memory problem
