### ISSUE TITLE
Showing playbacktime on cursor

### ISSUE THREAD

**Issue by vishagar81** [katspaugh/wavesurfer.js#920]
Hello,

First of all, thanks for writing such a wonderful library. I am interested in showing a 'running' text like a tooltip on the cursor. Is that already possible? If not, then could you guide me as to how can I do it.

Use case: showing a word that is being played based on the timing information available in another file.

**Comment by entonbiba** [comment]
Here you go, something like this will work. I'll create an example soon.
https://github.com/entonbiba/examples/blob/master/wavesurfer/mouse-tooltip-playback-time

**Comment by thijstriemstra** [comment]
not sure, @katspaugh is there a place for that?

**Comment by entonbiba** [comment]
@thijstriemstra maybe I'll add this feature to the current cursor plugin or in the examples folder

**Comment by katspaugh** [comment]
> not sure, @katspaugh is there a place for that?

The Examples page on the website.
