### ISSUE TITLE
Passing waveform data from server

### ISSUE THREAD

**Issue by deckchairuk** [katspaugh/wavesurfer.js#923]
Hello,

I am trying to setup pre-rendered peaks using the BBC audiowaveform progam. I have generated the json file using the example you provide here: https://wavesurfer-js.org/faq/

I then passed the file into my load function like so: wavesurfer.load('/assets/audio/A1.mp3', '/assets/audio/waveforms/A1.json'); but it renders very differently to how it should.

Do you have any ideas as to why this could be happening?

Thanks, Harry.

**Comment by deckchairuk** [comment]
I tried to get the peaks using this: console.log(wavesurfer.backend.getPeaks(512));

But I just get [1022: 0, 1023: 0] returned which is the incorrect format to pass back into the load function.

**Comment by deckchairuk** [comment]
Fixed - the parameters that worked (on the BBC Audio waveform program) were:

audiowaveform -i some-file.mp3 --pixels-per-second 1 -b 8 -o some-file.json

**Comment by katspaugh** [comment]
AFAIR, the second parameter is supposed to be an array, not a URL string.

**Comment by mspae** [comment]
can we close this?
