### ISSUE TITLE
How to create simple Volume Slider?? -- Gain Node -- setFilters ?? 

### ISSUE THREAD

**Issue by tweed** [katspaugh/wavesurfer.js#925]
Hi! tried many things - does anyone have an example of how to add a volume slider HTML and JS ?

I have the equalizer example working though need to add a simple master volume fader
This is the equalizer example i hope to add a volume slider to
https://wavesurfer-js.org/examples/

BIG thanks!

**Comment by entonbiba** [comment]
@tweed here you go:
http://codepen.io/entonbiba/pen/BpmdRR

**Comment by tweed** [comment]
VERY VERY much appreciated!!!  Bet it helps many of us.

**Comment by tweed** [comment]
I have enjoyed the Volume Slider - now I'm trying to find a way to modify the code from the link above to get the slider to reflect the correct position when i set DEFAULT VOLUME with this:

`wavesurfer.setVolume(0.4);`

REALLY hoping to some help with this - it's FANTASTIC to have the slider - and as i set a default volume to be much less than 100% loud - hoping to have the slider not show 100% full right position by default -

Long way of asking:

is there a way to have the slider follow the default volume I set with
`wavesurfer.setVolume(0.4);`

Sorry and thanks!!

**Comment by mspae** [comment]
Check the code for the zoom slider in the examples.

**Comment by tweed** [comment]
THANK YOU
i am looking at this part
`var slider = document.querySelector('#slider');

slider.oninput = function () {
  var zoomLevel = Number(slider.value);
  wavesurfer.zoom(zoomLevel);
};`

AND now i will try to change this part of the code i am currently using that does NOT show correct default volume in slider position - THIS is the last half of script that works, YET doesn't show default volume with slider's initial position

`
// PARTIAL CODE - VOLUME bits at bottom - THANKS!
// Bind filters to vertical range sliders
                var container = document.querySelector('#equalizer');
                filters.forEach(function (filter) {
                  var input = document.createElement('input');
                  wavesurfer.util.extend(input, {
                    type: 'range',
                    min: -40,
                    max: 40,
                    value: 0,
                    title: filter.frequency.value
                  });
                  input.style.display = 'inline-block';
                  input.setAttribute('orient', 'vertical');
                  wavesurfer.drawer.style(input, {
                    'webkitAppearance': 'slider-vertical',
                    width: '32px',
                    height: '92px'
                  });
                  container.appendChild(input);

                  var onChange = function (e) {
                    filter.gain.value = ~~e.target.value;
                  };

                  input.addEventListener('input', onChange);
                  input.addEventListener('change', onChange);
                });
          var volumeInput = document.querySelector('#volume');
          var onChangeVolume = function (e) {
            wavesurfer.setVolume(e.target.value);
            console.log(e.target.value);
          };
        volumeInput.addEventListener('input', onChangeVolume);
        volumeInput.addEventListener('change', onChangeVolume);

          // moved to here below
        wavesurfer.setVolume(0.4);


        // For debugging
        wavesurfer.filters = filters;
              });

      </script>
`

**Comment by entonbiba** [comment]
@tweed here you go, it will be available with wavesurfer.getVolume(); in the next update. For now you can use the following below:
````
wavesurfer.setVolume(0.4);
  document.querySelector('#volume').value = wavesurfer.backend.getVolume();
````

**Comment by tweed** [comment]
entonbiba !!! CRINGING to reopen on this -- me and I'm certain many others will love the getVolume feature!

I am struggling to figure out, after many mods/attempts
why the volume slider on screen in browser still shows 100% full-on instead of correct position.
Terribly sorry to ask after all the super-helpful assists
in my attempts i can of course get the volume to default to softer/lower
what i can't do is get the on-screen slider to reflect the correct level/volume - it always displays 100% full-on

        `  var volumeInput = document.querySelector('#volume');
          var onChangeVolume = function (e) {
            wavesurfer.setVolume(e.target.value);
            console.log(e.target.value);
          };
        volumeInput.addEventListener('input', onChangeVolume);
        volumeInput.addEventListener('change', onChangeVolume);

          // moved to here below
          wavesurfer.setVolume(0.4);
          document.querySelector('#volume').value = wavesurfer.getVolume();`

**Comment by tweed** [comment]
FANTASTICALLY HELPFUL!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  the last puzzle piece - GREATEST thanks

**Comment by asystemsaus** [comment]
Is it possible to do this with two channels ? 
When you split channels do they get a name or an Id i can work with.
I want to be able to change the volume of each channel seperately.

**Comment by anesask** [comment]
> document.querySelector('#volume').value = wavesurfer.getVolume();

Cannot get it... is there any code example?

Thanks in advance
