### ISSUE TITLE
partialRender with zoom = broken

### ISSUE THREAD

**Issue by Stoyvo** [katspaugh/wavesurfer.js#932]
Hey Folks,

Pulled the latest, started using partialRender and WOW big performance boost... but also not working with MultiCanvas.

![image](https://cloud.githubusercontent.com/assets/6148099/22360332/bad40294-e41c-11e6-8e64-9f57fb0bc190.png)

Notice the waveform getting "fuzzy". It's either fuzzy or a solid blank line depending on zoom level.

Config is as follows:

    var WaveSurfer = {
        defaultParams: {
            height        : 60,
            waveColor     : '#999',
            progressColor : '#555',
            cursorColor   : '#333',
            cursorWidth   : 1,
            skipLength    : 2,
            minPxPerSec   : 30,
            pixelRatio    : window.devicePixelRatio || screen.deviceXDPI / screen.logicalXDPI,
            fillParent    : true,
            scrollParent  : false,
            hideScrollbar : true,
            normalize     : true,
            audioContext  : null,
            container     : null,
            dragSelection : false,
            loopSelection : false,
            audioRate     : 1,
            interact      : true,
            splitChannels : false,
            mediaContainer: null,
            mediaControls : false,
            renderer      : 'MultiCanvas',
            backend       : 'WebAudio',
            mediaType     : 'audio',
            autoCenter    : true,
            partialRender : true,
            quickCenter   : true
        },

**Comment by Stoyvo** [comment]
Looks like "normalize" option was causing the issue.

**Comment by thijstriemstra** [comment]
@chrisparton1991 thoughts?

**Comment by Stoyvo** [comment]
Any sugguestions @thijstriemstra @chrisparton1991 ?

**Comment by thijstriemstra** [comment]
can you try to reproduce with less options? what example audio clip are you using? kinda hard to give meaningful feedback on this bug report.

**Comment by Stoyvo** [comment]
@thijstriemstra These are all the options plus some overrides. Provided an exact list to help make it easier to replicate. It happens on all files, tested with MP3. Only happens when using partial rendering. Noticed it mostly with normalize on.

**Comment by entonbiba** [comment]
@Stoyvo why exactly are you using partialRender when using MultiCanvas backend?

**Comment by Stoyvo** [comment]
@entonbiba Specifically for the performance increase while zooming and because also because there's nothing saying I shouldn't.

Either:
1) We fix the issue with the rendering
2) We add handling to restrict this as an option and fall back to the suggested/required setting

**Comment by entonbiba** [comment]
@Stoyvo the latest release 1.3.2 has a debounce feature. In the sample below you can see how it is used to fix performance issues when using the zoom feature. 
http://codepen.io/entonbiba/pen/xgmqmv 

The only problem I see is that partialRender sometimes causes the waveform to render incorrectly when using the timeline plugin. I can only replicate the following issue below while using the parameter, is that what you're getting on your end?![image](https://cloud.githubusercontent.com/assets/5193884/22947764/43c3fff8-f2ca-11e6-8891-3231c851211b.png)


 If you can provide the mp3 deatils such as size, encoding etc, or the file then we can test it further.

**Comment by Stoyvo** [comment]
@entonbiba Try this one: http://codepen.io/anon/pen/PWLZNM

If the dropbox file does not work, I have attached a file that replicates this issue with partial renderer. 
[6265853_Get_Me_Outta_Here_feat__Flux_Pavilion_Shaun_Frank_Remix.zip](https://github.com/katspaugh/wavesurfer.js/files/775921/6265853_Get_Me_Outta_Here_feat__Flux_Pavilion_Shaun_Frank_Remix.zip)

**Comment by Stoyvo** [comment]
Interesting find: If you zoom in,  press play, it will start to replicate the issue. Leave the track playing, switch tabs, wait a few seconds, then go back to the example tab, the rendering will be correct for the X amount of seconds you were off-tab.

**Comment by Stoyvo** [comment]
Can confirm the issue also exists when using:
renderer : 'Canvas'

If I disable normalize (normalize: false) then the issue isn't so bad, but it is clearly distorted:
![image](https://cloud.githubusercontent.com/assets/6148099/22960696/e51de614-f30d-11e6-85f3-9ef4df73743a.png)

**Comment by Stoyvo** [comment]
@entonbiba @thijstriemstra @chrisparton1991 Any insight to what's being experienced here?

**Comment by entonbiba** [comment]
@Stoyvo can you try it with version 1.3.7? The example is still using 1.3.1 which doesn't have the debounce feature, also the file is missing from dropbox it's giving 404 error.

**Comment by thijstriemstra** [comment]
Closing, switch to v2. If the bug is still in v2, open a new issue, thanks.
