### ISSUE TITLE
getPlaybackRate() method

### ISSUE THREAD

**Issue by MartinDelille** [katspaugh/wavesurfer.js#934]
There is a `setPlaybackRate()` but no `getPlaybackRate()` method for the `WaveSurfer` object.

Would it be possible to add it?

**Comment by entonbiba** [comment]
You can get it directly by calling the following, I'll add a pull request for the method.
`wavesurfer.backend.playbackRate`

**Comment by MartinDelille** [comment]
Thanks! I just did the PR

**Comment by entonbiba** [comment]
here is the webaudio.js updated,

https://github.com/katspaugh/wavesurfer.js/compare/master...entonbiba:patch-1

**Comment by entonbiba** [comment]
you may close this issue as it's fixed with #939 #936

**Comment by thijstriemstra** [comment]
@entonbiba can you also add this to the documentation (in `gh-pages` branch), e.g. https://wavesurfer-js.org/docs/methods.html?

**Comment by entonbiba** [comment]
@thijstriemstra updated #940

**Comment by thijstriemstra** [comment]
thx!
