### ISSUE TITLE
empty + redrawBuffer breaks player with pre-rendered peaks

### ISSUE THREAD

**Issue by omerts** [katspaugh/wavesurfer.js#943]
Hey,

We have a player we pre-rendered peaks. 
We have bounded to the window's resize method, and onresize call:
```javascript
wavesurfer.empty()
wavesurfer.redrawBuffer()
```
This works fine after play has been clicked (aka wavesurfer.play()).
The problem is before play has been clicked, if the window has been resized, it breaks the player, and it doesn't play once play is clicked.

Here is a reproduction example:
http://codepen.io/omerts/pen/EZbBZw

Click break -> play, will not work
Click play -> break, will work

Omer

**Comment by entonbiba** [comment]
@omerts here you go, a working example.
http://codepen.io/entonbiba/pen/VPqvME

**Comment by mspae** [comment]
Still an issue?

**Comment by entonbiba** [comment]
don't think, works fine in the example

**Comment by mspae** [comment]
Ok. I'll close this for now then.
