### ISSUE TITLE
Uncaught TypeError: Cannot read property 'canvas' of undefined

### ISSUE THREAD

**Issue by joelpresence** [katspaugh/wavesurfer.js#947]
We have been using waversurferjs to great success (thanks for this awesome library!).  :-)  However, it suddenly stopped working and we have no idea why.  There were no code changes on our end.  It works when run locally on my laptop, but when I deploy to Heroku, we get the error:

```
vendor-ce0b1d3….js:21 Uncaught TypeError: Cannot read property 'canvas' of undefined
    at Object.updateDimensions (vendor-ce0b1d3….js:21)
    at Object.updateSize (vendor-ce0b1d3….js:21)
    at Object.setWidth (vendor-ce0b1d3….js:21)
    at Object.drawPeaks (vendor-ce0b1d3….js:21)
    at Object.drawBuffer (vendor-ce0b1d3….js:20)
    at Object.loadDecodedBuffer (vendor-ce0b1d3….js:20)
    at Object.<anonymous> (vendor-ce0b1d3….js:20)
    at Object.<anonymous> (vendor-ce0b1d3….js:20)
    at Object.<anonymous> (vendor-ce0b1d3….js:20)
updateDimensions @ vendor-ce0b1d3….js:21
updateSize @ vendor-ce0b1d3….js:21
setWidth @ vendor-ce0b1d3….js:21
drawPeaks @ vendor-ce0b1d3….js:21
drawBuffer @ vendor-ce0b1d3….js:20
loadDecodedBuffer @ vendor-ce0b1d3….js:20
(anonymous) @ vendor-ce0b1d3….js:20
(anonymous) @ vendor-ce0b1d3….js:20
(anonymous) @ vendor-ce0b1d3….js:20
```

This was working on Heroku last week, and it just stopped working, with no code changes on our our end.  However, it still works on our local laptops, it's only busted when wavesurfer is running inside our Ember app deployed to heroku.  waversurfer inside our Ember app deployed to my local laptop works fine.

I have no idea how to debug this ... the div it's supposed to render into is definitely there.  Any ideas?

Any help would be hugely appreciated!

Thanks.  :-)

**Comment by thijstriemstra** [comment]
@joelpresence did you upgrade wavesurfer.js? What version are you using?

**Comment by joelpresence** [comment]
Thanks @thijstriemstra .  We are using version 1.2.7.

Any ideas?

**Comment by thijstriemstra** [comment]
is it maybe something with https?

**Comment by joelpresence** [comment]
And I just checked the URL that we are giving to wavesurfer - it loads just fine in wavesurfer and I plays independently in other players or in a raw browser window.  It seems to be something with the rendering of peaks on the canvas.  Is there any way for me to test that (turn of wavesurfer rendering and just have playback) to try and narrow it down?  https - maybe, why do you ask?  :-)  Thanks again for all of your help!

**Comment by thijstriemstra** [comment]
well, the microphone uses getUserMedia which requires https (or localhost), perhaps canvas/pixel manipulation also requires it nowadays, i don't know. Since this is an application issue (most likely Ember) I'm not sure there's much we can do.

**Comment by joelpresence** [comment]
I just tried both http and https and it fails for both.  We haven't changed our version of Ember or our version of wavesurfer ... Is there any way to test wavesurfer with all use of canvas turned off?  Can you give me some tips where to look and see what's going on with the canvas?  I'm willing to post rendered html if that helps and write up a summary for a wiki if I learn something debugging this.  :-)  Really appreciate your help!

**Comment by thijstriemstra** [comment]
I would make sure your system uses unminified versions of libraries like wavesurfer.js so it's easy to see where in wavesurfer.js code the error get's thrown. Place breakpoints and console.log's in that area and try again.

**Comment by joelpresence** [comment]
Thanks @thijstriemstra .  How can I make sure that our system uses unminified versions of libraries like wavesurfer.js?  I'm not a very experienced JS or Ember dev so any tips are gratefully accepted.  We are using ember-browserify to import wavesurfer as "npm:wavesurfer" since wavesurfer isn't in Ember Observer as a cli dep.

**Comment by thijstriemstra** [comment]
Check the ember-browserify docs mate :)

**Comment by joelpresence** [comment]
OK, I rolled back to a much older version of our code that seems to work on Heroku, so I will try to binary search to find what broke things.

**Comment by thijstriemstra** [comment]
does #945 fix it?
