### ISSUE TITLE
Add a comment to Waveform

### ISSUE THREAD

**Issue by deckchairuk** [katspaugh/wavesurfer.js#948]
Hey there,

I'm looking to build something that would allow commenting on wave forms on a similar fashion to Soundcloud.

I was wondering if there's a method that would let me get the position the user clicks on a waveform/render a marker on page load of this position?

Thanks, Harry.

**Comment by deckchairuk** [comment]
Have got the click position using the seek event.

Problem I'm having now is it fires 2 seek events so when I add the comment on seek it prompts the user twice.

**Comment by deckchairuk** [comment]
I've decided to instead go with the comment added just applies to the current position of the song as I can just use the getCurrentTime method.

I now want to add the timestamp to the comments, and when users click the time stamp it seeks to that point in the track. The problem is getCurrentTime returns seconds and the seek method uses the progress from 0 - 1.

Do I have to do (timePlayed / songLength)*100) or is there a better way to do this?

**Comment by entonbiba** [comment]
@deckchairuk are you trying to get the time as in 00:00 ? 

You can do the following:
````
function timeformat(timeget) {
    if (!timeget) {return "00:00";}

    var min = Math.floor(timeget / 60);
    var sec = Math.ceil(timeget) % 60;

    return (min < 10 ? '0' : '') + min + ":" + (sec < 10 ? '0' : '') + sec;
};
timeformat(wavesurfer.getCurrentTime());
````

Here is an example I created that sets the current time played as a tooltip to the cursor.
http://codepen.io/entonbiba/pen/KaymLp

**Comment by entonbiba** [comment]
@deckchairuk regarding the comments part, maybe we can add it as plugin

**Comment by thijstriemstra** [comment]
No feedback on question, closing.
