### ISSUE TITLE
wavesurfer destroy method errors on firefox 31.7

### ISSUE THREAD

**Issue by chadkoepf** [katspaugh/wavesurfer.js#949]
we recently upgraded to wavesurfer 1.3 through npm, and it seems now that the destroy method throws an error "this.ac.close is not a function" when using this ADMITTEDLY extremely old version of firefox.

**Comment by mspae** [comment]
What version of firefox is it?

**Comment by chadkoepf** [comment]
31.7

**Comment by chadkoepf** [comment]
I tried just emptying the div element that the wav resides in.  this fixes the issue in firefox, but then in chrome I reach the max audio context (6) message after opening multiple audio files.  I'd rather not have to check for browser and version and do different things based on that, so I'm hoping someone has an idea of what's going on with the audiocontext, and why firefox doesn't wanna close it

**Comment by entonbiba** [comment]
@chadkoepf you can do something like this `wavesurfer.backend.ac.close()`. It won't work in IE, only chrome and firefox.

It's the equivalent to AudioContext.close(). The reason you're getting that error is because you're creating more than the allowed AudioContext chrome can handle.

**Comment by mspae** [comment]
https://github.com/katspaugh/wavesurfer.js/pull/862 related?

**Comment by chadkoepf** [comment]
The problem is with firefox.  it works fine in chrome and chrome is the only one with the audiocontext max message.  when I do wavesurfer.destroy() everything works fine in chrome, it's the old version of firefox I have to support that causes the error.  My option is to just empty the div instead of destroying the ac which makes it work fine in firefox.  I don't want to check for browser versions and write different code. 

.backend.ac.close() is undefined according to firefox, which is the same issue as .ac.close()

**Comment by entonbiba** [comment]
@mspae yes,

@chadkoepf ac.close() is not available in that version of FireFox. It was available in version 40.
https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/close 
![image](https://cloud.githubusercontent.com/assets/5193884/22555354/748cc02c-e931-11e6-928b-dee395d9e9a7.png)

**Comment by chadkoepf** [comment]
it looks like #862 is closing the ac in the destroy() method, which might explain why it stopped working all of a sudden.  firefox says .ac.close() is undefined.  Perhaps it's understood by newer browsers, but needs do be instantiated differently to work with older browsers?

**Comment by chadkoepf** [comment]
so is there  a workaround to manually close the ac in firefox that would also be understood by modern browsers?

**Comment by entonbiba** [comment]
@chadkoepf for older versions of FireFox check if ac.close is undefined and just empty the div.
For modern browsers it will work, meaning chrome 43+ and firefox 40+ for now.
