### ISSUE TITLE
Minimap draws flat waveform due to old calls to getPeaks and drawPeaks

### ISSUE THREAD

**Issue by dmongrel** [katspaugh/wavesurfer.js#951]
The minimap plugin is making calls to old versions of getPeaks and drawPeaks (without start/end values).

I am not setup to have you do a pull request, but it appears the following lines fix the issue in the render() function (original lines commented):

<code>
 render: function () {

        var len = this.getWidth();

        // var peaks = this.wavesurfer.backend.getPeaks(len);

        // this.drawPeaks(peaks, len);

        var peaks = this.wavesurfer.backend.getPeaks(len, 0, len);

        this.drawPeaks(peaks, len, 0, len);
</code>

**Comment by thijstriemstra** [comment]
@dmongrel can you make a pull request? If you have a github account you can make a PR (even using the browser editor).

**Comment by dmongrel** [comment]
@thijstriemstra Thanks for letting me know about this quick editing method of providing fixes.  Still haven't learned everything about GitHub yet.  I created a pull request, hopefully I did it right.

**Comment by dmongrel** [comment]
Fixed in PR #959
