### ISSUE TITLE
How can I play one song and have 2 waveforms in sync? & safari render issue

### ISSUE THREAD

**Issue by matt3224** [katspaugh/wavesurfer.js#952]
In an app i'm making I need to show the waveform twice in separate pieces of ui. These would need to be in sync, is this possible? I see you allow split channels which is close to what i want but in my case it would be a straight duplicate.

Thanks,

**Comment by entonbiba** [comment]
@matt3224 It's possible, check out the minimap plugin. Essentially it would do the same thing, I'll try to put a sample together in a few days for this.

**Comment by TrevorHinesley** [comment]
@entonbiba any update on this? Would love to see a possible example.

**Comment by entonbiba** [comment]
@matt3224 this is the link to the sample, have a look at that first.
http://codepen.io/entonbiba/pen/ggeGyG

**Comment by matt3224** [comment]
Thanks @entonbiba that looks like it will work! Not working in Safari though.. yet, any ideas?

**Comment by entonbiba** [comment]
@matt3224 you using the latest safari version or technical preview?

**Comment by matt3224** [comment]
Latest Stable `Version 10.1 (12603.1.30.0.34)`

**Comment by entonbiba** [comment]
@matt3224 when you get a change may you try with Safari TP if possible? Also can you screenshot of what is not working?

**Comment by matt3224** [comment]
@entonbiba Yeah sure this is what I see after I click play:

![screen shot 2017-05-14 at 3 47 42 pm](https://cloud.githubusercontent.com/assets/2401925/26034951/c4a6af70-38bc-11e7-96e8-c71ea8633576.png)

It will just stay like this and play no sound, however works perfectly in Chrome.

Just checked in TP too where it also does not work unfortunately.

**Comment by entonbiba** [comment]
@matt3224 hmm, and the dev console doesn't return any errors or warnings in safari?

**Comment by matt3224** [comment]
@entonbiba nope absolutely nothing, it's like it's just dead. Even in the dev tools timelines the only thing that happens is that the button being pressed in causes a repaint of that button. No js runs though, weird

**Comment by entonbiba** [comment]
@matt3224 I'll test it today on the mac and see what is happening.

**Comment by entonbiba** [comment]
@matt3224 I found that the buffer length is returning undefined in safari for the getPeaks method. I'll see what can be done to fix it for safari.

**Comment by entonbiba** [comment]
@matt3224 ok it should be fixed with my pr #1096
