### ISSUE TITLE
Waveform with rounded bars

### ISSUE THREAD

**Issue by matt3224** [katspaugh/wavesurfer.js#953]
![screen shot 2017-02-01 at 13 47 44](https://cloud.githubusercontent.com/assets/2401925/22509237/11beb6aa-e885-11e6-8f01-fc21f67abb90.png)

Hey, I'm working on a project and the design for the waveform is fairly custom, each bar having border-radius/rounded ends and the gaps being larger than that of the demo's.

How would I go about doing this?

Thanks,

**Comment by entonbiba** [comment]
@matt3224 something like this?

I'll have to implement this enhancement code with the current WaveSurfer library. 

Preview:
http://codepen.io/entonbiba/pen/vgRZwa

Current:
![image](https://cloud.githubusercontent.com/assets/5193884/22534667/8c67951e-e8c3-11e6-89a7-cbcd9c73c109.png)

With barRadius parameter (to be added via pull request)
![image](https://cloud.githubusercontent.com/assets/5193884/22535093/af1f461c-e8c6-11e6-9351-89b3b58c3cf1.png)

**Comment by matt3224** [comment]
Hey @entonbiba thanks for that. I had a little play, http://codepen.io/matt3224/pen/RKMJdp

It looks as though the barWidth property is not behaving correctly now, also is the radius making it truly rounded? It's hard to tell.

Looks good so far though, really appreciate the help!

**Comment by entonbiba** [comment]
@matt3224 I'll see what else can be done to be make look smoother when the barWidth is larger. However if you make it 7 it should be fine.

http://codepen.io/anon/pen/BprqMm

**Comment by matt3224** [comment]
Do you find that setting the bar width makes the gap bigger but not the bar?

**Comment by entonbiba** [comment]
@matt3224 if I set it to 3 it looks nice, you want the bar a bit bigger when using the radius though right?
http://codepen.io/anon/pen/BprqMm

**Comment by matt3224** [comment]
Yeah, I mean I would imagine you could control it much like you would in css, using width, margin and border-radius. That way I could have any width bar with any gap size with either a rounded or flat ends. That would make it very versatile indeed.

Thanks again!

**Comment by entonbiba** [comment]
@matt3224 yea I've made it so if the barRadius parameter is not set, it would result in flat ends. Also you can do something like `barRadius: 5` which would set the radius manually. 

http://codepen.io/entonbiba/pen/xgzOqx?editors=0010
![image](https://cloud.githubusercontent.com/assets/5193884/22621564/904e46cc-eaf4-11e6-81b1-3e96f9559a2f.png)

**Comment by Agshealth-Raj** [comment]
hi please help me,, i cannot access mp3 file from FTP server..

**Comment by Agshealth-Raj** [comment]
"wavesurfer is not defined" i got this issue while click play button in my code.. please help me..

**Comment by entonbiba** [comment]
@Agshealth-Raj is the click button within a wavesufer ready event?

**Comment by matt3224** [comment]
Hey, its been a whole year since I first queried this enhancement. The project I needed this for did go to development and i've been working on it for a few months. With v2 and all I wondered if this was implemented. I really could do with having this functionality. Thanks!

**Comment by bradley-varol** [comment]
I'd also really like this as a feature.

**Comment by matt3224** [comment]
I still also need this feature

**Comment by matt3224** [comment]
@entonbiba is there anything you can do/suggest or perhaps could you let me know what you did to achieve this before?

**Comment by delgiudices** [comment]
Yeah this would be super useful

**Comment by thijstriemstra** [comment]
if you copy/paste the `roundRect` method below in `src/drawer.canvasentry.js`:

```javascript
/**
 * Draws a rounded rectangle using the current state of the canvas.
 * If you omit the last three params, it will draw a rectangle
 * outline with a 5 pixel border radius
 * @param {CanvasRenderingContext2D} ctx
 * @param {Number} x The top left x coordinate
 * @param {Number} y The top left y coordinate
 * @param {Number} width The width of the rectangle
 * @param {Number} height The height of the rectangle
 * @param {Number} [radius = 5] The corner radius; It can also be an object 
 *                 to specify different radii for corners
 * @param {Number} [radius.tl = 0] Top left
 * @param {Number} [radius.tr = 0] Top right
 * @param {Number} [radius.br = 0] Bottom right
 * @param {Number} [radius.bl = 0] Bottom left
 * @param {Boolean} [fill = false] Whether to fill the rectangle.
 * @param {Boolean} [stroke = true] Whether to stroke the rectangle.
 */
const roundRect = function(ctx, x, y, width, height, radius, fill, stroke) {
  if (typeof stroke == 'undefined') {
    stroke = true;
  }
  if (typeof radius === 'undefined') {
    radius = 5;
  }
  if (typeof radius === 'number') {
    radius = {tl: radius, tr: radius, br: radius, bl: radius};
  } else {
    var defaultRadius = {tl: 0, tr: 0, br: 0, bl: 0};
    for (var side in defaultRadius) {
      radius[side] = radius[side] || defaultRadius[side];
    }
  }
  ctx.beginPath();
  ctx.moveTo(x + radius.tl, y);
  ctx.lineTo(x + width - radius.tr, y);
  ctx.quadraticCurveTo(x + width, y, x + width, y + radius.tr);
  ctx.lineTo(x + width, y + height - radius.br);
  ctx.quadraticCurveTo(x + width, y + height, x + width - radius.br, y + height);
  ctx.lineTo(x + radius.bl, y + height);
  ctx.quadraticCurveTo(x, y + height, x, y + height - radius.bl);
  ctx.lineTo(x, y + radius.tl);
  ctx.quadraticCurveTo(x, y, x + radius.tl, y);
  ctx.closePath();
  if (fill) {
    ctx.fill();
  }
  if (stroke) {
    ctx.stroke();
  }

}
```

And in the `fillRectToContext` method of `CanvasEntry` change:

```javascript
ctx.fillRect(x, y, width, height);
```

to 

```javascript
let radius = 3;
roundRect(ctx, x, y, width, height, radius, true, false);
```

it will render with rounded corners but for some reason only the first half is correct as shown in screenshot below. Anybody an idea?

![Screenshot from 2019-07-10 23-11-00](https://user-images.githubusercontent.com/305679/61005195-0bb75000-a368-11e9-9df9-7b8ba603d5fe.png)

**Comment by kubk** [comment]
@thijstriemstra Hi, thank you. I found a workaround for the problem:
```diff
    fillRectToContext(ctx, x, y, width, height) {
        if (!ctx) {
            return;
        }
+        if (height < 0) {
+            height = Math.abs(height);
+            y -= height;
+        }
        const cornerRadius = 5;
        this.roundRect(ctx, x, y, width, height, cornerRadius, true, false);
    }
```
It is strange, but in some cases height is negative which affects calculating of border radius.

**Comment by thijstriemstra** [comment]
awesome, sounds good @kubk!

**Comment by Rijk** [comment]
Can this be merged in the library?

**Comment by thijstriemstra** [comment]
@Rijk can you make a pull request so it can be merged?

**Comment by Rijk** [comment]
Sorry, thought this was an open PR.

**Comment by kubk** [comment]
@Rijk @thijstriemstra Will create a PR in the next few days with these changes: https://github.com/katspaugh/wavesurfer.js/issues/953#issuecomment-517068622
