### ISSUE TITLE
mediaSession plugin

### ISSUE THREAD

**Issue by thijstriemstra** [katspaugh/wavesurfer.js#957]
"With the brand new Media Session API, you can now customize media notifications by providing metadata for the media your web app is playing. It also allows you to handle media related events such as seeking or track changing which may come from notifications or media keys."

See https://developers.google.com/web/updates/2017/02/media-session

Basically I want to be able to control a wavesurfer.js player from a notification on my phone.

![screenshot](https://developers.google.com/web/updates/images/2017/02/tldr.png)

**Comment by entonbiba** [comment]
@thijstriemstra awesome I'll have a go at it with this API

**Comment by thijstriemstra** [comment]
Looks like it'll be available in a stable Android Chrome in March. "The Media Session API is supported in Chrome 57 (beta in February 2017, stable in March 2017)."

**Comment by entonbiba** [comment]
@thijstriemstra you can download the beta from here on android device.
https://www.google.com/intl/en/chrome/browser/beta.html

**Comment by thijstriemstra** [comment]
thanks @entonbiba. A friend also mentioned you can use dev tools in chrome on the desktop to simulate/connect a mobile device on the chrome beta.

**Comment by entonbiba** [comment]
@thijstriemstra yes, but you still need an android to test the media session api for now. You can also use ripple emulator or download an android emulator on desktop.

**Comment by entonbiba** [comment]
@thijstriemstra ok it's ready, now just needs testing on mobile devices once the API is available on android, iphone and windows.
https://github.com/entonbiba/Media-Session-API-wavesurfer-js

**Comment by thijstriemstra** [comment]
@entonbiba awesome. Now if we could wrap it in a plugin.. but I assume you want to test on android first.

**Comment by entonbiba** [comment]
@thijstriemstra yea I want it to be supported in at least 2 browsers before creating the plugin. Microsoft Edge browser has the status as under construction.
![image](https://cloud.githubusercontent.com/assets/5193884/22620897/fe0cf96c-eae3-11e6-97ac-0bb8e2cb07c1.png)

**Comment by thijstriemstra** [comment]
@entonbiba I took a stab at a plugin, see https://github.com/thijstriemstra/wavesurfer.js/tree/media-session-plugin

I couldn't get it to work though, see https://collab-project.github.io/videojs-wavesurfer/test/media-session.html for example.

Also couldn't get your example to work, uploaded it here: https://collab-project.github.io/videojs-wavesurfer/test/session-test.html

But the official example does work on my device: https://googlechrome.github.io/samples/media-session/audio.html

Any idea @entonbiba? Are you sure it works with webaudio, the official example uses an `<audio>` element..

**Comment by thijstriemstra** [comment]
Ah, found it on the [blog](https://developers.google.com/web/updates/2017/02/media-session#implementation_notes):

"As the Web Audio API doesn't request Android Audio Focus for historical reasons, the only way to make it work with the Media Session API is to hook up an <audio> element as the input source to the Web Audio API. Hopefully, the proposed [Web AudioFocus API](https://wicg.github.io/audio-focus/explainer.html) will improve the situation in the near future."

So, the way I'm reading that: without audio element no media session api? How did you manage to get it work @entonbiba?

**Comment by thijstriemstra** [comment]
With the MediaElement backend it works!

**Comment by entonbiba** [comment]
@thijstriemstra no it will work with web audio once stable is released, all it's doing is checking for a valid event in the mediaSesion namespace. At the moment yea the audio tag is required, we might be able to trick it with some timeout and blank audio file in the audio tag. ;) 

I'm currently testing it on windows phone with a beta version of edge.

**Comment by thijstriemstra** [comment]
"At the moment yea the audio tag is required" but your example doesn't have an audio element? And do you have a link to back up "no it will work with web audio once stable is released" because i can't find any..

**Comment by thijstriemstra** [comment]
Opened PR #996 for a plugin that adds simple play/pause and seek forward/backward controls + title and artwork. We can always add playlist support later (in the playlist example perhaps).

**Comment by entonbiba** [comment]
@thijstriemstra currently audio tag is required, I added a 5.5 min audio file and muted it in my example.

It will support web audio and you can check the commit here,
https://github.com/WICG/mediasession/commit/e62c0d5e5a613e86bc9080a4bb985ec08a698049

**Comment by thijstriemstra** [comment]
@entonbiba that's awesome, thanks for the feedback! For now the example requires the `MediaElement` backend but that can be dropped once it's supported in a Chrome version (without having to change the plugin).

**Comment by rowild** [comment]
The 2.0.1 release does not generate a mediasession.min.js on
```
npm run start:plugins
```
I did "npm install" and then "npm run start:plugins". Did I forget something? Or miss something during my research? Thanks for your help and tips!
 
![screen shot 2018-01-02 at 00 38 36](https://user-images.githubusercontent.com/213803/34471910-53467fe0-ef55-11e7-975c-1e156e19e3b2.png)

**Comment by thijstriemstra** [comment]
> The 2.0.1 release does not generate a mediasession.min.js

See https://github.com/katspaugh/wavesurfer.js/issues/1286 for the ticket for this issue.
