### ISSUE TITLE
WebAudio - Incorrect duration, length, and sampleRate

### ISSUE THREAD

**Issue by Stoyvo** [katspaugh/wavesurfer.js#958]
Hello,

Not sure if this is a WebAudio issue or with wavesurfer, maybe both. Walk through these steps. Audacity is required (for my tests at least, my file will be provided).

1) Download tests.zip:  [tests.zip](https://github.com/katspaugh/wavesurfer.js/files/749534/tests.zip)
2) Extract tests.zip
3) Load track 1
4) inspect wavesurfer.backend.source.buffer, notice duration, length, sampleRate
5) Load track 2
6) inspect wavesurfer.backend.source.buffer, notice duration, length, sampleRate

Result:
- Both tracks are the same in duration, length, and sampleRate.
- SampleRate should be 44100, not 44800

Fallback check:
- Open Audacity and compare the two files. The 2nd file will have first beat at 1.9 seconds, 1st file has first beat at 1.4 seconds.

The difference here is detrimental when loading data from external sources and regions being marked ~0.5 seconds off.

Any insight to the issue is appreciated.

**Comment by thijstriemstra** [comment]
Can you try to reproduce this with pure webaudio code?

**Comment by Stoyvo** [comment]
I have made a bug report here: https://bugs.chromium.org/p/chromium/issues/detail?id=689334

With the issue standing, the use of regions are rendered as useless :( Thankfully it works on firefox?

**Comment by thijstriemstra** [comment]
Is it better on OSX or Linux?

**Comment by Stoyvo** [comment]
I have only tried Windows 10 + Chrome 56.

**Comment by thijstriemstra** [comment]
Closing, can't fix.
