### ISSUE TITLE
Microphone Plugin - Please add an audioprocess event

### ISSUE THREAD

**Issue by leonardorame** [katspaugh/wavesurfer.js#965]
It would be really nice to monitor the position in time passed since recording started, somethin like the audioprocess event of WaveSurfer, but for the microphone plugin.

**Comment by thijstriemstra** [comment]
Wait, 'recording started'? When does it record? can you make a PR?

**Comment by leonardorame** [comment]
Well, I'm talking about the microphone plugin. Should I say when the microphone started playing?.

I cannot make a PR, because I don't know the code, but I think this should be pretty simple for you.

**Comment by thijstriemstra** [comment]
I guess you mean as soon as the visualization starts, you want to receive an event continuously, until the visualization is stopped. I could add this but I'm not sure if it's worth the overhead to send an event every time, I think it would decrease performance. What you could do is trigger the event yourself by redefining the `reloadBuffer` function that now looks like this:

```javascript
    /**
     * Redraw the waveform.
     */
    reloadBuffer: function(event) {
        if (!this.paused) {
            this.wavesurfer.empty();
            this.wavesurfer.loadDecodedBuffer(event.inputBuffer);
        }
    },
```

You can redefine it by doing something like:

```javascript
var microphone = Object.create(WaveSurfer.Microphone);
    microphone.init({
        wavesurfer: wavesurfer
});
microphone.reloadBuffer = function(event) {
    if (!this.paused) {
            this.wavesurfer.empty();
            this.wavesurfer.loadDecodedBuffer(event.inputBuffer);
            // XXX: this is where you want to trigger the event.
            this.trigger('myEvent');
        }
};

microphone.on('myEvent', function() {
        console.info('reloaded buffer');
});

microphone.start();
```

@leonardorame let me know if this works for you.

**Comment by leonardorame** [comment]
Great!, I'll try it.
