### ISSUE TITLE
Bad zooming performance when using timeline plugin

### ISSUE THREAD

**Issue by GianlucaCal** [katspaugh/wavesurfer.js#967]
Hi,

I'm experiencing some problems with huge audio files (I'm talking about a 24 hours mp3s, 256kbit/s with a sample rate of 48000 Hz ).
I'm able to visualize the whole waveform with prerendered peaks generated server-side but there are several other major problems:

-the timeline is messed up and impossible to read

-as soon as I zoom-in the browser collapse and the process of zoom-in is insanely slow

-chrome can at least visualize the waveform, firefox cant and crashes

The initial situation on chrome is like this:

![cattura](https://cloud.githubusercontent.com/assets/24889920/22644526/489891b4-ec63-11e6-981f-0a07635ce48f.PNG)

My wavesurfer options are these:
```
wavesurfer.init({
        container: document.querySelector('#waveform'),
        height: 120,
        waveColor: '#A8DBA8',
        progressColor: '#3B8686',
        backend: 'MediaElement',
        normalize: true,
        renderer: 'MultiCanvas',
        dragSelection: true,
        minPxPerSec: 10,
        partialRender : true,
        pixelRatio:  1

    });
```

So I was wonder if wavesurfer can handle such big files.

Also I know I have some problem with the zoom options; even with shorter files (30 min) the zoom is particularly slow and doesnt go back to the initial waveform.
I wouldnt know where to start in order to fix these problems.

Hope someone could help me out

**Comment by katspaugh** [comment]
Have you tried with the new `partialRender` parameter from #909?

**Comment by GianlucaCal** [comment]
yes it's in my wavesurfer options

**Comment by katspaugh** [comment]
Ah, true, sorry 😅

**Comment by mspae** [comment]
@katspaugh maybe we can debounce the zoom callback for some quick perf optim

**Comment by katspaugh** [comment]
Debouncing should probably be on the app side, wrapping the slider UI event.

**Comment by GianlucaCal** [comment]
how can I accomplish this?

**Comment by katspaugh** [comment]
Libraries like underscore.js or lodash.js have a debounce function.

Assuming your code looks like this:
```
    slider.addEventListener('input', function () {
        wavesurfer.zoom(Number(this.value));
    });
```

You need to turn it into
```
    slider.addEventListener('input', _.debounce(function () {
        wavesurfer.zoom(Number(this.value));
    }, 30)); // run not more often than once in 30 ms
```

**Comment by GianlucaCal** [comment]
My code looks exactly like the one you showed but still the fix doesnt work, I mean now Chrome doesnt crash anymore when I zoom, but the zoom slider is not usable, it takes pretty much 1 minute to move the slider...In relation to that I have a question: does the zoom recalulate the peaks everytime I use it even if I have pre-rendered peaks?

**Comment by GianlucaCal** [comment]
I found out that the problem is not the zoom which works just fine even with huge files! But it's the timeline plugin used in conjuction with the zoom, it has to recalculate all time values...is there an easy fix to it?

**Comment by entonbiba** [comment]
@GianlucaCal I implemented a debounce feature in wavesurfer. It's now available with the wavesurfer.js library built in.

You may use it like this, notice the `wavesurfer.util.debounce(FUNCTIONHERE,timeinmilliseconds);`
````
    slider.addEventListener('input', wavesurfer.util.debounce(function () {
        wavesurfer.zoom(Number(this.value));
    }, 100)); // run not more often than once in 30 ms
````

**Comment by entonbiba** [comment]
@GianlucaCal here is a working sample with the debounce feature.
http://codepen.io/entonbiba/pen/xgmqmv

**Comment by GianlucaCal** [comment]
@entonbiba Yes thanks, it works flawlessly but my problem is quite different, in fact it's not the zoom slider (still I added a debounce function and it works) but the Timeline plugin! It does huge calculations to rerender the timeline plugin everytime it does a zoom!

**Comment by entonbiba** [comment]
@GianlucaCal yes I added a debounce feature on the timeline plugin on that sample. Do you have the audio file you are using, can you provide a direct link to it so I can test with the sample?

**Comment by GianlucaCal** [comment]
@entonbiba oh that's cool! I have the peaks and the mp3 on dropbox, here is the link: 
https://www.dropbox.com/sh/qt8x9r4wj02ciex/AACRCj1SOozfHotktsGzt6i2a?dl=0

**Comment by entonbiba** [comment]
@GianlucaCal yea the timeline plugin does a lot of calculating which is required for it to update properly. I added the debounce feature to the timeline plugin in the previous example, I'll update the actual plugin soon.

I managed to make your file work successfully with the following setup below. We can probably look into making the timeline render when it's playing smoother. 
````
// change the max value for the slider to 5, this will at least ensure normal zoom and out.
<input id="slider" type="range" min="1" max="5" value="1" />

// set timeInterval to 30
var wavesurfer = WaveSurfer.create({
  container: '#waveform',
  waveColor: '#D2EDD4',
  progressColor: '#46B54D',
  height: 120,
  normalize: true,
  backend: 'MediaElement',
  renderer: 'MultiCanvas',
  pixelRatio:  1,
  timeInterval: 30
});
````
