### ISSUE TITLE
default mp3 from archive.org is offline,

### ISSUE THREAD

**Issue by entonbiba** [katspaugh/wavesurfer.js#970]
@katspaugh @thijstriemstra it seems the audio source that is used on the plugins is offline and not found.

https://ia902606.us.archive.org/35/items/shortpoetry_047_librivox/song_cjrg_teasdale_64kb.mp3 

![image](https://cloud.githubusercontent.com/assets/5193884/22714943/d10a89a4-ed5c-11e6-9f39-50c03b3d02ac.png)

Here are three other samples we can use. Let me know if you're ok with them.

`demo.wav` and `demo.mp3` will be:
**1) The Godfather Theme Song Speak Softly Love**
https://ia800508.us.archive.org/15/items/LoveThemeFromTheGodfather/02LoveThemeFromTheGodfather.mp3

`demo2.wav` and `demo2.mp3` will be:
**2) Beethoven's Symphony No. 9**
https://ia800207.us.archive.org/9/items/BeethovensSymphonyNo.9/BeethovensSymphonyNo.9scherzo.mp

`demo3.wav` and `demo3.mp3` will be:
**3) Mozart Symphony 40**
https://archive.org/download/Mozart_Symphony_40/1_Molto_allegro_vbr.mp3

**Comment by thijstriemstra** [comment]
That sucks. We should have a 404 check as part of the travis build or simply include a file in the repo like we used to have.

**Comment by katspaugh** [comment]
Damn it, they took it down again. Let's choose a short piece of music/spoken word and save it into repo. The Godfather file is 2.6 Mb – this might be OK.

**Comment by thijstriemstra** [comment]
+1

**Comment by entonbiba** [comment]
@katspaugh @thijstriemstra I'll update the demo audio file to a shorter length of "The Godfather". 👍

**Comment by entonbiba** [comment]
@thijstriemstra @katspaugh updated ! I made them 30 seconds long and mastered them.
