### ISSUE TITLE
How can I have the soundwave for my audio file upload gradually rather than wait for the upload bar to finish?

### ISSUE THREAD

**Issue by pedronmarques** [katspaugh/wavesurfer.js#971]
How can I have the soundwave for my audio file upload gradually rather than wait for the upload bar to finish?
As is I have to wait until the upload bar (see images below) finishes for the soundwave to appear and being able to play. 
Possibly I would like to have the soundwave form as it uploads.
I'm linking to a 1hour long mp3 hosted on Archive.org

<img width="697" alt="screen shot 2017-02-07 at 8 02 28 pm" src="https://cloud.githubusercontent.com/assets/9155684/22718832/90ebce1e-ed70-11e6-9405-8a401edfb93e.png">
<img width="801" alt="screen shot 2017-02-07 at 8 03 32 pm" src="https://cloud.githubusercontent.com/assets/9155684/22718831/90eb886e-ed70-11e6-95c5-dd1d40ed9152.png">

**Comment by entonbiba** [comment]
@pedronmarques at the moment no since Web Audio needs the full audio file to decode. You can save the waveform and preload decoded waveform data. `wavesufer.load('audiofile.mp3',[data]);` If you use MediaElement and have the waveform data, preload it and the audio will start playing right away.

Here is an example:
https://wavesurfer-js.org/example/audio-element/ 

It would look something like this.
````
        wavesurfer.load('linktoaudiofile.mp3', [
0.0218, 0.0183, 0.0165, 0.0198, 0.2137, 0.2888, 0.2313, 0.15, 0.2542, 0.2538, 0.2358, 0.1195, 0.1591, 0.2599, 0.2742, 0.1447, 0.2328, 0.1878, 0.1988, 0.1645, 0.1218, 0.2005, 0.2828, 0.2051, 0.1664, 0.1181, 0.1621, 0.2966, 0.189, 0.246, 0.2445, 0.1621, 0.1618, 0.189, 0.2354, 0.1561, 0.1638, 0.2799, 0.0923, 0.1659, 0.1675, 0.1268, 0.0984, 0.0997, 0.1248, 0.1495, 0.1431, 0.1236, 0.1755, 0.1183, 0.1349, 0.1018, 0.1109, 0.1833, 0.1813, 0.1422, 0.0961, 0.1191, 0.0791, 0.0631, 0.0315, 0.0157, 0.0166, 0.0108
        ]);
````

**Comment by pedronmarques** [comment]
Thanks will try it out and get back to you

**Comment by mspae** [comment]
Closing: inactive
