### ISSUE TITLE
Minimap bindWaveSurferEvents changes cause render before buffer available

### ISSUE THREAD

**Issue by dmongrel** [katspaugh/wavesurfer.js#972]
In v1.3.1, the changes to minimap plugin method bindWaveSurferEvents, which are:
`- this.wavesurfer.on('ready', this.render.bind(this));`
`+ this.render();`

Causes a this.buffer.length is undefined warning/error in getPeaks(), as the buffer is not yet ready.  Changing this.render back to the on event, restores functionality.  I will leave it to the author of those changes to fix things, since I don't know the nature of the problem they were trying to fix.

**Comment by entonbiba** [comment]
@dmongrel you should initialize the minimap plugin from the wavesurfer.ready event.

http://codepen.io/entonbiba/pen/ggeGyG?editors=0010

var minimap;
wavesurfer.on('ready', function () {
  minimap = wavesurfer.initMinimap({
    height: 30,
    waveColor: '#ddd',
    progressColor: '#999',
    cursorColor: '#68A93D'
  });
});

**Comment by dmongrel** [comment]
Ah yes, that was the issue--haven't changed that piece of code for 9 mos. so I was still creating outside of the ready function.
