### ISSUE TITLE
Waveform Rendering Problem on Safari

### ISSUE THREAD

**Issue by gorkie** [katspaugh/wavesurfer.js#975]
Hi guys,

I'm having a problem displaying waveform on some browsers.

The waveform is displaying on Chrome, Opera and Firefox browsers. But, it is not displaying on Safari, Safari Mobile, Chrome for iOS etc. browsers. How can I fix this?

For a better understanding of the problem, you can see the atteched images.

<img width="1439" alt="ws_chrome" src="https://cloud.githubusercontent.com/assets/16632488/22738546/83c482b2-ee10-11e6-8d66-027d66d25239.png">

<img width="1439" alt="ws_safari" src="https://cloud.githubusercontent.com/assets/16632488/22738545/83c1f894-ee10-11e6-9cb9-bf1f6a7f3667.png">

You can also browse my Wavesurfer settings here.

`
    

        container: '#waveform',
        waveColor: '#8e8e8e',
        progressColor: '#7FBC65',
        cursorColor: '#8e8e8e',
        height: 96,
        minPxPerSec: 100,
        pixelRatio: window.devicePixelRatio,
        fillParent: !0,
        audioRate: 1,
        barWidth: 1,
        backend: "MediaElement",
        mediaType: "audio",
        scrollParent: false,
        hideScrollbar: true,

    };

    if (location.search.match('normalize')) {
        options.normalize = true;
    }

    if (location.search.match('canvas')) {
        options.renderer = 'Canvas';
    }

    if (location.search.match('svg')) {
        options.renderer = 'SVG';
    }

    //Set song
    wavesurfer.init(options);
    wavesurfer.song = "/assets/song/Preview2.mp3";

    wavesurfer.load(wavesurfer.song, wavesurfer.backend.peaks);
    wavesurfer.drawBuffer();

`

Thank you in advance for your help.

**Comment by entonbiba** [comment]
@gorkie on ios the user will have to initiate the audio play. 

Here's an example where it works on ios.
http://codepen.io/entonbiba/pen/WRyxga

**Comment by gorkie** [comment]
@entonbiba I'm using Safari 10.0.3. There is no problem with playing song. When I press the play button, the song plays. Just does not seem waveform visual.

**Comment by thijstriemstra** [comment]
why are you doing `drawBuffer`?

**Comment by gorkie** [comment]
@thijstriemstra I added for testing, I did not use.

**Comment by entonbiba** [comment]
@gorkie I tested it on the latest ios safari, chrome for mobile ios and it's working fine. May you retry with the latest version 1.3.2 on your end?

**Comment by thijstriemstra** [comment]
closing, no feedback.
