### ISSUE TITLE
Integrate wavesurfer with existing SoundManager2 audio player

### ISSUE THREAD

**Issue by RighteousIdealizedDung** [katspaugh/wavesurfer.js#986]
I have an implementation of wavesurfer with SoundManager2. I use the latter to play and control the audio, the former to show a waveform, from a JSON array, and to capture clicks on the waveform, which I then raise as SoundManager events to change the position of the track. An example is at: https://byta.com/app/public/share/41/7460/23157. The full code is quite complex but the wavesurfer init code for each track is:

                        var waveformDiv = '#waveform_'+ fileID;
                        if (wavesurferObj){
                            wavesurferObj.empty();
                        }
                        wavesurferObj = WaveSurfer.create({
                            container:  document.querySelector(waveformDiv),
                            waveColor: '#d8d7e1',
                            cursorColor:  '#d8d7e1',
                            progressColor: '#ff4d59',
                            barWidth: 4,
                            backend: 'MediaElement',
                        }); 

                        $('.mediaExpand.expanded #fileDiv_' + fileID).find('.waveform').slideDown();    

                        //Set song
                        wavesurferObj.song = soundManagerObj.nowPlaying.url;

                        max = Math.max.apply(Math, wavFormData.data);

                        //Set peaks
                        wavesurferObj.backend.peaks = wavFormData.data.map(function (p) { return (p / max) });

                        //Draw peaks
                        wavesurferObj.drawBuffer();

                        //Start playing after song is loaded
                        wavesurferObj.on("ready", function () {
                            soundManagerObj.nowPlaying.play();
                            wavesurferObj.drawer.unAll();
                            $(wavesurferObj.drawer.container).on('click', progressBarClickHandler);
                        });
                        wavesurferObj.on("error", function (err) {
                            if (preloadedAudio.hasOwnProperty('id_' + fileID)) {
                                preloadedAudio['id_' + fileID].destruct();
                                delete (preloadedAudio['id_' + fileID]);
                                $('#waveform_'+ fileID).empty();
                            }
                            if (currentlyLoading.fileID && currentlyLoading.fileID == fileID){
                                currentlyLoading = {};
                            }
                            getMetaDataAndPlayTrack (fileID, currentSound);
                        });
                        wavesurferObj.load(wavesurferObj.song, wavesurferObj.backend.peaks, 'none');

That works fine. The omission of any call to wavesurferObj.play() prevents WaveSurfer from outputting any sound, but wavesurfer still requests the track from the url to load it. I would like to separate WaveSurfer entirely from any audio functions, use it in "display only" mode, so to speak. We have a HTML5 audio element created by SoundManager available by the time the wavform loads so is there a way to use that and prevent any unnecessary calls to the server?

Many thanks in advance,

Pete

**Comment by thijstriemstra** [comment]
@RighteousIdealizedDung have you checked https://github.com/collab-project/videojs-wavesurfer?

**Comment by RighteousIdealizedDung** [comment]
@thijstriemstra I don't think that helps me. Our issue that we have invested a lot of time in getting audio streaming working well across browsers (which is hard to do!) using SoundManager2. We'd just like to add wavforms to that set-up. We have an audio instance on the page, created by SoundManager2, I would hope that there is a way that WaveSurfer  can use that.

**Comment by katspaugh** [comment]
Instead of the URL of a song, you can `load()` an `<audio>` element (which I assume SoundManager2 is creating somewhere). Also you don't need to set peaks directly and call `drawBuffer`. Just pass them as the second parameter to the `load()` call.

**Comment by RighteousIdealizedDung** [comment]
@katspaugh Thanks for that, it was the info I was looking for. Unfortunately it didn't solve my problem, it seems that SoundManager2 doesn't create an `<audio>` element. I am having to rework my code because of that. Am closing this issue, and thanks again.

**Comment by randal923** [comment]
> Instead of the URL of a song, you can `load()` an `<audio>` element (which I assume SoundManager2 is creating somewhere). Also you don't need to set peaks directly and call `drawBuffer`. Just pass them as the second parameter to the `load()` call.
> 
> So, inspect your HTML, find the audio tag SoundManager2 creates, and create wavesurfer.js like this:
> 
> ```
>                       var wavesurfer = WaveSurfer.create({
>                         container:  document.querySelector(waveformDiv),
>                         waveColor: '#d8d7e1',
>                         cursorColor:  '#d8d7e1',
>                         progressColor: '#ff4d59',
>                         barWidth: 4,
>                         backend: 'MediaElement',
>                     });
>                     var peaks = wavFormData.data.map(function (p) { return (p / max) });
>                     wavesurfer.load(document.querySelector(audioTag), peaks);
> ```

Would it be okay to re-open this issue and talk about how to do it with React and forwardRefs? I created a question on Stackoverflow about this and we can figure how to do this, it can help others in the future.

https://stackoverflow.com/questions/71907215/how-to-integrate-wavesurfer-with-existing-audio-react
