### ISSUE TITLE
v1.3.2 Waveform display problem with timeline

### ISSUE THREAD

**Issue by janjon** [katspaugh/wavesurfer.js#990]
## demo
http://codepen.io/janjon/pen/jyEyMe?editors=1111

**Comment by katspaugh** [comment]
I don't see any problems now. I think the issue was that cdnjs is not immediately putting up package updates.

**Comment by katspaugh** [comment]
Ah, wait. It's borked indeed. The waveform is too small.

**Comment by janjon** [comment]
@katspaugh Thank you for your quick response, are there any new changes to the plot?

**Comment by janjon** [comment]
1.2.8  normal, Problem in 1.3.0

**Comment by katspaugh** [comment]
The change in 1.3.0 was we made MultiCanvas the default. If you set `renderer: 'Canvas'`, it should work.

**Comment by janjon** [comment]
@katspaugh There are problems with timeline, after switching to different files because of the use of `peak ` timeline is always back and forth after the switch can not be displayed

http://codepen.io/janjon/pen/jyEyMe

**Comment by katspaugh** [comment]
Gotcha, thanks @janjon

**Comment by janjon** [comment]
Thank you for your contribution

**Comment by janjon** [comment]
@katspaugh `renderer: 'Canvas'` no effect

**Comment by janjon** [comment]
@katspaugh How to quickly repair，I am more anxious

Thank you

**Comment by thijstriemstra** [comment]
Can someone post a before/after screenshot?

**Comment by janjon** [comment]
@katspaugh how to solve the problem， please

**Comment by janjon** [comment]
@thijstriemstra 
http://codepen.io/janjon/pen/jyEyMe?editors=1111

After upgrading to 1.3.2 waveform can not be displayed properly, 1.2.3 can.
Waveform shows only the front part, incomplete

**Comment by thijstriemstra** [comment]
@janjon what about v2.0.1?

**Comment by thijstriemstra** [comment]
Please try 2.x and report create a new issue if it still exists, any older version is deprecated.
