### ISSUE TITLE
Adding regions dynamically

### ISSUE THREAD

**Issue by manumora** [katspaugh/wavesurfer.js#991]
After audio is ready, I click on a button to add several regions but it doesn't work. Somebody knows what is happening?
Thanks in advance.

`		var seek_regions = function(times){
			for(i=0; i < times.length; i++){
			    wavesurfer.addRegion({
			        start: times[i],
			        end: times[i]+1,
			        color: 'hsla(400, 100%, 30%, 0.1)'
			    });
			}`

**Comment by entonbiba** [comment]
@manumora can you provide the code you are using on codepen?
