### ISSUE TITLE
Minimap plugin does not render complete waveform with large files

### ISSUE THREAD

**Issue by mspae** [katspaugh/wavesurfer.js#994]
In the annotation example you can see that the minimap plugin does not completely render. Apparently it is limited to the currect viewport of the main wave. (Maybe related to peak cache …)

![annot](https://cloud.githubusercontent.com/assets/1044829/22899760/41e77e1a-f22c-11e6-9d14-9b09101e545d.png)

**Comment by entonbiba** [comment]
@mspae can you attach the file here?

**Comment by mspae** [comment]
The online example uses 1.2.7 – try it with the current version locally.

**Comment by mspae** [comment]
Maybe fixed by #1203 or #1198 – needs to be checked once #1203 is merged.
