### ISSUE TITLE
Allow for pre-decoded peaks and peak calculation on the client

### ISSUE THREAD

**Issue by scottt2** [katspaugh/wavesurfer.js#999]
Hey @katspaugh !

First, **thanks so much for this great library**. It and the community around it are just great. Can't star it enough.

To the issue at hand--I have augmented my local copy of WS to allow for pre-decoded peaks to render immediately while the file downloads and then once downloaded, WS decodes on the client and renders, replacing the pre-decoded peaks.

**Question:** I am wondering if this would be a candidate for inclusion in the library itself through the use of an option on WS itself? I currently am using `remoteThenLocalPeaks`, but it can be whatever.

The reason I did this was due to me not seeing a way to have clean zooming with pre-decoded data. As it currently is, once WS has been provided a `peaks` array on `load`, it sticks to that array. As you know, with a zoom event and no pre-decoded `peaks`, WS will recalculate the `peaks` array for high fidelity zooming, increasing the array size as the zoom factor goes up. Without this dynamic recalculation, the user is stuck with some very primitive looking waveforms.

The entire change can be summarized as follows:

1. Add `remoteThenLocalPeaks: false` to the default options.
2. Alter lines https://github.com/katspaugh/wavesurfer.js/blob/master/src/wavesurfer.js#L463-L476 to be:

```javascript
        // If no pre-decoded peaks provided, attempt to download the
        // audio file and decode it with Web Audio.
        // If the remoteThenLocalPeaks is enabled, first render the provided
        // peaks, then switch to using the local render to support zooming.
        if (peaks && !this.params.remoteThenLocalPeaks) { this.backend.setPeaks(peaks); }
        else if(this.backend.supportsWebAudio()) {
            if (peaks && this.params.remoteThenLocalPeaks) { this.backend.setPeaks(peaks); }
            this.getArrayBuffer(url, (function (arraybuffer) {
                this.decodeArrayBuffer(arraybuffer, (function (buffer) {
                    this.backend.buffer = buffer;
                    this.backend.setPeaks(null);
                    this.drawBuffer();
                    this.fireEvent('waveform-ready');
                }).bind(this));
            }).bind(this));
        }
    },
```

I can fork and issue a PR for all this, but I wanted to first do a sanity check with you to see if this is something you think would be useful to include.

Thanks again!
-Tyler

**edit** correct the method in which peaks are passed.

**Comment by mspae** [comment]
Me, I like the idea. :+1:  But maybe we can find a shorter more concise name for the option. Maybe `redecodeOnZoom` or something similiar to describe what the option is actually for.

**Comment by katspaugh** [comment]
Sounds good! 👍 

I suggest naming the parameter `forceDecode`.

Also, the code can be optimized a bit:

```
        if (peaks) this.backend.setPeaks(peaks);

       if ((!peaks || this.params.forceDecode) && this.backend.supportsWebAudio()) {
            this.getArrayBuffer(url, (function (arraybuffer) {
                this.decodeArrayBuffer(arraybuffer, (function (buffer) {
                    this.backend.buffer = buffer;
                    this.backend.setPeaks(null);
                    this.drawBuffer();
                    this.fireEvent('waveform-ready');
                }).bind(this));
            }).bind(this));
        }
```
